marklogic/marklogic-data-hub

data-hub/build.gradle, data-hub/src/main/java/com/marklogic/hub/DataHub.java, data-hub/src/test/java/com/marklogic/hub/DataHubTest.java, data-hub/src/test/java/com/marklogic/hub/HubTestBase.java
changes to make DataHubTest get the rest port from gradle.properties
changes on build.gradle to resolve build issue as suggested by Paxton
=> Data hub unit test fix

quick-start/README.md, quick-start/src/main/java/com/marklogic/hub/config/EnvironmentConfiguration.java, quick-start/src/main/java/com/marklogic/hub/web/controller/BaseController.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/DataHubServerApiController.java, quick-start/src/main/java/com/marklogic/hub/web/form/BaseForm.java, quick-start/src/main/java/com/marklogic/hub/web/form/LoginForm.java, quick-start/src/main/webapp/WEB-INF/pages/directives/header.html, quick-start/src/main/webapp/WEB-INF/pages/login/login.html, quick-start/src/main/webapp/WEB-INF/pages/top/top.html, quick-start/src/main/webapp/WEB-INF/static/app/controllers/loginController.js, quick-start/src/main/webapp/WEB-INF/static/app/directives/headerDirective.js, quick-start/src/main/webapp/WEB-INF/static/app/quickStartApp.js, quick-start/src/main/webapp/WEB-INF/static/app/services/dataHubService.js, quick-start/src/main/webapp/WEB-INF/static/css/quick-start.css
Changes include
1. Fix for https://github.com/marklogic/data-hub-in-a-box/issues/21 to allow getting properties from a file and command line then saving it to a property file after successful login to prepopulate login form for succeeding access to the app
2. Display errors from login if existing
3. Added menu that display the username and a link to logout that removes the saved configuration
Kindly review.
=> Quick Start UI and configuration changes

quick-start/README.md, quick-start/src/main/java/com/marklogic/hub/config/EnvironmentConfiguration.java, quick-start/src/main/java/com/marklogic/hub/service/DataHubService.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/DataHubServerApiController.java, quick-start/src/main/java/com/marklogic/hub/web/form/LoginForm.java, quick-start/src/main/resources/application.properties, quick-start/src/main/webapp/WEB-INF/pages/login/login.html
I added the user plugin directory in setting up the Data Hub. Kindly review.
=> Added user plugin directory in setting up the Data Hub

data-hub/src/test/java/com/marklogic/hub/DataHubTest.java, data-hub/src/test/java/com/marklogic/hub/DomainManagerTest.java, data-hub/src/test/java/com/marklogic/hub/FlowManagerTest.java, data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, quick-start/src/main/java/com/marklogic/hub/factory/DomainModelFactory.java, quick-start/src/main/java/com/marklogic/hub/model/FlowType.java, quick-start/src/main/webapp/WEB-INF/static/top/modal/domainModal.html, quick-start/src/main/webapp/WEB-INF/static/top/modal/flowModal.html
#34 - change CANONICAL and INPUT to lower case
=> #33 - make input and canonical optional

quick-start/src/main/java/com/marklogic/hub/service/DomainManagerService.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/DataHubServerApiController.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/DomainApiController.java, quick-start/src/main/java/com/marklogic/hub/web/form/LoginForm.java, quick-start/src/main/webapp/WEB-INF/static/app/directives/headerDirective.js, quick-start/src/main/webapp/WEB-INF/static/app/directives/spinner.html, quick-start/src/main/webapp/WEB-INF/static/app/directives/spinnerDirective.js, quick-start/src/main/webapp/WEB-INF/static/app/quickStartApp.js, quick-start/src/main/webapp/WEB-INF/static/app/services/dataHubService.js, quick-start/src/main/webapp/WEB-INF/static/css/quick-start.css, quick-start/src/main/webapp/WEB-INF/static/index.html, quick-start/src/main/webapp/WEB-INF/static/login/login.html, quick-start/src/main/webapp/WEB-INF/static/login/loginController.js, quick-start/src/main/webapp/WEB-INF/static/top/domains.html, quick-start/src/main/webapp/WEB-INF/static/top/top.html, quick-start/src/main/webapp/WEB-INF/static/top/topController.js
We made changes in the UI on displaying messages on success and error, adding loading icon for every action so the user will know that a request is in progress, and synching. Kindly review.
=> Quick-start synching, UI changes for messages, loading icon, etc.

data-hub/src/main/java/com/marklogic/hub/Mlcp.java, data-hub/src/main/resources/ml-modules/root/com.marklogic.hub/lib/flow-lib.xqy, data-hub/src/main/resources/ml-modules/root/com.marklogic.hub/mlcp-flow-transform.xqy, data-hub/src/main/resources/ml-modules/root/com.marklogic.hub/plugins/raw.xqy, data-hub/src/main/resources/ml-modules/root/com.marklogic.hub/writers/default.xqy, data-hub/src/test/resources/flow-manager-test/my-test-flow-with-all/content/content.xqy, data-hub/src/test/resources/flow-manager-test/my-test-flow-with-all/headers/headers.xqy, data-hub/src/test/resources/flow-manager-test/my-test-flow-with-all/triples/triples.xqy, data-hub/src/test/resources/flow-manager-test/my-test-flow-with-header/content/content.xqy, data-hub/src/test/resources/flow-manager-test/my-test-flow-with-header/headers/headers.xqy, data-hub/src/test/resources/flow-manager-test/my-test-flow-with-header/triples/triples.xqy, data-hub/src/test/resources/flow-manager-test/my-test-flow1/content/content.xqy, data-hub/src/test/resources/flow-manager-test/my-test-flow1/headers/headers.xqy, data-hub/src/test/resources/flow-manager-test/my-test-flow1/triples/triples.xqy
fixed mlcp run for input flows
=> more changes to the plugin signature

data-hub/src/main/java/com/marklogic/hub/FlowManager.java, data-hub/src/main/java/com/marklogic/hub/service/CancellableTask.java, data-hub/src/main/java/com/marklogic/hub/service/TaskManagerService.java, quick-start/src/main/java/com/marklogic/hub/model/TaskManagerModel.java, quick-start/src/main/java/com/marklogic/hub/service/FlowManagerService.java, quick-start/src/main/java/com/marklogic/hub/service/TaskManagerService.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/FlowApiController.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/TaskManagerApiController.java, quick-start/src/main/webapp/WEB-INF/static/app/services/dataHubService.js, quick-start/src/main/webapp/WEB-INF/static/app/services/modalService.js, quick-start/src/main/webapp/WEB-INF/static/index.html, quick-start/src/main/webapp/WEB-INF/static/top/flows.html, quick-start/src/main/webapp/WEB-INF/static/top/modal/loadDataModal.html, quick-start/src/main/webapp/WEB-INF/static/top/topController.js
changes to support stopping an already running flow
=> Quick start cancel run flow

quick-start/src/main/java/com/marklogic/hub/web/controller/api/DataHubServerApiController.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/EntityApiController.java, quick-start/src/main/resources/static/app/directives/headerDirective.js, quick-start/src/main/resources/static/app/services/dataHubService.js
=> #114 - Return the updated state after deploying the modules to remove the delay

quick-start/src/main/java/com/marklogic/hub/config/EnvironmentConfiguration.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/DataHubServerApiController.java, quick-start/src/main/java/com/marklogic/hub/web/form/LoginForm.java, quick-start/src/main/resources/static/app/directives/headerDirective.js, quick-start/src/main/resources/static/login/login.html
I added both staging and final REST ports in login page and saved them in the properties file. I also cleaned up the properties file keys and included a minor issue in logout. Kindly review.
=> 117 - Add staging and final REST ports in login page

marklogic-data-hub/src/main/java/com/marklogic/hub/DataHubContentPump.java, marklogic-data-hub/src/main/java/com/marklogic/hub/Mlcp.java, marklogic-data-hub/src/main/java/com/marklogic/hub/service/TaskManagerService.java, marklogic-data-hub/src/main/java/com/marklogic/spring/batch/hub/CollectorReader.java, marklogic-data-hub/src/main/java/com/marklogic/spring/batch/hub/FlowWriter.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/FlowApiController.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/TaskManagerApiController.java, quick-start/src/main/resources/static/top/topController.js
Load Data and Run Flow now reports errors to the quick-start user
=> 67 input flow report failure

marklogic-data-hub/src/main/java/com/marklogic/hub/Mlcp.java
=> 142 - Add default collections when loading data using flows

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.hub/lib/flow-lib.xqy, marklogic-data-hub/src/main/resources/scaffolding/conformance/sjs/content.sjs, marklogic-data-hub/src/main/resources/scaffolding/conformance/sjs/headers.sjs, marklogic-data-hub/src/main/resources/scaffolding/conformance/sjs/triples.sjs, marklogic-data-hub/src/main/resources/scaffolding/conformance/xqy/content.xqy, quick-start/src/main/resources/static/app/services/dataHubService.js
=> fixed #158

marklogic-data-hub/src/main/java/com/marklogic/hub/Scaffolding.java, marklogic-data-hub/src/main/java/com/marklogic/hub/ScaffoldingValidationException.java, marklogic-data-hub/src/main/java/com/marklogic/hub/ScaffoldingValidator.java, marklogic-data-hub/src/test/java/com/marklogic/hub/ScaffoldingTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/ScaffoldingValidatorTest.java
Kindly review. The approach is to check for duplicate REST service extensions and transforms inside the plugin directory only.
=> 143 - Added validation for duplicate REST service extensions and transforms.

quick-start/src/main/resources/static/app/directives/headerDirective.js, quick-start/src/main/resources/static/app/quickStartApp.js, quick-start/src/main/resources/static/app/services/dataHubService.js, quick-start/src/main/resources/static/doc/apiDocController.js
This is just for fixing the Jshint errors.
=> Cleanup - Fix Jshint errors

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/DataHubContentPump.java, quick-start/src/main/java/com/marklogic/hub/config/EnvironmentConfiguration.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/DataHubServerApiController.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/FlowApiController.java, quick-start/src/main/resources/static/app/directives/headerDirective.js, quick-start/src/main/resources/static/app/quickStartApp.js, quick-start/src/main/resources/static/app/services/dataHubService.js, quick-start/src/main/resources/static/app/services/modalService.js, quick-start/src/main/resources/static/doc/apiDocController.js, quick-start/src/main/resources/static/top/topController.js
=> 130 - Remember the last input path per flow

examples/healthcare/plugins/entities/Patients/conformance/final/writer/writer.xqy, marklogic-data-hub/src/main/java/com/marklogic/hub/DataHub.java, marklogic-data-hub/src/main/java/com/marklogic/hub/util/HubFileFilter.java, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.hub/lib/flow-lib.xqy
added checks for both types of path separators in regexes
=> fixed #187

quick-start/src/main/resources/static/app/services/modalService.js, quick-start/src/main/resources/static/css/quick-start.css, quick-start/src/main/resources/static/top/modal/loadDataModal.html
Made the changes for Issue #205. Kindly review.
=> 205 - Minor load data improvements

quick-start/src/main/resources/static/app/directives/notificationDirective.js
This will address #192. Kindly review.
=> 192 - Removed automatic closing of notification

marklogic-data-hub/src/main/java/com/marklogic/hub/DataHub.java, quick-start/src/main/java/com/marklogic/hub/factory/EntityModelFactory.java, quick-start/src/main/java/com/marklogic/hub/factory/FlowModelFactory.java, quick-start/src/main/java/com/marklogic/hub/model/EntityModel.java, quick-start/src/main/java/com/marklogic/hub/model/FlowModel.java, quick-start/src/main/java/com/marklogic/hub/service/DataHubService.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/DataHubServerApiController.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/EntityApiController.java, quick-start/src/main/java/com/marklogic/hub/web/form/LoginForm.java, quick-start/src/main/resources/static/app/services/dataHubService.js, quick-start/src/main/resources/static/top/entities.html, quick-start/src/main/resources/static/top/flows.html
Reverts marklogic/marklogic-data-hub#213
=> Revert "fixed #197"

.gitignore, marklogic-data-hub/build.gradle
=> Updates Java Client API dependency to stable build

CONTRIBUTING.md
=> Adds CLA requirement (#361)

_pages/getting-started-2x.md, _pages/how.md, _pages/what.md
I was admiring your tutorial and learning from how you've put this whole thing together.
Unapologetic justifications for my arbitrary suggestions:
- 'Normalize' dates seems confusing when next to 'Denormalizing', which
refers to a different meaning of 'normal' (who gets to say what's normal
anyway?)
- capitalize Envelope when it's the pattern, lower-case when it is a
specific envelope
=> Some typos and suggestions

quick-start/src/main/ui/app/mlcp-ui/mlcp-ui.component.ts
=> Support MLCP fastload

build-docs.sh, marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/util/HubModuleManager.java, marklogic-data-hub/src/main/resources/overview.html, quick-start/src/main/java/com/marklogic/quickstart/AuthConfig.java
this adds a script to generate javadocs and publish them to the docs site.
this fixes issues #212
=> fixed #212

dependencies.md
Adding the list that Paxton put together.
=> adding list of dependencies

examples/performance-sample/build.gradle, marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle
updating ml-gradle version to latest.
=> updating ml-gradle version

quick-start/e2e/page-objects/auth/login.ts, quick-start/e2e/page-objects/entities/entities.ts, quick-start/e2e/specs/auth/authenticated.ts, quick-start/e2e/specs/create/create.ts, quick-start/e2e/specs/index.ts, quick-start/protractor.conf.js
- Add login negative tests
- Add tests on Advanced settings
- Add multiple entities tests
- Add entity remove tests 
- Add different type of properties tests
- Add delete multiple property tests
=> additional tests on login, advanced settings, and entities page

quick-start/src/main/ui/app/select-key-values/select-key-values.component.html
Instead of on update, which is overkill
=> React to changes in the harmonize flow options on blur

quick-start/e2e/page-objects/traceViewer/traceViewer.ts, quick-start/e2e/qa-data/plugins/headersWithOptions.sjs, quick-start/e2e/specs/create/create.ts, quick-start/e2e/specs/run/run.ts, quick-start/e2e/specs/traces/traces.ts, quick-start/protractor.conf.js
These tests have the verification on trace view page for custom content and headers plugin. It also have some more stabilization on the flow page
=> E2E - more traces tests

marklogic-data-hub/src/test/java/com/marklogic/hub/EndToEndFlowTests.java
Added test for input flow using DMSDK
=> Adding test for input flow using DMSDK

marklogic-data-hub/src/test/java/com/marklogic/hub/DebugLibTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/EndToEndFlowTests.java, marklogic-data-hub/src/test/java/com/marklogic/hub/EntityManagerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/ScaffoldingTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/TracingTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/collector/StreamCollectorTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java
Fix for DHFPROD-412. The field cache is invalidated on before every test run
=> Fix for DHFPROD-412, other failing tests

quick-start/src/main/ui/app/search/search.service.ts
Add URI encoding before requesting document contents on Browse Data document details pane.
=> Issue #557 fix

gradle.properties, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, marklogic-data-hub/src/trace-ui/package-lock.json, marklogic-data-hub/src/trace-ui/package.json, quick-start/package-lock.json, quick-start/package.json
=> 3.0.0 versioning update

marklogic-data-hub/src/main/java/com/marklogic/hub/util/MlcpRunner.java
Hi @ayuwono , try out this fix, and see how it works for you.  In the meantime jenkins will give it a shot.
=> Issue #883 quickstart cannnot load delimited text

examples/online-store/plugins/entities/Product/harmonize/Harmonize Products/content/content.sjs
Needed for code consistency in QuickStart tutorial
=> DHFPROD-496 add let variable declarations

quick-start/src/main/ui/app/flows/flows.component.scss
=> Fix tab bar layout issue #798

quick-start/src/main/ui/app/jobs/job-output.component.scss
Fixes #582 - should be reviewed for UX before merging.
=> Fixes #582 - should be reviewed for UX before merging.

quick-start/src/main/ui/app/search/search.service.ts
Now matches other implementations throughout codebase which leverage encodeURIComponent()
=> Rework of fix for issue #557 where URI in request to /doc API

quick-start/src/main/ui/app/entity-modeler/entity-modeler.component.ts
PR with @mhuang-ml change to #578 for the develop branch (already in develop-2.x)
=> Fix for Issue #578

_data/sidenav.yml, _pages/ingest/ingest.md, _pages/ingest/javaclientapi.md, _pages/ingest/mlcp.md, _pages/ingest/quickstart.md, _pages/ingest/rest.md
Update Ingest overview documentation as well as the following subsections:
- QuickStart
- MLCP
- MarkLogic Java Client API
- MarkLogic REST Client API
=> DHFPROD-646 3.x documentation, Ingest

_data/sidenav.yml, _pages/understanding/architecture.md, _pages/understanding/concepts.md, _pages/understanding/flowtracing.md, _pages/understanding/how.md, _pages/understanding/projectstructure.md, _pages/understanding/understanding.md, _pages/welcome.md
Update Understanding DHF overview documentation as well as the following subsections:
Concepts
Organization (renamed from Architecture)
How It Works
Flow Tracing
Project Structure
Adding more intro to How It Works, which could use a review.
Also added inline comments to key sections that were referenced in task but not updated yet.
=> DHFPROD-646 3.x documentation, Understanding

README.md
Added changes to reflect what build steps recently worked for myself and @ayuwono.
=> Update README for docs branch

NOTICES.txt
Updated Legal Notice for 9.0-5 server release timeframe.
=> Updated legal notices

_pages/tutorial/3x/wrapping-up.md
Update old community account link URLs.
=> Fix links in Tutorial Wrapping Up

_pages/tutorial/3x/3x.md
Old link goes to community account.
=> Fix old finished example link

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/scaffold/impl/ScaffoldingImpl.java, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/UpdateHubTaskTest.groovy, quick-start/src/main/java/com/marklogic/quickstart/web/CurrentProjectController.java, quick-start/src/main/ui/app/login/login.component.html, quick-start/src/main/ui/app/login/login.component.ts
Another attempt to satisfy travis.
=> Fix update test develop

README.md
How to build Javadoc pages and how to add those pages to the documentation
=> Add Javadoc info to docs README

_pages/ingest/javaclientapi.md
@sastafford noticed a bug in our instructions for java wrt 3.0  this PR corrects the flow names
=> Update flow docs for Java Client API

quick-start/src/main/ui/app/entities/property.model.ts, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.html, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.ts
Fixes to Pii UI covering issue #996 that follow @wooldridge DHFPROD-497 implementation
=> Fix for #996

marklogic-data-hub/src/server-side/dhf.sjs, marklogic-data-hub/src/server-side/dhf.xqy, marklogic-data-hub/src/server-side/endpoints/collector.xqy, marklogic-data-hub/src/server-side/impl/flow-lib.sjs, marklogic-data-hub/src/server-side/impl/flow-lib.xqy, marklogic-data-hub/src/server-side/transforms/mlcp-flow-transform.sjs, marklogic-data-hub/src/server-side/transforms/mlcp-flow-transform.xqy
I've combed through the server-side errors and made all the calls consistent.    I created anew prefix called "DATAHUB-" for those errors which did not seem to fix into pre-existing categories of RESTAPI errors.  A message file is ready to go into the server too.
=> DHFPROD-401 First pass at rationalizing error calls

quick-start/e2e/page-objects/entities/entities.ts, quick-start/e2e/specs/create/create.ts
Creating a PR to test the PII feature for the quick-start application
Added the following tests:
1) Enable PII property from quickstart UI
2) Toggle PII on a property
3) Check for the persistence of the PII property when logged in a different session
Also, added/updated the locators for the entities
=> DHFPROD-628 Adding quickstart tests for PII property

marklogic-data-hub/src/server-side/impl/flow-lib.sjs
This fixes one test that is failing as a result of error changes.  
Pretty straightforward and id love to merge.
=> Error code catch in sjs flow lib DHFPROD-254

marklogic-data-hub/src/server-side/impl/flow-lib.sjs
I made a basic mistake in changing the logic for tracing errors in the sjs codepath.  I want to let jenkins chew on this pr and see how it goes
=> Another fix to errors

quick-start/package.json, quick-start/src/main/ui/app/app.module.ts, quick-start/src/main/ui/app/listfilter/index.ts, quick-start/src/main/ui/app/listfilter/listfilter.pipe.ts, quick-start/src/main/ui/app/map/map.component.html, quick-start/src/main/ui/app/map/map.component.scss, quick-start/src/main/ui/app/map/map.component.ts
=> Add filter by typing and updates for long property lists

quick-start/src/main/ui/app/entity-modeler/entity-editor.component.html, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.scss, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.ts
* added per-name field validation
* added validation message
* added input field highlight
* added disabling of Save button in the case of invalid form
=> DHFPROD-852: support for property validation for any whitespace character

quick-start/src/main/ui/app/select-list/select-list.component.ts
New message: "Remove the project from the list of projects? Will not remove any project data on disk."
Fixes #1042
=> Update message in remove project dialog

_pages/docs/architecture.md, _pages/docs/docs.md, _pages/ingest/rest.md
A new page that just lists default pages and ports for DHF projects.
=> DHFPROD-848, DHFPROD-847 docs about ports and dbs

quick-start/src/main/ui/app/entity-modeler/choose-collation.component.scss, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.scss, quick-start/src/main/ui/app/entity-modeler/entity-modeler.component.scss, quick-start/src/main/ui/app/entity-modeler/externaldef-dialog.component.scss, quick-start/src/main/ui/app/folder-browser/folder-browser.component.scss, quick-start/src/main/ui/app/login/login.component.scss, quick-start/src/main/ui/app/mlcp-ui/mlcp-ui.component.scss, quick-start/src/main/ui/app/new-entity/new-entity.component.scss, quick-start/src/main/ui/app/new-flow/new-flow.component.scss, quick-start/src/main/ui/app/select-key-values/select-key-values.component.scss
These issues occurred after upgrading to Angular 6. Our MDL library does not currently support Angular 6.
- Remove extra spacing on sides of folder browser
- Adjust bottom border in selected text fields
Fixes #1030
=> DHFPROD-926 fix QuickStart UI style issues

quick-start/src/main/ui/app/jobs/jobs.component.html, quick-start/src/main/ui/app/jobs/jobs.component.ts
Fix for #739 Disable delete jobs dropdown item when no jobs selected.
=> Issue/739 Fix

quick-start/src/main/ui/app/jobs/job-output.component.html, quick-start/src/main/ui/app/jobs/job-output.component.ts, quick-start/src/main/ui/app/ml-error/ml-error.component.html, quick-start/src/main/ui/app/ml-error/ml-error.component.ts
This is a bug fix to handle both issues with the readability of the output & and rendering of the stack within the job details view.
=> Issue #969 Pretty printing added to output

quick-start/src/main/ui/app/jobs/job-output.component.ts, quick-start/src/main/ui/app/jobs/jobs.component.ts
=> Typescript error fix + some other code clean-up

quick-start/e2e/specs/create/create.ts
Added a step to redeploy before creating all the flows to avoid modules not found errors
=> redeploy before creating flows

quick-start/e2e/specs/jobs/jobs.ts
fix verification on jobs dashboard count after jobs and traces db is merged
=> fix verification on jobs dashboard count

quick-start/e2e/qa-data/plugins/contentWithOptions.sjs
This change is to use new custom harmonize content plugin for sku and SKU property. Also using xpath to get the price property
=> e2e using new harmonize content

quick-start/src/main/ui/app/map/map.component.html, quick-start/src/main/ui/app/map/map.component.scss, quick-start/src/main/ui/app/map/map.component.ts, quick-start/src/main/ui/app/search/search.component.html, quick-start/src/main/ui/app/search/search.component.scss, quick-start/src/main/ui/app/search/search.component.ts
Allow user to change the source document URI in the mapping UI.
Add a copy-to-clipboard icon to result items in Browse Data view.
=> DHFPROD-967 change source URI in mapping

quick-start/src/main/ui/app/harmonize-flow-options/harmonize-flow-options.component.ts
Map name now shows up instead of "Create Map" after a map has been created and saved.
=> Temporary fix for #1036 - will require rewrite when new backend in place

quick-start/src/main/ui/app/harmonize-flow-options/harmonize-flow-options.component.ts, quick-start/src/main/ui/app/map/map.component.ts, quick-start/src/main/ui/app/map/map.service.ts
This is a rebase of work from @clockworked247 and @wooldridge onto the main mapping dev branch.
=> Updates to mapping CRUD

quick-start/src/main/ui/app/login/login.component.html
Minor typo fix for DHFPROD-1020 on spelling typo for pre-install check label
=> fix typo on pre-install check label

quick-start/e2e/page-objects/auth/login.ts, quick-start/e2e/page-objects/browse/browse.ts, quick-start/e2e/page-objects/dashboard/dashboard.ts, quick-start/e2e/page-objects/entities/entities.ts, quick-start/e2e/page-objects/flows/flows.ts, quick-start/e2e/page-objects/jobs/jobs.ts, quick-start/e2e/specs/create/create.ts, quick-start/e2e/specs/run/run.ts
Fixed locators to be non positional, wherever possible. Raised a bug to include classes for table elements in quick-start to make the tests completely devoid of position based locators.
There are some test updates to include changes made to locators as well as error handling wrt using expect as compared to some no op code.
=> Locator fixes and test updates

quick-start/src/main/ui/app/app.routes.ts, quick-start/src/main/ui/app/header/header.component.html, quick-start/src/main/ui/app/mappings/index.ts, quick-start/src/main/ui/app/mappings/map.component.html, quick-start/src/main/ui/app/mappings/map.component.scss, quick-start/src/main/ui/app/mappings/map.component.ts, quick-start/src/main/ui/app/mappings/mappings.component.html, quick-start/src/main/ui/app/mappings/mappings.component.scss, quick-start/src/main/ui/app/mappings/mappings.component.ts
Changes to QuickStart mapping UI as described in DHFPROD-1040. Details:
- Added side nav for managing saved maps
- Use child routing for mapping edit view
- Added reset button and popup at save
- Added messaging for case of no source docs
- Made mapping desc and URI editable
=> DHFPROD-1040 QuickStart mapping UI redesign

quick-start/src/main/ui/app/mappings/map.component.html, quick-start/src/main/ui/app/mappings/map.component.scss, quick-start/src/main/ui/app/mappings/map.component.ts, quick-start/src/main/ui/app/mappings/mappings.component.html, quick-start/src/main/ui/app/mappings/mappings.component.ts, quick-start/src/main/ui/app/mappings/new-map.component.html, quick-start/src/main/ui/app/mappings/new-map.component.ts
Add description input field to Create New Mapping dialog
Move pencil edit icon for source editing next to URI
Additional edit interaction fixes
Update no-source-docs messaging
=> DHFPROD-1040 updates to mapping UI

quick-start/e2e/page-objects/appPage.ts, quick-start/e2e/page-objects/mappings/mappings.ts, quick-start/e2e/specs/create/create.ts
Commits include:
* Page objects for Mappings page
* Fix for failed regression tests that look for ng-reflect-model attribute
=> Mappings page-objects DHFPROD-886

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/MappingManagerImpl.java, quick-start/src/main/ui/app/mappings/map.component.ts, quick-start/src/main/ui/app/mappings/mappings.component.ts
=> DHFPROD-1122 Changed initial mapping version to be version 0 instead of version 1

marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/HubProject.java
Fixed Javadocs for HubConfig and HubProject
=> Fixed Javadocs

marklogic-data-hub/src/test/java/com/marklogic/hub/MappingE2E.java, marklogic-data-hub/src/test/resources/e2e-test/mapping/final-es-default.json, marklogic-data-hub/src/test/resources/e2e-test/mapping/final-es-default.xml, marklogic-data-hub/src/test/resources/e2e-test/mapping/final-es-empty.json, marklogic-data-hub/src/test/resources/e2e-test/mapping/final-es.xml, marklogic-data-hub/src/test/resources/e2e-test/mapping/staging-es.json, marklogic-data-hub/src/test/resources/e2e-test/mapping/staging-es.xml
Modified MappingE2E tests and updated keys
=> Modified MappingE2E tests and updated keys

marklogic-data-hub/src/server-side/extensions/scaffold-content.xqy
To get tests going green and resolve the single quote string escape issue
=> DHFPROD-1131 fix to get tests green

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java
=> Trim trailing whitespaces for flow properties file

quick-start/src/main/java/com/marklogic/quickstart/service/MappingManagerService.java, quick-start/src/main/java/com/marklogic/quickstart/web/MappingController.java
=> Respond with 404 in case of mapping not found

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigBuilderImpl.java, quick-start/src/main/java/com/marklogic/quickstart/AuthConfig.java, quick-start/src/main/java/com/marklogic/quickstart/auth/MarkLogicAuthenticationManager.java
fixing #752 - the ssl issue with quickstart
=> fixing ssl not working from quickstart

examples/spring-batch/plugins/entities/customer/input/customerInput/main.xqy, ml-data-hub-plugin/src/test/resources/2x-harmonize-flow/main.sjs, ml-data-hub-plugin/src/test/resources/2x-input-flow/main.sjs
This update was suggested by @dmcassel in the referenced bug.  I am wondering whether it will go through jenkins without complaint -- we must not evaluate this code if it had not broken tests previously.
=> DHFPROD-1183 update dhf import references

_data/sidenav.yml, _pages/docs/architecture.md, _pages/docs/serverside.md
A couple of things to go into docs-develop for 3.1
=> Docs develop

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowImpl.java
Throws relevant error message.
=> DHFPROD-1010 Added error message for invalid properties file

marklogic-data-hub/src/server-side/extensions/scaffold-content.xqy, marklogic-data-hub/src/server-side/impl/flow-lib.sjs, marklogic-data-hub/src/server-side/impl/flow-lib.xqy, marklogic-data-hub/src/test/resources/scaffolding-test/es-harmonize-content.sjs, marklogic-data-hub/src/test/resources/scaffolding-test/es-input-content.sjs
fix handling of xml comments and processing instructions in harmonize flows
=> Dhfprod 872

_pages/docs/serverside.md
Just a one liner for the current docs
=> DHFPROD-1126 fix import link

marklogic-data-hub/src/test/java/com/marklogic/hub/MappingE2E.java, marklogic-data-hub/src/test/resources/e2e-test/mapping/final-es-extranodes.xml, marklogic-data-hub/src/test/resources/e2e-test/mapping/staging-es-extranodes.xml
Fixing test and adding tests for xml docs with comments/processing instructions
=> Fixing test and adding tests for xml docs with comments/processing

quick-start/e2e/specs/create/create.ts, quick-start/src/main/ui/app/entity-modeler/entity-box.component.html, quick-start/src/main/ui/app/entity-modeler/entity-box.component.scss, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.html, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.scss, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.ts
Issue #1144 
Validation now checks to ensure property name is not empty, unique & without spaces.  Also, I updated the e2e test where it checks for error message string.
=> Able to save an entity with duplicate property names

marklogic-data-hub/src/test/java/com/marklogic/hub/MappingE2E.java, marklogic-data-hub/src/test/resources/e2e-test/mapping/final-es-1.json, marklogic-data-hub/src/test/resources/e2e-test/mapping/final-es-1.xml, marklogic-data-hub/src/test/resources/e2e-test/mapping/final-es-empty.json, marklogic-data-hub/src/test/resources/e2e-test/mapping/final-es-empty.xml, marklogic-data-hub/src/test/resources/e2e-test/mapping/final-es-extranodes.xml, marklogic-data-hub/src/test/resources/e2e-test/mapping/final-es.json, marklogic-data-hub/src/test/resources/e2e-test/mapping/final-es.xml, marklogic-data-hub/src/test/resources/e2e-test/mapping/staging-es-extranodes.xml, marklogic-data-hub/src/test/resources/e2e-test/mapping/staging-es.json, marklogic-data-hub/src/test/resources/e2e-test/mapping/staging-es.xml
Fixing MappingE2E test, modifying key files
=> Fixing MappingE2E test, modifying key files

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java, quick-start/src/test/java/com/marklogic/quickstart/service/MappingManagerServiceTest.java
=> Allows whitespace in mapping name

marklogic-data-hub/build.gradle
All I've done is the simple version bump.  Don't merge this PR until we analyze fallout.
=> Upgrade java client api

dependencies.md, examples/data-integration-tests/build.gradle
=> Updated marklogic-client-api to 4.1.0

_pages/docs/architecture.md, _pages/docs/security.md
Some clean up from your commits the other day. It fixes the problem that caused the pages to be unreachable on pubs, plus some formatting issues I noticed.
=> Fix bad permalinks, clean up subsec and table formatting

marklogic-data-hub/src/main/resources/scaffolding/gradle_properties, quick-start/src/main/java/com/marklogic/quickstart/model/HubSettings.java, quick-start/src/main/java/com/marklogic/quickstart/web/ProjectsController.java, quick-start/src/main/ui/app/environment/hub-settings.model.ts, quick-start/src/main/ui/app/login/login.component.html, quick-start/src/main/ui/app/login/login.component.ts
Add Staging Modules, Staging Triggers, Staging Schemas, Final Modules, Final Triggers, and Final Schemas database names to advanced settings. Remove Modules, Triggers and Schemas.
Fixed scaffolding for gradle.properties file
=> DHFPROD-1202 add new database name settings

ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/CreateHarmonizeFlowTaskTest.groovy
Fixing harmonize flow test using mapping. This test fails currently due to 'mlLoadModules' using  force load set to 'false'(DHFPROD-1248)
=> Fixing harmonize flow test using mapping

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/DataHubTest.java
Reverting the supported server versions for 4.0  to 9.0-5 and above
=> Reverting the supported versions to 9.0-5 and above

marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/DataHubInstallTest.java, quick-start/protractor.conf.js
1. Fixed HubTestBase for ssl/ cert auth after the changes
2. added install/uninstall test 
3. fixed typo in protractor.conf.js
=> Fixed HubTestBase, added install/uninstall test and fixed typo

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubAmpsCommand.java
Assigning the modified string to "ampCall"
=> Assigning the modified string to "ampCall"

quick-start/src/main/ui/app/login/login.component.html, quick-start/src/main/ui/app/login/login.component.ts
This PR just updates some links to documentation in preparation for 4.0.0 release.  They wont actually be live until we push docs-develop to docs
=> DHFPROD-1089 links to documentation in quickstart

quick-start/e2e/specs/auth/authenticated.ts
As install and uninstall with custom values are working on this branch, adding this step
=> QS e2e: using custom advanced settings on project init

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/extensions/scaffold-content.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/EndToEndFlowTests.java, marklogic-data-hub/src/test/resources/scaffolding-test/es-harmonize-content.sjs, marklogic-data-hub/src/test/resources/scaffolding-test/es-input-content.sjs
Trying to fix DHFPROD-1309.  Just want to see if this causes any other regression
=> Fixing content generated for input flows with es

marklogic-data-hub/build.gradle, marklogic-data-hub/src/test/java/com/marklogic/hub/util/Installer.java
Including ssl/cert-auth setup/teardown
=> Including ssl/cert-auth setup/teardown

marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/JobManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/impl/JobManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/util/MlcpRunner.java, marklogic-data-hub/src/test/java/com/marklogic/hub/PiiE2E.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/DebugLibTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/HubConfigTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/job/JobManagerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java, marklogic-data-hub/src/test/java/com/marklogic/hub_integration/MappingE2E.java, marklogic-data-hub/src/test/java/com/marklogic/hub_integration/StreamCollectorTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/HubTask.groovy, quick-start/src/main/java/com/marklogic/quickstart/service/JobService.java, quick-start/src/main/java/com/marklogic/quickstart/web/EntitiesController.java, quick-start/src/main/java/com/marklogic/quickstart/web/JobsController.java, quick-start/src/test/java/com/marklogic/quickstart/service/JobServiceTest.java
Updated tests for load balancer properties
=> Changed method signature for loadBalancerHost

_pages/docs/release-notes.md, _pages/understanding/upgrading.md
Changes as per Shannon's latest comments in DHFPROD-1344.
=> DHFPROD-1344 Remove Quickstart as an upgrade path. Mention mlDHFVersion.

marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubDatabaseCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/gradle_properties, ml-data-hub-plugin/gradle.properties
Refactored code to use this property to check if DHF is running in a provisioned environment or not
=> Added mlIsProvisionedEnvironment gradle property

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowManagerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/ScaffoldingTest.java
=> Creating index in jobs db and removing hardcoding in tests

quick-start/src/main/ui/app/select-key-values/select-key-values.component.html, quick-start/src/main/ui/app/select-key-values/select-key-values.component.scss
In QuickStart Harmonize Flow view. Fixes #1120.
=> DHFPROD-1045 fix Options “+” icon alignment

marklogic-data-hub/src/test/java/com/marklogic/hub_integration/StreamCollectorTest.java
=> Fixing StreamCollectorTest

_data/sidenav.yml, _pages/project/dhsdeploy.md
This is probably still not quite right yet, but I figured it'd save us both some time if get the PR up for you to review. Maybe I'll get lucky.
The HTML version is up on pubs.
=> DHFPROD-1261 Add a page about DHS deployment

quick-start/e2e/specs/run/run.ts
verification update on document results count
=> e2e - doc results verification update

_pages/ingest/mlcp.md, _pages/understanding/upgrading.md
A typo in the current docs branch.
=> Typo in upgrade doc about properties

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/HubConfigTest.java
=> Refresh project props before loading new props

marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/HubConfigTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/entity/EntityManagerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowManagerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/ScaffoldingValidatorTest.java
=> Added ability to switch between flowRunnerConfig and adminConfig

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubPrivilegesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/DeployHubPrivilegesTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/UndeployHubPrivilegesTask.groovy
1. Does a custom deployment of privileges and not rely fully on ml-app-deployer
2. Creates privileges only if they aren't present
=> Create privileges only if they aren't present

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/PreinstallCheckTask.groovy
if "safeToInstall" return a message "PreInstall check: [PASSED]"
else
throw TaskExecutionException
=> DHFPROD-1483 : Fixing the hubPreInstallCheck task

quick-start/src/main/ui/app/shared/stories/components/facets/facets.component.stories.ts, quick-start/src/main/ui/app/shared/stories/components/mappings/naw-map-ui.component.stories.ts, quick-start/src/main/ui/app/shared/stories/components/pagination/pagination.component.stories.ts
Add knobs to the following components: facets, new-map-ui, pagination
=> MLUI add knobs functionality

quick-start/src/main/ui/app/shared/stories/components/mappings/new-map-ui.component.stories.ts
Typo in filename. Change naw-map-ui.component.stories.ts to new-map-ui.component.stories.ts.
=> MLUI fix filename new-map-ui story

examples/barebones/README.md, examples/barebones/build.gradle, examples/custom-tokens/build.gradle, examples/custom-tokens/gradle.properties, examples/data-integration-tests/build.gradle, examples/disconnected-project/build.gradle, examples/disconnected-project/gradle.properties, examples/external-security/build.gradle, examples/external-security/gradle-example.properties, examples/gradle-tasks-demo/Readme, examples/gradle-tasks-demo/docs/build.gradle, examples/gradle-tasks-demo/docs/gradle.properties, examples/healthcare/README.md, examples/healthcare/build.gradle, examples/load-binaries/README.md, examples/online-store/README.md, examples/online-store/build.gradle, examples/performance-sample/build.gradle, examples/single-step-ingest/README.md, examples/spring-batch/README.md, examples/spring-batch/build.gradle, examples/ssl/build.gradle, examples/ssl/gradle.properties
* Updated the examples with 4.0.2 version
=> 4.0.2 Example changes

_data/sidenav.yml, _pages/docs/release-notes.md, _pages/faqs.md, _pages/tutorial/2x/modeling-product-entity.md, _pages/tutorial/2x/wrapping-up.md, _pages/understanding/projectstructure.md, _pages/understanding/understanding.md, _pages/understanding/upgrading.md, javadocs/2.0.4/overview-summary.html
Details: https://project.marklogic.com/jira/browse/DHFPROD-1479?focusedCommentId=146677
=> DHFPROD-1479 - Fixed broken links.

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/DataHubInstallTest.java, ml-data-hub-plugin/build.gradle, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/BasicAuthTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/SslTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/TlsTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/BaseTest.groovy
1. Loading value of 'finalSimpleSsl' 
2. fixing typos in property names
3. Fixing gradle plugin ssl/tls tests
4. Creating a task for the full cycle gradle tests
=> Fix for Support Ticket 20961 

marklogic-data-hub/src/test/java/com/marklogic/hub/PiiE2E.java
Change tests to use jackson api instead of gson
=> Using jackson instead of gson in tests

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, ml-data-hub-plugin/build.gradle, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateEntityTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateFlowTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateMappingTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/DeployHubModulesTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/DeployUserModulesTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/ExportJobsTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/HubTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/SaveIndexes.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/UpdateHubTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/UpdateIndexes.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/BaseTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/HubUpdateTaskTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/InstalledTests.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/UpdateIndexesTaskTest.groovy
In this PR,
1. Run gradle plugin tasks in spring context
2. Modify tests to run in spring context (tests ran fine in local)
3. (Re)Include upgrading legacy flows in DataHub.upgradeFlows()
=> Springification of gradle plugin 

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java
=> upgraded ml-app-deployer to ver 3.10.0

quick-start/src/main/ui/app/mlcp-ui/mlcp-ui.component.html, quick-start/src/main/ui/app/mlcp-ui/mlcp-ui.component.scss
Make button alignment consistent with harmonize flow view.
=> DHFPROD-1410 left-align input-flow buttons

quick-start/.gitignore, quick-start/e2e/page-objects/appPage.ts, quick-start/e2e/page-objects/auth/login.ts, quick-start/e2e/page-objects/browse/browse.ts, quick-start/e2e/page-objects/entities/entities.ts, quick-start/e2e/page-objects/flows/flows.ts, quick-start/e2e/page-objects/mappings/mappings.ts, quick-start/e2e/specs/auth/authenticated.ts, quick-start/e2e/specs/create/create.ts, quick-start/e2e/specs/jobs/jobs.ts, quick-start/e2e/specs/mappings/mappings.ts, quick-start/e2e/specs/mappings/typeAhead.ts, quick-start/e2e/specs/run/run.ts, quick-start/e2e/specs/traces/traces.ts, quick-start/e2e/specs/uninstall/uninstall.ts, quick-start/package.json, quick-start/protractor.conf.js
Jenkins jobs on both linux and windows are showing green. This QS e2e implementation is ready to be merged to develop
=> Async/await implementation on QS e2e UI test

_data/sidenav.yml, _pages/glossary.md, _pages/understanding/how.md, _pages/understanding/plugins.md
- DHFPROD-1482 - DHF Glossary - Tech-reviewed by @sbayatpur-ml.
- DHFPROD-1506 Move Plugins wiki page to new docs - Tech-reviewed by @aebadirad.
- sidenav.yml: Added the new topics.
- how.md: Removed comment about needing a detailed plugins topic. Minor spelling and punctuation fixes.
=> New docs topics: glossary and plugins

quick-start/src/main/ui/app/flows/flows.component.ts
See DHFPROD-1411 fix, need to type getFlowType arg as Flow.
=> fix QuickStart type issue in getFlowType()

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
Using the autowired command for installing amps
=> Using the autowired command

marklogic-data-hub/build.gradle, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java
=> Init hub project

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, quick-start/src/main/java/com/marklogic/quickstart/AuthConfig.java
This PR
1. Loads properties from local gradle.properties and not from the one in project
2. create and init proj if required
3. Autowires "authFilter"
=> WIP-Fixing test in spring context

quick-start/build.gradle
=> Making quickstart tests run

quick-start/src/main/ui/app/app.module.ts, quick-start/src/main/ui/app/dashboard/dashboard.component.scss, quick-start/src/main/ui/app/entity-modeler/entity-box.component.html, quick-start/src/main/ui/app/entity-modeler/entity-box.component.scss, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.html, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.scss, quick-start/src/main/ui/app/flows/flows.component.html, quick-start/src/main/ui/app/jobs/jobs.component.html, quick-start/src/main/ui/app/jobs/jobs.component.scss, quick-start/src/main/ui/app/mappings/map.component.html, quick-start/src/main/ui/app/mappings/map.component.scss, quick-start/src/main/ui/app/mlcp-ui/mlcp-ui.component.html, quick-start/src/main/ui/app/mlcp-ui/mlcp-ui.component.scss, quick-start/src/main/ui/app/tooltip/tooltip.directive.README.md
- Add new Bootstrap tooltips for index icons
- Replace existing MDL tooltips with Bootstrap tooltips
- Add help icons to mapping and entities views
- Destination docs page for help icons to come
=> DHFPROD-1426 WIP index tooltips and help icons

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
=> Fix ssl issue

marklogic-data-hub/src/main/java/com/marklogic/hub/collector/impl/CollectorImpl.java, marklogic-data-hub/src/main/resources/dhf-defaults.properties, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/SslTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/TlsTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/BaseTest.groovy
This PR
1. Fixes DHFPROD-1552
2. Fixes the hostname verifier for Collector 
3. Fixes SslTest, TlsTest (SslTest runs fine, Tlstest still has issues)
=> Fix for DHFPROD-1552, failing ssl tests

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubDatabaseCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/HubDeployDatabaseCommandFactory.java
See comments on the DeployHubDatabaseCommand constructor
=> 1561 Fix for ordering database commands

marklogic-data-hub/src/test/java/com/marklogic/bootstrap/DataHubInstallTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/PiiE2E.java
This PR
1. Fixes DataHubInstall test
2. Fixes other test issues. 
Hopefully all tests pass in the next run (except TlsTest)
=> Changing the paths for trigger files, fixing tests

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
DHF wasn't previously doing this, but I think this is intended to be part of the concept of "update the indexes" - i.e. don't spend any time determining if forests need to be created. I think this should be fine for the QuickStart app, where I believe the intent is to update indexes based on entity definitions.
=> 1562 Disabling forest creation when updating indexes

quick-start/src/main/ui/app/entity-modeler/entity-box.component.html, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.html, quick-start/src/main/ui/app/mappings/map.component.html
Target page in documentation has yet to be created.
=> DHFPROD-1426 hide QuickStart help icons

marklogic-data-hub/src/test/java/com/marklogic/hub/core/HubConfigTest.java
Resetting the hubConfig to its default values. Hopefully, tests run fine after this.
=> Resetting the hubConfig to its default values

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
They were technically fine before, but with this approach, they have a description.
=> Fixed how the hub-specific amp tasks are defined

quick-start/e2e/page-objects/browse/browse.ts, quick-start/e2e/page-objects/traces/traces.ts
=> fix regression failure due to locator mismatch

gradle.properties, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, ml-data-hub-plugin/gradle.properties, quick-start/gradle.properties, quick-start/src/main/java/com/marklogic/quickstart/service/EnvironmentConfig.java
Making changes for a '4.1.0-rc1' release
=> Making changes for a '4.1.0-rc1' release

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
Fixes https://project.marklogic.com/jira/browse/DHFPROD-1587
=> do not initialize if project is already initialized

marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle
=> Only QS bootRun should be enabled

marklogic-data-hub/src/test/java/com/marklogic/hub/impl/InitializeConfigDirsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/InitializeModulePathsTest.java
Fixing modules path and config dirs tests in Windows
=> Fixing modules path and config dirs tests in Windows

gradle.properties, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, ml-data-hub-plugin/gradle.properties, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/HubUpdateTaskTest.groovy, quick-start/gradle.properties, quick-start/src/main/java/com/marklogic/quickstart/service/EnvironmentConfig.java
Changing versions to 4.1.0-rc2
=> Changing versions to 4.1.0-rc2

quick-start/src/main/java/com/marklogic/quickstart/auth/ConnectionAuthenticationFilter.java
Fixes DHFPROD-1632
QS now overrides the properties file by the chosen env specific properties file.
=> DHFPROD-1632 Read from the chosen environment

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/GeneratePiiTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/HubTask.groovy
Fixing generatePiiCommand command
=> Fixing generatePiiCommand command

gradle.properties, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, ml-data-hub-plugin/gradle.properties, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/HubUpdateTaskTest.groovy, quick-start/gradle.properties, quick-start/src/main/java/com/marklogic/quickstart/service/EnvironmentConfig.java
=> Updated version to make it compatible with internal Nexus

marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadHubModulesCommandTest.java
Fixing the 'LoadHubModulesCommandTest'
=> Fixing the 'LoadHubModulesCommandTest'

marklogic-data-hub/build.gradle, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/Installer.java, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/SSLsetup.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/PiiE2E.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/HubConfigTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/HubProjectTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadHubModulesCommandTest.java
Trying to run the java api test with ssl/cert-auth
=> Making ssl/cert-auth test work

quick-start/src/main/ui/app/entity-modeler/entity-editor.component.html, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.scss, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.ts
Same as: https://github.com/marklogic/marklogic-data-hub/pull/1686
But onto develop.
=> DHFPROD-1433 make entity editor scrollable

quick-start/build.gradle
Make Spring Boot version consistent
=> Upgrade Spring boot ver for QS

quick-start/src/main/ui/app/shared/components/mappings/map-ui.component.html, quick-start/src/main/ui/app/shared/components/mappings/map-ui.component.ts
This should fix the mapping page issues.
=> DHFPROD-1658 fix mapping view

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/MappingManagerImpl.java
This PR intends to fix issues #1710 , #1709  and #1708 (corresponding JIRA tickets are DHFPROD-1663, 1664, 1665)
=> Fix for DHFPROD-1663, 1664, 1665

marklogic-data-hub/src/main/resources/scaffolding/Entity.json
Including "elementRangeIndex" in the placeholder entity . Fix for https://project.marklogic.com/jira/browse/DHFPROD-1581
=> DHFPROD-1581 fix

quick-start/e2e/page-objects/auth/login.ts, quick-start/e2e/specs/auth/authenticated.ts, quick-start/src/main/ui/app/login/login.component.ts, quick-start/src/main/ui/app/shared/components/login/login-ui.component.html, quick-start/src/main/ui/app/shared/components/login/login-ui.component.ts, quick-start/src/main/ui/app/shared/stories/components/login/login.component.stories.ts
This PR enables the "finished" UI button when percentComplete=100%.
On clicking the button user is redirected to Dashboard
=> Dhfprod 662 qs stuck

quick-start/e2e/specs/mappings/mappings.ts
=> add redeploy to stabilize

ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateEntityTaskTest.groovy, ml-data-hub-plugin/src/test/resources/my-new-entity.entity.json
This PR attempts to update existing plugin test that verifies entity create using hubCreateEntity task.
=> Updating test for DHFPROD-1581

quick-start/e2e/page-objects/auth/login.ts, quick-start/e2e/specs/auth/authenticated.ts, quick-start/src/main/ui/app/login/login.component.ts, quick-start/src/main/ui/app/shared/components/login/login-ui.component.html, quick-start/src/main/ui/app/shared/components/login/login-ui.component.ts, quick-start/src/main/ui/app/shared/stories/components/login/login.component.stories.ts
=> Revert "Dhfprod 662 qs stuck (#1726)"

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/HubConfigTest.java
Fix for https://project.marklogic.com/jira/browse/DHFPROD-1682
Setting content db to final db in the appConfig.
=> Setting content db to final db

marklogic-data-hub/gradle-dhs.properties, ml-data-hub-plugin/gradle-dhs.properties
This PR fixes some diffs seen when running DHF tests in DHS. There still will be some test diffs but those are expected.
=> Updating gradle-dhs.properties to run DHF core tests in DHS

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/extensions/flow.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/extensions/sjsflow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/flow-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/trace-lib.sjs
=> Dhfprod 1667

quick-start/src/main/ui/app/shared/components/mlcp/mlcp-ui.component.html, quick-start/src/main/ui/app/shared/components/mlcp/mlcp-ui.component.scss
Reverts marklogic/marklogic-data-hub#1763
=> Revert "DHFPROD-1428: Improve the usability of text input elements"

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/DeployUserArtifactsTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/BaseTest.groovy
This PR 
1. Fixes LoadUserArtifactsCommand, gradle plugin task
2. Fixes the test
=> Fix LoadUserArtifactsCommand and tests in 4.x

marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/HubProject.java, marklogic-data-hub/src/main/java/com/marklogic/hub/ProcessManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ProcessManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/processes/Process.java, marklogic-data-hub/src/main/java/com/marklogic/hub/processes/ProcessImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/processes/ProcessManagerTest.java, marklogic-data-hub/src/test/resources/scaffolding-test/myTestCustomProcess.processes.json, marklogic-data-hub/src/test/resources/scaffolding-test/myTestIngestProcess.processes.json, marklogic-data-hub/src/test/resources/scaffolding-test/myTestMappingProcess.processes.json, marklogic-data-hub/src/test/resources/scaffolding-test/myTestMappingProcess2.processes.json
* Adds ProcessManager class for handling Processes
* Adds tests for ProcessManager class
=> Dhfprod 1718 process manager

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ProcessManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/processes/ProcessImpl.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/exception/ProcessAlreadyPresentException.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/exception/ProcessNameRequiredException.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateProcessTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/HubTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateProcessTaskTest.groovy
* Add task hubCreateProcess 
* Add test for hubCreateProcess task
=> Dhfprod 1755 hubCreateProcess task

marklogic-data-hub/src/test/java/com/marklogic/hub_integration/MappingE2E.java
Deleting project dir before tests, hopefully this fixes the failing tests
=> Deleting project dir before tests

quick-start/src/main/ui/app/login/login.component.ts, quick-start/src/main/ui/app/shared/components/login/login-ui.component.html, quick-start/src/main/ui/app/shared/components/login/login-ui.component.ts
=> DHFPROD-1726: "Update a Hub Project link" produces error

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
=> Remove amps during uninstall

ml-data-hub-plugin/src/test/resources/tde-template/Order.entity.json
=> Fixing the "Order" entity

quick-start/e2e/specs/uninstall/uninstall.ts
to accommodate windows on jenkins
=> add wait on uninstall for windows

examples/single-step-ingest/src/main/ml-modules/services/run-ingest-harmonize.xqy
Resolving the single step ingest example against the 4.x develop branch
=> Fixing Issue #1810: fixed single-step-ingest example

quick-start/e2e/specs/uninstall/uninstall.ts
to accommodate windows machine on jenkins
=> add wait on uninstall for windows machine

quick-start/src/main/ui/app/shared/components/mappings/map-ui.component.html, quick-start/src/main/ui/app/shared/components/mappings/map-ui.component.ts
This is the same fix that was merged in 4.x-develop branch.
=> DHFPROD-1745 Primary key is not displayed on mapping entity table

marklogic-data-hub/src/main/java/com/marklogic/hub/HubProject.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/HubProjectTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
This PR makes timestamp files env. specific by prefixing the filename with envName.
=> Dhfprod 1760 - env specific timestamp file

marklogic-data-hub/src/main/java/com/marklogic/hub/HubProject.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/HubProjectTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
This PR makes timestamp files env. specific by prefixing the filename with envName
=> Dhfprod 1760 develop

gradle.properties, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, ml-data-hub-plugin/gradle.properties, quick-start/gradle.properties
@aebadirad or @srinathgit  please review and merge only to  4.2.0-rc1
=> update version to be 4.2.0-rc1

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/trace-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/trace-lib.xqy
This PR fixes an issue with success/failure event counters.
=> Fixes #1721, DHFPROD-1680 and DHFPROD-1619 to develop

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/trace-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/trace-lib.xqy
This PR fixes an issue with success/failure event counters.
=> Fixes #1721, DHFPROD-1680 and DHFPROD-1619 to 4.x-develop

quick-start/package.json, quick-start/server.js
Fix to e2e test execution w/ support for running new Express server.
=> e2e test fix to setup Express server when e2e testing + warnings off

marklogic-data-hub/src/main/java/com/marklogic/client/ext/modulesloader/impl/FlowDefModulesFinder.java, marklogic-data-hub/src/main/java/com/marklogic/client/ext/modulesloader/impl/ProcessDefModulesFinder.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java
Deploy mapping artifact to staging db only
=> Deploy process and flow artifacts to the staging db

marklogic-data-hub/build.gradle
=> DHFPROD-1675: Upgrade ml-gradle to version 3.12.0

marklogic-data-hub/build.gradle
=> DHFPROD-1675: Upgrade ml-gradle to version 3.12.0 for 4.x-develop

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/Flow.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java, marklogic-data-hub/src/main/resources/scaffolding/flowName.flow.json, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowManagerTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateFlowTask.groovy
Update the createFlow task to use the new methods
=> DHFPROD-1809 Add getter/setters to flow

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/run-flow-context.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/run-flow-context.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/trace-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/trace-lib.xqy
Porting the 4.x fix into the develop branch to include flow name
=> #1845 port for adding flow names for 4.x

quick-start/src/main/ui/app/app.module.ts, quick-start/src/main/ui/app/app.routes.ts, quick-start/src/main/ui/app/components/manage-flows/flow.model.ts, quick-start/src/main/ui/app/components/manage-flows/index.ts, quick-start/src/main/ui/app/components/manage-flows/manage-flows.component.ts, quick-start/src/main/ui/app/components/manage-flows/manage-flows.service.ts, quick-start/src/main/ui/app/components/manage-flows/ui/index.ts, quick-start/src/main/ui/app/components/manage-flows/ui/manage-flows-ui.component.html, quick-start/src/main/ui/app/components/manage-flows/ui/manage-flows-ui.component.scss, quick-start/src/main/ui/app/components/manage-flows/ui/manage-flows-ui.component.ts
Simple view, model, and service functionality for Manage Flows feature.
=> DHFPROD-1861: Set up Manage Flows

marklogic-data-hub/src/main/java/com/marklogic/hub/collector/Collector.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/RunFlowResponse.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collector.sjs
Convert 'options' to json in collector, fix javadocs and other misc changes
=> Convert 'options' to json in collector, fix javadocs and other misc changes

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubArtifactsCommand.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/DeployHubArtifactsTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/HubTask.groovy
Add LoadHubArtifactsCommand to deploy default steps and flows
Get resource as stream to work in both jar file and via IDE
TODO: Add tests for LoadHubArtifactsCommand
=> Deploy default artifacts

quick-start/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html, quick-start/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.ts
- Messaging for delete flow dialog
- Format numbers in table
- Fix typo
=> Fix content on Manage Flows

quick-start/src/main/ui/app/app.routes.ts, quick-start/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, quick-start/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.ts, quick-start/src/main/ui/app/components/flows-new/manage-flows/manage-flows.component.ts, quick-start/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html, quick-start/src/main/ui/app/components/flows-new/models/flow.model.ts, quick-start/src/main/ui/app/components/flows-new/services/manage-flows.service.ts
- Via getFlow(flowId) service.
- Update Manage Flows name links.
=> DHFPROD-1839: Pass flow into Edit Flow component

quick-start/api/swagger/mocks.json, quick-start/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html, quick-start/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.scss, quick-start/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.ts, quick-start/src/main/ui/app/components/flows-new/models/flow.model.ts
Updates mock data for mapping steps to add targetEntity.
Also fixes handling of status data (i.e., “Never Run” if there is no latest job).
=> Add Target Entity data to Manage Flows table

quick-start/src/main/ui/app/entities/entities.service.ts, quick-start/src/main/ui/app/flows/flows.component.ts, quick-start/src/main/ui/app/mlcp/mlcp.component.ts, quick-start/src/main/ui/app/shared/components/flows/flows-ui.component.html
Improper copying of settings between flows fixed + trash icon delete fix
Fixes:
https://github.com/marklogic/marklogic-data-hub/issues/1858
https://github.com/marklogic/marklogic-data-hub/issues/1879
https://github.com/marklogic/marklogic-data-hub/issues/1877
=> DHFPROD-1879 & DHFPROD-1821 bug fixes

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/RunFlowResponse.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/Job.java
Printing the fullOuput if "options.fullOutput" is set
=> Printing the fullOuput if "options.fullOutput" is set

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/RunFlowResponse.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/Job.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs
Setting 'fullOutput' of type Map and returning 'documents' only if 'fullOutput' is set
=> Setting 'fullOutput' of type Map and returning 'documents' only if 'fullOutput' is set

_pages/release-notes/release-notes-4_2_x-core.md
=> Recommitted DHFPROD-1876 into new branch.

quick-start/api/swagger/mocks.json
Added the JSON in support of Ingest, Mapping & Mastering step types
Farmed Ingest from current develop settings and Mapping JSON from 4.x-develop, since mapping is broken on the develop branch.
Good first cut, but will likely need work next week when I return.   Should be enough for the UI team to get started with their work!
=> DHFPROD-1911 - Swagger updates Ingest, Mapping & Mastering step types

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/collector/EmptyCollectorTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/RunFlowTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/InstalledTests.groovy
Fix for DHFPROD-1919 (plus a test) and DHFPROD-1684
=> Fix for DHFPROD-1919 and DHFPROD-1684

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/flow/impl/LegacyFlowRunnerImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/legacy/collector/EmptyLegacyCollectorTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/RunFlowTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/RunLegacyFlowTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/NotInstalledTests.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/SslTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/TlsTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/InstalledTests.groovy
This PR fixes
1. DHFPROD-1919(and adds a test)
2. DHSPROD-1684
3. Fixes the currently failing tests in 'develop'
4. Fixes response for RunFlowTask . The responses with options.fullOutput set to true looks like
```
{
"jobId": "xsdf",
"flowName": "default-ingest",
"jobOutput": null,
"fullOutput": {
"/sampleOrder.json": {
"content": {
"envelope": {
"headers": {},
"triples": [],
"instance": {
"Order": {
"id": "832",
"price": 15,
"products": [{
"Product": {
"sku": "325353353535",
"title": "sample product 1",
"price": 22,
"categories": ["new", "useful"]
}
}, {
"Product": {
"sku": "1111111111",
"title": "sample product 2",
"price": 50,
"categories": ["boring"]
}
}, {
"Product": {
"sku": "32",
"title": "sample missing price product",
"price": null,
"categories": ["new", "useful"]
}
}]
},
"info": …
```
=> DHFPROD-1919(and adding a test), DHFPROD-1684, fixing response for RunFlowTask

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/ingest/default/main.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/datahub.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/runFlow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/debug.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/invoke-step.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/perf.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/prov.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/step.sjs
- Add performance tracking class
- Reduce the number of times that classes are generated by passing the datahub object around
=> DHFPROD-1927 Add performance metrics

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/ingest/default/main.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/mlcp-flow-transform.sjs
https://project.marklogic.com/jira/browse/DHFPROD-1924
=> DHFPROD-1924: Metadata and options recording (add option.headers)

quick-start/api/swagger/mocks.json, quick-start/src/main/ui/app/components/flows-new/models/merging.data.ts
Added Smart Mastering config data (matching and merging) to Swagger endpoints:
GET  /flows
GET  /flows/{flowId}
PUT  /flows/{flowId}
Also temporarily added a static file for merging data (already one for matching).
=> DHFPROD-1937: Smart Mastering config data for mocks

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs
https://project.marklogic.com/jira/browse/DHFPROD-1924
Not fully functionally now..
{"message":"Error running step: XDMP-DOCNOTFOUND: xdmp.documentPutMetadata(\"1000055\", {createdOn:xs.dateTime(\"2019-03-07T08:36:37.227054-08:00\"), createdBy:\"admin\", createdInFlow:\"default-ingest\", ...}) -- Document not found.","type":"error","currentDateTime":"2019-03-07T08:36:37.224784-08:00","user":"admin","serverID":"5108687386095107457","serverName":"data-hub-STAGING","dbID":"16375177684613873349","dbName":"data-hub-STAGING","modulesDbID":"1766317885932357440","modulesDbName":"data-hub-MODULES"}
=> DHFPROD-1924 - add metadata

quick-start/api/swagger/mocks.json, quick-start/server.js
Restored Swagger doc and server changes in support of interactive server.
=> DHFPROD-1906: Restored changes

quick-start/server.js
You may now return to work...  arg.   Thanks for everyone's patience.
=> Fix for QS loading/login

web/src/main/java/com/marklogic/hub/web/web/CurrentProjectController.java, web/src/main/java/com/marklogic/hub/web/web/JobsController.java, web/src/main/java/com/marklogic/hub/web/web/SearchController.java, web/src/main/java/com/marklogic/hub/web/web/TracesController.java
Changing the scope of the beans to "request"
=> Changing the scope of the beans to "request"

quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/add-match-option-dialog.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/add-match-threshold-dialog.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/match-options-ui.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/match-thresholds-ui.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/ui/run-flow-dialog.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.html, quick-start/src/main/ui/app/components/flows-new/manage-flows/ui/flow-settings-dialog.component.html, quick-start/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html
Completed work on new QA selectors against latest develop.
Evolving document tracking these and future selectors for new UIs here:
https://wiki.marklogic.com/display/ENGINEERING/UI+Selectors+for+Testing
Already rebased off latest develop, so plz merge ASAP.   @bsrikan is also awaiting these changes.
=> DHFPROD-1941: Selectors for QA Testing

build.gradle
@kkanthet ,
I have added a new task that updates version in all hardcoded locations. IS this an acceptable solution ? After running this new task, you will have to commit and push the changes before you start the release process .
=> Update version in hardcoded locations

quick-start/src/main/ui/app/app.module.ts, quick-start/src/main/ui/app/components/flows-new/edit-flow/edit-flow.module.ts, quick-start/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, quick-start/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, quick-start/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts, quick-start/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.scss
Mostly done. TODO:
- Recognize no ingested docs and display messaging
- Currently using buttons inside bottom pane instead of in header
- Add mapping properties above menus per: https://wiki.marklogic.com/display/ENGINEERING/Flow+UI+Design
=> DHFPROD-1816: Integrate mapping config

quick-start/src/main/ui/app/app.module.ts, quick-start/src/main/ui/app/components/flows-new/edit-flow/edit-flow.module.ts, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/match-options-ui.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/match-options-ui.component.scss, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/match-options-ui.component.ts, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/match-thresholds-ui.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/match-thresholds-ui.component.scss, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/match-thresholds-ui.component.ts, quick-start/src/main/ui/app/components/flows-new/models/match-options.model.ts
For weight values in Match Options and Match Thresholds tables.
=> DHFPROD-1679: Edit in place for weights

quick-start/e2e/specs/index.ts
this PR just comments the index file to remove  4.x-quick-start tests
=> remove 4.x quick-start tests

marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepImpl.java, marklogic-data-hub/src/test/resources/scaffolding-test/myTestCustomStep.step.json, marklogic-data-hub/src/test/resources/scaffolding-test/myTestIngestStep.step.json, marklogic-data-hub/src/test/resources/scaffolding-test/myTestMappingStep.step.json, marklogic-data-hub/src/test/resources/scaffolding-test/myTestMappingStep2.step.json
Update test artifacts to better represent the step artifacts
=> Add getter/setters in StepImpl for new fields

quick-start/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/match-options-ui.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/match-thresholds-ui.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.html
In mapping and mastering steps. Removes old MDL buttons.
=> DHFPROD-1816: Fix buttons, layout

marklogic-data-hub/build.gradle
This resolves the compilation issue
=> Adding jdom to the dependencies

CHANGELOG.md
=> DHFPROD-1928: Release/4.2.2

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/ApplicationConfig.java, web/build.gradle, web/package-lock.json, web/src/main/java/com/marklogic/hub/web/AuthConfig.java, web/src/main/java/com/marklogic/hub/web/WebApplication.java, web/src/main/java/com/marklogic/hub/web/WebSocketConfig.java
This should make it so gradle commands now work.
Todo: get web app up and running without the factory bean error
=> DHFPROD-1828: Additional fixes to get gradle working

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/flow-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/flow-lib.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/legacy/flow/LegacyFlowManagerTest.java, marklogic-data-hub/src/test/resources/flow-manager-test/harmonized-with-ns-xml/harmonized1.xml, marklogic-data-hub/src/test/resources/flow-manager-test/harmonized-with-ns-xml/harmonized2.xml, marklogic-data-hub/src/test/resources/flow-manager-test/my-test-flow-ns-xml-sjs/collector.sjs, marklogic-data-hub/src/test/resources/flow-manager-test/my-test-flow-ns-xml-sjs/content.sjs, marklogic-data-hub/src/test/resources/flow-manager-test/my-test-flow-ns-xml-sjs/flow.xml, marklogic-data-hub/src/test/resources/flow-manager-test/my-test-flow-ns-xml-sjs/headers.sjs, marklogic-data-hub/src/test/resources/flow-manager-test/my-test-flow-ns-xml-sjs/main.sjs, marklogic-data-hub/src/test/resources/flow-manager-test/my-test-flow-ns-xml-sjs/triples.sjs, marklogic-data-hub/src/test/resources/flow-manager-test/my-test-flow-ns-xml-sjs/writer.sjs, marklogic-data-hub/src/test/resources/flow-manager-test/my-test-flow-ns-xml-xqy/collector.xqy, marklogic-data-hub/src/test/resources/flow-manager-test/my-test-flow-ns-xml-xqy/content.xqy, marklogic-data-hub/src/test/resources/flow-manager-test/my-test-flow-ns-xml-xqy/flow.xml, marklogic-data-hub/src/test/resources/flow-manager-test/my-test-flow-ns-xml-xqy/headers.xqy, marklogic-data-hub/src/test/resources/flow-manager-test/my-test-flow-ns-xml-xqy/main.xqy, marklogic-data-hub/src/test/resources/flow-manager-test/my-test-flow-ns-xml-xqy/triples.xqy, marklogic-data-hub/src/test/resources/flow-manager-test/my-test-flow-ns-xml-xqy/writer.xqy, marklogic-data-hub/src/trace-ui/package-lock.json
added support for namespaces in function instanceToCanonicalXml/flow:instance-to-canonical-xml in resp. flow-lib.sjs and flow-lib.xqy for data-hub/4 and in function instanceToCanonicalXml in flow-utils.sjs for data-hub/5.
Added tests to LegacyFlowManagerTest
=> Fixing Issue: #1580: added namespace support to harmonize flows.

web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/merging.model.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog.component.ts
=> Fix build errors

marklogic-data-hub/src/main/java/com/marklogic/hub/FlowManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/Job.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/JobStatus.java, marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/LegacyFlowManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/impl/LegacyFlowManagerImpl.java
Incorporating Jos's  PR with some changes
=> DHFPROD-1825:Flowrunner improvements

marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/Step.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepRunnerFactory.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/StepImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/util/json/JSONObject.java
Adds required properties to Step
Adds utility method to getMap from Json Object
Expose method to create staging client using passed DB param
Fixed minor issues
=> DHFPROD-1888: Adds required properties to Step

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, web/src/main/java/com/marklogic/hub/web/service/FlowManagerService.java, web/src/main/java/com/marklogic/hub/web/web/FlowController.java
1. Wiring UI to backend
2.  fixing issue in FLowRunnerImpl
=> Wiring UI to backend, fixing issue in FLowRunnerImpl

web/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/run-flow-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/run-flow-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.ts
I also removed 'redeploy' from edit flow view
=> DHFPROD-2011: Refactor Step and Run Dialog to use FormBuilder

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowStatusListener.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, web/src/main/java/com/marklogic/hub/web/web/FlowController.java
Adding listener and using 'flowName' in the controller
=> Adding listener and using 'flowName' in the controller

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java
@aebadirad ,
I had started with WriteStepRunner last week ,had forgotten to check-in. It is incomplete but has a basic writebatcher in place that reads files from provided location...
=> Create a WriteStepRunner

web/e2e/page-objects/flows/manageFlows.ts, web/e2e/specs/auth/authenticated.ts, web/e2e/specs/flows/index.ts, web/e2e/specs/flows/manage-flows.ts, web/e2e/specs/index.ts
Test and page objects for manage flows.
=> DHFPROD-1872: Tests for manage flows

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/prov.sjs
@ryan321 
Features:
- Added ability to track merge of properties on a merge step through the creation of document property records, merge records and a new document record based on those merge records.
- Added a queue with commit() and discard() features that allow queued provenance records to be committed in a single call or discarded on error. A flag for turning on this feature must be added to the module.
=> DHFPROD-2046: Provenance merge tracking

web/src/main/java/com/marklogic/hub/web/model/StepModel.java, web/src/main/java/com/marklogic/hub/web/service/FlowManagerService.java
Handle some more exceptions
Add detailed error messages
=> Refactor code

marklogic-data-hub/src/main/java/com/marklogic/hub/ApplicationConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/RunFlowResponse.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/Job.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepRunnerFactory.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/StepImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/jobs.sjs, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/RunFlowTask.groovy, web/src/main/java/com/marklogic/hub/web/service/FlowManagerService.java, web/src/main/java/com/marklogic/hub/web/web/FlowController.java
Fixing FlowRunner, service layer and returning responses that UI likes
=> Fixing FlowRunner and service layer

web/e2e/page-objects/flows/manageFlows.ts, web/e2e/specs/flows/manage-flows.ts
Small tweak for manage flows page objects and tests. It seems that some page objects are changed, and some tests need to wait for some elements to show up
=> DHFPROD-1811: update manage flows page object and test

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/flow-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/flow-lib.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java, marklogic-data-hub/src/test/resources/flow-runner-test/harmonized-with-ns-xml/harmonized1.xml, marklogic-data-hub/src/test/resources/flow-runner-test/harmonized-with-ns-xml/harmonized2.xml, marklogic-data-hub/src/test/resources/flow-runner-test/input/employee1.xml, marklogic-data-hub/src/test/resources/flow-runner-test/input/employee2.xml, marklogic-data-hub/src/test/resources/flow-runner-test/my-test-flow-ns-xml-sjs/collector.sjs, marklogic-data-hub/src/test/resources/flow-runner-test/my-test-flow-ns-xml-sjs/content.sjs, marklogic-data-hub/src/test/resources/flow-runner-test/my-test-flow-ns-xml-sjs/flow.xml, marklogic-data-hub/src/test/resources/flow-runner-test/my-test-flow-ns-xml-sjs/headers.sjs, marklogic-data-hub/src/test/resources/flow-runner-test/my-test-flow-ns-xml-sjs/main.sjs, marklogic-data-hub/src/test/resources/flow-runner-test/my-test-flow-ns-xml-sjs/triples.sjs, marklogic-data-hub/src/test/resources/flow-runner-test/my-test-flow-ns-xml-sjs/writer.sjs, marklogic-data-hub/src/test/resources/flow-runner-test/my-test-flow-ns-xml-xqy/collector.xqy, marklogic-data-hub/src/test/resources/flow-runner-test/my-test-flow-ns-xml-xqy/content.xqy, marklogic-data-hub/src/test/resources/flow-runner-test/my-test-flow-ns-xml-xqy/flow.xml, marklogic-data-hub/src/test/resources/flow-runner-test/my-test-flow-ns-xml-xqy/headers.xqy, marklogic-data-hub/src/test/resources/flow-runner-test/my-test-flow-ns-xml-xqy/main.xqy, marklogic-data-hub/src/test/resources/flow-runner-test/my-test-flow-ns-xml-xqy/triples.xqy, marklogic-data-hub/src/test/resources/flow-runner-test/my-test-flow-ns-xml-xqy/writer.xqy, marklogic-data-hub/src/trace-ui/package-lock.json
* Fixing Issue: #1580: added namespace support to harmonize flows.
added support for namespaces in function instanceToCanonicalXml/flow:instance-to-canonical-xml in resp. flow-lib.sjs and flow-lib.xqy for data-hub/4
Added tests to FlowRunnerTest
* Issue #1580 Added test files and adjusted FlowRunnerTest for namespace support
=> DHFPROD-1553: Feature/dhf4 1580 namespace support (#2095)

marklogic-data-hub/src/main/java/com/marklogic/hub/util/json/JSONObject.java
@srinathgit you can use the following code snippet for converting a map to a json string
//option is a Map<String, Object> 
JSONObject jsonObject = new JSONObject();
String optionString = jsonObject.convertMapToJsonString(options);
=> DHFPROD-1885: add utility methods for converting map to json string

marklogic-data-hub/src/main/java/com/marklogic/hub/HubProject.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/scaffold/Scaffolding.java, marklogic-data-hub/src/main/resources/scaffolding/custom-module/main.sjs, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateStepTask.groovy
TODO: Add more information/comments to the template module
=> DHFPROD-1990: Generate template module for steps

web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html, web/src/main/ui/app/components/flows-new/models/flow.model.ts
Updated 'Docs' to 'Records' only.
=> DHFPROD-1995: Manage Flows TODOs

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/StepImpl.java, marklogic-data-hub/src/main/resources/hub-internal-artifacts/flows/default-ingest.flow.json, marklogic-data-hub/src/main/resources/hub-internal-artifacts/flows/default-mapping.flow.json, marklogic-data-hub/src/main/resources/hub-internal-artifacts/steps/ingest/marklogic/default-ingest.step.json, marklogic-data-hub/src/main/resources/hub-internal-artifacts/steps/mapping/marklogic/default-mapping.step.json, marklogic-data-hub/src/main/resources/scaffolding/flowName.flow.json, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowManagerTest.java, marklogic-data-hub/src/test/resources/flow-manager-test/test-flow.flow.json
The other changes surrounding this ticket were already made in the Smart Mastering feature branch. https://github.com/marklogic/marklogic-data-hub/pull/2090/files#diff-5e944b09cf7c5a31ae3bc89610e7b97cR32
=> DHFPROD-2041: Adjust flow scaffolding to put identifier in option

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs
Added fields in createBatch func.
=> DHFPROD-2034: Debug improvement #1: Add host information to Jobs document that helps with debugging

web/e2e/page-objects/flows/editFlow.ts, web/e2e/page-objects/steps/customStep.ts, web/e2e/page-objects/steps/ingestStep.ts, web/e2e/page-objects/steps/mappingStep.ts, web/e2e/page-objects/steps/masteringStep.ts, web/e2e/page-objects/steps/steps.ts
First pass of the page objects. As some of the objects are shared, we will most likely refactor the code to use shared functions. But, some selectors are not identical in pattern (will log for enhancement). There are some TODO lists on some step area. Most of the page objects are covered to get started with UI automation
=> DHFPROD-2060: flow and steps page objects

web/src/main/ui/app/components/jobs-new/jobs.data.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.module.ts, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.scss, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.ts, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.scss, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.ts, web/src/main/ui/app/components/jobs-new/ui/output-dialog.component.html, web/src/main/ui/app/components/jobs-new/ui/output-dialog.component.scss, web/src/main/ui/app/components/jobs-new/ui/output-dialog.component.ts, web/src/main/ui/app/components/jobs-new/ui/status-dialog.component.html, web/src/main/ui/app/components/jobs-new/ui/status-dialog.component.scss, web/src/main/ui/app/components/jobs-new/ui/status-dialog.component.ts
Popups for Jobs and Job Details views. Access via menus and status links.
Also added "View Flow" links in Jobs view menus.
=> DHFPROD-2066: Add output and status details popups

web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/match-options-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-collection-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-option-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-strategy-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-collections-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-options-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-strategies-ui.component.html, web/src/main/ui/app/components/folder-browser/ui/folder-browser-ui.component.html
Step Details:
- Mastering: Merge
- Ingest
- Custom
- Mapping
Documented here:
https://wiki.marklogic.com/display/ENGINEERING/QuickStart+UI+Selectors+for+Testing
=> DHFPROD-2080: More Selectors

web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.ts, web/src/main/ui/app/components/flows-new/services/manage-flows.service.ts
I removed collections endpoint and polling functionality for progress bar for now.
=> DHFPROD-2099: "Run Flow" returns an empty object

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs
added changes in updateBatch func for adding line number and filename in batch doc.
=> DHFPROD-2035: Debug Improvement #2: Add line number/file name information to Jobs document to help with debugging

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/Job.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/JobUpdate.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepRunnerFactory.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/rest-api/lib/extensions-util.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/dmsdk-ingest.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/dmsdk-ingest.xqy
1. Implement 'noBatchWrite' option to stop writing batch docs
2. Adding a new server transform for running dmsdk ingest
3. Fix bug in 'case' statement in StepRunnerFactory, handling cases when first step run fails without job doc created
4. Update java client version
5. Making WriteStepRunner handle options and use them for running
=> DHFPROD-2009: WriteStepRunner

Jenkinsfile, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/main/resources/scaffolding/custom-module/main.sjs, web/api/mocks/data/collections.json, web/api/mocks/data/steps.json, web/src/main/java/com/marklogic/hub/web/model/StepModel.java, web/src/main/ui/app/components/common/info-label/info-label.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/custom/custom.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ingest.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.ts, web/src/main/ui/app/components/flows-new/services/manage-flows.service.ts
- Update mapping step display upon step settings update
- Edit mock collections to match step names
- Rename for consistency: "chosenEntity" -> "targetEntity"
- Fix source setting in new/edited mapping dialog
- Handle no-source-docs case, show messaging
Note that beyond the above updates there are some additional fixes that need to be made to the QuickStart Java middle tier to support the mapping, see:
https://project.marklogic.com/jira/browse/DHFPROD-2106
https://project.marklogic.com/jira/browse/DHFPROD-2107
=> DHFPROD-1816: Mapping configuration step

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/collections.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/collections.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/rest-api/lib/extensions-util.xqy, web/src/main/java/com/marklogic/hub/web/service/CollectionsService.java, web/src/main/java/com/marklogic/hub/web/web/CollectionsController.java
- Adds Resource Service Extension for querying collections in the specified database
- Adds controller and service for web service endpoint
=> DHFPROD-2137: Add collections endpoint

web/e2e/page-objects/jobs/jobDetails.ts, web/e2e/page-objects/jobs/manageJobs.ts
The first cut for jobs view and job details page objects. We will need to update it later as the jobs selectors are finalized. This first cut is enough to get the UI automation going.
=> DHFPROD-2113: add page objects for new jobs view

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, web/src/main/java/com/marklogic/hub/web/model/CTSSearchQuery.java, web/src/main/java/com/marklogic/hub/web/service/SearchService.java, web/src/main/java/com/marklogic/hub/web/web/SearchController.java, web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog.component.ts, web/src/main/ui/app/components/search/search.service.ts
- Merge feature branch with latest develop work
- Handle source query definitions for mapping (hit new ctsSearch endpoint)
- Set default database type to avoid some errors with mock data
This should get all the features for the mapping step working. Would like to merge this feature branch into develop ASAP.
=> DHFPROD-1816: Mapping step updates

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/scaffold/Scaffolding.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/StepImpl.java, marklogic-data-hub/src/main/resources/scaffolding/defaultFlow.flow.json, marklogic-data-hub/src/main/resources/scaffolding/flowName.flow.json, marklogic-data-hub/src/test/resources/master-test/flows/myNewFlow.flow.json, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateFlowTask.groovy
hubCreateFlow will create a flow with all default steps unless specified not to using "noDefaultSteps" parameter
=> DHFPROD-2075: Create flow with all default steps unless specified not to

web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.html
See:
https://wiki.marklogic.com/display/ENGINEERING/QuickStart+UI+Selectors+for+Testing
=> DHFPROD-2159: Completed addition of Jobs list and details selectors

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/collector/impl/CollectorImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/collector/impl/FileCollector.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowStatusListener.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/RunFlowResponse.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/Job.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/JobStatus.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/JobUpdate.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepRunnerFactory.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepStatusListener.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/rest-api/lib/extensions-util.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/dmsdk-ingest.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/dmsdk-ingest.xqy
This PR contains
1. DMSDK ingestion 
2. Fixes to Flowrunner(writing job outputs to job doc, fixing an issue in jobs.sjs, add more info to flow status listener)
=> DHFPROD-2009:DMSDK ingest/ FlowRunner fixes

web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-option-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-option-dialog.component.scss, web/src/main/ui/app/components/flows-new/manage-flows/ui/flow-settings-dialog.component.html, web/src/main/ui/app/components/flows-new/manage-flows/ui/flow-settings-dialog.component.scss
Updated New Flow and New Match Option (Reduce type) dialogs.
Screenshots here: https://project.marklogic.com/jira/browse/DHFPROD-2143
=> DHFPROD-2143: Make Add/Remove buttons consistent

web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.ts
Fixes issue with tab selection when the container is not rendered yet due to Angular Material bug https://github.com/angular/material2/issues/7006
=> DHFPROD-2140: Fix Mastering tab selection

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/StepDefinitionManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepRunnerFactory.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collector.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/dmsdk-ingest.sjs
Changes to Flow, Step Runner and enode due to model change
=> Changes to Flow, Step Runner and enode due to model change

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs
Fail at the document level, instead of the batch level and track the completed/failed items.
=> DHFPROD-2104: Store detailed information in job batch docs

web/e2e/page-objects/jobs/jobDetails.ts, web/e2e/page-objects/jobs/manageJobs.ts
Update jobs page objects after latest fix on the selectors
=> DHFPROD-2160: Update jobs page objects

web/src/main/ui/app/components/flows-new/manage-flows/manage-flows.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.ts
Make it work on Manage Flows page. Reuse deployService.redeployUserModules().
=> DHFPROD-2147: Redeploy button

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepDefinition.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepRunnerFactory.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/IngestionStepDefinitionImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/MasteringStepDefinitionImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/hub-internal-artifacts/steps/ingestion/marklogic/default-ingestion.step.json, marklogic-data-hub/src/main/resources/hub-internal-artifacts/steps/mastering/marklogic/default-mastering.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/prov.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/step.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/dmsdk-ingest.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/step/StepDefinitionManagerTest.java, web/src/main/java/com/marklogic/hub/web/service/FlowManagerService.java
Rename stepdef names, fix job status and stop() method
=> Rename stepdef names, fix job status and stop() method

web/api/mocks/data/steps.json, web/api/swagger/mocks.json, web/api/swagger/mocks.yaml
=> DHFPROD-2170: Updated Swagger and Mock data to match property changes

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/prov.sjs
TODO: Check with @clockworked247 regarding 
`createStepRecord` function
=> Add stepName and stepDefinition to prov

marklogic-data-hub/src/main/java/com/marklogic/hub/step/AbstractStepDefinition.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/MasteringStepDefinitionImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/runFlow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowManagerTest.java
Change 'identifier' to 'sourceQuery'
=> Change 'identifier' to 'sourceQuery'

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/prov.sjs
Fix prov bug (passing the step name to createStepRecord() method and passing all the params to _create' + capitalizedStepType + 'StepRecord method
=> Fix prov bug

web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.scss, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.scss, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.ts, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.scss, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.ts
Address consistency and functionality for job info appearing across UI views in prep for jobs data coming from back end.
Affects: Manage Flows, Edit Flow, Jobs, Job Details
- Format status, capitalize first word (e.g.: “Finished with errors”)
- Right-align numeric values (Jobs, Committed, Failed) in table columns
- Make column header labels consistent (“Committed”, “Failed”)
- Cross link job and record info (not all links work, awaiting backend integration and document tagging with job IDs)
- Friendly timestamp display across views (“3 months ago”)
Had to hack some capitalization with lodash as CSS/Angular weren't cooperating. Also slightly rounded step-container corners.
=> DHFPROD-2173: Jobs info update

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubArtifactsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/step.sjs, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/DeployHubArtifactTaskTest.groovy
TODO: Change folder structure for hub-internal-artifacts (steps -> step-definitions)
=> Change collection uri to have step-definition in it

web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.scss, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.ts
Copy of https://github.com/marklogic/marklogic-data-hub/pull/2245, trying to appease Jenkins.
=> DHFPROD-2145: Reset button for jobs filters

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java, marklogic-data-hub/src/main/resources/scaffolding/defaultFlow.flow.json
Updated steps in the default flow
=> Use the name supplied by the user

web/src/main/ui/app/components/entity-modeler/entity-box/entity-box.component.scss, web/src/main/ui/app/components/entity-modeler/entity-modeler.component.html, web/src/main/ui/app/components/entity-modeler/entity-modeler.component.ts, web/src/main/ui/app/components/resizable/resizable.component.scss
fixing broken link arrows between boxes
=> fixing janky border on entity modeler

web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.ts
TODOs: 
Mapping step doesn't work ( no search endpoint with mock )
Manage flow view is working with previous Flow mock data. (needs to updated)
=> DHFPROD-2175: Update UI against new Mock API data ( Edit Flow View)

web/api/mocks/data/flows.json, web/api/mocks/data/jobs.json, web/src/main/ui/app/components/flows-new/manage-flows/ui/step-icons-ui.component.html, web/src/main/ui/app/components/flows-new/manage-flows/ui/step-icons-ui.component.scss
Flows:
steps -> object property "type" -> "stepDefinitionType"
"stepDefinitionType" value is now uppercase
Jobs:
"timeStarted" -> "startTime"
"timeEnded -> "endTime"
UI Updates:
Manage Flow table view - type icons
"docsCommitted" -> "recordsCommitted"
"docsFailed" -> "recordsFailed"
=> DHFPROD-2187: final updates to mock structures to reflect server

web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html
Fix for error:
ERROR TypeError: Cannot read property 'outlets' of null
=> DHFPROD-2196: fix to router error

marklogic-data-hub/src/main/java/com/marklogic/hub/step/AbstractStepDefinition.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/CustomStepDefinitionImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/IngestionStepDefinitionImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/MappingStepDefinitionImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/MasteringStepDefinitionImpl.java
Add keys to fileLocations object
=> Fix empty collection issue

web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.html
Tooltip described different setting so removed. Added "Optional" label as text input hint.
=> DHFPROD-2200: Remove tooltip, add optional label

marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, web/src/main/java/com/marklogic/hub/web/web/CurrentProjectController.java
Scaffold folders for entities and mappings dirs
=> DHFPROD-2203: Add watcherService to entities, flows and step-definitions

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts, web/src/main/ui/app/components/flows-new/models/custom-options.model.ts, web/src/main/ui/app/components/flows-new/models/mapping-options.model.ts, web/src/main/ui/app/components/flows-new/models/mastering-options.model.ts
I also fixed custom step created  DHFPROD-2189
=> DHFPROD-2209: Source collection information needs to be persisted by the back end for steps

marklogic-data-hub/src/main/java/com/marklogic/hub/step/AbstractStepDefinition.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepDefinition.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/Step.java, web/src/main/java/com/marklogic/hub/web/model/StepModel.java
Also fixed the batchSize and threadCount field being 0 in custom step
now they are null if not set from the UI
=> DHFPROD-2215: Fix modulePath not getting updated for custom step

web/e2e/specs/index.ts
Commented out the tests while fixing so CI can run for this time. We'll focus on E2E manual tests first
=> Commented out flows until selectors are fixed

web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.html, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html
Added tooltips in the edit-flow page as per the review in PR for feature/DHFPROD2174 branch.
=> DHFPROD-2174: Add descriptions as mouseover titles for flow, step name

web/src/main/ui/app/components/jobs-new/job-details.component.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.component.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.service.ts, web/src/main/ui/app/components/jobs-new/models/job.model.ts, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.ts, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.ts
I don't think pagination and filtering are setup yet for job details view.
=> DHFPROD-2216: Connect Jobs Endpoints to UI

web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/match-options-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/match-thresholds-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-collections-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-options-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-strategies-ui.component.html, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.html
Already reviewed with @ayuwono, update pagination values.
5, 10, 25, 50 (default 10)
Tables:
Manage Flows
Jobs
Job Details
Match Options
Match Thresholds
Merge Options
Merge Strategies
Merge Collections
=> DHFPROD-2236: Update pagination values for tables

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog.component.ts
Fix error when there are no steps and you are creating a step that wants collections.
Handle “no steps” case in addStepsToCollections().
=> DHFPROD-2225: Fix collections retrieval

web/src/main/ui/app/components/jobs-new/models/job.model.ts, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.ts, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.ts
- Display missing values (except for step times in Job Details view — no times being returned from back end currently)
- Fix filter menus
- Adjust humanized duration to display more times in actual seconds
- Update model to handle zero number values
=> DHFPROD-2238: Fix job views errors

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/gradle_properties
@aebadirad staging, final and job ports were enclosed in quotes. Not sure if that was intentional. I have removed them. Please review and let me know if I should switch it back.
=> DHFPROD-2265: Adding flow-developer-role to modulePermissions

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java
Handle windows paths during ingestion. For C:\\Documents\\abc.json will be converted to /c/Documents/abc.json
=> DHFPROD-2009:Handle windows paths during ingestion

web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.scss
Target entity data is missing from jobs payloads. Adjust Job Details UI to address this, see: https://project.marklogic.com/jira/browse/DHFPROD-2270
=> DHFPROD-2270: Adjust Job Details summary since no target entity

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.ts, web/src/main/ui/app/components/flows-new/validators/new-step-dialog.validator.ts
fix new step dialog validation + small clean-up for incorrect properties from before 2096 prop name changes.
=> DHFPROD-2194: fix new step dialog validation

web/src/main/java/com/marklogic/hub/web/service/DataHubService.java
include 'loadHubArtifactsCommand' to installUserModules()
=> DHFPROD-2276: include 'loadHubArtifactsCommand' to DataHubService.installUserModules()

web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.ts
Includes progress bar fix for DHFPROD-228
=> DHFPROD-2269: Unable to run multiple steps at one time

ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/CreateHarmonizeFlowTaskTest.groovy, ml-data-hub-plugin/src/test/resources/my-new-mapping-1.mapping.json
=> DHFPROD-2284: Fixing failed gradle test

web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts
removed the jobs database as an option
=> DHFPROD-2122: Display the correct available source databases in the UI

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, web/src/main/java/com/marklogic/hub/web/service/FlowManagerService.java
Flow status of other non-running flows were wrongly updated for the case when a flow is running on the Flow page and we switch back to Manage Flows page...
=> DHFPROD-2268: Flow status of other non-running flows were wrongly updated

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java
Set the format of the first step's start time same as the others
=> DHFPROD-2261: Set the format of the first step's start time same as the others

web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/manage-flows.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html
There's currently an issue where latestJob object doesn't return 'finished.' It gets stuck at 'completed step #'
=> DHFPROD-2300: fixed bugs for running from manage flow view

web/src/main/java/com/marklogic/hub/web/service/EnvironmentConfig.java
=> Change SNAPSHOT to rc1

web/src/main/java/com/marklogic/hub/web/service/FlowManagerService.java
TODO: We should standardize on the exceptions.
=> DHFPROD-2339: Throw error on changing flow name and step name/type

web/src/main/java/com/marklogic/hub/web/service/NewJobService.java
https://project.marklogic.com/jira/browse/DHFPROD-2351
=> DHFPROD-2351: Jobs page return 500 error

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts
For details, see: https://project.marklogic.com/jira/browse/DHFPROD-2350
=> DHFPROD-2350: Do not save map on initial loading

web/src/main/java/com/marklogic/hub/web/service/NewJobService.java
=> Fix job bug when fixed DHFPROD-2351

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts
https://drive.google.com/file/d/1fVJk8VmzspnF36ftY-F8_xEP-oomCWnB/view
=> DHFPROD-2281: required field indicators removed from new custom step

web/src/main/java/com/marklogic/hub/web/service/FlowManagerService.java
Depends on PR https://github.com/marklogic/marklogic-data-hub/pull/2382 to work correctly.
=> DHFPROD-2318: Generate custom module for custom step

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts, web/src/main/ui/app/components/flows-new/models/step.model.ts, web/src/main/ui/app/components/flows-new/validators/new-step-dialog.validator.ts
https://drive.google.com/file/d/1pGt-_pzcQERtPKnlUg_mTLfr6LotgvBg/view
Will need to be rebased after https://github.com/marklogic/marklogic-data-hub/pull/2385 is merged.
=> DHFPROD-2279: Validation for collection vs query fixes

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/util/HubFileFilter.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java, marklogic-data-hub/src/test/resources/flow-runner-test/flows/testFlow.flow.json
This PR
1. Checks for flow stop-on-error and sets the status correctly
2. Adds a test for the same
3. Add artifacts to correct writesets in LoadArtifactsCommand
4. Stop writing step and flow docs to data-hub-MODULES
=> DHFPROD-2359:Fix stop-on-error status for flow and other minor bugs

web/src/main/ui/app/app.module.ts, web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/manage-flows.component.ts, web/src/main/ui/app/components/jobs-new/services/running-job-service.ts
For Manage Flow view and Edit Flow View
=> DHFPROD-2241: Update Run endpoint polling in Quickstart

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/Flow.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/Step.java, web/src/main/java/com/marklogic/hub/web/model/MappingModel.java, web/src/main/java/com/marklogic/hub/web/model/StepModel.java, web/src/main/java/com/marklogic/hub/web/service/FlowManagerService.java, web/src/main/java/com/marklogic/hub/web/service/MappingManagerService.java, web/src/main/java/com/marklogic/hub/web/web/FlowController.java, web/src/test/java/com/marklogic/hub/web/service/MappingManagerServiceTest.java
https://project.marklogic.com/jira/browse/DHFPROD-2330
It also fixed https://project.marklogic.com/jira/browse/DHFPROD-2350 on the server side (save with a new version only if the mapping configuration gets changed).
=> DHFPROD-2330: Avoid unnecessary saving when managing steps in a flow

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/ui/flow-settings-dialog.component.ts
Disabled being able to edit a flow name. Disabled the ability to edit step name and change step type when editing ( server-side adds step type to suffix of name for id )
=> DHFPROD-2332: QuickStart GUI Inconsistencies when renaming flows

web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts
Also fixed DHFPROD-2329: Remove flow from inside the flow doesn't redirect to the manage flow view.
=> DHFPROD-2325: Wrong step ordering when creating a new step with existing 2 or more steps

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts
I get a 404 error response when I try to edit and save a custom step. I created JIRA ticket DHFPROD-2401 to track it. https://project.marklogic.com/jira/browse/DHFPROD-2401
=> DHFPROD-2390: Extra fields and inconsistency on step's edit settings

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowImpl.java
TODO: We should probably use something like this https://github.com/marklogic/marklogic-data-hub/blob/557495b05115f2c9668b866209f3f71d2f7821a2/web/src/main/java/com/marklogic/hub/web/service/FlowManagerService.java#L361
so as not to update the file when we add new step-def types.
=> DHFPROD-2401: Add Custom step type

web/e2e/page-objects/entities/entities.ts, web/e2e/specs/create/create.ts, web/e2e/specs/entities/entity.ts, web/e2e/specs/entities/index.ts, web/e2e/specs/index.ts, web/e2e/specs/scenarios/simpleJson.ts, web/protractor.conf.js
For this task, I reused some of the old test code and added new cases. Please help me test this change on Jenkins.
=> DHFPROD-2354: e2e tests for entity tab.

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, web/src/main/java/com/marklogic/hub/web/auth/ConnectionAuthenticationFilter.java
https://project.marklogic.com/jira/browse/DHFPROD-2414
=> DHFPROD-2414: QS somehow persists previously used data-hub name

web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ingest.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts
=> DHFPROD-2373: After ingestion step creation, the step clears up database name when user uses custom database name

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs
write functions now return information about the transaction and it is stored in the job batch document.
=> DHFPROD-2435: Accurate write tx and dateTime

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java
DHFPROD-2428:Set ext to xml if outputFormat is xml, json otherwise for CSV ingestion
=> DHFPROD-2428:Set ext to xml if outputFormat is xml, json otherwise for CSV ingestion

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java
Change the "datahubCreatedBy" user to the one writing the documents
=> DHFPROD-2456:Change the "datahubCreatedBy" user to the one writing the documents

marklogic-data-hub/src/main/java/com/marklogic/hub/entity/DefinitionType.java, web/src/main/java/com/marklogic/hub/web/model/entity_services/DefinitionType.java, web/src/main/ui/app/models/definition.model.ts, web/src/main/ui/app/models/entity.model.ts
I tested this out manually - just needed the namespace/namespacePrefix properties in the various model classes.
=> DHFPROD-2427: Added namespace and namespacePrefix to entity model

web/e2e/specs/flows/manage-flows.ts
Modify outdated test method name to fix the storybook compilation error
=> Fix storybook compilation error

web/src/main/java/com/marklogic/hub/web/service/FlowJobService.java, web/src/main/java/com/marklogic/hub/web/service/FlowRunnerChecker.java
https://project.marklogic.com/jira/browse/DHFPROD-2453
Expected:
The docs committed count should match the docs ingested
=> DHFPROD-2453: total counter problem for multiple steps

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/RunFlowTask.groovy
Fixing variable assignments and passing 'failHard' to StepRunners
=> DHFPROD-2483: Fixing variable assignments and passing 'failHard' to StepRunners

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/util/json/JSONObject.java
=> DHFPROD-2453: Overloading method with option to allow null values

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/RunStepResponse.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/hub-internal-config/databases/job-database.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/step.sjs, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/RunFlowTask.groovy, web/e2e/specs/scenarios/simpleJson.ts, web/src/main/java/com/marklogic/hub/web/model/FlowStepModel.java, web/src/main/java/com/marklogic/hub/web/service/FlowJobService.java, web/src/main/java/com/marklogic/hub/web/service/FlowManagerService.java, web/src/main/java/com/marklogic/hub/web/service/FlowRunnerChecker.java, web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/manage-flows.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.ts, web/src/main/ui/app/components/jobs-new/services/running-job-service.ts
=> DHFPROD-2461: fix to manage flows accurately showing information

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java
Cherrypicking commits  from develop to release branch
=> DHFPROD-2501: If 'uris'is null and job is stopped return the response immediately

web/src/main/ui/app/components/flows-new/manage-flows/manage-flows.component.ts, web/src/main/ui/app/components/header/ui/header-ui.component.html, web/src/main/ui/app/components/jobs-new/job-details.component.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.component.ts, web/src/main/ui/app/components/jobs-new/services/running-job-service.ts, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.ts, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.ts
There is a bug that requires server side changes where individual step status does not get updated. I created JIRA ticket for that https://project.marklogic.com/jira/browse/DHFPROD-2549.
I also added the space in the header for jobs (https://project.marklogic.com/jira/browse/DHFPROD-2527)
=> DHFPROD-2378: Use running job service for Job and Job Detail View

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/jobs.sjs
Setting the 'stepResponse' to running when starting step execution
=> DHFPROD-2549: Setting the 'stepResponse' to running when starting step execution

marklogic-data-hub/build.gradle, marklogic-data-hub/src/installer/logback.xml, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/Installer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/InstallerTest.java
See the comments in Installer for how to build and run it. 
Also removed the "main" method from ApplicationConfig as I don't believe there's any use case for it.
=> DHFPROD-2546: Can now install/upgrade DHF via an executable jar

web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-option-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-option-dialog.component.ts
=> DHFPROD-2528: Disable Strategy option if no strategies

web/src/main/java/com/marklogic/hub/web/service/FlowJobService.java
https://project.marklogic.com/jira/browse/DHFPROD-2526
=> allow multiple stale states recovery

web/src/main/ui/app/components/common/common.module.ts, web/src/main/ui/app/components/common/spinner/spinner.component.scss, web/src/main/ui/app/components/common/spinner/spinner.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/manage-flows.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.ts, web/src/main/ui/app/components/jobs-new/job-details.component.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.component.ts, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.ts, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.ts
Added indeterminate progress bar.
=> DHFPROD-2271: Some lags on loading flows and jobs if you have a lot of them

web/e2e/page-objects/browse/browse.ts, web/e2e/page-objects/flows/editFlow.ts, web/e2e/page-objects/steps/masteringStep.ts, web/e2e/qa-project/input/advantage/cust1003.json, web/e2e/qa-project/input/bedrock/bedrock_customers.csv, web/e2e/specs/scenarios/multiFlows.ts, web/e2e/specs/scenarios/simpleJson.ts
This PR:
- Expand tests that will match and merge documents based on zip code algorithm
- Verify tests results based on exact and zip match and merge
- Update page objects
- Cleanup and stabilize tests
Need to merge this manually as it doesn't have DHFPROD id
=> E2E UI Automation - match and merge with zip code

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/rest-api/lib/extensions-util.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/rest-api/get-extension-function.sjs
I'm running this locally to make sure that my modification to modulePaths doesn't break anything. 
Pinging @derms  on this too.
=> DHFPROD-2588: Fix for resolving custom transform module paths

web/src/main/ui/app/components/flows-new/edit-flow/ui/run-flow-dialog.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.scss, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.scss, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.scss, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.scss
Handles long flow and step names on Manage Flows, Edit Flow, Jobs, Job Details, and the Run Dialog
=> DHFPROD-2514: css to handle long flow names and steps

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy, web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts
Also, adjusts the mastering step to set entity collection on the proper documents.
=> DHFPROD-2555: Add collection for entity with mapping step

web/e2e/page-objects/browse/browse.ts, web/e2e/specs/scenarios/multiFlows.ts, web/e2e/specs/scenarios/simpleJson.ts
This PR fixed facets regression issue as the result of dev fix
=> E2E UI regression facets fix

marklogic-data-hub/src/test/resources/job-monitor-test/batch1.json, marklogic-data-hub/src/test/resources/job-monitor-test/batch2.json
This should fix the failing test
=> DHFPROD-2506: Change 'step' to 'stepNumber' in test batch docs

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/ingestion/default/main.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java, marklogic-data-hub/src/test/resources/flow-runner-test/input/ingest.txt
Processing text docs that have xml/json content and a test for it
=> DHFPROD-2452: Processing text docs that have xml/json content and a test for it

web/e2e/page-objects/dashboard/dashboard.ts, web/e2e/page-objects/flows/editFlow.ts, web/e2e/page-objects/flows/manageFlows.ts, web/e2e/page-objects/steps/mappingStep.ts, web/e2e/page-objects/steps/steps.ts, web/e2e/specs/entities/entity.ts, web/e2e/specs/flows/edit-flows.ts, web/e2e/specs/flows/index.ts, web/e2e/specs/flows/steps/ingestion.ts, web/e2e/specs/flows/steps/mapping.ts
In this pr:
1. Mapping step e2e UI tests.
2. Removed sleeps in some cases.
3. Remove test entity at the end of flow tests,
=> DHFPROD-2603: e2e UI mapping step tests.

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/ui/flow-settings-dialog.component.html, web/src/main/ui/app/components/flows-new/manage-flows/ui/flow-settings-dialog.component.scss, web/src/main/ui/app/components/flows-new/manage-flows/ui/flow-settings-dialog.component.ts, web/src/main/ui/app/components/flows-new/tooltips/flows.tooltips.ts, web/src/main/ui/app/components/flows-new/tooltips/manage-flows.tooltips.ts
Adds tooltips to Batch Size, Thread Count, and Options settings in New Step dialog.
Content is stored in separate flows.tooltips.ts file.
=> DHFPROD-2149: Add tooltips to New Step

web/src/main/ui/app/components/entity-modeler/entity-editor/entity-editor.component.html, web/src/main/ui/app/components/entity-modeler/entity-editor/entity-editor.component.ts
Consistent with Flows and Steps. This also prevents issues with renaming to duplicate Entity name and breaking Target Entity links in Steps.
=> DHFPROD-2616: Disable editing entity title

ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/TlsTest.groovy
Fix 'TlsTest' so that it works with jdk versions > 8
=> DHFPROD-2511:Fix 'TlsTest' so that it works with jdk versions > 8

web/e2e/page-objects/entities/entities.ts, web/e2e/page-objects/steps/masteringStep.ts, web/e2e/specs/entities/entity.ts, web/e2e/specs/flows/index.ts, web/e2e/specs/flows/manage-flows.ts, web/e2e/specs/flows/steps/mapping.ts, web/e2e/specs/flows/steps/mastering.ts, web/e2e/specs/scenarios/multiFlows.ts, web/e2e/specs/scenarios/simpleJson.ts
1. e2e UI mastering step tests.
2. Entity page tests modifications.
=> DHFPROD-2604: e2e UI mastering step tests.

web/e2e/page-objects/entities/entities.ts, web/src/main/ui/app/components/entity-modeler/entity-box/entity-box.component.html, web/src/main/ui/app/components/entity-modeler/entity-box/entity-box.component.scss
quick 2-line change for DHFPROD-2488.
=> DHFPROD-2488: changed delete entity icon from X to trash

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/DataHubTest.java
Support 9.0 versions > 9.0-7 and all 10.0 versions, 10 nightly > 06/01
=> DHFPROD-2625: Support 9.0 versions > 9.0-7 and all 10.0 versions, 10 nightly > 06/01

web/e2e/specs/scenarios/multiFlows.ts, web/e2e/specs/scenarios/simpleJson.ts
Add await on flow run to stabilize the tests
=> E2E UI - stabilize flow run with await

marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java
Changing validation tests to accommodate for changes in 10.x server behavior
=> DHFPROD-2632:Changing validation tests to accommodate for changes in 10.x server 

web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-collection-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-collection-dialog.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-collection-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-option-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-option-dialog.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-option-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-strategy-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-strategy-dialog.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-strategy-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts, web/src/main/ui/app/components/flows-new/tooltips/flows.tooltips.ts
-Added tooltips for new ingestion, mapping, and mastering step. 
-Added tooltips for ingest lower panel
-Added tooltips for mastering lower panel (merging). 
-Added dummy placeholder text for custom step tooltip in flows.tooltips
=> DHFPROD-2380: Added tooltips for Ingestion, Mapping, and Mastering include DHFPROD 2381 and 2384

examples/README.md, examples/insurance/README.md, examples/insurance/flows/BedrockFlow.flow.json
- Add dh5-custom-hook example to the overall README
- Minor edits to the READMEs
- Fix path and description in flow in insurance example
=> Data Hub examples edits

web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-option-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-option-dialog.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-option-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-threshold-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-threshold-dialog.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-threshold-dialog.component.ts, web/src/main/ui/app/components/flows-new/tooltips/flows.tooltips.ts
Also removed conflicting default tooltips and corrected a variable name typo
=> DHFPROD-2383: added customized tooltips for matching tab

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java, marklogic-data-hub/src/test/resources/flow-runner-test/flows/testFlow.flow.json
Add filename to header and metadata properties when ingesting csv docs and a test
=> DHFPROD-2508: Add filename to header and metadata properties when ingesting csv docs

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/RunFlowTask.groovy
Adding "separator" to gradle hubRunFlow command arguments
=> Adding "separator" to gradle hubRunFlow command arguments

web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-option-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-option-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-threshold-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-threshold-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/ui/flow-settings-dialog.component.html, web/src/main/ui/app/components/flows-new/manage-flows/ui/flow-settings-dialog.component.ts, web/src/main/ui/app/components/flows-new/validators/instant-error-match.validator.ts
DHFPROD-2653:  Fixed by calling selectedTypeChanged method in ngOnInit
=> DHFPROD-2620: Fixed by adding real-time error checking

web/e2e/page-objects/flows/manageFlows.ts, web/e2e/specs/scenarios/index.ts, web/e2e/specs/scenarios/multiFlows.ts, web/e2e/specs/scenarios/simpleJson.ts
This PR:
- Update and add page object to click on last finished job from manage flows page
- Change verification to click the last finished job from manage flows page
=> DHFPROD-2659: Fix verification inconsistency on last finished job

web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
Add snackbar saved indicator for UI changes that lack feedback:
- Ingestion step config
- Mapping step config
- Custom step config
=> DHFPROD-2531: Add snackbar saved indicator

examples/barebones/build.gradle, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle
@aebadirad I'm thinking this is worth doing for the develop branch and the master branch. I only bumped up the version on projects where it was obviously safe to do so.
=> Bumping up a few example projects to 5.0.1

marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java
Revert "Changing validation tests to accommodate for changes in 10.x server behavior"
This reverts commit f75402fd
The issue has been fixed in 10.x server
=> DHFPROD-2632:Revert "Changing validation tests to accommodate for changes in 10.x server behavior"

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/dmsdk-ingest.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java, marklogic-data-hub/src/test/resources/flow-runner-test/flows/testFlow.flow.json
Add "createdUsingFile" to header when ingesting csv.
=> DHFPROD-2658: Add "createdUsingFile" to header when ingesting csv

web/e2e/specs/scenarios/multiFlows.ts, web/e2e/specs/scenarios/simpleJson.ts
To make PR job cleaner until the bug is fixed (https://project.marklogic.com/jira/browse/DHFPROD-2679)
=> E2E UI - Comment out tests until bug is fixed

web/e2e/page-objects/steps/steps.ts, web/e2e/specs/browse/browse-data.ts, web/e2e/specs/scenarios/multiFlows.ts
- Update page objects for additional collections
- Test for adding additional collections and verifying the facet collection
=> DHFPROD-2701: E2E UI - add page objects and tests for additional collections

web/src/main/ui/app/components/common/common.module.ts, web/src/main/ui/app/components/common/http-error/http-error.component.html, web/src/main/ui/app/components/common/http-error/http-error.component.scss, web/src/main/ui/app/components/common/http-error/http-error.component.ts, web/src/main/ui/app/components/common/index.ts, web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.ts, web/src/main/ui/app/components/jobs-new/job-details.component.ts, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.ts, web/src/main/ui/app/components/no-content/no-content.scss, web/src/main/ui/app/components/no-content/no-content.ts
cleaned up PR and included @briantang changes.
=> DHFPROD-2575: Add 404 Route and exception handling for invalid routes

web/src/main/ui/app/app.module.ts, web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.module.ts, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ingest.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.ts, web/src/main/ui/app/components/flows-new/tooltips/flows.tooltips.ts
1. Updated the MLCP command with suggested changes related to step number and CSS.
2. Rebased the repository to resolve conflicts.
@wooldridge - Please review.
=> DHFPROD-2135: FE Implementation Display MLCP command in ingest step

web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.ts, web/src/main/ui/app/components/flows-new/tooltips/flows.tooltips.ts
Add uri preview feature to ingestion step page. I am creating a draft PR for review now and will rebase with Nikhil's changes (mlcp command) once they are merged
=> DHFPROD-2386: Add uri preview feature to ingestion step page

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs
Handle `Sequence` payloads in `cleanData()` to address my proximate problems with #2736 
Also includes some whitespace changes, as previous indenting obscured the logic.
=> DHFPROD-2741: Addresses #2736 by handling Sequence payloads.

web/src/main/ui/app/components/flows-new/models/step.model.ts
I just catch the description from the response of back end
=> DHFPROD-2740: fixed by adding description into stepsArray

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/flowWithStepReturningNull.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/mapping-prov-test.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/suite-teardown.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/teardown.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/test-data/CustomerNull.flow.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/test-data/CustomerNull.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/test-data/nullStep.sjs, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.ts
The following line could also be changed to `Array.isArray(value)`, but that is not necessary to fix the proximate problem.
=> Allow null or undefined values in step result.

marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/AbstractVerifyCommand.java
Simple typo fix in verifier message for Triggers
=> DHFPROD-2672: Fixing typo for the verifier message in triggers

web/e2e/page-objects/flows/editFlow.ts, web/e2e/page-objects/steps/ingestStep.ts, web/e2e/page-objects/steps/steps.ts, web/e2e/qa-project/input/flow-test/sep-types/comma-data/data.csv, web/e2e/qa-project/input/flow-test/sep-types/pipe-data/data.csv, web/e2e/qa-project/input/flow-test/sep-types/semicolon-data/data.csv, web/e2e/qa-project/input/flow-test/sep-types/tab-data/data.tsv, web/e2e/specs/flows/steps/ingestion.ts, web/e2e/specs/flows/steps/mapping.ts, web/e2e/specs/flows/steps/mastering.ts, web/e2e/test-objects/flowConfig.ts, web/e2e/test-objects/stepConfig.ts
In this PR I added several UI automated tests for the following Jira tasks:
1. DHFPROD-2713: Page validation for CSV separator type.
2. DHFPROD-2712: Page validation for target format and additional collections.
=> DHFPROD-2713: Page validation for CSV separator type, target format and additional collections 

web/src/main/ui/app/components/folder-browser/folder-browser.component.ts, web/src/main/ui/app/components/folder-browser/ui/folder-browser-ui.component.html, web/src/main/ui/app/components/folder-browser/ui/folder-browser-ui.component.ts
allow users to click to save changes when browsing
=> DHFPROD-2342: fixed by allowing user to click to browse folders

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/jobs/getJobDocsForFlows.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/jobs/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/jobs/test-data/mapping-job1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/jobs/test-data/mastering-job1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/jobs/test-data/mastering-job2.json
This is for a bug that was already fixed. Intent is to get test coverage on a fairly important function in the jobs module.
=> DHFPROD-2722: Added tests for getJobDocsForFlows

web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.ts
Updated the -output_collections parameter to include step name and removed flow name & input collection names.
=> DHFPROD-2780: The parameter "output_collections" of MLCP command in the ingest step, needs to be updated.

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/StepMetrics.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/WriteStepRunnerTest.java
Fix the percent complete value for csv ingestion
=> DHFPROD-2301: Fix the percent complete value for csv ingestion

examples/insurance/mappings/AdvantageFlow-AdvantageMap/AdvantageFlow-AdvantageMap-0.mapping.json, examples/insurance/mappings/BedrockFlow-BedrockMap/BedrockFlow-BedrockMap-0.mapping.json, examples/online-store/mappings/Test/Test-1.mapping.json, examples/online-store/mappings/Test/Test-2.mapping.json, marklogic-data-hub/src/test/java/com/marklogic/hub/legacy/flow/LegacyFlowRunnerTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/com/marklogic/hub/mapping/extractInstance-test.sjs, marklogic-data-hub/src/test/resources/flow-runner-test/mappings/e2e-mapping-1.mapping.json, marklogic-data-hub/src/test/resources/mapping-test/mappings/CustomerXML-CustomerXMLMapping/CustomerXML-CustomerXMLMapping-0.mapping.json, marklogic-data-hub/src/test/resources/master-test/mappings/person/person-1.mapping.json, marklogic-data-hub/src/test/resources/upgrade-projects/dhf43x/plugins/mappings/Product Mapping/Product Mapping-4.mapping.json, ml-data-hub-plugin/src/test/resources/my-new-mapping-1.mapping.json, web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/mappings/map.component.ts, web/src/main/ui/app/components/mappings/stories/map-ui.component.stories.ts, web/src/test/resources/integration-test-data/mapping-data.json
I updated all of the test files to have "/" as well.
=> DHFPROD-2502: The sourceContext in a new mapping is now always "/"

web/e2e/page-objects/appPage.ts, web/e2e/page-objects/flows/manageFlows.ts, web/e2e/page-objects/jobs/jobDetails.ts, web/e2e/page-objects/jobs/jobs.ts, web/e2e/page-objects/jobs/manageJobs.ts, web/e2e/page-objects/settings/settings.ts, web/e2e/specs/index.ts, web/e2e/specs/jobs/index.ts, web/e2e/specs/jobs/jobs.ts, web/e2e/test-objects/flowConfig.ts, web/e2e/test-objects/stepConfig.ts
QS Jobs page validation tests.
=> DHFPROD-2356: Quickstart UI Automation on jobs page validation

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, web/src/main/java/com/marklogic/hub/web/service/AsyncFlowService.java
Fix running percent in ingestion and erratic behavior of status bar in UI
=> DHFPROD-2793: Fix running percent in ingestion and erratic behavior of status bar in UI

web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.ts
Add "/" to the uri preview when inputFileType is 'csv'
=> DHFPROD-2821: Add "/" to the uri preview when inputFileType is 'csv'

marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/WriteStepRunnerTest.java
Fix for DHFPROD-2793 broke WriteStepRunnerTest. Fixing the test
=> DHFPROD-2822:Fix 'WriteStepRunnerTest'

web/e2e/page-objects/jobs/manageJobs.ts, web/e2e/page-objects/steps/ingestStep.ts, web/e2e/page-objects/steps/masteringStep.ts, web/e2e/specs/flows/steps/ingestion.ts, web/e2e/specs/flows/steps/mastering.ts
1. Added new tests and verification in the existing tests for the MLCP command.
2. Fixed two ingestion tests that fail on Jenkins.
=> DHFPROD-2795:Page validation on MLCP Command

web/e2e/page-objects/appPage.ts, web/e2e/page-objects/dashboard/dashboard.ts, web/e2e/specs/dashboard/dashboard.ts
Added validation for QS menu about Data Hub version, project directory, MarkLogic version and the file a bug link.
=> DHFPROD-2835: Page validation for QS about menu

web/e2e/specs/scenarios/simpleJson.ts
Updated the docs counts from 6 back to 8
This is the expected behavior and was a regression before
=> DHFPROD-2848: Update tests due to mastering fix

web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.ts
All the requirements are completed for this story. Also, updated the Source Format option 'CSV' to 'Delimited Text'.
=> DHFPROD-2731: Customize the 'CSV Separator' field in Quickstart

web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-option-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-threshold-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/match-thresholds-ui.component.html
=> DHFPROD-2164: Change label names for Zip type Match option

web/e2e/page-objects/flows/editFlow.ts, web/e2e/page-objects/steps/ingestStep.ts, web/e2e/specs/scenarios/multiFlows.ts, web/e2e/test-objects/stepConfig.ts
For some reason, we missed the commit fd63d75 for the PR https://github.com/marklogic/marklogic-data-hub/pull/2791 made before. 
Here is the missing fix.
=> DHFPROD-2869: Replace CSV to Delimited Text for UI tests.

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/DhsInstallTest.java
This prevents a user from having to add the following properties to gradle-dhs.properties:
mlAppServicesAuthentication=basic
mlAppServicesSimpleSsl=true
=> DHFPROD-2867: For DHS, defaulting App-Services config to that of staging

web/e2e/page-objects/browse/browse.ts, web/e2e/page-objects/dashboard/dashboard.ts, web/e2e/page-objects/entities/entities.ts, web/e2e/page-objects/flows/editFlow.ts, web/e2e/page-objects/flows/manageFlows.ts, web/e2e/page-objects/steps/ingestStep.ts, web/e2e/page-objects/steps/mappingStep.ts, web/e2e/page-objects/steps/masteringStep.ts, web/e2e/specs/scenarios/simpleJson.ts
1. Refactored simple Json e2e test suite to smaller specs. 
2. Added page validation for dashboard, entity, flow, browse data and jobs pages.
=> DHFPROD-2840: UI smoke test suite for page validation.

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/dhf-defaults.properties
And removed code referring to obsolete properties - mlFinalScheme, mlStagingScheme, mlJobScheme, and mlAppServicesScheme
=> DHFPROD-2872: Deprecated getScheme/setScheme on HubConfig

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/util/CMASettings.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/DataHubTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
Support for 4.x-develop on 9.0-10 and above, 10.0 nightly > 06/01
=> DHFPROD-2905: Support 9.0-10 and above, 10.0 nightly > 06/01

ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/BaseTest.groovy
=> DHFPROD-2943: Update the module count

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/Step.java
Ignoring unnecessary fields in step json
=> DHFPROD-2961: Remove unnecessary fields in step json

marklogic-data-hub/src/test/java/com/marklogic/bootstrap/DataHubInstallTest.java
Added a message so its easier to know what the count should be if this test fails in the future.
=> Update triggers count in test

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
Automatically select another doc if original source doc is not found in mapping step
=> DHFPROD-2515:Automatically select another doc if original source doc is not found

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/StepRunnerUtil.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java
=> DHFPROD-2896: (5.x) Don't write Job docs from middleware if disableJobOutpu

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/DhsInstallTest.java
Already submitted a PR for the 5.x branch, this is for develop
=> DHFPROD-2897: Known values for a DHS installation are now set

examples/dh-5-example/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/nifi/NifiTemplateGenerator.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/nifi/database-client-service.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/nifi/get-file.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/nifi/invoke-http.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/nifi/log-attribute.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/nifi/log-message.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/nifi/merge-content.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/nifi/nifi.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/nifi/options-json.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/nifi/put-marklogic.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/nifi/run-flow-step.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/nifi/split-text.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/nifi/update-attribute.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/nifi/GenerateNifiTemplateTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/nifi/GenerateNifiTemplateTask.groovy
Have only tested this on the 3-step flow in the dh-5-example project, but it works fine there. Note the instructions printed out by the Gradle task for modifying the template after it's been loaded into NiFi.
=> DHFPROD-2784: Can now generate a NiFi template for a flow

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/default/main.sjs, marklogic-data-hub/src/main/resources/scaffolding/custom-module/sjs/main-custom.sjs, marklogic-data-hub/src/main/resources/scaffolding/custom-module/sjs/main-mapping.sjs
Will open a separate JIRA ticket to capture the requirements for this
=> DHFPROD-2826: Removing use of createAttachments

marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/flow/impl/LegacyFlowRunnerImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/extensions/flow.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/extensions/sjsflow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/legacy/flow/impl/LegacyFlowRunnerImplTest.java
Throw HTTP 400 in case of plugin errors and handle error responses. (to 5.x-develop branch)
=> DHFPROD-2959: Throw HTTP 400 in case of plugin errors

web/src/main/ui/app/components/flows-new/edit-flow/ingest/ingest.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.ts, web/src/main/ui/app/components/flows-new/models/step.model.ts
Fixed the issue in the ticket mentioned below.
DHFPROD-3035: A new custom ingestion step is created with separator , for input file type json.
=> DHFPROD-3035: A new custom ingestion step is created with separator , for input file type json.

marklogic-data-hub/src/main/java/com/marklogic/hub/mapping/MappingFunctions.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/mappingFunctions.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/mappingFunctions.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/rest-api/lib/extensions-util.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/getMappingFunctions.sjs, web/src/main/java/com/marklogic/hub/web/service/MappingManagerService.java, web/src/main/java/com/marklogic/hub/web/web/MappingController.java
Adding a endpoint to fetch xpath and mapping functions. It can be accesses using /api/current-project/mappings/functions endpoint
=> DHFPROD-3124:Adding a endpoint to fetch xpath and mapping functions

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/extensions/flow.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/extensions/sjsflow.sjs
Throw HTTP 400 if errorCount > 0 and if the error is a "DATAHUB-PLUGIN-ERROR"
=> DHFPROD-2959: Check if error is a plugin error

marklogic-data-hub/src/main/java/com/marklogic/hub/validate/CustomStepValidator.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/stepValidate.sjs, web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.ts
Fix issue in checking for module perms, refactor CustomStepValidator
=> DHFPROD-2721:Fix issue in checking for module perms, refactor CustomStepValidator

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/extensions/flow.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/extensions/sjsflow.sjs
Throw HTTP 400 if errorCount > 0 and if the error is a "DATAHUB-PLUGIN-ERROR"
=> DHFPROD-2959:Check if error is a plugin error

marklogic-data-hub/src/main/java/com/marklogic/hub/collector/impl/FileCollector.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/MappingManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/job/impl/LegacyJobManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/DataHubInstallTest.java, web/src/main/java/com/marklogic/hub/web/service/LegacyFlowManagerService.java
See how this affects the stability of our pipeline
=> DHFPROD-3068: Be more responsible with our streams

web/src/main/ui/app/components/login/login.component.ts
Change the link to point to upgrade to DHF 5.x
=> DHFPROD-3083:Change the link to point to upgrade to DHF 5.x

web/angular.json, web/package-lock.json, web/package.json, web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts, web/src/main/ui/app/components/flows-new/services/manage-flows.service.ts
Added the UI components for mapping expression related story DHFPROD-3010 and DHFPROD-3019.
=> DHFPROD-3010: Support mapping expressions for flat JSON files and nested entities in the UI

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/mapping/Mapping.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommandTest.java
Also fixed javadoc error in Mapping.java
=> DHFPROD-3193: language is now replaced with lang when loading artifacts

marklogic-data-hub/src/main/java/com/marklogic/hub/step/RunStepResponse.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/MappingTest.java, marklogic-data-hub/src/test/resources/mapping-test/entities/Order.entity.json, marklogic-data-hub/src/test/resources/mapping-test/flows/OrderJSON.flow.json, marklogic-data-hub/src/test/resources/mapping-test/input/json/order1.json, marklogic-data-hub/src/test/resources/mapping-test/lookupDictionary/validDictionary.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testCustomFunction1.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testDateANDDateTime.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testInvalidDatePattern.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testInvalidDateStringValue.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testInvalidDateTimeFormat.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testInvalidDateTimePattern.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testInvalidDictionary.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testInvalidNonStandardFormat.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testInvalidStandardFormat.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testLookupFunction.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testLookupInvalidDocument.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testLookupNonJSON.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testMissingLookup.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testXPathFunctions.json, marklogic-data-hub/src/test/resources/mapping-test/src/main/ml-modules/root/custom-modules/mapping-functions/custom-mapping-function.sjs
This PR takes in commits from #2969 and fixes the failing tests. I will close #2969 once this gets merged.
=> DHFPROD-3192:Unable to use a custom mapping function

ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/UpdateIndexesTaskTest.groovy
Including the test in release branch
=> DHFPROD-3194: Fixing mlUpdateIndexesTest so it runs after saving the indexes

marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/dhf-defaults.properties, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/entity-model-reader.json, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommandTest.java
There's an open question about whether anything further should be done about the developer role, but I wanted to get what's in here out for review as I think it's stable.
There's some random white-space cleanup in here as well, probably from when I auto-formatted the code using Intellij.
=> DHFPROD-3110: Adding architect and developer roles for Explorer

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/Versions.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/DataHubInstallTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/ValidateMappingTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/lib/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/rejectFromFlow.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/validateJsonAccept.sjs, ml-data-hub-plugin/src/test/resources/my-new-mapping-1.mapping.json
Mostly related to mapping and ensuring the version of ML supports the latest ES mapping stuff
DHFPROD-3193: Handling 9.0-10.1 as well
=> DHFPROD-3193: Test fixes

web/src/main/ui/app/components/login/login.component.ts
Fixing the broken pre install check UI
=> DHFPROD-2917:Fixing the broken pre install check UI

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/jobInfo/jobInfo.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/jobInfo/jobInfo.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/jobInfo/service.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/jobInfo/jobInfoTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/jobInfo/suiteSetup.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/jobInfo/suiteTeardown.sjs
Does not include the Gradle task to generate the java class as DHF will not be using the endpoint for now.
=> DHFPROD-3242: Add data-services endpoint for querying latest job info

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
Fixed the bugs in functions list icon and field list icon
=> DHFPROD-3010: Fixing the bug with functionslist and Field list

marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/MappingTest.java, marklogic-data-hub/src/test/resources/mapping-test/input/json/order1.json
and adding job output so its clear why the test failed when they do.
=> DHFPROD-3276: Fixing a declarativeMapper test

web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html
Mapping properties are passed in as table component property.
Nested table components get sub property object.
Cleanup of unused code, formatting of existing code.
=> DHFPROD-3010: Load saved mapping into UI

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
For hiding/showing columns of entity table.
=> DHFPROD-3010: Entity table column menu

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
Bug fixes for the story DHFPROD-3022.
=> DHFPROD-3022 : Browse to previous or next documents when creating a mapping

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
This PR involves only the Bug fixes for DHFPROD-3022.
=> DHFPROD-3022: Browse to previous or next documents when creating a mapping

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/test-data/content/valid-customer.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/test-data/entities/Customer.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/test-data/mappings/CustomerMapping/CustomerMapping-0.mapping.json, marklogic-data-hub/src/test/resources/mapping-test/entities/Order.entity.json, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testDateANDDateTime.json
This PR also updates unit-test data for validate-entity to have test coverage for the code change
=> DHFPROD-3310: Adding "date" as an accepted datatype

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/services/mlMappingFunctions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/getMappingFunctions.sjs
Remove "fn:" from display name as well
=> DHFPROD-3019: Remove "fn:" from display name as well

web/src/main/java/com/marklogic/hub/web/service/DataHubService.java
Call 'GenerateFunctionMetaDataCommand' after modules db is cleared
=> DHFPROD-3337:Call 'GenerateFunctionMetaDataCommand' after modules db is cleared

marklogic-data-hub/src/main/resources/scaffolding/defaultFlow.flow.json
Create "entity-services-mapping" step if 'hubCreateFlow' is run
=> DHFPROD-3293:Create "entity-services-mapping" step if 'hubCreateFlow' is run

marklogic-data-hub/src/trace-ui/src/app/projects/projects.service.ts, web/src/main/java/com/marklogic/hub/web/service/DataHubService.java, web/src/main/java/com/marklogic/hub/web/web/CurrentProjectController.java, web/src/main/ui/app/components/login/login.component.ts, web/src/main/ui/app/components/login/ui/login-ui.component.html, web/src/main/ui/app/components/login/ui/login-ui.component.ts, web/src/main/ui/app/services/projects/projects.service.ts
Also removed associated code and unused methods in the Java web tier
=> DHFPROD-1450: Removed 'Update it' button

marklogic-data-hub/src/main/resources/ml-modules/services/mlCollections.sjs, web/src/main/java/com/marklogic/hub/web/model/SJSSearchQuery.java, web/src/main/java/com/marklogic/hub/web/service/SearchService.java, web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/search/search.service.ts, web/src/test/java/com/marklogic/hub/web/service/SearchServiceTest.java
DHFPROD-3245:Add 'urisOnly' option in ml:Collections and use it in UI
=> DHFPROD-3245:Add 'urisOnly' option in ml:Collections and use it in UI

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts, web/src/main/ui/app/components/flows-new/services/manage-flows.service.ts
Contains changes for the UI portion of story DHFPROD-3023
=> DHFPROD-3023: Test button checks for errors in UI mapping

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateNestedMapping.sjs
Reworked validateMapping to be a bit simpler too.
=> DHFPROD-3322: Validating the expression of a nested property

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/DataHubTest.java
5.1.0 supports server 9.x >= 9.0-10 or 10.x >= 10.0-2
=> DHFPROD-3102:5.1.0 supports server 9.x >= 9.0-10 or 10.x >= 10.0-2

web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
This PR contains the changes for DHFPROD-3021 mainly.
=> DHFPROD-3021: Support mapping expressions for namespaces and nested XML and JSON files in the UI

marklogic-data-hub/src/main/java/com/marklogic/hub/mapping/MappingImpl.java
DHFPROD-3348: Remove the hardcoded id->id map
=> DHFPROD-3348: Remove the hardcoded id->id map

marklogic-data-hub/src/main/java/com/marklogic/hub/mapping/MappingImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/MappingManagerTest.java
DHFPROD-3414: Remove 'language' when saving mapping
=> DHFPROD-3414: Remove 'language' when saving mapping

web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.scss
Also CSS cleanup for entity-table.
=> DHFPROD-3422: Remove blank row for collapsed nested mapping entity

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, web/src/main/java/com/marklogic/hub/web/service/EntityManagerService.java, web/src/main/java/com/marklogic/hub/web/service/FlowManagerService.java, web/src/main/java/com/marklogic/hub/web/service/MappingManagerService.java, web/src/main/java/com/marklogic/hub/web/web/HubErrorController.java, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
This PR solves 2 issues
DHFPROD-3023: Loads only mapping when it changes, don't force load artifacts when not required, introduce a delay of 750 ms after "Test" button is hit
In my mac, if mapping changes, it gets loaded in less than < 0.2 secs usually
DHFPROD-3421 - Show popup only if error shows that mapping is not present
=> DHFPROD-3023:(and DHFPROD-3421) Load mapping when it changes, popup only if mapping nor present

web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
Fixing compilation issues in the file
=> DHFPROD-3023:Fixing compilation issues in the file

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts
Check if the input field is null
=> DHFPROD-3439:Check if the input field is null

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts
=> DHFPROD-3351: Wrong xpath generated by mapping in the expression

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.ts
=> DHFPROD-3367: QS: Mapping issue for the array value

web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.ts
Correctly handle arrays based on strings and other basic datatypes (instead of only arrays of other entities).
Also fix typo errors in mapping getResults().
Clean up some code formatting.
=> DHFPROD-3474: Fix array handling in mapping

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/EntityManagerImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/RemoveCollationFromEntityReferencePropertyTest.java
Also cleaned up a few compiler warnings in EntityManagerImpl
=> DHFPROD-3472: Removing collation from entity reference properties

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
1. Fix for the bug DHFPROD-3442.
2. Fixed the issue where data type in source table was being displayed as Object or Array for nested XML source doc as well.
=> DHFPROD-3442: Missing elements in QS mapping source data table in case of array of xml elements

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
When inserting info from the prop menu in mapping, take into account the parent context and trim if needed.
=> DHFPROD-3409: Trim mapping context

web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss
=> DHFPROD-3506: TEST and clear buttons are not aligned properly above the Entity table

marklogic-data-hub/src/main/resources/ml-modules/transforms/mlGenerateFunctionMetadata.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/LoadTestModules.java, marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub_unit_test/TestConfig.java, marklogic-data-hub/src/test/ml-modules/root/custom-modules/mapping-functions/add-function.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/runMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/mappings/OrdersMapping/OrdersMapping-2.mapping.json
Enable creation of custom xquery mapping functions
=> DHFPROD-3501: Enable creation of custom xquery mapping functions

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
1. Fixed the bug DHFPROD-3519.
2. Fixed the issues mentioned by Marilyn in the ticket DHFPROD-3023.
=> DHFPROD-3519: Namespaces doesn't appear if the prefix is given alongwith xmlns attribute in the node

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/MappingTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/createEntityServicesMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/nestedMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/content/person3.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/mappings/PersonMapping/PersonMapping-4.mapping.json
Fixes the remaining issue @bsrikan noted in PR https://github.com/marklogic/marklogic-data-hub/pull/3181
=> DHFPROD-3547: Use document root for mapping

web/src/main/ui/app/models/entities.service.ts
When entity is edited/saved,save all entities that refer to it
=> DHFPROD-3548: When entity is edited/saved,save all entities that refer to it

web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.scss
See: https://project.marklogic.com/jira/browse/DHFPROD-3410
=> DHFPROD-3410: Move help icon to other side of mapping text box

web/src/main/ui/app/models/entities.service.ts
When entity is deleted, remove it from all entities that refer to it
=> DHFPROD-3597:When entity is deleted,remove it from all entities that refer to it

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
=> DHFPROD-3613: Mapping UI source document navigation arrows appear clickable when no other source files exist

.github/ISSUE_TEMPLATE.md, CHANGELOG.md, examples/dhf4/DHS-e2e/DHS/build.gradle, examples/dhf4/dhf-with-tests-xquery/build.gradle, examples/dhf4/disconnected-project/build.gradle, examples/dhf4/disconnected-project/gradle.properties, examples/dhf4/external-security/build.gradle, examples/dhf4/external-security/gradle-example.properties, examples/dhf4/gradle-tasks-demo/docs/build.gradle, examples/dhf4/healthcare/build.gradle, examples/dhf4/ssl/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/error/DataHubConfigurationException.java, marklogic-data-hub/src/main/resources/dhf-defaults.properties, marklogic-data-hub/src/main/resources/overview.html, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, marklogic-data-hub/src/main/resources/scaffolding/gradle_properties, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/trace-ui/src/app/traces/trace-viewer.component.html, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/InitProjectTask.groovy, web/src/main/ui/app/components/login/ui/login-ui.component.html, web/src/main/ui/app/components/settings/settings.component.html, web/src/main/ui/app/components/settings/ui/settings-ui.component.html, web/src/main/ui/app/components/trace-viewer/trace-viewer-ui.component.html
Just the reference change from 'Data Hub Framework' to 'Data Hub'.
=> DHFPROD-3387: Replace reference to 'Data Hub Framework' with 'Data Hub' in QuickStart

web/src/main/ui/app/components/search/search.component.ts
Call doSearch() again only if current db is changed
=> DHFPROD-3464: Call doSearch() again only if current db is changed

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubArtifactsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, web/src/main/java/com/marklogic/hub/web/service/DataHubService.java, web/src/test/java/com/marklogic/hub/web/service/DataHubServiceTest.java
Don't delete modules timestamp file if not necessary
=> DHFPROD-3646: Don't delete modules timestamp file if not necessary

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts, web/src/main/ui/app/components/flows-new/models/step.model.ts
Fix for the bug DHFPROD-3601 in UI layer.
=> DHFPROD-3601: Set the default in the UI (and the backend) to 1 thread for a mastering step, in case they don't read the docs first

web/src/main/java/com/marklogic/hub/web/service/FileSystemWatcherService.java
This ensures that DH can still be compiled and run on OpenJDK.
=> DHFPROD-3523: SensitivityWatchEventModifier is now loaded dynamically

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java
Create prov doc in ingestion step
=> DHFPROD-3191:Create prov doc in ingestion step

web/build.gradle
Skip the task publish web using " -PskipWeb=true"
=> DHFPROD-3685: Skipping build web

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss
1. Bug fix for DHFPROD-3615.
2. UI changes to the way we display namespaces.
=> DHFPROD-3615: For XML elements in a namespace, the element selector doesn’t work

examples/README.md, examples/insurance/.gitignore, examples/insurance/README.md, examples/insurance/build.gradle, examples/insurance/flows/BedrockFlow.flow.json, examples/insurance/flows/CustomerMastering.flow.json, examples/insurance/mappings/AdvantageFlow-AdvantageMap/AdvantageFlow-AdvantageMap-0.mapping.json, examples/insurance/mappings/BedrockFlow-BedrockMap/BedrockFlow-BedrockMap-0.mapping.json, examples/json-mapping-example/.gitignore, examples/json-mapping-example/README.md, examples/json-mapping-example/build.gradle, examples/json-mapping-example/data/jsonPerson1.json, examples/json-mapping-example/data/xmlPerson1.xml, examples/json-mapping-example/entities/Address.entity.json, examples/json-mapping-example/entities/Name.entity.json, examples/json-mapping-example/entities/Person.entity.json, examples/json-mapping-example/flows/jsonToJson.flow.json, examples/json-mapping-example/flows/xmlToJson.flow.json, examples/json-mapping-example/mappings/jsonToJson-mapjson/jsonToJson-mapjson-1.mapping.json, examples/json-mapping-example/mappings/xmlToJson-mapxml/xmlToJson-mapxml-1.mapping.json, examples/json-mapping-example/src/main/ml-data/referenceData/countryCodes.json, examples/json-mapping-example/src/main/ml-modules/root/custom-modules/mapping-functions/custom-javascript-functions.sjs, examples/json-mapping-example/src/main/ml-modules/root/custom-modules/mapping-functions/custom-javascript-module.mjs, examples/json-mapping-example/src/main/ml-modules/root/custom-modules/mapping-functions/custom-xquery-functions.xqy
Also updated the insurance project to use the new mapping system
=> DHFPROD-2806: Added json-mapping-example project

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/content/orderTest.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/entities/OrderType.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/mappings/OrdersMapping/OrdersMapping-3.mapping.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateAndRunMapping.sjs
Show array values when "Test" button is clicked
=> DHFPROD-3678:Show array values when "Test" button is clicked

web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss
Add CSS bottom padding to enclosing container for mapping step.
=> DHFPROD-3668: Add mapping container space for long properties menus

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts
=> DHFPROD-2794: Collections list doesn't change immediately upon changing the database in New Mastering/Mapping/Custom step Window

web/e2e/page-objects/flows/editFlow.ts, web/e2e/page-objects/steps/mappingStep.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.html
=> DHFPROD-3705: Fix the overlay in QuickStart for property and function picker

web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.html
Quick fix, escaped the quotes.
=> DHFPROD-3663: Update tooltip for context icon

marklogic-data-hub/src/main/resources/scaffolding/defaultFlow.flow.json
Adding threadCount, batchSize and customHook to defaultFlow
=> DHFPROD-3686:Adding threadCount, batchSize and customHook to defaultFlow

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/ValidateMappingTest.java, web/src/main/java/com/marklogic/hub/web/service/MappingManagerService.java, web/src/main/java/com/marklogic/hub/web/web/CurrentProjectController.java, web/src/main/java/com/marklogic/hub/web/web/MappingController.java, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts, web/src/main/ui/app/components/flows-new/services/manage-flows.service.ts
Make mapping validation/test work with final db
=> DHFPROD-3722:Make mapping validation/test work with final db

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts
=> DHFPROD-3749: Adding namespace prefix to array of elements doesnt work as expected

marklogic-data-hub/src/main/resources/ml-modules/services/mlMappingFunctions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/getMappingFunctions.sjs
Remove "base-uri","document-uri" from list of functions
=> DHFPROD-3665:Remove "base-uri","document-uri" from list of functions

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping-functions/core.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/createEntityServicesMapping.sjs, marklogic-data-hub/src/test/resources/mapping-test/mappingConfig/testCustomFunction1.json
Rename existing 'pattern' variable, fix custom func in test. This should fix the failing tests
=> DHFPROD-3620:Rename existing 'pattern' variable, fix failing tests

.gitignore, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/util/ModuleWatchingConsumer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/util/ModuleWatchingConsumerTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
This is undoing what I previously submitted to the develop branch with a leaner fix.
=> DHFPROD-3812: Fixing hubInit

web/package-lock.json, web/package.json
Update typescript to ~3.2.4 to keep installed version < 3.3.0
Updates to @aebadirad's PR.
=> DHFPROD-3844: Update typescript version, remove storybook dependencies

CHANGELOG.md
Adding only GITHUB issues to the Changelog. Please let me know if I need to add the epics/stories.
=> DHFPROD-3818: Adding changelog.md

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java, marklogic-data-hub/src/test/resources/flow-runner-test/flows/testFlow.flow.json
Setting document permissions correctly during ingestion
=> DHFPROD-3874:Setting document permissions correctly during ingestion

marklogic-data-hub/src/main/resources/hub-internal-config/security/amps/amps-dhf-update-batch.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/amps/amps-dhf-update-job.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/datahub.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/services/mlJobs.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunWithDataHubOperatorTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/jobs/buildJobPermissionsScript.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/jobs/getJobDocsForFlows.sjs, marklogic-data-hub/src/test/resources/flow-runner-test/flows/testFlow.flow.json
Insert/update job/batch docs with permissions using new roles
=> DHFPROD-3618:Insert/update job/batch docs with permissions using new roles

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/job-lib.xqy
Note: we have no dh5 tests to, well, test this in the gradle plugin.
=> DHFPROD-3112: update the scope of the directory query

build.gradle, marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle, web/build.gradle
Jacoco Report:
https://jenkins.marklogic.com/view/DHF-9.0-Server-All/job/Datahub_CC/lastBuild/jacoco/
Sonar Report:
http://sonar.marklogic.com/dashboard/index/10662
=> DHFPROD-2117: Code coverage(Jacoco) and Sonar

marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/InstallIntoDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/dhf-defaults.properties, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin-role.json, marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-entity-create.json, marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-entity-delete.json, marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-entity-modify.json, marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-entity-validate-create.json, marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-entity-validate-modify.json, marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-json-mapping-create.json, marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-json-mapping-delete.json, marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-json-mapping-modify.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/lib.sjs, marklogic-data-hub/src/main/resources/scaffolding/gradle_properties, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/command/InstallIntoDhsCommandTest.java, ml-data-hub-plugin/gradle.properties, web/gradle.properties
Initialize new DH project without data-hub-admin-role
=> DHFPROD-3522:Initialize new DH project without data-hub-admin-role

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployDatabaseFieldCommand.java
Fix undo for 'DeployDatabaseFieldCommand'
=> DHFPROD-3943: Fix undo for 'DeployDatabaseFieldCommand'

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployDatabaseFieldCommand.java
Set the right undo sort order for 'DeployDatabaseFieldCommand'
=> DHFPROD-3943: Set the right undo sort order for 'DeployDatabaseFieldCommand'

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubDeveloperTest.java
Missed this requirement the first time around
=> DHFPROD-3108: data-hub-developer can now delete a protected path

marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunWithDataHubOperatorTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubAdminTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubDeveloperTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubOperatorTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubSecurityAdminTest.java
Ignoring tests unsupported in server versions < 10.0-3
=> DHFPROD-3968:Ignoring tests unsupported in server versions < 10.0-3

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubDeveloperTest.java
Manage scheduled tasks as data-hub-developer in DHS
=> DHFPROD-3906:Manage scheduled tasks as data-hub-developer in DHS

marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java
=> DHFPROD-3968: Ignore tests on 9.0-nightly

marklogic-data-hub/src/main/java/com/marklogic/hub/HubProject.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/DataHubInstallTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/ExportProjectTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/ExportProjectTaskTest.groovy
=> DHFPROD-3781:Export project files as a zip

web/src/main/java/com/marklogic/hub/web/web/CurrentProjectController.java
Ensure absence of some dirs doesn't affect authentication
=> DHFPROD-3089:Ensure absence of some dirs doesn't affect authentication

marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/InstallIntoDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/UpdateDhsModulesPermissionsCommand.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-environment-manager.json, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/command/InstallIntoDhsCommandTest.java
Prohibit DHS users from updating DHF modules
=> DHFPROD-2691:Prohibit DHS users from updating DHF modules

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/database-fields/staging-database.xml, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/merging.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java, marklogic-data-hub/src/test/resources/upgrade-projects/dhf43x/key/final-database.xml, marklogic-data-hub/src/test/resources/upgrade-projects/dhf43x/src/main/ml-config/database-fields/final-database.xml, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/UpdateIndexesTaskTest.groovy, ml-data-hub-plugin/src/test/resources/update-indexes/final-database.xml, ml-data-hub-plugin/src/test/resources/update-indexes/staging-database.xml
Replace jsonPropertyValueQuery with pathRangeQuery
=> DHFPROD-3911:Replace jsonPropertyValueQuery with pathRangeQuery

examples/dh-5-example/README.md, examples/dh-5-example/build.gradle, examples/dh-5-example/src/main/entity-config/exp-final-entity-options.xml, examples/dh-5-example/src/main/entity-config/exp-staging-entity-options.xml, examples/dh-5-example/src/main/java/org/example/RunFlowWithCustomHubConfig.java, examples/dh-5-example/src/main/java/org/example/RunFlowWithoutProject.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowInputs.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowInputsTest.java
This is intended to be linked to from new docs that will be added to  https://docs.marklogic.com/datahub/flows/run-flow-using-datahub-api.html
=> DHFPROD-4023: Added examples for running a flow without a project

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-entity-model-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-entity-model-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-environment-manager.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-explorer-architect.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-flow-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-flow-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-job-internal.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-job-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-mapping-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-mapping-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-module-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-module-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-monitor.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-security-admin.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-step-definition-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-step-definition-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/flow-developer-role.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/flow-operator-role.json
The intent is for these to be usable in the docs as well
=> DHFPROD-4054: Simplified descriptions of new roles

marklogic-data-hub/src/test/java/com/marklogic/hub/cli/client/RunFlowViaMainTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunWithDataHubOperatorTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/DeployProtectedPathsWhenUpdatingIndexesTest.java
This isn't failing locally. I'm guessing it's either do to the adminHubConfig being modified by a previous test, or that the mkdirs call isn't succeeding because the "security" directory doesn't exist. No idea really.
=> DHFPROD-3935: Trying to fix protected paths tests

marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/UpdateDhsModulesPermissionsCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/command/InstallIntoDhsCommandTest.java
Fixing the permissions of DHS REST extensions
=> DHFPROD-2691:Fixing the permissions of DHS REST extensions

web/src/main/java/com/marklogic/hub/web/web/CurrentProjectController.java
Ensure that watcher service is disabled after user logs out
=> DHFPROD-4046:Ensure that watcher service is disabled after user logs out

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/ingestion/default/testXmlIngestWIthRoot.sjs
Ingest correctly when xml doc root node name is 'root'
=> DHFPROD-3625:Ingest correctly when xml doc root node name is 'root'

Jenkinsfile
Moving windows jobs to different parallel stage
Moving quick start to another parallel stage
adding 10.0-3 tests
adding when condition
=> DHFPROD-4086: Moving Jobs between stages and Adding tests for 10.0-3

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy
=> DHFPROD-4161: Unwrap type instance query

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/InstallerCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/Main.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/Options.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/AbstractInstallerCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/AbstractVerifyCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/VerifyDhfInDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/deploy/CopyQueryOptionsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/deploy/DhsDeployServersCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/deploy/UpdateDhsModulesPermissionsCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/deploy/DhsDeployServersCommandTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
I did some repackaging of the installer program so it's more clear that that program is for DHS. Nothing changed other than packages and imports. The only change of interest in here is in build.gradle.
=> DHFPROD-4021: Client jar is now being published

marklogic-data-hub/src/main/java/com/marklogic/hub/cli/client/CommandLineFlowInputs.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/client/RunFlowCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/client/RunFlowCommandTest.java
=> DHFPROD-4141: Client jar now supports -ssl and -auth

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/StepDefinitionManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/util/json/JSONUtils.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.mjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/flows.mjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/stepDefinitions.mjs, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/HubAppDeployerTest.java
As per requirement for this task, CRUD operations must be performed first on db and then to project.  
The corresponding PR for CRUD APIs  in one UI repo is
https://project.marklogic.com/repo/projects/PROD/repos/one-ui/pull-requests/23/diff
=> DHFPROD-4104:Use DS to perform flow/step CRUD operations

marklogic-data-hub/src/installer/logback.xml, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubOtherServersCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateFunctionMetadataCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubArtifactsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubModulesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/DhsDeployer.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/Options.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/AbstractInstallerCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/AbstractVerifyCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/deploy/CopyQueryOptionsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/deploy/DhsDeployServersCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/Versions.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/deploy/DhsDeployServersCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/DataHubImplTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/HubConfigImplTest.java
- Handling 2 other privileges that DHS is creating
- Fixed bug in HubConfigImpl where setHost wasn't called
- Reusing server version from Manage API instead of calling REST API for it (fixes bug where staging server was getting version 9 rewriter)
- Installer now logs to stdout
- dhsVerify is now working
=> DHFPROD-4118: Various fixes for installer

one-ui/ui/src/App.tsx, one-ui/ui/src/components/header/header.module.scss, one-ui/ui/src/components/reset-env/reset-env.tsx, one-ui/ui/src/pages/Reset.tsx
A UI convenience as we develop login functionality, resets hostname setting on server.
=> DHFPROD-3978: Misc UI updates

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/AbstractSecurityTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubAdminTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubDeveloperTest.java
These requirements were missed the first time around, fairly simple to add them in now.
=> DHFPROD-4214: Adding privileges for clearing jobs and updating indexes

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java, one-ui/src/main/java/com/marklogic/hub/curation/controllers/FlowController.java, one-ui/src/main/java/com/marklogic/hub/curation/services/FlowManagerService.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/FlowControllerTest.java
Create endpoints for getting all flows, all steps in a flow
=> DHFPROD-4222:Create endpoints for getting all flows, all steps in a flow

marklogic-data-hub/src/main/java/com/marklogic/hub/HubProject.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, one-ui/src/main/java/com/marklogic/hub/oneui/auth/ConnectionAuthenticationFilter.java, one-ui/src/main/java/com/marklogic/hub/oneui/auth/LoginLogoutHandler.java, one-ui/src/main/java/com/marklogic/hub/oneui/controllers/EnvironmentController.java, one-ui/src/main/java/com/marklogic/hub/oneui/services/EnvironmentService.java, one-ui/src/test/java/com/marklogic/hub/oneui/services/EnvironmentServiceTest.java, one-ui/ui/src/App.tsx, one-ui/ui/src/components/install-form/install-form.tsx, one-ui/ui/src/components/project-info-header/project-info-header.module.scss, one-ui/ui/src/components/project-info-header/project-info-header.test.tsx, one-ui/ui/src/components/project-info-header/project-info-header.tsx, one-ui/ui/src/pages/ProjectInfo.module.scss, one-ui/ui/src/pages/ProjectInfo.test.tsx, one-ui/ui/src/pages/ProjectInfo.tsx, one-ui/ui/src/util/auth-context.tsx
DHFPROD-3990:Display project information in UI
=> DHFPROD-3990:Display project information in UI

one-ui/ui/src/components/login-form/login-form.module.scss, one-ui/ui/src/components/login-form/login-form.tsx, one-ui/ui/src/pages/Login.module.scss, one-ui/ui/src/pages/Login.tsx
Third try for this due to conflict/rebase issues:
- Apply inline validation messaging to hostname, username, and password fields.
- Move error messaging to the top of form, as shown in the wireframe, and use Ant Design alert component for message.
- Refactor form to use flexbox for better layout control.
- Keep submit button disabled until all required fields have inputs.
PR replaces: https://github.com/marklogic/marklogic-data-hub/pull/3506
=> DHFPROD-3978: Updates to login UI

one-ui/ui/src/pages/ProjectInfo.tsx
Display the right values in the UI
=> DHFPROD-3990:Display the right values in the UI

Jenkinsfile
Pass testing=true to all gradle commands
=> DHFPROD-4086: Fixing issues to run Example projects

marklogic-data-hub/src/main/java/com/marklogic/hub/HubProject.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, one-ui/src/main/java/com/marklogic/hub/oneui/controllers/EnvironmentController.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/EnvironmentControllerTest.java, one-ui/ui/src/pages/ProjectInfo.tsx
=> DHFPROD-3788:Download project

one-ui/ui/config-overrides.js, one-ui/ui/src/App.css, one-ui/ui/src/components/load-data/load-data-card.module.scss, one-ui/ui/src/components/load-data/load-data-card.tsx, one-ui/ui/src/components/load-data/load-data-list.module.scss, one-ui/ui/src/components/load-data/load-data-list.test.tsx, one-ui/ui/src/components/load-data/load-data-list.tsx, one-ui/ui/src/components/load-data/new-data-load-dialog/new-data-load-dialog.module.scss, one-ui/ui/src/components/load-data/new-data-load-dialog/new-data-load-dialog.tsx, one-ui/ui/src/components/load-data/switch-view.module.scss, one-ui/ui/src/components/login-form/login-form.module.scss, one-ui/ui/src/config/conversionFunctions.config.tsx, one-ui/ui/src/pages/Home.module.scss, one-ui/ui/src/pages/Home.tsx, one-ui/ui/src/pages/LoadData.module.scss, one-ui/ui/src/pages/LoadData.tsx
This consists of few bug fixes for the new data load artifact dialog.
=> DHFPROD-3986: Few bug fixes for New/Edit Data load artifact Dialog

web/e2e/specs/dashboard/dashboard.ts, web/e2e/specs/flows/steps/ingestion.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts
Other than fixing tests, this PR has a commit to correctly handle mapping steps that were created outside of QS.
Following are the links of QS test runs with this PR in Jenkins:
https://jenkins.marklogic.com/view/DHF-9.0-Server-All/job/5.x/job/NO_CI_dhf-qs-develop-rh7_10_ReleaseBuild/60/
https://jenkins.marklogic.com/view/DHF-9.0-Server-All/job/5.x/job/NO_CI_dhf-qs-develop-rh7_10_ReleaseBuild/61/
https://jenkins.marklogic.com/view/DHF-9.0-Server-All/job/5.x/job/NO_CI_dhf-qs-develop-rh7_10_ReleaseBuild/62/
=> DHFPROD-4295: Fix QS Test to address changes in permissions to steps

one-ui/src/main/java/com/marklogic/hub/oneui/services/EnvironmentConfig.java, one-ui/src/main/java/com/marklogic/hub/oneui/services/EnvironmentService.java, one-ui/ui/src/components/install-form/install-form.tsx, one-ui/ui/src/pages/ProjectInfo.tsx, one-ui/ui/src/util/auth-context.tsx, one-ui/ui/src/util/environment.tsx
Provide host, stagingPort info to UI and some refactoring
=> DHFPROD-4258:Provide host, stagingPort info to UI and some refactoring

one-ui/ui/src/components/load-data/load-data-card.module.scss, one-ui/ui/src/components/load-data/load-data-card.tsx, one-ui/ui/src/components/load-data/load-data-list.module.scss, one-ui/ui/src/components/load-data/load-data-list.tsx, one-ui/ui/src/components/load-data/new-data-load-dialog/new-data-load-dialog.tsx, one-ui/ui/src/pages/LoadData.tsx
This contains the role based access related changes for stories 3915, 3916 and 3917.
=> DHFPROD-3916: Added support for Role based privileges

ml-data-hub-plugin/build.gradle
This is required for "gradle publishToMavenLocal" to work.
=> Bumping Gradle plugin to 1.9 compatibility

one-ui/src/main/java/com/marklogic/hub/oneui/controllers/EnvironmentController.java, one-ui/src/main/java/com/marklogic/hub/oneui/exceptions/CustomExceptionHandler.java, one-ui/src/main/java/com/marklogic/hub/oneui/models/HubConfigSession.java, one-ui/src/main/java/com/marklogic/hub/oneui/services/DataHubService.java, one-ui/src/main/java/com/marklogic/hub/oneui/services/EnvironmentService.java, one-ui/ui/src/components/install-form/install-form.module.scss, one-ui/ui/src/components/install-form/install-form.tsx, one-ui/ui/src/components/login-form/login-form.module.scss, one-ui/ui/src/components/login-form/login-form.tsx, one-ui/ui/src/pages/Install.module.scss, one-ui/ui/src/pages/Install.tsx
- Middle-tier error handling and messaging, including suggestions for different error types
- Front-end form validation and submit button disabling
- Hide "remember me" and "forgot password" functionality for now
- Layout refactoring
- Link to dashboard after successful installation
=> DHFPROD-3784: Login and Install UI functionality

marklogic-data-hub/build.gradle
Adding ML Unit Tests to 'testAcceptance' for PR jobs.
./gradlew testAcceptance will be run for PR jobs
=> DHFPROD-3837:Adding ML Unit Tests to 'testAcceptance' for PR jobs

one-ui/ui/src/components/login-form/login-form.tsx
"The host name "localhost" was not found." -> "The host "localhost" was not found."
Update approved by @sbayatpur.
=> Minor error message edit for login

one-ui/ui/src/App.tsx, one-ui/ui/src/pages/Home.module.scss, one-ui/ui/src/pages/Home.tsx, one-ui/ui/src/pages/LoadData.tsx, one-ui/ui/src/pages/ProjectInfo.tsx, one-ui/ui/src/pages/no-match-redirect.tsx
Perform endpoint call to check for 401 each route change.
Put a reset button on Home page for convenience.
Refactor App.tsx for cleaner routing.
Add typing to project info object.
Add redirect for 404s on App.tsx.
=> DHFPROD-4351: Auto logout after inactivity

one-ui/ui/src/App.tsx, one-ui/ui/src/components/header/header.module.scss, one-ui/ui/src/components/header/header.tsx
Logo/title redirects to install view when project has yet to be installed.
Also use application title from config file in header.
=> DHFPROD-4346: Install redirect

one-ui/ui/src/components/install-form/install-form.tsx
During a timeout, recognize the 401 status when installation is started and redirect to login.
=> DHFPROD-4420: Timeout redirect in install view

one-ui/src/main/java/com/marklogic/hub/oneui/controllers/EnvironmentController.java, one-ui/src/main/java/com/marklogic/hub/oneui/exceptions/CustomExceptionHandler.java, one-ui/src/main/java/com/marklogic/hub/oneui/exceptions/ProjectDirectoryException.java, one-ui/ui/src/components/install-form/install-form.tsx
Make sure error messages coming from the middle tier are displayed and are consistent with text approved by Docs.
=> DHFPROD-4419: Update install error handling

Jenkinsfile
=> DHFPROD-3837: Running only unit tests for PR

one-ui/src/test/java/com/marklogic/hub/oneui/services/EnvironmentServiceTest.java
https://project.marklogic.com/jira/browse/DHFPROD-4444
=> DHFPROD-4444: Fixed a test case failure

one-ui/src/main/resources/application.properties, one-ui/ui/src/components/load-data/new-data-load-dialog/new-data-load-dialog.module.scss, one-ui/ui/src/components/load-data/new-data-load-dialog/new-data-load-dialog.tsx, one-ui/ui/src/config/tooltips.config.js
1. Increased the limit of total file size to 100MB.
2. Added an error message when the upload fails upon reaching the 100MB limit.
3. Moved the help icons to right side of the form fields in New Data load Modal.
=> DHFPROD-4301: Uploading large file fails with no error

one-ui/ui/api/swagger/mocks.json
flowId is the flow name
stepId is a composite of 'stepName-stepType'
=> DHFPROD-3918: Update flowId and stepId descriptions

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/EnvironmentControllerTest.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/LoadDataControllerTest.java, one-ui/src/test/java/com/marklogic/hub/oneui/TestHelper.java
Fix was really simple and added a test but didnt run it. I would like to know how to run them locally.
Moved loadDataConfig object to testHelper so I can use it in EnvironmentControllerTest. We should probably discuss on how to arrange these tests so as to have a common helper class.
=> DHFPROD-4478: loadData artifact is now included in the downloaded zip

one-ui/src/test/java/com/marklogic/hub/curation/controllers/EnvironmentControllerTest.java, one-ui/src/test/java/com/marklogic/hub/oneui/TestHelper.java
create user and assign role to run unit tests with different users.
=> DHFPROD-4487: Add user creation to run unit tests

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/createEntityServicesMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/mappingWithTwoPropertiesWithSameObjectType.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/entities/Person.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/mappings/PersonMapping/PersonMapping-6.mapping.json
"m:entity" now refers to a unique property path instead of an entity type title.
=> DHFPROD-4285: Can now map multiple properties of the same entity type

Jenkinsfile
Fixing windows regression
Adding 9.0-12 linux regression
Adding windows 9.0-12 regression
=> DHFPROD-4525: Improvements to Pipeline

marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/DhsDeployer.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/deploy/DeployHubQueryRolesetsCommand.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployAsDeveloperTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/deploy/DeployHubQueryRolesetsCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/DeployProtectedPathsWhenUpdatingIndexesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubDeveloperTest.java
I'll create a separate PR for develop.
=> DHFPROD-4558: data-hub-developer can now deploy query rolesets

marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/DhsDeployer.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployAsDeveloperTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubDeveloperTest.java
See comments/assertions for why this is being done.
=> DHFPROD-4558: Changing order of deploying PPs and QRs

CHANGELOG.md, README.md, gradle.properties, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, ml-data-hub-plugin/gradle.properties, web/gradle.properties
Please check if the minimum ML version is correct in the READ ME file.
=> DHFPROD-4074: Update Versions and Change log

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mappings.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/mappingTest.sjs
The GUI isn't handling the 400 correctly yet, but I verified that the error message is present in the response sent to the GUI.
=> DHFPROD-4504: Mapping validation now fails when name is not unique

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MappingService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/service.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/testMapping.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/testMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/testMappingTest.sjs, one-ui/src/main/java/com/marklogic/hub/curation/controllers/MappingController.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/MappingControllerTest.java
https://project.marklogic.com/jira/browse/DHFPROD-4536
=> DHFPROD-4536: Middle-Tier - Use data service API to validate mapping

one-ui/ui/src/util/environment.tsx
Set 'project name' header correctly after installation
=> DHFPROD-4423:Set 'project name' header correctly after installation

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-match-merge-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-match-merge-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/matching.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/security/getAuthoritiesTest.sjs, one-ui/src/main/java/com/marklogic/hub/curation/controllers/MatchingController.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/MatchingControllerTest.java, one-ui/src/test/java/com/marklogic/hub/oneui/TestHelper.java, one-ui/ui/api/swagger/mocks.json, one-ui/ui/api/swagger/mocks.yaml, one-ui/ui/src/App.tsx, one-ui/ui/src/components/entities/entity-tiles.tsx, one-ui/ui/src/components/entities/matching/create-edit-matching-dialog/create-edit-matching-dialog.module.scss, one-ui/ui/src/components/entities/matching/create-edit-matching-dialog/create-edit-matching-dialog.test.tsx, one-ui/ui/src/components/entities/matching/create-edit-matching-dialog/create-edit-matching-dialog.tsx, one-ui/ui/src/components/entities/matching/matching-card.module.scss, one-ui/ui/src/components/entities/matching/matching-card.test.tsx, one-ui/ui/src/components/entities/matching/matching-card.tsx, one-ui/ui/src/config/tooltips.config.js, one-ui/ui/src/pages/EntityTypes.tsx, one-ui/ui/src/util/roles.tsx
=> DHFPROD-3994:CRUD matching artifact

marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MappingService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/getMappingFunctions.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/getMappingFunctions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getMappingFunctionsTest.sjs, one-ui/src/main/java/com/marklogic/hub/curation/controllers/MappingController.java, one-ui/src/main/java/com/marklogic/hub/oneui/models/HubConfigSession.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/MappingControllerTest.java
https://project.marklogic.com/jira/browse/DHFPROD-4537
Included a simple bug fix (newReverseFlowClient method in HubConfigSession class though we did not use it now in one-ui).
=> DHFPROD-4537: Middle-Tier: use data services to map functions

one-ui/ui/src/App.css, one-ui/ui/src/pages/ProjectInfo.module.scss, one-ui/ui/src/pages/ProjectInfo.tsx
https://project.marklogic.com/jira/browse/DHFPROD-4358
1. Fix button layout problem;
2. Make the upload button disable for unauthorized users;
3. Show warning message under the upload button
4. has a dependency on https://github.com/marklogic/marklogic-data-hub/pull/3639
=> DHFPROD-4358: UI: Hookup the middle-tier end point for upload project

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-explorer-architect.json, one-ui/src/main/java/com/marklogic/hub/oneui/managers/ModelManager.java, one-ui/src/test/java/com/marklogic/hub/oneui/managers/ModelManagerTest.java
Removed try/catch now that data-hub-explorer-architect can access the job-info data service.
=> DHFPROD-4519: Inherit from "data-hub-module-reader" role 

marklogic-data-hub/src/test/java/com/marklogic/bootstrap/Installer.java, one-ui/build.gradle, one-ui/src/test/java/com/marklogic/hub/curation/controllers/EnvironmentControllerTest.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/FlowControllerTest.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/LoadDataControllerTest.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/MappingControllerTest.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/MatchingControllerTest.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/fullcycle/EnvironmentControllerInstallTest.java, one-ui/src/test/java/com/marklogic/hub/oneui/AuthTest.java, one-ui/src/test/java/com/marklogic/hub/oneui/TestHelper.java, one-ui/src/test/java/com/marklogic/hub/oneui/managers/SearchManagerTest.java, one-ui/src/test/java/com/marklogic/hub/oneui/models/HubConfigSessionTest.java, one-ui/src/test/java/com/marklogic/hub/oneui/services/EnvironmentServiceTest.java, one-ui/src/test/resources/application-test.properties
=> DHFPROD-4604:Fix failing one-ui tests

one-ui/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss, one-ui/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, one-ui/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, one-ui/ui/src/config/data.config.js
Mapping with no source documents
=> DHFPROD-4366:Mapping with no source documents

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/FlowControllerTest.java, one-ui/src/test/java/com/marklogic/hub/oneui/TestHelper.java
Insert hub artifacts before runFlow() test
=> DHFPROD-4604: Insert hub artifacts runFlow() test

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mappings.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/matching.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/default/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/default/main.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/mappingTest.sjs, one-ui/src/test/java/com/marklogic/hub/curation/controllers/MappingControllerTest.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/MatchingControllerTest.java, one-ui/ui/api/swagger/mocks.json, one-ui/ui/api/swagger/mocks.yaml, one-ui/ui/src/components/common/dropdown-with-search/dropdownWithSearch.module.scss, one-ui/ui/src/components/common/dropdown-with-search/dropdownWithSearch.test.tsx, one-ui/ui/src/components/common/dropdown-with-search/dropdownWithSearch.tsx, one-ui/ui/src/components/entities/entity-tiles.tsx, one-ui/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.tsx, one-ui/ui/src/components/entities/mapping/mapping-card.test.tsx, one-ui/ui/src/components/entities/mapping/mapping-card.tsx, one-ui/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss, one-ui/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, one-ui/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, one-ui/ui/src/components/entities/matching/create-edit-matching-dialog/create-edit-matching-dialog.tsx, one-ui/ui/src/components/entities/matching/matching-card.tsx, one-ui/ui/src/config/tooltips.config.js, one-ui/ui/src/util/manageArtifacts-service.tsx, one-ui/ui/src/util/search-service.tsx
This PR contains changes for both DHFPROD-4171 and DHFPROD-4185.
=> DHFPROD-4171: Test and Clear buttons for mapping

CONTRIBUTING.md, gradle/wrapper/gradle-wrapper.properties, marklogic-data-hub/gradle.properties, one-ui/README.md, one-ui/gradle/wrapper/gradle-wrapper.properties, web/README.md
Updated Gradle wrapper to latest 5.x release - 5.6.4. 
Also updated README for one-ui.
I removed some of the instructions for forking and rebasing - I think we expect people to know how to manage a fork and branches, and there's of course plenty of info on the Internet for that. Just didn't want to maintain that information here too.
=> DHFPROD-4605: Updated CONTRIBUTING.md file

one-ui/ui/src/components/numeric-facet/numeric-facet.tsx, one-ui/ui/src/components/selected-facets/selected-facets.module.scss, one-ui/ui/src/components/sidebar/sidebar.tsx, one-ui/ui/src/pages/Browse.module.scss, one-ui/ui/src/pages/Browse.tsx
Also contains fix for DHFPROD-4648: Change api path for numeric facets.
=> DHFPROD-4615: Facet selections should be relocated under the search bar

.github/PULL_REQUEST_TEMPLATE.md
Adding a check list to the PR template.
```diff
```
=> DHFPROD-4662: Adding checklist to PR Template

one-ui/ui/src/App.scss, one-ui/ui/src/components/entities/entity-tiles.tsx, one-ui/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.tsx
This PR resolves the bug 4504.
```diff
```
=> DHFPROD-4504: Not able to persist mapping artifact with same name in another entity

NOTICE.txt
Including Notice.txt
```diff
```
=> DHFPROD-4522: Including new Notice.txt

one-ui/ui/src/components/activity-settings/activity-settings-dialog.test.tsx, one-ui/ui/src/components/activity-settings/activity-settings-dialog.tsx
Change default permissions, set them to 'data-hub-operator,read,data-hub-operator,update'
```diff
```
=> DHFPROD-4618:Change default permissions

one-ui/src/main/java/com/marklogic/hub/oneui/models/StepModel.java, one-ui/src/test/java/com/marklogic/hub/curation/controllers/FlowControllerTest.java
Remove "fileLocations" from flow declaration
```diff
```
=> DHFPROD-4610:Remove "fileLocations" from flow declaration

one-ui/ui/src/api/__mocks__/facets.tsx, one-ui/ui/src/api/facets.tsx, one-ui/ui/src/assets/mock-data/facet.js, one-ui/ui/src/components/numeric-facet/numeric-facet.test.tsx, one-ui/ui/src/components/numeric-facet/numeric-facet.tsx
=> DHFPROD-4632: Mock api endpoints using jest for RTL tests.

gradle.properties, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, ml-data-hub-plugin/gradle.properties, web/gradle.properties
Updating the version to use 5.2-SNAPSHOTS
```diff
```
=> DHFPROD-4698: Updating the version

marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/DhsDeployer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployAsDeveloperTest.java
=> DHFPROD-4697: hubDeploy now generates metadata for mapping functions

marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/deploy/DeployHubQueryRolesetsCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/deploy/DeployHubQueryRolesetsCommandTest.java
Also modifying the test so it only tests for an error on 10.0-3.
```diff
```
=> DHFPROD-4698: Bumping up logging to error for query roleset issue

one-ui/ui/src/components/load-data/new-data-load-dialog/new-data-load-dialog.test.tsx, one-ui/ui/src/components/load-data/new-data-load-dialog/new-data-load-dialog.tsx
=> DHFPROD-4621: Only upload data once

one-ui/build.gradle
=> DHFPROD-4699: Build and copy UI before building the war file

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/step.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/step/makeFunction.sjs
=> DHFPROD-4693: Providing better error when step module is not found

one-ui/ui/src/components/login-form/login-form.test.tsx, one-ui/ui/src/components/login-form/login-form.tsx
Tests for login component, with a minor change to initial state set to host. 
@wooldridge incase you run into issues with Reset, its already broken in develop. Will file a separate bug for that. Changes in this PR are not responsible for that.
This PR also demonstrates functional testing, by hitting APIs and mocking their response.
FYI @brucean52 @Sanjeevani19 @timur-isangulov 
```diff
```
=> DHFPROD-4539: unit and functional tests for login component

one-ui/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.test.tsx, one-ui/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.tsx, one-ui/ui/src/config/data.config.js
Added some tests for create/edit mapping component. Changed existing enzyme test to RTL test. Can be used as an example to write unit tests for other components.
@xnikhil08 I have commented out 3 tests, which needs code refactor. Please replace xtest with test to run and fix the code as applicable.
```diff
```
=> DHFPROD-3991: RTL tests for create/edit mapping config

one-ui/ui/src/components/entities/matching/create-edit-matching-dialog/create-edit-matching-dialog.test.tsx, one-ui/ui/src/components/entities/matching/create-edit-matching-dialog/create-edit-matching-dialog.tsx, one-ui/ui/src/config/matching-data.config.js
Add tests for CRUD matching step
```diff
```
=> DHFPROD-3994:Add tests for CRUD matching step

one-ui/ui/src/App.tsx, one-ui/ui/src/components/activity-settings/activity-settings-dialog.tsx, one-ui/ui/src/components/entities/entity-tiles.tsx, one-ui/ui/src/components/header/header.tsx, one-ui/ui/src/components/install-form/install-form.tsx, one-ui/ui/src/components/load-data/new-data-load-dialog/new-data-load-dialog.tsx, one-ui/ui/src/components/modal-status/modal-status.test.tsx, one-ui/ui/src/components/modal-status/modal-status.tsx, one-ui/ui/src/components/numeric-facet/numeric-facet.tsx, one-ui/ui/src/components/pop-over-search/pop-over-search.tsx, one-ui/ui/src/components/reset-env/reset-env.tsx, one-ui/ui/src/config/application.config.js, one-ui/ui/src/pages/Bench.tsx, one-ui/ui/src/pages/Browse.tsx, one-ui/ui/src/pages/Detail.tsx, one-ui/ui/src/pages/EntityTypes.tsx, one-ui/ui/src/pages/LoadData.tsx, one-ui/ui/src/pages/ProjectInfo.tsx, one-ui/ui/src/pages/View.test.tsx, one-ui/ui/src/pages/View.tsx, one-ui/ui/src/util/user-context.tsx
- Implementation requires all endpoints to call resetSessionTimer in finally block.
- Popup Warning timer is configurable in application.config.js ( use 290 for testing )
- Auto logout time can be changed for testing ( line 25 in modal-status.tsx ) set to 280
- Created modal-status.tsx component that I will later extend to support 500 network request errors.
```diff
```
=> DHFPROD-4375: Warning popout before automatic logout

CHANGELOG.md, gradle.properties, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, ml-data-hub-plugin/gradle.properties, web/gradle.properties
Updating versions and change log for 5.2.1
```diff
```
=> DHFPROD-4698: Updating version and Changelog

marklogic-data-hub/src/main/resources/overview.html
=> DHFPROD-2693:Linking to new docs site in Javadocs

ml-data-hub-plugin/build.gradle
Updating the publish plugin as the earlier version has security vulnerabilities and was depricated.
```diff
```
=> DHFPROD-4698: updating publish plugin

marklogic-data-hub/src/test/java/com/marklogic/bootstrap/Installer.java, marklogic-data-hub/src/test/java/com/marklogic/hub_unit_test/RunMarkLogicUnitTestsTest.java, marklogic-data-hub/src/test/ml-config/databases/final-database.json, marklogic-data-hub/src/test/resources/master-test/entities/person/person.entity.json
Also speeding up bootstrap by deploying the test final-database.json via a single call, as opposed to all the overhead of datahub.updateIndexes()
```diff
```
=> DHFPROD-4727: Fixing MasterTest failure

CHANGELOG.md, ml-data-hub-plugin/build.gradle
Adding changelog and plugin update. 
Note: Need two different commits as master.
```diff
```
=> DHFPROD-4698: Adding changelog and Plugin upgrade

one-ui/ui/src/util/data-conversion.tsx
=> DHFPROD-4714:Browse page goes blank on DHS Service

azure/flow-runner-function/src/main/java/com/marklogic/dhf/azure/FunctionDataHubFlow.java, azure/flow-runner-function/src/test/java/com/marklogic/dhf/azure/FunctionDataHubFlowTest.java
DHFPROD-4532: added asserts for test methods
rename the method to buildFlowInputs
```diff
```
=> DHFPROD-4532: impl for invoking the flow by taking params from req body

one-ui/src/test/java/com/marklogic/hub/oneui/controllers/ModelControllerTest.java
=> DHFPROD-4656: Fixed compilation error in ModelControllerTest

one-ui/ui/src/components/entities/entity-tiles.tsx, one-ui/ui/src/components/entities/mapping/mapping-card.tsx, one-ui/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss, one-ui/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, one-ui/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, one-ui/ui/src/config/data.config.js, one-ui/ui/src/util/xml-parser.tsx
This PR enables XML data support in Mapping source data table.
```diff
```
=> DHFPROD-4186: Map from XML source data

one-ui/ui/src/assets/mock-data/entity-table.js, one-ui/ui/src/components/entity-table/entity-table.test.tsx, one-ui/ui/src/components/entity-table/entity-table.tsx, one-ui/ui/src/util/data-conversion.tsx
=> DHFPROD-4655: add support for array type in entity view page

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, one-ui/ui/src/config/bench.config.ts, one-ui/ui/src/pages/Bench.test.tsx, one-ui/ui/src/pages/Bench.tsx, one-ui/ui/src/util/roles.tsx
See up to 10 mapping errors after step runs
```diff
```
=> DHFPROD-4399:See up to 10 mapping errors after step runs

one-ui/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.test.tsx, one-ui/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.tsx, one-ui/ui/src/components/entities/mapping/mapping-card.tsx, one-ui/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss, one-ui/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, one-ui/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, one-ui/ui/src/util/manageArtifacts-service.tsx
This PR contains changes for the story DHFPROD-4172 and fix for the bug DHFPROD-4690.
```diff
```
=> DHFPROD-4172: Added support for NestedEntity in Mapping and Bug Fix for DHFPROD-4690

marklogic-data-hub-central/src/test/java/com/marklogic/hub/curation/controllers/LoadDataControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/curation/controllers/MappingControllerTest.java, marklogic-data-hub-central/ui/src/components/activity-settings/activity-settings-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/activity-settings/activity-settings-dialog.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/loadData.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mappings.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/setGetSettingsTest.sjs, marklogic-data-hub/src/test/resources/flow-runner-test/flows/testFlow.flow.json, marklogic-data-hub/src/test/resources/flow-runner-test/loadData/testLoadData.settings.json
Certain settings weren't being accounted for when running a data load. Reading in those settings now. I also added the missing target format on the mapping settings form.
https://drive.google.com/open?id=1ymeBD_m5KvOnUBtLo3d_DVFFbEJFErW4
```diff
```
=> DHFPROD-4173: Apply additional settings in flow runner

Jenkinsfile
Running tests on 10.0-4 ML
```diff
```
=> DHFPROD-4758: Adding 10.0-4

marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java
Removed/modified assertions that expected the database to be empty after clearing it; it no longer is, as DHF core artifacts are no longer deleted
```diff
```
=> DHFPROD-4440: Fixing EndToEndFlowTests

marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.module.scss, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-4630:Revert or remove unapplied facet selections

marklogic-data-hub-central/ui/e2e/setup.sh
Adding --info to the gradle tasks in qa-project for datahub deployment logs
```diff
```
=> DHFPROD-4725: Adding info to the gradle tasks in qa-project for deployment logs

marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java
=> DHFPROD-4440: Today's fixes for E2E tests

marklogic-data-hub-central/ui/demo-customer/build.gradle
=> Adding nexus url

marklogic-data-hub-central/ui/demo-customer/gradle.properties
=> Adding ml credentials

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-common-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-common.json, specs/docs/security/DataHubSecurity.md, specs/models/AuthoritiesList.v1.json, specs/reference/data-services/security.v1.json, specs/reference/rest-endpoints/security.v1.json
=> DHFPROD-4625: Hub Central Security functional spec

marklogic-data-hub/src/test/java/com/marklogic/hub_integration/MappingE2E.java, marklogic-data-hub/src/test/java/com/marklogic/hub_integration/StreamLegacyCollectorTest.java
Either fixed assertions on the number of docs in a database, or removed them when not necessary
```diff
```
=> DHFPROD-4440: More E2E test fixes

marklogic-data-hub-central/ui/src/components/load-data/load-data-list.test.tsx, marklogic-data-hub-central/ui/src/components/load-data/load-data-list.tsx, marklogic-data-hub-central/ui/src/config/data.config.js
=> DHFPROD-4617: RTL test for bug DHFPROD-4617

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EntitySearchController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/managers/EntitySearchManager.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/models/DocSearchQueryInfo.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractMvcTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/EntitySearchControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/managers/EntitySearchManagerTest.java, marklogic-data-hub-central/ui/src/components/date-facet/date-facet.tsx, marklogic-data-hub-central/ui/src/components/date-time-facet/date-time-facet.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.tsx, marklogic-data-hub-central/ui/src/components/numeric-facet/numeric-facet.tsx, marklogic-data-hub-central/ui/src/components/result-table/result-table.tsx, marklogic-data-hub-central/ui/src/components/search-bar/search-bar.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/View.tsx, marklogic-data-hub-central/ui/src/services/user-preferences.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/EntitySearchService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/deleteSavedQuery.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/deleteSavedQuery.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/entitysearch/EntitySearchServiceTest.java
Delete saved personal queries feature
Refactoring Search API to match with SavedQueries feature
```diff
```
=> DHFPROD-3650: Delete saved personal queries feature

Jenkinsfile
- Adding info to test tasks.
- Re arranging the order of tests
- Adding a new checklist item.
```diff
```
=> DHFPROD-4526: Adding info to gradle tasks

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/ds-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/saveSavedQuery.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/security/getAuthorities.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/security.sjs
=> DHFPROD-4802: Adding authorities to saved-queries artifact

marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/config/data.config.js, marklogic-data-hub-central/ui/src/util/test-utils.tsx
This PR contains adds the Filtering and Sorting capability in Mapping Source and Entity tables.
Also adds a Column Option Selector for Entity table.
```diff
```
=> DHFPROD-3020: Filtering, Sorting in Source/Entity Mapping tables and Column Option Selector in Entity Table

marklogic-data-hub-central/ui/src/config/bench.config.ts, marklogic-data-hub-central/ui/src/pages/Bench.test.tsx, marklogic-data-hub-central/ui/src/pages/Bench.tsx
This PR includes unit test for errors in running load data step in a flow along with commenting out console.log in Bench.tsx
```diff
```
=> DHFPROD-4025: unit test for failed jobStatus and some refactoring

Jenkinsfile
need to run the war with --hubUseLocalDefaults=true for running it on local env.
```diff
```
=> DHFPROD-4847: Fixing e2e tests

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-entity-exporter.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/security.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/core/HubProjectTest.java
=> DHFPROD-4728: Adding roles and users to export entity instances

marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/config/bench.config.ts, marklogic-data-hub-central/ui/src/config/roles.config.ts, marklogic-data-hub-central/ui/src/pages/Bench.test.tsx, marklogic-data-hub-central/ui/src/pages/Bench.tsx
Tests running mapping steps as data-hub-developer and data-hub-operator. Also move mock roles service objects to roles.config.ts for test reuse.
```diff
```
=> DHFPROD-3992: Add tests for running mapping steps

marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.module.scss, marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/config/data.config.js
Source fields dropdown for Mapping and filtering
```diff
```
=> DHFPROD-4189:Source fields dropdown for Mapping and filtering

azure/flow-runner-function/pom.xml, azure/flow-runner-function/src/main/java/com/marklogic/dhf/azure/FunctionDataHubFlow.java
DHFPROD-4532: flowrunner to handle direct or loadbalancer connectivity
```diff
```
=> DHFPROD-4532: flowrunner to handle direct or loadbalancer connectivity

marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/api/__mocks__/queries.tsx, marklogic-data-hub-central/ui/src/api/queries.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/query.js, marklogic-data-hub-central/ui/src/components/queries/managing/edit-query-dialog/edit-query-dialog.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.module.scss, marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.test.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.module.scss, marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.test.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.tsx, marklogic-data-hub-central/ui/src/components/search-bar/search-bar.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.test.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-4198:Create Save Query UI Component,DHFPROD-4628:Handle "save" and "save as" when there are unapplied changes

marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/WebMvcConfig.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EntitySearchController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/managers/EntitySearchManager.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractHubCentralTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractMvcTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/TestConstants.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/EntitiesControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/EntitySearchControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/MappingControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/MatchingControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/environment/DownloadConfigurationFilesTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/managers/EntitySearchManagerTest.java, marklogic-data-hub-central/src/test/resources/test-projects/reference-project/entities/Customer.entity.json, marklogic-data-hub-central/ui/api/swagger/mocks.json, marklogic-data-hub-central/ui/api/swagger/mocks.yaml, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/EntitySearchService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getOpticPlan.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getOpticPlan.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/models/GetPrimaryEntityTypesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStepWithProcessorsTest.java, marklogic-data-hub/src/test/resources/entity-reference-model/entities/Customer.entity.json, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/Customer.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/ReferenceModelProject.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/AfterModulesLoadedCallback.java
=> DHFPROD-4226: Export rows as csv

examples/reference-entity-model/src/main/ml-config/security/users/bertand.json
Added Bertrand the business analyst to the reference project for demo
```diff
```
=> DHFPROD-4864: Add business analyst user

specs/models/Flow.schema.json, specs/models/MasterCollections.v1.json, specs/models/MatchStep.v1.json, specs/models/MergeStep.v1.json, specs/models/Step.v1.json, specs/models/StepSettings.v1.json, specs/reference/data-services/mastering.v1.json, specs/reference/rest-endpoints/mastering.v1.json
Internal functional spec can be found here: https://wiki.marklogic.com/display/ENGINEERING/Hub+Central+Mastering+Design+Specification
```diff
```
=> DHFPROD-4624: functional spec APIs for mastering in Hub Central

marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/config/data.config.js, marklogic-data-hub-central/ui/src/util/test-utils.tsx
This PR only contains fixes for some issues. No tests required here as the unit tests are already being added as part of the story(4171) itself.
```diff
```
=> DHFPROD-4171: Fixed few issues raised in testing of TEST and CLEAR buttons

marklogic-data-hub-central/ui/src/components/activity-settings/activity-settings-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/activity-settings/activity-settings-dialog.tsx
Trivial fixes (no tests necessary):
- Make placeholder text consistent.
- Remove console.log messages or convert them to console.error messages.
```diff
```
=> DHFPROD-4726: Fix placeholder text, console messages

marklogic-data-hub-central/README.md
=> DHFPROD-4797: Updating HC README to capture how to use hubInit

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
Fix Column alignment in entity table. This is due to an issue with antd where table headers are misaligned if scroll 'y' is set. It is not needed here anyway, so removing it. I don't think this requires a test
```diff
```
=> DHFPROD-4756:Fix Column alignment in entity table

marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/edit-query-dialog/edit-query-dialog.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-4861: Query needs to be selected by default after saving a query

marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/user-context-mock.js, marklogic-data-hub-central/ui/src/components/modal-status/modal-status.test.tsx, marklogic-data-hub-central/ui/src/components/modal-status/modal-status.tsx
=> DHFPROD-4654: Added 500 error support to hub central

Jenkinsfile, marklogic-data-hub-central/build.gradle
Removed TestFullCycle from pipeline
Removed testFullCycle Task
Added publish task
```diff
```
=> DHFPROD-4897: Task to publish hubcentral war to nexus

marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/result-table/result-table.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/util/user-context.tsx
=> DHFPROD-4776: Fixed faceting persistence between Snippet and Table View

marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/gradle.properties, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/Application.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/SwaggerConfig.java, marklogic-data-hub-central/src/main/resources/application.properties
Tossing SwaggerConfig into dev profile so we have an easy way of omitting it
```diff
```
=> DHFPROD-4887: Enabling Spring profiles

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/environment/ClearUserDataTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
=> DHFPROD-4775: Fix for ClearUserDataTest

marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/util/environment.tsx, marklogic-data-hub-central/ui/src/util/user-context.tsx
Add back the snippet used for page redirect which shouldn't have been removed in the previous PR
```diff
```
=> DHFPROD-4768:Fix route changes

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/AuthoritiesListV1.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/StepSettingsSchema.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/LoadDataControllerTest.java, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/loadData.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mapping.sjs
=> DHFPROD-4917: Add headers info to load data artifacts

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
Enable scrolling in entity table
```diff
```
=> DHFPROD-4756:Enable scrolling in entity table

marklogic-data-hub-central/ui/e2e/cypress/fixtures/users/developer.json, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/query/manage-queries-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.test.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/config/authorities.config.ts, marklogic-data-hub-central/ui/src/util/authorities.tsx
=> DHFPROD-4728: Grant role to allow user to export data

marklogic-data-hub-central/ui/src/pages/ProjectInfo.tsx
Remove "Project Directory" from project info page
```diff
```
=> DHFPROD-4768:Remove "Project Directory" from project info page

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/auth/AuthenticationFilter.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/auth/LoginFailureHandler.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/PrimaryEntityType.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/auth/AuthTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/EntitySearchControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/environment/ClearUserDataTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/environment/DownloadConfigurationFilesTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-login-to-hub-central.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-clear-user-data.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-downloader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-entity-exporter.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-user.json, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/Installer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub_unit_test/RunMarkLogicUnitTestsTest.java, marklogic-data-hub/src/test/ml-config/security/amps/dh-test-user-roles.json, marklogic-data-hub/src/test/ml-config/security/roles/data-hub-test-internal.json, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.sjs, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.xqy, marklogic-data-hub/src/test/ml-modules/root/test/invoke/create-test-role.xqy, marklogic-data-hub/src/test/ml-modules/root/test/invoke/create-test-user.xqy, marklogic-data-hub/src/test/ml-modules/root/test/invoke/delete-test-role.xqy, marklogic-data-hub/src/test/ml-modules/root/test/invoke/delete-test-user.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/getAuthoritiesTest.sjs, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
=> DHFPROD-4668: Add hub-central-user role

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java, marklogic-data-hub-central/src/test/resources/test-projects/reference-project/loadData/testLoadData.loadData.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs
=> DHFPROD-4917: Ensure headers property in loadData survives edit

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/PrimaryEntityType.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/LoadDataControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/MappingControllerTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/loadData.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mapping.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-es.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/setGetSettingsTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/testGetFullFlow.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/hubEsTest.sjs
=> DHFPROD-4888: Add entity type title as collection to mapped documents

marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/config/data.config.js
This PR fixes the dropdown issues in the Function selector and Source selector in Mapping UI.
```diff
```
=> DHFPROD-4185: Fixing the event bubbling issue in dropdown component

marklogic-data-hub-central/ui/e2e/cypress/support/pages/modeling.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.module.scss, marklogic-data-hub-central/ui/src/pages/Modeling.tsx
=> DHFPROD-4896: UX fixes for Add Entity Modal

Jenkinsfile
=> DHFPROD-4760: Running tests on DHS for every commit

marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/user-context-mock.js, marklogic-data-hub-central/ui/src/components/modal-status/modal-status.test.tsx, marklogic-data-hub-central/ui/src/components/modal-status/modal-status.tsx, marklogic-data-hub-central/ui/src/pages/ProjectInfo.tsx, marklogic-data-hub-central/ui/src/util/user-context.tsx
Timeout pop up should not close an open modal
```diff
```
=> DHFPROD-4739:Timeout pop up should not close an open modal

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/config/data.config.js
This PR implements the feature given in the ticket DHFPROD-4845.
```diff
```
=> DHFPROD-4845: Refine filtered results so nested elements with no filtered results do not appear

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
Fix the logic for fetching entities, setting targetEntityType and sourceContext. The existing tests should run fine. Additionally, this will require e2e which @bsrikan will add.
```diff
```
=> DHFPROD-4961:Fix the logic for fetching entities,setting targetEntityType and sourceContext

CONTRIBUTING.md
Fixing a minor typo that I noticed.
```diff
```
=> DHFPROD-4666: Fix typo in contributing.md

marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.module.scss, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.test.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx
=> DHFPROD-4719: Show warning if object or array datatype present.

_pages/refs/version-compatibility.md
- Removed all references to 5.x since this is 4.x documentation.
- Added 2.0.7 row.
- Added a link to the equivalent page in the 5.x docs.
```diff
```
- [n/a - Branch created from upstream less than an hour ago.] Rebase the branch with upstream
- [only one commit] Squashed all commits into a single commit
=> DHFPROD-4468: Docs: Updating/Correcting documentation about version compatibility

marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/discard-changes/discard-changes-modal.test.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/discard-changes/discard-changes-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx
=> DHFPROD-4635:Discard changes to revert back to original saved query

Jenkinsfile
=> DHFPROD-4898: Archiving the results with mlversion

Jenkinsfile
=> DHFPROD-4898: Adding the link to PR in the email notification

marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
Also includes DHFPROD-4927
```diff
```
=> DHFPROD-4926:Dropdown value should reset to 'select a query' when the query is deleted	

marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx
An attempt to fix the failing test for run test tile. @xnikhil08 there seems to be some work required after all.
```diff
```
=> DHFPROD-4772: Test for run tile

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
Persist source filter across documents. e2e test will be added by @bsrikan 
```diff
```
=> DHFPROD-4784:Persist source filter across documents

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/MappingController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/MappingControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/MappingMvcTest.java, marklogic-data-hub-central/ui/e2e/cypress/fixtures/users/developer.json, marklogic-data-hub-central/ui/e2e/cypress/fixtures/users/operator.json, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.test.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/config/bench.config.ts, marklogic-data-hub-central/ui/src/pages/EntityTypes.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-read-mapping.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-common.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-mapping-reader.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/security.sjs, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/Installer.java, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/testMappingTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/security/getAuthoritiesTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/getAuthoritiesTest.sjs
=> DHFPROD-4673: Add hub-central-mapping-reader role

_pages/refs/version-compatibility.md
Incorporated Kiran's feedback in previous PR.
```diff
```
- [n/a] Rebase the branch with upstream
- [n/a] Squashed all commits into a single commit
=> DHFPROD-4468: Updating/Correcting documentation about version compatibility

marklogic-data-hub-central/ui/src/App.tsx
Scoped the TileView inside SearchProvider
```diff
```
=> DHFPROD-5025: fix Explorer in tile UI

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx
Added test for the bug fix.
```diff
```
=> DHFPROD-4961: Test for duplicate property names in mapping expression

marklogic-data-hub-central/ui/src/components/activity-settings/activity-settings-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/components/load-data/load-data-list.test.tsx, marklogic-data-hub-central/ui/src/config/test-data.config.js
Fix placement of ellipsis for array values. 
```diff
```
=> DHFPROD-4866: Fix placement of ellipsis for array values

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowMigrator.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowMigratorTest.java, marklogic-data-hub/src/test/resources/flow-migration-test/entities/Order.entity.json, marklogic-data-hub/src/test/resources/flow-migration-test/entities/Person.entity.json, marklogic-data-hub/src/test/resources/flow-migration-test/flows/custom_only-flow.flow.json, marklogic-data-hub/src/test/resources/flow-migration-test/flows/ingestion_mapping-flow.flow.json, marklogic-data-hub/src/test/resources/flow-migration-test/flows/ingestion_mapping_mastering-flow.flow.json, marklogic-data-hub/src/test/resources/flow-migration-test/mappings/OrderMappingJson/OrderMappingJson-1.mapping.json, marklogic-data-hub/src/test/resources/flow-migration-test/mappings/OrderMappingXml/OrderMappingXml-1.mapping.json, marklogic-data-hub/src/test/resources/flow-migration-test/mappings/xmlToXml-mapXmlToXml/xmlToXml-mapXmlToXml-1.mapping.json, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/FlowMigrationTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/FlowMigratonTaskTest.groovy
Migrate flows and mappings to flows and steps
```diff
```
=> DHFPROD-4956:Migrate flows and mappings to flows and steps

marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/api/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/edit-query-dialog/edit-query-dialog.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/query-export/export-preview/export-preview.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.module.scss, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.test.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export.tsx, marklogic-data-hub-central/ui/src/components/result-table/result-table.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/util/data-conversion.tsx
Includes : https://project.marklogic.com/jira/browse/DHFPROD-4718 
```diff
```
=> DHFPROD-4225: Check and confirm before starting the export

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowMigrator.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowMigratorTest.java
Add 'stepId' to every created step
```diff
```
=> DHFPROD-4956:Add 'stepId' to every created step

marklogic-data-hub-central/ui/config-overrides.js, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/header/header.tsx, marklogic-data-hub-central/ui/src/components/load-data/load-data-list.tsx, marklogic-data-hub-central/ui/src/components/login-form/login-form.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/pages/noMatchRedirect.tsx
App and unit tests run ok.
```diff
```
=> DHFPROD-4980: Add Marklogic Design System

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowMigrator.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowMigratorTest.java
Ensure the DS endpoint returns migrated flows correctly
```diff
```
=> DHFPROD-4956:Ensure the DS endpoint returns migrated flows correctly

examples/reference-entity-model/src/main/ml-config/security/users/hub-developer.json, examples/reference-entity-model/src/main/ml-config/security/users/hub-operator.json, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MappingStepController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/AuthoritiesListV1.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/MappingControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/MappingMvcTest.java, marklogic-data-hub-central/ui/e2e/cypress/fixtures/users/developer.json, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.test.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-write-mapping.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-common-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-mapping-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-mapping-writer.json, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/Installer.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/getAuthoritiesTest.sjs
=> DHFPROD-4674: Add hub-central-writer role

examples/reference-entity-model/build.gradle, examples/reference-entity-model/steps/ingestion/loadCustomersJSON.step.json, examples/reference-entity-model/steps/ingestion/loadCustomersXML.step.json, examples/reference-entity-model/steps/mapping/mapCustomersJSON.step.json, examples/reference-entity-model/steps/mapping/mapCustomersXML.step.json, examples/reference-entity-model/testData/customers/customer1.json, examples/reference-entity-model/testData/customers/customer2.json
The focus of this is just to simplify use of different roles with hc-nightly
```diff
```
=> DHFPROD-5056: Align settings between load and mapping steps in reference project

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java
Make use of saveLocalFlow() when upgrading flows
```diff
```
=> DHFPROD-4702:Make use of saveLocalFlow() when upgrading flows

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelControllerTest.java
=> DHFPROD-5062: Fix testModelsServicesEndpoints test

marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.test.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.tsx, marklogic-data-hub-central/ui/src/config/tiles.config.ts, marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx
This PR contains the changes for the tickets DHFPROD-4819 and DHFPROD-4820.
The existing tests were fixed to adhere to the newly added authorities.
```diff
```
=> DHFPROD-4820: Adding authorities in Modeling and Tile view components

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/scaffold/Scaffolding.java, marklogic-data-hub/src/main/resources/scaffolding/defaultFlow.flow.json, marklogic-data-hub/src/main/resources/scaffolding/flowName.flow.json, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/exception/FlowAlreadyPresentException.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateFlowTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateFlowTaskTest.groovy
Added some logging to hubCreateFlow and a description for it too.
```diff
```
=> DHFPROD-4955: hubCreateFlow now defaults to an empty flow

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractMvcTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/environment/ClearUserDataTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/environment/DownloadProjectFilesMvcTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/CreateModelMvcTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelMvcTest.java, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.test.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.tsx, marklogic-data-hub-central/ui/src/config/tiles.config.ts, marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-read-entity-model.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-write-entity-model.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-entity-model-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-entity-model-writer.json
=> DHFPROD-4820: and DHFPROD-4819 entity reader/writer

_pages/refs/security.md
Added a note in the Security page.
```diff
```
- [n/a New branch.] Rebase the branch with upstream
- [n/a] Squashed all commits into a single commit
=> DHFPROD-5021: Docs 4.x: Clarifying Data Hub docs about the allowed authentication methods

Jenkinsfile
=> DHFPROD-5045: Adding Code-coverage reports

CHANGELOG.md, gradle.properties, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, ml-data-hub-plugin/gradle.properties, pipeline.properties, web/gradle.properties
```diff
```
- [N/A ] Squashed all commits into a single commit
=> DHFPROD-5082: Updating versions

marklogic-data-hub-central/ui/src/components/load-data/new-data-load-dialog/new-data-load-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/load-data/new-data-load-dialog/new-data-load-dialog.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/client/CommandLineFlowInputs.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/loadData.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/client/CommandLineFlowInputsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/client/RunFlowViaMainTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/WriteStepRunnerTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/convertIngestionStep.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/manageIngestionStep.sjs, marklogic-data-hub/src/test/resources/flow-runner-test/flows/runXqyFuncFlow.flow.json, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/RunFlowTask.groovy, specs/models/Flow.schema.json
Add 'outputURIPrefix' in ingestion step, replace "OutputURI Replacement" from HC
```diff
```
=> DHFPROD-4932:Add 'outputURIPrefix' in ingestion step, replace "OutputURI Replacement" from HC

marklogic-data-hub-central/ui/e2e/cypress/integration/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.table.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/view-entities.validation.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/application.config.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/home.tsx, marklogic-data-hub-central/ui/src/config/application.config.js
=> DHFPROD-4792: Change product name in Hub Central

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowMigrator.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowMigratorTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowMigratorUnitTest.java, marklogic-data-hub/src/test/resources/flow-migration-test/flows/custom_only-flow.flow.json, marklogic-data-hub/src/test/resources/flow-migration-test/flows/ingestion_mapping-flow.flow.json, marklogic-data-hub/src/test/resources/flow-migration-test/flows/ingestion_mapping_mastering-flow.flow.json, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/FlowMigrationTask.groovy
Tweaked the logging a bunch so lots is shown at the "warn" level so it'll show up when running the Gradle task, even without "-i". 
Extracted some protected methods from FlowMigrator for easy unit testing.
I figure if we run into any issues during testing, it should be easy to reproduce them via unit tests.
```diff
```
=> DHFPROD-5057: Updates to flow migration

CHANGELOG.md
=> DHFPROD-5082: Updating changelog for 5.2.2

marklogic-data-hub/src/main/java/com/marklogic/hub/HubProject.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/CreateStepTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateStepTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateStepTaskTest.groovy
=> DHFPROD-4954: Can now create a step via Gradle

examples/reference-entity-model/src/main/ml-config/security/users/bertand.json, examples/reference-entity-model/src/main/ml-config/security/users/hub-developer.json, examples/reference-entity-model/src/main/ml-config/security/users/hub-operator.json, examples/reference-entity-model/src/main/ml-config/security/users/pari.json, examples/reference-entity-model/src/main/ml-config/security/users/stewart.json, examples/reference-entity-model/src/main/ml-config/security/users/wailin.json
=> DHFPROD-5088: Adding roles to the users

examples/reference-entity-model/src/main/ml-config/security/users/hub-developer.json, examples/reference-entity-model/src/main/ml-config/security/users/pari.json, examples/reference-entity-model/src/main/ml-config/security/users/wailin.json, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/IngestionStepController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/IngestionStepControllerTest.java, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/config/load.config.ts, marklogic-data-hub-central/ui/src/config/mocks.config.ts, marklogic-data-hub-central/ui/src/pages/Load.test.tsx, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-write-ingestion.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-common-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-ingestion-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-ingestion-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-mapping-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-load-writer.json, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/Installer.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/getAuthoritiesTest.sjs
=> DHFPROD-4672: Add hub-central-load-writer role

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/config/test-data.config.js
This PR just fixes few tests related to step name as default collection in Advanced Settings.
```diff
```
=> DHFPROD-4388: Adding tests for step name as default collection in Advanced Settings Dialog

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-common-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-entity-model-writer.json
also, add xslt-invoke to common-writer
```diff
```
=> DHFPROD-5094: Make model-writer inherit from common-writer role

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/Headers__1.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/Processor__1.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/StepSettingsSchema.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/Vars__1.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/IngestionStepControllerTest.java, specs/models/StepSettings.schema.json
=> DHFPROD-4969: Backend work passing headers/processors in settings

ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/SslTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/TlsTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/BaseTest.groovy
Fix for failing gradle ssl/tls tests
```diff
```
=> DHFPROD-5104:Fix for failing gradle ssl/tls tests

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/HubCentral.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/LoadDataController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/exceptions/CustomExceptionHandler.java, marklogic-data-hub-central/src/main/resources/application.properties, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowMvcTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/FlowControllerTest.java, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.tsx, marklogic-data-hub-central/ui/src/config/run.config.ts, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub/src/test/resources/entity-reference-model/flows/ingestToFinal.flow.json
Run load step with selected files
```diff
```
=> DHFPROD-4904:Run load step with selected files

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/StepSchema.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/StepSettingsSchema.java, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/config/load.config.ts, marklogic-data-hub-central/ui/src/config/run.config.ts, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/loadData.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mapping.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/matching.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/mappingTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/setGetTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/convertMappingStep.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/manageIngestionStep.sjs, specs/models/Step.schema.json, specs/models/StepSettings.schema.json
Add 'Batch size' field to all steps created from HC
```diff
```
=> DHFPROD-4972:Add 'Batch size' field to all steps created from HC

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowMvcTest.java, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx
Fix a test, make cosmetic changes to ui
```diff
```
=> DHFPROD-4904:Fix a test, make cosmetic changes to ui

marklogic-data-hub-central/ui/e2e/cypress/integration/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.modeling.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.table.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/view-entities.validation.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/index.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/projectInfo.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/tiles.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/toolbar.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/index.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-table.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/query/manage-queries-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/detail.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/home.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/login.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/view.tsx, marklogic-data-hub-central/ui/src/components/login-form/login-form.tsx, marklogic-data-hub-central/ui/src/config/mocks.config.ts, marklogic-data-hub-central/ui/src/pages/ProjectInfo.test.tsx
Login e2e tests.
Refactored how page objects were being imported
```diff
```
=> DHFPROD-5052: login e2e tests and refactoring of page object imports

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/config/mocks.config.ts, marklogic-data-hub-central/ui/src/config/run.config.ts, marklogic-data-hub-central/ui/src/pages/Curate.test.tsx, marklogic-data-hub-central/ui/src/pages/Load.test.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx
Includes test updates to load and mapping with reader/writer authorities per test plan
```diff
```
=> DHFPROD-4671: Test updates

marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx
This PR contains changes for below mentioned tickets.
1. DHFPROD-5031: Add a load step to a new flow
2. DHFPROD-4749: Add a mapping step to a new flow
```diff
```
=> DHFPROD-5031: Adding load and mapping steps to flows

marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.modeling.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/confirmation-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/index.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-table.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/structured-type-modal.tsx, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/assets/mock-data/modeling.js, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.module.scss, marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.tsx, marklogic-data-hub-central/ui/src/config/confirmation-modal.config.js, marklogic-data-hub-central/ui/src/config/modeling.config.ts, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub-central/ui/src/types/modeling-types.ts, marklogic-data-hub-central/ui/src/util/data-conversion.tsx
=> DHFPROD-4177: Create new structured type property

examples/step-processors/README.md, marklogic-data-hub/src/main/java/com/marklogic/hub/collector/impl/FileCollector.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStepWithProcessorsTest.java, marklogic-data-hub/src/test/resources/entity-reference-model/flows/stepProcessors.flow.json, marklogic-data-hub/src/test/resources/entity-reference-model/modules/root/custom-modules/step-processors/onIngest.sjs
Also added a test for verifying that an ingestion step processor can modify the URI of a document.
And improved error handling in FileCollector, which now includes the directory path in the error message (which I ran into while getting the test together).
```diff
```
=> DHFPROD-5129: Improving step processor example project docs

examples/reference-entity-model/input/json/Cust1.json, examples/reference-entity-model/input/json/Cust2.json, examples/reference-entity-model/input/json/Cust3.json, examples/reference-entity-model/input/json/Cust4.json, examples/reference-entity-model/input/json/Cust5.json, examples/reference-entity-model/input/xml/CustXMLDoc1.xml, examples/reference-entity-model/input/xml/CustXMLDoc2.xml, examples/reference-entity-model/input/xml/CustXMLDoc3.xml, examples/reference-entity-model/input/xml/CustXMLDoc4.xml, examples/reference-entity-model/input/xml/CustXMLDoc5.xml, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/transforms/hubEntitySearchTransform.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/buildPropertyMetadata.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/jane.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/sally.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/entities/Customer.entity.json, marklogic-data-hub/src/test/resources/entity-reference-model/entities/Customer.entity.json
DHFPROD-5078: EntitySearch Transform Modules
DHFPROD-5078: Reference entity model changes
DHFPROD-5078: Tests
```diff
```
=> DHFPROD-5078: Display default properties for entity search results

marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.table.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.xml.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/entity-search.js, marklogic-data-hub-central/ui/src/components/result-table/result-table.module.scss, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.module.scss, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
Created a new results-tabular-view component(previous result-table component is still in place for future reference, can be deleted once all the table functionality is implemented)
- This story only handles showing data based on entity type selected, All entities will be handled in a different story
- Backend is not yet implemented for handling xml data, right now if we have xml documents empty table is displayed
```diff
```
=> DHFPROD-4157:Table View should show right layout and data for hierarchical columns with complex types

marklogic-data-hub/src/main/java/com/marklogic/hub/mapping/MappingImpl.java, marklogic-data-hub/src/main/resources/scaffolding/Entity.json, marklogic-data-hub/src/test/java/com/marklogic/hub/legacy/flow/LegacyFlowRunnerTest.java, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateEntityTaskTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateMappingTaskTest.groovy, ml-data-hub-plugin/src/test/resources/my-new-entity.entity.json
=> DHFPROD-4706: Update hubCreateEntity task

marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/discard-changes/discard-changes-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.test.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.test.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export.tsx, marklogic-data-hub-central/ui/src/components/result-table/result-table.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/util/data-conversion.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
includes DHFPROD-5058
Apply query isn't implemented in this pr because the backend work of the DHFPROD-5100 is needed for supporting this. 
```diff
```
=> DHFPROD-4881: Save table columns when saving a query with flat fields

marklogic-data-hub-central/ui/src/components/project-page/project-page.module.scss
Minor CSS change for the Project info modal
```diff
```
=> DHFPROD-4813: Fix CSS for the Project info modal
