data-hub/build.gradle, data-hub/src/hub-in-a-box/root/com.marklogic.hub/lib/flow-lib.xqy, data-hub/src/hub-in-a-box/services/domain.xqy, data-hub/src/hub-in-a-box/services/metadata/domain.xml, data-hub/src/main/java/com/marklogic/hub/DataHub.java, data-hub/src/main/java/com/marklogic/hub/DomainManager.java, data-hub/src/main/java/com/marklogic/hub/FlowManager.java, data-hub/src/main/java/com/marklogic/hub/RestAssetLoader.java, data-hub/src/main/java/com/marklogic/hub/domain/AbstractDomain.java, data-hub/src/main/java/com/marklogic/hub/domain/Domain.java, data-hub/src/main/java/com/marklogic/hub/domain/DomainImpl.java, data-hub/src/main/java/com/marklogic/hub/flow/AbstractFlow.java, data-hub/src/main/java/com/marklogic/hub/flow/SimpleFlow.java, data-hub/src/main/java/com/marklogic/hub/writer/ServerWriter.java, data-hub/src/test/java/com/marklogic/hub/DomainManagerTest.java, data-hub/src/test/java/com/marklogic/hub/FlowManagerTest.java, data-hub/src/test/resources/flow-manager-test/simple-flow.xml, quick-start/src/main/java/com/marklogic/hub/service/CollectorManagerService.java, quick-start/src/main/java/com/marklogic/hub/service/DataHubService.java, quick-start/src/main/java/com/marklogic/hub/service/DomainManagerService.java, quick-start/src/main/java/com/marklogic/hub/service/FlowManagerService.java, quick-start/src/main/java/com/marklogic/hub/web/controller/FlowManagerController.java, quick-start/src/main/java/com/marklogic/hub/web/controller/MainPageController.java, quick-start/src/main/webapp/WEB-INF/pages/deployment/deployment.html
- also added domains to the Java API and xquery
=> #24 - adding the backend code to support deploying a user's modules

README.md, marklogic-data-hub/src/main/resources/ml-modules/transforms/run-flow.xqy
Implemented a run-flow transform that can be invoked from PUT /v1/documents, java code inside a Java container, and REST extension. To verify if the transform is already installed, run http://localhost:8010/LATEST/config/transforms where localhost is the mlHost and 8010 is the port (mlStagingRestPort or mlFinalRestPort). I also updated README.md to guide the users how to use it. 
Let me know if I also need to create a JAVA method that inserts multiple documents using the run-flow transform.
=> 79 - Run-flow transform

quick-start/src/main/java/com/marklogic/hub/factory/EntityModelFactory.java, quick-start/src/main/java/com/marklogic/hub/factory/FlowModelFactory.java, quick-start/src/main/java/com/marklogic/hub/factory/RestModelFactory.java, quick-start/src/main/java/com/marklogic/hub/model/EntityModel.java, quick-start/src/main/java/com/marklogic/hub/model/RestModel.java, quick-start/src/main/java/com/marklogic/hub/service/EntityManagerService.java, quick-start/src/main/java/com/marklogic/hub/service/FileSystemWatcherService.java, quick-start/src/main/java/com/marklogic/hub/service/SyncStatusService.java, quick-start/src/main/java/com/marklogic/hub/web/controller/api/EntityApiController.java
Detection if modules are synched are now done solely in the factories of entity, flow and rest models using SyncStatusService. Kindly review.
=> 101 - Handle detection of REST directory

quick-start/src/main/resources/static/app/directives/header.html, quick-start/src/main/resources/static/app/directives/notification.html, quick-start/src/main/resources/static/app/directives/notificationDirective.js, quick-start/src/main/resources/static/app/quickStartApp.js, quick-start/src/main/resources/static/app/services/dataHubService.js, quick-start/src/main/resources/static/css/quick-start.css, quick-start/src/main/resources/static/index.html, quick-start/src/main/resources/static/top/topController.js
Notification is not dependent on jquery anymore.
But Glenn and I ,just today, think that it might be a better idea to implement the notification/error messages like how it is implemented in mac. It will not auto close. It will allow multiple messages to show up in the right side.
like this: https://github.com/jirikavi/AngularJS-Toaster
=> #104 make ui code more angular

examples/gradle-advanced/build.gradle, examples/gradle-advanced/gradle.properties, examples/gradle-advanced/src/main/ml-config/databases/final-database.json, examples/gradle-advanced/src/main/ml-config/databases/modules-database.json, examples/gradle-advanced/src/main/ml-config/databases/schemas-database.json, examples/gradle-advanced/src/main/ml-config/databases/staging-database.json, examples/gradle-advanced/src/main/ml-config/databases/triggers-database.json, examples/gradle-advanced/src/main/ml-config/servers/final-server.json, examples/gradle-advanced/src/main/ml-config/servers/staging-server.json, examples/gradle-basic/build.gradle, examples/gradle-basic/gradle.properties
=> fixed #184

examples/performance-sample/README.md, examples/performance-sample/build.gradle
closes #492
All the details are in the README -- this should fulfill all the requirements in #492.
I used the geonames cities5000, this results in 45669 records, loaded first as XML and agains as JSON. (For some reason, "cities5000" contains 45677 records, and there's a handful of bad-character errors.) There's many similar geonames collections ranging dramatically in size, so it'd be easy to switch to a different source for shorter or longer testing.
On my MBP after running `hubInit` in an empty directory, `doAll` takes ~6 minutes (including a full, first-time `mlDeploy`). Here's the timing output with `-Pprofile`:
```
BUILD SUCCESSFUL in 6m 8s
21 actionable tasks: 21 executed
Task timings:
2.742s  :hubPreInstallCheck
0.001s  :mlDeleteModuleTimestampsFile
0.004s …
```
=> adds performance sample

CONTRIBUTING.md, quick-start/e2e/page-objects/entities/entities.ts, quick-start/e2e/page-objects/page.ts, quick-start/e2e/specs/create/create.ts, quick-start/e2e/specs/index.ts, quick-start/package.json, quick-start/protractor.conf.js, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.ts
Added fix for #616 so that only the selected properties are wiped of their index/pkey/etc settings.
Also included E2E tests for properties and a check for this condition, plus tweaked settings to get the E2E settings to run.
=> Fixed #616

ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateHarmonizeFlowTaskTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/InstalledTests.groovy
Fixed the test so it a) succeeds and b) actually tests the sourceDB setting from a properties file
=> Feature/fix for #608 custom source db

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/collector/impl/CollectorImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/error/HarmonizeFlowError.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/JobStatus.java, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.hub/endpoints/collector.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/FlowManagerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/collector/StreamCollectorTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java, marklogic-data-hub/src/test/resources/stream-collector-test/collector.xqy, marklogic-data-hub/src/test/resources/stream-collector-test/content.xqy, marklogic-data-hub/src/test/resources/stream-collector-test/staging-database.json
added the internals for #536 because this task really needed it. Did not expose the stop on fail option to gradle or the UI
=> fixed #633

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.hub/lib/hub-entities.xqy
This is breaking the Harmonize Orders step in the tutorial.
=> Handle a null "range-path-index" value

quick-start/src/main/ui/app/facets/facets.component.html, quick-start/src/main/ui/app/facets/facets.component.scss
To resolve the issue of long collection names wrapping, then
the facet will utilize a different style class so the text is
smaller and will appear in a single line.  The facet value length
will be compared to determine if the custom class will be utilized
or not.
Added similar logic to the chiclet since the previous chiclets
were not being displayed properly, all the UI would show was
"Collection:" and you would not be able to see any text.  Added
hover over tooltip for the chiclet values so that the user can
see the full facet name.
=> Fixing Issue #409: add dynamic sizing to facets

quick-start/src/main/ui/app/app.module.ts, quick-start/src/main/ui/app/entities/entities.service.ts, quick-start/src/main/ui/app/flows/flows.component.ts, quick-start/src/main/ui/app/harmonize-flow-options/harmonize-flow-options.component.html, quick-start/src/main/ui/app/harmonize-flow-options/harmonize-flow-options.component.ts, quick-start/src/main/ui/app/select-key-values/select-key-values.component.html, quick-start/src/main/ui/app/select-key-values/select-key-values.component.scss, quick-start/src/main/ui/app/select-key-values/select-key-values.component.ts
The features allows the user to pass in a number of key-value options with a harmonize flow.
The key-value list is built as a configurable Angular component.
Harmonization flow options in the UI are persisted in local storage.
Also fixes #684.
=> Allow key-value options to be passed in for harmonization flows in UI

examples/single-step-ingest/README.md, examples/single-step-ingest/input/products/shirt.xml, examples/single-step-ingest/input/products/sunglasses.xml, examples/single-step-ingest/plugins/entities/Products/Products.entity.json, examples/single-step-ingest/plugins/entities/Products/harmonize/Harmonize Products/Harmonize Products.properties, examples/single-step-ingest/plugins/entities/Products/harmonize/Harmonize Products/collector.xqy, examples/single-step-ingest/plugins/entities/Products/harmonize/Harmonize Products/content.xqy, examples/single-step-ingest/plugins/entities/Products/harmonize/Harmonize Products/headers.xqy, examples/single-step-ingest/plugins/entities/Products/harmonize/Harmonize Products/main.xqy, examples/single-step-ingest/plugins/entities/Products/harmonize/Harmonize Products/triples.xqy, examples/single-step-ingest/plugins/entities/Products/harmonize/Harmonize Products/writer.xqy, examples/single-step-ingest/plugins/entities/Products/input/Load Products/Load Products.properties, examples/single-step-ingest/plugins/entities/Products/input/Load Products/content.xqy, examples/single-step-ingest/plugins/entities/Products/input/Load Products/headers.xqy, examples/single-step-ingest/plugins/entities/Products/input/Load Products/main.xqy, examples/single-step-ingest/plugins/entities/Products/input/Load Products/triples.xqy, examples/single-step-ingest/plugins/entities/Products/input/REST/services/run-ingest-harmonize.xqy
Created a custom REST endpoint that implements a PUT request that will
take the XML body and ingest it into the STAGING database and will
subsequently run the harmonization flow after the document is stored
in the STAGING database and the harmonized document is stored in the
FINAL database.
=> Fixing Issue #476: creating a single step example

marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java
This is just a change to the test setup for quickstart.  Now, it will honor the property in gradle.properties rather than just running on localhost.
=> Test on other hosts

quick-start/e2e/page-objects/flows/flows.ts, quick-start/e2e/specs/auth/authenticated.ts, quick-start/e2e/specs/create/create.ts
Tests:
- Add flow options
- Verify the flow options are retained after moving around tabs and another flows
- Remove flow options and verification
- Add page objects for flow options
=> Tests for E2E/flow options 

quick-start/src/main/java/com/marklogic/quickstart/service/TraceService.java, quick-start/src/test/java/com/marklogic/quickstart/service/TraceServiceTest.java
#738 is because I modified the code to add .json and .xml extensions to the trace documents. That was to make the import easier, but it broke the display of individual traces. This change checks for either extension as well as continuing to allow no extension.
=> #738 allowing for trace URIs with extensions

quick-start/package.json
When installing and running QuickStart on an ML VM, I couldn't access that QuickStart app from my remote machine, i.e. via:
http://engrlab-129-036.engrlab.marklogic.com:4200/
Adding --disable-host-check to the "ng serve" command fixed this:
`ng serve -pc proxy.config.json --host 0.0.0.0 --disable-host-check`
This is discussed here:
https://stackoverflow.com/questions/43677629/invalid-host-header-when-running-angular-cli-development-server-c9-io
There are reported security implications:
https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a
Note that I was not able to solve the issue by adding a --public option (with marklogic.com or *.marklogic.com) instead, which is mentioned in the above article.
=> Add --disable-host-check to allow external access

quick-start/src/main/ui/app/header/header.component.html, quick-start/src/main/ui/app/header/header.component.ts, quick-start/src/main/ui/app/new-flow/new-flow.component.html, quick-start/src/main/ui/app/new-flow/new-flow.component.ts
This includes "Entities" link in header and "Code Generation" section in Create Flow dialog.
Check for version !== 8 rather than == 9.
Fixes #591
=> #591 - Show 2.0 features for server versions >= 9

marklogic-data-hub/src/main/resources/ml-config/mimetypes/woff.json, marklogic-data-hub/src/main/resources/ml-config/mimetypes/woff2.json
This change just removes mimetypes from a default data hub.  the mimetypes are present in server 9.0-5 out of the box.
=> Remove mimetypes from deployed configuration #780

_pages/tutorial/install.md
Instead of as image; this future-proofs the version number.
Also fixed grammar under “Login to the Hub”
=> DHFPROD-731 display install tree as dynamic text

quick-start/src/test/java/com/marklogic/quickstart/service/FlowManagerServiceTest.java
=> Ignore mlcp test.  False failures occur and the test is redundant

quick-start/src/main/ui/app/entity-modeler/entity-modeler.component.ts
Adding an additional dialog message to the 2.0 development branch
that will require the user to press yes twice before the entity
and all associated flows and code are deleted
=> Fixing Issue #578: Adding deletion dialog

quick-start/src/main/ui/app/entity-modeler/entity-modeler.component.ts, quick-start/src/main/ui/styles.scss
Removing the double confirmation dialog and updating the
deletion message that is displayed to the user to make it
clearer to what they are deleting.
@aebadirad, this incorporates the latest feedback by @wooldridge and @ayuwono
=> Updating Issue #578: Update the deletion message

examples/online-store/plugins/entities/Product/harmonize/Harmonize Products/content/content.sjs
This commit to develop should fix (@ayuwono to verify): https://github.com/marklogic/marklogic-data-hub/issues/676
A similar commit was already made on master: https://github.com/marklogic/marklogic-data-hub/pull/896
=> Add let variable declarations

quick-start/src/main/ui/app/entity-modeler/entity-modeler.component.ts
When a new entity is created and saved in the Entities view, display Update Indexes dialog, similar to as is done when editing an entity. 
Update Indexes confirmation dialog feature moved to confirmUpdateIndexes() in entity-modeler.component.ts and now called from both new and edit code paths.
=> DHFPROD-675 add index confirm for save new entity

quick-start/src/main/ui/app/entities/entity.model.ts, quick-start/src/main/ui/app/entities/property.model.ts, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.html, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.ts, quick-start/src/main/ui/app/entity-modeler/entity-modeler.component.ts
Three recent fixes in QuickStart made to the develop branch, pushing to 2.x-develop:
DHFPROD-664: Stagger placement of entity containers in Entities view in QuickStart to avoid hidden containers
DHFPROD-675: Make sure new entity indexes can be added upon entity creation (via dialog) in QuickStart
DHFPROD-497: Fix selection of indexes in entity editor in QuickStart
=> QuickStart UI fixes for 2.x-develop

_pages/tutorial/3x/modeling-order-entity.md, _pages/tutorial/3x/modeling-product-entity.md
Remove the information in the tutorial about setting a primary key to a property automatically adding an element range index for that property.
According to @grechaw, you now have to explicitly set an element range index if you want such a thing on a property with a primary key. This is based on how Entity Services now works.
=> DHFPROD-502 fix tutorial, primary key does not add element range index

examples/data-integration-tests/build.gradle, marklogic-data-hub/build.gradle
Here is a PR that will fail to build until the Java Client API is available publicly.
=> Update Java Client API dependency to 4.0.4

quick-start/src/main/ui/app/codemirror/codemirror.component.scss
Rendering fix to CodeMirror to make tab indent rendering eq to 8 spaces
Fixes #396
See new correct rendering:
http://www.clipular.com/c/5055280828907520.png?k=MIH1aCCHRUfvwzy4TfJot_w7tz8
=> CodeMirror Rendering fixes #396

quick-start/src/main/ui/app/traces/trace-viewer.component.ts
This is a bit of a hack, we’re parsing and then re-stringifying the output if it is a string to fix the formatting.
This is also applied to rawContent (since both rawContent and output use the underlying formatting method).
=> Bug #959 fix Traces output JSON formatting

quick-start/src/main/ui/app/traces/trace-viewer.component.html
Do not display “s” suffix in plugin icon if no duration exists for that plugin.
This is an issue for the Write icon currently.
This will apply to all the plugin icons if, for whatever reason, they are missing a duration.
=> Bug #960 fix Traces duration in plugin icon

quick-start/protractor.conf.js
Added a flag so screenshots on failures will have test name instead of a random number.
Will help debugging failed tests faster and better by knowing which screenshot to look at for a particular test.
=> Improvement to test infrastructure to capture screenshots with proper filenames

quick-start/src/main/ui/app/map/map.component.html
Messaging added:
[Model name] has no properties to map. Add them in the [link]Entities[/link] view.
Fixes #1034.
=> Add messaging in mapping UI when model entity has no properties

quick-start/src/main/ui/app/entity-modeler/entity-editor.component.ts
#1043: fixing regression when no properties result in error state of the entity editor, it is actually a valid state, even though does not make much sense
=> #1043: regression fix

quick-start/src/main/ui/app/map/map.component.ts
- Do not recognize quoted numbers ("123") as numbers. Return "string".
- Add checks for arrays and object (use lodash functions).
Fixes #1051
=> Update type interpretation for mapping

quick-start/src/main/ui/app/facets/facets.component.html
MDL component styles require that the span tag have contents, otherwise style applied sets "display: none;"   Fix adds count value within the badge span tag.
=> Fix for #1039

quick-start/src/main/ui/app/dashboard/dashboard.component.html, quick-start/src/main/ui/app/dashboard/dashboard.component.ts
This fix to the angular app keeps the old configuration key from before the regression (job), but displays the database name as label (jobs).
Fixing this any other way would have introduced compatibility issues -- all of the configuration keys start with 'job' but the database name is -JOBS
=> DHFPROD-983 job db reports no counts

_pages/docs/architecture.md
This issue documents system transforms, with the intention of making this old wiki page removable:
https://github.com/marklogic/marklogic-data-hub/wiki/System-REST-transforms-and-services
=> DHFPROD-980 document system transforms

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java
This along with an update to MarkLogic Java Client API which has the fixes for https://github.com/marklogic/java-client-api/issues/881 and https://github.com/marklogic/java-client-api/issues/920 will fix the issue DHFPROD-907 (Excessive sockets in time_wait in harmonization tasks)
=> DHFPROD-907 Close Iterator after use

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java
I made some minor cleanup changes while reading the Java code for the first time:
- Renamed sourceClient to stagingClient for consistency
- Only instantiating FlowResource once now (it's threadsafe and thus we don't need to create one per batch)
- Removed unused variables in FlowManagerImpl
=> Minor cleanup in FlowRunnerImpl and FlowManagerImpl

quick-start/src/main/ui/app/mappings/mappings.component.html, quick-start/src/main/ui/app/mappings/mappings.component.ts, quick-start/src/main/ui/app/mappings/new-map.component.html, quick-start/src/main/ui/app/mappings/new-map.component.scss, quick-start/src/main/ui/app/mappings/new-map.component.ts
When duplicate name is entered, the following error text is displayed:
A mapping with this name already exists
And the Create button is disabled.
=> Do not allow duplicate mapping names

quick-start/src/main/ui/app/mappings/map.component.ts
When the user edits and saves a mapping description, we need to save the entire mapping. This makes the interaction consistent with editing the source URI. 
Fixes #1180
=> DHFPROD-1124 do a full mapping save with desc save

_pages/ingest/mlcp.md
Here's the change to mlcp paths along with a bit for SJS.  I do not know whether or not, indeed, one should not use the namespace param with SJS.  I figure if I try I might have to fix something :)
=> Update to mlcp transform paths

quick-start/src/main/ui/app/mappings/map.component.ts
Limit the displayed length of source value in mapping UI so it doesn't overflow source container.
Fixes DHFPROD-1164
=> DHFPROD-1164 add valMaxLen

quick-start/src/main/ui/app/mappings/map.component.html
Fixes DHFPROD-1178. Updates right-hand-side header label in Mapping UI. No change in code logic.
=> DHFPROD-1178 change “Model” to “Entity” in Mapping view

quick-start/src/main/ui/app/header/header.component.html
This will fix the icon on the browser tab, so it will look like this:
It was missing before
=> fix logo on browser tab

quick-start/package.json
QS tests were failing to run on windows platform with following error:
```
15:03:12] I/update - chromedriver: unzipping chromedriver_2.40.zip 
path.js:28 
throw new TypeError('Path must be a string. Received ' + inspect(path)); 
^ 
TypeError: Path must be a string. Received undefined 
```
This is because of the issue: https://github.com/angular/webdriver-js-extender/issues/17
The fix to the issue is available in webdriver-js-extender version 2.0.0 and the same is downloaded as a dependency with protractor 5.4.0. 
Hence the PR!
Here is the link to release notes that includes the fix we require:
https://github.com/angular/protractor/blob/master/CHANGELOG.md
=> Upgrading protractor to 5.4.0 to get latest webdriver-js-extender dependency

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/flow-lib.xqy
This change removes the check that ensures flow-lib is in query mode.  mlcp closed the loophole which allowed flows to run in query mode.
=> bug:50063 mlcp no longer allows query mode

quick-start/package.json
This is to fix the windows issue on 3.x-develop
[10:59:59] I/update - chromedriver: unzipping chromedriver_2.41.zip
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^
TypeError: Path must be a string. Received undefined
=> Upgrade protractor to version 5.4.0

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubAmpsCommand.java, marklogic-data-hub/src/main/resources/installer-util/install-amps.xqy, marklogic-data-hub/src/main/resources/installer-util/uninstall-amps.xqy
This PR partially reverts the update to use CMA.  Since the CMA method for amps only works with 9.0-6 and later, we check the server version in this patch to switch on server version.
If the server version is earlier than 9.0-5, a configuration error is now thrown.
=> DHFPROD-1299 server-version dependent amps install

_pages/tutorial/3x/3x.md, _pages/tutorial/3x/browse-understand-product-data.md, _pages/tutorial/3x/create-order-entity.md, _pages/tutorial/3x/create-order-input-flow.md, _pages/tutorial/3x/create-product-entity.md, _pages/tutorial/3x/create-product-input-flow.md, _pages/tutorial/3x/harmonizing-order-data.md, _pages/tutorial/3x/harmonizing-product-data.md, _pages/tutorial/3x/install.md, _pages/tutorial/3x/load-orders-as-is.md, _pages/tutorial/3x/load-products-as-is.md, _pages/tutorial/3x/mapping-product-entity.md, _pages/tutorial/3x/modeling-order-entity.md, _pages/tutorial/3x/modeling-product-entity.md, _pages/tutorial/3x/serve-data.md, _pages/tutorial/3x/wrapping-up.md
This doesn't fix the underlying fundamental problem, but it will ensure the published content doesn't falsely advertise itself as the 3.x tutorial.
=> Issue #1364 Remove "3.x" from the tutorial page titles

quick-start/src/main/ui/app/mappings/mappings.component.html, quick-start/src/main/ui/app/mappings/mappings.component.scss
Include bottom padding in the content container to account for open menus.
Make the content container scrollable if needed when a menu opens.
Applies the .page-content class similar to that in the flows view.
Fixes #1388
=> #1388 Add bottom space and scrolling for mapping menus

_pages/project/dhsdeploy.md
This is a small change -- a bug in the docs went out to docs prematurely, so it will be good to rectify.
=> DHFPROD-1418 property names reversed for docs on 4.0.1

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubModulesCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadHubModulesCommandTest.java
This fixes an issue where, when a DHF4 project depends on a library like smart-mastering-core or marklogic-unit-test via ml-gradle's "mlRestApi" Gradle configuration, the library fails to be loaded. That's due to the library having REST extensions in it which must be loaded via /v1/config/*. But because the hub modules haven't been loaded yet, those calls fail because the staging server can't find its rewriter. 
So this fix simply ensures that the command for deploying hub modules is executed before the command for deploying all other modules.
=> Hub modules are now loaded before all other modules

marklogic-data-hub/src/main/resources/scaffolding/gradle_properties, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/HubProjectTest.java, quick-start/src/test/java/com/marklogic/quickstart/web/EntitiesControllerTest.java
1. Fix for DHFPROD-1306 since mlAdminUsername/mlAdminPassword are deprecated since ml-gradle 3.4
2. Fixing 'EntitiesControllerTest'
=> Adding mlSecurityUsername/mlSecurityPassword to gradle.properties

marklogic-data-hub/src/main/java/com/marklogic/hub/util/MlcpRunner.java
Fixing the mlcp classpath for getting the mlcp tests in https://github.com/marklogic/dhf-project-tests/tree/end-to-end-flow-tests/end-to-end-flows-project passing.
=> Fixing the mlcp classpath

marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/dhf-internal-data-hub.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/dhf-internal-entities.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/dhf-internal-trace-ui.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-role.json
This PR added three URI privileges to security configuration for DHF, and removes the any-uri execute privilege for data-hub-role.
A corresponding change needs to be made in DHS provisioning (note to self)
=> DHFPROD-1246 flow operator/data-hub-user can deploy flows

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubAmpsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/dhf-internal-mappings.json, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java
1. Include the new privileges to HubProject.init() so that they are created in the proj dir when hub is initialized and deployed to db
2. Added a new privilege for uri "/mappings" 
3. Added a test that verifies entities, mappings and flows are not deployed using "data-hub-user"
4. Fixed a typo in DeployHubAmps command
=> Added a new privilege,included them in proj init, added test,fixed typo

marklogic-data-hub/src/main/java/com/marklogic/com/marklogic/client/ext/file/CacheBusterDocumentFileProcessor.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/tracing/trace-ui.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/tracing/tracing-rewriter.xml
This is a straightforward fix for trace-ui, which has several issues in 3.0-4.  Basically binary assets were getting processed by the cache buster and loaded as text, which garbled images, fonts, and the favicon.
=> DHFPROD-1302 Issues in trace ui binary asset loading

build.gradle, marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubPrivilegesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/SSLsetup.java, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/UnInstaller.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/PiiE2E.java
This PR enables running DHF core tests to run with all servers (DHF server, Manage, App Services and Admin) set to ssl/ cert auth in Spring Context.
=> Running DHF core tests with servers set to SSL/ cert auth in spring context

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/flow-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/flow-lib.xqy, marklogic-data-hub/src/trace-ui/src/app/ml-error/ml-error.component.html, marklogic-data-hub/src/trace-ui/src/app/ml-error/ml-error.ts, quick-start/src/main/ui/app/shared/components/ml-error/ml-error.component.html, quick-start/src/main/ui/app/shared/components/ml-error/ml-error.ts, quick-start/src/main/ui/app/shared/stories/components/ml-error/ml-error.component.stories.ts
This PR addresses a long-standing issue with traces from SJS plugins.  Errors are not reported in the tracing database in 4.0.2.  This fix makes an initial attempt at displaying these traces.  There is a server-side component to the fix, so users might have to upgrade to 9.0-8 to see it.   While Jenkins works on this PR I'll see what quick start looks like against 9.0-7.
=> DHFPROD-1513 Issue #1402 Traces don't have SJS stacks

gradle.properties, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/util/MlcpRunner.java, ml-data-hub-plugin/gradle.properties, quick-start/gradle.properties
1. This PR changes the versions in gradle.properties to align with 4.0.3 release and the already made changes in HubConfigImpl and other files
2. Updates MlcpRunner's classpath to run the dhf-project-tests
=> Change version and update mlcprunner classpath

quick-start/src/main/ui/app/mappings/map.component.ts
- When editing mapping URI, don’t save if URI val is
unchanged.
- When editing mapping description, don’t save if
description is unchanged.
=> DHFPROD-1408 no save if uri/desc unchanged

quick-start/src/main/ui/app/flows/flows.component.ts
Also:
- Keep flow in view after deletion if deletion was not flow displayed.
- Fix issue where flows component could not delete harmonize flow
settings if harmonize flow was not currently on display. (Create and
use a local settings-deletion method.)
=> DHFPROD-1411 display new flow in view after save

quick-start/e2e/specs/create/create.ts, quick-start/e2e/specs/mappings/mappings.ts, quick-start/e2e/specs/mappings/typeAhead.ts, quick-start/e2e/specs/run/run.ts, quick-start/e2e/specs/traces/traces.ts, quick-start/e2e/specs/uninstall/uninstall.ts
This PR implements navigate to respective page url on each spec. In case of element/dialog box timeout, it will bring a refreshed page for the next spec to minimize the cascading failures (often caused by protractor trying to click on background overlay elements)
=> e2e navigate to url on each spec

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, quick-start/src/main/java/com/marklogic/quickstart/auth/ConnectionAuthenticationFilter.java
DataHubPlugin now passes in the already-processed set of Gradle properties. No other code was calling withPropertiesFromEnvironment, so there's no longer a need to load any properties from a file.
=> Better fix for passing Gradle properties into HubConfigImpl

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java
I was able to run "gradle bootstrap" successfully with this; it was failing before the fix, working after it. 
This line oddly doesn't seem to impact Gradle deployment, which are sorting the databases.
=> 1561 Removing line that disables database ordering

gradle.properties
This was mistakenly checked in while publishing localy builds of DHF
=> Setting version back to 4.0.3

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubModulesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommandTest.java, ml-data-hub-plugin/build.gradle, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/DeployUserModulesTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/HubTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/HubWatchTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/SaveIndexes.groovy, quick-start/src/main/java/com/marklogic/quickstart/service/DataHubService.java
Renamed LoadUserStagingModulesCommand to LoadHubUserCommand to make it more clear what it does (since it's not staging-specific). 
Depends on ml-gradle 3.10.2, which I just released, which provides a hook in WatchTask for HubWatchTask to use.
=> 1551 mlLoadModules and mlWatch now work properly

ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/TlsTest.groovy
Wiring clients after changing hubConfig. TlsTest passes locally after this.
=> Wiring clients after changing hubConfig

gradle.properties, marklogic-data-hub/build.gradle, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, ml-data-hub-plugin/build.gradle, ml-data-hub-plugin/gradle.properties, quick-start/gradle.properties
1. Changed versions to 4.0.SNAPSHOT (excluding example projects)
2. Changed xcc dependency version in scaffold to 9.0-7
3. Added info for publishing jars
=> Changing versions to "4.0.SNAPSHOT" and publishing the jars

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateEntityTaskTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateInputFlowTaskTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateMappingTaskTest.groovy
This requires the user to run "hubInit" if the project hasn't been initialized yet. 
Also, initHubProject is no longer called if the project has not been initialized. If the project hasn't been initialized and the user isn't running hubInit, then the refreshProject call would likely fail because gradle.properties likely isn't present.
=> Fixing hubInit when gradle.properties doesn't exist

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
@aebadirad I'm not sure how to fully test this because of all the possible upgrade scenarios. The only concern I have with this is whether "refreshProject" can be called - that involves constructing a DatabaseClient to talk to the staging app server. If that's not possible because of what's in the user's gradle.properties file, then the hubUpdate will fail right away.
=> 1592 hubUpdate now works when the project isn't fully initialized

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/InitializeConfigDirsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/InitializeModulePathsTest.java
This modifies Alex's original PR and adds some tests. I believe the unit tests verify that the code is working, but I'm going to test it out on a local 4.1.0 project as well to ensure that mlModulePaths and mlConfigPaths both work.
=> 1596 mlModulePaths and mlConfigPaths now work

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java
This fixes DHFPROD-1601, which is the error about %%mlHubUserRole%% not being a valid role.
=> 1601 Ensuring default value of mlModulePermissions is valid

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/HubDeploySecurityTask.groovy
This fixes a bug where the preinstall check would fail because it tried to deploy amps, but the modules database didn't exist yet.
=> 1605 User amps are no longer deployed during the preinstall check

quick-start/src/main/ui/app/flows/flows.component.html, quick-start/src/main/ui/app/flows/flows.component.ts, quick-start/src/main/ui/app/new-flow/new-flow.component.html, quick-start/src/main/ui/app/new-flow/new-flow.component.scss, quick-start/src/main/ui/app/new-flow/new-flow.component.ts
Added Flow name form validation.
The server treats INPUT flows differently from HARMONIZE flows (making requests to different endpoints when creating/modifying/deleting).  Also, flows are entity specific, so you can have a flow of the same name as long as they are for different entities.   
Given that, flow name duplication prevention in the UI only triggers among the flows of the same Entity and Flow type, since the server allows for the other instances mentioned above.
=> DHFPROD-1328 fix validating that new Flow name is not a duplicate

quick-start/src/main/ui/app/entity-modeler/entity-editor.component.html, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.scss, quick-start/src/main/ui/app/entity-modeler/entity-editor.component.ts
Fixes entity editor extending beyond browser window when there are too many properties, making buttons not clickable:
- Make dialog body container scrollable after a max-height
- When new property is added, scroll to bottom
Resubmit of after rebase: #1684
=> DHFPROD-1433 make entity editor scrollable

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowManagerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/job/JobManagerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/job/TracingTest.java
This PR
1. Initializes 'hubAdminUserName', 'hubAdminRoleName'  so that user defined values are set and not the ones  from dhf-default.props.
2. Doesn't get 'bootStrapHost' if not required (it caused issues in DHS env when running test),
=> Initialize 'hubAdminUserName', 'hubAdminRoleName'  and fix build.gradle

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/HubAppDeployer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/HubAppDeployerTest.java
HubAppDeployer now extends SimpleAppDeployer in a way that it doesn't lose any functionality.
This is not intended for the 4.1.0 release - hoping it can go into 4.1.1 or 4.2.x.
=> HubAppDeployer no longer loses functionality in SimpleAppDeployer

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/transforms/mlcp-flow-transform.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/transforms/mlcp-flow-transform.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java
This PR intends to fix #1097 (DHFPROD-1011) , #1571 
@aebadirad , let me know if the regex to extract "options=..." is good enough
=>  Passing more than one options in input flows using mlcp

quick-start/src/main/ui/app/mappings/map.component.ts, quick-start/src/main/ui/app/shared/components/mappings/map-ui.component.html
Fixes refresh issue on map list in left-hand bar.  Fix also cleans up button code, making SAVE/RESET buttons in map-ui component HTML the "disabled" attribute dynamic, rather than two hard-coded versions of the same button.
=> Fix for DHFPROD-1161

marklogic-data-hub/src/main/resources/scaffolding/gradle-local_properties
comments out the scaffolded username/password in gradle-local-properties. Keeps user from getting bad auth on accident.
=> fixing #1736

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/extensions/scaffold-content.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/hub-entities.xqy
This PR enables 
1. content creation when ES models are submitted (models with internal and external references)
2. Continued support for DHF style models (one entity per file with/without references)
=> Support for ES models in content creation

quick-start/src/main/ui/app/flows/flows.component.ts, quick-start/src/main/ui/app/shared/components/codemirror/codemirror.component.ts
This PR
1. Populates 'errors' and 'hasErrors' objects when there are changes to the code
2. Places the bug icon on the right line (unsure why they are off by one line currently)
=> Fix for DHFPROD-590 and DHFPROD-1698

quick-start/build.gradle, quick-start/e2e/specs/auth/authenticated.ts
Spring boot upgrade, in turn, upgrades Apache Tomcat version as well, which is causing socket error issues.
Reverting to the older version for now.
=>  Revert Spring boot version upgrade for QS

marklogic-data-hub/src/test/java/com/marklogic/bootstrap/Installer.java
Making sure DHF modules are installed before tests are run.
=> Calling hubInstallModules in Installer class when running tests in DHS

quick-start/e2e/specs/create/create.ts, quick-start/e2e/specs/mappings/typeAhead.ts
It seems that with the new npm update to resolve the vulns, the toaster is not recognizable when running e2e with jasmine. This PR will comment out all browser wait on toaster appearance. It will not affect the other tests. Commenting them out, as maybe on the future it could work again.
=> E2e/no toaster wait -- comment out waiting for toaster after updating index

quick-start/e2e/specs/run/run.ts
This PR adds a wait after checking the entity-only box. Sometimes on jenkins the spinner keeps spinning while waiting for the result. This will fix the one failure on jenkins
=> wait after checking entity box

quick-start/e2e/specs/run/run.ts
On jenkins sometimes after clicking on the checkbox, the spinner takes some time for the results to come up
=> add wait after entity checkbox

marklogic-data-hub/src/main/java/com/marklogic/hub/HubProject.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/DataHubInstallTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java
This PR
1. Removes getHubSchemasDir(), usage of hub-internal-config/schemas and scaffolds ml-config/databases/<staging_db_name>/schemas for deploying to staging schemas db. Upgrade to 5.x will require manual copying of schemas from hub-internal-config/schemas to the destination dir.
2. Fixes the test that are affected as a result
=> Loading to staging schemas db from database-specific directory in develop

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
Upgrade staging schemas path in 5.x
1. Copy contents from hub-internal-config-version/schemas to ml-config/databases/<staging_schemas_db_name>/schemas
2. Since there is no upgrade path from 2.x  to 5.x, step 1 is done only for paths 4.x to 5.x
=> Upgrade staging schemas path in 5.x

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateHubTDETemplateCommand.java, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/GenerateTDETemplateFromEntityTaskTest.groovy, ml-data-hub-plugin/src/test/resources/tde-template/Customer.entity.json, ml-data-hub-plugin/src/test/resources/tde-template/Item.entity.json, ml-data-hub-plugin/src/test/resources/tde-template/Order.entity.json, ml-data-hub-plugin/src/test/resources/tde-template/Order1.entity.json, ml-data-hub-plugin/src/test/resources/tde-template/e2eentity.entity.json
This PR
1. Modifies GenerateHubTDETemplateCommand to generate TDE templates for DHF style entities with references
2. Adds tests that verifies template generation with ES style entity with reference (nested in a single file), DHF style entities with reference (entities in multiple file), DHF style entity without reference
=> Fix for generating TDE templates for DHF style entities with references

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateHubTDETemplateCommand.java, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/GenerateTDETemplateFromEntityTaskTest.groovy, ml-data-hub-plugin/src/test/resources/tde-template/Customer.entity.json, ml-data-hub-plugin/src/test/resources/tde-template/Item.entity.json, ml-data-hub-plugin/src/test/resources/tde-template/Order.entity.json, ml-data-hub-plugin/src/test/resources/tde-template/Order1.entity.json, ml-data-hub-plugin/src/test/resources/tde-template/e2eentity.entity.json
This PR
1. Modifies GenerateHubTDETemplateCommand to generate TDE templates for DHF style entities with references
2. Adds tests that verifies template generation with ES style entity with reference (nested in a single file), DHF style entities with reference (entities in multiple file), DHF style entity without reference
=> Fix for generating TDE templates for DHF style entities with references - 4.x-develop

ml-data-hub-plugin/src/test/resources/tde-template/Order.entity.json
=> Fixing the "Order" entity

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateHubTDETemplateCommand.java
This PR fixes
1. creates temp file with same name as entity file so that models written to final db by ml-app-deployer continue to have the same name as before and not get prepended by temp file name (/marklogic.com/entity-services/models/e2eentity.entity.json)
2. DHFPROD-1773- handles NPE when entities are on disk and not in db
=> Fix for DHFPROD-1773, DHFPROD-1746

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
This is part of DHFPROD-1764 that got missed earlier. During upgrade from 4.x to 5.x , hub-internal-config/schemas is removed as the path no longer works
=> Remove hub-internal-config/schemas as part of upgrade

quick-start/api/swagger/mocks.json, quick-start/server.js
Added examples to the Swagger doc as guidance to the API team.   See more details in DHFPROD-1775.
Changes:
- Updated to OpenAPI 3.0 format (aka Swagger 3.0 - we were prev 2.0)
- With OpenAPI 3.0, we can now add multiple examples to paths (POST/PUT mainly).  I added these to the doc as placeholders for the API team and will require updating as the details are decided.
=> DHFPROD-1775: Added multiple examples to Swagger docs

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/debug.sjs
Debug class
My implementation is generic, by design.  
After instantiating a new Debug object with config, a simple JSON object 
payload can be passed to the send() function.  If that object's "type"
property is allowed by the current log level, then the output tagged
with metadata and the complete JSON object is passed as a string to
xdmp.log()
A payload type value that is not of an accepted type is rejected.
A payload type value that requires a higher log level than currently specified is rejected.
All rejected payloads return an Error object with message:
"Error: Log level "{this.logLevel}" does not have permission to log type: {payload type}"
If we want, we can add payload validation, ensuring that the payload type has the proper
parameters (ie. type "error" could require a "stack" …
=> DHFPROD-1795: Debug class

marklogic-data-hub/src/main/java/com/marklogic/hub/FlowManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/exception/FlowNotFoundException.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/RunLegacyFlowTask.groovy
Add RunLegacyFlowTask for 4.x flows
Add access to FlowRunnerImpl in FlowManager
=> Add RunFlowTask for 5.x flows

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateHubTDETemplateCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/es/EntityServicesManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/EntityManagerImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/hub-entities.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-trigger.xqy
Properly build uber model as part of the entity services trigger and remove an unused class from a previous approach I was exploring the TDE gradle command.
=> DHFPROD-1788 Bring in other models for uber model in trigger

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/process.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/prov.sjs
This PR
1. Moves uuid() method to hub-utils.sjs and makes use of it in jobs.sjs
2. Modify write and delete document methods to accept db name and permissions as parameters and remove db specific methods
=> Refactoring e-node code

quick-start/src/main/ui/app/components/flows-new/manage-flows.module.ts, quick-start/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html, quick-start/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.scss, quick-start/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.ts, quick-start/src/main/ui/app/components/flows-new/manage-flows/ui/step-icons-ui.component.html, quick-start/src/main/ui/app/components/flows-new/manage-flows/ui/step-icons-ui.component.scss, quick-start/src/main/ui/app/components/flows-new/manage-flows/ui/step-icons-ui.component.ts
This PR adds a component for color icons under the name values in the Manage Flows table.
It also makes changes based on meeting with @sbayatpur:
- Add a Redeploy button to top (this action was by itself under a header menu in the wireframes, remove this header menu)
- Add friendly datetime display for Last Job Finished
- Remove "Actions" label from Actions column
=> DHFPROD-1870 Manage Flows fixes

quick-start/src/main/ui/app/app.module.ts, quick-start/src/main/ui/app/app.routes.ts, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/matching.component.ts, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/matching.module.ts, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/add-match-option-dialog.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/add-match-option-dialog.component.scss, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/add-match-option-dialog.component.ts, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/matching-ui.component.html, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/matching-ui.component.scss, quick-start/src/main/ui/app/components/flows-new/edit-flow/mastering/ui/matching-ui.component.ts, quick-start/src/main/ui/app/components/flows-new/models/match-options.model.ts, quick-start/src/main/ui/app/components/flows-new/models/match-thresholds.model.ts, quick-start/src/main/ui/app/components/flows-new/models/matching.data.ts, quick-start/src/main/ui/app/components/flows-new/models/matching.model.ts
Initially developing matching config as standalone page (set up a temporary route). Will eventually place in into Edit Flow bottom configuration pane, see: https://project.marklogic.com/jira/browse/DHFPROD-1815
Access current work here: http://localhost:4200/#/matching/{stepid}
(Value of {stepid} currently doesn't matter.)
Summary of work so far:
- Material design table and dialog boxes for Match Options
- Starter HTML table for Match Thresholds
- Hardcoded data for now
- Data model based on Smart Mastering configuration JSON
=> DHFPROD-1679: Start of UI for matching config page

quick-start/src/main/ui/app/app.routes.ts
Via change in app.routes.ts:
/flows now goes to new Manage Flows view (i.e., top-nav link).
/flows-old now goes to old Flows view.
No change to underlying component file structure (for now).
=> Update flows routing

web/src/main/ui/app/components/flows-new/edit-flow/custom/custom.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.html
Disabling the save button does not work for the 'mocked' custom save step due to the customModuleUri = undefined.
Please create a new custom step to test the functionality.
=> DHFPROD-1957: build fixes and updated custom save

web/e2e/specs/auth/authenticated.ts, web/e2e/specs/index.ts, web/e2e/specs/uninstall/uninstall.ts
Changes made so that tests can run in jenkins reliably. Once they do will create another PR ready to be merged for 1872 that has some tests and page objects for manage flow page.
Jenkins tests will now run in port 4200, since there is a blocker issue in running them on 8080.
=> DHFPROD-1872: Fix how tests are run

web/src/main/ui/app/app.module.ts, web/src/main/ui/app/app.routes.ts, web/src/main/ui/app/components/jobs-new/jobs.data.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.component.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.module.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.service.ts, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.scss, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.ts
Adds new Jobs view with Material Design table displaying jobs. Components are here:
app/components/jobs-new
Route is here:
http://localhost:4200/#/jobs
Old Jobs route has been changed to here:
http://localhost:4200/#/jobs-old
Currently working with static array of jobs data here:
app/components/jobs-new/jobs.data.ts
Next steps:
- Hook up to endpoint that delivers mock job data
- Add output data for display in output popup
- Add status data for display in status popup
- Add bulk-action column
- Add Job Details table
=> DHFPROD-2066: Start updated Jobs table

web/src/main/ui/app/app.module.ts, web/src/main/ui/app/app.routes.ts, web/src/main/ui/app/components/jobs-new/jobs.data.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.component.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.module.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.service.ts, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.scss, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.ts
Adds new Jobs view with Material Design table displaying jobs. Components are here:
app/components/jobs-new
Route is here:
http://localhost:4200/#/jobs
Old Jobs route has been changed to here:
http://localhost:4200/#/jobs-old
Currently working with static array of jobs data here:
app/components/jobs-new/jobs.data.ts
Next steps:
- Hook up to endpoint that delivers mock job data
- Add output data for display in output popup
- Add status data for display in status popup
- Add bulk-action column
- Add Job Details table
=> Add Jobs view and summary table

web/src/main/ui/app/app.module.ts, web/src/main/ui/app/app.routes.ts, web/src/main/ui/app/components/jobs-new/jobs.data.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.component.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.module.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.service.ts, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.scss, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.ts
Adds new Jobs view with Material Design table displaying jobs. Components are here:
app/components/jobs-new
Route is here:
http://localhost:4200/#/jobs
Old Jobs route has been changed to here:
http://localhost:4200/#/jobs-old
Currently working with static array of jobs data here:
app/components/jobs-new/jobs.data.ts
Next steps:
- Hook up to endpoint that delivers mock job data
- Add output data for display in output popup
- Add status data for display in status popup
- Add bulk-action column
- Add Job Details table
=> Start updated Jobs table

web/src/main/ui/app/app.routes.ts, web/src/main/ui/app/components/jobs-new/job-details.component.ts, web/src/main/ui/app/components/jobs-new/job.data.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.module.ts, web/src/main/ui/app/components/jobs-new/manage-jobs.service.ts, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.scss, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.ts, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.html
New Job Details view is linked from entries in Jobs table.
Currently gets job data from a static file:
app/components/jobs-new/job.data.ts
TODO:
- Hook up view to mock job data (via services calls)
- Status values should popup status details (at least for failed statuses)
- Committed non-zero values should link to Browse Data view for those documents
- Errors non-zero values should link to error information
=> Add Job Details view

web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/match-options.model.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-strategies-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog.component.ts, web/src/main/ui/app/components/flows-new/models/step.model.ts, web/src/main/ui/app/components/flows-new/validators/new-step-dialog.validator.ts
Adds validation when creating or editing a step. This was required as part of the mapping step update because missing data (target entity, source information) leads to a broken config view for mapping:
- Updates to new-step-dialog to ensure complete data is submitted.
- Custom validator checks for target entity and source data.
- Save button in new-step-dialog is disabled until data is valid
- Mark required fields in new-step-dialog with asterisk (i.e. the radio buttons label).
- For a new step, present a Step Type menu in the dialog and display the rest of the inputs after the type has been selected.
Follows guidelines described in the spreadsheet:
https://project.marklogic.com/jira/browse/DHFPROD-2148
To test, create or edit a step and test that empty required fields cannot be …
=> DHFPROD-2158: Validate mapping (and other step) data

web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.scss
Most of the current tooltips apply to MLCP command-line settings or are empty so we’re going to remove them for the initial release.
=> DHFPROD-2144: Remove tooltips and tooltip icons

web/e2e/page-objects/steps/masteringStep.ts
Update mastering step page objects with latest selectors fix
Mainly on merge-strategy and merge-collection, and also simplify some selectors path as we will use innerText for verification
=> DHFPROD-2112: Update mastering step page objects with latest selectors fix

web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-strategies-ui.component.ts
Recognize when user is creating a second merge strategy and have them confirm the new one will replace the old one.
=> DHFPROD-2092: Handle duplicate default merge strategies

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowManagerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java
Fixing the FlowManager and FlowRunner test as they were failing in DHS with flow-developer-role does not exist. On ingestion the permissions being set was that of flow-developer-role instead of flow-operator-role. Fixed that.
=> DHFPROD-1417: Updating flow tests to have correct permissions

web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.scss, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.ts
Edit Flow view when no jobs:
- Display gray “View Jobs” text (no link)
- Don’t display timestamp or timestamp prefix
- Display “Never run” as status
Manage Flows view:
- Display “Never run” as status
Generally:
- Display status with spaces (convert underscores) and capitalization of first word, e.g.: “Finished with errors”
- Display friendly timestamps with spaces and capitalization of first word, e.g.: “An hour ago”
- Handle linking correctly by checking for null properties in latestJob object
=> DHFPROD-2198: Handle no-jobs case for UI display

web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.html
In stepper header, don’t show “Ended” prefix when there is no timestamp to display.
=> DHFPROD-2217: Fix latest-job timestamp display

web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.html
- Stop displaying the “Ended” prefix when flows are running and there is no end time available.
- Add defensive checks for status and time values
=> DHFPROD-2263: Status and status time display fixes

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.html
With this fix, target entity is still an option for Custom step but not required. Required for Mapping and Mastering. You can click between step types while creating a new step and it should work OK.
=> DHFPROD-2280: Do not require target entity for custom step.

web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-option-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-option-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-threshold-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-threshold-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-collection-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-option-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-option-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-strategy-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-strategy-dialog.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-strategy-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/ui/flow-settings-dialog.component.html, web/src/main/ui/app/components/flows-new/validators/add-match-option.validator.ts, web/src/main/ui/app/components/flows-new/validators/add-merge-strategy.validator.ts, web/src/main/ui/app/components/flows-new/validators/source-weight.validator.ts, web/src/main/ui/app/components/flows-new/validators/weight.validator.ts
Add rudimentary validation in mastering forms for most important fields.
**Match Option** dialog:
- Property name (required)
- Weight (required and number)
**Match Threshold** dialog:
- Name (required)
- Weight (required and number)
- Action (required)
**Merge Option** dialog:
- Property to Merge (required)
- Make "Standard" default type
**Merge Strategy** dialog:
- Name (required)
**Merge Collections** dialog:
- Make "onMerge" default event
Other minor content fixes:
- Use capitalized step names in New Step menu. (NOTE: This is a change to the label (menu) text, not the selection value that is passed under the covers.)
- Edit step name error messages for conciseness and grammar.
- Remove “optional” labeling in forms where required inputs are already denoted.
=> DHFPROD-2103: Mastering validation

web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.html
In QuickStart, display number values for flow docs but do not link to Browse Data view since we currently cannot show those docs via a constrained search query. Affected views:
- Manage Flows
- Jobs
- Job Details
=> DHFPROD-2299: Hide links to committed/failed docs from a job

web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/matching.model.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/match-options-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-options-ui.component.html
Check for config.collections in model.
This was an unexpectedly easy fix.
=> DHFPROD-2232: Add property check when parsing match options

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/RunStepResponse.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java
Add 'stepStartTime' and 'stepEndTime' to the job doc.
Since step info is stored only in memory on client and job doc is created on server, the first step start time will be < job start time. So , after talking with @aebadirad , the first step time is set to job start time temporarily
=> DHFPROD-2261: Add 'stepStartTime' and 'stepEndTime' to the job doc

web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.html
Typo fix. Now the times should appear if available since those properties are coming from the jobs endpoint.
=> DHFPROD-2304: Show start and end times in Job Details

web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.html
The icon serves no purpose currently since the underlying property is passed back as true no matter what.
=> DHFPROD-2296: Hide step validity icon in flow UI

marklogic-data-hub/src/main/java/com/marklogic/hub/step/AbstractStepDefinition.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/Step.java, marklogic-data-hub/src/main/resources/hub-internal-artifacts/step-definitions/ingestion/marklogic/default-ingestion.step.json, marklogic-data-hub/src/main/resources/hub-internal-artifacts/step-definitions/mapping/marklogic/default-mapping.step.json, marklogic-data-hub/src/main/resources/hub-internal-artifacts/step-definitions/mastering/marklogic/default-mastering.step.json, marklogic-data-hub/src/test/resources/flow-runner-test/flows/testFlow.flow.json, marklogic-data-hub/src/test/resources/flow-runner-test/step-definitions/json-ingestion.step.json, marklogic-data-hub/src/test/resources/flow-runner-test/step-definitions/json-mapping.step.json, web/src/main/java/com/marklogic/hub/web/model/StepModel.java
-Steps now have nulls in batchSize, threadCount, retryLimit if not set
-Steps now don't have modulePath unless it's a CUSTOM step.
-Step-defs have defaults values for all keys.
=> DHFPROD-2367: Set null value for keys in steps if not set by the UI

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/ConstructServerManagerTest.java
I opted for a simple unit test for this, as I didn't want to modify groupName on hubConfig.appConfig and risk messing up other tests. 
Will create a separate PR for merging these changes into the develop branch.
=> DHFPROD-2207: Accounting for custom group name during pre-install check

marklogic-data-hub/src/main/java/com/marklogic/hub/collector/Collector.java, marklogic-data-hub/src/main/java/com/marklogic/hub/collector/impl/CollectorImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/RunFlowResponse.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/JobDocManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/RunStepResponse.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/StepRunnerUtil.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collector.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java
This PR,
1. Remove job doc creation/updating from collector 
2. Moves all step/flow start/end times to server- changes to extensions/jobs.sjs to handle creation/updating of stepresponse in the job doc at the start of step (when status is changed to "running step #" ) and at the end of step (when status is changed to "completed (or other statuses) step #" ) 
3. Corresponding changes to FlowRunner, Write/QueryStepRunners
4. Adds lastAttemptedStep, lastCompletedStep, user info to RunFLowResponse
5. Refactor code (JobUpdate renamed to JobDocManager and move common methods in Write/QueryStepRunner to StepRunnerUtil)
=> DHFPROD-2331: Set all step/flow start/end times to server

web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.ts
Running a flow can ingest sample documents required for mapping.
Account for this by reloading any mapping steps when a job ends.
1. edit-flow.component sets flowEnded flag with job ID at end of job
2. flowEnded passed to edit-flow-ui.component, which recognizes change in value
3. flowEnded passed to step.component, which triggers mapping load on change if mapping step
Screencast: https://drive.google.com/file/d/1to9CTpCugHLNLEPVKBJ5Z5xKh0WZqcqP/view
=> DHFPROD-2377: reload mapping after flow run

web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.html, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.html
Details in: https://project.marklogic.com/jira/browse/DHFPROD-2419
You can test by running a flow job that fails (e.g., put in bad URI replacement text for an ingestion). This fix addresses the missing 0 values in the committed column.
Plus minor CSS alignment tweak.
=> DHFPROD-2419: Handle 0 committed values in Jobs views

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/standard.xqy
Mastering uses string join on text nodes since fn:string doesn't return anything on object nodes. It wasn't taking into account that the nodes passed in could themselves be text nodes.
=> DHFPROD-2444: fix length weight on text nodes

marklogic-data-hub/src/main/resources/scaffolding/defaultFlow.flow.json, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateFlowTask.groovy, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/matching.model.ts
Also ensuring that config.tuning exists before checking for maxScan. 
Note that this does not yet generate a mapping file. I believe the current expectation, based on the warning message generated by hubCreateFlow, is that the user must either provide a mapping file or removing the mapping step.
Also - @akshaysonvane is putting together a separate PR for allowing for steps with a name starting with "default-" to work properly. I skirted around that issue by modifying the default flow template so that no steps have a name starting with "default-".
=> DHFPROD-2407: Adding missing data to default flow template

web/src/main/ui/app/components/pagination/pagination.component.ts
Pagination when going from the document details to browser page list fixed.  Page # now resets to first page or results, which is the same page as being shown in the list.
=> DHFPROD-2399: fix to browse pagination when going back/forth

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss
Gradle-generated flows may have a non-existent target entity set for mapping steps.
Check for this in the mapping step component and display appropriate messaging in UI.
=> DHFPROD-2407: Handle a flow with a non-existent target entity

marklogic-data-hub/src/main/java/com/marklogic/hub/step/RunStepResponse.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java
As per https://github.com/marklogic/marklogic-data-hub/pull/2470#discussion_r282583017, flowName is needed in stepResponse. so, adding 'flowName' to stepResponse
=> Adding 'flowName' to stepResponse

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/databases/job-database.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/step.sjs, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/RunFlowTask.groovy, web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/manage-flows.component.ts, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.html, web/src/main/ui/app/components/flows-new/manage-flows/ui/manage-flows-ui.component.ts, web/src/main/ui/app/components/jobs-new/services/running-job-service.ts
Currently running into a bug, when polling 2 different flow jobs, the latestJob object gets overwritten to with the last running flow job object. 
ex. FlowA was running first, then FlowB is started. FlowA gets overwritten with FlowB's latestJob information.
=> DHFPROD-2461: In Manage Flow page first flow's info gets replaced by second flow's info when running second

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java
If 'uris'is null and job is stopped return the response immediately. We can run this on win/linux cluster and ensure tests are running in cluster as well before merging
=> DHFPROD-2501: If 'uris'is null and job is stopped return the response immediately

web/e2e/specs/scenarios/simpleJson.ts
Minor browser sleep swap to make the tests more stable because the GUI changes on status didn't make it to 5.0.0
=> Minor browser sleep swap

web/e2e/page-objects/jobs/manageJobs.ts, web/e2e/page-objects/steps/masteringStep.ts, web/e2e/specs/scenarios/index.ts, web/e2e/specs/scenarios/multiFlows.ts
This PR:
- Add an E2E UI scenario from ingestion to mastering with CSV and JSON docs. This is similar to MLW demo with insurance customers. There is a test on docs merge notification
- Add test on manage jobs page to search specific jobs and undo filters
- Update and fix page objects to set/add/remove merge collections
=> E2E UI scenario with multiple flows and csv docs

web/e2e/specs/scenarios/multiFlows.ts
Fix some weird rendering issue. Sometimes the facet name "customer-merge" is displayed as "cus" or "custo" on jenkins run
=> Fix verification on merge collection facet

marklogic-data-hub/build.gradle, marklogic-data-hub/gradle-dhs.properties, ml-data-hub-plugin/gradle-dhs.properties
Made changes to ports to reflect latest changes in DHS.
Also updated the mlcp version to 9.0-8. This fixed all the failing mlcp tests in DHS.
Verified in a stack by running all the tests.
=> Updates to run DHS test on 4.x

web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
Add padding in mapping configuration container to account for open mapping menu.
Also:
- Widen menu slightly to match filter container width.
- Decrease number of value characters shown to keep from crowding menu disclosure triangle.
=> DHFPROD-2532: Add space for mapping menu

examples/dhf4-with-tests/build.gradle, examples/dhf4-with-tests/src/main/hub-internal-config/servers/job-server.json, examples/dhf4-with-tests/src/main/hub-internal-config/servers/staging-server.json, examples/dhf4-with-tests/src/test/java/org/example/VerifyDeploymentTest.java
I figure this is worth doing, even though we're on 5, as anyone that's on 4 that can't yet go to 5 should still be able to go to 4.3.1. 
Had to add an empty settings.gradle file to make Gradle 5.x happy.
=> DHFPROD-2571: Updated dhf4-with-tests project for 4.3.1

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployDatabaseFieldCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/DeployDatabaseFieldCommandTest.java
For reasons unknown to me, I had to make jdom a compile dependency, even though it should be coming over as a transitive dependency via ml-app-deployer.
=> DHFPROD-2554: Fields and field indexes are no longer dropped

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.ts
Resets mapping config when there are changes to the source collection setting or source query setting.
Looks for changes to source in step component. If found, calls a reset method (sourceChanged()) in mapping component.
Also CSS update to no-properties messaging to make consistent with other messaging styles.
=> DHFPROD-2341: Reset mapping config if source changes in step

marklogic-data-hub/src/main/java/com/marklogic/hub/DataHub.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, web/src/main/java/com/marklogic/hub/web/service/DataHubService.java, web/src/main/java/com/marklogic/hub/web/service/EntityManagerService.java, web/src/test/java/com/marklogic/hub/web/service/EntityManagerServiceTest.java
Things to consider:
1. Security concerns for adding 
`void deleteDocument(String uri, DatabaseKind databaseKind);`
2. With this PR, we are moving away from the trend of clearing all modules and then reinstalling all of them. Instead, we are specifically removing a document if the user removes the entity from UI. This causes an issue if a user removes the entity from the filesystem and then expects it to be removed from the server on redeploy using UI.
=> DHFPROD-2343: Remove the entity definition from database on deletion from UI

web/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.ts
To test:
- Create a flow.
- Edit the flow settings on the Edit Flow page.
- Add a key/value option and save.
Option should now persist.
=> DHFPROD-2572: Save options when editing flow settings

web/src/main/ui/app/components/facets/facets.component.html, web/src/main/ui/app/components/facets/facets.component.scss, web/src/main/ui/app/components/jobs/ui/jobs-ui.component.scss, web/src/main/ui/app/components/search/ui/search-ui.component.html, web/src/main/ui/app/components/search/ui/search-ui.component.scss, web/src/main/ui/app/components/traces/ui/traces-ui.component.scss
The following is the proposed change to the UI to not only fix the described bug with the text bumping down the chicklets but also the general size and "..." truncation of longer names.
What changed?
- The facets column became one column wider, while the results became one smaller. There is no negative impact on the results, as far as I can tell.
- As the browser shrinks or on smaller screen sizes, there was previously code that made the text bump down in size, making it unreadable. I've removed that and stayed at a fixed, readable size.
- We're now using CSS to handle the ellipsis, rathar than truncating by # of characters. This makes our truncation be more accurate.
- The chiclet size is much less wide with less padding, leaving more room for the collection name.
Old Behavior: …
=> DHFPROD-1878: Long facet text

examples/DHS-e2e/DHS/src/main/ml-config/databases/final-database.json, examples/custom-tokens/src/main/ml-config/databases/final-database.json, examples/dhf4-with-tests/src/main/hub-internal-config/databases/staging-database.json, examples/dhf5-custom-hook/src/main/ml-config/databases/final-database.json, examples/disconnected-project/src/main/hub-internal-config/databases/staging-database.json, examples/disconnected-project/src/main/ml-config/databases/final-database.json, examples/healthcare/src/main/ml-config/databases/final-database.json, examples/hr-hub/src/main/ml-config/databases/final-database.json, examples/load-binaries/src/main/ml-config/databases/final-database.json, examples/online-store/src/main/ml-config/databases/final-database.json, examples/single-step-ingest/src/main/ml-config/databases/final-database.json, examples/spring-batch/src/main/ml-config/databases/final-database.json, marklogic-data-hub/src/main/resources/ml-config/databases/final-database.json, marklogic-data-hub/src/test/resources/pii-test/src/main/hub-internal-config/databases/staging-database.json, marklogic-data-hub/src/test/resources/pii-test/src/main/ml-config/databases/final-database.json
There's no need for it to exists in src/main/resources/ml-config/final-database.json. I removed it from example projects as well, as again, no need for it to exist.
=> DHFPROD-2547: Removing empty range index array

marklogic-data-hub/build.gradle, marklogic-data-hub/src/test/java/com/marklogic/hub/LoadTestModules.java
This is the project that's used for running DHF tests.
=> DHFPROD-2611: Using ml-gradle 3.15.0 for deploying DHF bootstrap project

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, ml-data-hub-plugin/build.gradle, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
CMA for users doesn't work in ML 9.0-7, and DHF must be compatible with 9.0-7.
=> DHFPROD-2634: Disabling CMA for users

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
Doing this because when I ran the latest ml-app-deployer 3.15.0 tests on ML 9.0-7, several tests failed pertaining to databases and roles. The tests all pass in 9.0-9. So thinking better safe than sorry for now with DHF.
=> DHFPROD-2634: Turning off CMA for databases and roles

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub_unit_test/RunMarkLogicUnitTestsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub_unit_test/TestConfig.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/buildInvokeHookOptions.sjs
Added "testUnit" task as well so it's easy to run marklogic-unit-test tests. 
This also fixes an issue where TestConfig was being mistakenly picked up by the web tests.
=> DHFPROD-2656: Added unit tests for building invoke options

web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-option-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-option-dialog.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-threshold-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-threshold-dialog.component.scss, web/src/main/ui/app/components/flows-new/tooltips/flows.tooltips.ts
- Move Reduce Properties tooltip up to section label.
- Make title attributes empty (no space) strings.
- Nudge the tooltip containers to the right and widen container for match weight tooltip (keep to one line).
- Add tooltip for Action in Match Thresholds dialog.
- Edit tooltip content, mostly for length.
=> DHFPROD-2383: Matching tooltip edits

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java, marklogic-data-hub/src/test/resources/flow-runner-test/flows/testFlow.flow.json
Revert "Add filename to header and metadata properties when ingesting csv docs"
This reverts commit 0c3795d4 
The original solution to the issue has bugs, so reverting it. The new fix will go in 5.0.2
=> DHFPROD-2658: Revert "Add filename to header and metadata properties when ingesting csv docs"

web/src/main/ui/app/components/entity-modeler/entity-editor/entity-editor.component.ts
Now shows "Entity title already exists" when user tries entering a duplicate name with different case sensitivity.
=> DHFPROD-2636: UI fix preventing creation of duplicate entities with case sensitivity, include DHFPROD 2305 

web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.ts
- Added Saved indicator when changes to lower panels of Ingestion and Custom step are made
- Removed unnecessary onKeyChange function now that Enter is automatically checked for with (change)
- Text styling/positioning of indicator is tentative
=> Added saved indicator for Ingest and Custom lower panels

web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/custom/ui/custom-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ingest/ui/ingest-ui.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
Add snackbar saved indicator for config changes that currently lack feedback:
- Ingestion step config
- Custom step config
- Mapping step config
=> DHFPROD-2531: Add snackbar saved indicator

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/util/metrics/tracer/JaegerConfig.java, marklogic-data-hub/src/main/resources/dhf-defaults.properties, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, web/src/main/java/com/marklogic/hub/web/model/FlowJobModel.java, web/src/main/java/com/marklogic/hub/web/model/FlowStepModel.java, web/src/main/java/com/marklogic/hub/web/service/AsyncFlowService.java, web/src/main/java/com/marklogic/hub/web/service/FlowJobService.java, web/src/main/java/com/marklogic/hub/web/service/FlowManagerService.java, web/src/main/java/com/marklogic/hub/web/web/FlowController.java, web/src/main/java/com/marklogic/hub/web/web/NewJobController.java
https://project.marklogic.com/jira/browse/DHFPROD-2587
1. Introduce Jaeger for performance tracing;
2. Use Asyn callable/thread pool to improve the performance of getFlows api call;
3. Reduce getFlow call with disk access;
4. Sorte by flow name as default for getFlows response
5. Refractor code
=> DHFPROD-2587: Reduce latency of getFlows API call on the backend server

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/flow-utils/getMetadata.sjs
Issue: Metadata for documents from step1 has step1 name. Metadata for documents from step2 has step1 + step2 name and so on
Fix and test in this PR.
=> DHFPROD-2714: Metadata datahubCreatedByStep has a value of currentStep and all prev step names

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts, web/src/main/ui/app/components/flows-new/validators/new-step-dialog.validator.ts
-'Save' now works when validly filling out new Ingestion step, switching to a different step type, and then returning to Ingestion.
-Added option to choose "None" in optional Target Entity drop-down for Custom step dialog.
-Added error message for required Target Entity field.
=> DHFPROD-2655: fixed unsavable state in Ingestion step dialog. 

marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/AbstractVerifyCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/InstallIntoDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/VerifyDhfInDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/deploy/CopyQueryOptionsCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/command/InstallIntoDhsCommandTest.java
Triggers weren't getting loaded into the staging triggers database, but now they are.
Query options are now being copied to all of the URIs necessary for them to work via each of the 4 DHS groups.
=> DHFPROD-2560: Copying query options and loading staging triggers

web/src/main/ui/app/components/folder-browser/ui/folder-browser-ui.component.html, web/src/main/ui/app/components/folder-browser/ui/folder-browser-ui.component.ts
In the ingestion step, on opening a folder to select the source input path, the scroll will be on the top of directory list always.
=> DHFPROD-2694: Scroll to the top of directory list

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/double-metaphone.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/standard-reduction.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/thesaurus.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/zip.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/auditing/base.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/constants.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/collections.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/sm-es-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/helper-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/options-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/merging.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/collections.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/options.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/standard.xqy, marklogic-data-hub/src/test/resources/master-test/step-definitions/mastering/mastering/mastering.step.json
Items addressed:
- Adds SM-PERFORMANCE trace to better track where time is spent
- Minor performance enhancements in reducing the number of searches
- Moves merge options code into a separate library module at /com.marklogic.smart-mastering/survivorship/merging/options.xqy to reduce /com.marklogic.smart-mastering/survivorship/merging/base.xqy size
- Adds a helper function for building queries to reduce the duplicate code to determine whether json-property, element-value, or range queries should be used in the match algorithms
- Normalizes the output from a merge JavaScript function for the user, so the user can output array instead of sequence and JSON values will be converted to nodes for the user.
These changes current exist in the develop branch of smart-mastering-core …
=> Latest mastering changes with performance tracing and enhancements

web/e2e/page-objects/steps/ingestStep.ts, web/e2e/specs/scenarios/multiFlows.ts
Add tests on setting target URI replace and verify it on browse page
We will add the verification on target URI preview once DHFPROD-2776 is fixed (right now, the UI element doesn't show the text value)
=> DHFPROD-2773: E2E UI tests for target URI replace and preview

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/DhsInstallTest.java
8000 isn't available, so defaulting appServicesPort to finalPort.
Also, was running into some issues where timestamps files were preventing modules from being loaded. When running dhsDeploy, we rarely will have a desire to not load all the modules, so the module timestamps path is set to null.
=> DHFPROD-2674: Fixes for deploying user files to DHS

marklogic-data-hub/src/test/resources/master-test/mappings/person/person-1.mapping.json
This still expects "//" for the sourceContext
=> DHFPROD-2502: Fixing MasterTest

web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/match-options.model.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/matching.model.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/match-options-ui.component.html
Fixed the issue. The extra array brackets no longer appears when saving weights on the fly in mastering step.
=> DHFPROD-2703: Extra array brackets added when saving weights on the fly in mastering step

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/thesaurus.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/com.marklogic.smart-mastering/algorithms/thesaurus-expand.xqy
This is more of an ML bug, but this is a workaround to ensure that the thesaurus algorithm works properly.
This ticket isn't in 5.0.2 yet, but wanted to get eyes on this so that if added to 5.0.2, it can be merged in ASAP in support of DHFPROD-2720.
=> DHFPROD-2823: Thesaurus now works for cts:json-property-scope-query

marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle
Now that the Gradle configurations are up-to-date for these libraries, we no longer need to explicitly depend on jdom2, as it is now properly depended on via the use of the "api" configuration in ml-app-deployer.
Releases notes for ml-gradle 3.15.2 are at https://github.com/marklogic-community/ml-gradle/releases/tag/3.15.2
=> DHFPROD-2801: Upgrading to ml-gradle 3.15.2 and ml-app-deployer 3.15.1

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateFunctionMetadataCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping-functions/parseDate.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping-functions/parseDateTime.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/rest-api/lib/extensions-util.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/generate-function-metadata.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/generate-function-metadata.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/GenerateFunctionMetadataCommandTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/testDateTimeFunctions.sjs
1. This PR implements  DHFPROD-2798, DHFPROD-2576, DHFPROD-2157 as they are all related.
2. The function metadata generated in the today's 9.0-nightly and 10.0-nightly server would be incorrect. The issue will be fixed in tomorrow's nightly server (or the latest jenkins server)
=> DHFPROD-2798: Generate function metadata and OOTB date, dateTime functions

web/src/main/ui/app/components/flows-new/edit-flow/mastering/matching/ui/add-match-option-dialog.component.ts
Fixed the issue. The property to match should now pre-populate in the edit-setting dialogue box for any match-option.
=> DHFPROD-2844: Property name is not populated when editing a match option in mastering step

marklogic-data-hub/build.gradle
@bsrikan You can test this out via the same tests you were running yesterday for deploying into DHS - both via the installer and via dhsDeploy.
=> DHFPROD-2875: Defaulting to TLSv1.2 via ml-javaclient-util 3.13.2

web/e2e/specs/scenarios/multiFlows.ts
Enabling the mastering merge verification after the bug is fixed. The merge count is correct now.
Still excluding the notify and total doc count due to a new bug: DHFPROD-2895.
=> DHFPROD-2848: Enabling verification after mastering fix

web/e2e/page-objects/entities/entities.ts, web/e2e/page-objects/flows/editFlow.ts, web/e2e/page-objects/flows/manageFlows.ts, web/e2e/specs/scenarios/simpleJson.ts
Added Protractor's browser.wait() method to ensure the cancel/ok button is clickable on new flow popup window dialog.
=> DHFPROD-2910: validation of entity dialog fields test fix.

marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-json-mapping-create.json, marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-json-mapping-delete.json, marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-json-mapping-modify.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs
- Change to pre-commit triggers
- Ensure targetEntityType is a string and throw an explicit error if it is empty
- Add missing xs: prefix for datatype casts
=> General cleanup for mapping

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
Automatically select another doc if original source doc is not found. The PR for develop has been merged in #2883 , having the same changes in 5.x-develop
=> DHFPROD-2515:Automatically select another doc if original source doc is not found

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/rest-api/lib/search-util.xqy
Unfortunately, even module locations changed. Using xdmp:function and xdmp:apply to work around the difference in versions. 
Tested locally on 9.0-7 and nightly.
=> Latest 10 nightly tests fix

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/MasteringManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/MasteringManagerImpl.java, marklogic-data-hub/src/main/resources/hub-internal-artifacts/flows/manual-merge-mastering.flow.json, marklogic-data-hub/src/main/resources/hub-internal-artifacts/step-definitions/mastering/marklogic/manual-merge-mastering.step.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/amps/dhf-amp-69.json, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/collections.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/manual-merge.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/extensions/smMerge.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/match-and-merge/all-merged.xqy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/MergeDocs.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/MergeEntitiesTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/UnmergeEntitiesTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/DeployHubArtifactTaskTest.groovy
Merge Documents
Manually merge documents together given a set of options.
REST API
POST /v1/resources/ml:smMerge
parameters
- rs:uri=\<URIn> – the URIs of the documents to merge. It is a repeating parameter for each document to merge together. 
- rs:flowName=\<nameOfFlowWithMastering> – The name of the flow that has the mastering settings.
- rs:step=\<masteringStepNumber> – optional; The number of the mastering step with settings. Defaults to 1.
- rs:preview=\<true|false> – optional; if true, the merge doc is returned in the response body and not committed to the database; if false, the merged document will be saved. Defaults to false.
- request body
JSON object with any step options to override.
Gradle task
./gradlew hubMergeEntities
parameters
- -PmergeURIs=\<URI1>,...,\<URIn> –  the …
=> DHFPROD-2755: Initial manual merge work

examples/dh-5-example/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/step/AbstractStepDefinition.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/IngestionStepDefinitionImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/util/json/JSONObject.java, marklogic-data-hub/src/main/resources/scaffolding/defaultFlow.flow.json, marklogic-data-hub/src/test/java/com/marklogic/hub/step/CreateStepDefinitionTest.java
The string "null" was showing up in QS. In addition, I fixed a problem where "mapper" was appearing under matchOptions and mergeOptions - that was due to Jackson serializing the ObjectMapper instance on JSONObject. That no longer occurs. 
Also addresses:
DHFPROD-3056: Custom ingestion step now has a default sourceQuery
=> DHFPROD-3041: New step definitions no longer have a null description

marklogic-data-hub/src/test/java/com/marklogic/hub/legacy/flow/LegacyFlowRunnerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java, marklogic-data-hub/src/test/java/com/marklogic/hub_integration/MappingE2E.java, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/DeployHubArtifactTaskTest.groovy, web/src/test/java/com/marklogic/hub/web/service/FlowManagerServiceTest.java
LegacyFlowRunnerTest - needed to set target entity type
EndToEndFlowTests - I think this is just a timing issue in the Jenkins environment, so I increased the amount of time that the test will wait
MappingE2E - removed invalid tests for mappings with invalid properties
DeployHubArtifactTaskTest - bumped up expected count of step definitions as we now have 5
FlowManagerServiceTest - needed a valid entity
=> DHFPROD-2406: Fixing tests

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/debug-lib.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/trace-lib.xqy
Not sure why this is breaking on this branch and not on develop, but this fixes the problem - which was a couple failing tests in InstalledTests
=> DHFPROD-2406: Assigning default permissions to debug/trace modules

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/DhsInstallTest.java
These properties are used by some ml-gradle features that DHF makes use of, and thus they need to be forced to the DHS default values in addition to the DHS-specific properties.
=> DHFPROD-2897: ml-gradle database names are now set to DHS values

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
'serverVersion' gets populated only if dataHub.preInstallCheck() is called. bootstrap task doesn't call it. so adding a null check. This should fix the incorrect version in server rewriter
=> DHFPROD-3068: Populate 'serverVersion' if it is null

marklogic-data-hub/src/main/java/com/marklogic/hub/cli/Options.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/InstallIntoDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/VerifyDhfInDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/deploy/CopyQueryOptionsCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/command/InstallIntoDhsCommandTest.java
Can include --disableSsl=true
Also modifying CopyQueryOptionsCommand to not fail if a particular URI is not found
=> DHFPROD-3162: Added command line option to not use SSL

marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/AbstractInstallerCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/AbstractVerifyCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/InstallIntoDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/deploy/DhsDeployServersCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubOtherServersCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/deploy/DhsDeployServersCommandTest.java
This does depend on DHS no longer defaulting servers to DHF 4-specific rewriters, as those no longer exists.
=> DHFPROD-3223: mlServerVersion is now set correctly by the server

ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/UpdateIndexesTaskTest.groovy
The test here is enough to verify server side fix for "language":"zxx"
It is expected to fail in nightly builds until the bug is fixed.
I see a comment in the PR against develop and it can be enhanced later to verify generated json file.
=> DHFPROD-3194: Fixing mlUpdateIndexesTest so it runs after saving the indexes

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubDatabaseCommand.java
This fixes the error in UpdateIndexesTaskTest, but the test still fails for me locally for what seems like the following reason - the number of path range indexes isn't increased because hubSaveIndexes is called before the count of current indexes is retrieved. 
I don't think this test is really testing much that isn't covered elsewhere, and for that reason, I think it would suffice for the test to just verify that no errors occur.
=> Ensuring language is not submitted in a database payload

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubDatabaseCommand.java
This fixes the error in UpdateIndexesTaskTest, but the test still fails for me locally for what seems like the following reason - the number of path range indexes isn't increased because hubSaveIndexes is called before the count of current indexes is retrieved. 
I don't think this test is really testing much that isn't covered elsewhere, and for that reason, I think it would suffice for the test to just verify that no errors occur.
=> DHFPROD-3193: Ensuring language is not submitted in a database payload

marklogic-data-hub/src/test/java/com/marklogic/hub_unit_test/RunMarkLogicUnitTestsTest.java
Some tests prior to RunMarkLogicUnitTestsTest are clearing the final database which causes some of the unit tests to break.
=> DHFPROD-3277: Unit test suite now loads hub artifacts

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateFunctionMetadataCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/Versions.java, marklogic-data-hub/src/test/java/com/marklogic/hub/LoadTestModules.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/getMappingFunctions.sjs
GenerateFunctionMetadataCommand can now be run again as part of the unit test suite
=> DHFPROD-3010: Fixing unit tests for mapping functions

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateFunctionMetadataCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/util/ModuleWatchingConsumer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/GenerateFunctionMetadataCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/util/ModuleWatchingConsumerTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/HubWatchTask.groovy
This includes during mlWatch, mlLoadModules, mlReloadModules, mlDeploy, and mlRedeploy.
=> DHFPROD-3146: Function metadata now generated when loading modules

marklogic-data-hub/src/main/java/com/marklogic/hub/DataHub.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/DeployToDhsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java, marklogic-data-hub/src/test/resources/upgrade-projects/dhf43x/src/main/hub-internal-config/databases/staging-database.json, marklogic-data-hub/src/test/resources/upgrade-projects/dhf43x/src/main/ml-config/databases/final-database.json, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/dhs/DhsDeployTask.groovy
Instead, upgradeHub only backs up the hub-internal-config directory. It then checks to see if range-element-index has an empty array in final-database.json, and if so, it's removed without overwriting the file. 
Also removed the support for replacing the DHF version in build.gradle via regex, as our instructions for an upgrade tell the user to do this themselves first. 
Also did a little renaming while I was in DataHubImpl so that "install into DHS" is now "deploy to DHS".
=> DHFPROD-3159: No longer overwriting ml-config directory during upgrade

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MasteringService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/getDefaultCollections.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/getDefaultCollections.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/service.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/getDefaultCollections.sjs, web/src/main/java/com/marklogic/hub/web/web/MasteringController.java, web/src/test/java/com/marklogic/hub/web/web/MasteringControllerTest.java
Using Data Services for this. @ryanjdew  I figure the implementation of the endpoint will change so that the collections are defined elsewhere, but that's fine - I wanted to get this over to Mike ASAP so he's not blocked.
=> DHFPROD-3303: New endpoint for returning default mastering collections

marklogic-data-hub/src/main/resources/ml-modules-final/options/exp-default.xml, marklogic-data-hub/src/main/resources/ml-modules-staging/options/exp-default.xml, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateSearchOptions.sjs
This PR has 2 commits addressing the following issues
* Limiting facets to 25 to improve Explorer performance in case of a large number of facets
* Adding default query options file for the explorer
=> DHFPROD-3288: Limiting facets to 25 to improve Explorer performance 

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/jobInfo/jobInfo.sjs
Bug 53210 was impacting the use of score-reciprocal and was causing jobInfoTest.sjs to break on certain versions of ML.
=> DHFPROD-3153: Reworking latest job query to avoid server bug

web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/merge-collections.model.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/merging.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-collection-dialog.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/add-merge-collection-dialog.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-collections-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-collections-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-collections-ui.component.ts, web/src/main/ui/app/components/flows-new/services/manage-flows.service.ts
This is a Smart Mastering feature under Merging tab in UI:
- Include default collections in Merge Collections table.
- Retrieve defaults from new backend endpoint, see DHFPROD-3303
- Allow user to add additional collections for each event.
=> DHFPROD-3275: Update management of Merge Collections

web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-collections-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-collections-ui.component.ts
The updated Merge Collections table has four rows which are always present, pagination not needed.
@sbayatpur has approved this update.
=> DHFPROD-3275: Remove pagination from Merge Collections table

web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.ts
This PR handles spaces in input fields in case of json documents. For example, in the UI, input field "Sales Channel" will be converted to "*[local-name(.)='Sales Channel']" upon selection. 
@ryanjdew , let me know if this is an ok solution
=> DHFPROD-3229:Handle spaces in input field

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/entity-validation-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/shouldValidateEntity.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/test-data/content/customer-missing-first-name.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/test-data/content/customer-missing-last-name.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/validateJsonAccept.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/validateXmlAccept.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/xmlCustomerMissingFirstName.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/xmlCustomerMissingLastName.sjs
There are significant differences between the output of xdmp.validate and xdmp.jsonValidate, but this attempts to normalize some of the messages into a new headers.datahub.validationErrors.formattedMessages field/element.
=> DHFPROD-3106: Formatting some entity validation messages

web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
Give left and right tables a consistent look and feel.
Improve layout of buttons, headings.
Improve styling of source information on left side.
Remove zebra striping.
Display "Object" and "Array" for the those datatypes in Source table.
=> DHFPROD-3010: CSS style cleanup for mapping

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, web/src/main/java/com/marklogic/hub/web/service/DataHubService.java, web/src/main/java/com/marklogic/hub/web/service/EntityManagerService.java, web/src/main/java/com/marklogic/hub/web/service/FlowManagerService.java, web/src/main/java/com/marklogic/hub/web/service/MappingManagerService.java, web/src/main/java/com/marklogic/hub/web/web/CurrentProjectController.java
When saving an artifact - e.g. an entity, flow, or mapping - I don't see any reason to clear user modules first. The dataHub.clearUserModules method isn't getting rid of old artifacts from the staging/final databases. 
Clearing user modules just runs the risk of bugs like this due to timing conditions where a user may then run a flow before the user modules have been reloaded.
=> DHFPROD-3313: Don't clear modules unless needed in QS

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
The underlying code will all remain in case any user wants to try it out. But due to its minimal scope and the complexity of the generated template, it will not be included in the 5.1.0 release.
=> DHFPROD-2784: Removed hubGenerateNifiTemplate

web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss
- Hide lookup icon (since it currently is non-functional) and adjust layout to accommodate
- Add "Show/Hide Columns" tooltip label to the column filter button
These minor fixes were discussed/OKed in Slack by @rjrudin et al.
=> Updates to the mapping UI view

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/triggers/mapping/cleanUpMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/testCleanMapping.sjs
Remove xml/xslt when mapping is deleted. The current implementation has to be changed due to https://bugtrack.marklogic.com/53406
=> DHFPROD-3373:Remove xml/xslt when mapping is deleted

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/emptyExpression.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/lib/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/missingNestedPropertyExpression.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/nestedMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/runMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/content/person1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/content/person2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/mappings/PersonMapping/PersonMapping-1.mapping.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/mappings/PersonMapping/PersonMapping-2.mapping.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/mappings/PersonMapping/PersonMapping-3.mapping.json
I am not sure if this is the expected behavior, but it seems better to log and ignore these conditions as opposed to throwing errors, which happens via the Test button in QS - though the errors aren't reported, they're just logged.
=> DHFPROD-3407: Empty/missing expressions no longer throw errors

web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.ts
Matching, merging steps do not have subtabs. This code was causing browser errors.
=> DHFPROD-3446: Remove unneeded tab code for matching, merging steps

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/transforms/mlGenerateFunctionMetadata.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/transforms/generateFunctionMetadata/addMapNamespace.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/transforms/generateFunctionMetadata/verifyCompiledStylesheets.xqy
This is needed for the stylesheet generated for core.sjs which results in several map:* references that don't always resolve, depending on the context in which es.mapToCanonical is called. This ensures - via some admittedly hacky code in mlGenerateFunctionMetadata - that the map namespace prefix is declared. 
Also removed some dead code from lib.sjs that was causing confusion about mapping validation.
=> DHFPROD-3380: Map prefix is guaranteed to exist in mapping stylesheet

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/ml-modules-final/options/exp-default.xml, marklogic-data-hub/src/main/resources/ml-modules-staging/options/exp-default.xml, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateSearchOptions.sjs
* Generates the exp-final-entity-options.xml and exp-staging-entity-options.xml file in src/main/entity-config directory on upgrading hub to 5.1.0
* Limit number of facets on Collection facet type in explorer search options.
=> DHFPROD-3465: (and DHFPROD-3467) generating explorer query options file on upgrade to 5.1.0

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/HubWatchTask.groovy
This avoids a bug when a project is first initialized and the constructor fails.
=> DHFPROD-3461: Initializing onModulesLoader outside constructor

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/models/entities.service.ts
Make calls for entities, map, and functions sequentially.
Use more concise async calls in the services component.
I'm hoping this fixes the problems Firefox is having with the async loads in the mapping component. I'm no longer seeing the targetEntity errors in Firefox with this commit.
=> DHFPROD-3423: Refactor entity loading in mapping component

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
This PR fixes DHFPROD-3353, DHFPROD-3355 and retains mapped properties after source doc uris or source type is changed
=> DHFPROD-3353: DHFPROD-3355:Retain map after source doc uris/type

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts
1. Fix for the bug DHFPROD-3509.
2. Fixed the issue of Type not showing as Array and Object in source table for a JSON doc, if both XML and JSON Docs exists in same collection.
=> DHFPROD-3509: Missing items in QS mapping source data table in case of array of xml/json elements

marklogic-data-hub/gradle.properties, ml-data-hub-plugin/gradle.properties, web/gradle.properties
This is just to make life easier for when I want to run the unit tests via host:8011/test/default.xqy as flow-developer instead of as admin user. It has not impact on DHF application code.
=> Test users now have an easy-to-remember password

marklogic-data-hub/src/main/resources/hub-internal-artifacts/step-definitions/merging/marklogic/default-merging.step.json, marklogic-data-hub/src/main/resources/ml-database-field/final-database.xml, marklogic-data-hub/src/main/resources/ml-database-field/staging-database.xml, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/auditing/base.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/blocks-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/merging.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collector.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/getDefaultCollections.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/auditing/audtingCollectionTest.sjs, marklogic-data-hub/src/test/resources/master-test/flows/myMatchMergeFlow.flow.json, web/src/main/ui/app/components/flows-new/edit-flow/edit-flow.component.ts
Since we're changing the path for the merge range, this will require a re-deploy to get all the changes.
Items addressed:
- When I run a match step on a set of documents, a match summary JSON document is created (no change from previous behavior). This match summary JSON document is changed in the following ways:
- The URIs are displayed so the user understands which URIs will be processed (instead of just hashes)
- The name 'URIsToActOn' is changed to 'URIsToProcess'
-  In the "actionDetails" section, "merge" actions should have the relevant threshold included similar to "notify" actions
- Merge step should honor source collection/query instead of ignoring it for its own method. (e.g., the merge step should restrict the range index values to the collection/query specified)
- When I run a …
=> DHFPROD-3539: Smart Mastering cleanup items

marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java, web/src/main/java/com/marklogic/hub/web/service/DataHubService.java
Generate function metadata only if forceLoad is set to true
=> DHFPROD-3606:Generate function metadata only if forceLoad is set to true

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java
This PR does 2 things
1. Fixes 'forceLoad' in LoadUserModulesCommand so that property file manager is initialized and timestamp file is deleted before loading from standard ml-gradle location when forceLoad is set to true
2. Load all user artifacts so that mappings get recompiled so that we don't run into XDMP-UNDFUN error (DHFPROD-3606)
=> DHFPROD-3616:Fix forceLoad in LoadUserModulesCommand

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts, web/src/main/ui/app/components/flows-new/models/step.model.ts
=> DHFPROD-3601: Set the default in the UI (and the backend) to 1 thread for a mastering step, in case they don't read the docs first.

marklogic-data-hub/src/main/java/com/marklogic/hub/step/ResponseHolder.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java
The main cause of the error was that "documents" in the JSON returned by mlRunFlow was an array of objects, not a map. So ResponseHolder.documents is now a list. 
QueryStepRunner then had to be modified to convert this list into a map structure, where the key is the URI. 
This feature is undocumented and does not have any tests, so I put the change in QueryStepRunner into a try/catch to ensure it can never break anything.
=> DHFPROD-3176: Changed ResponseHolder.documents to a List

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts
Fix for the bug 2794.
Also, now the user will not be able to save the step without providing any value for sourceCollection field in Edit Step dialog box.
=> DHFPROD-2794: Collections list doesn't change immediately upon changing the database in New Mastering/Mapping/Custom step Window

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts
Users will now be able to save the step when the 'Query' option is chosen for the source type, but will be enforced to choose a collection name from the updated list, if source type is 'collection'.
=> DHFPROD-3761: Save button is disabled when trying to change source database in mapping step

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/util/ModuleWatchingConsumer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/util/ModuleWatchingConsumerTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
This avoids problems when the user runs hubInit and no username/password is set yet.
=> DHFPROD-3812: Lazily instantiate command in ModuleWatchingConsumer

.gitignore, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
This avoids problems when the user runs hubInit and no username/password is set yet.
=> DHFPROD-3812: Fixing hubInit

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubDeveloperTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubOperatorTest.java
Used to be data-hub-app-admin and data-hub-user
=> DHFPROD-3108: Renamed new roles to data-hub-developer and data-hub-operator

marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubArtifactsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/dhf-defaults.properties, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-entity-model-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-flow-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-flow-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-mapping-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-mapping-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-step-definition-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-step-definition-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/flow-developer-role.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/flow-operator-role.json, marklogic-data-hub/src/test/java/com/marklogic/hub/core/HubProjectTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadHubArtifactsCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommandTest.java
Insert artifacts with new roles.
@rjrudin ,
I don't think anything needs to be done for upgrade scenario as hubInit would initialize the new roles and deploying them would take care of writing them with appropriate roles.
=> DHFPROD-3617:Insert artifacts with new roles

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubAdminTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubDeveloperTest.java
Configure DH resources requiring new granular privileges.
@SameeraPriyathamTadikonda ,
This PR should be run on 10.0-nightly, this will fail on 10.0-2.1 against which all PRs usually run.
=> DHFPROD-3504:Configure DH resources requiring new granular privileges

marklogic-data-hub/src/main/resources/ml-modules/transforms/mlGenerateFunctionMetadata.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/GenerateFunctionMetadataCommandTest.java
This is needed so that an operator can run a mapping step
=> DHFPROD-3510: Metadata files get operator/execute

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/collector/impl/CollectorImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/StepDefinitionService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowInputs.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/job/JobDocManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/MarkLogicStepDefinitionProvider.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/ProjectStepDefinitionProvider.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepDefinitionProvider.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepRunnerFactory.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepDefinition/getStepDefinition.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepDefinition/getStepDefinition.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepDefinition/service.json, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunFlowRunnerTestsWithoutProjectTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/HubConfigImplTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/MappingTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/RunMappingTestsWithoutProjectTest.java, marklogic-data-hub/src/test/resources/flow-runner-test/flows/testFlow.flow.json, web/src/test/java/com/marklogic/hub/web/web/HubConfigJsonTest.java
Summary of changes:
- Extracted AbstractHubConfig from HubConfigImpl so that SimpleHubConfig can be used without depending on Spring
- Introduced StepDefinitionProvider so that StepRunnerFactory is no longer bound to retrieving step definitions from files. An ML-based implementation of this now retrieves step definitions via a new data service.
- Added FlowRunner.runFlowWithoutProject, along with new FlowInputs class to encapsulate all the possible inputs
- Subclassed FlowRunnerTest and MappingTest so that all of the tests in those two classes are now also run via runFlowWithoutProject
=> DHFPROD-3779: Can now run flows without Spring or a HubProject

marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collector.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collectorLib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/ConstrainSourceQueryToJobTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/endpoints/processSourceQuery.sjs
Also defined mlHubLogLevel in gradle.properties for the test application so that debug.log messages will show up, so those can be verified.
=> DHFPROD-3935: Can now constrain a source query to a job ID

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java
I noticed in the logging for FlowRunnerTest that there were some "ERROR" messages from WriteStepRunner with "null" as the message. I added a little context to both log messages, as "null" by itself of course doesn't say much.
=> DHFPROD-3779: Trying to debug while test failed on Jenkins

marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/ConstrainSourceQueryToJobTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunWithDataHubOperatorTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/ValidateMappingTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubOperatorTest.java
It started failing because it was accessing adminHubConfig before ensuring it was initialized to use flow-developer as a user.
Perhaps HubTestBase should be doing this before every test?? Otherwise there's the chance that one test modified adminHubConfig, and that bleeds over into the next test, causing an error.
I also modified setupProjectForRunningTestFlow, as it was ignoring the HubConfig object being passed into it.
=> DHFPROD-3935: Fixing ValidateMappingTest

marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/AbstractVerifyCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/InstallIntoDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/command/VerifyDhfInDhsCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/command/InstallIntoDhsCommandTest.java
I also realized that we still don't want flow-developer-role, flow-operator-role, or data-hub-admin-role deployed to DHS, as those grant too many privileges and thus shouldn't be present.
=> DHFPROD-4073: dhsVerify now correctly verifies roles

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/rest-api/rewriter/10-rewriter.xml
These seemingly was just an oversight, and the rewriter should have been using the OOTB module, just like the ML 9 rewriter is.
=> DHFPROD-4072: ML 10 rewriter now uses OOTB module for GET document

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/client/CommandLineFlowInputs.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/client/Main.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/client/RunFlowCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/RunFlowResponse.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/client/CommandLineFlowInputsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/client/RunFlowCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/client/RunFlowViaMainTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunWithDataHubOperatorTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FlowRunnerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubOperatorTest.java, marklogic-data-hub/src/test/resources/cli-client/test-options.json, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/RunFlowTask.groovy
Part of this involves taking the logic in RunFlowTask for processing user inputs and tossing that into the new CommandLineFlowInputs class, where it can be easily reused by the client Main program (and can also be tested easily too). 
Otherwise, this is mostly just some new code - the com.marklogic.hub.cli.client package, and then tests for the new code.
=> DHFPROD-3755: Can now run a flow via an executable jar

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunFlowRunnerTestsWithoutProjectTest.java
Avoids instantiating flowRunner twice, which was leading to a race condition as to which flowRunner "awaitCompletion" was being called on.
=> DHFPROD-3779: Fixing intermittent test failure

marklogic-data-hub/src/main/java/com/marklogic/hub/cli/client/CommandLineFlowInputs.java, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/client/RunFlowViaMainTest.java
I updated the JIRA ticket, as I think it's better for the argument casing to be consistent with hubRunFlow instead of with mlcp.
=> DHFPROD-3755: Changing casing of flow arguments to match hubRunFlow

web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/mapping-ui.component.ts
- Increase table widths and give additional width to property name columns
- Decrease padding to maximize usable screen real estate
- Decrease indent width to give more space to subproperties
- Set reasonable min-width settings to keep tables from breaking when the browser is shrunk
- Use flexbox more instead of floats for better layout control
=> DHFPROD-3555: Update mapping layout and tables to address wrapping

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/test/java/com/marklogic/hub/security/AbstractSecurityTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubDeveloperTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubOperatorTest.java
This avoids rest-reader/rest-writer default permissions from being added to every document inserted by this user (which was courtesy of the rest-writer role, which is inherited by rest-admin). 
Had to add tde-view to the operator to ensure that user can see TDE stuff in the schemas database.
=> DHFPROD-4154: Developer no longer inherits rest-admin

web/src/main/ui/app/components/flows-new/models/mapping-options.model.ts, web/src/main/ui/app/components/flows-new/models/mastering-options.model.ts, web/src/main/ui/app/components/flows-new/models/step.model.ts
I'm not sure why these steps didn't gain default permissions the first time around, but I think we're better off doing it for all step types.
=> DHFPROD-4245: Applying default permissions in QS for every step type

marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/DhsDeployer.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployAsDeveloperTest.java
It's necessary for these tasks to set "is provisioned environment" to true so that DHF excludes certain properties from database files.
=> DHFPROD-4158: hubDeploy tasks now work on-premise

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts
Without this, a flow configured outside of QS, shows up empty mapping configuration although mapping config is available.
=> DHFPROD-4257: QS should consider mapping name from the flow file as well

marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java
See the comment.
@ryanjdew  Let me know what you think about this. I don't know where to start to try to figure out why only 205 are in the collection sometimes. I think it'd help if the test were only try to e.g. match and merge 2 documents, with one additional document that is expected not to be merged. With over 200 documents being ingested, it's very difficult to know which ones are supposed to be merged together.
=> DHFPROD-4158: Changing MasterTest assertion

examples/dh-5-example/build.gradle
runFlowWithoutProject was causing hubInit to bomb since the ml* properties weren't defined yet
=> DHFPROD-4255: Can run hubInit on dh-5-example again

marklogic-data-hub/src/main/resources/hub-internal-config/database-fields/staging-database.xml, marklogic-data-hub/src/main/resources/ml-config/database-fields/final-database.xml, marklogic-data-hub/src/test/resources/upgrade-projects/dhf43x/key/final-database.xml, marklogic-data-hub/src/test/resources/upgrade-projects/dhf43x/src/main/ml-config/database-fields/final-database.xml, ml-data-hub-plugin/src/test/resources/update-indexes/final-database.xml, ml-data-hub-plugin/src/test/resources/update-indexes/staging-database.xml
Verified that the Explorer search options - exp-default.xml - all work fine on the dh-5-example project.
=> DHFPROD-4207: Field range indexes now use root instead of en collation

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-load-data-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-load-data-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/loadData.mjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs
DHFPROD-3916 talks about data-hub-load-data-reader and data-hub-load-data-writer roles to be able to update/view the load configuration in one-ui.
This PR is an attempt to create these new 5.3 roles.
=> DHFPROD-3916: Adding load data roles

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/Options.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/deploy/CopyQueryOptionsCommand.java, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/Installer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/deploy/CopyQueryOptionsCommandTest.java
The group and server names can now be defined via the command line. The server names are used for copying REST options around. Group names are also used for copying REST options around, and also for granular scheduled task privileges.
=> DHFPROD-4123: DHF installer no longer assumes group or server names

examples/dhs-example/README.md, examples/dhs-example/src/main/ml-config/security/roles/custom-role1.json
"manage" apparently doesn't work because it's not directly inherited by data-hub-security-admin.
=> DHFPROD-4158: Updated example to use a different privilege

one-ui/ui/src/components/load-data/new-data-load-dialog/new-data-load-dialog.tsx
Fixed the issue where errors were not being flagged in Target URI Preview, if user provides the invalid output URI Replacement
=> DHFPROD-4319: Output URI Replacement" and "Target URI preview" not working as expected

marklogic-data-hub/src/main/resources/ml-modules/services/mlRunFlow.sjs
FlowResource in QueryStepRunner is the only thing that calls this endpoint, and it never passes a "uri" param, nor does it ever send a request body. Also, our docs for using the REST API don't document either of these options. 
I'm removing this code in preparation for sharing code between this endpoint and the upcoming DS endpoint for running steps. Wanted to only reuse what's actually needed.
=> DHFPROD-3865: Removing dead code from mlRunFlow

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateHubTDETemplateCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepRunner/runSteps.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepRunner/runSteps.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/step-runner.sjs, marklogic-data-hub/src/main/resources/ml-modules/services/mlRunFlow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/MappingTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/stepRunner/runSingleStep.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/stepRunner/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/stepRunner/suite-teardown.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/stepRunner/test-data/content/person1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/stepRunner/test-data/content/person2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/stepRunner/test-data/content/person3.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/stepRunner/test-data/entities/Person.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/stepRunner/test-data/flows/PersonFlow.flow.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/stepRunner/test-data/mappings/PersonMapping/PersonMapping-1.mapping.json, ml-data-hub-plugin/build.gradle, web/build.gradle
Upgraded to Java Client 5.1.0 to use the Bulk IO API for testing. This required upgrading to ml-gradle 4.0, which supports Java Client 5.1 (3.x does not). 
Extracted reusable code from mlRunFlow.sjs into flow.sjs/findMatchingContent. This helps minimize the code in mlRunFlow.sjs (REST) and runSteps.sjs (DS).
=> DHFPROD-3865: Can now run a step via a Data Services endpoint

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/rest-api/rewriter/10-rewriter.xml, marklogic-data-hub/src/test/java/com/marklogic/hub/rewriter/StagingRewriterTest.java
The HEAD/PUT/DELETE dispatchers were referring to non-existent modules. They now refer to the OOTB ML modules.
=> DHFPROD-4483: Fixing custom rewriter for ML 10

examples/dh-5-example/src/main/java/org/example/RunFlowWithoutProject.java, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/client/RunFlowCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunFlowRunnerTestsWithoutProjectTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/RunMappingTestsWithoutProjectTest.java
And deprecated existing runFlow methods.
This is based on beta and tech summit feedback.
=> DHFPROD-4492: Renamed runFlowWithoutProject to runFlow

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/RunFlowRunnerTestsWithoutProjectTest.java
Temporarily removed code for applying artifact settings in support of batch size, thread count, a custom hook, and collections/permissions. No tests were depending on this code, and I'm wondering if this feature is needed yet - these things can all still be specified in the flow.
=> DHFPROD-4540: Added test for applyArtifactSettings

marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/deploy/DeployHubQueryRolesetsCommandTest.java
The SaveReceipt is not null when run against the trunk build, which has a fix for this scenario. So just logging a message to explain what's expected.
=> DHFPROD-4558: Modified test for deploying query rolesets

one-ui/ui/package.json
This antd version fixes the string/number typing issue for the Result component.
Details:
https://github.com/ant-design/ant-design/issues/21592
https://github.com/ant-design/ant-design/pull/21691
Thanks, @bsrikan, for discovering this fix.
=> DHFPROD-4568: Increase antd version to 3.26.13

one-ui/ui/src/components/login-form/login-form.tsx, one-ui/ui/src/util/auth-context.tsx
This PR fixes the issue mentioned in the TITLE and makes sure that the user maintains the required roles throughout the session.
=> DHFPROD-4361: Roles information gets reset when Load Data route is refreshed

one-ui/build.gradle
There were conflicts due to different npm versions on marklogic-datahub and one-ui modules. I added a working directory for npm in one-ui and it fixed the build issue(could download node 12.16.1) on develop
=> DHFPROD-4568: Adding working dir for npm

azure/flow-runner-function/README.md
Updating Readme to let the user know to manually edit the pom.xml file for the Azure function name. This is to avoid name-conflict during deployment.
=> DHFPROD-4523: Updated README file for Azure function name

one-ui/build.gradle
There were build issues as the plugin fails to download node.js intermittently.
The below suggests that changing the plugin resolves the issue.
https://github.com/srs/gradle-node-plugin/issues/301
=> DHFPROD-4568:Changing the node-gradle plugin

one-ui/build.gradle
This should resolve all the build issues while downloading node js.
=> DHFPROD-4568: Adding base dist url for node js

one-ui/ui/src/App.css, one-ui/ui/src/pages/Bench.module.scss, one-ui/ui/src/pages/Bench.tsx
This commit displays an error dialog box at end the of a run and handles:
- Failed run with no batches processed (shows single error)
- Completed run with one or more errors across batches (shows up to 10 errors realized)
Screencast of UI functionality:
https://drive.google.com/file/d/1znqu7xPXKQYKhR_XeIN7lYAnq9pXdBj3/view
How to set up system so that a run will fail:
https://project.marklogic.com/jira/browse/DHFPROD-4025?focusedCommentId=170498&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-170498
https://project.marklogic.com/jira/browse/DHFPROD-4025?focusedCommentId=170654&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-170654
This work depends on the following functionality being in place: …
=> DHFPROD-4025: Display step errors in post-run dialog

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collector.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collectorLib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/invoke-step.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/Installer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub_unit_test/RunMarkLogicUnitTestsTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/endpoints/collectorLib/prepareSourceQuery.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/flowWithValues.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/suite-teardown.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/test-data/flows/CustomerByValue.flow.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/test-data/step-definitions/CustomerByValue.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/test-data/valueStep.sjs, marklogic-data-hub/src/test/resources/flow-runner-test/custom-modules/custom/value-step/main.sjs, marklogic-data-hub/src/test/resources/flow-runner-test/flows/testValuesFlow.flow.json, marklogic-data-hub/src/test/resources/flow-runner-test/step-definitions/value-step.step.json
Step option "sourceQueryIsScript:true" can be added so that the collector knows to evaluate the sourceQuery as a script instead of tossing it into a cts.uris call. 
Did some renaming of "uris" as a variable to "items". Unfortunately can't change e.g. "uris" in a Batch document, as that'd be a breaking change. 
FlowRunnerTest now depends on the indexes in the test final-database.json file, so I moved the setup of those indexes from RunMarkLogicUnitTestsTest into Installer.
=> DHFPROD-3854: sourceQuery can now be a script

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/HubConfigImplTest.java
Set absolute schema path in 'AppConfig'. There is a test already for this running in regression, its failure resulted in this issue
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/develop/759/tests
=> DHFPROD-4603:Set absolute schema path in 'AppConfig'

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collectorLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/endpoints/collectorLib/prepareSourceQuery.sjs
This is an undocumented, untested feature that was uncovered by someone making use of it. So ensuring it still is supported.
=> DHFPROD-4665: sourceQuery can now be a cts.uris script again

azure/flow-runner-function/README.md, azure/flow-runner-function/pom.xml, azure/flow-runner-function/src/main/java/com/marklogic/dhf/azure/FunctionDataHubFlow.java, azure/flow-runner-function/src/test/java/com/marklogic/dhf/azure/FunctionDataHubFlowTest.java
Sometimes, noticing inconsistent behavior when the Function App is throwing exception and is not being handled properly by the Logic App. This PR is to return an appropriate message to the caller - either successful or exception message.
```diff
```
=> DHFPROD-4531: Handle runFlow exception to return a proper message to the caller

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/SavedQueriesService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-saved-query-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-saved-query-writer.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/savedQueries/saveSavedQuery.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/savedQueries/saveSavedQuery.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/savedQueries/service.json, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/savedQueries/SavedQueriesServiceTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/savedQueries/saveSavedQueryTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/security/getAuthoritiesTest.sjs, one-ui/src/main/java/com/marklogic/hub/oneui/controllers/SavedQueriesController.java, one-ui/src/test/java/com/marklogic/hub/oneui/TestHelper.java, one-ui/ui/api/swagger/mocks.json, one-ui/ui/api/swagger/mocks.yaml
DHFPROD-3647: Save Query endpoint implementation
DHFPROD-3647: Adding reader and writer roles for saved query documents
DHFPROD-3647: Save Query dataservice modules
```diff
```
=> DHFPROD-3647: Save personal search query and its associated filters

marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java
It's still failing intermittently in Jenkins. Reducing the sleep time and also improving the assertion so we can see what the status is when this fails. 
```diff
```
=> DHFPROD-4604: Trying to fix testStopJob again

marklogic-data-hub/src/main/resources/overview.html
Linking the new docs website on every javadocs page.
```diff
```
=> DHFPROD-2693:Linking to new docs site in Javadocs

marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/DhsDeployer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployAsDeveloperTest.java
hubDeploy and hubDeployAsDeveloper task now deploy lsqt configuration in develop.
```diff
```
=> DHFPROD-4119: hubDeploy now deploys lsqt configuration

marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/DhsDeployer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployAsDeveloperTest.java
hubDeploy and hubDeployAsDeveloper tasks now deploy lsqt configuration.
```diff
```
=> DHFPROD-4119: hubDeploy now deploys lsqt configurations

marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/xquery-lib.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/triggers/mapping/mappingJSONtoXML.sjs, marklogic-data-hub/src/main/resources/ml-modules/transforms/mlGenerateFunctionMetadata.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/createEntityServicesMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/runMappingWithUriReference.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/mappings/PersonMapping/PersonMapping-7.mapping.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/testCleanMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/testMappingTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/savedQueries/saveSavedQueryTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/security/getAuthoritiesTest.sjs
This opens the door to all sorts of variables in a mapping artifact. However, to achieve this, I had to make a copy of the ES functions map-to-canonical and node-map-to-canonical so that I can pass in a map of params to the underlying xdmp:xslt calls. I opened up bug 54632 so that the ES functions will allow this in a future version.
```diff
```
=> DHFPROD-3841: Can now reference $URI in mappings

one-ui/ui/src/components/activity-settings/activity-settings-dialog.test.tsx, one-ui/ui/src/components/activity-settings/activity-settings-dialog.tsx, one-ui/ui/src/config/data.config.js
Updated existing Enzyme tests to RTL and added some more unit tests for activity settings.
There is no test plan for this story, this was carried over from previous sprint. It includes all possible tests for the activity settings component.
Added comments for 2-3 scenarios that can be written after bugs are fixed.
Other than tests, added data-testid to select options for testing. 
Reused a boolean variable (usesSourceDatabase) in place of explicit check for acttivityType.
Added placeholder text for provenance granularity Select field.
Reviewers pls let me know if some more scenarios needs to be added.
```diff
```
=> DHFPROD-4173: Tests for activity settings

Jenkinsfile
Getting the original commit ID from PR instead of merged commit ID.
```diff
```
=> DHFPROD-4522: getting the correct commit Id

one-ui/README.md, one-ui/ui/mockserver/index.html, one-ui/ui/mockserver/package-lock.json, one-ui/ui/mockserver/package.json, one-ui/ui/mockserver/server.js
Using JsonRefs to resolve references to the models directory, but it unfortunately does not yet resolve references between model files.
This adds a new route at "/", which serves up index.html, which provides links to each swagger-ui view. So the existing /api/swagger-ui/ view is not modified in any way.
```diff
```
=> DHFPROD-4752: Generating a swagger-ui view for the models OpenAPI file

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/AbstractHubTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/PiiE2E.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/DebugLibTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/models/CreateAndUpdateModelTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/entity/EntityManagerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/legacy/collector/EmptyLegacyCollectorTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/legacy/flow/LegacyFlowManagerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/legacy/job/LegacyTracingTest.java, web/src/test/java/com/marklogic/hub/web/service/LegacyFlowManagerServiceTest.java
Submitting this as part of DHFPROD-4440, which involves step processors. I started writing a JUnit test for this and realized that our tests can be sped up by not having to load hub artifacts all the time (because clearDatabases no longer needs them) and by not having to generate and deploy entity-based search options, which are never used. 
Main change is that clearDatabases in HubTestBase no longer deletes the hub-core-artifact collection. That keeps all DH core artifacts present. Had to improve some legacy tests that were assuming that the database was empty after calling clear (making assertions on the number of docs in a database leads to brittle tests).
Also made a tweak to LoadUserModulesCommand that both speeds up tests and fixes a long-standing issue when running "mlWatch", which …
=> DHFPROD-4440: Improving how resetProject works in HubTestBase

Jenkinsfile, build.gradle
Ignoring Test failures on gradle task, pipeline will eventually fail when the junit report is published.
gradle task fails in case of compilation errors.
Removing true
```diff
```
=> DHFPROD-4758: Fail the pipeline in case of compilation errors.

marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java
Same problem as before, the assertions were based on an assumption that no document exist in the staging/final/job databases.
```diff
```
=> DHFPROD-4440: Another fix for EndToEndFlowTests

_pages/deploy/deploy-to-dhs.md
DHFPROD-4788 - Docs 4.x: Revert changes from DHFPROD-2952
Reverted to the second-to-last revision of deploy-to-dhs.md and corrected the link to the e2e example.
```diff
```
- [n/a - brand new branch from "docs" branch] Rebase the branch with upstream
- [n/a] Squashed all commits into a single commit
=> DHFPROD-4788: Docs 4.x - Revert changes from DHFPROD-2952

examples/step-processors/.gitignore, examples/step-processors/README.md, examples/step-processors/build.gradle, examples/step-processors/data/10248.json, examples/step-processors/data/10249.json, examples/step-processors/entities/Order.entity.json, examples/step-processors/flows/orderFlow.flow.json, examples/step-processors/mappings/OrderMappingJson/OrderMappingJson-1.mapping.json, examples/step-processors/src/main/ml-modules/root/custom-modules/step-processors/addHeaders.sjs, examples/step-processors/src/main/ml-modules/root/org.example/addPermissions.sjs, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowInputs.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/invoke-step.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/AbstractHubTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/ReferenceModelProject.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/models/GetPrimaryEntityTypesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStepWithProcessorsTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/flow-utils/getMetadata.sjs, marklogic-data-hub/src/test/resources/entity-reference-model/entities/Customer.entity.json, marklogic-data-hub/src/test/resources/entity-reference-model/entities/Order.entity.json, marklogic-data-hub/src/test/resources/entity-reference-model/flows/echoFlow.flow.json, marklogic-data-hub/src/test/resources/entity-reference-model/flows/stepProcessors.flow.json, marklogic-data-hub/src/test/resources/entity-reference-model/modules/root/custom-modules/custom/echoStep/echoStep.sjs, marklogic-data-hub/src/test/resources/entity-reference-model/modules/root/custom-modules/step-processors/addHeaders.sjs, marklogic-data-hub/src/test/resources/entity-reference-model/modules/root/custom-modules/step-processors/addPermissions.sjs, specs/models/Flow.schema.json
Included a new "step-processors" example project to document the feature. 
There are a lot of changes in flow.sjs, but much of this was due to 1) renaming variables for consistency, and 2) moving existing code into two new functions - writeProvenanceData and updateBatchDocument - so that "runFlow" isn't quite so big. 
The actual new stuff in flow.sjs is fairly minimal - it's the new applyProcessorsBeforeContentPersisted function, and I had to change the if/else that invokes a step module based on acceptsBatch=true. That block of code no longer adds content objects to the writeQueue, because it first needs to apply processors before adding content to the writeQueue.
```diff
```
=> DHFPROD-4440: Steps now support custom processors

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/CreateModelMvcTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelControllerTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/ds-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getMatchingPropertyValues.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getMinAndMaxPropertyValues.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/saveSavedQuery.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/createModel.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/saveModel.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateModelEntityTypes.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateModelInfo.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepDefinition/getStepDefinition.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/models/CreateAndUpdateModelTest.java
Also added new "throwBadRequest" convenience function and updated existing DS endpoints to use this instead of "throw Error" or "new Error". This function returns an error that can then be sent to the UI, as verified by CreateModelMvcTest.
```diff
```
=> DHFPROD-4795: Creating a model with an existing name now fails

marklogic-data-hub/build.gradle
While DH doesn't depend on spring-integration, I found that removing this dependency results in the published DH Gradle plugin no longer working - a classpath conflict occurs. So the spring-integration dependency is bring along some other needed dependency that overrides an older version, thus allowing DH to work correctly. This makes me very sad, but I'm restoring this dependency for now and will figure out the mess later, as there's no reason for DH to be depending on spring-integration otherwise.
```diff
```
=> DHFPROD-4720: Restoring spring-integration dependency

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubModulesCommand.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/SslTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/TlsTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/BaseTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/ExportLegacyJobsTaskTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/HubUpdateTaskTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/InstalledTests.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/JobDeleteTaskTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/ManualMergeUnmergeTaskTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/UpdateIndexesTaskTest.groovy
Undoing the change to defaulting the LHMC batchSize to 10. For some reason, this fails once or twice for tests that do load modules. It seems that a "gradle clean" that's run before "gradle bootstrap" avoids the issue of config.sjs/config.xqy being found twice on the classpath.
```diff
```
=> DHFPROD-3992: Fixing nightly tests, using JS syntax that works on 9.0-12

marklogic-data-hub-central/ui/e2e/cypress/fixtures/users/developer.json, marklogic-data-hub-central/ui/e2e/cypress/fixtures/users/operator.json, marklogic-data-hub-central/ui/e2e/cypress/integration/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.table.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/view-entities.validation.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/index.js, marklogic-data-hub-central/ui/e2e/cypress/support/pages/login.tsx, marklogic-data-hub-central/ui/e2e/setup.sh
Updated e2e test fixtures to include developer and operator user. Added custom commands to cypress.
e2e qa-project will now create these test users while mlDeploy and run the flows as data-hub-developer
FYI @SameeraPriyathamTadikonda, just in case there are any changes required to the pipeline.
```diff
```
=> DHFPROD-4818: Fixing cypress e2e to use developer user

ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/SslTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/TlsTest.groovy
These doc counts didn't really prove anything before, and they fail now that hub-core-artifacts are not cleared when the databases are cleared
```diff
```
=> DHFPROD-4440: Fixing tests, removing assertions on doc counts

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss
Entity table is skewed when the error from XPATH expression is longer. This PR also fixes the issue of 'Type' not displaying fully in entity table. I am not sure if this requires test and if so please provide suggestions as to what kind of tests to add
```diff
```
=> DHFPROD-4743:Entity table is skewed when the error from XPATH expression is longer

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
In my last PR for DHFPROD-4189, I changed 'lastIndexOf' to 'indexOf'. Fixing it.
```diff
```
=> DHFPROD-4189:Use 'lastIndexOf' to get xpath key

marklogic-data-hub-central/ui/src/config/bench.config.ts, marklogic-data-hub-central/ui/src/pages/Bench.test.tsx
Source format now correctly displayed in flow steps:
The fix was actually added with this:
https://github.com/marklogic/marklogic-data-hub/pull/3876
This commit adds tests for default (JSON) and non-default (XML) steps.
```diff
```
=> DHFPROD-4709: Show correct source format for Load steps in flow

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractMvcTest.java
There is a bug in MockMvc that causes ConcurrentModificationException
when it tries to read the response headers for async requests in
order to print the response.
```diff
```
=> DHFPROD-4894: Stop printing requests/responses on MockMvc test failure

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/HubCentral.java, marklogic-data-hub-central/src/main/resources/application.properties, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/HubCentralTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/ClearUserDataTest.java
Also added mlManageSimpleSsl/mlManageScheme to the list of properties to set default values for in DHS and for local dev. These are now needed because clearUserData talks to the Manage API.
```diff
```
=> DHFPROD-4775: Fixing ClearUserDataTest on ML 9.0-10-12

marklogic-data-hub/src/main/java/com/marklogic/hub/HubClient.java, marklogic-data-hub/src/main/java/com/marklogic/hub/collector/impl/CollectorImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubClientImpl.java
This ticket will likely go into Sprint 30. It was a simple change to make (as someone else did the real work), so I want to see how the tests run with this. 
This is the result of DHFPROD-4533, where performance testing confirmed that this approach of accessing the underlying OkHttpClient results in good performance and the same functional behavior. I ran all the tests locally, and all of them passed.
```diff
```
=> DHFPROD-4880: Using the Java Client for collecting URIs

examples/reference-entity-model/flows/CustomerFlow.flow.json, examples/reference-entity-model/mappings/CustomerMappingJSON.mapping.json
"orders" is a relation property to a separate primary entity type, and we don't support that.
```diff
```
=> DHFPROD-4864: Couple fixes for example project

marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
This contains the UI changes to use entityTypeId instead of entityName as targetEntityType for creating mapping artifacts.
Also removed few unnecessary console logs from entityType component.
```diff
```
=> 4865-mapping-bug: Updated the mapping UI components to use targetEntityId instead of entityName to create mapping artifact.

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/security.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/security/getAuthoritiesTest.sjs
Add 'operator' authority if user has the 'data-hub-operator' role. I believe this will be a temporary fix that will go away once @ryanjdew 's  security stories get merged 
```diff
```
=> DHFPROD-4933:Add 'operator' authority if user has the 'data-hub-operator' role

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/config/data.config.js, marklogic-data-hub-central/ui/src/util/test-utils.tsx
This PR enables the Collapse All and Expand All buttons in Source and Entity tables in mapping UI.
Also, it fixes the bug where the nested levels used to collapse when navigating between source documents, using the navigation buttons.
```diff
```
=> DHFPROD-4216: Collapse All/Expand All buttons for Source and Entity tables in Mapping UI.

build.gradle, marklogic-data-hub/README.md, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/SystemService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/system/getVersions.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/system/getVersions.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/system/service.json, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/system/GetVersionsTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/HubVersionTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/HubVersionTaskTest.groovy
One note - there's some cleanup I'm aiming to do when we do the story for getting rid of mlDHFVersion - the existing Versions class can be simplified a bit at that point. But I didn't want to touch it now because it has to account for DH not being installed, which of course is not a use case for HC. VersionInfo is intended to be a clean, simple way to get version data when you know you can connect to DH. 
```diff
```
=> DHFPROD-4804: Added hubVersion Gradle task

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
This PR fixes the following bugs.
DHFPROD-4936: Source Data is getting combined for 2 different mappings of an entity
DHFPROD-4938: Writing an xml document with no namespace adds an empty namespace
No test required as this just fixes few minor bugs in already existing component.
```diff
```
=> DHFPROD-4936: Source Data is getting combined for 2 different mappings of an entity

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelControllerTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/Customer.java
Was mistakenly using staging before
```diff
```
=> DHFPROD-4985: getPrimaryEntityTypes now uses the final DB client

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss
This PR fixes the bug DHFPROD-4944 where source data table used to overlaps Expand/Collapse button on screen resize. 
Simple and small bug fix so no test is required.
```diff
```
=> DHFPROD-4944: Fixing the issue where source data table overlaps Expand/Collapse button on screen resize

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
This is just another PR for 4398, to fix the 400 error in mapping POST request for XML source doc.
Doesn't need any test.
```diff
```
=> DHFPROD-4398: Fix the 400 error in mapping POST request for an XML doc.

marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/config/tiles.config.ts, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx
Minor updates:
- Update Curate icon color per @jbelonoj request (#FFC53D -> #BC811D)
- Update login landing page per @sbayatpur request (/home -> /tiles)
(Users can still get to temporary landing page via app title link.)
No tests necessary.
```diff
```
=> DHFPROD-4056: Tile UI fixes

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
This PR fixes an issue with irregular filter search pattern for arrays in source docs
Just a minor fix so no test is required here. Test for search already exists.
```diff
```
=> DHFPROD-4845: Fixed the issue with irregular filter search pattern for arrays in source docs

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/rest-api/rewriter/9-rewriter.xml
For testing, I used a script that's attached to 4935
```diff
```
=> DHFPROD-4935: Fixing bad paths in 9-rewriter.xml

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployDatabaseFieldCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/DhsDeployer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/RemoveDatabaseNameFromDatabaseFieldsPayloadTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployAsDeveloperTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployCustomUserFieldsTest.java, marklogic-data-hub/src/test/resources/test-projects/user-fields/ml-config/databases/final-database.json
Need this for a 5.2.2 release. 
```diff
```
=> DHFPROD-5037: DH fields/indexes are now retained during hubDeploy

marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadHubModulesCommandTest.java
I removed the call to load hub modules, which fails intermittently in the Jenkins environment. And it was unnecessary - we know the hub modules have been loaded already, the point of the test was to verify that the versions match. 
This likely isn't related to 4671, just borrowing that JIRA ID because it's the latest commit on develop right now.
```diff
```
=> DHFPROD-4671: Fixing LoadHubModulesCommandTest

azure/flow-runner-function/src/main/java/com/marklogic/dhf/azure/FunctionDataHubFlow.java, examples/dhf4/disconnected-project/gradle.properties, examples/dhf4/external-security/gradle-example.properties, marklogic-data-hub-central/ui/e2e/qa-project/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/gradle_properties, marklogic-data-hub/src/test/java/com/marklogic/hub/core/HubConfigTest.java, web/src/test/java/com/marklogic/hub/web/web/HubConfigJsonTest.java
Was deprecated back in 4.0.1; this is killing it almost completely.  If a user does try to set it (which doesn't impact anything), a warning message will be logged informing the user that they can safely remove the property from their configuration.
```diff
```
=> DHFPROD-5079: Removing mlLoadBalancerHosts

examples/step-processors/src/main/ml-modules/root/custom-modules/step-processors/addHeaders.sjs, examples/step-processors/src/main/ml-modules/root/org.example/addPermissions.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/resources/entity-reference-model/modules/root/custom-modules/step-processors/addHeaders.sjs, marklogic-data-hub/src/test/resources/entity-reference-model/modules/root/custom-modules/step-processors/addPermissions.sjs
It doesn't expect a contentArray to be returned, so cleaned up the examples / tests
```diff
```
=> DHFPROD-5065: Making behavior of applyProcessors more apparent

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/config/load.config.ts
This PR involves removal of the default collections from Target Collections field in Advanced Settings dialog.
```diff
```
=> DHFPROD-4388: Removing the default collections from Target Collections field in Advanced Settings dialog

examples/reference-entity-model/entities/Customer.entity.json, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EntitySearchController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/EntitySearchPropertyDefinitionSchema.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/EntitySearchResponseSchema.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/EntitySearchResultPropertySchema.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/EntitySearchResultSchema.java, specs/models/EntitySearchPropertyDefinition.schema.json, specs/models/EntitySearchResponse.schema.json, specs/models/EntitySearchResult.schema.json, specs/models/EntitySearchResultProperty.schema.json
This defines additions to an ML JSON search response. 
It also adds to the Customer reference entity to address some missing scenarios. 
The Swagger can be viewed at localhost:8080/swagger-ui.html, but our JSON Schema -> Swagger generator doesn't like certain things in the spec, such as "oneOf". So it's best to look at these specs directly to understand them.
```diff
```
=> DHFPROD-5060: Spec for returning entity properties in search

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/managers/EntitySearchManager.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/models/DocSearchQueryInfo.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/managers/EntitySearchManagerTest.java
I think the root cause is that the UI is passing empty strings, but this at least prevents an error from occurring.
```diff
```
=> DHFPROD-5110: Entity types that are empty strings no longer cause error

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EntitySearchController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/Constants.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/FacetHandler.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/impl/CollectionFacetHandler.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/impl/CreatedOnFacetHandler.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/impl/EntityPropertyFacetHandler.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/impl/JobRangeFacetHandler.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/models/DocSearchQueryInfo.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/models/Document.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/models/SearchQuery.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/managers/EntitySearchManager.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/EntitySearchControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/impl/AbstractFacetHandlerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/impl/CollectionFacetHandlerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/impl/CreatedOnFacetHandlerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/impl/EntityPropertyFacetHandlerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/impl/JobRangeFacetHandlerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/managers/EntitySearchManagerTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getOpticPlan.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs
Moved the logic for filtering out array/object type properties to the data service.
Also, we now use the entity model to filter out array/object type properties instead of relying on the column names sent by the FE.
```diff
```
=> DHFPROD-4984: Filter object/array type properties using entity model

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/Versions.java, web/src/main/java/com/marklogic/hub/web/service/EnvironmentConfig.java, web/src/main/ui/app/components/header/ui/header-ui.component.html, web/src/main/ui/app/components/login/ui/login-ui.component.html, web/src/main/ui/app/models/hub-settings.model.ts, web/src/main/ui/app/services/environment/environment.service.ts
Instead of reverting (https://github.com/marklogic/marklogic-data-hub/pull/4061), I think this may address QS's dependency on mlDHFVersion. 
This is now populated via versions.getLocalProjectVersion. And the header of QS has been 
changed to reference runningVersion instead of local project version.
```diff
```
=> DHFPROD-4912: Fixing QS's dependency on dhfversion

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.module.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/config/messages.config.ts, marklogic-data-hub-central/ui/src/config/mocks.config.ts, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java
```diff
```
Validate 'Target Permissions' in HC (It was already added as part of DHFPROD-4388, modified the tooltip here)
=> DHFPROD-4971:Validate 'Target Permissions'  in HC

examples/reference-entity-model/src/main/ml-config/security/users/hub-developer.json, examples/reference-entity-model/src/main/ml-config/security/users/pari.json, examples/reference-entity-model/src/main/ml-config/security/users/wailin.json, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowMvcTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/FlowControllerTest.java, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx, marklogic-data-hub-central/ui/src/config/authorities.config.ts, marklogic-data-hub-central/ui/src/config/mocks.config.ts, marklogic-data-hub-central/ui/src/config/run.config.ts, marklogic-data-hub-central/ui/src/pages/Curate.tsx, marklogic-data-hub-central/ui/src/pages/Load.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx, marklogic-data-hub-central/ui/src/util/authorities.tsx, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-read-flow.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-read-step.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-write-flow.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-common-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-common.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-flow-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-step-runner.json, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/Installer.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/getAuthoritiesTest.sjs, specs/docs/security/DataHubSecurity.md
Also:
-  adjusted the privileges to data-hub-common to be able to call mlHubversion extension
- fixed an issue where flow-operator was needed in addition to hub-central-step-runner on ML 9.0-12
```diff
```
=> DHFPROD-4670: Add hub-central-flow-writer role

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.tsx
Updated collapse/expand button labels in Mapping Step Details and changed 'Output URI Prefix' to 'Target URI Prefix' for consistency in Load Data form.
```diff
```
=> DHFPROD-5093: Terminology changes to Hub Central

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowMigrator.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowMigratorTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/TestObject.java, ml-data-hub-plugin/build.gradle, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/DeleteInstalledLegacyMappingsTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/MigrateProjectFlowsTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/hub/gradle/task/DeleteInstalledLegacyMappingsTaskTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/hub/gradle/task/MigrateProjectFlowsTaskTest.groovy
The new Gradle task is a combo of deploying user artifacts and deleting legacy mappings. 
Renamed hubMigrateFlows to hubMigrateProjectFlows to make it more clear that it only impacts the project files.
```diff
```
=> DHFPROD-5032: Can now migrate installed flows

marklogic-data-hub-central/ui/e2e/setup.sh
hubMigrateFlows task name has changed to hubMigrateProjectFlows. Updated setup script for qa-project in e2e.
```diff
```
=> DHFPROD-5189: Update migrate task name for qa-project setup

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
Added source-to-entity-map.scss for antd style override.
Modified source-to-entity-map.tsx and updated source-to-entity-map.modules.scss
When a filter is in use, the filter icon is now highlighted in a more noticeable fashion.
```diff
```
=> DHFPROD-5044: Highlight filter icon when mapping source is being filtered

examples/reference-entity-model/src/main/ml-config/security/users/bertrand.json, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/EntitySearchControllerTest.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-entity-exporter.json
Added necessary roles and privileges for user with role "hub-central-entity-exporter" to export CSV data. Also correctly renamed a file and added "hub-central-saved-query-user" role to the bertrand user in reference-entity-model.
```diff
```
=> DHFPROD-5139: User with hub-central-entity-exporter role can't export data

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/search-summary/search-summary.tsx, marklogic-data-hub-central/ui/src/config/guided-tour-steps.js, marklogic-data-hub-central/ui/src/config/tooltips.config.js
Changed the word "documents" to "results"/"records" in various areas in the UI visible to the user to remove MarkLogic specific language.
```diff
```
=> DHFPROD-5170: Remove the word "documents" in search results

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/RunFlowTask.groovy
I could not figure out how to test just this change, i.e. without setting up a real project with a flow file and an options file (I imagine previous editors of this file ran into the same problem, as we have very little coverage of this class). The fix is obvious though. I did a manual test in the reference project where I added {"disableJobOutput":true} to an options.json file, then referenced it via -PoptionsFile and also included -PshowOptions=true, and that worked correctly - i.e. no job/batch documents were created.
```diff
```
=> DHFPROD-5083: Fixed reference to optionsFile in hubRunFlow

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubDatabaseCommand.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/DeployHubDatabaseCommandTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-utils/replaceLanguageWithLang.sjs
Also fixed the name of what's now replaceLanguageWithLang.
```diff
```
=> DHFPROD-4976: Retaining language in database files when it's valid

marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts, marklogic-data-hub-central/ui/src/assets/mock-data/advanced-settings.data.ts, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.tsx
View Custom ingestion step. It should show up in "Load"  tile as usual and on opening "Settings", "Step Definition Name" should be present(which is not present for ootb ingestion step).
https://wiki.marklogic.com/display/ENGINEERING/Data+Load?preview=/125169351/171055005/CustomLoadDataSettings.png
```diff
```
=> DHFPROD-4997:View Custom ingestion step

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractHubCentralTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/MappingControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/managers/MapSearchManagerTest.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-user.json, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/ReferenceModelProject.java
Doing this as part of 4180 to help ensure tests for deleting an entity model are running as a minimally-privileged user.
```diff
```
=> DHFPROD-4180: HC tests now run as hub-central-user by default

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/SwaggerConfig.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/AbstractModelTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/CreateAndUpdateModelTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/DeleteModelTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelMvcTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub-central/src/test/resources/test-projects/delete-model-project/entities/Entity1.entity.json, marklogic-data-hub-central/src/test/resources/test-projects/delete-model-project/entities/Entity2.entity.json, marklogic-data-hub-central/src/test/resources/test-projects/delete-model-project/flows/testFlow.flow.json, marklogic-data-hub-central/src/test/resources/test-projects/delete-model-project/steps/mapping/testMap1.step.json, marklogic-data-hub-central/src/test/resources/test-projects/delete-model-project/steps/mapping/testMap2.step.json, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ModelsService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/mapping/MappingImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-entity-model-writer.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-delete-trigger.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-trigger.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/getModelReferences.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/getModelReferences.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/main/resources/scaffolding/Entity.json, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/ApplyDownloadedZipToProjectTest.java, marklogic-data-hub/src/test/resources/test-projects/download-artifacts/entities/Order.entity.json, marklogic-data-hub/src/test/resources/test-projects/download-artifacts/entities/Person.entity.json, marklogic-data-hub/src/test/resources/test-projects/download-artifacts/flows/testFlow.flow.json, marklogic-data-hub/src/test/resources/test-projects/download-artifacts/step-definitions/custom/testStep/testStep.step.json, marklogic-data-hub/src/test/resources/test-projects/download-artifacts/steps/ingestion/validArtifact.step.json, ml-data-hub-plugin/src/test/resources/my-new-entity.entity.json
* Added two new endpoints
1. GET /api/models/{modelName}/references - Returns the usage of the model in steps and other models
2. DELETE /api/models/{modelName} - Deletes the model
* Updated `hub-central-entity-model-writer` role to make it work with deletion.
* Added update permission for `data-hub-entity-model-writer` role on schema and TDE docs.
* Fixed the baseUri to include the closing `/`
```diff
```
=> DHFPROD-4180: Delete entity model

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/deleteStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/getStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/saveStep.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommandTest.java
This fixes an issue where default step properties were not being applied to manually created steps.
```diff
```
=> DHFPROD-5240: Loading steps via StepService now

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubArtifactsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/saveStep.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommandTest.java
This fixes an issue introduced by 5240 where loading steps failed because the OOTB step definitions didn't exist yet
```diff
```
=> DHFPROD-5240: Fixing the order of loading hub and user artifacts

marklogic-data-hub-central/ui/src/pages/TilesView.scss
- Changed gray background of Expand/Collapse headers inside Curate and Run Tile.
```diff
```
=> DHFPROD-5077: Remove gray background from Expand/Collapse headers

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
No good way to do an automated test for this; just verified manually by adding the following to the reference project's build.gradle file:
repositories {
jcenter()
}
dependencies {
mlBundle "com.marklogic:marklogic-unit-test-modules:1.0.beta"
}
=> DHFPROD-4713: hubDeployAsDeveloper now calls mlPrepareBundles

marklogic-data-hub-central/ui/src/App.scss
- Override for ant design table row hover color to the requested '#E9F7FE' color. 
- Applies to all instances of table rows across Hub Central.
```diff
```
=> DHFPROD-5076: Fix hover color for Mapping Step Details and other places

marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/hub-central-manage-saved-query.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/hub-central-saved-query-user.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/getEntityInstance.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/instanceWithAdditionalProperty.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/instanceWithNonExistentModel.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/jane.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/jane.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/sally.xml
DHFPROD-5126: Support XML instances in search results transform
DHFPROD-5276: Change manageSavedQuery privilege to savedQueryUser
```diff
```
=> DHFPROD-5126: Support XML instances in search transform

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/SwaggerConfig.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/CreateAndUpdateModelTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelMvcTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ModelsService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-entity-model-writer.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateModelEntityTypes.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateModelEntityTypes.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/models/CreateAndUpdateModelTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesTest.java
* Changed updateModelEntityTypes endpoint from
`PUT /{modelName}/entityTypes to PUT /entityTypes` with request body
```
[
{
"entityName":"string",
"modelDefinition":{}
}
]
```
* hub-central-entity-model-writer role can now deploy protected-paths, query-rolesets and database indexes.
* Updated Model Controller test to use hub-central-entity-model-writer role.
```diff
```
=> DHFPROD-5156: Save all entity models

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/customStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/saveStep.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/manageIngestionStep.sjs
Fix deployment of non-ootb ingestion steps. Setting the stepDefinitionName to 'default-ingestion' if it is not specified else use the one specified. Currently, the stepDefinitionName is set to 'default-ingestion' no matter the value of 'stepDefinitionName' in the request payload
```diff
```
=> DHFPROD-4997:Fix deployment of non-ootb ingestion steps

marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/components/header/header.module.scss, marklogic-data-hub-central/ui/src/components/tiles/toolbar.module.scss, marklogic-data-hub-central/ui/src/pages/TilesView.module.scss, marklogic-data-hub-central/ui/src/pages/TilesView.scss
- Added inner container wrapping footer and main content so users can scroll while header/toolbar remain fixed.
- Disabled browser scrollbar that was located inside the toolbar.
- New scrollbar is to the left of toolbar and outside of inner tile.
```diff
```
=> DHFPROD-5081: Hub Central header and toolbar should be sticky

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/tim.json
Adds handling for empty and null primaryKeys in the backend. Also added an empty primaryKey test. This is in addition to merged PR https://github.com/marklogic/marklogic-data-hub/pull/4132
```diff
```
=> DHFPROD-5204: backend - adding tests to creating primaryKey value

marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/StepRunnerService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepRunnerFactory.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepRunner/processUris.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepRunner/processUris.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepRunner/runSteps.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepRunner/runSteps.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepRunner/service.json, marklogic-data-hub/src/main/resources/ml-modules/services/mlRunFlow.sjs
All inputs are passed in a JSON object to the DS endpoint. This fixes an issue where the mlRunFlow endpoint fails when the string of request parameters is too long (mostly due to the length of each URI and the batch size). 
Cleaned up a few other things while I was at it:
- The sourceDatabase field wasn't used in QueryStepRunner, so removed it from QSR and from StepRunnerFactory (as it doesn't apply to WriteStepRunner either)
- The destinationDatabase field was actually never used in QSR either; the "target-database" param passed by FlowResource to mlRunFlow was never used. 
- Modified StepRunnerFactory to only set destinationDatabase on WriteStepRunner and removed it from the StepRunner interface
```diff
```
=> DHFPROD-5286: Processing URIs for a step now uses DS endpoint

marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/HubCentralManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java
* Changed the return type of `runCollector` to  `DiskQueue` as that's what we are returning.
```diff
```
=> DHFPROD-5283: Close resources

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/ui/src/assets/mock-data/entity-search.js, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.module.scss, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/util/data-conversion.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/transforms/hubEntitySearchTransform.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs
This PR contains changes for the tickets mentioned below.
DHFPROD-5112: Display default properties for "all entities" search results
DHFPROD-5152: Detail view column in the tabular view is missing
DHFPROD-5101: Expanded row render in the table view is missing after changes to the new table
```diff
```
=> DHFPROD-5112: Display default properties for "all entities" search results

marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
This is a small bug fix so no test is required.
```diff
```
=> DHFPROD-5313: Fixing the bug where clicking on expanded row render breaks the UI when there is no primary key

marklogic-data-hub-central/ui/src/App.test.tsx, marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/user-context-mock.ts, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.test.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.tsx, marklogic-data-hub-central/ui/src/pages/Overview.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx, marklogic-data-hub-central/ui/src/services/user-preferences.tsx, marklogic-data-hub-central/ui/src/types/user-types.ts, marklogic-data-hub-central/ui/src/util/user-context.tsx
Make the different tile views "URL accessible," i.e.:
/tiles/load -> Load view
/tiles/model -> Model view
/tiles/curate -> Curate view
/tiles/run -> Run view
/tiles/explore -> Explore view
Notes:
- Refactored routing in Add.tsx to add routes for the different tile views.
- Made the tool buttons links to the new routes to enable "open in new window" clicking etc.
- Refactored user-context to remove props no longer needed (redirect, etc).
- Removed some routes that are no longer relevant.
- Refactored add-step-to-flow feature based on new routes (use /tiles/run/add for that).
Updated tests (with @bsrikan's help), all passing.
```diff
```
=> DHFPROD-5066: Add routes and links for handling tile view

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/Versions.java, marklogic-data-hub/src/main/resources/scaffolding/gradle/wrapper/gradle-wrapper.properties, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java
Added some logging and a try/catch on updating mapping steps, just in case the call to get the ML version bombs. 
The actual fix is in Versions - we now fallback to ml:hubversion if mlHubversion can't be hit. See the comments about the complexity/value of an automated test for this.
Finally, I bumped up the Gradle version in the scaffolded gradle-wrapper.properties to be 6.2.2. The user will really need to do this first (since it can't be done as part of "./gradlew hubUpdate), but I wanted to correct this here as I think not doing it was an oversight in the ticket for upgrading to Java Client 5.2.0.
```diff
```
=> DHFPROD-5393: Can now run hubUpdate on DHF 4.3.x

examples/dhf5-custom-hook/README.md, examples/dhf5-custom-hook/entities/Customer.entity.json, examples/dhf5-custom-hook/flows/LoadCustomers.flow.json, examples/dhf5-custom-hook/input/customers/customers.csv, examples/dhf5-custom-hook/mappings/LoadCustomers-MapCustomers/LoadCustomers-MapCustomers-0.mapping.json, examples/dhf5-custom-hook/src/main/ml-modules/root/custom-modules/mapping/MapCustomers/custom-uri-hook.sjs
This example builds upon the DHF5-custom-hook example to show
how a user can create a custom hook on a mapping step to set
the uri of a document.
```diff
```
=> Fixing Issue #4121: Create an example of a custom hook updating a URI

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.hub/config.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/stepDefinition.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/AbstractHubCoreTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/DocumentMetadataHelper.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsWithCustomPermissionsTest.java
The values of mlFlowPermissions, mlStepDefinitionPermissions, and mlEntityModelPermissions are now applied by the DS endpoints for these artifact types.
```diff
```
=> DHFPROD-5407: Permission properties now work again

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java
Not changing `runHarmonizer` to accept a DiskQueue as runHarmonizer is also called by `run(Collection<String> uris)` which is part of our public API.
```diff
```
=> DHFPROD-5329: Close the resource only after running the job

marklogic-data-hub/src/main/java/com/marklogic/hub/util/QueryRolesetUtil.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/models/GenerateProtectedPathForXmlEntitiesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/AllArtifactsProject.java, marklogic-data-hub/src/test/resources/test-projects/entity-with-indexes/entities/Person.entity.json
Also added more exception handling for query rolesets, as the Manage API endpoint for them changed in ML 10.0-4 such that "PUT" is no longer available.
```diff
```
=> DHFPROD-5461: Fixing generation of protected paths

marklogic-data-hub-central/ui/src/assets/mock-data/common.data.ts, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
- Mapping test results of arrays with multiple values are now displayed on separate lines
- Maximum of two values shown and then '(X more)' all on separate lines
- Refactored RTL tests and test data to accommodate new response from backend and how it is handled in the UI.
```diff
```
=> DHFPROD-5187: Display mapping test results for arrays on separate lines

marklogic-data-hub-central/ui/src/App.test.tsx, marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts, marklogic-data-hub-central/ui/src/components/header/header.tsx, marklogic-data-hub-central/ui/src/components/modal-status/modal-status.test.tsx, marklogic-data-hub-central/ui/src/components/modal-status/modal-status.tsx, marklogic-data-hub-central/ui/src/pages/NoResponse.module.scss, marklogic-data-hub-central/ui/src/pages/NoResponse.test.tsx, marklogic-data-hub-central/ui/src/pages/NoResponse.tsx
Display error page when middle tier goes down.
Display of error view will happen upon:
- Switching tile tools or other route-changing navigation
- Opening system info dialog
- Clicking buttons in session dialog
Update modal-status tests to handle async systemInfo check.
```diff
```
=> DHFPROD-4456: Handle no network response

examples/reference-entity-model/.gitignore, examples/reference-entity-model/entities/Customer.entity.json, examples/reference-entity-model/src/main/entity-config/databases/final-database.json, examples/reference-entity-model/src/main/entity-config/databases/staging-database.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployEntityIndexesTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/com/marklogic/hub/impl/generate-indexes.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateSearchOptions.sjs, marklogic-data-hub/src/test/resources/test-projects/entity-with-indexes/entities/Person.entity.json
- Enable sorting for entity properties marked sortable via modeling
- removing src/main/entity-config/databases reference from gitignore in reference-entity-model
- Adding sortable properties to the Customer entity model
```diff
```
=> DHFPROD-5017: Enable sorting for entity properties marked sortable via modeling

marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MappingService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateFunctionMetadataCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/Versions.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/generateMappingTransforms.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/generateMappingTransforms.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/LoadTestModules.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/GenerateFunctionMetadataCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployAsDeveloperTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommandTest.java, marklogic-data-hub/src/test/resources/entity-reference-model/flows/simpleMapping.flow.json, marklogic-data-hub/src/test/resources/entity-reference-model/mappings/SimpleCustomerMapping/SimpleCustomerMapping-1.mapping.json, marklogic-data-hub/src/test/resources/entity-reference-model/modules/root/custom-modules/mapping-functions/echoFunction.sjs
Did a little cleanup too:
- LoadTestModules can now construct a HubConfigImpl using host/username/password, which means it can pass a HubConfig to GenerateFunctionMetadataCommand
- So got rid of obsolete constructors in GFMC
- And LoadTestModules doesn't need to call Versions(appConfig), so got rid of that from Versions
This was some overdue cleanup - I had created the above stuff before HubConfig(host,username,password) existed. But now that we have that constructor (which I realized needs to call applyProperties too, though that wasn't previously causing any problems), LoadTestModules doesn't need the stuff that existed in GFMC and Versions only for it.
```diff
```
=> DHFPROD-5504: Generating function metadata now regenerates transforms

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesTest.java, marklogic-data-hub/src/test/resources/logback.xml
This is close to a re-write of the command. All privileges are now built in memory before any are saved. Each is then saved via the same process, which checks for an existing privilege with the same action.
```diff
```
=> DHFPROD-5497: Creating granular privileges will now reuse existing ones

marklogic-data-hub-central/ui/src/assets/mock-data/common.data.ts, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
- Arrays of multi-values no longer show up in separate rows with duplicate names in 'Name' column.
- Multi values are now displayed as a list in a single row under a single 'Name'. 
- Hovering over values (truncated or not) in Source table now shows full text inside tooltip.
- Added tests for verifying truncated values and tooltip displaying all values on hover.
```diff
```
=> DHFPROD-5186: Display multi-value property of simple values as a list in source table

marklogic-data-hub-central/ui/src/pages/Curate.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/util/environment.tsx
Update HC tool views such that all views handle cases when middle tier has gone down (a 504 error results and an error dialog appears in the UI). This includes when clicking the Download button under Manage Project. Here is a screencast:
https://drive.google.com/file/d/1LB2WTXT75m4O1Z-E0KBkUIrXIxcJRPMt/view
```diff
```
=> DHFPROD-4456: Ensure all tools handle middle tier failure

marklogic-data-hub-central/ui/e2e/README.md, marklogic-data-hub-central/ui/e2e/setup.sh
Changes to setup script
Moving README to e2e
No tests needed. This is so pipeline can run Cypress tests successfully.
```diff
```
- [ NA] Added Tests
=> DHFPROD-5190: include environment property when saving indexes and move readme to e2e

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubDatabaseCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/DeployHubDatabaseCommandTest.java
This isn't an issue yet, but it could be in the future. This ensures that after we merge an entity-config file with another database file, the output does not have any tokens in it that still need to be replaced.
```diff
```
=> DHFPROD-5493: entity-config files now have tokens replaced

marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/Main.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/Options.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/MainTest.java
Also improved the error that's shown when the required args aren't specified. The usage is now shown.
```diff
```
=> DHFPROD-5540: Fixing help message in installer

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java
Remove granular privileges before removing databases. This fixes both DHFPROD-5535 and DHFPROD-5553. Tests in jenkins should run fine after this
```diff
```
=> DHFPROD-5553:Remove granular privileges before removing databases

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/resetUser.json
Fixes set user with roles and reseting them on windows. Using a file based approach instead of passing data object directly to fix windows issue.
Also included fix to load test since Card view is the new default view.
Added little tweaks so tests run consistently in slower environments.
Verified to work in mac and windows.
```diff
```
=> DHFPROD-5466: Fix for windows and minor tweaks for consistent test results

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStepWithProcessorsTest.java, marklogic-data-hub/src/test/resources/entity-reference-model/flows/stepProcessors.flow.json, marklogic-data-hub/src/test/resources/entity-reference-model/modules/root/custom-modules/step-processors/moduleThrowsError.sjs
Added some logging to QueryStepRunner so it's easier to see when a step starts and finishes too.
```diff
```
=> DHFPROD-5055: stopOnError now works with step processors

marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-clear-user-data.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-clear-user-data.json
Removing "data-hub-clear-user-data" privilege as it's no longer used. No tests required for this,
```diff
```
=> DHFPROD-5574:Removing "data-hub-clear-user-data" privilege as it's no longer used

marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/migration/FlowMigrator.java, marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/migration/HubCentralMigrator.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/migration/EntityModelMigratorTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/migration/FlowMigratorTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/DeleteLegacyMappingsTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/hub/gradle/task/DeleteLegacyMappingsTaskTest.groovy
While writing docs for this, made these changes:
- Now backing up ./entities to ./migrated-entities
- Renamed "hubDeleteInstalledLegacyMappings" to "hubDeleteLegacyMappings" 
- Removed "hubMigratedInstalledFlows", which doesn't account for entity models; the docs will just tell the user to do a full deploy
```diff
```
=> DHFPROD-5279: Tweaks to HC migration process

CODEOWNERS
I think "/*" is needed for matching files correctly.
```diff
```
=> DHFPROD-5552: Tweaking codeowners file

marklogic-data-hub-central/build-rpm.gradle, marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/src/rpm/configs/hub-central.conf, marklogic-data-hub-central/src/rpm/configs/hub-central.properties, marklogic-data-hub-central/src/rpm/scripts/post-install.sh, marklogic-data-hub-central/src/rpm/scripts/post-uninstall.sh, marklogic-data-hub-central/src/rpm/scripts/pre-install.sh, marklogic-data-hub-central/src/rpm/scripts/pre-uninstall.sh, marklogic-data-hub-central/src/rpm/services/hub-central.service, marklogic-data-hub/build.gradle
The package does not perform a dependency check on Java 11 because the java dependency could be satisfied by various packages (oracle java, openjdk java, etc). We can only add a dependency on one of the packages and if we change the java vendor or the package type in the future on DHS then the RPM will complain and not install. So I think its best not to include this dependency check.
```diff
```
=> DHFPROD-5484: Package hub-central as a RPM

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getMatchingPropertyValues.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getMinAndMaxPropertyValues.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/deleteSavedQueryTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/getMatchingPropertyValuesTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/getMinAndMaxPropertyValuesTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/getSavedQueryTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/saveSavedQueryTest.sjs
DHFPROD-5259: Privilege changes for getMinAndMaxPropertyValues and getMatchingPropertyValues ds endpoints
```diff
```
=> DHFPROD-5678: 9.0-11 test fixes related to entitySearch

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/Installer.java, marklogic-data-hub/src/test/java/com/marklogic/hub_unit_test/RunMarkLogicUnitTestsTest.java
- Moving the deployment of data-hub-test-internal role and amps to Installer class so that tests can be run from http://localhost:8011/test/default.xqy without running the RunMarkLogicUnitTestsTest once. (Currently, the role and amp is deployed by RunMarkLogicUnitTestsTest)
- Adding version compatibility check for deploying indexes in EntitySearchManagerTest to work with 9.0-11 version
```diff
```
=> DHFPROD-5678: Moving deployment of amps from RunMarkLogicUnitTestsTest to Installer and fixing 9.0-11 tests

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getMatchingPropertyValues.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getMinAndMaxPropertyValues.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-es.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/entity/GenerateProtectedPathsTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/hubEsTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/test-data/entities/EntitiesSearchEntity.entity.json
The es namespace and entity def namespace are now included when calling cts.pathReference.
I am not convinced these are fully working yet - the cts.pathReference call may need the second argument populated to specify the correct datatype and collation. Going to do some more testing, but wanted to get this merged ASAP as it's breaking HC. 
Also fixing GenerateProtectedPathsTest on 9.0-11 - need to use DeployHubQueryRolesetsCommand, which ignores the bug in the Manage API that throws an error when updating a query roleset. 
```diff
```
=> DHFPROD-5626: Fix for facet-values APIs

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/Customer.entity.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/Person.entity.json, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.test.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx, marklogic-data-hub-central/ui/src/util/user-context.tsx
- Also Includes https://project.marklogic.com/jira/browse/DHFPROD-5689
- Added an additional role for numeric slider e2e tests to pass
- Previously loadCustomersJSON name facet was shown on the sidebar under name entity properties but it seems to be a bug and loadCustomersJSON has been removed from the facets as part of https://project.marklogic.com/jira/browse/DHFPROD-5018, unfortunately most e2e tests are written based on loadCustomersJSON facet, Addressed all those issues in this PR
```diff
```
=> DHFPROD-5527:Changes to sort should be consideration for actions on Saved Query

marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/DhsDeployer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployAsDeveloperTest.java
Couldn't reproduce it anywhere else, but enabling CMA usage for protected paths worked for me locally.
```diff
```
=> DHFPROD-5626: Attempting to fix protected path issue in e2e project

marklogic-data-hub-central/ui/src/assets/mock-data/common.data.ts, marklogic-data-hub-central/ui/src/assets/mock-data/entity-search.js, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx
Update couple of test to verify empty string in json and xml document.
Also updated test data for explorer test. There is FE bug, where empty string sent by backend is not displayed. Filed a separate bug for that -- DHFPROD-5671
Also removed unused element locators and debug.
```diff
```
=> DHFPROD-3554: Test for input document containing empty string

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-custom-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-ingestion-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-mapping-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-match-merge-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-clear-user-data.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-downloader.json
The download role didn't need data-hub-operator, and the tests for it still ran fine.
The clear-user-data role just needed to swap out data-hub-developer for the individual writer roles. It already had the granular privileges needed for clearing databases. 
```diff
```
=> DHFPROD-5638: Download and clear-user-data roles are now limited

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateSearchOptions.sjs
This avoids search API errors due to duplicate state names. 
```diff
```
=> DHFPROD-5684: Sort state names are now entity type-specific

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/confirmation-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-table.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/types/modeling-types.ts, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/modeling-context-mock.js, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.module.scss, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.test.tsx, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx, marklogic-data-hub-central/ui/src/components/header/header.tsx, marklogic-data-hub-central/ui/src/components/modal-status/modal-status.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/navigation-prompt/navigation-prompt.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/types/modeling-types.ts
updated @testing-library/user-event to v12 for type method no longer being async 
https://github.com/testing-library/user-event/releases/tag/v12.0.0
added @testing-library/dom -> new dependency for user-event
added model reader e2e test
Persist model between tiles + navigation warn when logout: https://drive.google.com/file/d/15jSoV-fe7JgRWs4xeaYaJEBHTmNDrzQY/view
Navigate away with edits: https://drive.google.com/file/d/1eI-cDhw0GlTXd0YDSGvjnVzWsTWjmaOu/view
```diff
```
=> DHFPROD-5371: Navigate away prompt for modeling

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/getMappingFunctions.sjs
Exclude "distinct-values" from the list of mapping functions
```diff
```
=> DHFPROD-4691:Exclude "distinct-values" from the list of mapping functions

marklogic-data-hub-central/ui/src/assets/mock-data/common.data.ts, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
- Fix to XML source data format when there is a Namespace and the property is an array of values, causing invalid XPATH.
(should be 'custOrderInfo: nicknames' instead of 'nicknames')
```diff
```
=> DHFPROD-5359: Incorrect XPATH is generated when Mapping XML documents

marklogic-data-hub-central/ui/src/components/header/header.test.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.module.scss, marklogic-data-hub-central/ui/src/pages/Overview.module.scss, marklogic-data-hub-central/ui/src/pages/TilesView.scss
- Short css fixes to Overview, Tilesview, and zero-state explorer pages so that scrollbar is no longer visible when no scrolling is needed.
- No test for this scenario as could not find a way in RTL to verify the visibility of the scrollbar (elaboration in comments)
- Cleaning up tests from previous PR: https://github.com/marklogic/marklogic-data-hub/pull/4327.
```diff
```
=> DHFPROD-5562: UI Spike: Cross-platform scrollbar UX

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
This PR resolves the bug DHFPROD-5381 and also adds user preferences in explorer.
```diff
```
=> DHFPROD-5381: Upon refreshing the explorer page, the query name and description not persist

marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts, marklogic-data-hub-central/ui/src/assets/mock-data/flows.data.ts, marklogic-data-hub-central/ui/src/components/flows/flows.scss, marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx
Implement "Add Step" dropdown menu in flow container that allows user to add a step to a flow.
Screencast (showing privileged and unprivileged views): 
https://drive.google.com/file/d/1QmtrBnJegwhzoVowwAC-cpfrK-BNGiT9/view
Also:
- Update existing tests to have /api/steps mocked
- Add new roles-based tests for flows component
```diff
```
=> DHFPROD-5047: Add Step menu for flows

marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
No tests to add, this fix is to remove sorting logic on FE and show results what BE is returning. Fixing this also fixed sorting on array properties.
Some related tests to sorting on array properties was already added in  this PR https://github.com/marklogic/marklogic-data-hub/pull/4343
```diff
```
=> DHFPROD-5689:Sorting on array properties causes error

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs
Hub properties remain expanded when a hub property is selected.
```diff
```
=> DHFPROD-5718: Entity name shouldn't appear as facet

marklogic-data-hub-central/ui/src/components/facet/facet.test.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.test.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.tsx
Includes DHFPROD-5383: Collapse/Expand carets in Explorer are backwards
```diff
```
=> DHFPROD-5391: Improper position of spinner in explorer tile results view

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubSecurityAdminTest.java
=> DHFPROD-5753: Custom roles can now inherit pii-reader

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.test.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-5636: User without hub-central-saved-query-user can use Explorer and SavedQueries dropdown is not displayed on Zero state page

marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/migration/FlowMigrator.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/Step.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/migration/FlowMigratorTest.java, marklogic-data-hub/src/test/resources/test-projects/all-steps-referenced/flows/CurateCustomerJSON.flow.json
In 5.3, FlowManagerImpl.getLocalFlow() does not know how to read referenced flows into Step objects. When you attempted to run migration twice, FlowMigrator would crash because of the mostly-empty Step object. (Specifically, trying to use the null result of step.getName().)
This PR is my attempt to make the smallest changes that will allow FlowMigrator.migrateFlows() to run twice.
```diff
```
=> DHFPROD-5746: Migrating flows should be repeatable

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
Add 'namespaces' to mapping step when xml docs are opened. No additional tests needed as we don't immediately save the updated mapping but wait for users to edit the mapping before saving it
```diff
```
=> DHFPROD-5627:Add 'namespaces' to mapping step when xml docs are opened

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-step-runner.json
Beefed up an existing test as hc-step-runner. No role should inherit the internal role, as it's granted via amps when it's needed. 
```diff
```
=> DHFPROD-5766: Removed dh-job-internal from hc-step-runner

marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/edit-query-details.tsx
This PR is just about making the mask of edit query modal as closable so that the design is consistent with all other modals in Hub Central. No test is required for this as all other necessary e2e tests for modals are already available.
```diff
```
=> DHFPROD-5445: Updating default maskClosable property for edit query modal

marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.test.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js
=> DHFPROD-5448: Tooltip missing of Target Format in edit loading step

web/src/main/ui/app/components/jobs-new/ui/job-details-ui.component.html
Use step name to filter documents instead of step definition name in QS. No tests required.
```diff
```
=> DHFPROD-5775:Use step name to filter documents instead of step definition name in QS

marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.module.scss, marklogic-data-hub-central/ui/src/pages/Overview.module.scss, marklogic-data-hub-central/ui/src/pages/TilesView.module.scss
- Solves issue of double scrollbars appearing in tile view.
- Footer fits in the same view as tile to remove need for outer page scrollbar.
- Footer stays pinned at the bottom and in view even when window shrinks.
- No tests needed for css refactoring.
```diff
```
=> DHFPROD-5312: Make a (tile height + footer) fit into 100% of the page to avoid activating page scrollbar

marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx
If the panel for a flow is closed and a step is added to the flow (via the Add Step dropdown), then open the panel.
@jbelonoj has approved. Screencast: https://drive.google.com/file/d/15-g_pGeZOfaJPaAcpi0vgDEVBgeItcuh/view
```diff
```
=> DHFPROD-5778: Open panel after Add Step in Run

marklogic-data-hub-central/ui/src/assets/mock-data/entity-search.js, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
=> DHFPROD-5671: Explorer table does not show empty string sent by backend in the UI

Jenkinsfile, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/DeleteModelTest.java, marklogic-data-hub-central/src/test/resources/test-projects/delete-model-project/flows/testFlow.flow.json, marklogic-data-hub-central/src/test/resources/test-projects/delete-model-project/steps/matching/matching-step.step.json, marklogic-data-hub-central/src/test/resources/test-projects/delete-model-project/steps/merging/merrging-step.step.json, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub-central/ui/src/assets/mock-data/modeling.js, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-entity-model-writer.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/deleteModel.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/getModelReferences.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs
* Assigned `data-hub-match-merge-reader` and `data-hub-custom-reader` roles to `hub-central-entity-model-writer` role so that we can check for entity type references in matching/merging/mastering/custom steps.
* Changed JSON model key from `stepAndMappingNames` to `stepNames`.
```diff
```
=> DHFPROD-5793: Find entity type references in referenced steps

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
Without changing the code quite a bit, it's not possible to write a test for this condition because the null pointer exception (which occurs when stepDefinitionType is not set, which is true for converted steps) is caught and logged. And it's the logged error message that's confusing for users. So this just modifies the "if" condition so that the values being tested are on the right hand side of "equals" instead of the left hand side, thus avoiding the chance of a confusing NPE. 
```diff
```
=> DHFPROD-5840: Avoiding null pointer while upgrading project

marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/cloud/aws/AWSConfiguration.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/cloud/azure/AzureConfiguration.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/web/SslUtil.java
Introduced two new spring profiles specific to Azure and AWS which when activated will try to fetch the certificate artifacts from Azure/AWS services using the configured properties.
Following properties are needed for configuration:
AWS properties
```
spring.profiles.active=aws
aws.s3.bucketName=
aws.s3.keyName=
```
Azure properties
```
spring.profiles.active=azure
azure.keyvault.uri=
azure.storage.endpoint=
azure.storage.containerName=
azure.storage.blobName=
```
```diff
```
=> DHFPROD-5682:5788: Retrieve and apply keystore from cloud services

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesTest.java
Using CMA instead of RMA, and updating roles w/privileges instead of updating privileges w/ roles. Had to update the assertions in the test because the order in which the roles appear in a privilege isn't guaranteed. 
```diff
```
=> DHFPROD-5862: Speeding up deployment of granular privileges

marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ModelsService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/createModel.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/saveModel.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/saveModels.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/saveModels.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateModelEntityTypes.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateModelInfo.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsPerformanceTest.java
Added saveModels.sjs endpoint that saves models to one database only to avoid the combo of xdmp.invoke plus pre/post triggers, which causes performance delays. 
```diff
```
=> DHFPROD-5794: Speeding up saving models

marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/BuildPrettyWriterTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/DetermineInputFilePathTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/WriteStepRunnerTest.java
Fix failing test in windows due to carriage return and absolute path issues.
```diff
```
=> DHFPROD-5634: Fix tests failing in windows 10

marklogic-data-hub-central/ui/src/components/search-result/search-result-rtl.test.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx
=> DHFPROD-5849: Expanding rows remain consistent even after changing page in explorer tile for snippet view.

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx
This PR fixes the bug DHFPROD-5888. e2e tests are already present for saved queries.
Also updated few e2e tests to fix certain intermittent failures.
```diff
```
=> DHFPROD-5888: Handling null values in user preferences for saved queries

marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub-central/ui/e2e/setup.sh
Using cts.estimate in place of fn.count
Included environment property to verify gradle task
```diff
```
=> DHFPROD-5788: Missed environment property for verify tasks

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/auth/WebSecurityConfiguration.java, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/login.tsx, marklogic-data-hub-central/ui/src/App.test.tsx, marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/user-context-mock.ts, marklogic-data-hub-central/ui/src/pages/Detail.tsx, marklogic-data-hub-central/ui/src/pages/noMatchRedirect.test.tsx, marklogic-data-hub-central/ui/src/pages/noMatchRedirect.tsx
NOTE: This update addresses the behavior when running on port 8080. (A port 3000 dev setup already worked.)
When a user is unauthorized and executes an internal browser bookmark or enters an internal URL in the browser bar:
Redirect user to login page.
Include route as URL param to enable redirection.
Redirect to that URL after login.
If the initial route is bad (e.g., /notavalidroute), the user sees a 404 page after login (as would be expected when redirecting to a bad route).
@bsrikan I need to discuss relevant tests for this since this is reliant on server redirection (i.e., not React UI behavior). 
```diff
```
=> DHFPROD-5338: Bookmark redirect

marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployUserAmpsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/GetMLVersionTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
The use of newAppServicesDatabaseClient is failing intermittently. Since we don't need to retain any documents, we can use the Manage API to clear the database. 
```diff
```
=> DHFPROD-5811: Hopefully fixing how schemas dbs are cleared in tests

build.gradle, marklogic-data-hub-central/build.gradle, marklogic-data-hub-glue-connector/build.gradle, marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle, web/build.gradle
Now we don't need mainClassName specified on each subproject. We weren't using the application plugin for anything except by the unused jacoco task in ./build.gradle which has been removed. 
```diff
```
=> DHFPROD-5927: Removing unused Gradle application plugin

examples/reference-entity-model/README.md, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/util/stomp.ts, marklogic-data-hub-central/ui/src/util/user-context.tsx
- Remove 'return to default' sorting (happens on third click on table sort options) for tables across HC (except mapping modal)
- Updated existing tests and added new sorting tests for Entity table 
```diff
```
=> DHFPROD-5584: Remove 'return to default' sorting

marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/conversion/FlowConverterTest.java, marklogic-data-hub/src/test/resources/flow-conversion-test/flows/custom-master.flow.json
Ensure that user defined option is not dropped during HC conversion
```diff
```
=> DHFPROD-5181:Ensure that user defined option is not dropped during HC conversion

specs/models/DataHubEnvelope.schema.json
This is being added to the develop branch so that it can be used by the Spark connector team without having to switch to the 5.4-develop branch. It has no impact on anything in 5.3, other than if the Gradle task generateSchemaPojos is run. And I verified that it runs successfully. 
```diff
```
=> DHFPROD-5945: Schema for a DH envelope

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/facet.js, marklogic-data-hub-central/ui/src/components/facet/facet.test.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.tsx, marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.tsx
Popover search link only shown for a facet when number of facet items is great than a limit (20).
```diff
```
=> DHFPROD-5597: Show search link when facets > 20

marklogic-data-hub-central/ui/src/components/tiles/toolbar.tsx, marklogic-data-hub-central/ui/src/pages/Overview.module.scss, marklogic-data-hub-central/ui/src/pages/Overview.test.tsx, marklogic-data-hub-central/ui/src/pages/Overview.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx
This makes the containers on the Overview landing page clickable links (for users with the right permissions).
Also adds permissions content to containers when the containers are disabled and fixes minor corner radius issues.
To manually test, you can view disabled cards (all except Explore) as hub-user or enabled cards as hub-developer.
Note that this doesn't update the main icons or colors of the cards, that will come in a future story. We're keeping the current Overview page style, see the screenshots here: 
https://project.marklogic.com/jira/browse/DHFPROD-5971?focusedCommentId=184459&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-184459
@jbelonoj has reviewed and approved.
```diff
```
=> DHFPROD-5971: Link Overview containers to tile views

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/WriteStepRunnerTest.java
Set 'outputURIPrefix' to empty string if it's not set
```diff
```
=> DHFPROD-5868:Set 'outputURIPrefix' to empty string if it's not set

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.table.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.tsx
This reverts commit cc6c322ce87e879adac2d433054ed55e98ef1bb7, please refer DHFPROD-5878 ticket for reasons to revert this commit.
Reverting this commit also fixes some explorer e2e tests(https://project.marklogic.com/jira/browse/DHFPROD-6004) failing on DHS
```diff
```
=> DHFPROD-5878:Stop table scrolling in Explorer

marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.scss, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx
- Create a multi-slider component that displays a slider rail with multiple labeled "handles"
- Display an initial example of the slider under the Match tab
Also use @marklogic/react-compound-slider, a modified version of the slider library that supports labeled, crossing handles.
This merge provides @Sanjeevani19 with a slider component to work with for her Mastering work:
https://project.marklogic.com/jira/browse/DHFPROD-5230
No tests necessary for this.
```diff
```
=> DHFPROD-4381: Move slider to curate match

marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/customRole.spec.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.module.scss, marklogic-data-hub-central/ui/src/components/load/load-list.module.scss, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.module.scss, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.test.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx, marklogic-data-hub-central/ui/src/config/tiles.config.ts, marklogic-data-hub-central/ui/src/pages/Curate.module.scss, marklogic-data-hub-central/ui/src/pages/Curate.test.tsx, marklogic-data-hub-central/ui/src/pages/Curate.tsx, marklogic-data-hub-central/ui/src/pages/Load.module.scss, marklogic-data-hub-central/ui/src/pages/Load.test.tsx, marklogic-data-hub-central/ui/src/pages/Load.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.module.scss, marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/pages/Run.module.scss, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx
Also added tests of intro text display across tile views.
Intro text is stored in the config file for tiles.
Screencast is here: https://drive.google.com/file/d/1tXsvwKT0OBxl5l0fKkFFEs2lePbVj62y/view
```diff
```
=> DHFPROD-6027: Add intro text to the top of each tile

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping-functions/core.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/parseDate.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/parseDateTime.sjs
Map empty or null value to null when using parseDate and parseDateTime
```diff
```
=> DHFPROD-4543:Map empty or null value to null when using parseDate and parseDateTime

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataWriter.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/AbstractSparkConnectorTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/Options.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataWithOptionsTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/ingestion/bulkIngester.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/ingestion/BulkIngestTest.java
Configure Document Ingestion, sets the permissions, collections and sources of the document configured through options from Spark
```diff
```
=> DHFPROD-5944: Configure Document Ingestion via connector

marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/ingestion/bulkIngester.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/ingestion/BulkIngestTest.java, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/ingestion/ingestOnlySourceName.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/ingestion/ingestOnlySourceType.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/ingestion/ingestWithAllWorkUnitParams.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/ingestion/ingestWithOnlyCollections.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/ingestion/ingestWithOnlyUriPrefix.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/ingestion/ingestionWithNullParams.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/ingestion/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/lib/ingestionService.sjs
Added some helpers to data-hub-test-helpers.sjs while I was at it. 
Made one tweak to the endpoint to support workUnit being passed in via xdmp.invoke for test purposes. 
```diff
```
=> DHFPROD-5944: Refactored bulk ingest tests to ml-unit-test

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataWriter.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/AbstractSparkConnectorTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataTest.java
Also changed to IllegalArgumentException as a more descriptive version of RuntimeException
```diff
```
=> DHFPROD-5989: Added couple spark tests for null options

marklogic-data-hub-spark-connector/src/test/resources/junit-platform.properties
Disabling the parallel run as the next test picks up before assertions.
```diff
```
=> DHFPROD-6097: Disabling the Parallel Run

marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs
Added try/catch to hubUtils.parsePermissions, which will benefit the other clients of this function who are currently getting somewhat vague error messages
```diff
```
=> DHFPROD-5944: Added test for invalid permissions

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MatchingStepController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MergingStepController.java
Set 'overwrite' param to false in saveStep() for Matching/Merging controllers
```diff
```
=> DHFPROD-6085:Set 'overwrite' param to false in saveStep() for Matching/Merging controllers

marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js
Added few dummy fields in the merge rule modal related to "Merge Type" property, only when chosen as 'Custom'.
```diff
```
=> DHFPROD-5244: Add Custom Merge Type to Merge Rule form

marklogic-data-hub-central/ui/src/components/load/switch-view.scss, marklogic-data-hub-central/ui/src/components/load/switch-view.test.tsx, marklogic-data-hub-central/ui/src/components/load/switch-view.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.scss, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx
Remove background color and use #999 gray for Zero State Explorer switch.
Also update gray of Load switch to #999.
Remove switch-view.module.scss file since not used.
Add RTL tests to switch-view.test.
Screencast: https://drive.google.com/file/d/1Jep9LJKJa7Yn0US3HgyG6FukngC1rxVM/view
```diff
```
=> DHFPROD-5964: Update Zero State Explorer switch

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/common.data.ts, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx
- Handle existing step check when adding Load and Map steps to flows.
- Display warning in confirmation dialog.
- Also track menu selections in state so menus can be reset.
- Update tests to test for when step exists: mapping-card, load-card, load-list
- Refactor of mapping-card.test to remove redundant code.
Screncasts:
Load Card: https://drive.google.com/file/d/1hQwG0AOSpTJJ5GcIw8Yw5c5wzVauhmce/view
Load List: https://drive.google.com/file/d/1WYwvIJgt2Xu0qv4R5trp-ZucQ0JrTX_5/view
Map Card: https://drive.google.com/file/d/1FbpuoDMnWeUCIig0EK6pIfImx6nrVhuG/view
```diff
```
=> DHFPROD-5969: Check if step exists in flow when adding

marklogic-data-hub-central/ui/src/components/header/header.module.scss
Minor style update approved by @jbelonoj. Shrink service name text in header slightly: 22px -> 18px
(Line height also adjusted slightly for consistency across header.) No test updates required.
```diff
```
=> DHFPROD-6040: Decrease font size of service name in header

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/ingestion/bulkIngester.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/TemporalWriteTest.java
If the list of collections specified by the user has a temporal collection then the documents are ingested vi temporal.documentInsert().
```diff
```
=> DHFPROD-5988: Adding temporal collections

web/src/main/java/com/marklogic/hub/web/WebApplication.java, web/src/main/java/com/marklogic/hub/web/web/CurrentProjectController.java, web/src/test/java/com/marklogic/hub/web/web/CurrentProjectControllerTest.java
WebApplication was ending up with 2 HubConfigImpl instances due to ComponentScan'ing all of com.marklogic.hub. I was going to just mark the HubConfigImpl in WebApplication as @Primary, but figured it's safer / easier-to-understand if the packages are listed out. 
Also fixed an issue in CurrentProjectController, which was autowiring in HubProject. Added a simple test to ensure that this class can be autowired successfully. 
```diff
```
=> DHFPROD-6116: Fixing QS on 5.4-develop

CONTRIBUTING.md, marklogic-data-hub-central/build.gradle, marklogic-data-hub-spark-connector/README.md, marklogic-data-hub-spark-connector/build.gradle, marklogic-data-hub/build.gradle, web/build.gradle
The UI files for core will only be built when running "publish" now. 
Same goes for HC, except only when "bootWar" is run ("publish" seems to have no impact for HC). 
Removed the Spark README, as the only thing it was doing was mentioning the need to include skipui. We'll add it back once we have stuff to say in it. 
```diff
```
=> DHFPROD-6113: Removing need to include skipUi and skipWeb

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/JobsController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/JobsControllerTest.java, marklogic-data-hub-central/ui/src/assets/mock-data/curation/flows.data.ts, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/util/json-utils.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/step/RunStepResponse.java, marklogic-data-hub/src/test/java/com/marklogic/hub/step/RunStepResponseTest.java
- Added "targetDatabase" key with the value being the name of the database to RunStepResponse.
- The JobsController then replaces the targetDatabase name with the Database kind (staging/final) so the FE can set the correct database for data exploration.
- Also added the functionality to "explore curated data" by clicking on the status icon for the step.
```diff
```
=> DHFPROD-6121: Set the right target database in mapping step navigation

marklogic-data-hub-spark-connector/spark-test-project/src/main/resources/log4j.properties, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/DefaultSource.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/AtLeastOneWriteFailedMessage.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataWriter.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/AbstractSparkConnectorTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/HandleAbortedWriterTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/HandleFailedWriteTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/Options.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataViaCustomEndpointTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataWithOptionsTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteJobsDataTest.java, marklogic-data-hub-spark-connector/src/test/resources/log4j.properties, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/bulkIngester.api
Also removed the concept of batchSize - the BulkInputCaller already supports this itself, we don't need to maintain a list of records in HubDataWriter. 
As a result of this, rewrote a lot of the tests so that HubDataWriter.commit is called after all the fruit rows are written. This ensures that any pending writes are flushed.
```diff
```
=> DHFPROD-6096: Spark connector now handles write failures and aborts

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/DefaultSource.java
This seems important to see in the logging, particularly when running on DHF 5.2.x
```diff
```
=> DHFPROD-6153: Added logging for when connector writes a module

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx, marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/components/column-selector/column-selector.tsx, marklogic-data-hub-central/ui/src/components/date-facet/date-facet.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/components/facet/facet-element.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx
This is just fixing implementation detail for ant design components, to fix the issue where some components like tooltip, popovers etc., were being fixed to the body element. No tests are required here.
```diff
```
=> DHFPROD-6119: Ant Design components are fixed to body element

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/getMappingFunctions.sjs
Handle duplicate custom mapping functions. This failure https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-4759/10/tests was because there were 2 custom mapping functions of name 'echo'.
```diff
```
=> DHFPROD-6117:Handle duplicate custom mapping functions

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/DefaultSource.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/Options.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteJobsDataTest.java
=> DHFPROD-6163:Add the AWS Glue job info in the job document.

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx, marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.module.scss, marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx
- Added option to run a Load/Curate step in a new flow or run in an existing flow from Card view via Run icon
- Added RTL and Cypress tests for the respective scenarios
- Design reviewed by @jbelonoj, note: Run tooltip will briefly cover the Run menu, but discussed that this is the best option for now.
- note: There is a known bug with adding/running a same step to an existing flow where job details get corrupted. @srinathgit is working on a fix.
```diff
```
=> DHFPROD-5961: Add run icon and 'run in flow' menu to all steps

marklogic-data-hub/src/main/java/com/marklogic/hub/collector/impl/CollectorImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/bulk/fixCreatedByStep.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/ExcludeAlreadyProcessedItemsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunFlowWithInvalidStepDefTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java
The problem was that CollectorImpl was not throwing an exception when the collector failed. It instead returned a single item - the error message (the serialized JSON object from the REST API). That was then processed by the step, which resulted in zero successful items - but also zero failed items. 
Now that the collector properly throws an error, QueryStepRunner can say that if there are no failed items, then the step completed successfully. 
```diff
```
=> DHFPROD-5997: Fixing logic for determining step success

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/flow/getFlowWithLatestJobInfo.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job3.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job4.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job5.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/testGetFlowWithLatestJobInfo.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/testGetFlowsWithStepDetails.sjs
Same as #4810 for 5.3.0. Ensure we can get latest job details if a step is added more than once to a flow
```diff
```
=> DHFPROD-6168:Ensure we can get latest job details if a step is added more than once to a flow

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/ExcludeAlreadyProcessedItemsTest.java
Made what I think is a fix to QueryStepRunner so that if the count of failed items and total items in a batch are both zero, then the batch is considered successful. A batch is now only considered to have failed if there's at least one item that threw an error, which seems to make good sense. 
```diff
```
=> DHFPROD-5997: Fix for determining failed batches

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataSourceWriter.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/Options.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/WriteDataWithUriTemplateTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/writeLib.sjs
This Pull request introduces a "uritemplate" option. With this option you can add a uri template e.g. "/my/uri/prefix/{property1}/{property2}.json
See: https://project.marklogic.com/jira/browse/DHFPROD-6184
=> DHFPROD-6184:  Write records via URI Template using spark connector

marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx
No need for tests as we do not check for order in the UI. 
```diff
```
=> DHFPROD-6158: Curate Tile: Custom Tab should be last tab

marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx
For users with only reader role, replace Close button in the Edit Flow dialog with the enabled Close and disabled Save buttons seen in similar dialogs.
```diff
```
=> DHFPROD-5734: Change Close button to Save/Cancel buttons in Edit Flow

marklogic-data-hub/src/test/java/com/marklogic/hub/entity/EntityManagerTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/marklogic-data-hub-spark-connector/writeRecords/ingestionWithNullParams.sjs
Fix failing tests in 9.0-x server. This PR fixes 3 failing tests in https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/develop/1611/tests/.  
deployExplorerOptionsWithoutContainerConstraint() – com.marklogic.hub.entity.EntityManagerTest test is failing in 9.0-x.
@rjrudin, @akshaysonvane , @ryanjdew ,
It looks like we do not generate entity constraints in 9.0-x server. 
Not sure what should be done here, should the test be excluded in 9.0-x ?
```diff
```
=> DHFPROD-6234:Fix failing tests in 9.0-x server

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataSourceWriter.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/WriteDataWithUriTemplateTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/writeLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/marklogic-data-hub-spark-connector/writeLib/convertPropertyValueToString.sjs
Extracted convertPropertyValueToString so it can be tested as well. 
```diff
```
=> DHFPROD-6184: Enhancing error messages and tests

marklogic-data-hub/build.gradle
Enable logging in dhs installer, client jars
```diff
```
=> DHFPROD-6246:Enable logging in dhs installer, client jars

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/getDocumentForTesting.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/sourcePropertiesLib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/xmlToJsonForMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/lib/mappingService.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getDocumentForTesting/envelopedXmlTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getDocumentForTesting/nonExistentDocTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getDocumentForTesting/startWithJsonTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getDocumentForTesting/startWithXmlTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getDocumentForTesting/test-data/content/sampleCustomerDoc.json, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
This is an extension of DHFPROD-6098, "Create endpoint for fetching source document for mapping UI", and replaces https://github.com/marklogic/marklogic-data-hub/pull/4862, https://github.com/marklogic/marklogic-data-hub/pull/4867, and https://github.com/marklogic/marklogic-data-hub/pull/4871.
It adds the sourceProperties property to the endpoint's return.
Full endpoint path: /api/steps/mapping/{stepName}/testingDoc
```diff
```
=> DHFPROD-6101: Enhance the /api/steps/mapping/{stepName}/testingDoc endpoint to return "sourceProperties"

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/create-edit-mapping-dialog.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/curation/common.data.ts, marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.test.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.module.scss, marklogic-data-hub-central/ui/src/components/steps/steps.test.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.tsx
- Added a "Step Details" link in the create/edit mapping dialog to the source-to-entity mapping UI.
- Added a "Step Settings" link in the source-to-entity mapping UI to the mapping step settings dialog.
- Refactored steps settings to consistently use an isEditing property (instead of isNewStep).
- Removed outdated, unused code for step settings.
Added unit and e2e tests for the new links.
Screencast: https://drive.google.com/file/d/1IA4UeKO14T6vAjN8DUpOPi6Uh4F8-U3q/view
```diff
```
=> DHFPROD-6033: Add Step Details and Step Settings links

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/reader/HubDataSourceReader.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/reader/HubInputPartitionReader.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/Options.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/AbstractSparkReadTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadSimpleCustomersTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadViaSerializedPlanTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadWithCustomSparkSchemaTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadWithSelectedColumnsTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/initializeRead.sjs
Did some test refactoring too to avoid some duplication.
Reorganized initializeRead.sjs into commented functions to make it easier to read.
```diff
```
=> DHFPROD-6245: Can now specify custom Spark schema when reading rows

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.module.scss, marklogic-data-hub-central/ui/src/components/tiles/toolbar.scss, marklogic-data-hub-central/ui/src/components/tiles/toolbar.test.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.tsx
in tiles toolbar:
* added keyboard nagivation via up/down arrow keys
* added a customizable outline to "focused" tile icon
* fixed an issue where tiles link buttons' clickable areas were larger than expected
* fixed a visual issue where tiles icons were slightly off-center
* fixed a visual issue where mouse cursor was set to pointer when icon was disabled
```diff
```
=> DHFPROD-5650: added keyboard controls to tiles toolbar

marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/test/HubConfigObjectFactory.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
Original gradle properties get reset if runAsUser() is called. Once PR #4890 and this gets merged, most of the java tests should pass in DHS. No new tests needed, existing ones should pass.
```diff
```
=> DHFPROD-6290:Original gradle properties get reset if runAsUser() is called

marklogic-data-hub/src/main/resources/ml-modules/root/mlpm_modules/XQuery-XML-Memory-Operations/memory-operations-functional.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/mlpm_modules/XQuery-XML-Memory-Operations/memory-operations.xqy
This came up due to issues we were seeing on ML-9. https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/develop/1659/tests/ 
```diff
```
=> DHFPROD-6293: Use mem:safe-copy

marklogic-data-hub-central/ui/src/components/load/switch-view.scss, marklogic-data-hub-central/ui/src/components/load/switch-view.test.tsx, marklogic-data-hub-central/ui/src/components/load/switch-view.tsx
made radio button group that switches view in Load tile focusable and added outline when focused
```diff
```
=> DHFPROD-5623: added focus to switch view buttons in load tile

marklogic-data-hub/build.gradle
This eliminates a security vulnerability as well, as spring-int was bringing in version 5.1.11 of spring dependencies with vulnerabilities. 
```diff
```
=> DHFPROD-5123: Removed unused spring-integration dependency

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/ExcludeAlreadyProcessedItemsTest.java, marklogic-data-hub/src/test/resources/entity-reference-model/flows/simpleMapping.flow.json, marklogic-data-hub/src/test/resources/test-projects/simple-customer-flow/flows/simpleCustomerFlow.flow.json, marklogic-data-hub/src/test/resources/test-projects/simple-customer-flow/steps/mapping/excludeFalseCustomerMapping.step.json, marklogic-data-hub/src/test/resources/test-projects/simple-customer-flow/steps/mapping/noExcludeCustomerMapping.step.json, marklogic-data-hub/src/test/resources/test-projects/simple-customer-flow/steps/mapping/otherCustomerMapping.step.json, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
processedItemHashes is now only captured if enableExcludeAlreadyProcessed is set to true.
Removed some caching in jobs.sjs that wasn't having any impact, as the functions that were checking the caches were only being called once in a transaction. 
```diff
```
=> DHFPROD-6264: Supporting enableExcludeAlreadyProcessed

marklogic-data-hub/build.gradle
Enable logging in dhs installer, client jars
```diff
```
=> DHFPROD-6333:Enable logging in dhs installer, client jars

marklogic-data-hub-api/src/testFixtures/java/com/marklogic/hub/test/AbstractHubClientTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractHubCentralTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/AbstractSparkConnectorTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/CustomStepE2E.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/ConstrainSourceQueryToJobTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/IngestToFinalTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStepWithProcessorsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/RunFlowWithStemmingEnabledTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
- `runFlow` now does not automatically make input file paths absolute in the flow. Use the `makeInputFilePathsAbsoluteInFlow` method separately for flows. This change was necessary because `makeInputFilePathsAbsoluteInFlow` needs to run as developer user which was causing the flow to always run as developer user.
- Also added logging for user switching.
```diff
```
=> DHFPROD-6338: Fix runFlow

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
Resolving the bug DHFPROD-6200 where the search response page options were not getting reset upon changing the database.
```diff
```
=> DHFPROD-6200: Reset page options when switching between databases

marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.module.scss, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx
Apply same "right" placement as used in other step settings forms. Also update wrapper CSS class name to match component name.
```diff
```
=> DHFPROD-6279: Adjust placement of Match/Merge settings tooltips

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/zip-match/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/zip-match/test-data/content/FiveDigitMatch.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/zip-match/test-data/content/NineDigitMatch.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/zip-match/test-data/content/NoMatch.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/zip-match/test-data/content/NoNineDigitMatch.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/zip-match/test-data/entities/Address.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/zip-match/testZipMatch.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/lib/masteringTestLib.sjs, marklogic-data-hub/src/test/resources/test-config/databases/README.md, marklogic-data-hub/src/test/resources/test-config/databases/final-database.json
Storing the test under data-hub/5/smart-mastering/algorithms/zipMatch, assuming that we can have a variety of narrow tests for each algorithm in an algorithm-specific directory. 
Added a couple wildcard indexes to the test database to verify that nine-digit zip matches work.
```diff
```
=> DHFPROD-6323: Added isolated test for zip matching

marklogic-data-hub-central/ui/e2e/cypress/support/components/common/tiles.tsx
- Follow-up PR to fix persisting ingestion/mapping failures on DHS here: https://jenkins.marklogic.com/blue/organizations/jenkins/DatahubService%2FRun-Tests-dhs/detail/Run-Tests-dhs/497/tests/
- Re-arranging wait statement, as code is trying to close the modal before it is rendered.
- Tests are passing locally
```diff
```
=> DHFPROD-6210: Fix test failures on ingestion/mapping e2e tests

marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/deploy/DeployHubAmpsCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployUserAmpsTest.java
The error happens when there are no amps to deploy, and hubDeploy is run as a data-hub-developer. 
```diff
```
=> DHFPROD-6346: Deploying amps no longer throws unexpected error

marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.scss, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub-central/ui/src/types/curation-types.ts, marklogic-data-hub-central/ui/src/util/priority-order-conversion.tsx
Adding default timestamp handle on multi-slider in merging step detail.
```diff
```
=> DHFPROD-6259: Timestamp should be shown by default in priority order slider

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx
- Added support for remaining step types to Add Step Dropdown in Run Tile: Match, Merge, Master, Custom
- Added e2e test coverage, unit tests already exist 
```diff
```
=> DHFPROD-6357: Add remaining steps to Add Step Dropdown

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/tiles.tsx
- Finally able to reproduce the ingestion/mapping failures on DHS (reverting to Google Chrome 70) 
- Verified this solution resolves the problem.
- No need for wait statements or excessive esc buttons.
```diff
```
=> DHFPROD-6210: Fix for ingestion/mapping e2e failures on DHS

examples/reference-entity-model/build.gradle, examples/reference-entity-model/src/main/ml-config/security/users/common-user.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-common-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-common.json
Moved xdmp:with-namespaces from data-hub-common-writer to data-hub-common
```diff
```
=> DHFPROD-6393: data-hub-common role can now use MLCP

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
Making the default value of the properties "Identifier", "Allow multiple values" & "PII" as "no",  to avoid issues given in the ticket DHFPROD-6268.
```diff
```
=> DHFPROD-6268: Setting default values for Identifier, Multiple and PII properties in property modal

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/ContentObjectSchema.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/Context.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/Metadata.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/Permission.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/Provenance.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/Value.java, specs/models/ContentObject.schema.json
Excluding "previousUri" for now, as that's only used internally. If we want to expose it to users, we will likely use a more meaningful name like "derivedFrom". 
```diff
```
=> DHFPROD-6414: Added JSON schema for Content object

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/provenance/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/provenance/writeProvenanceThrowsError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/teardown.xqy, marklogic-data-hub/src/test/resources/test-config/security/amps/clear-jobs-database.json
Also improved ML unit test plumbing by making "clear-jobs-database" delete provenance data as well, which depends on an amp. 
One other change to flow.sjs is that previously, a bunch of prov data could be generated, but if the granularity level is off, then nothing was done with it. It seems to make more sense that if the level is off, we can bail right away and not generate all that data. 
```diff
```
=> DHFPROD-6412: Fixing syntax error when writing prov data

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/curation/advanced-settings.data.ts, marklogic-data-hub-central/ui/src/assets/mock-data/curation/common.data.ts, marklogic-data-hub-central/ui/src/assets/mock-data/curation/flows.data.ts, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.test.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.tsx, marklogic-data-hub-central/ui/src/config/steps.config.ts
- User can now edit Advanced settings (under Advanced tab) during step creation.
- Advanced tab is disabled until all require fields are filled out under Basic tab.
- Default Collections under Advanced tab are dynamically generated based on the Name value under Basic tab (and also the entity name in the case of mapping steps).
- Most default step values have been moved to a new config/steps.config.ts file.
- Unit and e2e tests now test settings editing under both tabs for new steps.
```diff
```
=> DHFPROD-6260: Enable Advanced Settings during step creation

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/command/UpdateDhsRestExtensionPermissionsTest.java
Do not refresh metadata when fetching transform,resources
```diff
```
=> DHFPROD-6441:Do not refresh metadata when fetching transform,resources

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStepWithProcessorsTest.java
Had to remove the throwing of an exception from stopJob - I couldn't find any reason why that would be good. With it there, the test was failing because 4 failed items were being reported instead of 2. Specifically, a stepItemFailureListener was throwing this exception, after the 2 failed items had already been captured. So it seems unnecessary to throw an exception when stopJob is called but the jobId cannot be found. Also ran all of the flow tests and none of them failed with this change. 
```diff
```
=> DHFPROD-6476: Step processor failure now reports correct job counts

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx
Quick fix to update defaultCollection value when user provides the step name in UI.
```diff
```
=> DHFPROD-6482: Step creation in HC doesn't set the "collections" to step name

marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx
=> DHFPROD-6429: Info icons in Add Strategy modal are not properly aligned in Win4

marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx
- Display modal with message from error object when calling api/flows fails
- Add test of api/flows error case
To test manually:
1. Create a flow and add a step to that flow.
2. Remove that added step via some external manner (e.g., remove the step file in QConsole). 
3. Go to the Run tile. An error modal should be displayed and the browser should no longer go into an infinite flows-retrieving loop.
Note that the resulting page displays no flows whatsoever (since the api/flows endpoint sends back and error and no flows).
```diff
```
=> DHFPROD-6369: Fix error handling in Run when a flow is missing a step

marklogic-data-hub-central/ui/src/assets/mock-data/authorities.testutils.ts, marklogic-data-hub-central/ui/src/config/messages.config.tsx, marklogic-data-hub-central/ui/src/pages/Curate.test.tsx, marklogic-data-hub-central/ui/src/pages/Curate.tsx, marklogic-data-hub-central/ui/src/pages/Load.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/util/authorities.tsx
Note to reviewers: I also took the liberty of adding a missing permissions message to other tiles.  Please also check those pages by directly manipulating the URL (to /tiles/run, etc.).
```diff
```
=> DHFPROD-6427: users with insufficient permission can no longer see curate page

marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/AbstractHubClientTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/RunFlowOnOverFiveThousandItemsTest.java, marklogic-data-hub/src/test/resources/test-projects/simple-custom-step/flows/simpleCustomStepFlow.flow.json, marklogic-data-hub/src/test/resources/test-projects/simple-custom-step/modules/root/custom-modules/custom/simpleCustomStep/simpleCustomStep.sjs, marklogic-data-hub/src/test/resources/test-projects/simple-custom-step/step-definitions/custom/simpleCustomStep/simpleCustomStep.step.json
uris.size() was being called after uris.close(), which resulted in an incorrect count.
Did some cleanup in QueryStepRunner as well - e.g. removing try/catch blocks that weren't doing anything. 
```diff
```
=> DHFPROD-6522: totalEvents is now calculated correctly

marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.test.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.tsx, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.test.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
- Validation for step names and flow names (no special characters besides hyphens and underscores allowed, leading character must be a letter)
```diff
```
=> DHFPROD-6454: Add validation to steps and flow names in Hub Central

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/GenerateIndexesTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateIndexes.sjs
I looked into the history of this change, and I think when it was made for DHFPROD-6215, the intent was good - try to remove indexes that previously existed - but it wasn't being done consistently for path range indexes as well. Nor is removal being done anywhere else - e.g. for protected paths based on PII properties. But we know that an empty array can be a dangerous thing, as that can remove all indexes from a database. And in the context of the entity-config database files, there's no way to know if all indexes should be removed or not. So an empty array is no longer being generated. 
```diff
```
=> DHFPROD-6527: No longer generating empty range-element-index array

marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.tsx
- Console error caused by state setting during component render
- Functionality stays the same, just moved state setting out of component rendering
- No tests needed
```diff
```
=> DHFPROD-6409: Console error when editing a mapping step

marklogic-data-hub-central/ui/src/config/overview.config.ts, marklogic-data-hub-central/ui/src/pages/Overview.module.scss, marklogic-data-hub-central/ui/src/pages/Overview.test.tsx, marklogic-data-hub-central/ui/src/pages/Overview.tsx
Screencast of the link functionality is here: https://drive.google.com/file/d/1GfPNCikMGP1_pdIrv_bKRpqNnWHhySaC/view
URL information is stored in a new `overview.config.ts` file for easy updating by Docs or whomever.
New unit test in Overview.test that checks the links for all five cards.
**Note that none of the link destinations are live yet!** They will become functional prior to the release, see details in the Jira ticket: https://project.marklogic.com/jira/browse/DHFPROD-5000
```diff
```
=> DHFPROD-5000: Add Documentation and Video Tutorial links to Overview

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/util/ModuleWatchingConsumer.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
I tried to get a test in place for this, but I don't know how to test mlWatch in a test (which enters an infinite loop). Instead, I added some logging to at least indicate when there's a misconfiguration -  i.e. the command or context are null. 
The actual bug fix is just to populate generateFunctionMetadataCommand when the other beans are populated in DataHubPlugin. 
```diff
```
=> DHFPROD-6560: mlWatch now generates function metadata

marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadArraysAndMapsTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadWithCustomSparkSchemaTest.java
Run couple of spark connector tests on Linux till server bug 55743 is fixed
```diff
```
=> DHFPROD-6538:Run couple of spark connector tests on Linux till server bug 55743 is fixed

marklogic-data-hub-central/ui/src/pages/Run.module.scss, marklogic-data-hub-central/ui/src/pages/Run.tsx
Just the simple change to update layout of the  confirmation modal. The relevant test scenarios already exist.
```diff
```
=> DHFPROD-6491: Update how Button to Explore looks in success and error modals in all steps

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/collections.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/util.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/collections.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/options.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/matching.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mastering/default/checkOptions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mastering/default/filterMatchingContent.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mastering/default/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mastering/default/test-data/entities/TestTargetEntityCarryOver.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-json/get-options-as-json.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-json/json-options-round-trip.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-json/min-json-options-round-trip.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-json/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-json/suite-teardown.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-json/test-data/custom-sjs-merge-options.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-json/test-data/custom-xqy-merge-options.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-json/test-data/merge-options-complete.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-json/test-data/merge-options-with-array-limit.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-json/test-data/merge-options.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-json/test-data/merge-options.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-json/test-data/path-merge-options.xml, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/ManualMergeUnmergeTaskTest.groovy, ml-data-hub-plugin/src/test/resources/master-test/myNewFlow.flow.json, web/e2e/specs/browse/browse-data.ts
Items Covered:
- The number step definitions increased by 1
- targetEntityType was no longer picked up when the mastering step was run causing the wrong collections to be applied
- The targetTypeEntity not being found hid an issue with blocking future merges. Once the mastering step was fixed, the step wasn't finding the merged record that was archived.
- Using the compiled merge options as a standard way to apply collections caused some merge options related tests to be updated to ensure they call valid functions. This didn't matter before because those tests covered translating between JSON and XML formats.
```diff
```
=> DHFPROD-6492: Fix regression in QuickStart mastering related test

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.test.tsx, marklogic-data-hub-central/ui/src/pages/Load.test.tsx
Original problem: new/edit step dialogs would send a payload on every keystroke.  steps.tsx can't process this very quickly, so there's a lag between user keystroke and when it appears on screen.  This fix replaces the update criteria to when the user shifts focus instead (for ex. user presses Save, or user moves onto the next input).
```diff
```
=> DHFPROD-6511: fixed input textbox lag in new step dialogs

marklogic-data-hub-api/src/main/java/com/marklogic/hub/HubClientConfig.java, marklogic-data-hub-central/src/main/resources/application.properties, marklogic-data-hub-spark-connector/spark-test-project/src/main/java/org/example/ReadCustomersFromFinal.java, marklogic-data-hub-spark-connector/spark-test-project/src/main/java/org/example/StreamingWriteCustomersToStaging.java, marklogic-data-hub-spark-connector/spark-test-project/src/main/java/org/example/WriteCustomersToStaging.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/Util.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/AbstractSparkConnectorTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/HubConfigImplTest.java
Updated the Spark connector to only set hubDhs=true, which means the user only needs to set hubDhs=false instead of both hubDhs/hubSsl. 
```diff
```
=> DHFPROD-6599: hubDhs=true now also enables simple SSL

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/models/CreateAndUpdateModelTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/models/validateModelDefinitions.sjs
Entity model property names should be an NCName
```diff
```
=> DHFPROD-6590:Entity model property names should be an NCName

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/src/components/detail-header/detail-header.tsx
- Follow-up PR to #5186 from comment in QA, capitalizing URI in instance and record view as well.
```diff
```
=> DHFPROD-6591: Entity snippet results use 'uri' instead of 'URI'

marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
Reviews should verify that there are no red console warnings when adjusting sliders in **Step Details** for any **Matching** step.  (Warnings are from React, and will only show up when running UI with `npm start`.)
```diff
```
=> DHFPROD-6541: fixed incompatible children type in multi-slider

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMatchOptionsLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/updateMatchOptions.sjs
Fixing bug in match options conversion noticed by Rob in reviewing PR 5192
```diff
```
=> DHFPROD-6410: Construct HC reduce rules appropriately

Jenkinsfile, build.gradle, marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/auth/SessionMonitorInterceptor.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/impl/CreatedOnFacetHandlerTest.java, marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/EntityManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/conversion/FlowConverter.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/EntityManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/MarkLogicVersionTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/DeployDatabaseFieldCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/conversion/FlowConverterTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/ClearUserModulesTest.java, ml-data-hub-plugin/build.gradle, web/build.gradle, web/src/main/java/com/marklogic/hub/web/service/EntityManagerService.java
Code changes are mostly changing how @Deprecated is used and not using some collections APIs that were added in Java 9 (but are easily replaced). 
Commented out CreatedOnFacetHandlerTest, will figure out how to fix those lines before this is merged. 
```diff
```
=> DHFPROD-6646: Reverting DHF to Java 8

marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx
=> DHFPROD-6632: Advanced tab is enabled in a new step with invalid name field

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addDocumentMetadataToSearchResults.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/recordWithSourcesObject.json
=> DHFPROD-6637: Fix for Explorer UI breaks when record contains source object instead of array

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
Tooltip for source doc should only appear for truncated values
```diff
```
=> DHFPROD-6111:Tooltip for source doc should only appear for truncated values

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.test.tsx
Changes to Advanced Target Collections values in Merge settings should not trigger the Discard Changes alert (since such values are saved independently). Here's the problem: https://drive.google.com/file/d/1BUQj9FRMM_mIji2wGxAqTiahLhYH_GHt/view
Test added in steps-test.
```diff
```
=> DHFPROD-6660: Fix Advanced Target Collections change checking

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubOperatorTest.java
Add "eval-search-string" privilege to Datahub
```diff
```
=> DHFPROD-6668:Add "eval-search-string" privilege to Datahub

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx
This PR fixes the issue where a user was allowed to save without at least one target permission.
```diff
```
=> DHFPROD-6664: Permissions field in advanced tab shows incorrect values after editing

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/auth/AuthenticationFilter.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/auth/AuthTest.java
HC returns "Internal Server Error" when logged in with a user with "data-hub-developer"
```diff
```
=> DHFPROD-6673:HC returns "Internal Server Error" when logged in with a user with "data-hub-developer"

marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/gradle.properties, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java, marklogic-data-hub-central/src/test/resources/sampleData/SalaryTable.csv, marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/conversion/HubCentralConverter.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/conversion/EntityModelConverterTest.java
Was curiously not able to reproduce this in a test. But in manual testing, with Jackson 2.10 used via Spring Boot 2.2.x, ingest of e.g. 1000 rows in a CSV file consistently did not ingest everything (931 rows would be returned). Once Jackson 2.11 is used, the problem goes away. 
```diff
```
=> DHFPROD-5968: Fixing CSV ingest issue via Spring Boot upgrade

Jenkinsfile
Not failing the pipeline in case of npm errors. Looks like cypress is throwing npm error even when all tests passed.
```diff
```
=> DEVO-160: temporary fix to proceed in case of npm error

marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/cloud/Constants.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/cloud/ParameterSource.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/cloud/aws/AWSConfiguration.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/cloud/aws/AWSParameterStore.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/cloud/azure/AzureConfiguration.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/cloud/azure/AzureKeyVaultSecret.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EnvironmentController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/pendo/PendoKeyProvider.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/pendo/PendoKeyProviderTest.java
- Introduced two new properties:
```
hubPendoEnabled = true/false <If true HC will try to retireve the pendo api key>
hubRetrieveCertificate = true/false <if true HC will try to retrieve the certificates keystore and password>
```
- Earlier the certificates keystore and password retrieval was based on just the spring profile but now it depends on `hubRetrieveCertificate` property as we need to support the following service combinations:
1. Services with no certificate and no Pendo
2. Services with a certificate but no Pendo
3. Services with no certificate but with Pendo
4. Services with both certificate and Pendo
- DHS now always needs to apply the appropriate spring profile using `spring.profiles.active=aws/azure` and then can use the `hubPendoEnabled/hubRetrieveCertificate` properties …
=> DHFPROD-6397: Retrieve Pendo key from cloud service

marklogic-data-hub/.gitignore, marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/ApplicationConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/Main.java, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/TestAppInstaller.java, ml-data-hub-plugin/build.gradle, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/BaseTest.groovy
Figured out the build issue; see uberJarClasses in marklogic-data-hub/build.gradle. May want to include this now in 5.4. 
Spring Boot was never needed; Spring is still being used heavily. And Spring Boot is still used by the QS and HC projects. 
```diff
```
=> DHFPROD-4854: Removing Spring Boot dependency from DHF core

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs
This is just to slightly shorten them with "hub-" instead of "data-hub-". 
```diff
```
=> DHFPROD-6965: One more rename of trace events for 5.4.0

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/customStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/loadData.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mapping.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mastering.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/matching.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/merging.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils/invoke-queue-write.sjs, marklogic-data-hub/src/main/resources/ml-modules/services/hubFlowRunner.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/HubFlowRunnerResource.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/IngestAndMapWithConnectedStepsTest.java, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/mappingTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/oneJsonDocWithOptions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/test-data/entities/Customer.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/test-data/flows/ingestAndMap.flow.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/test-data/steps/ingestion/ingestCustomer.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/test-data/steps/mapping/mapCustomer.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/twoJsonDocs.sjs, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
The two key new modules here are flowRunner.sjs and stepExecutionContext.sjs. They'll be changing a lot as more stories are done here. 
Also removed datahub.sjs dependencies from the artifact libraries to "lighten" them up. Their inclusion was causing some circular dependencies. flow.sjs no longer needs to do any gymnastics to use artifacts/core.sjs either. 
Also added installProjectFromUnitTestFolder to the JUnit tests so that an ml-unit-test project can easily be reused in a JUnit test. 
```diff
```
=> DHFPROD-6682: Can run ingest and map steps via connected steps endpoint

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addCustomStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
Adding custom steps to a flow from the Run tile has already been addressed in another ticket.  This PR allows users with sufficient permissions to add custom steps to a flow from the Curate tile.
Tests added account for both features.
Changes to mapping-card.tsx are purely-cosmetic syntax changes.
```diff
```
=> DHFPROD-4996: added option to add step to flow from Curate Tile

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/test-data/content/jsonEntity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/test-data/content/jsonEntityDifferentVersion.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/test-data/content/namespacedEntity.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/test-data/content/namespacedEntityDifferentVersion.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/test-data/content/noNamespaceEntity.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/test-data/entities/TdeContextNamespacedEntity.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/test-data/entities/TdeContextNoNamespaceEntity.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/verifyTdeContext.xqy
The false positives don't affect query results, but they do impact which documents are reindexed.
Extracted fix-tde-context and a few other private functions to start this module on the path towards readability. 
```diff
```
=> DHFPROD-6954: TDE context path now avoids false positives

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
- Refactored the entity table from 'mapping-step-details.tsx' into its own component 'entity-map-table.tsx'
- Added entity type name in first row of entity table, with placeholder entity settings icon + caret
- Visual updates to mapping screen, reviewed by @jbelonoj
1. New icons next to Source Data and Entity Type
2. Divider between source table and entity table is dashed line now
3. Updated color of table header and body
4. Moved Test and Clear buttons into entity container
5. Moved navigation URI buttons to top right of source container
6. Moved source collection and URI info out of question-mark popover and now always visible under Source Data
- Added RTL unit test verifying entity type name and icons in first row of entity table
- Commented out failing entity table filter tests in …
=> DHFPROD-6704: Visual changes to 1:1 mapping configuration screen

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/stepDefinition.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/saveStepDefinition.sjs
The logic for checking on "default-" isn't needed because OOTB DHF step definitions are loaded via /v1/documents, not the artifacts endpoint. 
```diff
```
=> DHFPROD-7009: Fixing bug with saving step definition

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
- Update to https://github.com/marklogic/marklogic-data-hub/pull/5347 for change requested in PM Review
- Reduced width of edit URI textfield so long URI's do not overlap with collapse/expand buttons
- Changed focus of edit URI input so end of URI can be seen in input field.
- No tests for visual updates
```diff
```
=> DHFPROD-6704: Visual Change to 1:1 Mapping

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub-central/ui/src/types/modeling-types.ts, marklogic-data-hub-central/ui/src/util/data-conversion.tsx
This PR allows users to create relationships between entities in the Modeling UI by exposing a Join Property menu in the Add Property dialog when a Related Entity type is selected.
Screencast: https://drive.google.com/file/d/1AzEfoFXTC_lGmbt1pFqzbTf2ix0wZ6Bj/view
Structured type properties and arrays cannot be used as related entity properties currently; I've added tooltip next to the menu explaining this. 
When you save the properties, the following is saved in the entity artifact:
https://project.marklogic.com/jira/browse/DHFPROD-6953?focusedCommentId=196954&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-196954
Notes:
- There is an auto-scrolling bug for new properties with multiple set to yes. This is not specific to the Join Property work and I've …
=> DHFPROD-6953: Add Join Property setting to Add Property dialog

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/reorderSteps.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/FlowService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/flow/updateFlow.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/flow/updateFlow.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/manageFlow.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/updateFlow.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/lib/flowService.sjs
This PR adds the feature of reordering steps. 
- The first step should only show a right arrow. The middle steps show both left and right arrows. The last step should only show a left arrow.
- The steps should persist after reordering.
- There was a change to updateFlowInfo api. It is now called updateFlow and contains an arg for a step array. It still updates the description the same way; that feature was not changed at all. 
```diff
```
=> DHFPROD-5080: Reorder steps in a flow via arrows

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/marklogic-unit-test/hub-test-helper.xqy, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/marklogic-unit-test/hub-test-helper/prepareDatabasesTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/marklogic-unit-test/hub-test-helper/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/marklogic-unit-test/hub-test-helper/test-data/content/aCustomer.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/marklogic-unit-test/hub-test-helper/test-data/entities/Customer.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/marklogic-unit-test/hub-test-helper/test-data/flows/myFlow.flow.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/marklogic-unit-test/hub-test-helper/test-data/step-definitions/custom/myCustomStep/myCustomStep.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/marklogic-unit-test/hub-test-helper/test-data/steps/custom/myCustomStep.step.json
Picked "dhmut" as a prefix - "data hub marklogic unit test". Open to suggestions. 
I realized we can't use this in the DHF tests because this helper needs to retain user artifacts, whereas DHF tests almost always want to delete user artifacts. 
```diff
```
=> DHFPROD-7035: New test module for writing ML tests

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java, specs/models/Batch.schema.json, specs/models/Step.schema.json
Fixes DHFPROD-2445 by adding overridden options to flow object options before writing initial batch report. The initial batch report is included in any intermediate updates.
```diff
```
=> DHFPROD-2445: adjust flow options to include overrides before writing batch report

marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.module.scss, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx
=> DHFPROD-7066: fixed misaligned help icons in new/edit curate step dialog

marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/conversion/FlowConverter.java
Change 'threadCount' to 1 to prevent hang in 9.x servers
```diff
```
=> DHFPROD-7077:Change 'threadCount' to 1 to prevent hang in 9.x servers

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/StepRunnerUtil.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepRunner/processBatch.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/writeQueue.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunFlowThatWritesDuplicateUrisTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/MakeCombinedOptionsTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/ingestAndMapToStaging.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/ingestToFinalMapToStaging.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/ingestionProducesDuplicateUris.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/oneJsonDocWithOptions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/flowStepWithErrorOnWrite.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/provenance/writeProvenanceThrowsError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/test-data/flows/myNewFlow.flow.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/test-data/step-definitions/errorStep.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/test-data/testModuleThrowsError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/flow-utils/makeCombinedOptions.sjs, marklogic-data-hub/src/test/resources/test-projects/simple-custom-step/flows/simpleCustomStepFlow.flow.json, marklogic-data-hub/src/test/resources/test-projects/simple-custom-step/modules/root/custom-modules/custom/simpleCustomStep/simpleCustomStep.sjs
To facilitate testing, I added support for step-specific options as well (really makes testing easier, as you don't have to create as many artifacts). 
Did the following cleanup too:
- Moved the duplicated Java code for combining options into StepRunnerUtil and added tests for it
- Moved the code for combining options in ML into flow-utils and added tests for it
- Created writeQueue.sjs so that flowRunner.sjs and flow.sjs can reuse it
```diff
```
=> DHFPROD-6717: Running connected steps against varying databases

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/writeQueue.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs
Stop using Object.values() as it doesn't work in 9.x server . I don't think it needs test, all existing tests should run fine
```diff
```
=> DHFPROD-7100:Stop using Object.values() as it doesn't work in 9.x server

marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/conversion/FlowConverter.java
Workaround QB hang issue when deleting legacy mappings in FlowConverter
```diff
```
=> DHFPROD-7077:Workaround QB hang issue when deleting legacy mappings in FlowConverter

marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx
This PR adds accessibility for reordering flows. You should be able to:
- Use tab to select a step arrow 
- Use shift tab to select the previously selected arrow
- Press enter to reorder the steps
```diff
```
=> DHFPROD-7045: Accessibility for reorder flows

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/pages/Load.test.tsx, marklogic-data-hub-central/ui/src/pages/Load.tsx, marklogic-data-hub-central/ui/src/types/view-types.ts, marklogic-data-hub-central/ui/src/util/loading-context.tsx, marklogic-data-hub-central/ui/src/util/user-context.tsx
This PR adds sessionStorage for the Load tile. It establishes the data structure and functions that will be used for future session storage stories.
- Persistence on view mode (card/list)
- Persistence on page number
- Persistence on sort order
```diff
```
=> DHFPROD-7043: Establish Session Storage for Retaining Current View in Hub Central

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
- Baseline implementation for filter for related entity types in mapping
- Placeholder values used for related entities until backend or mock data is added in DHFPROD-6706
- UI designs approved by @jbelonoj 
```diff
```
=> DHFPROD-6705: Filter for related entity types in Hub Central

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx
Fixed issues:
* validateEntity persisting as an additional setting for custom steps (should only apply for mapping steps)
* invalid JSON message does not display
```diff
```
=> DHFPROD-7059: patch

ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/GenerateTestSuiteTask.groovy
Couldn't find a way to write a test for this, as it only fails on Java 9+ higher, but we run tests with Java 8. So resorted to using a comment to explain the line change. 
```diff
```
=> DHFPROD-7036: Fix for hubGenerateTestSuite on Java 11

marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadArraysAndMapsTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadWithCustomSparkSchemaTest.java
Enable run of 2 spark connector tests on nightly on all platforms as server bug 55743 is fixed. The test ran fine on 10.0-nightly in my local on mac (it used to result in SEGFAULT earlier) 
```diff
```
=> DHFPROD-6538:Enable run of 2 spark connector tests on nightly on all platforms as server bug 55743 is fixed 

installer-for-dhs/src/main/java/com/marklogic/hub/dhs/installer/command/AbstractVerifyCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/amps/amps-dhf-update-batch.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/core/HubProjectTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/ext/mlunittest/GenerateTestSuiteTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/EnableBatchOutputTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/legacy/job/LegacyJobManagerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java, marklogic-data-hub/src/test/java/com/marklogic/hub_integration/MappingE2E.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/stepExecutionContext/batchOutputIsEnabledTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/ext/marklogic-unit-test/hub-test-helper/prepareDatabasesTest.sjs, marklogic-data-hub/src/test/resources/test-projects/simple-custom-step/modules/root/custom-modules/custom/simpleCustomStep/simpleCustomStep.sjs, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
createBatch/updateBatch are gone; we only have insertBatch now. So no amp needed for updateBatch anymore.
Also fixed an issue in the test plumbing where "getJobDocCount" was actually get legacy job docs, not DHF 5 job docs. 
```diff
```
=> DHFPROD-6525: Can now control whether Batch docs are created

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java
Entity models should not be loaded from subfolders. No test needed, manual tests would suffice.
```diff
```
=> DHFPROD-7015:Entity models should not be loaded from subfolders

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.test.tsx
- Fixed issue where deselecting a related entity table caused that table's filter label to drop to the next table.
- Fixed ordering of tables as related entities are selected (related related entities appear below their respective parents now)
- Added styling fix to table row dividers (approved by @jbelonoj)
- Tests are still going to be added as part of this [task](https://project.marklogic.com/jira/browse/DHFPROD-7155)
- NOTE: there are changes to unrelated files due to linting errors that must have been missed in a previous PR.
```diff
```
=> DHFPROD-7163: Related entity table ordering and deselection issue

marklogic-data-hub/src/main/java/com/marklogic/hub/step/RunStepResponse.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/mlcp-flow-transform.sjs, marklogic-data-hub/src/main/resources/ml-modules/services/mlSmMerge.sjs, marklogic-data-hub/src/main/resources/ml-modules/transforms/mlRunIngest.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/ReturnFullOutputTest.java, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/copyContentObject/copyJsonNodeValue.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/copyContentObject/copyJsonObjectValue.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/copyContentObject/copyXmlValue.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/dontWriteIngestionOrMappingOutput.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/dontWriteIngestionOutput.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/ingestAndMapToStaging.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/test-data/flows/CustomerByValue.flow.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/test-data/step-definitions/CustomerByValue.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/user-parameters/userModuleThrowsError.sjs
Renamed "noWrite" to "writeStepOutput". Also added support for fullOutput to flowRunner.sjs.
Did some cleanup of fullOutput too - it's now a Map<String, JsonNode> in Java. And WriteStepRunner wasn't doing anything with it, so I removed code from there. 
```diff
```
=> DHFPROD-6727: Steps can be configured to not write their output

marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx
Part 1 of PR.
Enabled faceting on structured properties (parents + children).  Changes to facets on structured properties are saved to underlying server.
```diff
```
=> DHFPROD-6223: added facet on structured property (hub central) (part 1)

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/index.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-multiple-modal.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/curation/matching.data.js, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx, marklogic-data-hub-central/ui/src/types/curation-types.ts
Below changes are addressed in this PR.
1. The ruleset with multiple properties can be saved now. The result can be seen on the match scale. Cypress tests added for the same.
2. Most of the validation & Integration tests exists in RTL. More scenarios will definitely be added further as we progress with other stories related to individual match types.
3. Saving the ruleset works for all the match types. However, the e2e test cases, if not done here already, will be added in their respective stories. e2e have been added for Zip and Exact match types.
All UI changes are approved by @jbelonoj.
```diff
```
=> DHFPROD-5231: Validate and Save ruleset for multiple properties form

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/util/data-conversion.tsx
User can now add properties of Related Entity type to structured properties, just as they can to regular, non-structured properties. 
Unit test and E2E test added. 
The data-conversion.tsx update is mostly refactoring to make code more concise (avoid long, repeated prop references).
```diff
```
=> DHFPROD-7027: Allow structured props to be of related type

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateIndexes.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateSearchOptions.sjs
- I am storing the range index path for facetable structured properties in the generated primary entity type in the uber-model as a result we can now generate facets for structured properties with the same name in two different entity types as well.
```diff
```
=> DHFPROD-7115: Generate facets for structured properties

marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx
This PR fixes a bug where flows weren't running from the Load Tile when the Run Tile maintained session storage. A temp fix was pushed so that flows could still be ran from the load tile, but it broke persistence. This PR will allow flow persistence and running flows from the load tile. Please check that HC can now do both. I would really appreciate if reviewers tried to break this, as this is something that would only get harder to fix (if there's a bug) as more code is added to the flows file if it's not fixed ASAP.
* Expected behavior for flow persistence if running from Load Tile:
If a user has flows open, they should persist. However, if a user has flows open, and they run a flow from the Load Tile, all flows will be closed besides the flow they are running. That flow will then …
=> DHFPROD-7181: Flows not running from Load Tile

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/CreateAndUpdateModelTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateModelInfo.sjs
@wooldridge found an issue where PUT request with a payload without namespace/prefix doesn't remove them in an already created entity model. This PR addresses that issue.
```diff
```
=> DHFPROD-7233:Allow users to remove namespace/prefix from an already created entity model

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/src/api/modeling.ts, marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling.js, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx
Allow users to specify a namespace and namespace prefix for non-structured properties in Modeling.
The backend handles the following errors:
- Namespace and prefix must be defined if either one is defined.
- Prefix cannot be a reserved word (e.g., "xml").
- Namespace needs to be an absolute URI (e.g., "http://example.org/test").
- Entity name cannot be a duplicate of existing entity name (this validation already exists).
Server-side errors are displayed in a common place at the bottom of the form. @jbelonoj has approved the UX.
Tests for this feature are handled with RTL unit tests. 
Entity payload is now handled slightly differently now so relevant tests were updated. Also cleaned up entity-type-modal tests to avoid repetition and hardcoding. 
```diff
``` …
=> DHFPROD-3754: Add namespace fields to Entity form

marklogic-data-hub/src/main/resources/hub-internal-artifacts/step-definitions/mapping/marklogic/entity-services-mapping.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/user-parameters/userModuleThrowsError.sjs
This is for user mapping params, and it avoids having to add the new "beforeMain" function. The mapping step main function then iterates over each item. If one throws an error, then it call addStepError and keeps going, unless stopOnError is true. This preserves the existing functionality for a mapping step. 
This is essentially a refactoring, as it doesn't change any tests except a new one, which is now simpler in terms of the error it's checking for. 
```diff
```
=> DHFPROD-4489: Changing mapping step to acceptsBatch=true

marklogic-data-hub-central/ui/src/assets/mock-data/curation/curation-context-mock.js, marklogic-data-hub-central/ui/src/assets/mock-data/curation/mapping.data.ts, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
- Given an existing step that previously had multiple mappings saved, when we reopen it now, all the mapped entities' respective tables should appear by default. And their filters are populated accordingly with which other tables are opened through them, etc.
```diff
```
=> DHFPROD-7273: Open all mapped related entity tables by default

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStepWithCustomHookTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/hooksAndInterceptors/setup.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/hooksAndInterceptors/testHooksAndInterceptors.sjs, marklogic-data-hub/src/test/resources/entity-reference-model/modules/root/custom-modules/custom-hooks/test-hook.sjs
Doing two things here:
- Ensuring that a Batch doc is written when a hook fails
- Passing the output content array when beforeHook is false
The second thing is being done for two reasons - 1) It's what users likely expected, and 2) It's the behavior users were getting for mapping steps, which is what they were most likely attaching custom hooks to for the purpose of modifying URIs. Mapping steps happened to allow this because they were modifying the input content object instead of returning a new one. But now in 5.5, a mapping step can be returning new content objects since it can return multiple content objects for related entities. So changing this both provides the expected behavior for an "after" hook and also ensures that hooks will continue to work as expected for mapping steps. …
=> DHFPROD-7288: Handling custom hook errors for 5.5

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/JobController.java, marklogic-data-hub-central/ui/src/pages/Run.tsx
- Avoids a race condition if the job doc is retrieved before it's written.
```diff
```
=> DHFPROD-7197: Avoid throwing an error if job doc not found

marklogic-data-hub-central/ui/src/assets/mock-data/curation/curation-context-mock.js, marklogic-data-hub-central/ui/src/assets/mock-data/curation/entity-definitions-mock.js, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx
Includes below changes:-
1. Expand All / Collapse All buttons now work within the ruleset form for multiple properties.
2. Fix for the bug DHFPROD-7299. The pagination is implemented in the table to resolve the issue. Details can be found in the JIRA.
All UI changes are reviewed by @jbelonoj.
```diff
```
=> DHFPROD-5233: Expand or Collapse properties in Ruleset form for multiple properties

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/datahub.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/stepDefinition.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStepWithCustomHookTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
Was missing a call to stepExecutionContext.addBatchErrorForEntireBatch . 
Also, for sanity reasons, removed the datahub instance from flow.sjs, as it had almost no value and created a circular dependency. Removed the code that returned the performance metrics, but that's currently disabled anyway in stepDefinition.sjs. If we find we have a need for that at some point, I think we'll integrate it in a different fashion. 
```diff
```
=> DHFPROD-7288: Batch status is now correct when custom hook fails

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/buildAndRunPropertyMappings.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/test-data/steps/mapping/mapCustomersJSON.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/test-data/steps/mapping/mapCustomersWithInvalidExpressions.step.json
Provide error message when mapping uri expression evaluates to null
```diff
```
=> DHFPROD-7306:Provide error message when mapping uri expression evaluates to null

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/finishStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/errorHandling/setup.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/errorHandling/test-data/step-definitions/errorThrowingStep.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/ingestMapMaster/dontCreateJobReportOnError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/ingestMapMaster/ingestMapMatchMerge.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/ingestMapMaster/setup.sjs
This just involves adding the job report to the writeQueue if a writeQueue exists, as opposed to writing the job report right away - need the former for connected steps, the latter for independent steps. 
```diff
```
=> DHFPROD-7325: Not creating job report if later step fails

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/merge-rule-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
Involves following changes.
1. Structured properties support in Add merge Rule form.
2. Fix for the bug DHFPROD-7337, where the ruleset name validation was not working properly. Test cases are added for the same.
UI changes are approved by @jbelonoj.
```diff
```
=> DHFPROD-7269: Select Structured Property in Add Merge Rule Form

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/transforms/mlRunIngest.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java
A no-namespaced "root" element is now included to match what MLCP does. 
```diff
```
=> DHFPROD-6665: DHF file ingestion now matches MLCP for XML from CSV

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx, marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts, marklogic-data-hub-central/ui/src/assets/mock-data/curation/flows.data.ts, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx
Move some testing from E2E to RTL unit tests to stabilize E2E testing and avoid intermittent failures.
@ngodugu-marklogic reviewed the PR draft and OKed it. 
This PR removes the three "add step to flow" instances in the E2E tests (mentioned in the ticket) and adds RTL unit tests that check when a new flow is added (when adding a step), adding the step, and also running the step.
E2E and unit tests pass on my local environment.
```diff
```
=> DHFPROD-7109: Update E2E tests that add step to new flow and run step

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
Updated properties in entities that have not been saved yet will now show up in the Join Property menu in Modeling.
To test:
1. Create a new property for an entity (e.g. Customer). Do not save the entity.
2. Create a new entity relationship that points from one entity (Order) to the entity with the new property (Customer).
3. Open the Join Property menu to confirm that the new property is included in the list of properties. (Previously, it was not.)
```diff
```
=> DHFPROD-7131: Handle entities with updated props when building join menu

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
- Existing related entities that have mappings in the mapping step can now be deleted from the artifact via either the X button on the related entity's table or X button on the related entity's label from the referred entity's filter.
- RTL tests added, will also add more coverage in e2e together once this is started https://project.marklogic.com/jira/browse/DHFPROD-7267
```diff
```
=> DHFPROD-7264: Delete mapping expressions for a related entity

marklogic-data-hub-central/ui/e2e/cypress.json, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addCustomStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/customIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/ingestionForAllFiletypes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/reorderSteps.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
Removing api response wait as it is not polling the response and temporarily disabling defaultIngestionCardView until DHFPROD-7260 is done
```diff
```
=> DHFPROD-7348: Fix E2E tests to wait for success Modal

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/pages/Curate.tsx
- Save mapping artifact in session storage on field change
- Use mapping artifact from session storage if present when viewing mapping UI
To test:
1. Open the details for a mapping step in the Hub Central Curate view.
2. Edit one or more XPath Expression fields, the UI saves these changes on field blur.
3. Go to a different view in Hub Central (Load, Run, Explore...).
4. Return to the Curate view, the details for the previous mapping step will open. 
5. Confirm that the edits made in step 2 are present. (Previously you would see the old values.)
This is a bug fix. Development of tests for updated mapping UI is still in progress, no tests in this PR.
```diff
```
=> DHFPROD-7304: Handle mapping artifact in session storage

examples/reference-entity-model/steps/merging/merge-customers.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/ingestion/default/main.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/HubFlowRunnerResource.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/IngestAndMapWithConnectedStepsTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/twoJsonDocs.sjs
Also ran into an issue where if the "content" object has no "value", an ingestion step throws an unhelpful error message. Fixed that by throwing a nice error message, and cleaned up the ingestion step module too (no longer depends on the datahub singleton). 
Also, while testing against the reference project, I found the fact that documents processed by the merging step were in both "merged-customer" and "merge-customers" to be confusing, since not every customer was being merged. So I removed "merged-customer". 
```diff
```
=> DHFPROD-7355: Fixing stepStartTime in job doc

marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubDeveloperTest.java
A change in ML nightly prevents a different task user being set
```diff
```
=> DHFPROD-7354: Fixing scheduled task test on nightly

marklogic-data-hub-central/ui/e2e/cypress.json, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx
```diff
```
- Fix for flaky run load step issue
- To verify: 
- 1. Create a load step and run it in a new flow via the Load tile (file picker should auto appear). 
- 2. Delete the step from the flow, delete the flow, then return to the Load tile
- 3. Run the load step in a new flow again (file picker should still auto appear, previously did not).
=> DHFPROD-7260: Run load step in new flow sometimes does not run

marklogic-data-hub-central/ui/src/api/mapping.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/curation/common.data.ts, marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-navigation/source-navigation.module.scss
- Add new dropdown menu for inserting reference values into the XPath Expression field in the mapping UI. Works similarly to the property and function menus that are already there.
- Refactor some of the mapping logic and CSS to make it more DRY.
- Fix the function menu bug so that the mapping UI auto-saves after function insertion. (Property and reference insertion also have auto-save.)
- Note that this PR doesn't include description information in the dropdown menu, that feature has been pushed to a separate ticket. This Jira ticket has been updated to note all this.
- Added tests for the reference menu and updated tests for the function menu.
To test, open mapping details for a step and use the new references menu (should appear next to all fields except Context). Selecting should add …
=> DHFPROD-7194: Add reference dropdown to mapping UI

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
Updated mapping menu insertion logic to fix save issues:
- Cannot rely on hook values being avail at time of save. Make sure tempMapExp is saved correctly (for reference and function vals).
- Also set insertedUri (not insertedContext) for URI field case.
To test, check reference (and function) menus when inserting content into URI and regular property fields in mapping UI. 
```diff
```
=> DHFPROD-7194: Fix saving issue for mapping menu values

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/runFlowWithRelatedEntityMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/test-data/steps/mapping/mapCustomersJSON.step.json
Ensure 'additionalCollections' setting works for related entity mapping
```diff
```
=> DHFPROD-7420:Ensure 'additionalCollections' setting works for related entity mapping

examples/reference-entity-model/README.md, examples/reference-entity-model/src/main/ml-modules/root/custom-modules/mapping-params/example-mapping-params.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/user-parameters/test-data/bad-get-parameter-values.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/user-parameters/test-data/user-params.sjs
The problem is that the structure of mappingStep differs based on whether the "Test" GUI button is used or when the mapping step is run. Something to resolve later when we're not about to release. 
```diff
```
=> DHFPROD-7453: Not including mappingStep in getParameterValues

marklogic-data-hub-central/src/main/resources/application.properties, marklogic-data-hub-central/ui/src/config/application.config.js, marklogic-data-hub-central/ui/src/util/user-context.tsx
Still needs extensive testing, but I believe getting away from the setInterval to track the timeout and using a Date instead will provide us with more accurate timing.
```diff
```
=> DHFPROD-7421: Use Date instead of interval for calculating timeout

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
Disable persistence of mapping step details temporarily until persistence for related entities is added. Mapping step persistence e2e test disabled.
```diff
```
=> DHFPROD-7466: Persistence issue in Mapping Step Details

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.module.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-7397: Make it clear custom hooks are deprecated in Hub Central

marklogic-data-hub-junit5/build.gradle
=> DHFPROD-7511: Added pom stuff for marklogic-data-hub-junit5

marklogic-data-hub-central/ui/src/assets/mock-data/curation/merging.data.ts, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
- UI support for ability to set a merge strategy as "default", with error messages if there is already an existing default strategy
- New column in step details that shows which strategy is currently the default one with a check mark
- Functionality: https://drive.google.com/file/d/121e4uv-toQgrLkxLEoVVfYAiJUJJ9U_C/view
```diff
```
=> DHFPROD-7454: Default Merge Strategies in Hub Central

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/index.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling-context-mock.js, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/types/modeling-types.ts, marklogic-data-hub-central/ui/src/util/modeling-context.tsx
We can now open the side panel on graph view by selecting the dummy entity type links in graph view or the new graph view navigation icon in table view.
```diff
```
=> DHFPROD-7434: View entity type from entity model graph view

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/config/mapping.config.js
- Automatic scrolling to the top of the respective table that had pagination applied to it (fixes issues where sometimes tables would be out of sight due to page size changing and scrollbar not following)
- Added dynamic refs library to dynamically create and assign specific refs to scroll to on each table.
- Demo here: https://drive.google.com/file/d/1gQoLP-Cy9FctItmNU6_AlgLmJCpUc6jv/view
- Will create a second PR for 5.5-develop branch once this is merged.
```diff
```
=> DHFPROD-7449: Scroll to respective tables when pagination is applied

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss
- Unified all entity table horizontal scrollbars under one scroll when the page width is shrunk.
- Previously each table had separate horizontal scrollbars within
- Designed reviewed by @jbelonoj 
- Will make secondary PR for 5.5-develop branch once this is merged
- No tests needed for css changes
```diff
```
=> DHFPROD-7450: Take horizontal scrolling out of entity tables

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/mapping-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/incorrectNumberOfArgumentsError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/setup.sjs
Handle wrong number of arguments for "fn:" function error in mapping step
```diff
```
=> DHFPROD-7443:Handle wrong number of arguments for "fn:" function error in mapping step(5.5.1)

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/mapping-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/incorrectNumberOfArgumentsError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/setup.sjs
Handle wrong number of arguments for "fn:" function error in mapping step
```diff
```
=> DHFPROD-7443:Handle wrong number of arguments for "fn:" function error in mapping step

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.module.scss, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/pages/Load.test.tsx
This PR removes the flow icon from load list view and adds a settings icon, making it consistent with table view. The link to settings via the load name was removed. Tests were edited and removed due to changed functionality.
```diff
```
=> DHFPROD-7409: HC UI inconsistent load "settings" access

marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx
=> DHFPROD-6478:Margin size mismatch between Map/Match tab vs Merge tab in Curate tile

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java
I had to update a couple existing tests, which I think in hindsight were erroneously expecting the wrong job status. If stopOnError=true, and the collector fails, then a user expects the flow to be stopped and no other steps to execute, which means the job status should be stop-on-error. 
```diff
```
=> DHFPROD-7570: stopOnError now works when the collector fails

marklogic-data-hub-central/ui/src/components/modeling/graph-view/properties-tab/properties-tab.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/properties-tab/properties-tab.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/properties-tab/properties-tab.tsx
- https://drive.google.com/file/d/1eZL6L0IBE8NbZpahMbrU2tDZy_sZoKiy/view
- When legend is shown, the legend + "Hide Legend <<" text is set to wrap to a new line depending on the width of the side panel, as discussed with Jamie. 
- Design approved by Jamie
```diff
```
=> DHFPROD-7448: Add legend to Properties tab in Graph View

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.module.scss, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.scss, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.scss
This PR removes the multiple scrollbars in Explore. There should be 1 vertical scrollbar on the Explore tile (the scroll is not on the table anymore). When reducing size of the window, a horizontal scrollbar should appear. The search bar stays fixed in line with table view and snippet view, which now has dynamic width. Sticky header was added in this PR. This PR also fixes the placeholder that appears when scrolling in Modeling.
Reviewers: Please check scrolling in other tiles to make sure no other tile was affected.
```diff
```
=> DHFPROD-5878: Stop table scrolling in Explorer

marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java
Using the same DB client to get the count of staging docs, and thus hoping that means the read succeeds as well. 
```diff
```
=> DHFPROD-7630: Attempt to fix E2E flow tests on Windows

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs
No test needed or possible, as verification is done by looking at logging
```diff
```
=> DHFPROD-7668: No longer logging confusing error when metadata is null

CONTRIBUTING.md, examples/dh-5-example/README.md, examples/dhs-example/build.gradle, examples/reference-entity-model/README.md, marklogic-data-hub-spark-connector/spark-test-project/build.gradle, performance-tests/projects/commoncrawl/build.gradle, performance-tests/projects/commoncrawl/gradle/wrapper/gradle-wrapper.properties
Replaced with mavenCentral() where appropriate. Did not modify any of the dhf4 example projects, as those depend on older versions of DHF and ml-gradle whose dependencies only exist in jcenter. 
```diff
```
=> DHFPROD-7695: Removed jcenter references

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.module.scss, marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx
- Added flow status modal upon running multiple steps in a flow in the Run tile
- When a flow has been run, its status modal can be opened via the info icon next to the flow name
- Out of scope: automatic updating of the status modal, so re-visit page to see changes at the moment
- Out of scope: Explore data button on the status modal.
- https://drive.google.com/file/d/1GHPRTM8E88LJP_Lnqw7RwVWhwCb1UXt3/view
```diff
```
=> DHFPROD-7133: Run flows success and error messages

marklogic-data-hub-api/src/main/java/com/marklogic/hub/HubClientConfig.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/models/DocSearchQueryInfo.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/models/SearchQuery.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/models/CalculateSearchCriteriaTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/models/CalculateSearchCriteriaWithSortOrderTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/constraint/entityType.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/constraint/hideHubArtifacts.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy
entityType and hideHubArtifacts are both ML custom constraints now instead of being in Java code, which will allow overriding the behavior of entityType possible via custom search options
Also reworked some tests in EntitySearchManagerTest to be plain JUnit tests, as the logic is now in SearchQuery and DocSearchQueryInfo instead of in EntitySearchManager
```diff
```
=> DHFPROD-7698: Refactored some of Explore into custom constraints

marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle
This fixes an issue where MlcpTask would have required Gradle 6.6 instead of 6.4, which would complicate hubUpdate for DHF 5.6 users that were using MlcpTask
```diff
```
=> DHFPROD-7714: Upgrading ml-gradle from 4.3.1 to 4.3.2

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/main/resources/ml-modules/services/mlDbConfigs.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/customdata/ExploreCustomEntityInstancesTest.java, marklogic-data-hub/src/test/resources/test-projects/custom-data/entities/Person.entity.json, marklogic-data-hub/src/test/resources/test-projects/custom-data/modules/root/custom-data-modules/my-indexes-post-processor.sjs, marklogic-data-hub/src/test/resources/test-projects/custom-data/modules/root/custom-data-modules/my-options-post-processor.xqy
This allows for a project, like TZ, to customize the DHF-generated indexes so that they conform to the project's data format. 
```diff
```
=> DHFPROD-7718: Can now customize how database indexes are built

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-vis.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
Right click menu is available now for entity nodes, with only one option so far, using which user can bring focus on any specific node so that the node is in center of the canvas.
```diff
```
=> DHFPROD-7712: Center the entity type

examples/dhf5-custom-hook/.gitignore, examples/dhs-example/.gitignore, examples/insurance/.gitignore, examples/mapping-example/.gitignore, examples/patient-hub/.gitignore, examples/reference-entity-model/.gitignore, examples/reference-entity-model/src/main/entity-config/databases/final-database.json, examples/reference-entity-model/src/main/entity-config/databases/staging-database.json, examples/smart-mastering-complete/.gitignore, examples/step-interceptors/.gitignore
This ensures that the databases files will be accounted for when mlDeploy is run. Without this, a user must run "mlDeploy hubDeployAsDeveloper", as the latter does generate index files while the former does not. One reason that the former does not is a chicken-and-egg problem - generating the indexes file requires first loading the DHF modules, but the databases/indexes are deployed before DHF modules are loaded. This can be solved, but the easiest solution is just to not gitignore src/main/entity-config/databases. 
```diff
```
=> DHFPROD-7807: Not ignoring entity-config/databases 

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/ExploreCustomEntityInstancesTest.java, marklogic-data-hub-central/src/test/resources/logback.xml, marklogic-data-hub-central/src/test/resources/test-projects/custom-data/modules/root/data-hub/public/extensions/entity/build-entity-query.xqy, marklogic-data-hub-central/src/test/resources/test-projects/custom-data/modules/root/data-hub/public/extensions/entity/post-process-search-options.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/getPrimaryEntityTypes.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/constraint/entityType.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/public/extensions/entity/build-entity-query.xqy
This applies when a project uses a different technique for identifying entity instance documents; getPrimaryEntityTypes.sjs now supports that technique via the build-entity-query.xqy extension point. 
```diff
```
=> DHFPROD-7805: Fixing instance count in modeling tile 

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/ExploreCustomEntityInstancesTest.java, marklogic-data-hub-central/src/test/resources/test-projects/custom-data/entities/Person.entity.json, marklogic-data-hub-central/src/test/resources/test-projects/custom-data/modules/root/data-hub/public/extensions/entity/build-property-path-reference.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getMatchingPropertyValues.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getMinAndMaxPropertyValues.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/public/extensions/entity/build-property-path-reference.sjs
Added build-property-path-reference.sjs extension to allow for a user to override how a cts.pathReference is constructed in case there entity documents do not conform to the ES format. 
```diff
```
=> DHFPROD-7806: Path reference construction can now be overridden

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graph.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx, marklogic-data-hub-central/ui/src/api/modeling.ts, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx, marklogic-data-hub-central/ui/src/config/graph-vis.config.ts, marklogic-data-hub-central/ui/src/pages/Modeling.tsx
Nodes have physics applied initially to determine initial coordinates. 
(Position persistence during and immediately after stabilization may be buggy and can use some review by the team. For example: Select a node during stabilization or immediately after stabilization.)
Clicking and dragging a node updates the coordinates for the node in the local state and in the database (user can leave graph view and return and the position is retained).
Position changes due to panning the entire graph set and zooming are not supported yet and have been described in bug tickets: DHFPROD-7838, DHFPROD-7839
```diff
```
=> DHFPROD-7528: Persist entity node coordinates for graph

marklogic-data-hub-central/ui/e2e/cypress.json, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx
Enabled e2eMasteringflow.spec.tsx test, for now since we are not able to move visjs slider from the test, I am hitting the API directly to add thresholds and rulesets
```diff
```
=> DHFPROD-7906: Enable e2eMasteringflow.spec.tsx test without slider validation

marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.test.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.tsx, marklogic-data-hub-central/ui/src/config/tiles.config.ts, marklogic-data-hub-central/ui/src/pages/Detail.module.scss, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx
The detail view shared the same options as the explore tile view. This caused issues with CSS that was targeting the Explore view to hide contents on the detail page.  This change set addresses this by making a detail view its own TileView.
```diff
```
=> DHFPROD-7947: Making Detail view its own tile

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss
Add z-index CSS to place legend in Mapping Step Details under the Test and Clear buttons. 
```diff
```
=> DHFPROD-8099: Fix legend overlap in Mapping Step Details

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/query/manage-queries-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/edit-query-dialog/edit-query-dialog.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.module.scss, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/discard-changes/discard-changes-modal.test.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/discard-changes/discard-changes-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/edit-query-details.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx
In this pr was changed some Modals that have cancel/no/yes option to have only no/yes options, was centered that 2 buttons to keep the look and feel like others modals with this two options. (Validated with UX)
```diff
```
=> DHFPROD-8004: Query managing replacement

marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
Replaces old `antd` Table component in **Curate / Merging** steps with the new `<HCTable>` component (2 tables).
```diff
```
=> DHFPROD-7753: Merging/merging-step-detail

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/expandable-table-view/expandable-table-view.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
Replaces old `antd` table component in Curate / Matching `<ExpandableTableView>` with the new `<HCTable>` component.
```diff
```
=> DHFPROD-7750: Matching/expandable-table-view

marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/expandable-table-view/expandable-table-view.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
Solves an intermittent failure with the nested data tables to be replaced without `Name` or `Property Name` columns (Explore tables being replaced mostly).
```diff
```
=> DHFPROD-8257: Fix Table headers rendered by default and missing expand icon

marklogic-data-hub-central/ui/src/components/header/header.tsx, marklogic-data-hub-central/ui/src/config/overview.config.ts, marklogic-data-hub-central/ui/src/pages/Overview.test.tsx, marklogic-data-hub-central/ui/src/pages/Overview.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx, marklogic-data-hub-central/ui/src/util/environment.tsx
- Basic refactoring to make documentation links dynamic with the Hub Central version.
```diff
```
=> DHFPROD-8228: Make Hub Central Documentation Links Dynamic

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommandTest.java
=> DHFPROD-8248: Modules loader encodes files paths at wrong moment

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx, marklogic-data-hub-central/ui/src/App.scss
Solves the blank tile/container issue on `develop`.
```diff
```
=> DHFPROD-8332: Every tile is getting rendered blank after navigation from Home

marklogic-data-hub-central/ui/src/components/facet/facet.module.scss
Before:
After:
```diff
```
- [n/a ] Added Release Notes
=> DHFPROD-8370: [Explore] Properties with long names on the sidebar overstep each other

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
Fixed behavior to unify the behavior when adding new properties on entities. Also, adds the same behavior to the entity side panel view on graph that was missing in 5.6.
```diff
```
=> DHFPROD-8325: Table-Structured property must have comprehensive behavior when property is added and delete

marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
Just commenting out the table -view navigation link from the node right click menu temporarily, until it is added after resolving the backend issue.
```diff
```
=> DHFPROD-8236: Hiding table-view navigation link

marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/common/hc-sider/hc-sider.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx
- Added borders to entity colors in Modeling table view and Explore sidebar
- Also fixed the sidebar collapse icon being cut off
- Designs approved by @jbelonoj 
```diff
```
=> DHFPROD-8344: Add Border to all Color Blocks

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/nodeExpand.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs
Adding predicate attribute to the edge of the graph endpoints.
```diff
```
=> DHFPROD-8124: Reveal additional relationships

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json, marklogic-data-hub-central/ui-custom/src/components/Address/Address.test.tsx, marklogic-data-hub-central/ui-custom/src/components/Address/Address.tsx, marklogic-data-hub-central/ui-custom/src/components/Chiclet/Chiclet.tsx, marklogic-data-hub-central/ui-custom/src/components/DataTableMultiValue/DataTableMultiValue.test.tsx, marklogic-data-hub-central/ui-custom/src/components/DataTableMultiValue/DataTableMultiValue.tsx, marklogic-data-hub-central/ui-custom/src/components/DataTableValue/DataTableValue.test.tsx, marklogic-data-hub-central/ui-custom/src/components/DataTableValue/DataTableValue.tsx, marklogic-data-hub-central/ui-custom/src/components/DateTime/DateTime.tsx, marklogic-data-hub-central/ui-custom/src/components/Image/Image.tsx, marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.scss, marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.test.tsx, marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.tsx, marklogic-data-hub-central/ui-custom/src/views/Detail.test.tsx, marklogic-data-hub-central/ui-custom/src/views/Detail.tsx
Pass config info into ResultsList items and the Detail personal section consistently:
- "component" property that specifies the component
- "config" property that specifies the configuration for that component, with consistent properties (arrayPath, path, etc.)
Create an Image widget for thumbnails, etc.
Add a default color to Chiclet widget. Displayed when no color found in widget config.
Fix tests.
=> DHFPROD-8533: Componentize ResultsList and Detail views

examples/entity-viewer-v2/entity-viewer-client/build.gradle, examples/entity-viewer-v2/entity-viewer-client/input/10033.xml, examples/entity-viewer-v2/entity-viewer-client/input/10073.xml, examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json, marklogic-data-hub-central/ui-custom/src/api/api.ts, marklogic-data-hub-central/ui-custom/src/components/List/List.scss, marklogic-data-hub-central/ui-custom/src/components/List/List.test.tsx, marklogic-data-hub-central/ui-custom/src/components/List/List.tsx, marklogic-data-hub-central/ui-custom/src/components/Recent/Recent.scss, marklogic-data-hub-central/ui-custom/src/components/Recent/Recent.test.tsx, marklogic-data-hub-central/ui-custom/src/components/Recent/Recent.tsx, marklogic-data-hub-central/ui-custom/src/components/Relationships/Relationships.tsx, marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.scss, marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.test.tsx, marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.tsx, marklogic-data-hub-central/ui-custom/src/components/Section/Section.scss, marklogic-data-hub-central/ui-custom/src/components/Section/Section.tsx, marklogic-data-hub-central/ui-custom/src/components/Value/Value.tsx, marklogic-data-hub-central/ui-custom/src/store/DetailContext.tsx, marklogic-data-hub-central/ui-custom/src/util/util.tsx, marklogic-data-hub-central/ui-custom/src/views/Dashboard.tsx, marklogic-data-hub-central/ui-custom/src/views/Detail.test.tsx, marklogic-data-hub-central/ui-custom/src/views/Detail.tsx
Update Recent component to pull from dynamic data.
Create List component for Recent and ResultsList components to use for property data display.
Refactor Detail view and Detail context to work with URIs instead of a record ID.
Integrate new getRecord() endpoint call to get a record based on a URI.
Add output_uri_replace value for cleaner, consistent URIs.
Process IDs in Relationships component so that URIs are referenced for links.
Add prepend/append properties for changing data at extraction (vs. prefix/suffix at display).
Update Section widget to take custom styles as config.
```diff
```
=> DHFPROD-8085: Recently Visited Records widget

examples/entity-viewer-v2/entity-viewer-client/input/10035.xml, examples/entity-viewer-v2/entity-viewer-client/input/10062.xml, examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json, marklogic-data-hub-central/ui-custom/src/api/api.ts, marklogic-data-hub-central/ui-custom/src/store/DetailContext.tsx, marklogic-data-hub-central/ui-custom/src/views/Dashboard.tsx, marklogic-data-hub-central/ui-custom/src/views/Detail.tsx, marklogic-data-hub-central/ui-custom/src/views/Header.tsx, marklogic-data-hub-central/ui-custom/src/views/Search.tsx
Add a configurable “local” version of Recently Visited feature.
Make getRecords and getRecent endpoints configurable.
Convert ternaries to AND checks.
Add loading spinners to Detail-related views.
```diff
```
=> DHFPROD-8558: Recently Visited Records widget using local storage

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx, marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.module.scss, marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-8569: Related entity icons still visible in the new entity icons sidebar, for table/snippet views

marklogic-data-hub-central/ui-custom/src/store/SearchContext.tsx
While we reset the pageNumber state on new searches, we aren't resetting the start state. This causes a search error. See the ticket for a description of a test that gives an error.
This fix resets the start state on new searches just as we reset the pageNumber state.
```diff
```
=> DHFPROD-8706: Reset start state on new searches

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json, marklogic-data-hub-central/ui-custom/src/api/api.ts, marklogic-data-hub-central/ui-custom/src/components/RecentSearches/RecentSearches.scss, marklogic-data-hub-central/ui-custom/src/components/RecentSearches/RecentSearches.tsx, marklogic-data-hub-central/ui-custom/src/components/SearchBox/SearchBox.tsx, marklogic-data-hub-central/ui-custom/src/components/SelectedFacets/SelectedFacets.tsx, marklogic-data-hub-central/ui-custom/src/store/SearchContext.tsx, marklogic-data-hub-central/ui-custom/src/views/Detail.tsx, marklogic-data-hub-central/ui-custom/src/views/Search.tsx
Search queries added as query param in browser address bar.
User can execute search by copying/pasting browser URL.
User can execute search by copying via Recent Searches widget and pasting.
Refactored search logic across components to support.
Fixed entity menu updates in SearchBox widget.
To test:
- Check that encoded search string is kept as query param in browser address bar when searches are executed.
- Copy the browser URL and use that in separate browser window and confirm that search is correct with no errors.
- Click the "Copy & Share" icon for a saved search on the Dashboard and use that in separate browser window and confirm that search is correct with no errors 
- Confirm that search information appears OK in Saved Searched. It now includes the entity selection (e.g., [person] …
=> DHFPROD-8570: Handle saved searches

marklogic-data-hub-central/ui/src/components/entities/entity-tiles.test.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.tsx, marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx, marklogic-data-hub-central/ui/src/pages/Curate.test.tsx
Includes the following:
- DHFPROD-8767: In Hub Central, displaying incorrect error message in the "Add Property" modal
- DHFPROD-8670: Change step name format in Hub Central
- DHFPROD-8711: Remove Query Settings from Monitoring Tile
```diff
```
=> DHFPROD-8767: Add Property Modal Messaging

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json
We now use a non-search endpoint (in the example app, /api/explore/getRecord) to retrieve a single record for the Detail view.
We don't need the additional config settings to constrain the results to get a single record.
```diff
```
=> DHFPROD-8857: Remove unneeded config values for Detail

marklogic-data-hub-central/ui-custom/src/store/SearchContext.tsx
This fixes the error where a single search result is not displayed in the UI, since the result value is not stored in an array in the result response.
```diff
```
=> DHFPROD-8867: Ensure search response result value is an array

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json, marklogic-data-hub-central/ui-custom/src/components/Relationships/Relationships.test.tsx, marklogic-data-hub-central/ui-custom/src/components/Relationships/Relationships.tsx
Screencast: https://watch.screencastify.com/v/ok6HhcTL8j617D0rEPEG
With this update, users can now use text-based graph nodes in the Relationships widget. In config.json, they set the "type" property to "text" (or to "image" if they want image-based) and add "label" properties to map the text they want on the nodes.
FYI: We currently do not have unit tests for the Relationships widget, these will come later as there are canvas-related errors (Hub Central dev's have experienced similar, per @xnikhil08). Ticket for this: https://project.marklogic.com/jira/browse/DHFPROD-8874
```diff
```
=> DHFPROD-8871: Support text-based nodes in Relationships

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/detail.config.sjs, marklogic-data-hub-central/ui-custom/src/components/Relationships/Relationships.scss, marklogic-data-hub-central/ui-custom/src/components/Relationships/Relationships.tsx
Make it configurable with any properties with label/value pairs, similar to Timeline popover.
```
"popover": {
"items": [
{
"label": "Name",
"path": "person.nameGroup.fullname.value"
},
{
"label": "City",
"arrayPath": "person.addresses.address",
"path": "city"
},
{
"label": "State",
"arrayPath": "person.addresses.address",
"path": "state"
}
]
}
```
```diff
```
=> DHFPROD-8831: Refactor Relationships popover tooltip

marklogic-data-hub-central/ui-custom/src/components/Timeline/Timeline.tsx
Refactor to use regular variables for minTime and maxTime since state variable changes cause a component refresh. See notes in Jira ticket:
https://project.marklogic.com/jira/browse/DHFPROD-8896
```diff
```
=> DHFPROD-8896: Avoid excessive state variable updates in Timeline

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/detail.config.sjs, marklogic-data-hub-central/ui-custom/src/components/DataTableValue/DataTableValue.test.tsx, marklogic-data-hub-central/ui-custom/src/components/DataTableValue/DataTableValue.tsx
Handle the case where the original data looks like this:
```
<phone>917-910-6575</phone>
<phone>917-910-6576</phone>
```
The JSON results look like this:
```
['917-910-6575', '917-910-6576']
```
(No metadata.)
And the DataTableValue config looks like this:
```
"config": {
"id": "phone",
"title": "Phone Number",
"arrayPath": "person.phone",
"icon": "phone",
"width": "400px",
```
(In this case, value property is not needed because no metadata and we want to show the two strings.)
This case is tested here: https://github.com/wooldridge/marklogic-data-hub/blob/DHFPROD-8894/marklogic-data-hub-central/ui-custom/src/components/DataTableValue/DataTableValue.test.tsx#L53
```diff
```
=> DHFPROD-8894: Handle simple arrays in DataTableValue

marklogic-data-hub-central/gradle.properties, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/auth/AuthenticationFilter.java, marklogic-data-hub-central/ui/package-lock.json
There are two things to test on this branch
1. The Hubcentral build and
2. The EntityViewer build
Testing HubCentral build:
1. Run ./gradlew clean build -x test to build hub central war file
2. Clean you ML database and deploy reference-entity-model project
3. Run the war file created in the marklogic-data-hub-central/build/libs directory
4. The application should start up without any issues and should be able to use all the features of HC
Testing EntityViewer build:
1. Run ./gradlew clean build -x test -Pwar.archiveName=marklogic-entity-viewer -Pversion=rc-1 -PreactUiPath=./ui-custom to build entity-viewer war file
2. Clean you ML database and deploy entity-viewer-v2/entity-viewer-client project
3. Run the war file created in the marklogic-data-hub-central/build/libs directory
4. The …
=> DHFPROD-8846: Install Entity Viewer modules only on EntityViewer build

marklogic-data-hub-central/ui-custom/src/App.tsx, marklogic-data-hub-central/ui-custom/src/api/api.ts, marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.test.tsx, marklogic-data-hub-central/ui-custom/src/components/SearchBox/SearchBox.test.tsx, marklogic-data-hub-central/ui-custom/src/setupProxy.js, marklogic-data-hub-central/ui-custom/src/store/DetailContext.tsx, marklogic-data-hub-central/ui-custom/src/store/UserContext.tsx
Our app init strategy offers a CORS workaround (setupProxy.js) for the DEVELOPMENT environment (port 3000).
In PRODUCTION (port 8080), the loginAddress server will need to handle CORS issues if that server differs from the server that serves the React app. If the loginAddress in properties is on the same server as the app (e.g., http://localhost:8080/api/explore/login) then PRODUCTION will work without any CORS handling.
To test:
1. Development (3000). When loginAddress property in properties file is mock server at http://localhost:8888/api/explore/login, correct userid will be set. Change that value to something else (e.g., http://www.google.com) and the userid will be incorrect, but the initial auth should still work since we're not checking validity of userid value.
2. Production …
=> DHFPROD-8931: Fix proxying behavior for getting loginAddress

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
=> DHFPROD-8981: GraphSearch doesn't show the ellipsis on concepts properly

marklogic-data-hub-central/src/main/resources/explore-data/ui-config/search.config.sjs, marklogic-data-hub-central/ui-custom/src/components/Facets/Facets.tsx
Add Collection facet config to OOTB search.config.sjs.
NOTE: @rahulvudutala needs to finish a subtask before we merge this: https://project.marklogic.com/jira/browse/DHFPROD-9043
When following the instructions here to get an OOTB env working (with sample records):
https://wiki.marklogic.com/display/ENGINEERING/Entity+Viewer%3A+Set+up+minimal+UI+with+v1.0.0
I can see the Collection facet appear in the UI:
```diff
```
- ##### Owner:
=> DHFPROD-9018: Display collections facet OOTB

marklogic-data-hub-central/ui-custom/src/components/RecordRaw/RecordRaw.tsx, marklogic-data-hub-central/ui-custom/src/components/ResultSnippet/ResultSnippet.scss, marklogic-data-hub-central/ui-custom/src/components/ResultSnippet/ResultSnippet.test.tsx, marklogic-data-hub-central/ui-custom/src/components/ResultSnippet/ResultSnippet.tsx, marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.scss, marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.test.tsx, marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.tsx
Creates a new ResultSnippet widget for displaying match snippet content from results payload OOTB. Can configure highlight color, font weight for match text, and separator for multiple matches. Minimal OOTB search results now look like the following (default match style is bold/light yellow with " ... " separator):
```diff
```
- ##### Owner:
=> DHFPROD-9015: Add highlighting to match snippets

marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
Redundant Expand/Collapse Mapping Step curate table
```diff
```
- ##### Owner:
=> DHFPROD-9003: RedundantExpandCollapseMappingStep

examples/entity-viewer-baseball/src/main/ml-modules/root/explore-data/ui-config/search.config.sjs, examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/search.config.sjs, marklogic-data-hub-central/ui-custom/src/components/Facets/Facets.test.tsx, marklogic-data-hub-central/ui-custom/src/components/Facets/Facets.tsx, marklogic-data-hub-central/ui-custom/src/components/SelectedFacets/SelectedFacets.tsx, marklogic-data-hub-central/ui-custom/src/store/SearchContext.tsx, marklogic-data-hub-central/ui-custom/src/views/Search.test.tsx
Update the facet type called "category" to be called "string" per customer's request.
```diff
```
- ##### Owner:
=> DHFPROD-9079: Change 'category' type in facet configuration to 'string'

marklogic-data-hub-central/ui-custom/src/components/Chiclet/Chiclet.tsx, marklogic-data-hub-central/ui-custom/src/components/DateTime/DateTime.tsx, marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.scss
Add ellipses (via CSS) and title attribute.
Make timestamp and chiclet content consistent (by adding titles).
```diff
```
- ##### Owner:
=> DHFPROD-9057: Handle long status values in ResultsList

marklogic-data-hub-central/ui/src/components/tiles/toolbar.module.scss, marklogic-data-hub-central/ui/src/components/tiles/toolbar.scss, marklogic-data-hub-central/ui/src/components/tiles/toolbar.test.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.tsx, marklogic-data-hub-central/ui/src/config/tiles.config.ts, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx, marklogic-data-hub-central/ui/src/theme/HCVariables.scss
DHFPROD-5486: Indicate open tiles by icon state
```diff
```
- ##### Owner:
=> DHFPROD-5486: Indicate open tiles by icon state

marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx
DHFPROD-9001-e2eVerfTilesNoDataIsLost
```diff
```
- ##### Owner:
=> DHFPROD-9001: Verify that no unsaved data is lost when switching tiles

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/entityMappingMoreLessFunctionality.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.tsx
Edit mapping step settings are not showing collection when editing the new mapping step.
```diff
```
- ##### Owner:
=> DHFPROD-9094: EditMappingStepSettingsShowsNoCollection

marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/pages/Curate.tsx
Page error on curate tile when we add concepts in the model page.
```diff
```
- ##### Owner:
=> DHFPROD-9129: PageErrorOnCurateTile

examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/dashboard.config.sjs, examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/detail.config.sjs, examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/search.config.sjs, marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/landing.tsx, marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/recordDetails.tsx, marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/search.tsx, marklogic-data-hub-central/ui-custom/src/components/Concat/Concat.scss, marklogic-data-hub-central/ui-custom/src/components/Concat/Concat.test.tsx, marklogic-data-hub-central/ui-custom/src/components/Concat/Concat.tsx, marklogic-data-hub-central/ui-custom/src/components/DateTime/DateTime.tsx, marklogic-data-hub-central/ui-custom/src/components/ImageGallery/ImageGallery.tsx, marklogic-data-hub-central/ui-custom/src/components/ImageGalleryMulti/ImageGalleryMulti.tsx, marklogic-data-hub-central/ui-custom/src/components/List/List.tsx, marklogic-data-hub-central/ui-custom/src/components/Occupations/Occupations.tsx, marklogic-data-hub-central/ui-custom/src/components/RecentRecords/RecentRecords.test.tsx, marklogic-data-hub-central/ui-custom/src/components/RecentRecords/RecentRecords.tsx, marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.scss, marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.test.tsx, marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.tsx, marklogic-data-hub-central/ui-custom/src/components/SummaryMeter/SummaryMeter.scss, marklogic-data-hub-central/ui-custom/src/components/Timeline/Timeline.tsx, marklogic-data-hub-central/ui-custom/src/components/Value/Value.tsx, marklogic-data-hub-central/ui-custom/src/util/util.tsx, marklogic-data-hub-central/ui-custom/src/views/Detail.test.tsx, marklogic-data-hub-central/ui-custom/src/views/Detail.tsx
Added a new Concat widget for displaying concatenated elements from the payload. 
Also refactored title configuration on search results, detail page, and recently viewed (which is where users specifically wanted to use the Concat widget).
Example configuration (concatenate given name and surname for search titles) is here: https://github.com/wooldridge/marklogic-data-hub/blob/DHFPROD-9039/examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/search.config.sjs#L102
Content between concatenated elements can be added with "prefix" and "suffix" properties (which are already in our configuration patterns).
Concat supports regular values and also a "type" of "DateTime" which works similar to the "DateTime" widget. (See the unit tests for an example).
Tests pass, detailed …
=> DHFPROD-9039: New Concat widget, title reconfig

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeNotification.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/unMerge.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/OneToOneNotes, marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/temp/Customer.entity.json, marklogic-data-hub-central/ui/src/assets/mock-data/explore/entity-search.js, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.module.scss, marklogic-data-hub-central/ui/src/components/record-view/record-view.test.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs
- Added merge icon setup for merge notifications in Explore (only in All Data Card view)
- Includes @AkshayBajajML 's backend changes
- Reference:
```diff
```
- ##### Owner:
=> DHFPROD-9135: Merge documents modal icons

examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/dashboard.config.sjs, examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/search.config.sjs, marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/search.tsx, marklogic-data-hub-central/ui-custom/package.json, marklogic-data-hub-central/ui-custom/src/components/ImageGallery/ImageGallery.tsx, marklogic-data-hub-central/ui-custom/src/components/ImageGalleryMulti/ImageGalleryMulti.tsx, marklogic-data-hub-central/ui-custom/src/components/LinkList/LinkList.tsx, marklogic-data-hub-central/ui-custom/src/components/Membership/Membership.tsx, marklogic-data-hub-central/ui-custom/src/components/MetadataValue/MetadataValue.tsx, marklogic-data-hub-central/ui-custom/src/components/Metrics/Metric.tsx, marklogic-data-hub-central/ui-custom/src/components/Pagination/Pagination.tsx, marklogic-data-hub-central/ui-custom/src/components/Relationships/Relationships.tsx, marklogic-data-hub-central/ui-custom/src/components/ResultActions/ResultActions.tsx, marklogic-data-hub-central/ui-custom/src/components/SocialMedia/SocialMedia.tsx, marklogic-data-hub-central/ui-custom/src/components/SummaryMeter/SummaryMeter.scss, marklogic-data-hub-central/ui-custom/src/components/SummaryMeter/SummaryMeter.tsx, marklogic-data-hub-central/ui-custom/src/components/Timeline/Timeline.tsx, marklogic-data-hub-central/ui-custom/src/components/WhatsNew/WhatsNew.tsx, marklogic-data-hub-central/ui-custom/src/store/MetricsContext.tsx, marklogic-data-hub-central/ui-custom/src/store/SearchContext.tsx, marklogic-data-hub-central/ui-custom/src/util/util.test.tsx, marklogic-data-hub-central/ui-custom/src/util/util.tsx, marklogic-data-hub-central/ui-custom/src/views/Dashboard.tsx, marklogic-data-hub-central/ui-custom/src/views/Search.test.tsx
Use the jsonpath-plus library.
Create alternative functions in util.tsx.
Add tests to util functions.
There are places in the configuration where I've updated the paths to use JSONPath notation:
- https://github.com/wooldridge/marklogic-data-hub/blob/DHFPROD-9110/examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/search.config.sjs#L91
- https://github.com/wooldridge/marklogic-data-hub/blob/DHFPROD-9110/examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/search.config.sjs#L139
- https://github.com/wooldridge/marklogic-data-hub/blob/DHFPROD-9110/examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/search.config.sjs#L156
- https://github.com/wooldridge/marklogic-data-hub/blob/DHFPROD-9110/examples/entity-viewer/src/main/ml-modules/root/ …
=> DHFPROD-9110: Use JSONPath expressions for config paths

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/merger.sjs
=> DHFPROD-9419: Notifications should not be generated when only one URI

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/curation/flows.data.ts, marklogic-data-hub-central/ui/src/components/flows/confirmation-modals.tsx, marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx, marklogic-data-hub-central/ui/src/components/flows/flow-panel/step-card.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flow-panel/step-card.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/flows/types.ts, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx, marklogic-data-hub-central/ui/src/types/run-types.ts
- DHFPROD-9465: Run Flows After Step Change 
- DHFPROD-9457: Flow Menu Select/Deselect All 
- DHFPROD-9508:  Run Flow Refactor: Clean up Flows component
- Load by default of checkboxes (1 load type only checked at the same time in the flow, the rest, all checked).
```diff
```
- ##### Owner:
=> DHFPROD-9465: Run Flows After Step Change

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
This PR include a fix for DHFPROD-9540
```diff
```
- ##### Owner:
=> DHFPROD-9543: BE - Group nodes are displaying incorrectly

Jenkinsfile
=> DHFPROD-9678: Fix nightly cypress jenkins build failure

.github/PULL_REQUEST_TEMPLATE.md, Jenkinsfile, marklogic-data-hub-central/build.gradle
This PR changes the place where the linting process is done.
Now the linting is done in the build task so we removed it from the pipeline.
```diff
```
- ##### Owner:
=> DHFPROD-9701: Moving linting step on pipeline

marklogic-data-hub-central/ui/src/components/common/switch-view/view-switch.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/components/entities/page-header/page-header.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub-central/ui/src/theme/HCTheme.scss
=> DHFPROD-5624: Load + Curate: Keyboard navigation within Cards

installer-for-dhs/build.gradle, marklogic-data-hub-api/build.gradle, marklogic-data-hub-client-jar/build.gradle, marklogic-data-hub-junit5/build.gradle, marklogic-data-hub-test/build.gradle, marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle
None of these should have any functional impact, they're mostly intended to minimize security vulnerabilities and promote consistency across dependencies. 
Note that mlcp-util was moved to testImplementation as `MlcpRunner` is only used for testing.
=> DHFPROD-9882: Updating dependencies

marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx
The stop Flow Button Disappears After One Second.
```diff
```
- ##### Owner:
=> DHFPROD-9848: Stop Flow Button Disappears After One Second

marklogic-data-hub-central/ui/src/components/tiles/toolbar.module.scss, marklogic-data-hub-central/ui/src/theme/HCVariables.scss
Main Side Panel Tiles Icons Are Not Highlighted
```diff
```
- ##### Owner:
=> DHFPROD-9844: Main Side Panel Tiles Icons Highlighted

marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addDocumentMetadataToSearchResults.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/jane.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/jane.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/sally.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/sally.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/entities/Customer.entity.json
- Testing would require changes to our existing project to accommodate boolean values. Created a testing [ticket](https://project.marklogic.com/jira/browse/DHFPROD-9918) for that and added this to the manual testing wiki in the meantime.
```diff
```
- ##### Owner:
=> DHFPROD-9878: Boolean Property Results Missing in Explore Table

marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx
Curate Card Footers Are Cut Off
```diff
```
- ##### Owner:
=> DHFPROD-9939: Curate Card Footers Are Cut Off

marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
- This is an edge case only in the graph view where the child of a structured property is configured in a relationship.
- Test scenario added to manual wiki: https://wiki.marklogic.com/display/ENGINEERING/Manual+Testing+Scenarios
```diff
```
- ##### Owner:
=> DHFPROD-9960: Structured Property Relationships cannot be edited

marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/graphValidations.cy.tsx, marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenario1.cy.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-table.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/modeling/concept-class-modal/concept-class-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
Adds `Add Entity Property` button under properties table.
```diff
```
- ##### Owner:
=> DHFPROD-9644: Add a second "Add Property" button in DHC/Model screen

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-target-collections.tsx
Add Validations To Typeahead Component
```diff
```
- ##### Owner:
=> DHFPROD-9743: Add Validations To Typeahead Component

Jenkinsfile
=> DHFPROD-10051: Increase time out rh7_cluster_10.0-7 on 5.8 pipeline

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.mjs
- **PROBLEM**: When two merged documents are connected by a relationship, the unmerge option is visible on one merged node but not the other.
- **FINDINGS**: While building out the nodes for the graph results, the first merged document being traversed enters the proper functions to retrieve unmerge details, but in the same pass later builds a node for the related merged document which skips the proper channels.
- **Option One**: When the first merged document is being traversed and attempts to also build a node for the other merged document in the same pass, choose to opt out so the other merged document can be properly traversed on its own later.
- **Option Two**: Add the "fetch unmerge details" that was missing where the other node was later being built in the same pass.
- I went with …
=> DHFPROD-10061: Unmerge option is not getting displayed for all nodes

marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenarioGraph.cy.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
Adds cypress test scenario to `writerScenarioGraph.cy.tsx` and fixes identing issues.
```diff
```
- ##### Owner:
=> DHFPROD-9998: Validate Structured Property Relationships Can Be Edited

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/run/runFlow.cy.tsx, marklogic-data-hub-central/ui/e2e/cypress/e2e/mastering/e2eMasteringflow.cy.tsx, marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/graphValidations.cy.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx
This is the second iteration to solve failures in nightly chrome
```diff
```
- ##### Owner:
=> DHFPROD-10240: check e2e win-chrome failures in the latest chrome version iteration 2

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/run/runFlow.cy.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
This PR fixes 
on nightly 
```diff
```
- ##### Owner:
=> DHFPROD-10240: check e2e win-chrome failures in the latest chrome version

marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx, marklogic-data-hub-central/ui/src/components/table-view/table-view.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/common.mjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.mjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/merger.mjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/core/models/entityModel.mjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/nullNodeMatch.mjs
Also handles JSON null properties in the new JavaScript code and no longer applies the archived collection to merged documents that are merged multiple times.
```diff
```
- ##### Owner:
=> DHFPROD-10368: Unmerge nodes that aren't part of core search results

examples/real-estate/dataset/thesaurus/thesaurus2.xml
The underlying issue causing this error, as well as another one we have identified, is tied to the real estate project's data. Specifically, the file used to configure synonyms in this instance should contain values in lowercase.
```diff
```
- ##### Owner:
=> DHFPROD-10434: BE:Matching synonyms not working
