marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/impl/CreatedOnFacetHandler.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/impl/CreatedOnFacetHandlerTest.java, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.xml.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.test.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar-rtl.test.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
=> DHFPROD-4786: Facet by time window based on when an entity instance was created

marklogic-data-hub-central/ui/src/components/load/load-card.module.scss, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/config/formats.config.js
This PR just fixes small bugs in the load cards.
No tests are required here.
```diff
```
=> DHFPROD-4723: Fixing the source format labels in the load cards

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/MappingControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/MappingMvcTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.hub/config.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs, marklogic-data-hub/src/main/resources/ml-modules/transforms/mlGenerateFunctionMetadata.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/GenerateFunctionMetadataCommandTest.java
=> DHFPROD-5146: Ensure hub-central roles can read custom mapping functions

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/resources/test-projects/all-artifacts/mappings/LegacyMapping/LegacyMapping.mapping.json, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/ClearUserDataTask.groovy
The ClearUserDataTest was effectively updated by adding a legacy mapping to the project, which caused the test to fail until DataHubImpl was modified.
```diff
```
=> DHFPROD-5063: Enhancements to clearing user data

Jenkinsfile
```diff
```
- [ N/A] Squashed all commits into a single commit
=> DHFPROD-5172: Abort pipeline if Changes Requested

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowMigrator.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowMigratorTest.java
=> DHFPROD-5192: All ingestion steps are now migrated

marklogic-data-hub-central/ui/src/components/query-export/query-export.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.module.scss, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-results/search-results.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-5024: Browse view in tiles needs CSS fixes

marklogic-data-hub/src/main/resources/ml-modules/services/mlSmMerge.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java
=> DHFPROD-5160: Return the correct document to preview a merge

marklogic-data-hub-central/ui/src/assets/mock-data/common.data.ts, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.test.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.tsx, marklogic-data-hub-central/ui/src/pages/Curate.test.tsx, marklogic-data-hub-central/ui/src/pages/Load.test.tsx
Label updates in mapping and load UI views. No new views or functionality. Existing tests updated.
```diff
```
=> DHFPROD-4497: Update Mapping/Load UI labels

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/matching.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mastering/default/filterMatchingContent.sjs
=> DHFPROD-5157: Don't process audit and notification docs through match

marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/HubCentralManager.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/ApplyDownloadedZipToProjectTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
=> DHFPROD-4857: hubApply fails immediately if file is not found

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/models/SearchQuery.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/transforms/hubEntitySearchTransform.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs
=> DHFPROD-5177: Changes to EntitySearch API to accept propertiesToDisplay for tabular view

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/StepSchema.java, marklogic-data-hub-central/ui/src/assets/mock-data/advanced-settings.data.ts, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub/src/main/resources/hub-internal-artifacts/step-definitions/mapping/marklogic/entity-services-mapping.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mapping.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/entity-validation-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/shouldValidateEntity.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/convertMappingStep.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/manageMappingStep.sjs, specs/models/Step.schema.json
=> DHFPROD-4970: add validate entity field to mapping step

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/JobsController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java, marklogic-data-hub-central/ui/e2e/cypress/integration/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/view-entities.validation.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/projectInfo.tsx, marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/assets/mock-data/flows.data.ts, marklogic-data-hub-central/ui/src/assets/mock-data/search-context-mock.js, marklogic-data-hub-central/ui/src/components/queries/saving/discard-changes/discard-changes-modal.test.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Run.module.scss, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.scss, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/step/RunStepResponse.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/Step.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs
- This PR has both backend and FE changes hence the two commits
- Fixed integration tests which were failing on develop previously
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/develop/1046/tests 
```diff
```
=> DHFPROD-4421:After mapping step is run, I should be able to easily view my results in Explorer

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-odbc-user.json, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubOdbcUserTest.java
=> DHFPROD-5208: Added data-hub-odbc-user

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/janeAddress.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/sallyAddress.json
=> DHFPROD-5204: BackEnd - Add primary Key value field in the searchAPI results response

marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.tsx
Remove a lot of unused code from load artifact create/edit page. Works fine with my local tests. No tests needed.
```diff
```
=> DHFPROD-5268:Remove unused code from load artifact create/edit page

marklogic-data-hub-central/ui/src/components/column-selector/column-selector.test.tsx, marklogic-data-hub-central/ui/src/components/column-selector/column-selector.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-5148: Ability to show multiple values in a table view for a property.

marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.tsx
Fix css for custom card. No tests needed
```diff
```
=> DHFPROD-4998:Fix css for custom card

marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.test.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.tsx
=> DHFPROD-4879:Reset to no query

marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.modeling.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/confirmation-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/types/modeling-types.ts, marklogic-data-hub-central/ui/src/api/modeling.ts, marklogic-data-hub-central/ui/src/assets/mock-data/modeling.js, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.module.scss, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.test.tsx, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/types/modeling-types.ts, marklogic-data-hub-central/ui/src/util/modeling-context.tsx
Includes typo fix for DHFPROD-5275
```diff
```
=> DHFPROD-4180: Delete Entity Type

marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/EntitySearchControllerTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/ReferenceModelProject.java
=> DHFPROD-5114: Fixing 500 Error for XML Documents on clicking Details Link

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
Ensure source doc is displayed fine and editing doc URI works. @bsrikan's e2e suite will be updated, no unit tests 
```diff
```
=> DHFPROD-5151:Ensure source doc is displayed fine and editing doc URI works

marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.modeling.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/toolbar.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/types/modeling-types.ts, marklogic-data-hub-central/ui/src/api/modeling.ts, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.test.tsx, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/types/modeling-types.ts, marklogic-data-hub-central/ui/src/util/modeling-context.tsx
=> DHFPROD-4931: Save Entity

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowMigrator.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowMigratorTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowMigratorUnitTest.java, marklogic-data-hub/src/test/resources/flow-migration-test/flows/custom-master.flow.json, marklogic-data-hub/src/test/resources/flow-migration-test/flows/custom_only-flow.flow.json, marklogic-data-hub/src/test/resources/flow-migration-test/flows/ingestion_mapping-flow.flow.json
Migration of custom steps
```diff
```
=> DHFPROD-5181:Migration of custom steps

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/environment/ClearUserDataTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/customStep/getCustomStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/client/RunFlowViaMainTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/deploy/CopyQueryOptionsCommandTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/customStep/manageCustomStep.sjs, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
=> DHFPROD-5277: Fix ML-9.0-12 tests

marklogic-data-hub-central/ui/src/assets/mock-data/search-payload-results.js, marklogic-data-hub-central/ui/src/components/expandable-table-view/expandable-table-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs
=> DHFPROD-5116: Fixed snippet view

marklogic-data-hub-central/ui/src/assets/authorities.testutils.ts, marklogic-data-hub-central/ui/src/components/header/system-info.module.scss, marklogic-data-hub-central/ui/src/components/header/system-info.test.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.tsx, marklogic-data-hub-central/ui/src/util/authorities.tsx
=> DHFPROD-4812: UI: Clear user data from Hub Central

marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.test.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-5281: Zero state queries dropdown is not getting updated

marklogic-data-hub-central/build.gradle, web/build.gradle
=> DHFPROD-5292: Fixing the publish task

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/util/MlcpRunner.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/test/java/com/marklogic/hub/mlcp/MlcpCopyTest.java, marklogic-data-hub/src/test/resources/mlcp-test/test-doc.json
=> DHFPROD-5305: (DH 5.2) Provide privileges required for MLCP copy

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java, marklogic-data-hub-central/src/test/resources/test-projects/run-flow-test/flows/testFlow.flow.json, marklogic-data-hub-central/src/test/resources/test-projects/run-flow-test/modules/root/custom-modules/custom/testStep/main.sjs, marklogic-data-hub-central/src/test/resources/test-projects/run-flow-test/step-definitions/custom/testStep/testStep.step.json, marklogic-data-hub-central/src/test/resources/test-projects/run-flow-test/steps/custom/testStep.step.json, marklogic-data-hub-central/src/test/resources/test-projects/run-flow-test/steps/ingestion/testLoadData.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/stepDefinition.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
=> DHFPROD-4661: Verify custom steps can be run

Jenkinsfile, build.gradle, gradle.properties, marklogic-data-hub-central/build.gradle, marklogic-data-hub/build.gradle, web/build.gradle
Added an internal node mirror for downloading the node(http://node-mirror.eng.marklogic.com:8080/).  
```diff
```
=> DHFPROD-5441: Adding a proxy nexus

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/buildEntityTemplate.sjs
=> DHFPROD-5203: Throwing nicer error message when entity type isn't found

marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.module.scss
Css changes to fix formatting, no tests to add.
```diff
```
=> DHFPROD-5417:Fix Format of Popover Search

Jenkinsfile, build.gradle, gradle.properties, marklogic-data-hub-central/build.gradle, marklogic-data-hub/build.gradle, web/build.gradle
=> DHFPROD-5441: Changing the variable to nodeDistributionUrl

marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/util/MlcpRunner.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-common-writer.json, marklogic-data-hub/src/test/java/com/marklogic/hub/mlcp/MlcpCopyTest.java, marklogic-data-hub/src/test/resources/mlcp-test/test-doc.json
=> DHFPROD-5305: (DH 5.3) Provide privileges required for MLCP copy

marklogic-data-hub-central/ui/e2e/cypress/integration/scenarios.modeling.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/confirmation-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/types/modeling-types.ts, marklogic-data-hub-central/ui/src/assets/mock-data/modeling-context-mock.js, marklogic-data-hub-central/ui/src/assets/mock-data/modeling.js, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.test.tsx, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/types/modeling-types.ts, marklogic-data-hub-central/ui/src/util/modeling-context.tsx
=> DHFPROD-5156: Save All Entities

marklogic-data-hub-central/ui/src/components/tiles/toolbar.test.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.tsx
=> DHFPROD-5349: Various roles can access tiles they are not supposed to

marklogic-data-hub-central/ui/src/components/header/header.test.tsx, marklogic-data-hub-central/ui/src/components/header/header.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.module.scss, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx
Includes DHFPROD-5331: Remove search and settings icons from HC tool bar
```diff
```
=> DHFPROD-5379: Export query as CSV Preview table need to handle new lines

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateAndRunMapping.sjs
Return mapping validation array response to frontend
```diff
```
=> DHFPROD-5187:Return mapping validation array response to frontend

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubDatabaseCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/HubDeployDatabaseCommandFactory.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/DhsDeployer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployAsDeveloperTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployEntityIndexesTest.java, marklogic-data-hub/src/test/resources/test-projects/entity-with-indexes/entities/Person.entity.json
=> DHFPROD-5463: Staging database is now always updated by hubDeploy

CHANGELOG.md
=> DHFPROD-5470: Updating the changelog for 5.2.3

gradle.properties, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, ml-data-hub-plugin/gradle.properties, web/gradle.properties
=> DHFPROD-5470: Updating the version to 5.2.3

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/StepController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/StepControllerTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MasteringService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/StepService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/flow/getFlowsWithStepDetails.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/getStepsByType.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/getStepsByType.sjs
=> DHFPROD-5047: Endpoint for list of all steps

marklogic-data-hub-central/gradle.properties, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/SwaggerConfig.java, marklogic-data-hub-central/src/main/resources/application.properties
=> DHFPROD-5198: HC defaults to "production" profile

marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/components/footer/footer.module.scss, marklogic-data-hub-central/ui/src/components/header/header.module.scss, marklogic-data-hub-central/ui/src/components/header/system-info.module.scss, marklogic-data-hub-central/ui/src/components/queries/managing/edit-query-dialog/edit-query-dialog.module.scss, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.module.scss, marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.module.scss, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.module.scss, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.module.scss, web/src/main/ui/app/components/flows-new/edit-flow/mastering/merging/ui/merge-strategies-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ui/edit-flow-ui.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ui/step.component.scss, web/src/main/ui/app/components/flows-new/edit-flow/ui/stepper.component.scss, web/src/main/ui/app/components/jobs-new/ui/manage-jobs-ui.component.scss, web/src/main/ui/app/components/theme/styles/_material2-theme.scss
=> DHFPROD-5274: Update CSS font definitions

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
Handle null values in json array. e2e tests will be added by @bsrikan , no unit tests
```diff
```
=> DHFPROD-5151:Handle null values in json array

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/DeleteModelTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/generateModelConfig.sjs
=> DHFPROD-5494: Fix NPE while deploying search options

marklogic-data-hub-central/ui/src/components/facet/facet.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.tsx
This PR fixes the bug DHFPROD-5324. Only CSS fixes involved, so no tests are needed.
```diff
```
=> DHFPROD-5324: Fix the issue where grey background and border for entity/hub properties panel are not uniform

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/CreateAndUpdateModelTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/GenerateIndexesTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/com/marklogic/hub/impl/generate-indexes.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateSearchOptions.sjs, marklogic-data-hub/src/test/resources/scaffolding-test/employee.entity.json, marklogic-data-hub/src/test/resources/scaffolding-test/manager2.entity.json, marklogic-data-hub/src/test/resources/test-projects/all-artifacts/entities/Order.entity.json, marklogic-data-hub/src/test/resources/test-projects/all-artifacts/entities/Person.entity.json, marklogic-data-hub/src/test/resources/test-projects/download-artifacts/entities/Order.entity.json, marklogic-data-hub/src/test/resources/test-projects/download-artifacts/entities/Person.entity.json, marklogic-data-hub/src/test/resources/test-projects/entity-with-indexes/entities/Person.entity.json, ml-data-hub-plugin/src/test/resources/update-indexes/my-unique-order-entity.entity.json, ml-data-hub-plugin/src/test/resources/update-indexes/my-unique-save-index-entity-1.entity.json, ml-data-hub-plugin/src/test/resources/update-indexes/my-unique-save-index-entity-2.entity.json
=> DHFPROD-5018: Enable faceting for entity properties marked "facet-able" via modeling

marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/gradle.properties, marklogic-data-hub/build.gradle
=> DHFPROD-5123: Update Spring Framework version

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java, marklogic-data-hub-central/ui/src/assets/mock-data/flows.data.ts, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/pages/Curate.test.tsx, marklogic-data-hub-central/ui/src/pages/Load.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/flow/getFlowsWithStepDetails.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/testGetFlowsWithStepDetails.sjs
=> DHFPROD-5041: View steps from run tile

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/detail.tsx, marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/components/expandable-table-view/expandable-table-view.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.test.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/components/search-results/search-results.test.tsx, marklogic-data-hub-central/ui/src/components/search-results/search-results.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Detail.module.scss, marklogic-data-hub-central/ui/src/pages/Detail.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
- This PR also includes https://project.marklogic.com/jira/browse/DHFPROD-5328 ,https://project.marklogic.com/jira/browse/DHFPROD-5307, https://project.marklogic.com/jira/browse/DHFPROD-5373
- Fixed test suite which were previously commented out for table view
```diff
```
=> DHFPROD-5457:Detail and Browse View should open in the Explore tile

marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/table-view/table-view.test.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs
This PR fixes the bug DHFPROD-5358. Just a small bug fix so no unit tests added. @timur-isangulov will add an e2e test for this later.
```diff
```
=> DHFPROD-5358: Fixing the issue where UI throws error when source document is not an entity instance

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/scenarios.modeling.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/confirmation-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-table.tsx, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
```diff
```
Includes fix for DHFPROD-5415
=> DHFPROD-5284: Delete Property

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/scenarios.modeling.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx
=> DHFPROD-5180: Edit Property pt2

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/buildPropertyMetadata.sjs
=> DHFPROD-5514: Add facetable and sortable property in entityPropertyDefinitions within searchResponse

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/PullConfigurationFilesTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/hub/gradle/task/PullConfigurationFilesTaskTest.groovy
Pull configuration files from DH instance
```diff
```
=> DHFPROD-5199:Pull configuration files from DH instance

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping-functions/core.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/MappingTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/parseDate.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/parseDateTime.sjs
=> DHFPROD-3671: Support more formats for parseDate and parseDateTime

marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle
=> DHFPROD-5508: Upgrading to ml-gradle 4.0.4 / ml-app-deployer 4.0.3

examples/reference-entity-model/steps/mapping/mapCustomersXML.step.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/mapping/mapCustomersXML.step.json
=> DHFPROD-5303: Use text nodes instead of just nodes

Jenkinsfile, marklogic-data-hub-central/ui/e2e/Dockerfile, marklogic-data-hub-central/ui/e2e/setup.sh
Running windows tests before quickstart
Fixing typo
Moving the DHS pipeline stage
Deleting Docker file
```diff
```
=> DHFPROD-5466: Cypress E2e update

marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/discard-changes/discard-changes-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/types/query-types.ts, marklogic-data-hub-central/ui/src/util/search-context.tsx, marklogic-data-hub-central/ui/src/util/test-utils.tsx
This PR takes care of the tickets DHFPROD-4082 and DHFPROD-4985.
```diff
```
=> DHFPROD-3577: Global sort based on Indexed properties (4082 & 4985)

web/src/main/java/com/marklogic/hub/web/auth/ConnectionAuthenticationFilter.java
Enable login to QS. There are QS tests in pipeline which should pass once this is merged.
```diff
```
=> DHFPROD-5447:Enable login to QS

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/Customer.entity.json, marklogic-data-hub-central/ui/src/components/numeric-facet/numeric-facet.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx
=> DHFPROD-5421:Unable to click 'Apply Changes' after adjusting numeric facet filter.

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/scenarios.modeling.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/confirmation-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/types/modeling-types.ts, marklogic-data-hub-central/ui/src/assets/mock-data/modeling-context-mock.js, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.test.tsx, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/types/modeling-types.ts, marklogic-data-hub-central/ui/src/util/modeling-context.tsx
=> DHFPROD-5067: Revert all changes to entity types

marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.test.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx
=> DHFPROD-5386: Explorer Zero state: Default dropdown should be populated

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/environment/DownloadProjectFilesMvcTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/getArtifactsWithProjectPaths.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/AllArtifactsProject.java
=> DHFPROD-5476: Download Configuration Files is not working in Windows machine

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/com/marklogic/hub/impl/generate-indexes.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateSearchOptions.sjs
- DHFPROD-5522: Fix for the 9.0-12 failing tests
- Tests to check generation of index config and search options for already existing indexes
```diff
```
=> DHFPROD-5018: Tests to check generation of index config and search options for already existing indexes

CONTRIBUTING.md
=> DHFPROD-5524: Updated to mention skipWeb when publishing

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/saveStep.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/manageMappingStep.sjs
Set correct values for 'processors', 'customHook' and 'headers' when a step is edited
```diff
```
=> DHFPROD-5370:Set correct values for 'processors', 'customHook' and 'headers' when a step is edited

CONTRIBUTING.md
=> DHFPROD-5543: Fix supported Java versions on CONTRIBUTING page

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.table.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.xml.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar-rtl.test.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
=> DHFPROD-5392: Make "Hub Properties" expanded by default in "all entities" results view side-pane under Explorer tile

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateFunctionMetadataCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployAsDeveloperTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/deploy/GenerateFunctionMetadataInDhsTest.java
=> DHFPROD-5496: User function errors won't cause DHF installer to fail

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/Versions.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
=> DHFPROD-5497: Not installing granular privileges if ML doesn't support

CODEOWNERS
We'll try this and see how it works out. Can always modify later.
```diff
```
=> DHFPROD-5552: Added code owners file

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/scenarios.modeling.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx
=> DHFPROD-5362: Add Entity button disabled if duplicate name is used fix

Jenkinsfile, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, pipeline.properties
=> DHFPROD-5563: Updating the versions and setting up pipeline for 5.4

Jenkinsfile
=> DHFPROD-5566: Fixing windows regression

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateFunctionMetadataCommand.java
Also fixed a logging statement in CreateGranularPrivilegesCommand
```diff
```
=> DHFPROD-5496: Added logging for function metadata

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java, marklogic-data-hub-central/src/test/resources/test-projects/run-flow-test/flows/testCsvFlow.flow.json, marklogic-data-hub-central/src/test/resources/test-projects/run-flow-test/steps/ingestion/testLoadCsvAsXml.step.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-common.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/flow-operator-role.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-entity-exporter.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-mapping-reader.json
=> DHFPROD-5520: Load CSV to XML with step-runner role

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/src/components/load/switch-view.scss, marklogic-data-hub-central/ui/src/components/load/switch-view.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/edit-query-dialog/edit-query-dialog.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.module.scss, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.test.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx
Includes: DHFPROD-5399, DHFPROD-5308, DHFPROD-5544
```diff
```
=> DHFPROD-5330: Fix alignment and words used in the zero state page

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStepWithCustomHookTest.java, marklogic-data-hub/src/test/resources/entity-reference-model/flows/customHookFlow.flow.json, marklogic-data-hub/src/test/resources/entity-reference-model/modules/root/custom-modules/custom-hooks/test-hook.sjs
=> DHFPROD-5575: Added test for custom hooks

marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/Main.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/AbstractInstallerCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/CanInstallDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/command/CanInstallDhsCommandTest.java
Determine if DHF installer can be run against existing DHS instance
```diff
```
=> DHFPROD-5460:Determine if DHF installer can be run against existing DHS instance

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/search-results/search-results.test.tsx, marklogic-data-hub-central/ui/src/components/search-results/search-results.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
Also includes DHFPROD-5342
```diff
```
=> DHFPROD-5343: Saving a query in snippet view throws an error

marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-5258:After mapping step is run, Tile title should be Explore, shows up Run tile title and icon

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-validate-trigger.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/models/insertInvalidEntityModel.sjs
Most of the changes are whitespace because I tossed everything in the trigger into a try/catch block. 
```diff
```
=> DHFPROD-5517: Nicer error message when model fails validation

marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/ui/package-lock.json
=> DHFPROD-5506: Update node version for security

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/flow/createFlow.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/manageFlow.sjs
=> DHFPROD-5425: Prevent creating flow with existing name

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/scenarios.modeling.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-table.tsx, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, package-lock.json
=> DHFPROD-5321: firefox improvement, design system v1.0.4

marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/AbstractInstallerCommand.java
Changing the log message when getting DHF version fails.
```diff
```
=> DHFPROD-5460:Changing the log message when getting DHF version fails

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/ConstrainSourceQueryToJobTest.java
This test failed in Jenkins due to not finding an entity - not sure how that could happen, but I feel better having it use the reference project.
```diff
```
=> DHFPROD-5588: Converting test to work with reference project

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/getArtifactsWithProjectPaths.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/AllArtifactsProject.java
=> DHFPROD-5529: Fixing PII path filenames

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/PullConfigurationFilesTask.groovy
=> DHFPROD-5209: Tweaks to task descriptions and logging

Jenkinsfile, marklogic-data-hub/build.gradle
=> DHFPROD-5625: Call bootstrap task explicitly

marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.test.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx
=> DHFPROD-5548: Remove the link column from the manage queries pane

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/getArtifactsWithProjectPaths.sjs, marklogic-data-hub/src/test/resources/test-projects/all-artifacts/steps/custom/someTestStep.step.json
=> DHFPROD-5635: Don't include custom steps in download

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result-rtl.test.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx
=> DHFPROD-5547: Tooltips and word fixes for detailed view

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/EntitySearchControllerTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/EntitySearchService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getOpticPlan.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getOpticPlan.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/getOpticPlanTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/suiteSetup.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/test-data/entities/EntitySearchEntity.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/test-data/entities/NumericEntity.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/test-data/entities/NumericStringEntity.entity.json
=> DHFPROD-3577: Support sorting on export

ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/PullConfigurationFilesTask.groovy
=> DHFPROD-5209: Not deleting downloaded file

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.tsx
=> DHFPROD-5408: Discard all changes icon in explorer screen doesn't work consistently

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/models/SearchQuery.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/EntitySearchControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub-central/ui/src/util/search-context.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getOpticPlan.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/getOpticPlanTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateSearchOptions.sjs, marklogic-data-hub/src/test/resources/customer-entity-with-indexes/entities/Customer.entity.json, marklogic-data-hub/src/test/resources/test-config/databases/staging-database.json, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
=> DHFPROD-3577: Global sort based on sortable properties

marklogic-data-hub-central/ui/src/components/header/header.test.tsx, marklogic-data-hub-central/ui/src/components/header/header.tsx
=> DHFPROD-5325:Add link from Hub Central to documentation site

examples/reference-entity-model/.gitignore, examples/reference-entity-model/build.gradle, examples/reference-entity-model/flows/CurateCustomerJSON.flow.json, examples/reference-entity-model/flows/CurateCustomerXML.flow.json, examples/reference-entity-model/input/json/Cust5-merge.json, examples/reference-entity-model/src/main/ml-config/security/users/hub-developer.json, examples/reference-entity-model/src/main/ml-config/security/users/hub-operator.json, examples/reference-entity-model/src/main/ml-config/security/users/hub-user.json, examples/reference-entity-model/src/main/ml-modules/root/custom-modules/custom/collectionAdder/collectionAdder.sjs, examples/reference-entity-model/step-definitions/custom/collectionAdder/collectionAdder.step.json, examples/reference-entity-model/steps/custom/collectionAdder.step.json
Also adding "hub-user" for testing a user that only has hub-central-user (it doesn't work, Explore blows up because the user can't hit the saved query endpoints, will write up a ticket for that).
```diff
```
=> DHFPROD-5630: Adding steps to reference project

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/getArtifactsWithProjectPaths.sjs
=> DHFPROD-5635: Adjusting fix for what steps to download

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/column-selector/column-selector.test.tsx, marklogic-data-hub-central/ui/src/components/column-selector/column-selector.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export.test.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/util/data-conversion.tsx
Includes: DHFPROD-5154, DHFPROD-5449, DHFPROD-5490, DHFPROD-5549, DHFPROD-5586
```diff
```
=> DHFPROD-5550: Tooltip and indicator for identifier column

marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/HubCentralManager.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/ApplyDownloadedZipToProjectTest.java, marklogic-data-hub/src/test/resources/test-projects/download-artifacts/steps/custom/customStep.step.json, marklogic-data-hub/src/test/resources/test-projects/download-artifacts/steps/mapping/personMapping.step.json
=> DHFPROD-5635: Only deleting ingestion and mapping steps on apply

marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.test.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx
also updated link test with proper permissions needed to view the link column
```diff
```
=> DHFPROD-5433: Confirmation modal message for deleting a query doesn't match the AC

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/AddStepToFlowTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/AddStepToFlowTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/AddStepToFlowTaskTest.groovy
=> DHFPROD-5266:Add step to flow

marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.tsx, marklogic-data-hub-central/ui/src/util/conversionFunctions.tsx
=> DHFPROD-5043: Incorrect collection name shows up in mapping UI

Jenkinsfile, marklogic-data-hub-central/build.gradle
Run the buildRpm task on build and publish the RPMS
```diff
```
=> DHFPROD-5696: Build and publish RPM

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/auth/WebSecurityConfiguration.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/auth/SessionManagerTest.java
=> DHFPROD-5492: Use random port for session test

marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.test.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-4589: Use custom trigger for collapsable side bar

marklogic-data-hub-central/ui/src/pages/Run.tsx
Fixes error message to have bolded flow name
```diff
```
=> DHFPROD-5425: Duplicate flow name error message now has a bolded flow name

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/auth/SessionManagerTest.java, marklogic-data-hub-central/ui/src/App.test.tsx, marklogic-data-hub-central/ui/src/util/stomp.ts, marklogic-data-hub-central/ui/src/util/user-context.tsx
=> DHFPROD-5492: log out websockets ends in closed state

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EnvironmentController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/environment/DownloadProjectFilesMvcTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/PullConfigurationFilesTask.groovy
=> DHFPROD-5686: HC project zip filename is now consistent

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/buildEntityNamespaceMap.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateIndexes.sjs
=> DHFPROD-5685: Always including entity namespace prefixes in indexes

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/getEntityInstance.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/instanceWithNamespace.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/textdoc.txt
=> DHFPROD-5637: Add entityInstance object to search results for row render

marklogic-data-hub-central/ui/src/assets/mock-data/flows.data.ts, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx
=> DHFPROD-5311: Fix file type circles in Run Tile

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/WriteStepRunnerTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/convertIngestionStep.sjs
Fix issues with "outputURIPrefix" in ingestion step
```diff
```
=> DHFPROD-5224:Fix issues with "outputURIPrefix" in ingestion step

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/EntityManagerImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/entity/EntityManagerTest.java, marklogic-data-hub/src/test/resources/scaffolding-test/ManagerWithEmployeeRef.entity.json
=> DHFPROD-5132: Filter out external references in mapping

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepDefinition/getStepDefinition.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/models/GetPrimaryEntityTypesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/GenerateFunctionMetadataCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/IngestToFinalTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunFlowWithInvalidStepDefTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStepWithCustomHookTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStepWithProcessorsTest.java, marklogic-data-hub/src/test/resources/test-projects/flow-with-invalid-step-def/flows/invalidStepDef.flow.json, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/ReferenceModelProject.java
Most of this is test cleanup - I moved "runFlow" from ReferenceModelProject to AbstractHubTest so it can be easily reused in any test. Added RunFlowWithInvalidStepDefTest to test the actual changes. 
```diff
```
=> DHFPROD-5693: Nice error thrown when a step def cannot be found

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/customStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/loadData.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mapping.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/matching.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/stepDefinition.sjs
The 3 functions were not used anywhere and can safely be removed. 
```diff
```
=> DHFPROD-5709: Removing unused artifacts functions

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
Remove unnecessary GET and POST calls when opening mapping.  No tests needed. I have added info on what manual tests have to be done in the ticket
```diff
```
=> DHFPROD-5627:Remove unnecessary GET and POST calls when opening mapping

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
- Fix ambiguous indentation in source table of mapping step
- Adjusted respective unit tests accordingly.
```diff
```
=> DHFPROD-5136: Fix indentation for source documents in Mapping Step

marklogic-data-hub/src/main/resources/scaffolding/custom-module/sjs/main-custom.sjs
Fixing the custom step boilerplate code. No tests needed. 
```diff
```
=> DHFPROD-4807:Fixing the custom step boilerplate code

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/confirmation-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/types/modeling-types.ts, marklogic-data-hub-central/ui/src/assets/mock-data/modeling-context-mock.js, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.test.tsx, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/types/modeling-types.ts
=> DHFPROD-5512: Save and delete entity type

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/getEntityInstance.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/instanceElementInDifferentXpath.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/mergedJsonInstance.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/mergedXmlInstance.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/entities/Person.entity.json
=> DHFPROD-4145: Ability to show multiple values in the table view when it conflicts with the associated property definition

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
… loading large docs
```diff
```
=> DHFPROD-5369: Usability bug: Mapping step should show a spinner while loading large docs

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/WebSocketConfig.java
=> DHFPROD-5492: Add CORS header to websockets requests

marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/HubProject.java, marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/migration/FlowMigrator.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/StepDefinitionManagerImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mastering.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/merging.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/saveStep.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/ApplyDownloadedZipToProjectTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/migration/AllStepsReferencedTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/migration/FlowMigratorTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/step/StepDefinitionManagerTest.java, marklogic-data-hub/src/test/resources/flow-migration-test/flows/ingestionMappingFlow.flow.json, marklogic-data-hub/src/test/resources/flow-migration-test/flows/ingestionMappingMasteringFlow.flow.json, marklogic-data-hub/src/test/resources/test-projects/all-steps-referenced/data/json/Cust1.json, marklogic-data-hub/src/test/resources/test-projects/all-steps-referenced/data/json/Cust2.json, marklogic-data-hub/src/test/resources/test-projects/all-steps-referenced/data/json/Cust3.json, marklogic-data-hub/src/test/resources/test-projects/all-steps-referenced/data/json/Cust4.json, marklogic-data-hub/src/test/resources/test-projects/all-steps-referenced/data/json/Cust5-merge.json, marklogic-data-hub/src/test/resources/test-projects/all-steps-referenced/data/json/Cust5.json, marklogic-data-hub/src/test/resources/test-projects/all-steps-referenced/entities/Customer/Customer.entity.json, marklogic-data-hub/src/test/resources/test-projects/all-steps-referenced/entities/Order/Order.entity.json, marklogic-data-hub/src/test/resources/test-projects/all-steps-referenced/flows/CurateCustomerJSON.flow.json, marklogic-data-hub/src/test/resources/test-projects/all-steps-referenced/mappings/CurateCustomerJSONMapping/CurateCustomerJSONMapping-1.mapping.json, specs/models/Flow.schema.json, web/src/test/java/com/marklogic/hub/web/service/FlowManagerServiceTest.java
=> DHFPROD-5663: Migrate matching, merging, and mastering steps

marklogic-data-hub-central/ui/e2e/cypress.json, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/projectInfo.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/e2e/package-lock.json, marklogic-data-hub-central/ui/e2e/package.json, marklogic-data-hub-central/ui/src/assets/mock-data/ingestion.data.ts, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx
DHFPROD-5162: fix unit tests
fixes failing ingestion tests.
detailed tests for user facing roles
locator updates and corresponding unit test fixes
```diff
```
=> DHFPROD-5162: comprehensive e2e tests for different hc roles

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx
This PR only has fixes for e2e tests failing in scenarios.queries, tests pass on mac. @bsrikan will be testing on windows once all the e2e tests pass across the app. https://github.com/marklogic/marklogic-data-hub/pull/4391 has fixes for other e2e tests
```diff
```
=> DHFPROD-5721: Cypress E2E tests fail on Both Mac and windows

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-common.json, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/sm-es-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/helper-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-matching/matchWithUnderscore.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-matching/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-matching/test-data/content/customer1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-matching/test-data/content/customer2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-matching/test-data/entities/Customer_V1.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-matching/test-data/flows/customerV1Flow.flow.json
=> DHFPROD-5700: Don't add unnecessary encoding for match queries

Jenkinsfile
```diff
```
- [ NA] Added Tests
- [ NA] Reviewed Tests
=> DHFPROD-5723: Abort the pipelines in case of draft

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/IngestToFinalTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/flow-utils/getMetadata.sjs
=> DHFPROD-5380: datahubCreatedByStep is now set correctly

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs
=> DHFPROD-5413: Return search results in the order of selected properties

Jenkinsfile
=> DHFPROD-5723: Run build tasks in parallel

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.module.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/custom/view-custom-dialog/view-custom-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/create-edit-matching-dialog/create-edit-matching-dialog.module.scss, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.module.scss, marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.module.scss, marklogic-data-hub-central/ui/src/components/login-form/login-form.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.module.scss
=> DHFPROD-5385: Tooltip help icon colors are different colors

Jenkinsfile, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.table.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
=> DHFPROD-5722: Run cypress tests on PR

Jenkinsfile
=> DHFPROD-5722: Fixing gradle path issues

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.module.scss
No tests needed for CSS change. 
```diff
```
=> DHFPROD-5598: Hovering over unapplied facets make them look like applied facets

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateSearchOptions.sjs
=> DHFPROD-5728: Sort entities based on datatype-specific index

marklogic-data-hub/src/test/java/com/marklogic/hub_integration/MappingE2E.java
Remove the unnecessary cleanup in 'MappingE2E' test
```diff
```
=> DHFPROD-5758:Remove the unnecessary cleanup in 'MappingE2E' test

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/matching.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/merging.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/saveStep.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/AddStepToFlowTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/CreateStepTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/AddStepToFlowTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateStepTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateStepTaskTest.groovy
Create "matching" and "merging" steps, add them to flow
```diff
```
=> DHFPROD-5666:Create "matching" and "merging" steps, add them to flow

marklogic-data-hub-central/ui/src/pages/Run.tsx
=> DHFPROD-5695: Modals aren't closed when HC auto logs off

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/query/manage-queries-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx
=> DHFPROD-5570: Description doesn't showup when we apply a query from zero state.

marklogic-data-hub-central/ui/src/assets/mock-data/common.data.ts, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
Updates to source value display in mapping:
- Strings surrounded with double quotes
- Properties equal to null or "" are displayed in source table
- Properties equal to null or "" are displayed correctly in source dropdown in entity table
More details in the Jira ticket: https://project.marklogic.com/jira/browse/DHFPROD-5372
```diff
```
=> DHFPROD-5372: Handle strings and null values correctly in mapping source

marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.tsx
=> DHFPROD-5744: Remove disabled trash icon from Custom Step card

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/sally.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/sally.xml
=> DHFPROD-5762: Adding sources object in Entity Headers to search result

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
This PR also includes DHFPROD-5408, DHFPROD-5450, DHFPROD-5713
```diff
```
=> DHFPROD-5412: Can't clear or unselect selected facets on side bar.

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/ingestion/bulkIngester.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/ingestion/bulkIngester.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/ingestion/BulkIngestTest.java
=> DHFPROD-5473 : Adding endpoints and unit test

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/exceptions/CustomExceptionHandler.java
=> DHFPROD-5541: Log handled exceptions

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/ingestion/bulkIngester.sjs
=> DHFPROD-5473: Adding permission comment to sjs file.

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/async-loader/async-loader.tsx
=> DHFPROD-5771: Stabilize e2e and handle async XHR requests

marklogic-data-hub/src/main/java/com/marklogic/hub/FlowManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MasteringService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/conversion/FlowConverter.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/StepManager.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMatchOptions.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMatchOptions.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMatchOptionsLib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/conversion/AllStepsReferencedTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/conversion/FlowConverterUnitTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/updateMatchOptions.sjs
=> DHFPROD-5182: Transform match steps to new model

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/ingestion/bulkIngester.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/ingestion/BulkIngestTest.java
=> DHFPROD-5474: Serialization with an envelope

marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/conversion/FlowConverter.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java
Return 'null' if local flow file is not found. Failing tests should run fine
```diff
```
=> DHFPROD-5182:Return 'null' if local flow file is not found

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs
Updating the doc for "makeEnvelope" function
```diff
```
=> DHFPROD-5667:Updating the doc for "makeEnvelope" function

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
=> DHFPROD-5781: Selected facets display with the entity name when refreshing page.

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx
Also includes DHFPROD-5779
```diff
```
=> DHFPROD-5398:On deleting selected query, Clear Query icon gets distorted

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mapping.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/mappingStep/GetMappingStepsTest.java
This was actually intentional was a hack until mapping steps were ready to go. 
```diff
```
=> DHFPROD-5582: Fixing bug where legacy mappings were returned as steps

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-xml/lib/lib.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-xml/merge-data-hub-headers.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-xml/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-xml/test-data/entities/Customer.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-xml/test-data/hub-doc1.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-xml/test-data/hub-doc2.xml
=> DHFPROD-5792: Keep Hub sources header XML intact on merge

marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub-central/ui/src/pages/Run.test.tsx
=> DHFPROD-5581: Fix wording on hover text for X in steps in a flow

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMatchOptions.sjs
=> DHFPROD-5182: Add "No privilege required" comment

marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MasteringService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/conversion/FlowConverter.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMergeOptions.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMergeOptions.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMergeOptionsLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/updateMergeOptions.sjs
=> DHFPROD-5183: Transform merge steps to new model

marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
=> DHFPROD-5722: Fixing the version

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/flowRunsWithStepRunnerRole.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-matching/matchWithUnderscore.sjs
See the assertion messages for why
```diff
```
=> DHFPROD-5766: Not running certain tests on ML 9

Jenkinsfile
=> DHFPROD-5723: re-arranging the stages

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/api/__mocks__/facets.tsx, marklogic-data-hub-central/ui/src/api/facets.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/facet.js, marklogic-data-hub-central/ui/src/components/facet/facet.tsx, marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.test.tsx, marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
Also includes fix for failing scenarios.json test in the pipeline
```diff
```
=> DHFPROD-5783:String facets on the search popover don't indicate the current selection state.

marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
No tests for adding missing key props for the components. 
```diff
```
=> DHFPROD-5787: Non unique keys console warning for the MLTable on Explore tab.

marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts, marklogic-data-hub-central/ui/src/components/header/system-info.test.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.tsx
https://drive.google.com/file/d/13P_jMb29jmmshmgqfg0xlKcvocFM6agB/view
```diff
```
=> DHFPROD-5579: Add confirmation modal for Clear User Data

web/src/main/ui/app/components/flows-new/edit-flow/ui/new-step-dialog-ui.component.ts
Enable creation of steps with stepDefName "default-*". This line was inadvertently removed when working on DHFRPOD-5633. Adding it back.
```diff
```
=> DHFPROD-5633:Enable creation of steps with stepDefName "default-*"

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubOtherServersCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/deploy/DhsDeployServersCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/DeployHubOtherServersCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/deploy/DhsDeployServersCommandTest.java
Bug was introduced when HubClient was added, as Versions was trying to get a server version without either HubConfig or HubClient. We now have automated tests to ensure this feature works correctly. 
```diff
```
=> DHFPROD-5802: Fixing how staging rewriter is set

marklogic-data-hub-central/ui/src/assets/mock-data/search-payload-results.js, marklogic-data-hub-central/ui/src/components/detail-header/detail-header.test.tsx, marklogic-data-hub-central/ui/src/components/detail-header/detail-header.tsx, marklogic-data-hub-central/ui/src/components/expandable-table-view/expandable-table-view.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs
This PR includes fix for the bug DHFPROD-4138 and some refactoring of the code.
```diff
```
=> DHFPROD-4138: Handling duplicates in the sources array in searchResults response and refactoring the explorer code accordingly.

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/bulk/fixCreatedByStep.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FixCreatedByStepTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/FixCreatedByStepTask.groovy
=> DHFPROD-5743: Handling case where docs have multiple job IDs

marklogic-data-hub/src/main/resources/scaffolding/custom-module/sjs/main-custom.sjs
Adding comments to custom main.sjs module for handling XML instances
```diff
```
-[N/A ] Added Tests
=> DHFPROD-4076:Adding comments to custom main.sjs module for handling XML instances

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.tsx
=> DHFPROD-5783:String facets on the search popover don't indicate the current selection state. 

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.test.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-5803: The save query icon should not persist when switching between entities. 

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/manageMappingStep.sjs
=> DHFPROD-5824: Defaulting targetFormat for mapping step

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-trigger.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/entity/GenerateSchemasTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
Also modified resetDatabases so that the schema databases are cleared. 
```diff
```
=> DHFPROD-5811: Fixing schema generation when multiple namespaces are used

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
- Fixed TypeError causing problems during XML source document rendering 
- No tests added for simple error fix, the scenario is already covered by existing tests (once it passes the error that this PR resolves).
```diff
```
=> DHFPROD-5822: XML source document not getting rendered

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/components/detail-header/detail-header.tsx, marklogic-data-hub-central/ui/src/components/expandable-table-view/expandable-table-view.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx
This PR fixes the bug 5727 and involves few more enhancements to the explorer UI code. e2e test is added.
```diff
```
=> DHFPROD-5727: Fixing the bug where 400 error occurs on refreshing the Detail page in Explore tile

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/saveStep.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/createXmlIngestionStep.sjs
=> DHFPROD-5836: Not including outputFormat in HC ingestion steps

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/detail.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx
This PR contains a minor fix for the bug DHFPROD-5808 and small refactoring in e2e tests.
```diff
```
=> DHFPROD-5808: Fix the bug where creating or deleting a Mapping step causes extra GET requests

marklogic-data-hub/src/main/resources/scaffolding/defaultFlow.flow.json, marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/CreateDefaultFlowTest.java
=> DHFPROD-5832: Mapping step in default flow uses targetEntity

examples/reference-entity-model/input/xml/CustXMLDoc1.xml, examples/reference-entity-model/input/xml/CustXMLDoc2.xml, examples/reference-entity-model/input/xml/CustXMLDoc3.xml, examples/reference-entity-model/input/xml/CustXMLDoc4.xml, examples/reference-entity-model/input/xml/CustXMLDoc5.xml
=> DHFPROD-5814:Add xml test data to verify ingestion functionality

Jenkinsfile
=> DHFPROD-5723: Changing the ML version to 10.0-4.4

marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/util/user-context.tsx
=> DHFPROD-5804: Fix endpoints being called on logout

marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx
=> DHFPROD-5818: Disabled buttons have hover color on Run Tile

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
=> DHFPROD-5825: Mapping collapse/expand buttons do not reset on close

examples/dh-5-example/flows/ingestion_mapping-flow.flow.json, examples/dh-5-example/flows/ingestion_mapping_mastering-flow.flow.json
Adding "targetEntity" to mapping steps
```diff
```
=> DHFPROD-5810:Adding "targetEntity" to mapping steps

marklogic-data-hub-central/ui/e2e/cypress/fixtures/curateTile/orderDateProcessor.json, marklogic-data-hub-central/ui/e2e/cypress/fixtures/input/10259.json, marklogic-data-hub-central/ui/e2e/cypress/fixtures/loadTile/orderCategoryCodeProcessor.json, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/advanced-settings-dialog.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/e2e/hc-qa-project/src/main/ml-modules/root/custom-modules/step-processors/addOrderCategoryCode.sjs, marklogic-data-hub-central/ui/e2e/hc-qa-project/src/main/ml-modules/root/custom-modules/step-processors/addOrderDate.sjs
=> DHFPROD-5530: e2e test for custom ingest processor

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/detail.tsx, marklogic-data-hub-central/ui/src/components/expandable-table-view/expandable-table-view.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/components/table-view/table-view.test.tsx, marklogic-data-hub-central/ui/src/components/table-view/table-view.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx
This PR removes the last pieces of extracted object being used in explorer UI code. It was necessary to be consistent across all navigating components in explorer and also to avoid issues like DHFPROD-5761.
```diff
```
=> DHFPROD-5761: Removing last usage of extracted object in explorer UI code to fix few other issues.

marklogic-data-hub-central/ui/src/components/column-selector/column-selector.test.tsx, marklogic-data-hub-central/ui/src/components/column-selector/column-selector.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
=> DHFPROD-5819: Column selector on explore tile is not consistent.

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/DhsDeployer.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/deploy/DeployHubAmpsCommand.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-security-admin.json, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/Installer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployAsSecurityAdminTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployUserAmpsTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
PR to allow DHS users to define and deploy Amps.
@kkanthet , @SameeraPriyathamTadikonda 
This PR requires 10.0-4.4 for the tests to run. I believe PR jobs run on 10.0-4.2. Can the version be bumped up to 10.0-4.4 ?
```diff
```
=> DHFPROD-5571:Allow DHS users to define and deploy Amps

web/src/main/java/com/marklogic/hub/web/service/CollectionsService.java
Remove 'hub-internal-artifact' from the list of collections
```diff
```
=> DHFPROD-5864:Remove 'hub-internal-artifact' from the list of collections

marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx
=> DHFPROD-5851: Fix mapping tool namespacing edge case

marklogic-data-hub-central/build.gradle
=> DHFPROD-5867: Removing publish task

examples/reference-entity-model/src/main/ml-config/security/users/wailin.json
Add "hub-central-custom-reader" to wailin.
@SameeraPriyathamTadikonda 
I don't think this PR needs to run all the tests. I think this can be merged after approval
```diff
```
=> DHFPROD-5869:Add "hub-central-custom-reader" to wailin

examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DHFPROD-5873: Updating version to 5.3.0-rc1

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/AddStepToFlowTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/CreateStepTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateFlowTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateFlowTaskTest.groovy
Write flow artifact created by 'hubCreateFlow' to db, add better logging
```diff
```
=> DHFPROD-5877:Write flow artifact created by 'hubCreateFlow' to db, add better logging

marklogic-data-hub-central/ui/src/components/login-form/login-form.tsx
Remove console.log in the login-form component that is displaying user response info.
```diff
```
=> DHFPROD-5894: Remove console.log in login-form

marklogic-data-hub-central/ui/e2e/README.md, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub-central/ui/e2e/setup.sh
1. Updates to README with example of curationEndpoint requested by cloud services team and steps to run e2e test against DHS.
2. Updated setup script and build.gradle to include task to verify flow was run successfully by checking record count in staging and final database
```diff
```
- [ NA ] Added Tests
- [ NA ] Reviewed Tests
=> DHFPROD-5786: Updates to e2e readme, setup script and build.gradle

CHANGELOG.md, Jenkinsfile, gradle.properties, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, ml-data-hub-plugin/gradle.properties, pipeline.properties, web/gradle.properties
```diff
```
- [NA] Squashed all commits into a single commit
=> DHFPROD-5879: Update versions to 5.2.4

marklogic-data-hub-central/src/main/resources/application-dev.properties, marklogic-data-hub-central/src/main/resources/application.properties
=> DHFPROD-5901: Use DEBUG level logging only in the dev profile

CHANGELOG.md
Updating the changelog in develop branch
```diff
```
=> DHFPROD-5879: Updating changelog for 5.2.4

marklogic-data-hub-glue-connector/README.md, marklogic-data-hub-glue-connector/build.gradle, marklogic-data-hub-glue-connector/gradle.properties, marklogic-data-hub-glue-connector/src/main/java/com/marklogic/hub/cloud/aws/glue/IOUtil.java, marklogic-data-hub-glue-connector/src/main/java/com/marklogic/hub/cloud/aws/glue/Writer/MarkLogicDataWriter.java, marklogic-data-hub-glue-connector/src/main/java/com/marklogic/hub/cloud/aws/glue/Writer/MarkLogicDataWriterFactory.java, marklogic-data-hub-glue-connector/src/main/java/com/marklogic/hub/cloud/aws/glue/Writer/MarkLogicWriteDataSource.java, marklogic-data-hub-glue-connector/src/main/java/com/marklogic/hub/cloud/aws/glue/Writer/MarkLogicWriter.java, settings.gradle
=> DHFPROD-5882: Adding connector code in a new directory.

examples/reference-entity-model/src/main/ml-config/security/users/bertrand.json, examples/reference-entity-model/src/main/ml-config/security/users/stewart.json, examples/reference-entity-model/src/main/ml-config/security/users/wailin.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-curator.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-explorer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-modeler.json, marklogic-data-hub/src/test/java/com/marklogic/hub/security/VerifyHubCentralRolesTest.java
Create hub-central roles to be shown in service portal
```diff
```
=> DHFPROD-5898:Create hub-central roles to be shown in service portal

Jenkinsfile, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
=> DHFPROD-4723: Running tests in parallel

marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
Not sure why, but clearDatabase is failing against Docker VMs - so using a DatabaseClient again. 
```diff
```
=> DHFPROD-4723: Fixing how schemas databases are cleared

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubDatabaseCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/HubCentralManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/EntityManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/impl/LegacyFlowManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/Step.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/util/json/JSONObject.java, web/src/main/java/com/marklogic/hub/web/model/MappingModel.java, web/src/main/java/com/marklogic/hub/web/service/MappingManagerService.java, web/src/main/java/com/marklogic/hub/web/service/NewJobService.java
=> DHFPROD-5691: Fix outstanding issues found by coverity static scan

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx
=> DHFPROD-5830: fix for revert entity type

marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx
=> DHFPROD-5488:Move X in facets to the right side of the bubbles

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/EntitySearchControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub-central/src/test/resources/test-projects/reference-project/entities/Customer.entity.json, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/EntitySearchService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ModelsService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/exportSearchAsCSV.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/exportSearchAsCSV.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/exportSearchAsCSVTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/suite-setup.xqy, marklogic-data-hub/src/test/resources/entity-reference-model/entities/Customer.entity.json, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
In the process of adding tests.
```diff
```
=> DHFPROD-5870: Fix namespaced path range indexes on export

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java
=> DHFPROD-5691: Fix outstanding issue found by coverity static scan

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx
Fix for the e2e tests.
An e2e tests should be removed and the similar scenario should be handled in RTL integration test. Created below task to take care of it.
https://project.marklogic.com/jira/browse/DHFPROD-5958
```diff
```
=> DHFPROD-5597: Fixing the failing e2e tests

examples/reference-entity-model/README.md
```diff
```
- [ NA] Added Tests
- [ NA] Reviewed Tests
=> DHFPROD-5815: Adding instructions to deploy the project to DHS

marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/src/util/stomp.ts, marklogic-data-hub-central/ui/src/util/user-context.tsx
=> DHFPROD-5907: Fix Cypress WebSocket errors

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/assets/mock-data/entity-table.js, marklogic-data-hub-central/ui/src/components/facet/facet-element.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.module.scss, marklogic-data-hub-central/ui/src/components/facet/facet.test.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.tsx, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.tsx
Includes DHFPROD-3628: Remove unneeded tooltips for Explorer facet values
```diff
```
=> DHFPROD-5748: Radio group for switching views in Explore is not consistent with Load.

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/Customer.entity.json, marklogic-data-hub-central/ui/src/components/date-facet/date-facet.tsx, marklogic-data-hub-central/ui/src/components/date-time-facet/date-time-facet.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
=> DHFPROD-5897: Clearing date range facet does not clear facet.

examples/reference-entity-model/flows/CurateCustomerJSON.flow.json, examples/reference-entity-model/steps/matching/match-customers.step.json, examples/reference-entity-model/steps/merging/merge-customers.step.json
=> DHFPROD-5977: Finished converting reference project

marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/conversion/FlowConverter.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/conversion/FlowConverterTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/conversion/FlowConverterUnitTest.java
=> DHFPROD-5978: Fixing flow conversion so flow fields are not lost

Jenkinsfile, marklogic-data-hub-glue-connector/build.gradle
Archiving and running tests
Adding Publish task
```diff
```
=> DHFPROD-5966: Build,Run tests and publish

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractHubCentralTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/EntitySearchControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/exportSearchAsCSV.sjs, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
=> DHFPROD-5970: Fix CSV export test failures

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub-central/ui/e2e/hc-qa-project/flows/personXML.flow.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/input/xml/persons/first-name-double-metaphone1.xml, marklogic-data-hub-central/ui/e2e/hc-qa-project/input/xml/persons/first-name-double-metaphone2.xml, marklogic-data-hub-central/ui/e2e/hc-qa-project/input/xml/persons/first-name-synonym1.xml, marklogic-data-hub-central/ui/e2e/hc-qa-project/input/xml/persons/first-name-synonym2.xml, marklogic-data-hub-central/ui/e2e/hc-qa-project/input/xml/persons/ssn-match1.xml, marklogic-data-hub-central/ui/e2e/hc-qa-project/input/xml/persons/ssn-match2.xml, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/ingestion/loadPersonXML.step.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/mapping/mapPersonXML.step.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/matching/match-xml-person.step.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/merging/merge-xml-person.step.json, marklogic-data-hub-central/ui/e2e/setup.sh, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/src/assets/mock-data/common.data.ts, marklogic-data-hub-central/ui/src/components/facet/facet.test.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.tsx, marklogic-data-hub-central/ui/src/components/xml-view/xml-view.test.tsx, marklogic-data-hub-central/ui/src/components/xml-view/xml-view.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx
=> DHFPROD-5863: Detail page renders merged xml documents

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.table.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.tsx
Also Includes DHFPROD-5323
```diff
```
=> DHFPROD-5878:Stop table scrolling in Explorer

marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx
=> DHFPROD-5605: Include the name of the mapping step in the confirmation

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/customIngestion.spec.tsx
Add e2e test for custom ingestion step
```diff
```
=> DHFPROD-5533:Add UI test for custom ingestion step

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/types/modeling-types.ts
=> DHFPROD-5923: Updated Relationship to Related Entities

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.module.scss, marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.module.scss, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub-central/ui/src/pages/Modeling.module.scss, marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx
Also includes tooltip updates to action icons (save, revert, trash) in entity type table and add to step in load list view. 
```diff
```
=> DHFPROD-5896: Inconsistent use of tooltips with delete icon

marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss
Includes DHFPROD-5603
```diff
```
=> DHFPROD-5596: Column selector icon should be right-aligned with the table.

marklogic-data-hub-central/src/main/resources/application.properties, marklogic-data-hub-central/ui/src/assets/mock-data/user-context-mock.ts, marklogic-data-hub-central/ui/src/components/modal-status/modal-status.tsx, marklogic-data-hub-central/ui/src/config/application.config.js, marklogic-data-hub-central/ui/src/util/user-context.tsx
=> DHFPROD-5962: Set default session timeout value to 10 minutes

marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx
- Load cards now ordered by last updated.
- Pointed for develop as story is marked for 5.3
```diff
```
=> DHFPROD-5608: Placement of new card in Load

marklogic-data-hub-central/ui/e2e/cypress/fixtures/curateTile/customUriHook.json, marklogic-data-hub-central/ui/e2e/cypress/fixtures/loadTile/addPrimaryKeyHook.json, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/advanced-settings-dialog.tsx, marklogic-data-hub-central/ui/e2e/hc-qa-project/src/main/ml-modules/root/custom-modules/ingestion/IngestOrders/addPrimaryKeyHook.sjs, marklogic-data-hub-central/ui/e2e/hc-qa-project/src/main/ml-modules/root/custom-modules/mapping/MapCustomers/customUriHook.sjs
Added e2e tests mapping and load steps having custom Hook.
```diff
```
=> DHFPROD-5531: Adding e2e test for mapping and load steps having custom Hook

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/runMapping.sjs
=> DHFPROD-5957: Add baseUri to XML entity instances

marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
=> DHFPROD-6005: Remove extra slash for the redirect test authorization.spec e2e.

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/CreateAndUpdateModelTest.java
=> DHFPROD-5915: Deploying search options when model is created

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/auth/AuthenticationFilter.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/auth/LoginFailureHandler.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/auth/LoginHandler.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/TestConstants.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/auth/AuthTest.java
If user can't read modules, return HTTP 403
```diff
```
=> DHFPROD-5940:If user can't read modules, return HTTP 403

marklogic-data-hub-central/ui/e2e/.gitignore, marklogic-data-hub-central/ui/e2e/cypress.json, marklogic-data-hub-central/ui/e2e/cypress/fixtures/roles/hc-custom-role.json, marklogic-data-hub-central/ui/e2e/cypress/integration/login/customRole.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/e2e/setup.sh
=> DHFPROD-5742: Add e2e custom roles test

marklogic-data-hub-central/ui/src/config/modeling.config.ts
Tests are N/A as this PR deals with updating a static list of data types. 
```diff
```
=> DHFPROD-5956: Move string to the top of property type list in Modeling

marklogic-data-hub-central/ui/e2e/cypress/fixtures/curateTile/customHeader.json, marklogic-data-hub-central/ui/e2e/cypress/fixtures/input/10260.json, marklogic-data-hub-central/ui/e2e/cypress/fixtures/loadTile/customHeader.json, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/advanced-settings-dialog.tsx
=> DHFPROD-5532: e2e test for load and map step with custom header

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataWriter.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/ingestion/bulkIngester.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/ingestion/BulkIngestTest.java
This pull request focuses on the changes needed for - https://project.marklogic.com/jira/browse/DHFPROD-5974
```diff
```
=> DHFPROD-5974: Ingest documents with user-defined prefix and guaranteed unique URI

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-match-merge-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-developer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-match-merge-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-match-merge-writer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-operator.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/security.sjs
also DHFPROD-4676: Create hub-central-match-merge-writer role
```diff
```
=> DHFPROD-4675: Create hub-central-match-merge-reader-role

marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/create-edit-matching-dialog/create-edit-matching-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/create-edit-matching-dialog/create-edit-matching-dialog.tsx
=> DHFPROD-5614: Confusing Placeholder Text in Mapping Modal

marklogic-data-hub/src/test/java/com/marklogic/bootstrap/TestAppInstaller.java
=> DHFPROD-5571: Added test security-admin user

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
=> DHFPROD-5621: Disabled 'Test' Button in curate turns purple on hover

marklogic-data-hub-spark-connector/build.gradle, marklogic-data-hub-spark-connector/gradle.properties, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataWriterFactory.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/AbstractSparkConnectorTest.java
- Assume DHS usage by default.
- Ability to run tests on DHS
- Running tests using gradle.
```diff
```
=> DHFPROD-5942: Assume DHS Usage by default.

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/util/authorities.tsx
Enabling the match tab in Curate tile. Small change so no test is required here. All the necessary tests will be added in match and merge related stories.
```diff
```
=> DHFPROD-6028: Enable match tab in the Curate tile.

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx
=> DHFPROD-6039: Fix for e2e Load CRUD test

NOTICE.txt
=> RC-2281: Adding the latest Notices.txt

marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployUserAmpsTest.java
Run DeployUserAmpsTest on servers >= 10.0-4.4
```diff
```
=> DHFPROD-6042:Run DeployUserAmpsTest on servers >= 10.0-4.4

marklogic-data-hub-central/ui/src/config/tooltips.config.js
=> DHFPROD-5560: Save Entity Text

marklogic-data-hub-central/ui/e2e/setup.sh
=> DHFPROD-6045: Deploy custom role as part of DHS e2e

marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-6053: Reduce number of entitySearch requests on zero state page.

marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
=> DHFPROD-6055: Fix failing e2e numeric/date facet test.

marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.module.scss, marklogic-data-hub-central/ui/src/pages/Modeling.tsx
Only updating icons in UI, so no tests required. 
```diff
```
=> DHFPROD-6026: Change database icon in modeling to regular save icon

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsTokenReplaceTest.java
=> DHFPROD-4809: Substitute tokens when loading user artifacts

marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/deploy/DeployHubAmpsCommand.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-security-admin.json, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployUserAmpsTest.java
Update amp with "data-hub-security-admin" on servers > 10.0-4.4
```diff
```
=> DHFPROD-5823: Update amp with "data-hub-security-admin" on servers > 10.0-4.4

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EntitySearchController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/EntitySearchControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/ReferenceModelProject.java
=> DHFPROD-5950: Exploring curated entities from staging and final databases

Jenkinsfile, marklogic-data-hub-central/ui/e2e/setup.sh
- Updated setup.sh script with two parameters for deploying project on DHS
```diff
```
=> DHFPROD-6058: Update setup.sh script for DHS

marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployUserAmpsTest.java
=> DHFPROD-5823: Tweaking test to avoid merge conflicts on rebase

marklogic-data-hub-central/ui/src/components/raw-data/raw-data-card-view/raw-data-card-view.module.scss, marklogic-data-hub-central/ui/src/components/raw-data/raw-data-card-view/raw-data-card-view.test.tsx, marklogic-data-hub-central/ui/src/components/raw-data/raw-data-card-view/raw-data-card-view.tsx, marklogic-data-hub-central/ui/src/components/search-bar/search-bar.module.scss, marklogic-data-hub-central/ui/src/components/search-bar/search-bar.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.module.scss, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
Creating just a dummy UI structure for explore all data feature, including the card view.
Added initial unit test for card view which will be modified in future.
```diff
```
=> DHFPROD-4731: Explore All Data

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/getPrimaryEntityTypes.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/models/GetPrimaryEntityTypesTest.java
View entity types in alphabetical order
```diff
```
=> DHFPROD-6060:View entity types in alphabetical order

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/SwaggerConfig.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MatchingStepController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MergingStepController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MatchingStepControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MergingStepControllerTest.java, marklogic-data-hub-central/ui/src/util/authorities.tsx, marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-read-match-merge.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-write-match-merge.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-match-merge-reader.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-match-merge-writer.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/getList.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/deleteStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/getStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/getStepsByType.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/saveStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/security.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/getAuthoritiesTest.sjs, specs/docs/security/DataHubSecurity.md, specs/models/AuthoritiesList.v1.json
=> DHFPROD-6057: CRUD match steps - Backend

marklogic-data-hub-central/ui/e2e/README.md, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
- Modified README with latest changes to ./setup.sh script
- Added fix for intermittent test failures on DHS
```diff
```
=> DHFPROD-6046: e2e fix for Explorer scenarios on DHS

marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx, marklogic-data-hub-central/ui/src/config/tiles.config.ts, marklogic-data-hub-central/ui/src/pages/TilesView.scss
Tile style update:
New border color: #BFBFBF
New border-radius: 2px
New control icon color: #777
Just CSS updates, no additional tests or test updates needed.
@jbelonoj has approved.
```diff
```
=> DHFPROD-6067: Update border and control icon styles for tiles

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.module.scss, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx
=> DHFPROD-5960: Update the blue hover menu for step cards

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/EntitySearchControllerTest.java
=> DHFPROD-6068: Bypass rangeQuery test for ML 10.0-3 and earlier

marklogic-data-hub-spark-connector/build.gradle, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataWriter.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataWriterFactory.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/AbstractSparkConnectorTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/Options.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataViaCustomEndpointTest.java, marklogic-data-hub-spark-connector/src/test/resources/custom-ingestion-endpoint/endpoint.api, marklogic-data-hub-spark-connector/src/test/resources/custom-ingestion-endpoint/endpoint.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/ingestion/bulkIngester.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/ingestion/BulkIngestTest.java
=> DHFPROD-5989: Configure workUnit and endpointState in Spark connector

marklogic-data-hub/src/main/resources/ml-modules/transforms/mlRunIngest.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/RunDefaultIngestionTest.java
Default to step 1 if flow name and step are not provided
```diff
```
=> DHFPROD-5537:Default to step 1 if flow name and step are not provided

marklogic-data-hub/build.gradle
I was initially going to do this for 5.4-develop, but it's such a trivial change that I think it's worth putting on develop. The unit tests all still pass, and this of course has no impact on any application functionality. 
```diff
```
=> DHFPROD-6071: Upgraded marklogic-unit-test to 1.0.0

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/RunFlowWithStemmingEnabledTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
Add test to run flow with stemming searches set to "advanced"
```diff
```
=> DHFPROD-5991:Add test to run flow with stemming searches set to advanced

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/api/facets.tsx, marklogic-data-hub-central/ui/src/api/queries.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/facet.js, marklogic-data-hub-central/ui/src/components/facet/facet.tsx, marklogic-data-hub-central/ui/src/components/numeric-facet/numeric-facet.test.tsx, marklogic-data-hub-central/ui/src/components/numeric-facet/numeric-facet.tsx, marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.test.tsx, marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.test.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.module.scss, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.test.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx
=> DHFPROD-5950: FE-Select database for exploring curated entities

marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx
=> DHFPROD-5891: Running a step collapses the expanded flow

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MergingStepController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MergingStepControllerTest.java
=> DHFPROD-6073: Middle-tier Endpoint For Default Mastering Collections

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
=> DHFPROD-6075: Fix date facet failing test on develop

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/flows.data.ts, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/pages/Curate.test.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx, marklogic-data-hub-central/ui/src/util/conversionFunctions.tsx
- Mapping Cards now sorted by last updated
- Modified RTL tests and test data to verify sorting
- Including small e2e fix for load CRUD intermittent failure
```diff
```
=> DHFPROD-6000: Placement of new card in Curate

marklogic-data-hub-central/ui/src/assets/mock-data/curation-context-mock.js, marklogic-data-hub-central/ui/src/assets/mock-data/merging.data.ts, marklogic-data-hub-central/ui/src/assets/mock-data/merging.js, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx
Creating a dummy structure for merge rule dialog with property selector mocked to Customer Entity. Only one field "Property" is available in this ticket. Other properties are being added as part of separate ticket.
```diff
```
=> DHFPROD-4390: Create merge rule form

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java
Save flow only if it's modified during hubUpdate
```diff
```
=> DHFPROD-6083:Save flow only if it's modified during hubUpdate

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataWriter.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataWriterFactory.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/BuildHubConfigTest.java
Also renamed "params" to "options" to be consistent with Spark
```diff
```
=> DHFPROD-5942: Added unit tests for building HubConfig

specs/models/DataHubEnvelope.schema.json
=> DHFPROD-5944: Adding the sourceType to the schema

Jenkinsfile
Using Java11+ as there is a bug with MLCP running on JAVA11
```diff
```
=> DHFPROD-5634: Using Java11+ to run tests on windows

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.json.tsx
=> DHFPROD-6075: Fix data facet test on develop

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/HubDataSource.java
=> DHFPROD-6056: Structured Streaming in Spark

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/IngestionStepController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MappingStepController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/StepService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/saveStep.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/saveStep.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/customStep/CreateAndUpdateCustomStepTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStandaloneStepTest.java
Allow removal of properties from step when loading from gradle
```diff
```
=> DHFPROD-6085:Allow removal of properties from step when loading from gradle

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/confirmation-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-modal.tsx
=> DHFPROD-6093: Modeling e2e test improvements

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/exceptions/DataHubException.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/managers/ModelManager.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateSearchOptions.sjs
=> DHFPROD-4732: Explore All Data

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.module.scss, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx, marklogic-data-hub-central/ui/src/types/curation-types.ts
Saves new ruleset to context only.
```diff
```
=> DHFPROD-5253: Add Zip, Exact, Reduce to Single Ruleset Matching Form

marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.scss, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx
=> DHFPROD-5230:Create scale component for matching and merging

marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.module.scss
=> DHFPROD-6031: Can't see the right side of the table

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ArtifactService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/clearUserArtifacts.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/clearUserArtifacts.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/ClearUserArtifactsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/ClearUserDataTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/ClearUserArtifactsTask.groovy
Clear user artifacts from DHF instance
```diff
```
=> DHFPROD-5999:Clear user artifacts from DHF instance

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/SwaggerConfig.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EntitySearchController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/transforms/hubAllDataSearchTransform.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addDocumentMetadataToSearchResults.sjs
=> DHFPROD-4659: Document metadata of the document to visualize in card view

marklogic-data-hub/src/test/java/com/marklogic/hub/legacy/flow/LegacyFlowManagerTest.java
=> DHFPROD-5634: Fix failing windows test

marklogic-data-hub-central/ui/src/assets/mock-data/curation-context-mock.js, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub-central/ui/src/types/curation-types.ts, marklogic-data-hub-central/ui/src/util/curation-context.tsx
=> DHFPROD-5254: Add Synonym Type to Single Ruleset Modal

marklogic-data-hub-central/ui/src/config/tiles.config.ts, marklogic-data-hub-central/ui/src/pages/Overview.tsx, marklogic-data-hub-central/ui/src/pages/Run.module.scss
In both Overview and the Run tile: "Add your step to a flow and run it."
Approved by @jbelonoj, no test updates needed.
```diff
```
=> DHFPROD-6011: Update Run intro text

marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub-central/ui/src/pages/Modeling.module.scss
```diff
```
- x N/A Tests
- x N/A Tests
=> DHFPROD-5560: Save Entities Text

examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DHFPROD-6128: Updating the versions to 5.3.0-rc2

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/src/components/expandable-table-view/expandable-table-view.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/search-bar/search-bar.test.tsx, marklogic-data-hub-central/ui/src/components/search-bar/search-bar.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
Just a fix for the bug described in the associated JIRA ticket. Also, contains fix for few e2e testing edge cases.
```diff
```
=> DHFPROD-6092: Fixing the issue where switching between all data to entity sometimes switches to all entities

marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
=> DHFPROD-6055: Fix for the e2e on develop 5.3

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx
=> DHFPROD-5975: Screen corruption after Select Flow on Load Screen

marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/AbstractSparkConnectorTest.java, marklogic-data-hub-spark-connector/src/test/resources/log4j.properties
=> DHFPROD-5988: Removed some terms

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.module.scss, marklogic-data-hub-central/ui/src/components/queries/queries.tsx
=> DHFPROD-6080:Save query button should be visible and disabled

marklogic-data-hub-api/build.gradle, marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle
Also bumped up ml-development-tools to 5.3.0 to match the Java Client
```diff
```
=> DHFPROD-6136: Upgraded to ml-gradle/app-deployer 4.1.0

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
Demo video https://drive.google.com/file/d/1_U7p5L4Ygit42Vi2tesrpvSfB07yFDgg/view
```diff
```
=> DHFPROD-5932: Change collapse/expand toggle behavior in mapping step details.

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/MappingController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/MappingControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MappingStepControllerTest.java, marklogic-data-hub-central/ui/src/assets/mock-data/common.data.ts, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/getMappingFunctions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/getXpathFunctionsThatDoNotWorkInMappingExpressions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getMappingFunctionsTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/getMappingFunctions.sjs
Function picker dropdown should be sorted in alphabetical order
```diff
```
=> DHFPROD-6117:Function picker dropdown should be sorted in alphabetical order

marklogic-data-hub-api/src/main/java/com/marklogic/hub/HubClientConfig.java, marklogic-data-hub-spark-connector/.gitignore, marklogic-data-hub-spark-connector/build.gradle, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/DefaultSource.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataWriter.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataWriterFactory.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/BuildHubClientConfigTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/bulkIngester.api, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/bulkIngester.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/ingestion/BulkIngestTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/TemporalWriteTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/lib/ingestionService.sjs
=> DHFPROD-6095: - Run connector against DHF 5.x

marklogic-data-hub/src/test/java/com/marklogic/hub/legacy/flow/LegacyFlowManagerTest.java
=> DHFPROD-5634: Fix failing test

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
=> DHFPROD-6127: Date facets replace the most recent selected facet, when still greyed out.

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/DefaultSource.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataWriter.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/Options.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataViaCustomEndpointTest.java, marklogic-data-hub-spark-connector/src/test/resources/custom-ingestion-endpoint/endpoint.api, marklogic-data-hub-spark-connector/src/test/resources/custom-ingestion-endpoint/endpoint.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/bulkIngester.api, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/bulkIngester.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/ingestion/BulkIngestTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/lib/ingestionService.sjs
=> DHFPROD-6051: The connector should point to java-client-api version 5.3

marklogic-data-hub-central/ui/src/components/entities/entity-tiles.module.scss, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.scss, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.test.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx
=> DHFPROD-6049: Confusion because operations don't apply to custom steps

marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataViaCustomEndpointTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataWithOptionsTest.java, marklogic-data-hub-spark-connector/src/test/resources/custom-ingestion-endpoint/endpoint.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/bulkIngester.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/TemporalWriteTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/ingestion/ingestionWithNullParams.sjs
=> DHFPROD-6095: Fixing Spark connector so it runs on DHF 5.2.x

marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.module.scss, marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.tsx
=> DHFPROD-6077: Guidance text in New Loading Step modal

marklogic-data-hub-central/ui/src/pages/Overview.test.tsx, marklogic-data-hub-central/ui/src/pages/Overview.tsx
=> DHFPROD-6125: Text correction in Intro Page

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/StepControllerTest.java, marklogic-data-hub-central/src/test/resources/test-projects/reference-project/steps/ingestion/firstLoadData.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/getStepsByType.sjs
View steps in alphabetical order in Add Step pulldown
```diff
```
=> DHFPROD-5892:View steps in alphabetical order in Add Step pulldown

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getMappingFunctionsTest.sjs
Print the functions array to debug random failure
```diff
```
=> DHFPROD-6117:Print the functions array to debug random failure

marklogic-data-hub-central/ui/src/components/detail-header/detail-header.tsx
- Fix for small bug that was responsible for Internal Server Error in cypress tests on 5.4
```diff
```
=> DHFPROD-6115: e2e test failures on 5.4-develop

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/DefaultSource.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/AbstractSparkConnectorTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/VerifyUserIsAuthorizedTest.java
=> DHFPROD-6151: Throwing nice error when credentials are invalid

Jenkinsfile
=> DHFPROD-6159: Fix QS Failures on pipelines

marklogic-data-hub-central/ui/src/assets/mock-data/curation/flows.data.ts, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Run.module.scss, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-4873: View loaded source data in Explorer after load step is run

marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/components/flows/flows.tsx
react-dropzone offers the same functionality and interaction as the previous file picker, so existing tests capture the scope of this ticket. 
```diff
```
=> DHFPROD-6131: Update file picker for running a Load step

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/DefaultSource.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteDataTest.java
=> DHFPROD-6153: Loading default Initialize and Finalize endpoints

marklogic-data-hub-central/ui/e2e/cypress/integration/explorer/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/tiles/tiles.module.scss, marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-6081: Make manage queries button more visible

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/double-metaphone.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/lib/lib.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/null-node-match.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/test-data/null-node.json
=> DHFPROD-6164: Null JSON node throws error in double metaphone match

marklogic-data-hub-central/ui/src/components/flows/flows.tsx
=> DHFPROD-6165:Rebase conflicts

marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/initializeJob.sjs
=> DHFPROD-6153: Adding the buildJobPermissions to initializeEndpoint

marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub-central/ui/src/types/curation-types.ts
=> DHFPROD-5256: Add Custom Match Type to Match Ruleset for 1 property form

marklogic-data-hub-api/src/testFixtures/java/com/marklogic/hub/test/TestObject.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/DefaultSource.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/Options.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteJobWithCustomEndpointsTest.java, marklogic-data-hub-spark-connector/src/test/resources/custom-job-endpoints/finalizeJob.api, marklogic-data-hub-spark-connector/src/test/resources/custom-job-endpoints/finalizeJob.sjs, marklogic-data-hub-spark-connector/src/test/resources/custom-job-endpoints/initializeJob.api, marklogic-data-hub-spark-connector/src/test/resources/custom-job-endpoints/initializeJob.sjs
=> DHFPROD-6161: User can now customize job endpoints

marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx
DHFPROD-5757: Ensure the flow panel scrolled upon adding a step to a flow in Run
- When the user adds a step from any interface, the flow panel is opened and scrolled to the right.
```diff
```
=> DHFPROD-5757:Ensure the flow panel scrolled upon adding a step to a flow in Run

marklogic-data-hub/src/main/resources/hub-internal-config/security/amps/amps-dhf-get-temporal-collections.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/temporal/hub-temporal.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/DeployDatabaseFieldCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/TemporalWriteTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/legacy/job/LegacyTracingTest.java, marklogic-data-hub/src/test/resources/test-projects/temporal-test/data/test.json, marklogic-data-hub/src/test/resources/test-projects/temporal-test/flows/temporal-test.flow.json, marklogic-data-hub/src/test/resources/test-projects/temporal-test/ml-config/databases/staging-database.json, marklogic-data-hub/src/test/resources/test-projects/temporal-test/ml-config/databases/staging-database/temporal/axes/temporal-system-axis.json, marklogic-data-hub/src/test/resources/test-projects/temporal-test/ml-config/databases/staging-database/temporal/collections/temporal-test.json, marklogic-data-hub/src/test/resources/test-projects/temporal-test/modules/root/custom-modules/custom/temporal-step/main.sjs, marklogic-data-hub/src/test/resources/test-projects/temporal-test/step-definitions/custom/temporal-test/temporal-test.step.json
Enable writing temporal documents in 5.2.x.
```diff
```
=> DHFPROD-6162:Enable writing temporal documents

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/dataservices/SparkService.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/DefaultSource.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataWriter.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataWriterFactory.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/Options.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/WriteJobsDataTest.java, marklogic-data-hub-spark-connector/src/test/resources/custom-job-endpoints/initializeJob.api, marklogic-data-hub-spark-connector/src/test/resources/custom-job-endpoints/initializeJob.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/initializeJob.api, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/initializeJob.sjs, specs/models/Job.schema.json
=> DHFPROD-6163:Add the AWS Glue job info in the job document.

Jenkinsfile
=> DHFPROD-6173: Testing on ML:10.0-5 and updating the target branches

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MatchingStepControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MergingStepControllerTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/setArtifact.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/mappingTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/matchingTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/mergingTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/test-data/entities/TestEntity-NoConfig.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/test-data/entities/TestEntity-hasConfig.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/lib/artifactService.sjs
=> DHFPROD-6132: Back-end changes to group matching/merging by entity

CHANGELOG.md, gradle.properties, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, ml-data-hub-plugin/gradle.properties, pipeline.properties, web/gradle.properties
```diff
```
- [NA] Squashed all commits into a single commit
=> DHFPROD-6177: Update version to Datahub 5.2.5

CHANGELOG.md
=> DHFPROD-6177: Updating the changelog for 5.2.5

marklogic-data-hub-central/ui/src/pages/Run.tsx
Don't rerender page when flow is run. I don't think this needs a test , I think manual test should suffice.
```diff
```
=> DHFPROD-5519:Don't rerender page when flow is run

marklogic-data-hub-api/build.gradle
=> DHFPROD-6181: Publish marklogic datahub api to nexus

marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/curation/create-edit-step-props.ts, marklogic-data-hub-central/ui/src/assets/mock-data/curation/curation-context-mock.js, marklogic-data-hub-central/ui/src/assets/mock-data/curation/merging.data.ts, marklogic-data-hub-central/ui/src/assets/mock-data/curation/merging.js, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/edit-merge-strategy-dialog/edit-merge-strategy-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/edit-merge-strategy-dialog/edit-merge-strategy-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/edit-merge-strategy-dialog/edit-merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub-central/ui/src/pages/TilesView.tsx, marklogic-data-hub-central/ui/src/types/curation-types.ts
=> DHFPROD-5246:Edit merge strategy && zero state page for merging step

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/pages/Load.test.tsx
=> DHFPROD-5606: Need consistency in edit icons

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
=> DHFPROD-6148: Hub properties grey facets are being removed when entity properties are selected.

marklogic-data-hub-central/ui/src/components/entities/create-edit-step-dialog/create-edit-step-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx
=> DHFPROD-6132: Create Match step with updated card UI

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/loadData.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/IngestWithSourceNameAndSourceTypeTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/convertIngestionStep.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/flow-utils/createHeaders.sjs
=> DHFPROD-5948: Add sourceName and sourceType parameters to OOTB load step

marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts, marklogic-data-hub-central/ui/src/assets/mock-data/curation/advanced-settings.data.ts, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs
After talking to @wooldridge, this doesn't have the end to end tests due to the work on ticket combining Basic and Advanced Settings (https://project.marklogic.com/jira/browse/DHFPROD-6037). I've created a task to follow up on that later. (https://project.marklogic.com/jira/browse/DHFPROD-6185)
```diff
```
=> DHFPROD-4330: Advanced Settings for Matching

marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.test.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx
=> DHFPROD-5604: Clarify hover text for apply and discard

marklogic-data-hub-central/ui/src/components/search-bar/search-bar.test.tsx, marklogic-data-hub-central/ui/src/components/search-bar/search-bar.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.test.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx
=> DHFPROD-5601: Improved hint text for Search

marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.tsx
=> DHFPROD-5245:Add Property-specific Merge Type to Merge Rule form

marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/ReferenceModelProject.java, performance-tests/README.md, performance-tests/build.gradle, performance-tests/gradle.properties, performance-tests/src/main/java/com/marklogic/hub/performance/CreateCustomers.java, performance-tests/src/main/resources/logback.xml, performance-tests/src/test/jmeter/invoke-manage-api.jmx, settings.gradle
Includes a task for creating N customers 
```diff
```
=> DHFPROD-6191: Initial performance project

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx, marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.module.scss, marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx
- Duplicate PR to https://github.com/marklogic/marklogic-data-hub/pull/4798 for develop
```diff
```
=> DHFPROD-5961: Add run icon and 'run in flow' menu to all the steps

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/detail-nonEntity.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/explore/Non-entity-document-payload.js, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.module.scss, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.test.tsx, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx, marklogic-data-hub-central/ui/src/components/table-view/table-view.module.scss, marklogic-data-hub-central/ui/src/components/table-view/table-view.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getRecord.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/getRecordTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/test-data/content/jane.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/test-data/content/jane.xml
Adding the new detail view for non-entity instance document(All Data option).
```diff
```
=> DHFPROD-4733: Navigate to the Detail view for JSON and XML documents

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/parseDate.sjs
=> DHFPROD-6192: Account for timezone in parseDate tests

marklogic-data-hub-central/ui/src/assets/mock-data/explore/Non-entity-document-payload.js, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.module.scss, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.test.tsx, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-5947: Navigate to the Detail view for Txt documents.

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/parseDate.sjs
=> DHFPROD-6192: 5.3.0-rc3 Account for timezone in parseDate tests

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/flow/getFlowWithLatestJobInfo.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job3.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job4.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job5.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/testGetFlowWithLatestJobInfo.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/testGetFlowsWithStepDetails.sjs
Ensure we can get latest job details if a step is added more than once to a flow
```diff
```
=> DHFPROD-6168:Ensure we can get latest job details if a step is added more than once to a flow

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.module.scss, marklogic-data-hub-central/ui/src/components/load/load-list.scss, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx
- Run step functionality in Load TABLE view
- Design has been verified by @jbelonoj 
- Will create a duplicate PR towards develop after this one is merged
```diff
```
=> DHFPROD-6099: Add run icon and 'run in flow' menu to Load TABLE view

examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
```diff
```
- [ NA] Added Tests
- [ NA] Reviewed Tests
=> DHFPROD-6208: Update the versions to 5.3.0-rc3

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.module.scss, marklogic-data-hub-central/ui/src/components/load/load-list.scss, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx
- Duplicate PR to https://github.com/marklogic/marklogic-data-hub/pull/4822 made for develop branch
```diff
```
=> DHFPROD-6099: (develop) Add run icon and 'run in flow' menu to Load Table view

marklogic-data-hub-api/src/main/java/com/marklogic/hub/MarkLogicVersion.java, marklogic-data-hub-api/src/testFixtures/java/com/marklogic/hub/test/ReferenceModelProject.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadSimpleCustomersTest.java
Moved MarkLogicVersion into API project so that Spark can use it. 
```diff
```
=> DHFPROD-5912: Fixing Spark read tests on 5.2.x

CODEOWNERS
Added entries for performance-tests and Spark project
```diff
```
=> DHFPROD-6191: Update to CODEOWNERS

marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/AbstractSparkConnectorTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/HandleAbortedWriterTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/HandleFailedWriteTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/WriteJobWithCustomEndpointsTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/WriteJobsDataTest.java, marklogic-data-hub-spark-connector/src/test/resources/custom-job-endpoints/finalizeWrite.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/finalizeWrite.sjs
Catch and log error if updating job doc fails
```diff
```
=> DHFPROD-6217:Catch and log error if updating job doc fails

marklogic-data-hub-central/ui/src/pages/Browse.tsx
No need for tests as we do not test for order in the UI. 
```diff
```
=> DHFPROD-5642: Inconsistent order of table/snippet buttons/icons

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/config/messages.config.ts
Recognize errors in Target Permissions on field blur
```diff
```
=> DHFPROD-6194:Recognize errors in Target Permissions on field blur

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step-dialog/create-edit-step-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/create-edit-step-dialog/create-edit-step-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step-dialog/create-edit-step-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/custom/view-custom-dialog/view-custom-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping-dialog/create-edit-mapping-dialog.tsx, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx, marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/load/new-load-dialog/new-load-dialog.tsx, marklogic-data-hub-central/ui/src/components/login-form/login-form.test.tsx, marklogic-data-hub-central/ui/src/components/login-form/login-form.tsx
=> DHFPROD-5613: fixed save button consistency

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/confirmation-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/create-edit-step-dialog.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/index.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/types/modeling-types.ts, marklogic-data-hub-central/ui/src/assets/mock-data/curation/merging.js, marklogic-data-hub-central/ui/src/components/entities/create-edit-step-dialog/create-edit-step-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/create-edit-step-dialog/create-edit-step-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step-dialog/create-edit-step-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js
CRUD functionality for merge steps. Added the relevant test cases.
```diff
```
=> DHFPROD-4328: CRUD Merge Step

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/matching.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/merging.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/security.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/CreateStepTest.java
Create match and merge step in the new format by default
```diff
```
=> DHFPROD-6244:Create match and merge step in the new format by default

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/src/api/matching.ts, marklogic-data-hub-central/ui/src/assets/mock-data/curation/curation-context-mock.js, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.scss, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.tsx, marklogic-data-hub-central/ui/src/types/curation-types.ts, marklogic-data-hub-central/ui/src/util/curation-context.tsx
=> DHFPROD-4315: CRUD Match Steps Thresholds

marklogic-data-hub-api/src/testFixtures/java/com/marklogic/hub/test/TestObject.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/reader/HubDataSourceReader.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/Options.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/AbstractSparkReadTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadSimpleCustomersTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadViaSerializedPlanTest.java, marklogic-data-hub-spark-connector/src/test/resources/serialized-plans/CustomerIdLessThanFive.json, marklogic-data-hub-spark-connector/src/test/resources/serialized-plans/GroupAndOrderByCustomerId.json, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/initializeRead.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/readLib.sjs
Extracted AbstractSparkReadTest to make it easier to write test classes for reading. 
```diff
```
=> DHFPROD-6175: Can now provide a serialized plan

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractHubCentralTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/CreateAndUpdateModelTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployDatabaseFieldCommand.java, marklogic-data-hub/src/main/resources/hub-internal-config/database-fields/staging-database.xml, marklogic-data-hub/src/main/resources/ml-config/database-fields/final-database.xml, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/DeployDatabaseFieldCommandTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/searchResultFacetsTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateSearchOptions.sjs, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/UpdateIndexesTaskTest.groovy, ml-data-hub-plugin/src/test/resources/update-indexes/final-database.xml, ml-data-hub-plugin/src/test/resources/update-indexes/staging-database.xml
=> DHFPROD-5984: Adding indexes to filter on sourceName and sourceType as hub facets

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/HubConfigImplTest.java
Run OOTB ml-gradle DMSDK tasks against Final db in DHS.
```diff
```
=> DHFPROD-6143:Run OOTB ml-gradle DMSDK tasks against Final db in DHS.

marklogic-data-hub-central/ui/src/components/facet/facet.module.scss, marklogic-data-hub-central/ui/src/components/facet/facet.test.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.test.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
=> DHFPROD-5595: Facet expand/collapse uses the wrong arrows

CONTRIBUTING.md
We don't want a PR out of the blue, so updated the CONTRIBUTING guide to recommend creating an issue first. 
```diff
```
=> DHFPROD-6019: Changing instructions for pull requests

marklogic-data-hub-central/ui/src/api/merging.ts, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/edit-merge-strategy-dialog/edit-merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js
=> DHFPROD-5235:Save merge rule

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
=> DHFPROD-6227: Explorer failing cypress tests.

marklogic-data-hub-spark-connector/gradle.properties
=> DHFPROD-6257: Updating the spark connector version to 2.4.5.0

marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx
=> DHFPROD-6174: added existing step confirmation in Run Tile

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/reader/HubDataSourceReader.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/Options.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadWithSelectedColumnsTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/initializeRead.api, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/initializeRead.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/readLib.sjs
=> DHFPROD-6198: Can now specify columns to select

marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/AbstractSparkReadTest.java
Check if server is nightly version first
```diff
```
=> DHFPROD-6262: Check if server is nightly version first

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/customIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/tiles.tsx
Just few e2e test fixes for mapping related failures.
```diff
```
=> DHFPROD-6212: Fixing few mapping related e2e tests on DHS

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/ingestion/loadCustomersJSON.step.json, marklogic-data-hub-central/ui/src/assets/mock-data/explore/facet-props.js, marklogic-data-hub-central/ui/src/components/facet/facet.test.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.tsx, marklogic-data-hub-central/ui/src/config/hub-properties.config.js
=> DHFPROD-5984: Filter on sourceName and sourceType as hub facets.

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStandaloneStepTest.java
=> DHFPROD-6269: Restoring deprecated FlowRunnerImpl constructor

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx
=> DHFPROD-6263: Modeling e2e test improvements

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
=> DHFPROD-5247:Delete merge rules

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
This reverts commit ba65a39e1243c3985460aee166b37dda05f5a72b.
```diff
```
=> DHFPROD-6227:Reverting the commit without JIRAID

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java
=> DHFPROD-6271: Temporary fix for final-database.xml

marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/WriteDataWithOptionsTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/writeLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/marklogic-data-hub-spark-connector/writeRecords/ingestOnlySourceName.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/marklogic-data-hub-spark-connector/writeRecords/ingestWithAllWorkUnitParams.sjs
=> DHFPROD-6275: Changes sources/name to datahubSourceName

marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/curation/common.data.ts, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/pages/Load.tsx, marklogic-data-hub-central/ui/src/util/loading-context.tsx
=> DHFPROD-6261: Page Size functionality for the Load List pagination is broken.

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/index.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/multi-slider.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/index.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/threshold-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.scss, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.tsx, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx
=> DHFPROD-5229: Save a match ruleset, DHFPROD-5250: Delete a match ruleset

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/advanced-settings.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/index.tsx, marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts, marklogic-data-hub-central/ui/src/assets/mock-data/curation/advanced-settings.data.ts, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-target-collections.module.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-target-collections.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/merging.sjs
E2E test video: https://drive.google.com/file/d/1pFzv8w20tVNNw-iNlORpJX4NUMiZo_t9/view?usp=sharing
```diff
```
=> DHFPROD-4331: Merge Step Advanced Settings

marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/AbstractSparkReadTest.java
=> DHFPROD-6262: Check if the version is 10.0-nightly or >=10.0-5

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/triggers/mapping/mappingJSONtoXML.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/MappingTest.java
Cleaned up mappingJSONtoXML a bit with better variable names, but main change is the addition of a try/catch. 
```diff
```
=> DHFPROD-4471: Improved error when mapping transform cannot be created

marklogic-data-hub-central/ui/e2e/cypress/support/components/common/tiles.tsx
- Added fix for ingestion/mapping cypress dhs failure on click 
- Verified locally on dhs instance
```diff
```
=> DHFPROD-6210: Fix test failures for ingestion/mapping e2e tests

marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/entitySearch/GetRecordTest.java
=> DHFPROD-6201: Test Fixes

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/api/matching.ts, marklogic-data-hub-central/ui/src/assets/mock-data/curation/matching.js, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
This PR adds the possible match combinations in match step details.
```diff
```
=> DHFPROD-4320: show possible match combinations in match step details

examples/reference-entity-model/steps/ingestion/loadCustomersJSON.step.json, examples/reference-entity-model/steps/ingestion/loadCustomersXML.step.json, examples/reference-entity-model/steps/ingestion/loadNamespacedCustomers.step.json, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MergingStepController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MergingStepControllerTest.java, marklogic-data-hub-central/ui/src/assets/mock-data/curation/merging.data.ts, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/edit-merge-strategy-dialog/edit-merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MappingService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MasteringService.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-match-merge-reader.json, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/calculateMergingActivity.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/calculateMergingActivity.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/calculateMergingActivityLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/calculateMergingActivity.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/test-data/content/matchSourceQuery.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/test-data/content/matchSourceQuery.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/test-data/content/notMatchSourceQuery.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/test-data/content/notMatchSourceQuery.xml
=> DHFPROD-6229: Dynamic source names for priority order

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/components/load/switch-view.scss, marklogic-data-hub-central/ui/src/components/load/switch-view.test.tsx, marklogic-data-hub-central/ui/src/components/load/switch-view.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.test.tsx, marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/config/hub-properties.config.js, marklogic-data-hub-central/ui/src/pages/Browse.test.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
DHFPROD-5599: Don't show pagination controls if 0 or 1 pages.
DHFPROD-6126: Radio Group Switcher Hover State.
DHFPROD-6287: source name and source type facets are rendered in incorect location.
```diff
```
=> DHFPROD-6167: Correct Column name Entity to Entity Type.

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/ingestion/ingest-orders.step.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/ingestion/loadCustomersXML.step.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/ingestion/loadPersonJSON.step.json, marklogic-data-hub-central/ui/src/assets/mock-data/explore/json-document-payload.js, marklogic-data-hub-central/ui/src/assets/mock-data/explore/search-payload-results.js, marklogic-data-hub-central/ui/src/components/detail-header/detail-header.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub/src/main/resources/hub-internal-config/database-fields/staging-database.xml, marklogic-data-hub/src/main/resources/ml-config/database-fields/final-database.xml, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/loadData.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/IngestWithSourceNameAndSourceTypeTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/searchResultFacetsTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/test-data/content/jane.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/test-data/content/jane.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/test-data/content/matchSourceQuery.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/test-data/content/matchSourceQuery.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/convertIngestionStep.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addDocumentMetadataToSearchResults.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/mergedJsonInstance.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/mergedXmlInstance.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/sally.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/sally.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/flow-utils/createHeaders.sjs
=> DHFPROD-6247: Add sourceName to records during ingestion and make it facetable

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/multi-slider.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx
=> DHFPROD-5249: Edit a match ruleset

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/ClearDatabaseTaskTest.groovy
Clear DHS database without breaking DHF
```diff
```
=> DHFPROD-6238:Clear DHS database without breaking DHF

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/mlcp-flow-transform.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/transforms/mlcp-transform/addSourceNameAndSourceType.sjs
=> DHFPROD-5949: Add sourceName and sourceType parameters to datahub MLCP transform

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.module.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.module.scss, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.test.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.module.scss, marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub-central/ui/src/pages/Load.test.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.module.scss, marklogic-data-hub-central/ui/src/pages/Modeling.tsx
=> DHFPROD-6065: Inconsistent/incorrect UI when no access

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/multi-slider.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/threshold-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.tsx
=> DHFPROD-6249: Edit matching threshold fixes

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/entityDrivenMerges.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-json/merge-deeply-nested.sjs
=> DHFPROD-6295: Fix JSON merges when all properties are merged in via XPath

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.tsx
- Automatically open step details after creating a mapping step.
```diff
```
=> DHFPROD-5439: Automatically open step details

CONTRIBUTING.md, examples/reference-entity-model/build.gradle, examples/reference-entity-model/lib/log4j.properties, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/dhf.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/flow-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/trace-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/xmlToJsonForMapping.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collector.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/http-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/step.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping-functions/core.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/rest-api/lib/extensions-util.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/mlcp-flow-transform.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/readLib.sjs, marklogic-data-hub/src/main/resources/ml-modules/services/mlStepValidate.sjs, marklogic-data-hub/src/main/resources/ml-modules/transforms/mlRunIngest.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/legacy/job/LegacyTracingTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/mappingTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/validateTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/manageFlow.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/manageMappingStep.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/step/makeFunction.sjs
=> DHFPROD-6283: Replacing fn.error calls with 400/404 errors

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/entitySearch/GetRecordTest.java
=> DHFPROD-6311: Adding console logs to debug GetRecordTest

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MatchingStepController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MatchingStepControllerTest.java, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/multi-slider.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/threshold-modal.tsx, marklogic-data-hub-central/ui/src/api/matching.ts, marklogic-data-hub-central/ui/src/assets/mock-data/curation/matching.js, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/calculateMatchingActivity.sjs
Adding possible match combinations for match step details page.
```diff
```
=> DHFPROD-4320: Show possible match combinations based on configuration

marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.test.tsx
Description in title. (Title edited 12/3/2020)
Also see first comment.
```diff
```
=> DHFPROD-5707: added focus style to MLButton component

build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat, marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateHubTDETemplateCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, ml-data-hub-plugin/build.gradle, web/build.gradle
=> DHFPROD-6304: Update the java client api to version 5.3.2

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/entitySearch/GetRecordTest.java
=> DHFPROD-6311: Fix for intermittently failing GetRecordTest

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/reader/HubDataSourceReader.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/reader/HubInputPartition.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/reader/HubInputPartitionReader.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/AbstractSparkConnectorTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/Options.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadWithCustomEndpointsTest.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/WriteJobWithCustomEndpointsTest.java, marklogic-data-hub-spark-connector/src/test/resources/custom-read-endpoints/customReadRows.api, marklogic-data-hub-spark-connector/src/test/resources/custom-read-endpoints/customReadRows.sjs, marklogic-data-hub-spark-connector/src/test/resources/custom-read-endpoints/initializeRead.api, marklogic-data-hub-spark-connector/src/test/resources/custom-read-endpoints/initializeRead.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/readRows.sjs
=> DHFPROD-6172: Customize Spark connector endpoints for reading rows

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx
=> DHFPROD-6320: Fix modeling e2e failures

marklogic-data-hub-central/ui/e2e/cypress/support/components/common/tiles.tsx
- Fix for cypress failures on Windows DHS, verified tests pass locally on VM.
```diff
```
=> DHFPROD-6210: Fix for failing ingestion/mapping tests on DHS

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/entityDrivenMatches.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/CustMatchNotify.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/NsCustMatchNotify.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/matching/matchCustomers.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/matching/matchNamespacedCustomers.step.json
=> DHFPROD-6292: Add full merged URIs to notify documents

marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.tsx
=> DHFPROD-5243: Merge rule strategies select dropdown

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx
=> DHFPROD-6232: Entity should be Entity Type in Map step details

examples/dh-5-example/src/main/java/org/example/RunFlowWithCustomHubConfig.java
Fix NPE in RunFlowWithCustomHubConfig in dh-5-example project
```diff
```
=> DHFPROD-6337:Fix NPE in RunFlowWithCustomHubConfig in dh-5-example project

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/function-extension/functional.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/sm-es-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/util.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/options.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/dhf.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/flow-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/trace-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-validate-trigger.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/http-utils.xqy, marklogic-data-hub/src/main/resources/ml-modules/services/mlFlow.xqy, marklogic-data-hub/src/main/resources/ml-modules/services/mlScaffoldContent.xqy, marklogic-data-hub/src/main/resources/ml-modules/services/mlSmHistoryDocument.xqy, marklogic-data-hub/src/main/resources/ml-modules/services/mlSmHistoryProperties.xqy, marklogic-data-hub/src/main/resources/ml-modules/services/mlSmNotifications.xqy, marklogic-data-hub/src/main/resources/ml-modules/transforms/mlInputFlow.xqy, marklogic-data-hub/src/main/resources/ml-modules/transforms/mlRunFlow.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/models/insertInvalidEntityModel.sjs
Throw 4xx error when using fn:error if appropriate
```diff
```
=> DHFPROD-6284:Throw 4xx error when using fn:error if appropriate

marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.test.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx
=> DHFPROD-6296: Make pagination hiding consistent across all views that have it.

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-operator.json, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubSecurityAdminTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/RedactionUserTest.java, marklogic-data-hub/src/test/resources/test-projects/redaction-test/flows/redaction-test.flow.json, marklogic-data-hub/src/test/resources/test-projects/redaction-test/ml-config/databases/data-hub-staging-SCHEMAS/schemas/collections.properties, marklogic-data-hub/src/test/resources/test-projects/redaction-test/ml-config/databases/data-hub-staging-SCHEMAS/schemas/redact-rule.json, marklogic-data-hub/src/test/resources/test-projects/redaction-test/modules/root/custom-modules/custom/redaction-step/main.sjs, marklogic-data-hub/src/test/resources/test-projects/redaction-test/step-definitions/custom/redaction-test/redaction-test.step.json, marklogic-data-hub/src/test/resources/test-projects/redaction-test/steps/custom/redact-phone.step.json
=> DHFPROD-6297: Add redaction privilege to roles

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/base.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/zip.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/matching/matchCustomers.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/matching/matchNamespacedCustomers.step.json
=> DHFPROD-6323: Fix zip match function for HC step

examples/README.md, examples/mapping-example/gradle/wrapper/gradle-wrapper.properties
Made it clear how to obtain a local copy of the DH Gradle plugin. 
```diff
```
=> DHFPROD-6340: Updated example projects README

marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/add-merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.module.scss, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.module.scss, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/pages/Detail.module.scss, marklogic-data-hub-central/ui/src/pages/Detail.tsx
- no tests as this deals with updating existing icons.
- also removes some unused variables to get eslint to pass.
```diff
```
=> DHFPROD-6032: Incorrect icon for JSON source

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
=> DHFPROD-6318: Intermittent Cypress test failure

CHANGELOG.md
=> DHFPROD-6344:Update CHANGELOG.md for version 5.2.6

gradle.properties, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, ml-data-hub-plugin/gradle.properties, web/gradle.properties
=> DHFPROD-6344:Update to version 5.2.6

marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/src/util/user-context.tsx
=> DHFPROD-5726: fix login/logout redirect

marklogic-data-hub-central/ui/src/components/flows/flows.tsx
- Short fix for conditional statement that was causing an error
- No tests added as coverage already exists for the scenarios
```diff
```
=> DHFPROD-6339: Adding/Running a step to a new flow crashes the app

examples/reference-entity-model/steps/matching/match-customers.step.json, examples/reference-entity-model/steps/merging/merge-customers.step.json, marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/conversion/FlowConverter.java, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/util.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/options-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/options.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/conversion/FlowConverterUnitTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/util.sjs
=> DHFPROD-6319: Use targetEntityType in new match/merge steps

marklogic-data-hub/src/test/java/com/marklogic/hub/security/RedactionUserTest.java
- Fixes test failures on 9.0-11
```diff
```
=> DHFPROD-6297: Add isVersionCompatibleWith520Roles check for hc roles

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/step.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/CustomStepE2E.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/step/makeFunction.sjs, marklogic-data-hub/src/test/resources/mapping-test/flows/Admissions.flow.json
Provide info when main.sjs is not found or user doesn't required permissions
```diff
```
=> DHFPROD-4947:Provide info when main.sjs is not found or user doesn't required permissions

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/ModuleWriter.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/reader/HubDataSourceReader.java, marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/writer/HubDataSourceWriter.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadModulesWrittenToModulesDatabaseTest.java
=> DHFPROD-6274: Install Spark modules for reading if not present

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/database-fields/staging-database.xml, marklogic-data-hub/src/main/resources/ml-config/database-fields/final-database.xml, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/merging.sjs, marklogic-data-hub/src/test/resources/upgrade-projects/dhf43x/key/final-database.xml, ml-data-hub-plugin/src/test/resources/update-indexes/final-database.xml, ml-data-hub-plugin/src/test/resources/update-indexes/staging-database.xml
```diff
```
-  N/A Reviewed Tests
=> DHFPROD-6216: Optimize match summary range index

.github/PULL_REQUEST_TEMPLATE.md
=> DHFPROD-6343: Added ESLint Checkbox

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/entitySearch/GetRecordTest.java, marklogic-data-hub/src/test/resources/test-projects/provenance-test/flows/inline.flow.json
Mapping step fails when provenance is set to "fine"
```diff
```
=> DHFPROD-6231:Mapping step fails when provenance is set to "fine"

marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/custom/view-custom/view-custom.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.tsx, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.test.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js
=> DHFPROD-6309: Add a tooltip for a disabled name field on edit step and edit flow

marklogic-data-hub-api/build.gradle, marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle
Brings marklogic-client-api 5.3.2 along
```diff
```
=> DHFPROD-6350: Upgrading ml-gradle/app-deployer to 4.1.1

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMatchOptionsLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/updateMatchOptions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/secondAction.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/matching/matchCustomers.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/matching/matchNamespacedCustomers.step.json
=> DHFPROD-6326: Fix custom action match step migration

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/query/manage-queries-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.test.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/discard-changes/discard-changes-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx, marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx, marklogic-data-hub-central/ui/src/pages/Browse.test.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx, marklogic-data-hub-central/ui/src/types/query-types.ts, marklogic-data-hub-central/ui/src/util/search-context.tsx
Fixing the bugs mentioned in the ticket DHFPROD-6002 and DHFPROD-6347.
```diff
```
=> DHFPROD-6002: Refactoring manage query component to be available in Explore tile header

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.scss, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx
=> DHFPROD-6299:View number scale for slider components in match

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.module.scss, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.tsx
=> DHFPROD-6276: Update card footer icons

marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.test.tsx, marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.tsx
Just a label change.
```diff
```
=> DHFPROD-6079: Updating "Search" label under facets

marklogic-data-hub-central/ui/src/api/record.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/explore/Non-entity-document-payload.js, marklogic-data-hub-central/ui/src/assets/mock-data/explore/entity-search.js, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.module.scss, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.test.tsx, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.module.scss, marklogic-data-hub-central/ui/src/components/record-view/record-view.test.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addDocumentMetadataToSearchResults.sjs
=> DHFPROD-6332: FE Implementation: Download a record or artifact from All Data View.

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/xquery-lib.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/runEmptyMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/runMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/mappings/CustomerMapping/CustomerMapping-1.mapping.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/mappings/OrdersMapping/OrdersMapping-4.mapping.json
Remove '$ref' from empty entity instance
```diff
```
=> DHFPROD-6219:Remove '$ref' from empty entity instance

marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
Added encryption to the class attributes in HTML for the Entity Model table.
```diff
```
=> DHFPROD-6280: Spike: Check and remove user data in the class attribute in HTML.

marklogic-data-hub-api/src/testFixtures/java/com/marklogic/hub/test/AbstractHubClientTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
=> DHFPROD-6359: Fix ML9 cluster regression in MasterTest

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployDatabaseFieldCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/DeployDatabaseFieldCommandTest.java
=> DHFPROD-6356: Fixing bug when jobs database has existing path namespaces

marklogic-data-hub-api/src/testFixtures/java/com/marklogic/hub/test/AbstractHubClientTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
=> DHFPROD-6354: Fixing bug with failedEvents value

examples/dhs-example/README.md, examples/dhs-example/src/main/ml-config/databases/data-hub-FINAL/temporal/collections/lsqt/temporal-collection.json, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-temporal-user.json, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubSecurityAdminTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/temporal-operations/suiteSetup.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/temporal-operations/suiteTeardown.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/temporal-operations/temporalOperationsTest.sjs
=> DHFPROD-6298: Add temporal privileges to roles

marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/pages/Curate.tsx
This can be tested by running the matching step from the matching card and seeing the results in query console
```diff
```
=> DHFPROD-4382: Add matching step to flow

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
=> DHFPROD-6352: Error thrown when creating a mapping

Jenkinsfile
=> DEVO-110:Update DHF Develop pipeline to include palamida scan

marklogic-data-hub-central/ui/src/config/tooltips.config.js
Also tweaked the language a bit to make it more clear what the time value represents. 
```diff
```
=> DHFPROD-6371: Fixed typo in Last Processed tooltip

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/IngestionStepControllerTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/default/main.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/verifyHeaders.sjs
'createdOn' and 'createdBy' in mapped documents are incorrect
```diff
```
=> DHFPROD-6241:'createdOn' and 'createdBy' in mapped documents are incorrect

marklogic-data-hub/src/main/resources/scaffolding/build_gradle
Manually tested this by changing the version to 5.2.x. A snapshot version can't be tested because that would require a buildscript - but we don't want to complicate this with a buildscript, which most users would rarely ever need. 
```diff
```
=> DHFPROD-6345: Updated build_gradle file

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getRecord.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/entitySearch/GetRecordTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/getMissingRecord.sjs
=> DHFPROD-6368: Throwing 404 when record cannot be found

marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx
e2e testing for running match and merge steps will be added in the subtask DHFPROD-6373
```diff
```
=> DHFPROD-4548: Add merging step to flow

Jenkinsfile
=> DEVO-144:Cleanup Jenkins workspace before flexcode scan

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/customStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/loadData.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mapping.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/stepDefinition.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/mappingTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/validateTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/saveInvalidStep.sjs
=> DHFPROD-6377: Invalid artifact message now includes artifact name

marklogic-data-hub-central/ui/e2e/hc-qa-project/flows/CurateClientJSON.flow.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/flows/CurateCustomerJSON.flow.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/flows/CurateCustomerXML.flow.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/flows/convertedFlow.flow.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/flows/personJSON.flow.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/flows/personXML.flow.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/flows/testCustomFlow.flow.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/src/main/ml-modules/root/custom-modules/custom/dob-match.xqy, marklogic-data-hub-central/ui/e2e/hc-qa-project/src/main/ml-modules/root/custom-modules/custom/dob-merge.sjs, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/matching/match-person.step.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/matching/match-xml-person.step.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/merging/merge-person.step.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/merging/merge-xml-person.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMatchOptionsLib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMergeOptionsLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/updateMatchOptions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/updateMergeOptions.sjs
=> DHFPROD-6360: Convert match/merge steps in QA project

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/StepControllerTest.java, marklogic-data-hub-central/src/test/resources/test-projects/reference-project/steps/custom/collectionAdder.step.json, marklogic-data-hub-central/src/test/resources/test-projects/reference-project/steps/mastering/master-person.step.json, marklogic-data-hub-central/src/test/resources/test-projects/reference-project/steps/matching/match-customers.step.json, marklogic-data-hub-central/src/test/resources/test-projects/reference-project/steps/merging/merge-customers.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/getStepsByType.sjs
=> DHFPROD-6357: Return all user-defined steps

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/expandable-table-view/expandable-table-view.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx
=> DHFPROD-6364: Database selection is not shown in UI when navigated from instance view to All Entities view.

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/sql/sources/v2/reader/HubInputPartitionReader.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/Options.java, marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadWithCustomOptimizationlevel.java, marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/readRows.sjs
=> DHFPROD-6205: Customize Optic optimization level via Spark connector

marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/components/tiles/tiles.module.scss, marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx
See comment for full list of buttons affected by this PR.
```diff
```
=> DHFPROD-5652: added focus and focus indicator to close buttons

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/temporal-operations/temporalOperationsTest.sjs
=> DHFPROD-6298: Add "set LSQT automation" priv to dh-developer role

marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.scss
Simple CSS fix. No test needed. 
```diff
```
=> DHFPROD-6353: Source properties not visible in mapping UI

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-curator.json
=> DHFPROD-6335: hub-central-curator cannot see matching and merging steps

Jenkinsfile
=> DEVO-147:Temporarly avoid FlexCode scan failure

marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.scss, marklogic-data-hub-central/ui/src/components/steps/steps.test.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.js, marklogic-data-hub-central/ui/src/pages/Load.test.tsx
=> DHFPROD-6310: Add tooltip for a disabled tab on Step Settings screens

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/AddMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/AddMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.test.tsx
=> DHFPROD-6373: Cypress e2e test for Creating and Running Match/Merge steps

build.gradle, examples/README.md, examples/snapshot-testing/.gitignore, examples/snapshot-testing/README.md, examples/snapshot-testing/build.gradle
=> DHFPROD-6389: New snapshot-testing example project

marklogic-data-hub-spark-connector/gradle.properties
=> DHFPROD-6388: Updating the spark version to 1.0-snapshot

marklogic-data-hub-spark-connector/gradle.properties
=> DHFPROD-6388: Updating the version to spark 1.0.0-rc1

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EnvironmentController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/environment/DownloadProjectFilesMvcTest.java, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/projectInfo.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.module.scss, marklogic-data-hub-central/ui/src/components/header/system-info.test.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/HubCentralManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/AllArtifactsProject.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/ApplyDownloadedZipToProjectTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/GetHubCentralFilesAsZipTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/GetProjectAsZipTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/ClearUserDataTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/PullConfigurationFilesTask.groovy
Download project zip from HC
```diff
```
=> DHFPROD-5935:Download project zip from HC

marklogic-data-hub-central/ui/src/api/record.tsx, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.scss, marklogic-data-hub-central/ui/src/components/record-view/record-view.test.tsx
=> DHFPROD-6367: Document with encoded URI cannot be downloaded.

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-trigger.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/test-data/entities/Entity1.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/test-data/entities/Entity2.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/test-data/entities/Entity3.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/testTdeGenerationDisabled.sjs
Disable generation of TDE for entity models
```diff
```
=> DHFPROD-6149:Disable generation of TDE for entity models

CONTRIBUTING.md
=> DHFPROD-6410: Updated Gradle version in contributing guide

marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/HubCentralManager.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/GetProjectAsZipTest.java
Replace tokens in gradle.properties file
```diff
```
=> DHFPROD-5935:Replace tokens in gradle.properties file

examples/README.md, examples/dh-5-example/README.md, examples/dhf5-custom-hook/README.md, examples/insurance/README.md, examples/mapping-example/README.md, examples/patient-hub/README.md, examples/reference-entity-model/README.md, examples/smart-mastering-complete/README.md, examples/step-processors/README.md
Added text for users that wish to use a snapshot version of DHF
```diff
```
=> DHFPROD-6180: Updated README for example projects

web/build.gradle
=> DHFPROD-6423: building UI for the build task

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/helper-impl.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/reduce/lib/reduceTestLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/reduce/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/reduce/test-data/content/JaneTurnerSameStreet.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/reduce/test-data/entities/ReducePerson.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/reduce/testLegacyReduce.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/reduce/testReduce.sjs
Also tweaked some trace logging - xdmp:to-json-string seems more useful, as it produces a JSON string that can then be easily copied/pasted into an editor and formatted for analysis. 
```diff
```
=> DHFPROD-6327: Fixing unconverted reduce matcher

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.tsx
Added null/undefined check for thresholds and rulesets.
```diff
```
=> DHFPROD-6436: Blank screen when editing matching step details

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/util.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/helper-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/options-impl.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java, marklogic-data-hub/src/test/resources/master-test/flows/myNewFlow.flow.json
=> DHFPROD-6385: Optimize top-level value retrieval for matching

marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.test.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx
=> DHFPROD-6435: Preserve the collection when editing match/merge steps

marklogic-data-hub/src/main/java/com/marklogic/hub/error/DataHubSecurityNotInstalledException.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/core/DataHubInstallTest.java
=> DHFPROD-6419: Better error message when hubUpdate fails

marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx
=> DHFPROD-6416: Property to match field does not clear

gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/gradle.properties
=> DEVO-155: Setting up JVM props

examples/dh-5-example/README.md
=> DHFPROD-5395: Better instructions in dh-5-example project

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
Added a fix for this bug to refresh the query list in the dropdown properly.
```diff
```
=> DHFPROD-6452: Fix for the issue where query name persists in the select query dropdown even after deleting it

marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.scss, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
=> DHFPROD-6390:Make the slider in Merge step view-only.

marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
=> DHFPROD-6426: Incorrect configuration for reduce rule from HC

marklogic-data-hub-central/ui/src/components/header/system-info.test.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.tsx
Update the text for downloading hub central and project files
```diff
```
=> DHFPROD-5935:Update the text for downloading hub central and project files

marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/src/main/resources/application.properties
I couldn't reproduce the issue locally, but this seems to be the fix based on Spring Boot docs and others reporting the same issue. Won't know for sure until we can test within a DHS instance. 
```diff
```
=> DHFPROD-6379: Fixing HC redirects when receiving HTTPS request

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
=> DHFPROD-6488: Remove dropdown menu for adding a single ruleset

examples/dhf5-custom-hook/src/main/ml-modules/root/custom-modules/ingestion/IngestOrders/archive-hook.sjs
```diff
```
- [done] JIRA_ID included in all the commit messages
- [done] PR title is in the format JIRA_ID:Title
- [?] Rebase the branch with upstream
- [n/a] Squashed all commits into a single commit
- [n/a] Code passes ESLint tests
=> DHFPROD-6365: Updated comments in the example.

marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
=> DHFPROD-6483: Cypress e2e tests consistently fail on authorization test

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx
- Commenting out flaky RTL test for now as it we cannot reproduce it and it is blocking regressions.
```diff
```
=> DHFPROD-6495: Mapping RTL test failing intermittently

marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/Client.entity.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/Customer.entity.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/Person.entity.json, marklogic-data-hub/src/main/resources/hub-internal-artifacts/step-definitions/merging/marklogic/default-merging.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/helper-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/matching.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/merging.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/CreateStepTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/mergingTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/helper/property-name-to-query.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/helper/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/helper/test-data/entities/MasteringTestEntity.entity.json, marklogic-data-hub/src/test/resources/test-config/databases/final-database.json
=> DHFPROD-6385: Match query optimizations

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
Exposed the link to explorer on merge step run confirmation modal.
```diff
```
=> DHFPROD-4422: After merge step is run, I can easily view my results in Explorer

marklogic-data-hub-spark-connector/src/main/java/com/marklogic/hub/spark/dataservices/SparkService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MasteringService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/SecurityService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/util/JacksonUtil.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-user-reader.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/security/describeRole.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/security/describeRole.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/security/describeUser.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/security/describeUser.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/security/service.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/security/describe-lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/TestAppInstaller.java, marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/security/DescribeUserAndRoleTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubSecurityAdminTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/util/JacksonUtilTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/lib/securityService.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/security/describeRoleTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/security/describeUserTest.sjs, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/DescribeRoleTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/DescribeUserTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/PrintInheritableRolesTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/hub/gradle/task/DescribeRoleTaskTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/hub/gradle/task/DescribeUserTaskTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/hub/gradle/task/PrintInheritableRolesTaskTest.groovy
Also includes some comment updates to DS-generated interfaces. 
```diff
```
=> DHFPROD-6450: New Gradle tasks for describing users and roles

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/src/config/formats.config.js
=> DHFPROD-6376: added clarification to format options in load step

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
=> DHFPROD-6500: Fix failing runFlow tests on develop.

marklogic-data-hub-spark-connector/build.gradle
=> DHFPROD-6463: AWS Glue: Exception occurs while ingesting documents using the connector jar

marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx
=> DHFPROD-6466: Removed sort and facet for structured properties

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/PullChangesTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/hub/gradle/task/PullChangesTaskTest.groovy
=> DHFPROD-6503: Renaming task to hubPullChanges

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMatchOptionsLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/updateMatchOptions.sjs
=> DHFPROD-6499: Adjust match step Hub Central conversions to 0-100 scale

marklogic-data-hub-spark-connector/gradle.properties
=> DHFPROD-6510: Updating the version 1.0.0-rc2

marklogic-data-hub-spark-connector/build.gradle
=> DHFPROD-6463: Fixing the build issues

Jenkinsfile
=> DEVO-110: Update DHF Develop pipeline to include palamida scan

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/options-impl.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/match-rule-to-full-property-name.xqy
=> DHFPROD-6385: Fix runaway XPath expression in compile match options

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommandTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/artifactNameValidationTest.sjs
Add validation to step, stepdef and flow names in gradle task
```diff
```
=> DHFPROD-6490:Add validation to step, stepdef and flow names in gradle task

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployQueryOptionsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/installer/deploy/CopyQueryOptionsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/EntityManagerImpl.java, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/TestAppInstaller.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/DeployQueryOptionsCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/entity/EntityManagerTest.java
=> DHFPROD-6474: Generating and Deploying search options during datahub deployment

marklogic-data-hub-central/ui/src/components/header/system-info.module.scss, marklogic-data-hub-central/ui/src/components/header/system-info.test.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.tsx
…within the Info modal
```diff
```
=> DHFPROD-6428: Download/Clear buttons not greyed out in disabled mode within the Info modal

marklogic-data-hub-central/ui/src/assets/mock-data/curation/steps.data.ts, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-target-collections.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.test.tsx
- Test creation of all step types in steps/steps.test
- Distinguish different coarse-granularity possibilities for steps in test data
- Test for Advanced Target Collections table presence for Merging step
```diff
```
=> DHFPROD-6517: Update step settings tests

marklogic-data-hub/src/test/java/com/marklogic/hub/impl/ClearUserModulesTest.java
=> DHFPROD-6474: Fixing Intermittent ClearUserModulesTest Failure

marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx
=> DHFPROD-6446: fixed missing entity link in Run tile

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/StepDefinitionManagerImpl.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateFlowTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateStepDefinitionTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateFlowTaskTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateStepDefinitionTaskTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/CreateStepTaskTest.groovy
Don't write artifacts to project unless you can write it to db
```diff
```
=> DHFPROD-6490:Don't write artifacts to project unless you can write it to db

examples/reference-entity-model/steps/matching/match-customers.step.json, examples/reference-entity-model/steps/merging/merge-customers.step.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/matching/match-person.step.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/matching/match-xml-person.step.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/merging/merge-person.step.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/merging/merge-xml-person.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/getDefaultCollections.sjs
Fix 'targetEntityType' for match and merge steps
```diff
```
=> DHFPROD-6514:Fix 'targetEntityType' for match and merge steps

marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.test.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.tsx, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx
- Follow-up PR to address some issues caught in QA from @srinathgit 
- On special characters error in name field, save button should not submit but remain enabled
- Spaces should not be allowed in name field
```diff
```
=> DHFPROD-6454: Add validation to step and flow names in Hub Central

marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/pages/Load.tsx
=> DHFPROD-6528: Unable to find Source Records error when updating XPATH

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.tsx
We will revisit any test scenarios for this bug in a separate mini-hardening, in the interest of time. Just the fix for the bug is included in this PR.
```diff
```
=> DHFPROD-6531: Mapping properties from first mapping pre-populated on all other mappings

examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DEVO-158:Datahub 5.4.0 beta release

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.module.scss, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.test.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx, marklogic-data-hub-central/ui/src/components/sidebar-footer/sidebar-footer.module.scss, marklogic-data-hub-central/ui/src/components/sidebar-footer/sidebar-footer.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-6383: Make applying facets in explorer more clear

marklogic-data-hub-central/ui/src/components/date-time-facet/date-time-facet.tsx
This is just an ant design component implementation fix. No tests are required here.
```diff
```
=> DHFPROD-6455: Resolved the issue where Date time component (Ant Design) was fixed to the body element

marklogic-data-hub-central/ui/src/components/column-selector/column-selector.tsx, marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx, marklogic-data-hub-central/ui/src/components/expandable-table-view/expandable-table-view.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/header/header.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/query-export/export-preview/export-preview.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/components/table-view/table-view.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx, marklogic-data-hub-central/ui/src/pages/Curate.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/util/data-conversion.tsx
=> DHFPROD-6408: fixed several console warnings when launching DataHub

marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-6394: Update disabled tab tooltip 

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.queries.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.test.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-6442: Select query dropdown looks misaligned in card view

marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.module.scss, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.scss, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.test.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
Note to reviewers: please check positioning of the question icons in more than one browser. The CSS is very subjective so if you notice it's off in any way, let me know.
```diff
```
=> DHFPROD-6443: Make Collection and Query more clear when defining curation steps 

marklogic-data-hub-central/ui/src/components/modal-status/modal-status.tsx, marklogic-data-hub-central/ui/src/components/navigation-prompt/navigation-prompt.tsx
=> DHFPROD-6459: Autologout fixes

examples/smart-mastering-complete/src/main/ml-modules/root/custom-modules/custom/dob-match.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/options-impl.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/custom-xqy-matching-algo.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/lib/lib.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/test-data/custom-xqy-matching-algo-dob-options.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/test-data/custom-xqy-matching-algo-dob.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/test-data/dob1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/test-data/dob2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/test-data/entities/Person.entity.json
=> DHFPROD-6329: Unconverted custom match action fails

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.module.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx
=> DHFPROD-6400: fixed dialog layout rendering bug when tabbing in load and mapping forms

marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.test.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx
=> DHFPROD-6529: Auto suggestion fix for create-edit-step component

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
=> DHFPROD-6552: Fix unique key warning for match combinations

examples/smart-mastering-complete/src/main/ml-modules/root/custom-modules/custom/dob-match.xqy
=> DHFPROD-6329: Unconverted custom match action fails (2nd PR)

marklogic-data-hub-central/ui/e2e/package-lock.json, marklogic-data-hub-central/ui/e2e/package.json
=> DHFPROD-6548: Update Cypress to latest version

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.queries.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-6439: Using a saved query from 'All Data' allows me to search entities using the card view

marklogic-data-hub-api/src/main/java/com/marklogic/hub/HubClientConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/HubConfigImplTest.java
=> DHFPROD-6553: hubDhs and hubSsl now take precedence over related props

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EnvironmentController.java, marklogic-data-hub-central/ui/public/index.html, marklogic-data-hub-central/ui/src/App.test.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/system-info.data.ts, marklogic-data-hub-central/ui/src/types/common-types.ts, marklogic-data-hub-central/ui/src/util/user-context.tsx
Just the UI changes (with dummy key) to integrate pendo with HC.
```diff
```
=> DHFPROD-6396: Implement Pendo in Hub Central UI

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/util.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/options.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/util.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-xml/test-data/path-merge-options.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/merging-function-arguments.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/test-data/javascriptMergingFunctions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/test-data/xqueryMergingFunctions.xqy
=> DHFPROD-6520: Pass the appropriate format to merge functions

marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx
=> DHFPROD-6401:Custom Radio option doesn't automatically select in adding merge strategy

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.tsx
- Fix for target format not being reflected in step creation
- Fix for target database selection not being reflected in step settings
```diff
```
=> DHFPROD-6461: Load form has errors

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
=> DHFPROD-6557: Fix for failing Run cypress test on DHS

marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-6561: Fix for the issue where the card view doesn't open if select from zero state explorer page.

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/package-lock.json, marklogic-data-hub-central/ui/e2e/package.json, marklogic-data-hub-central/ui/e2e/tsconfig.json
=> DHFPROD-6577: Failing ingestion and runflow cypress e2e tests

marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
Got it reviewed with Julia
```diff
```
=> DHFPROD-6502:Design enhancements for priority order slider in merge strategies table	

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.queries.tsx
=> DHFPROD-6555: Failing explorer cypress tests on DHS

marklogic-data-hub-central/ui/src/components/queries/queries.tsx
=> DHFPROD-6462: Fixed Query Description is retained on database change

marklogic-data-hub-central/ui/src/api/matching.ts, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
=> DHFPROD-6530: Fetch match information after step is saved

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractHubCentralTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/TestObject.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/entitySearch/GetRecordTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployCustomUserFieldsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployEntityIndexesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/dhs/DeployUserAmpsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/AllArtifactsProject.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/ClearUserModulesTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/IngestWithSourceNameAndSourceTypeTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java, web/src/test/java/com/marklogic/hub/web/service/LegacyFlowManagerServiceTest.java, web/src/test/java/com/marklogic/hub/web/web/EntitiesControllerTest.java
Ensure tests pass in Windows platform
```diff
```
=> DHFPROD-6532:Ensure tests pass in Windows platform

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
=> DHFPROD-6589: Fix Failing explore cypress e2e test

marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.scss
=> DHFPROD-6544: Function search bar is not getting displayed properly in Map Step

marklogic-data-hub-central/ui/src/components/header/system-info.module.scss
=> DHFPROD-6579: Overlay in Clear All User Data not centered

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.queries.tsx
=> DHFPROD-6589: Fix manage query failing Explorer test

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.queries.tsx
=> DHFPROD-6589: Fix manage query Explorer test

marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.scss
=> DHFPROD-6600: Fix ant-radio button positioning

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx
=> DHFPROD-6421: Threshold slider tooltip out of synch with slider position

marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx
- URI should be all caps in Snippet View
- No tests needed for text update
```diff
```
=> DHFPROD-6591: Entity snippet results use 'uri' instead of 'URI'

marklogic-data-hub-central/ui/src/App.test.tsx, marklogic-data-hub-central/ui/src/components/header/header.tsx
=> DHFPROD-6597: Change MarkLogic logo link to Hub Central intro page

NOTICE.txt
=> DHFPROD-6536: Adding updated Notice.txt for 2021

web/src/main/ui/app/components/flows-new/edit-flow/mapping/mapping.component.ts, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.html, web/src/main/ui/app/components/flows-new/edit-flow/mapping/ui/entity-table-ui.component.ts
Ensure QS mapping UI shows mapping functions. I don't think there are unit tests for QS. If there are e2e tests, they should just run fine.
```diff
```
=> DHFPROD-6602:Ensure QS mapping UI shows mapping functions

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dhs/DhsDeployer.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommandTest.java
Deploy only modified artifact when using QS
```diff
```
=> DHFPROD-6585:Deploy only modified artifact when using QS

marklogic-data-hub-central/ui/src/pages/Overview.module.scss
=> DHFPROD-6588: added hover indicator on overview page card links

marklogic-data-hub-central/ui/src/components/entities/mapping/create-edit-mapping/create-edit-mapping.tsx
…it-mapping component
```diff
```
=> DHFPROD-6387: Auto complete doesn't use updated source database for create-edit-mapping component

marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx
=> DHFPROD-6586: Switch positions of x and check for apply facets

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/detail-nonEntity.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/detail.tsx, marklogic-data-hub-central/ui/src/components/detail-header/detail-header.test.tsx, marklogic-data-hub-central/ui/src/components/detail-header/detail-header.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.test.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx
=> DHFPROD-6594: Change file type column name to record type

Jenkinsfile
=> DHFPROD-6626: Running regressions on 10.0-6

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.test.tsx
- Updating test fixes for intermittently failing RTL tests that were commented out earlier with this task.
```diff
```
=> DHFPROD-6495: Mapping RTL test fails intermittently

marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.module.scss, marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-entity-map/source-to-entity-map.scss
=> DHFPROD-6613: Query dropdown changes its position with a flicker

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/AddMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/AddMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/customIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.queries.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.table.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.xml.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writer.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/create-edit-step-dialog.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/merge-rule-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/login.tsx
=> DHFPROD-6494: Matching/merging e2e failures

examples/smart-mastering-complete/steps/matching/match-persons.step.json, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/entityDrivenMatches.sjs
=> DHFPROD-6410: and DHFPROD-6534 Construct HC reduce rules appropriately

marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.module.scss, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx
=> DHFPROD-6610: Move the DB selection to the top in Explorer home page

marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts, marklogic-data-hub-central/ui/src/util/search-service.tsx
=> DHFPROD-6407:Encode 'docUri' in GET request

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, specs/models/Batch.schema.json
This is primarily to make life simpler in 5.5 in case we need to store the results of multiple steps on a Batch document. 
```diff
```
=> DHFPROD-6627: Refactored the implementation of processedItemHashes

marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/HubCentralManager.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/GetProjectAsZipTest.java
Include gradle-dhs.properties as part of project zip that's downloaded from Hub Central
```diff
```
=> DHFPROD-6628:Include gradle-dhs.properties as part of project zip that's downloaded from Hub Central

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/BatchSchema.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/CollectionsInformation.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/CompleteError.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/DocumentsArchived.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/JobSchema.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/MasterDocuments.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/MergeJobReportSchema.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/NotificationDocuments.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/ResultingMerges.java, specs/models/Batch.schema.json, specs/models/Job.schema.json, specs/models/MergeJobReport.schema.json
Generated associated Java classes too
```diff
```
=> DHFPROD-6650: Updated Job/Batch schemas and added MergeJobReport

marklogic-data-hub-central/ui/src/util/manageArtifacts-service.tsx
Encode uri before sending request
```diff
```
=> DHFPROD-6648:Mapping results are not shown when the test button is clicked	

marklogic-data-hub/build.gradle, marklogic-data-hub/src/trace-ui/package-lock.json
=> DHFPROD-6622: Fix for trace-ui security vulnerabilities

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
This is intended to minimize the damage from one of the clear operations failing. It's not possible to cause a clear operation to fail, which is why there's no test for this scenario. But this change will help in case a clear operation does fail. 
```diff
```
=> DHFPROD-6658: Changing order in which databases are cleared

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-6582: Explore: unapplied facets persists across views

marklogic-data-hub/src/main/resources/scaffolding/custom-module/sjs/main-mapping.sjs
Fixing the custom mapping step boilerplate code
```diff
```
=> DHFPROD-6584:Fixing the custom mapping step boilerplate code

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-6608: Move Possible Combinations box to the top

Jenkinsfile
=> DHFPROD-6646: Using OpenJDK instead of Oracle

marklogic-data-hub/build.gradle
=> DHFPROD-6667: Avoid zip error in Java tests

marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-6549: Explorer shows datahub artifacts when All Entities is selected

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/calculateMatchingActivityLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/calculateMatchingActivity.sjs
=> DHFPROD-6651: Include reduce queries in threshold combos

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.queries.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/edit-query-dialog/edit-query-dialog.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx
=> DHFPROD-6631: Editing a query name using manage queries modal doesn't update currently selected query name.

Jenkinsfile
=> DEVO-101:Add code coverage of HC and DHF to pipelines

marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-4465:Prevent users from entering duplicate options when merging

.gitignore, marklogic-data-hub/src/main/java/com/marklogic/hub/cli/client/CommandLineFlowInputs.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/cli/client/CommandLineFlowInputsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerImplTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java
Also removed some dead code from the mapping step; noticed that when I added an error to the step during manual testing. 
Slight mod to root .gitignore file - I'm trying out VSCode for Java coding, and it defaults to compiling classes to bin directory. 
```diff
```
=> DHFPROD-4510: Fixing failHard param

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/models/DocSearchQueryInfo.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx
=> DHFPROD-6636: Hide data hub artifacts by default

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/source-to-entity-map.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
=> DHFPROD-6521: e2e test coverage for few bugs

marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/AllArtifactsProject.java
Fix intermittent failure reading zip file
```diff
```
=> DHFPROD-6667:Fix intermittent failure reading zip file

Jenkinsfile, build.gradle, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
```diff
```
- [NA] Squashed all commits into a single commit
=> DHFPROD-6684: Update versions and enable auto-merge

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs
This is being done in preparation for 5.5; it's a new trace event in 5.4, so no backwards compatibility issue. 
```diff
```
=> DHFPROD-6686: Renaming trace event

marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/components/search-bar/search-bar.module.scss, marklogic-data-hub-central/ui/src/components/search-bar/search-bar.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.module.scss, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx
=> DHFPROD-6611: Redesign search bar dropdown

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/search-bar/search-bar.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.test.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.test.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx, marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-6670: FE work for Hide Data Hub artifacts by default

Jenkinsfile
=> DEVO-160: stage in PR pipeline exits with success if Cypress test fails

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/VerifyBatchTimestampTest.java, marklogic-data-hub/src/test/resources/test-projects/custom-step-with-sleep/flows/customFlowWithSleep.flow.json, marklogic-data-hub/src/test/resources/test-projects/custom-step-with-sleep/modules/root/custom-modules/custom/customStepWithSleep/customStepWithSleep.sjs, marklogic-data-hub/src/test/resources/test-projects/custom-step-with-sleep/step-definitions/custom/customStepWithSleep/customStepWithSleep.step.json
=> DHFPROD-3280: fixed timestamps for batch jobs report

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/standard.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/merging-max-sources-all.xqy
=> DHFPROD-6679: Ignore max sources/values when set to 'All'

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/scenarios.json.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
Added a fix for the bug 6690 and added the missing test case for Created On facet in explorer.
```diff
```
=> DHFPROD-6690: Date facets persist on the sidebar even though clear unapplied facets is clicked

marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/GetProjectAsZipTest.java
Fix intermittent failure unzipping file
```diff
```
=> DHFPROD-6667:Fix intermittent failure unzipping file

marklogic-data-hub/build.gradle
=> DHFPROD-6948: Removing spring-beans dependency from mlcp-util

marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/GetProjectAsZipTest.java
=> DHFPROD-6667: Another attempt at GetProjectAsZipTest

marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
=> DHFPROD-6950: Fix the failing cypress e2e scripts

marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubOperatorTest.java
Run QBE test on versions >=10.0-3
```diff
```
=> DHFPROD-6735:Run QBE test on versions >=10.0-3

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyDataInDatabases.spec.tsx
=> DHFPROD-6964: Fix the E2E scripts that are failing in DHS

Jenkinsfile, marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/gradle.properties, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/HubCentral.java, marklogic-data-hub-central/src/main/resources/application-aws.properties, marklogic-data-hub-central/src/main/resources/application-azure.properties, marklogic-data-hub-central/src/main/resources/application.properties, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/HubCentralTest.java, marklogic-data-hub-central/src/test/resources/application-test.properties, marklogic-data-hub-central/ui/e2e/README.md
=> DHFPROD-6962: Only enable hubDhs for aws/azure spring profile

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
=> DHFPROD-6698: Use the Reduce Toggle for Single Properties Form

marklogic-data-hub-central/build.gradle
=> DHFPROD-6739: updated nodejs version for palamida report

examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DHFPROD-6977:Datahub 5.4.0 release

Jenkinsfile
=> DHFPROD-6684: Reverting to use develop branch

examples/README.md, examples/reference-entity-model/build.gradle, examples/step-interceptors/build.gradle, performance-tests/projects/commoncrawl/build.gradle
=> DHFPROD-6982: Bumped example project version to 5.5-SNAPSHOT

marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-monitor-jobs.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-job-monitor.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-job-monitor.json, marklogic-data-hub/src/test/java/com/marklogic/hub/security/VerifyHubCentralRolesTest.java
=> DHFPROD-6941: Add new Job Monitor roles

marklogic-data-hub-api/build.gradle
=> DHFPROD-6977: Adding tasks to generate POM and javadoc tasks

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java, web/src/main/java/com/marklogic/hub/web/service/AsyncFlowService.java
Fix issues with javadocs
```diff
```
- [ n/a] Code passes ESLint tests
- [ n/a] Reviewed Tests
=> DHFPROD-6977:Fix issues with javadocs

marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/ApplyDownloadedZipToProjectTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/GetHubCentralFilesAsZipTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/GetProjectAsZipTest.java
=> DHFPROD-6667: More attempts at fixing intermittent failures in zip tests

Jenkinsfile
=> DHFPROD-6646: Upgrading java8 to latest to avoid zip failures

specs/models/ModelDefinitions.json
Update entity model schema to include related entity and  join property
```diff
```
- [n/a ] Code passes ESLint tests
=> DHFPROD-6968:Update entity model schema to include related entity and  join property

marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
=> DHFPROD-6976: Fix the E2E scripts that are failing on windows

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/RunFlowResponseSchema.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/StepResponses__1.java, specs/models/RunFlowResponse.schema.json
=> DHFPROD-6956: Adding schema for RunFlowResponse

marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/AbstractHubClientTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/services/hubFlowRunner.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/DocumentMetadataHelper.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsWithCustomPermissionsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/AddSourceNameAndTypeStepDefTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/HubFlowRunnerResource.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/IngestAndMapWithConnectedStepsTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/test-data/flows/ingestXmlAndMap.flow.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/test-data/steps/ingestion/ingestXmlCustomer.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/test-data/steps/mapping/mapXmlCustomer.step.json
Most of this is test changes; the changes to the app were fairly small, other than introducing support for an XML payload. 
```diff
```
=> DHFPROD-6716: Can run ingest and map connected steps on XML input

marklogic-data-hub-central/ui/e2e/cypress.json
=> DHFPROD-7000: Comment out cypress e2e tests

Jenkinsfile
=> DEVO-196: update DHF pipelines to remove QS

marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubSecurityAdminTest.java
This is a test created to verify the bug fix for DHFPROD-6606. 
```diff
```
=> DHFPROD-6606: ML is allowing data-hub-security-admin can create role with xdmp:shutdown privilege

installer-for-dhs/build.gradle, marklogic-data-hub-client-jar/build.gradle, marklogic-data-hub-client-jar/src/main/java/com/marklogic/hub/clientjar/ClientJarFlowInputs.java, marklogic-data-hub/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/CommandLineFlowInputs.java
=> DHFPROD-7006: Cleaning up some duplication of CommandLineFlowInputs

Jenkinsfile
=> DHFPROD-7006: Archiving installer and client jar

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.module.scss
=> DHFPROD-6958: Select URIs for Testing and Test Button

build.gradle, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DHFPROD-6977:Datahub 5.4.1-rc1 release

build.gradle, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DHFPROD-0000:Datahub 5.4.1_rc1 release

build.gradle, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DHFPROD-0000:Datahub 5.4.0_rc2 release

marklogic-data-hub-central/ui/e2e/cypress.json, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addCustomStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/customIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/ingestionForAllFiletypes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/validationsForNonHCSavedQueryUser.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyDataInDatabases.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/customRole.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
=> DHFPROD-6998: Stabilize ingestion E2E Scripts

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
=> DHFPROD-7021: Added descriptions for Gradle tasks lacking them

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/merging.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils/invoke-queue-write.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/WriteDocumentsTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/matchingTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/mergingTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/writeContentArray/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/writeContentArray/writeContentNoPermissions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/writeContentArray/writeContentWithPermissions.sjs
Changed "writeDocuments" in hub-utils into "writeContentArray" in flow-utils, as it's a flow-specific function. 
Also fixed matchingTest and mergingTest - some assertions weren't being returned. 
```diff
```
=> DHFPROD-7030: Correctly applying default permissions

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/customStep/getCustomStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collector.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collectorLib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/endpoints/collectorLib/prepareSourceQuery.sjs
Set a limit on the query used in a step
```diff
```
=> DHFPROD-3093:Set a limit on the query used in a step

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
=> DHFPROD-6960: Select All Data For Testing

Jenkinsfile, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub-central/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, pipeline.properties
=> DHFPROD-7046:Updating the versions to 5.4-SNAPSHOT for 5.4.1

marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-7040: updated custom step settings icon

marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/customRole.spec.tsx, marklogic-data-hub-central/ui/src/config/tiles.config.ts, marklogic-data-hub-central/ui/src/pages/Overview.tsx
Also made description on card match description in tile.
```diff
```
=> DHFPROD-6973: updated descriptions for explore card and tile

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunFlowWithSameJobIdTest.java
=> DHFPROD-6526: Job times are incorrect when reusing job ID

marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/TestObject.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunFlowWithSameJobIdTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/VerifyBatchTimestampTest.java
=> DHFPROD-6526: Refactored tests with timestamp comparisons

marklogic-data-hub-api/build.gradle
=> DHFPROD-7046: Adding tasks to generate POM and javadoc tasks

marklogic-data-hub-central/ui/e2e/cypress/support/components/common/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
=> DHFPROD-6700: Toggle Between Matched and Not Matched Pairs

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/test-data/content/jsonEntity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/test-data/content/jsonEntityDifferentVersion.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/test-data/content/namespacedEntity.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/test-data/content/namespacedEntityDifferentVersion.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/test-data/content/noNamespaceEntity.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/test-data/entities/TdeContextNamespacedEntity.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/test-data/entities/TdeContextNoNamespaceEntity.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/verifyTdeContext.xqy
This is already on 5.4-develop, it's for develop now. 
```diff
```
=> DHFPROD-6954: TDE context path now avoids false positives

marklogic-data-hub-central/ui/src/pages/Browse.tsx
Small fix. No new tests needed here as relevant test already exists.
```diff
```
=> DHFPROD-6972: Data hub artifacts not visible when All Data is selected

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
=> DHFPROD-7048: Test values in mapping doesn't update for XML source docs when editing URI manually

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/stepDefinition.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/saveStepDefinition.sjs
This is already on 5.4-develop, just submitting for develop. 
```diff
```
=> DHFPROD-7009: Fixing bug with saving step definitions

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java, web/src/main/java/com/marklogic/hub/web/service/AsyncFlowService.java
=> DHFPROD-7046:Fix issues with javadocs

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
Added missing parameter when calling handleEntityExpandCollapse function.
```diff
```
=> DHFPROD-6945: Create Expand/Collapse component for the mapping UI. 

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Simplified them, and directing customers and employees to Support / JIRA when appropriate. 
```diff
```
=> DHFPROD-7064: Updating Github templates

examples/reference-entity-model/build.gradle, examples/reference-entity-model/entities/BabyRegistry.entity.json, examples/reference-entity-model/entities/Customer.entity.json, examples/reference-entity-model/entities/Order.entity.json, examples/reference-entity-model/entities/Product.entity.json, examples/reference-entity-model/flows/CurateCustomerWithRelatedEntitiesJSON.flow.json, examples/reference-entity-model/input/jsonCustomersWithRelatedEntities/customer1WithRelatedEntities.json, examples/reference-entity-model/steps/ingestion/loadCustomersWithRelatedEntitiesJSON.step.json, examples/reference-entity-model/steps/mapping/mapCustomersWithRelatedEntitiesJSON.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/map-multiple-entities/test-data/steps/mapping/mapCustomersJSON.step.json
Update example project with a flow that runs related entity mappings
```diff
```
=> DHFPROD-6957:Update example project with a flow that runs related entity mappings

marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/authorities.testutils.ts, marklogic-data-hub-central/ui/src/components/tiles/tiles.scss, marklogic-data-hub-central/ui/src/components/tiles/toolbar.scss, marklogic-data-hub-central/ui/src/components/tiles/toolbar.test.tsx, marklogic-data-hub-central/ui/src/config/tiles.config.ts, marklogic-data-hub-central/ui/src/pages/Monitor.module.scss, marklogic-data-hub-central/ui/src/pages/Monitor.test.tsx, marklogic-data-hub-central/ui/src/pages/Monitor.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.scss, marklogic-data-hub-central/ui/src/pages/TilesView.tsx, marklogic-data-hub-central/ui/src/util/authorities.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/security.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/getAuthoritiesTest.sjs
=> DHFPROD-6942: navigation to monitor tile

marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/AbstractHubClientTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/prov.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FixCreatedByStepTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/ProvenanceDocumentsForEachStepTest.java, marklogic-data-hub/src/test/resources/entity-reference-model/legacyProvenanceRecord1.xml, marklogic-data-hub/src/test/resources/entity-reference-model/legacyProvenanceRecord2.xml
=> DHFPROD-6413: Provenance records persisted for each step in a flow with unique id

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
=> DHFPROD-6691: Select single and multiple property form from a dropdown

examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub-central/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DHFPROD-7046:Datahub 5.4.1 release

Jenkinsfile
=> DEVO-211:publishAnddhs stage wrongly skipped in DHF pipeline

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/custom.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx
=> DHFPROD-7028: fixed custom step additional settings not displaying in UI

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
=> DHFPROD-6984: Validation check to handle URI in test match

marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.module.scss, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/pages/Monitor.test.tsx, marklogic-data-hub-central/ui/src/pages/Monitor.tsx
This update adds a Foreign Key Relationship icon to the Modeling view. The icon appears in the legend and also next to entity properties that are of the Related Entity type. 
Screencast: https://drive.google.com/file/d/1plik18bjhdjOkWfFh3U4HdWC29LktRkE/view
A unit test checks the presence of the icon and its tooltip next to a Related Entity property. 
I've also refactored a Property Table test so that it works correctly given the recent addition of the Join Property field. 
I also fixed some ESLint formatting issues in other new-ish files.
```diff
```
=> DHFPROD-6952: Add foreign key relationship icon to Modeling

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-http-user.json, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubHttpUserTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubSecurityAdminTest.java
Add role for network access capabilities
```diff
```
=> DHFPROD-7010:Add role for network access capabilities

marklogic-data-hub-spark-connector/gradle.properties
=> DEVO-212: Updating the version to 1.0.0

marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/pages/Monitor.test.tsx
Fixed the test of editing a relationship property in property-modal.test in Modeling. 
Also fixed ESLint issues in Monitor.test.
```diff
```
=> DHFPROD-7063: Fix edit relationship property test in Modeling
