marklogic/marklogic-data-hub

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addCustomStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/ingestionForAllFiletypes.spec.tsx
=> DHFPROD-7091: Fix for tests failing at adding steps to a flow

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
=> DHFPROD-7090: Button spacing issue in Run tile

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-downloader.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/getArtifactsWithProjectPaths.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/AllArtifactsProject.java, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/ApplyDownloadedZipToProjectTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/artifacts/getArtifactsWithProjectPaths.sjs
=> DHFPROD-6967: added custom step support to hub-central-download

marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/AbstractHubClientTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowInputs.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils/invoke-queue-write.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStepAsUserWithDefaultCollectionsTest.java
Did some renaming - "baseCollections" is now "configCollections"
```diff
```
=> DHFPROD-6404: User default collections are now applied by a step

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/FlowService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/flow/updateFlow.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/flow/updateFlow.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/updateFlow.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/lib/flowService.sjs
This PR 
- Changes updateFlow endpoint to accept a name, description and array of stepIds (previously accepted a JsonNode flow). 
- Updated descriptions in api file.
- No major UI changes besides removing a useless attribute.
```diff
```
=> DHFPROD-5080: Reorder steps in a flow via arrows

Jenkinsfile
=> DEVO-204:Update develop pipeline to run full develop pipeline nightly

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
=> DHFPROD-7072: Edit Source Doc URI Save/Discard Buttons do not work

marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/types/curation-types.ts
=> DHFPROD-7105: Unable to run Match Step with Custom ruleset

marklogic-data-hub-junit5/build.gradle, marklogic-data-hub-junit5/src/main/java/com/marklogic/hub/ext/junit5/HubDatabasePreparer.java, marklogic-data-hub-junit5/src/main/java/com/marklogic/hub/ext/junit5/MarkLogicUnitTestArgumentsProvider.java, marklogic-data-hub-junit5/src/test/java/com/marklogic/hub/ext/junit5/MarkLogicUnitTestArgumentsProviderTest.java
=> DHFPROD-7039: Added support for running ML unit tests via JUnit

marklogic-data-hub-central/ui/src/config/tiles.config.ts, marklogic-data-hub-central/ui/src/pages/Overview.tsx
=> DHFPROD-7101: improved UI text in Overview page

marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.tsx
=> DHFPROD-7032: Step and Flow in details page should not look like links

marklogic-data-hub-central/ui/src/components/search-result/search-result.module.scss
=> DHFPROD-7033:Icons in snippet view in explore should be purple

marklogic-data-hub-central/ui/src/components/search-result/search-result.module.scss
=> DHFPROD-7033:Icons in snippet view in explore should be purple	

marklogic-data-hub-central/ui/src/components/login-form/login-form.module.scss, marklogic-data-hub-central/ui/src/components/login-form/login-form.tsx
=> DHFPROD-7096:Visual feedback when logging in

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/matching.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/merging.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/datahub.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/invoke-step.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/prov.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/stepDefinition.sjs, marklogic-data-hub/src/main/resources/ml-modules/services/mlSmMatch.sjs, marklogic-data-hub/src/main/resources/ml-modules/services/mlSmMerge.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mastering/default/filterMatchingContent.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/provenance/writeProvenanceThrowsError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/lib/masteringTestLib.sjs
=> DHFPROD-7110: Replaced globalContext with stepExecutionContext

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java
Compiles fine on Java 8
```diff
```
=> DHFPROD-6526: Fixing Java 11 compilation issue

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MatchingStepController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MatchingStepControllerTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MasteringService.java, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/options-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/previewMatchingActivity.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/previewMatchingActivity.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/preview-matching-activity-lib.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/previewMatchingActivity.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/test-data/content/CustMatchMerge1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/test-data/content/CustMatchMerge2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/test-data/content/CustShippingCityStateMatch1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/test-data/content/CustShippingCityStateMatch2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/test-data/content/CustShippingCityStateMatch3.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/test-data/content/CustShippingCityStateMatch4.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/test-data/content/nameDictionary.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/test-data/entities/Customer.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/test-data/steps/matching/matchCustomers.step.json
=> DHFPROD-7106: previewMatchingActivity API, first cut

marklogic-data-hub-central/ui/src/components/header/system-info.test.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.tsx, marklogic-data-hub-central/ui/src/config/messages.config.tsx
=> DHFPROD-6975: fixed incorrect information in download UI messages

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/CustomStepController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/CustomStepControllerTest.java, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/custom.spec.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/CustomStepService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/customStep/getCustomStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/customStep/updateCustomStep.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/customStep/updateCustomStep.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/customStep/manageCustomStep.sjs
=> DHFPROD-7059: added functionality to edit custom settings for custom steps

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/entitySearch/GetRecordTest.java
=> DHFPROD-6985: Record History when provenance has a flow that doesn't exist

marklogic-data-hub-central/ui/src/components/header/system-info.test.tsx, marklogic-data-hub-central/ui/src/config/messages.config.tsx
Additional revision to https://github.com/marklogic/marklogic-data-hub/pull/5425
```diff
```
=> DHFPROD-6975: (appended) updates to system info download messages

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matchStepAdvanceSettingsReader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matchStepAdvanceSettingsWriter.spec.tsx
=> DHFPROD-6185: End to end test for match step advanced settings

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java
Log progress as step runs.
It's just a couple of log messages.I don't think test is needed, manual verification should suffice
```diff
```
- [ n/a] Reviewed Tests
=> DHFPROD-7014:Log progress as step runs

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/calculateMatchingActivityLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/calculateMatchingActivity.sjs
=> DHFPROD-7104: (5.4.2) Fix calculated match activity recursion

installer-for-dhs/src/main/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommand.java, installer-for-dhs/src/test/java/com/marklogic/hub/dhs/installer/command/InstallIntoDhsCommandTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubDefaultTdesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/main/resources/tdes/JobsData.json, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/DeployHubDefaultTdesCommandTest.java
=> DHFPROD-7052: TDE For Querying Jobs Data

marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ProvenanceService.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/amps/prune-provenance.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-prune-provenance.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/provenance/pruneProvenance.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/provenance/pruneProvenance.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/provenance/service.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/provenance/pruning.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/lib/provenanceService.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/provenance/pruneProvenance.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/provenance/setup.sjs
=> DHFPROD-6966: Bulk Data Service to prune provenance data

marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx
=> DHFPROD-7073: Flows with long step names have containment issues

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/customIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/ingestionForAllFiletypes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/validationsForNonHCSavedQueryUser.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyDataInDatabases.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/customRole.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
=> DHFPROD-7137: Update the E2E tests in feature/5.4

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/calculateMatchingActivityLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/calculateMatchingActivity.sjs
=> DHFPROD-7104: Fix calculated match activity recursion

marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/assets/mock-data/monitor/job-results.ts, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.module.scss, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.test.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx, marklogic-data-hub-central/ui/src/components/login-form/login-form.tsx, marklogic-data-hub-central/ui/src/pages/Monitor.tsx, marklogic-data-hub-central/ui/src/util/date-conversion.tsx
=> DHFPROD-6944:Job monitor result table

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/validateStepCommonLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/validateSteps/commonValidateFunctions.sjs
=> DHFPROD-7103: parse collection from sourceQuery in various formats

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/jobs/job-results-lib.sjs, marklogic-data-hub/src/main/resources/tdes/JobsData.json, marklogic-data-hub/src/test/java/com/marklogic/hub/entity/EntityServicesAlignmentTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/jobs/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/jobs/test-data/jobs/test-doc1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/jobs/test-data/jobs/test-doc2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/jobs/test-data/jobs/test-doc3.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/jobs/testGetJobInfo.sjs, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
=> DHFPROD-7053: ML library using Optic For Querying Jobs Data

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx
Just the dummy version of UI. The multiple ruleset form doesn't save yet. End to end tests will be added in future stories where form will be saved with relevant data.
- UX changes are approved by @jbelonoj
```diff
```
=> DHFPROD-5227: Ruleset form for selecting multiple properties

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx, marklogic-data-hub-central/ui/src/types/view-types.ts
=> DHFPROD-5754: Retain state when navigating away and back to Model tile

examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub-central/gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DHFPROD-7156:Release 5.4.2 datahub

marklogic-data-hub-central/LICENSE.txt, marklogic-data-hub-central/NOTICE.txt, marklogic-data-hub-spark-connector/LICENSE.txt, marklogic-data-hub-spark-connector/NOTICE.txt
=> DHFPROD-7159: Add Notice and License files to hub central and spark connector projects

marklogic-data-hub-central/ui/src/assets/mock-data/curation/curation-context-mock.js, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.test.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.tsx, marklogic-data-hub-central/ui/src/types/curation-types.ts, marklogic-data-hub-central/ui/src/util/curation-context.tsx
Currently the BE api is the not returning the appropriate errors, this story just shows up one warning right now. The remaining part will be handled as a part of https://project.marklogic.com/jira/browse/DHFPROD-6994, tests will be added as a part of https://project.marklogic.com/jira/browse/DHFPROD-7158
```diff
```
=> DHFPROD-6644: Front-end: Each after merge save, call validation API and display warnings if they exist

CODEOWNERS
Update 'CODEOWNERS' file
```diff
```
=> DHFPROD-7160:Update 'CODEOWNERS' file

CODEOWNERS
=> DHFPROD-7160:Updating CODEOWNERS

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/entity-services/function-metadata.xsl
Adding xslt for generating function metadata from ML server
```diff
```
=> DHFPROD-5850:Adding xslt for generating function metadata from ML server

CODEOWNERS
Updating CODEOWNERS file
```diff
```
=> DHFPROD-7160:Updating CODEOWNERS file

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/ingestionForAllFiletypes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts, marklogic-data-hub-central/ui/e2e/package.json
=> DHFPROD-7167: Fix the New Flow related tests

marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/types/view-types.ts
=> DHFPROD-7029: Retain state when navigating away and back to the Run Tile

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy
=> DHFPROD-7098: (5.4) Cleanup match results xml

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/xquery-lib.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/entity-services/function-metadata.xsl, marklogic-data-hub/src/main/resources/ml-modules/transforms/mlGenerateFunctionMetadata.sjs, marklogic-data-hub/src/test/ml-modules/root/custom-modules/mapping-functions/addOne.sjs, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/mapping-functions-sequence-parameter/setup.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/mapping-functions-sequence-parameter/testMappingFunctionWithSequenceParam.sjs
Pass sequence to custom SJS mapping function
```diff
```
=> DHFPROD-5850:Pass sequence to custom SJS mapping function

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/BatchSchema.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/Options__1.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/StepSchema.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/models/reservedEntityName.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/models/validateModelDefinitions.sjs
A name is reserved if it's also the name of a generated search constraint.
Also checking in updates to the Java classes that are generated based on JSON schema. 
```diff
```
=> DHFPROD-7130: Verifying that entity name is not a reserved term

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy
=> DHFPROD-7098: Cleanup match results xml

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/testTargetCollectionAdditivity/flowWithTargetCollectionsAdditivity.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/testTargetCollectionAdditivity/flowWithoutTargetCollectionsAdditivity.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/testTargetCollectionAdditivity/setup.sjs
=> DHFPROD-3097: added option to maintain collections in steps

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping-functions/core.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/user-parameters/mappingWithTwoUserParams.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/user-parameters/setup.sjs
=> DHFPROD-4489: Renamed keyValue to lookup

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MatchingStepController.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/previewMatchingActivity.sjs
=> DHFPROD-5764: run match preview in sourceDatabase

Jenkinsfile
=> DEVO-229:fix issue with unintentional PR merge

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/Context.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils/invoke-queue-write.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/stepWithQuality/runStepWithQuality.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/stepWithQuality/runWithInvalidQuality.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/stepWithQuality/setup.sjs, specs/models/ContentObject.schema.json
New PR for https://github.com/marklogic/marklogic-data-hub/pull/5508 because I'm not sure what happened to it
```diff
```
=> DHFPROD-6843: add quality to documents created by step

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/BatchSchema.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/JobSchema.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/Options__1.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/StepSchema.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/startStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/transforms/mlRunIngest.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/IngestJsonAsXmlTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunFlowWithInvalidStepDefTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java, specs/models/Job.schema.json
Added tests for lastAttemptedStep/lastCompletedStep. And corrected these values to always be strings, instead of being initialized as numbers and then modified later to be strings. 
Added a test to verify that Batch docs aren't created when running an ingestion step.
```diff
```
=> DHFPROD-6525: Fixing bug where lastAttemptedStep wasn't set

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/stepDefinition.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/default/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/bulk/fixCreatedByStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepDefinition/getStepDefinition.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/stepDefinition.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/RunFlowWithStemmingEnabledTest.java
Ensure steps run fine with stemming turned on
```diff
```
=> DHFPROD-7182:Ensure steps run fine with stemming turned on

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/thesaurus.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/zip.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/helper-impl.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/schemaElements/matching-with-schema.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/schemaElements/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/schemaElements/suite-teardown.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/schemaElements/test-data/content/testSchemaXml.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/schemaElements/test-data/schema.xsd
=> DHFPROD-7099: (5.4) Support matching with complex type XML schemas

Jenkinsfile
=> DEVO-191:Update DHF develop pipeline to include HC on-prem

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/thesaurus.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/zip.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/helper-impl.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/schemaElements/matching-with-schema.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/schemaElements/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/schemaElements/suite-teardown.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/schemaElements/test-data/content/testSchemaXml.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/schemaElements/test-data/schema.xsd
=> DHFPROD-7099: Support matching with complex type XML schemas

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx
=> DHFPROD-7191: Fix the defaultIngestionCardView.spec.tsx test

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/writeQueue.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/testFindStepResponses.sjs
=> DHFPROD-7100: Using getObjectValues so it works on ML 9

marklogic-data-hub-central/ui/src/assets/mock-data/curation/entity-definitions-mock.js, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
=> DHFPROD-7155: Add tests for viewing related entity types

marklogic-data-hub-central/ui/e2e/cypress/plugins/index.js, marklogic-data-hub-central/ui/e2e/cypress/support/index.js, marklogic-data-hub-central/ui/e2e/package-lock.json, marklogic-data-hub-central/ui/e2e/package.json
=> DHFPROD-7206: Skipping the rest of tests on first failure

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job-query-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/test-data/jobs/test-doc2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/test-data/jobs/test-doc3.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/testFindStepResponses.sjs
=> DHFPROD-7051: Sorting when Querying Jobs Data

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/BatchSchema.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/StepResult.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/WriteTransaction.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/finishJob.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/finishStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/startJob.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/startStep.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/batch.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/writeQueue.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils/invoke-queue-write.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/singleStep.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/test-data/steps/ingestion/ingestCustomer.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/twoJsonDocs.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/ext/marklogic-unit-test/hub-test-helper/prepareDatabasesTest.sjs, specs/models/Batch.schema.json
Most of the changes here involve moving logic from larger library modules (jobs.sjs and flowRunner.sjs) into smaller class modules, which should make the logic easier to understand and result in a better separation of concerns. 
The main new chunk of behavior is the addition of the "stepResults" array to the Batch document. 
Added Job.sjs and Batch.sjs classes to consolidate logic pertaining to creating/updating these documents.
Added FlowExecutionContext.sjs to capture state pertaining to a flow that is running connected steps. 
```diff
```
=> DHFPROD-6718: Connected steps now generate job data

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addCustomStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/customIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/ingestionForAllFiletypes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/reorderSteps.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
=> DHFPROD-7222: Fix E2E tests to wait for jobs api to respond

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
=> DHFPROD-7026: Filter by property name in the entity table

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/writeQueue.sjs, marklogic-data-hub/src/main/resources/ml-modules/services/hubFlowRunner.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/HubFlowRunnerResource.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/IngestAndMapWithConnectedStepsTest.java
Also fixed a couple bugs in logging that I ran into
```diff
```
=> DHFPROD-6718: hubFlowRunner now supports jobId

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/options-impl.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/custom-controlled-weight.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/lib/lib.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/test-data/custom-matching-with-custom-weight-options.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/test-data/custom-xqy-matching-algo-dob.xqy
=> DHFPROD-7234: (5.4.x) Use cts:query weights for score when weight unspecified

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/options-impl.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/custom-controlled-weight.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/lib/lib.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/test-data/custom-matching-with-custom-weight-options.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/test-data/custom-xqy-matching-algo-dob.xqy
=> DHFPROD-7234: Use cts:query weights for score when weight unspecified

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.module.scss, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.module.scss, marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx
~The value prop is redundant (already covered by checkCurrentQueryChange) and is blocking the correct placeholder color from showing.~
```diff
```
=> DHFPROD-4863: fixed styling of saved query dropdown in explore

marklogic-data-hub-central/ui/e2e/package.json
=> DHFPROD-7075: create automates test suites for sanity testing

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/SwaggerConfig.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/CreateAndUpdateModelTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ModelsService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/createModel.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/createModel.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateModelInfo.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateModelInfo.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/models/CreateAndUpdateModelTest.java, specs/models/ModelDefinitions.json
Middle tier work for creating/updating entity model with namespace/prefix
```diff
```
=> DHFPROD-7233:Middle tier work for creating/updating entity model with namespace/prefix

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job-query-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/testFindStepResponses.sjs
=> DHFPROD-7051: Refactoring API to reuse react components

marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx
=> DHFPROD-5232: View selected properties at top of Ruleset form for multiple properties

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/options-impl.xqy
```diff
```
- N/A Added Tests (Tests already exist)
=> DHFPROD-7234: (5.4.3) Don't cache calculated weights

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/options-impl.xqy
```diff
```
- N/A Added Tests (Tests already exist)
=> DHFPROD-7234: Don't cache calculated weights

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
=> DHFPROD-7184: Expand mapping tables height to 100%

marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
=> DHFPROD-7272: Fix the failing E2E tests

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/custom-controlled-weight.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/test-data/custom-matching-with-custom-weight-options.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/test-data/custom-matching-with-custom-weight.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/matching/test-data/doc1.json
=> DHFPROD-7234: No caching or double counting calculated weights

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job-query-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/test-data/jobs/test-doc1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/testFindStepResponses.sjs
=> DHFPROD-7085: Facets and Filtering of Jobs Table

marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.test.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx, marklogic-data-hub-central/ui/src/pages/Monitor.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-7208:Sorting - FE Implemenattion

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/expandable-table-view/expandable-table-view.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/expandable-table-view/expandable-table-view.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
=> DHFPROD-4546: Show Ruleset Table when testing match configuration

examples/reference-entity-model/steps/mapping/mapCustomersWithRelatedEntitiesJSON.step.json, examples/reference-entity-model/steps/mapping/mapCustomersWithRelatedEntitiesXML.step.json, marklogic-data-hub-central/ui/src/assets/mock-data/curation/common.data.ts, marklogic-data-hub-central/ui/src/assets/mock-data/curation/entity-definitions-mock.js, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
- Includes [DHFPROD-7193: Add an entity-specific context field](https://project.marklogic.com/jira/browse/DHFPROD-7193) 
- Tests added in RTL
- cypress tests will be needed but require extensive setup to cover related entities from end-to-end. Created a task for that [here](https://project.marklogic.com/jira/browse/DHFPROD-7267)
```diff
```
=> DHFPROD-6708: Save mappings to related entity types in Hub Central

examples/reference-entity-model/steps/mapping/mapCustomersWithRelatedEntitiesJSON.step.json, examples/reference-entity-model/steps/mapping/mapCustomersWithRelatedEntitiesXML.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/testMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/getXpathFunctionsThatDoNotWorkInMappingExpressions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/runMappingWithUriReference.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateAndRunMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/validateJsonWithXPathThatNeedsEscaping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/buildAndRunPropertyMappings.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/test-data/steps/mapping/mapCustomersJSON.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/test-data/steps/mapping/mapCustomersXML.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/user-parameters/mappingWithTwoUserParams.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/user-parameters/userModuleThrowsError.sjs
Test Mapping expressions for related entities
```diff
```
=> DHFPROD-7164:Test Mapping expressions for related entities

examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub-central/gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DHFPROD-7279: Release 5.4.3 datahub

gradle.properties, marklogic-data-hub/gradle.properties, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, ml-data-hub-plugin/gradle.properties, web/gradle.properties
Updating versions to 5.2-SNAPSHOT
```diff
```
=> DHFPROD-7261:Updating versions to 5.2-SNAPSHOT

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
**Note** :  Removed Matched and not Matched Tabs in this PR as well. 
Removed Validation check for user to enter at least 2 URIS to test match configuration.
```diff
```
=> DHFPROD-4547: Expand and collapse thresholds and pairs for Test Match functionality.

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStepWithCustomHookTest.java, marklogic-data-hub/src/test/resources/entity-reference-model/modules/root/custom-modules/custom-hooks/test-hook.sjs
=> DHFPROD-7289: Handling custom hook errors for 5.4

examples/dhf5-custom-hook/.gitignore, examples/dhf5-custom-hook/src/main/ml-modules/root/custom-modules/ingestion/IngestOrders/archive-hook.sjs, examples/dhf5-custom-hook/src/main/ml-modules/root/custom-modules/mapping/MapCustomers/custom-uri-hook.sjs
=> DHFPROD-7017: Added note about toObject to custom hook example

marklogic-data-hub-central/ui/e2e/package-lock.json, marklogic-data-hub-central/ui/e2e/package.json
Fixed 5 high and 2 moderate vulnerabilities:
- Updated mochawesome-merge to ^4.0.0
- Updated elliptic to latest
All e2e tests pass
```diff
```
=> DEVO-238: fixed package vulnerabilities in ui/e2e

marklogic-data-hub-central/ui/src/components/date-facet/date-facet.module.scss, marklogic-data-hub-central/ui/src/components/date-facet/date-facet.tsx, marklogic-data-hub-central/ui/src/components/date-time-facet/date-time-facet.module.scss, marklogic-data-hub-central/ui/src/components/date-time-facet/date-time-facet.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.module.scss, marklogic-data-hub-central/ui/src/components/facet/facet.test.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.tsx, marklogic-data-hub-central/ui/src/components/numeric-facet/numeric-facet.module.scss, marklogic-data-hub-central/ui/src/components/numeric-facet/numeric-facet.tsx
Small UX changes as requested
```diff
```
=> DHFPROD-6223: fixed UI appearance when searching via facets on structured props

marklogic-data-hub-central/ui/e2e/package-lock.json, marklogic-data-hub-central/ui/e2e/package.json, web/package-lock.json, web/package.json
5.4-develop version of https://github.com/marklogic/marklogic-data-hub/pull/5592
In addition to fixing y18n and elliptic in e2e, this PR also updates y18n in web
Fixed 11 high vulnerabilities:
- updated concurrently to ^5.0.1
```diff
```
=> DEVO-238: fixed package vulnerabilities in web and ui/e2e

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/buildAndRunPropertyMappings.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/runFlowWithRelatedEntityMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/test-data/steps/mapping/mapCustomersJSON.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/test-data/steps/mapping/mapCustomersWithInvalidExpressions.step.json
Middle-tier support for testing uri expression from UI
```diff
```
=> DHFPROD-7287:Middle-tier support for testing uri expression from UI

marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java
Fix failures in legacy flow test 'EndToEndFlowTests'
```diff
```
=> DHFPROD-7293:Fix failures in legacy flow test 'EndToEndFlowTests'

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/mlcp-flow-transform.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/public/flow/flow-api.sjs, marklogic-data-hub/src/main/resources/ml-modules/services/hubFlowRunner.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/errorHandling/batchStepStopOnError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/errorHandling/beforeCustomHookThrowsError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/errorHandling/dontStopOnFirstStepError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/errorHandling/dontStopOnSecondStepError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/errorHandling/flowThrowsError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/errorHandling/interceptorThrowsError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/errorHandling/stopOnFirstStepError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/errorHandling/stopOnSecondStepError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/ingestMapMaster/ingestMapMatchMerge.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/hooksAndInterceptors/testHooksAndInterceptors.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/dontWriteIngestionOrMappingOutput.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/dontWriteIngestionOutput.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/ingestAndMapToStaging.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/ingestToFinalMapToStaging.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/ingestionDoesntWriteProvenance.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/ingestionProducesDuplicateUris.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/oneJsonDocWithOptions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/singleStep.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/twoJsonDocs.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/testTargetCollectionAdditivity/flowWithTargetCollectionsAdditivity.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/testTargetCollectionAdditivity/flowWithoutTargetCollectionsAdditivity.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/user-parameters/mappingWithTwoUserParams.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/user-parameters/userModuleThrowsError.sjs
Renamed processContentWithFlow to runFlowOnContent and likewise for runStepOnContent; the use of "run" is more consistent with existing DHF stuff
```diff
```
=> DHFPROD-7111: Made runFlowOnContent public

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MatchingStepController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MergingStepController.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MasteringService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/validateMergingStep.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/validateMergingStep.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/validateSteps/validateMergingStep.sjs
=> DHFPROD-6994: Backend work for separate merge warnings

marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.module.scss, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.scss, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.test.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx
=> DHFPROD-7084: Show additional attributes in Jobs table UI

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/com/marklogic/hub/mapping/mapping-test.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/runMappingWithUriExpressionThatEvaluatesToNull.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/test-data/flows/customerFlow.flow.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/test-data/steps/mapping/mapWithUriExpressionEvaluatesToNull.step.json
Fail mapping step if 'uriExpression' evaluates to null
```diff
```
=> DHFPROD-7271:Fail mapping step if 'uriExpression' evaluates to null

marklogic-data-hub/build.gradle
=> DEVO-242: Run regressions and release 5.2.7

examples/barebones/build.gradle, examples/dh-5-example/build.gradle, examples/dh-5-example/gradle/wrapper/gradle-wrapper.properties, examples/dhf5-custom-hook/build.gradle, examples/dhs-example/build.gradle, examples/disconnected-project/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/reference-entity-model/build.gradle, examples/smart-mastering-complete/build.gradle, examples/step-interceptors/build.gradle, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
Also bumped the DHF version to 5.5.0 for these projects
```diff
```
=> DHFPROD-7318: Fixing how example projects reference Gradle plugin

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/startJob.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/batch.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowProvenance.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/writeQueue.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils/invoke-queue-write.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/prov.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/mlcp-flow-transform.sjs, marklogic-data-hub/src/main/resources/ml-modules/services/hubFlowRunner.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/HubFlowRunnerResource.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/IngestAndMapWithConnectedStepsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/RunConnectedStepsViaMlcpTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/test-data/flows/ingestAndErrorStep.flow.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/test-data/flows/ingestAndMap.flow.json
Also renamed trace events to hub-flow and hub-flow-debug, which touched a dozen files or so. Otherwise the changes are pretty minimal. 
```diff
```
=> DHFPROD-7175: Can now choose step numbers for connected steps

examples/reference-entity-model/steps/mapping/mapCustomersWithRelatedEntitiesJSON.step.json, examples/reference-entity-model/steps/mapping/mapCustomersWithRelatedEntitiesXML.step.json
Include hubURI() in reference-entity-project uriExpression examples
```diff
```
=> DHFPROD-7294:Include hubURI() in reference-entity-project uriExpression examples

examples/step-interceptors/README.md, examples/step-interceptors/data/10250.json, examples/step-interceptors/src/main/ml-modules/root/custom-modules/step-interceptors/filterOrders.sjs, examples/step-interceptors/steps/mapping/map-orders.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/hooksAndInterceptors/setup.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/hooksAndInterceptors/test-data/addHeaders.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/hooksAndInterceptors/test-data/beforeMain.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/hooksAndInterceptors/testHooksAndInterceptors.sjs
Did a little cleanup in flow.sjs too - there's no need for writeQueue to be a class variable, it can be a local one. 
```diff
```
=> DHFPROD-7292: Now supporting "beforeMain" interceptors

CODEOWNERS
=> DHFPROD-7328:Remove users from CODEOWNERS file

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowProvenance.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/errorHandling/beforeCustomHookThrowsError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/errorHandling/interceptorThrowsError.sjs
=> DHFPROD-7326: Using console.error for error messages

marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json
Updating axios version (high severity dependabot issue)
```diff
```
=> DHFPROD-7312: Fix github vulnerabilities

Jenkinsfile
=> DEVO-240: Investigate connection issues in nightly regressions

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/exportSearchAsCSV.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/exportSearchAsCSVTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/searchResultFacetsTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/test-data/entities/Customer.entity.json
=> DHFPROD-7301: (5.4) fix issue with exporting single column and DHFPROD-7303 Include primary key default selected properties 

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/exportSearchAsCSV.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/exportSearchAsCSVTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/searchResultFacetsTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/test-data/entities/Customer.entity.json
Adding both bugs to this single PR each with separate commits. I didn't want to have to deal with potential conflicts since they are closely related.
```diff
```
=> DHFPROD-7301: fix issue with exporting single column and DHFPROD-7303 Include primary key default selected properties

marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling.js, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/types/common-types.ts, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/getModelReferences.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/findEntitiesWithForeignKeyReferences.sjs
…ssociated with them
```diff
```
=> DHFPROD-7263:Prevent deletion of entities that have join properties associated with them

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/preview-matching-activity-lib.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/previewMatchingActivity.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/entity-lib/findEntityIdentifiers.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/entity-lib/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/entity-lib/test-data/content/person1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/entity-lib/test-data/content/person2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/entity-lib/test-data/entities/PersonModel.entity.json
=> DHFPROD-7169: Add primary keys to matching preview response

marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-7330: Explore All Data shows data when entity models are empty

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/expandable-table-view/expandable-table-view.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/expandable-table-view/expandable-table-view.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
=> DHFPROD-7270: Add structured properties to the test matched result table

marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/monitor/facet-props.js, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx, marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.test.tsx, marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.tsx, marklogic-data-hub-central/ui/src/components/monitor-selected-facets/monitor-selected-facets.test.tsx, marklogic-data-hub-central/ui/src/components/monitor-selected-facets/monitor-selected-facets.tsx, marklogic-data-hub-central/ui/src/components/monitor-sidebar/monitor-sidebar.tsx, marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.tsx, marklogic-data-hub-central/ui/src/components/sidebar-footer/sidebar-footer.tsx, marklogic-data-hub-central/ui/src/config/monitoring.config.js, marklogic-data-hub-central/ui/src/pages/Monitor.module.scss, marklogic-data-hub-central/ui/src/pages/Monitor.tsx, marklogic-data-hub-central/ui/src/util/monitor-context.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
Also includes DHFPROD-7203
```diff
```
=> DHFPROD-7205: Filter based on step and flow name

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling.js, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx
Support for Structured property in single ruleset form.
```diff
```
=> DHFPROD-7168: Select Structured Property in Single ruleset form

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job-query-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/jobs/queryHubJobs.sjs
=> DHFPROD-7123: Additional filter parameters for hubJobs endpoint

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/DisableJobOutputTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/EnableBatchOutputTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/WriteStepRunnerTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/test-data/steps/ingestion/ingestXmlCustomer.step.json
Did some renaming of "options" to "runtimeOptions" and "combinedOptions" to make the code more readable too. 
```diff
```
=> DHFPROD-7210: disableJobOutput now works as a flow option

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-utils/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-utils/test-data/entities/Customer.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-utils/writeDocuments.sjs
=> DHFPROD-7302: (5.4) Better messages for common write errors

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/flow-utils/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/flow-utils/test-data/entities/Customer.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/flow-utils/writeContentArray.sjs
=> DHFPROD-7302: Better messages for common write errors

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/JobController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/JobControllerTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/JobService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/getMatchingPropertyValues.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/getMatchingPropertyValues.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job-query-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/test-data/jobs/test-doc1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/test-data/jobs/test-doc3.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/testFindStepResponses.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/testGetMatchingPropertyValues.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/lib/jobService.sjs
=> DHFPROD-7204: Popover Search Functionality

marklogic-data-hub-central/ui/src/components/facet/facet.module.scss, marklogic-data-hub-central/ui/src/components/monitor-selected-facets/monitor-selected-facets.tsx, marklogic-data-hub-central/ui/src/components/monitor-sidebar/monitor-sidebar.test.tsx, marklogic-data-hub-central/ui/src/components/monitor-sidebar/monitor-sidebar.tsx, marklogic-data-hub-central/ui/src/config/monitoring.config.js, marklogic-data-hub-central/ui/src/util/monitor-context.tsx
=> DHFPROD-7200: Filter on Start Time in Monitor page

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/Flow.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/IngestToFinalTest.java
Also renamed "overrideOptions" to "runtimeOptions" for consistency in Flow class
```diff
```
=> DHFPROD-7347: Removing duplicate collections in stepExecutionContext

examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub-central/gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DEVO-246:Datahub release 5.4.4

marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx, marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.tsx, marklogic-data-hub-central/ui/src/components/monitor-selected-facets/monitor-selected-facets.tsx, marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.test.tsx, marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.tsx, marklogic-data-hub-central/ui/src/config/tiles.config.ts, marklogic-data-hub-central/ui/src/pages/Monitor.module.scss, marklogic-data-hub-central/ui/src/pages/Monitor.tsx, marklogic-data-hub-central/ui/src/util/monitor-context.tsx
=> DHFPROD-7204:Filter based on step type

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.module.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.test.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java, marklogic-data-hub/src/main/resources/hub-internal-artifacts/step-definitions/mapping/marklogic/entity-services-mapping.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mapping.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/saveStep.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/CreateStepTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/removeAttachment/runMappingStepWithAndWithoutAttachment.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/removeAttachment/setup.sjs
=> DHFPROD-4270:Disable including attachment in mapped document

marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-common.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-operator.json, marklogic-data-hub/src/test/java/com/marklogic/bootstrap/TestAppInstaller.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubAdminTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubCommonTest.java
=> DHFPROD-7067: Adding new privileges pertaining to requests

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/ingestAndMapConnected/twoJsonDocs.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/hubURI.sjs
=> DHFPROD-7369: Fixing couple JS tests failing on ML 9

ml-data-hub-plugin/src/test/groovy/com/marklogic/hub/gradle/task/GenerateTestSuiteTaskTest.groovy
=> DHFPROD-7373: Fix for generateTestSuiteTask tests on Windows

marklogic-data-hub/src/main/resources/hub-internal-config/security/amps/evalInDatabase.json
Fix role name in 'evalInDatabase' amp
```diff
```
=> DHFPROD-7376:Fix role name in 'evalInDatabase' amp

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-es.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/hubEsTest.sjs
=> DHFPROD-7320: Adjust path for structured properties

marklogic-data-hub/src/test/java/com/marklogic/bootstrap/TestAppInstaller.java
=> DHFPROD-7378: Fixing creation of test users

examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DEVO-258:Datahub 5.5.0 beta release

marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubDeveloperTest.java
=> DHFPROD-7354: Fixing scheduled task test on nightly for 5.4

marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/job/impl/LegacyJobManagerImpl.java
=> DHFPROD-7370: Fix for Export legacy jobs on ML 9

NOTICE.txt
=> DEVO-263: updating notices.txt

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MappingStepController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MappingStepControllerTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MappingService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/getReferences.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/getReferences.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/user-parameters/testGetReferences.sjs
Support for selecting references in mapping UI in HC
```diff
```
=> DHFPROD-7283:Support for selecting references in mapping UI in HC

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
=> DHFPROD-7364: View when my matching configuration Test yields no matches

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/RunConnectedStepsViaMlcpTest.java
=> DHFPROD-7390: Fixing test to run against DHS

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/DeleteModelTest.java, marklogic-data-hub-central/ui/src/api/modeling.ts, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/types/common-types.ts, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MappingService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ModelsService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/getModelReferences.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/getModelReferences.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/findEntitiesWithForeignKeyReferences.sjs
:Prevent deletion of foreign key properties that have join properties associated with them
```diff
```
=> DHFPROD-7344:Prevent deletion of foreign key properties that have join properties associated with them

marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.module.scss, marklogic-data-hub-central/ui/src/components/monitor-selected-facets/monitor-selected-facets.tsx, marklogic-data-hub-central/ui/src/pages/Monitor.module.scss, marklogic-data-hub-central/ui/src/pages/Monitor.tsx
Design changes, approved by @jbelonoj 
```diff
```
=> DHFPROD-7314: Change page title on Monitoring screen

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/main/resources/scaffolding/custom-module/sjs/main-ingestion.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/CreateStepDefinitionTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateStepDefinitionTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/HubTask.groovy
Also moved logic for creating a step definition into ScaffoldingImpl so that it can be more easily tested, and then added a test for it
```diff
```
=> DHFPROD-7372: Custom ingestion module now uses flowApi

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/custom.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matchStepAdvanceSettingsWriter.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/reorderSteps.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
=> DHFPROD-7375: Cypress tests fix on Nightly linux and Win10 machines

marklogic-data-hub-central/build.gradle, marklogic-data-hub/build.gradle
=> DHFPROD-7379: Fix vulnerabilities found in Palamida scan

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/errorHandling/moreThanTenErrorsOccur.sjs
=> DHFPROD-7401: Only capturing up to 10 error messages

Jenkinsfile, marklogic-data-hub-central/build.gradle
=> DHFPROD-7356:Skip RTL and Cypress tests on BE PR's

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/preview-matching-activity-lib.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/previewMatchingActivity.sjs
=> DHFPROD-7345: +DHFPROD-7388 stabilize previewMatchActivity

Jenkinsfile
=> DEVO-281: Increase timeout in DHF regression pipeline

marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx, marklogic-data-hub-central/ui/src/api/modeling.ts, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.scss, marklogic-data-hub-central/ui/src/util/user-context.tsx
UI fixes for Mapping UI:
- Test/clear buttons in a fixed location 
- Whitespace reduced
- Only one scroll bar per container 
- Popup on refresh removed
No tests needed.
```diff
```
=> DHFPROD-7290: Make Test/Clear buttons in Mapping UI always accessible

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MergingStepController.java, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx, marklogic-data-hub-central/ui/src/api/merging.ts, marklogic-data-hub-central/ui/src/api/modeling.ts, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/validateMergingStepLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/validateSteps/validateMergingStep.sjs
Test cases will be added by @ngodugu-marklogic as part of https://project.marklogic.com/jira/browse/DHFPROD-7158
```diff
```
=> DHFPROD-6995: FE : Show warnings based on different views

Jenkinsfile
=> DHFPROD-7398: Capture ML Logs in Jenkins archive on cypress failure

marklogic-data-hub-central/ui/src/pages/Monitor.tsx
=> DHFPROD-7120: Ensure job results is updated after remount

examples/reference-entity-model/steps/mapping/mapCustomersWithRelatedEntitiesJSON.step.json, examples/reference-entity-model/steps/mapping/mapCustomersWithRelatedEntitiesXML.step.json, marklogic-data-hub-central/ui/src/assets/mock-data/curation/entity-definitions-mock.js, marklogic-data-hub-central/ui/src/assets/mock-data/curation/mapping.data.ts, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/mappable-entity-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getEntitiesForMapping/test-data/entities/Order.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getEntitiesForMapping/testGetEntitiesForUI.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/test-data/steps/mapping/mapCustomersJSON.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/test-data/steps/mapping/mapCustomersWithInvalidExpressions.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/test-data/steps/mapping/mapCustomersXML.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/test-data/steps/mapping/mapWithUriExpressionEvaluatesToNull.step.json
Ensure related entity mapping id is unique
```diff
```
=> DHFPROD-7402:Ensure related entity mapping id is unique

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/JobManager.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/amps/deleteJobs.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/privileges/data-hub-delete-jobs.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-developer.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-job-deleter.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/bulk/deleteJobs.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/bulk/deleteJobs.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/DeleteJobsTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/DeleteJobsTask.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/DeleteLegacyJobsTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/LegacyJobDeleteTaskTest.groovy
=> DHFPROD-6731: and DHFPROD-6732: Bulk Data Service and Gradle Task to delete jobs data

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunFlowWithWriteErrorTest.java, marklogic-data-hub/src/test/resources/test-projects/simple-custom-step/modules/root/custom-modules/custom/simpleCustomStep/writeErrorStepModule.sjs
=> DHFPROD-7414: Step write errors are now handled correctly

marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
UI changes are approved by @jbelonoj.
```diff
```
=> DHFPROD-7362: Expand/Collapse Parent Structured Types in Single Ruleset form, and view tooltips for Reduce toggle in single and Multiple Ruleset form

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/mlcp-flow-transform.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/RunConnectedStepsViaMlcpTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/mlcp/MlcpRunner.java
Avoids escaping issues on Windows by creating a temp options file to hold the transform_param.
```diff
```
=> DHFPROD-7426: Fix MLCP related unit test failures on Windows

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs
=> DHFPROD-7423: Fix for getJobDetails MlUnit test on 9.0-11

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/thesaurus.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/helper-impl.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity2/previewMatchingActivity.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/synonym/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/synonym/test-data/content/bob.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/synonym/test-data/content/robbie.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/synonym/test-data/content/robert.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/synonym/test-data/entities/MasteringTestEntity.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/synonym/thesaurus-expand.xqy
=> DHFPROD-7368: Synonym match type not working properly with range index

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-settings/entity-settings.tsx
=> DHFPROD-7291: Add e2e for related entity advance settings

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/RunConnectedStepsViaMlcpTest.java
=> DHFPROD-7410: Avoiding duplicate collections

marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/MappingPerformanceTool.java
=> DHFPROD-7324: Initial tool for testing mapping performance

marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/gradle.properties, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/SwaggerConfig.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/WebMvcConfig.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/auth/WebSecurityConfiguration.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EntitySearchController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/JobController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/MappingController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/CustomStepController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/IngestionStepController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MappingStepController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MatchingStepController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MergingStepController.java, marklogic-data-hub-junit5/build.gradle, marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle
=> DHFPROD-7406: Update middle-tier dependencies

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/DeleteJobsTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/hub/gradle/task/DeleteJobsTaskTest.groovy
Also moved DeleteJobsTask to hub.task
```diff
```
=> DHFPROD-6732: Added smoke test for hubDeleteJobs

marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
=> DHFPROD-7368: Account for synonym fix in e2e mastering test

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/login.tsx
=> DHFPROD-7375: Cypress tests fix on Nightly

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/advanced-settings-dialog.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/detail.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx
=> DHFPROD-7346: Add e2e for source attachment in mapped docs

marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/JobService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/getJob.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/getJobWithDetails.sjs
=> DHFPROD-7357: Address 500 error retrieving job details

marklogic-data-hub-central/ui/src/components/job-response/job-response.module.scss, marklogic-data-hub-central/ui/src/components/job-response/job-response.scss, marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.test.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx, marklogic-data-hub-central/ui/src/util/date-conversion.tsx
=> DHFPROD-7315:Small fix requests for Monitoring table

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/setup.xqy
=> DHFPROD-7430: Add time for trigger to previewMatchActivity test

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/advanced-settings-dialog.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/create-edit-mapping-dialog.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
Added an e2e test along with the fix for this issue.
```diff
```
=> DHFPROD-7429: Advanced Settings in mapping details not saving/persisting correctly

marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx, marklogic-data-hub-central/ui/src/pages/Monitor.tsx
=> DHFPROD-7361:e2e test coverage for facets on monitoring tile

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/security/describe-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/security/describeSimpleRole.sjs
=> DHFPROD-7455: Fixing bug in hubDescribeRole

marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx, marklogic-data-hub-central/ui/src/components/monitor-sidebar/monitor-sidebar.tsx, marklogic-data-hub-central/ui/src/util/monitor-context.tsx
=> DHFPROD-7418: Clearing applied facet clears only the facet attribute

marklogic-data-hub/src/main/resources/hub-internal-config/database-fields/staging-database.xml, marklogic-data-hub/src/main/resources/ml-config/database-fields/final-database.xml
=> DHFPROD-7463: Turning off positions for metadata field range indexes on staging and final databases

examples/reference-entity-model/README.md, examples/reference-entity-model/src/main/ml-modules/root/custom-modules/mapping-params/example-mapping-params.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/getReferences.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/user-parameters/test-data/bad-get-parameter-values.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/user-parameters/test-data/user-params.sjs
=> DHFPROD-7453: Including mappingStep in getParameterValues

marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-7267: Explorer failing test fixes

marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/ingestMapMaster/setup.sjs
=> DHFPROD-7467: Clear schemas databases before running the test

marklogic-data-hub/src/test/java/com/marklogic/bootstrap/TestAppInstaller.java
=> DHFPROD-7464: Include the four groups for provisioned env

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/ingestMapMaster/ingestMapMatchMerge.sjs
=> DHFPROD-7467: Refactor test to not assert on the triple array length

Jenkinsfile
=> DEVO-295: avoid abortion of regression pipeline

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addCustomStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
=> DHFPROD-7468: e2e tests failing on HC-on perm parallel

examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DEVO-297:Datahub 5.5.0 release

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/mapping-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/getXpathFunctionsThatDoNotWorkInMappingExpressions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateAndRunMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/buildAndRunPropertyMappings.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/handleUndefinedFunctionError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/lib/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/setup.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/test-data/content/customer.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/public/flow/flowApi/runStepOnContent/runMappingStepWithError.sjs
Throw better when encountering XDMP_UNDFUN in mappings. This is not be merged until error messages are finalized and respective stories groomed. Creating PR just for review.
```diff
```
=> DHFPROD-7148:Handle XDMP_UNDFUN error in mapping step

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
=> DHFPROD-7451: Add spinner for entity properties load in mapping

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/mapping-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/invalidArgumentError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/setup.sjs
Handle XDMP-ARGTYPE error in mapping step
```diff
```
=> DHFPROD-7446:Handle XDMP-ARGTYPE error in mapping step

pipeline.properties
=> DEVO-297: fix pipeline properties to pint to feature/5.5-develop

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/mapping-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/getXpathFunctionsThatDoNotWorkInMappingExpressions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateAndRunMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/buildAndRunPropertyMappings.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/handleUndefinedFunctionError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/lib/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/setup.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/test-data/content/customer.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/public/flow/flowApi/runStepOnContent/runMappingStepWithError.sjs
Handle XDMP_UNDFUN error in mapping step
```diff
```
=> DHFPROD-7148:Handle XDMP_UNDFUN error in mapping step(5.5.1)

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/mapping-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/invalidArgumentError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/setup.sjs
Handle XDMP-ARGTYPE error in mapping step
```diff
```
=> DHFPROD-7446:Handle XDMP-ARGTYPE error in mapping step(5.5.1)

Jenkinsfile
=> DEVO-307: Investigate why code-review stage is not executed

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMergeOptionsLib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/conversion/FlowConverterTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/updateMergeOptions.sjs
=> DHFPROD-7503: 'default' is now converted in a merge strategy

installer-for-dhs/build.gradle, marklogic-data-hub-central/build.gradle, marklogic-data-hub-client-jar/build.gradle
=> DHFPROD-4705: Update gradle configs

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/CreateAndUpdateModelTest.java
=> DHFPROD-7343: Deleted index gets restored on final db

marklogic-data-hub-central/ui/src/components/date-time-facet/date-time-facet.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
=> DHFPROD-7415:Calendar cut off in facet sidebar

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matchWarnings.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeWarnings.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/merge-rule-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/merge-strategy-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
=> DHFPROD-7158: e2e tests for showing matching and merging warnings

marklogic-data-hub-central/build.gradle, marklogic-data-hub/build.gradle
=> DHFPROD-7461: Resolving vulnerability: CVE-2016-6303(High Critical)

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/mapping-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/cannotComputeError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/setup.sjs
Handle XDMP-COMPUTE error in mapping step
```diff
```
=> DHFPROD-7447:Handle XDMP-COMPUTE error in mapping step

marklogic-data-hub-junit5/build.gradle
=> DHFPROD-7511: Added pom stuff for marklogic-data-hub-junit5

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/mapping-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/cannotComputeError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/setup.sjs
Handle XDMP-COMPUTE error in mapping step
```diff
```
=> DHFPROD-7447:Handle XDMP-COMPUTE error in mapping step(5.5.1)

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/mapping-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateAndRunMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/cannotComputeError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/invalidLexicalValueError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/setup.sjs
Handle XDMP-LEXVAL error in mapping step
```diff
```
=> DHFPROD-7445:Handle XDMP-LEXVAL error in mapping step

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/mapping-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateAndRunMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/invalidLexicalValueError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/setup.sjs
Handle XDMP-LEXVAL error in mapping step
```diff
```
=> DHFPROD-7445:Handle XDMP-LEXVAL error in mapping step(5.5.1)

marklogic-data-hub-central/ui/src/assets/mock-data/curation/merging.data.ts, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
- Making duplicate PR for 5.5 branch, originally PR has already been merged to develop
```diff
```
=> DHFPROD-7454: Default Merge Strategies in Hub Central

marklogic-data-hub-central/ui/src/config/overview.config.ts
Required for correct documentation links. Video Tutorial links will stay at 5.4 for now.
```diff
```
=> DHFPROD-7513: Update Overview content to version 5.5

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/options.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMergeOptionsLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/updateMergeOptions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/defaultMergeStrategy.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/test-data/content/CustMatchMerge1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/test-data/content/CustMatchMerge2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/test-data/content/customerMatchSummary.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/test-data/defaultMergingFunction.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/test-data/entities/Customer.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/test-data/steps/merging/mergeCustomers.step.json
=> DHFPROD-7454: (5.5.1) Back-end work for default merge strategies in new steps

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/options.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMergeOptionsLib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/updateMergeOptions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/defaultMergeStrategy.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/test-data/content/CustMatchMerge1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/test-data/content/CustMatchMerge2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/test-data/content/customerMatchSummary.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/test-data/defaultMergingFunction.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/test-data/entities/Customer.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/test-data/steps/merging/mergeCustomers.step.json
=> DHFPROD-7454: Back-end work for default merge strategies in new steps

marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/setup.xqy
=> DHFPROD-7519: Wait for indexes before unit test

marklogic-data-hub-central/ui/e2e/package.json
=> DHFPROD-7484: Make E2E tests compatible with Firefox

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/MappingControllerTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/mapping-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateNestedMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/testMappingTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/badXPathError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/setup.sjs
Handle "Invalid XPath expression" error in mapping step
```diff
```
=> DHFPROD-7465:Handle "Invalid XPath expression" error in mapping step(5.5.1)

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/MappingControllerTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/mapping-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateNestedMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/testMappingTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/badXPathError.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mapping-errors/setup.sjs
Handle "Invalid XPath expression" error in mapping step
```diff
```
=> DHFPROD-7465:Handle "Invalid XPath expression" error in mapping step

marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.module.scss, marklogic-data-hub-central/ui/src/pages/Modeling.tsx
Design changes approved by @jbelonoj 
```diff
```
=> DHFPROD-7404:Hub Central unsaved model information scrolls off the screen

marklogic-data-hub-central/ui/src/config/overview.config.ts
Required for correct documentation links. Video Tutorial links will stay at 5.4 for now.
```diff
```
=> DHFPROD-7513: (5.5.1) Update Overview content to version 5.5

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addCustomStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx
=> DHFPROD-7523: Fix for e2e test failures on feature/5.5 develop branch

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss
=> DHFPROD-7450: Take horizontal scrolling out of entity tables (5.5.1) 

marklogic-data-hub-central/ui/ui_perf_tests/README.md, marklogic-data-hub-central/ui/ui_perf_tests/bottom-heavy/editXPath.js, marklogic-data-hub-central/ui/ui_perf_tests/bottom-heavy/index.js, marklogic-data-hub-central/ui/ui_perf_tests/bottom-heavy/mappingPage.js, marklogic-data-hub-central/ui/ui_perf_tests/bottom-heavy/nestedProps.js, marklogic-data-hub-central/ui/ui_perf_tests/bottom-heavy/perfHelper.js, marklogic-data-hub-central/ui/ui_perf_tests/bottom-heavy/testButton.js, marklogic-data-hub-central/ui/ui_perf_tests/config.json, marklogic-data-hub-central/ui/ui_perf_tests/even/editXPath.js, marklogic-data-hub-central/ui/ui_perf_tests/even/index.js, marklogic-data-hub-central/ui/ui_perf_tests/even/mappingPage.js, marklogic-data-hub-central/ui/ui_perf_tests/even/nestedProps.js, marklogic-data-hub-central/ui/ui_perf_tests/even/perfHelper.js, marklogic-data-hub-central/ui/ui_perf_tests/even/testButton.js, marklogic-data-hub-central/ui/ui_perf_tests/top-and-bottom-heavy/editXPath.js, marklogic-data-hub-central/ui/ui_perf_tests/top-and-bottom-heavy/index.js, marklogic-data-hub-central/ui/ui_perf_tests/top-and-bottom-heavy/mappingPage.js, marklogic-data-hub-central/ui/ui_perf_tests/top-and-bottom-heavy/nestedProps.js, marklogic-data-hub-central/ui/ui_perf_tests/top-and-bottom-heavy/perfHelper.js, marklogic-data-hub-central/ui/ui_perf_tests/top-and-bottom-heavy/testButton.js, marklogic-data-hub-central/ui/ui_perf_tests/top-heavy/editXPath.js, marklogic-data-hub-central/ui/ui_perf_tests/top-heavy/index.js, marklogic-data-hub-central/ui/ui_perf_tests/top-heavy/mappingPage.js, marklogic-data-hub-central/ui/ui_perf_tests/top-heavy/nestedProps.js, marklogic-data-hub-central/ui/ui_perf_tests/top-heavy/perfHelper.js, marklogic-data-hub-central/ui/ui_perf_tests/top-heavy/testButton.js
=> DHFPROD-7298: Mapping UI performance: Create performance tests

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/config/mapping.config.js
=> DHFPROD-7449: Scroll to respective tables when pagination is applied (5.5.1) 

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
=> DHFPROD-7396: Move URI info, reduce whitespace in Mapping UI

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowProvenance.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/prov.sjs
=> DHFPROD-7457: Convert Provenance code to library instead of class instance

marklogic-data-hub-central/ui/src/hooks/use-interval-worker.js, marklogic-data-hub-central/ui/src/hooks/use-interval.tsx
=> DHFPROD-7501: (5.5.1) Use Worker for interval to avoid sleep

examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DEVO-330: Datahub 5.5.1 release

marklogic-data-hub-central/ui/src/hooks/use-interval-worker.js, marklogic-data-hub-central/ui/src/hooks/use-interval.tsx
=> DHFPROD-7501: Use Worker for interval to avoid sleep

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/system/finishHubDeployment.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/provenance/prov-lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/FinishHubDeploymentCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/entity/EntityServicesAlignmentTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java
=> DHFPROD-7524: Deploy PROV TDE extension to staging and final schemas db

marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.module.scss, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx
- https://drive.google.com/file/d/1BXmybOWH_Iz5gLWDgO4ZICOF5YjwkQ27/view
- Design reviewed by Jamie
```diff
```
=> DHFPROD-6656: Card selector loses rounded edges

specs/xml/Provenance.xsd
=> DHFPROD-7152: Add provenance schema to project

marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx
=> test-react-graph-vis: Test code for the graph library

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx
=> test-react-graph-vis: More updates

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/properties-tab/properties-tab.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.scss, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx
- Added Property Table in Graph view side panel Properties tab
- Add, Edit, and Delete functionality for properties in the table works as well
- https://drive.google.com/file/d/1HWDB78yzktglE-I66SxpMunebiwCIJz-/view
- Designs reviewed by Jamie
```diff
```
=> DHFPROD-7436: View Properties in Graph view

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/ClearUserSchemasTest.java, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/ClearUserSchemasTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/BaseTest.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/ClearUserSchemasTaskTest.groovy
Clear user schemas
```diff
```
=> DHFPROD-7020:Clear user schemas

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java
Endpoint for running flows from HC
```diff
```
=> DHFPROD-7541:Endpoint for running flows from HC

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx
=> test-react-graph-vis: Trying fontAwesomeIcons

marklogic-data-hub-spark-connector/README.md
=> DHFPROD-7571: Improvements to Spark README

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java
I had to update a couple existing tests, which I think in hindsight were erroneously expecting the wrong job status. If stopOnError=true, and the collector fails, then a user expects the flow to be stopped and no other steps to execute, which means the job status should be stop-on-error. 
```diff
```
=> DHFPROD-7570: stopOnError now works when the collector fails

CODEOWNERS
=> DHFPROD-7580:Update code owners file

marklogic-data-hub-central/ui/e2e/cypress.json, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx
=> DHFPROD-7485: Fix E2E tests to run on DHS

.github/PULL_REQUEST_TEMPLATE.md, Jenkinsfile
=> DHFPROD-7527: Optionally run the UI tests on BE PRs

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/api/graph-vis-api-for-testing.js, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx, marklogic-data-hub-central/ui/src/types/common-types.ts
=> DHFPROD-7537: Adding code to handle tests later

installer-for-dhs/build.gradle
=> DEVO-350: add publishing task to installer-for-dhs module

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
- https://drive.google.com/file/d/173y-Y4g0jGPW6_65JCTtxzOjjbqFjfWD/view
```diff
```
=> DHFPROD-7601: Adjust XML view of page size for mapping UI

Jenkinsfile
=> DEVO-360: No failures is reported if cypress has errors in its log

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.module.scss, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.scss, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.scss
=> DHFPROD-5878: Stop table scrolling in Explorer

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/pages/Run.module.scss, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx
=> DHFPROD-7132: Run flows from Run tile

examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle
=> DEVO-363:Datahub 5.5.2 release

marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/JobService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/amps/update-provenance-record.json, marklogic-data-hub/src/main/resources/hub-internal-config/security/amps/write-provenance-record.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/finishJob.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/startJob.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/startJob.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/provenance/dh-provenance.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/provenance/prov-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/lib/jobService.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/provenance/data-hub-provenance/lib/dh-prov-assert-lib.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/provenance/data-hub-provenance/setup.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/provenance/data-hub-provenance/verifyNewProvenanceRecord.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/provenance/data-hub-provenance/verifyProvenanceRecordOnFinishJob.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/provenance/data-hub-provenance/verifyProvenanceRecordOnStartJob.sjs
=> DHFPROD-7459: Create PROV records for Job/Step(s) at Job start

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
=> DHFPROD-7554: Match Combinations box should not take over entire page

marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle
=> DHFPROD-7623: Removed OBE bintray config

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/JobControllerTest.java
=> DHFPROD-7586: Ensure TDEs are installed for JobControllerTest

Jenkinsfile
=> DEVO-362: fix fake success ( green ) in UI tests if stage was faild

marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/DeployToReplicaTest.java
=> DHFPROD-7632: Fix for DeployToReplicaTest

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/provenance/data-hub-provenance/lib/dh-prov-assert-lib.xqy
=> DHFPROD-7632: Fix for RunMarkLogicUnitTestsTest

marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/DeployToReplicaTest.java
=> DHFPROD-7632: Trying to fix DeployToReplicaTest

marklogic-data-hub-central/build.gradle
=> DHFPROD-7629: Fix for HC after Spring Boot upgrade

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss
Mapping error cuts off in middle of word
```diff
```
=> DHFPROD-7539:Mapping error cuts off in middle of word

marklogic-data-hub-central/build-rpm.gradle
=> DHFPROD-7629: Fix for rpm build

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/buildAndRunPropertyMappings.sjs
Include number of entity instances created by mapping when "Test" button is clicked
```diff
```
=> DHFPROD-7428:Include number of entity instances created by mapping when "Test" button is clicked

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx, marklogic-data-hub-central/ui/src/config/graph-vis.config.ts
- Convert graph nodes from custom SVG to box shapes
- Move non-dynamic graph settings data to new config file: `config/graph-vis.config.ts`
- Some refactoring and cleanup
- Graph testing is being worked on separately
```diff
```
=> DHFPROD-7659: Convert graph nodes from custom SVG to box shapes

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/CreateAndUpdateModelTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/createModel.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateModelEntityTypes.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateModelInfo.sjs, specs/models/ModelDescriptor.json
CRUD for entity node coordinates to support graph display
```diff
```
=> DHFPROD-7620:CRUD for entity node coordinates to support graph display

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-vis.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
This PR involves only the template and examples of the hooks created in cypress for graph vis library. Those can be used further to locate and test graph nodes and edges.
```diff
```
=> DHFPROD-7609: Creating the testing hooks for graph vis library in cypress

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/exceptions/CustomExceptionHandler.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/HubCentral.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/ModelDescriptor.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/schemas/Modeling.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/ExceptionThrowingController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/exceptions/CustomExceptionHandlerTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/exceptions/HandleIOExceptionTest.java
Also updated a few HC schema classes based on changes to the underlying JSON schema files
```diff
```
=> DHFPROD-7631: Better handling of broken pipe error

ml-data-hub-plugin/build.gradle
=> DHFPROD-7629: Fixing compile error in ml-data-hub

examples/reference-entity-model/steps/ingestion/loadCustomersJSON.step.json, examples/reference-entity-model/steps/ingestion/loadCustomersXML.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-es.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/prov.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/provenance/dh-provenance.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/provenance/prov-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/provenance/provenanceWriteQueue.sjs, marklogic-data-hub/src/main/resources/ml-modules/transforms/mlRunIngest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/provenance/sourceProvenance.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/provenance/provenanceDocumentQueries.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/provenance/setup.xqy
=> DHFPROD-7568: Provide functions to query PROV information

Jenkinsfile
=> DEVO-372: regressions build fails. error: No such property: CHANGE_URL

marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub-central/ui/e2e/hc-qa-project/gradle/wrapper/gradle-wrapper.properties
Also fixed reference to the ML Maven repo so that https is used
```diff
```
=> DHFPROD-7629: Updating Gradle wrapper in HC QA project

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/core-functions-impl.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/MappingTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/runMapping.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/parseDate.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/simpleTests/mapping-test.sjs
Include timezone for parseDate() response
```diff
```
=> DHFPROD-7645:Include timezone for parseDate() response

marklogic-data-hub-central/ui/puppeteer_tests/graph-vis/README.md, marklogic-data-hub-central/ui/puppeteer_tests/graph-vis/config.json, marklogic-data-hub-central/ui/puppeteer_tests/graph-vis/index.js, marklogic-data-hub-central/ui/puppeteer_tests/graph-vis/loadGraphUI.js, marklogic-data-hub-central/ui/puppeteer_tests/graph-vis/perfHelper.js
=> DHFPROD-7538: Test performance of graph UI

Jenkinsfile
=> DEVO-373: DHF regressions cut off if dhs-test stage fails

Jenkinsfile, build.gradle, examples/README.md, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/reference-entity-model/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, examples/step-interceptors/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, performance-tests/projects/commoncrawl/build.gradle
=> DEVO-375: Update version to 5.6-snapshots and allow insecure protocols

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling-context-mock.js, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/types/modeling-types.ts, marklogic-data-hub-central/ui/src/util/modeling-context.tsx
=> DHFPROD-7611: Delete entity type from graph view

build.gradle, marklogic-data-hub-api/build.gradle, marklogic-data-hub-junit5/build.gradle, marklogic-data-hub-test/build.gradle, marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle
=> DEVO-365: Allow insecure protocols for publising

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/entity-lib/findEntityIdentifiers.sjs
I am unable to reproduce the test. Logging more information for 'findEntityIdentifiers' test for debugging next time the issue occurs
```diff
```
=> DHFPROD-7699:Logging more information for 'findEntityIdentifiers' test

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
Demo: https://drive.google.com/file/d/1SrOX5_9Bq8mwjUD0PAxiKeCbb9oLsJGq/view?usp=sharing
```diff
```
=> DHFPROD-7533: Filter for entity types in Graph UI

Jenkinsfile
=> DHFPROD-7327: Create jenkins job for DHCCE Nightly regression

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/index.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/relationship-modal.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling.js, marklogic-data-hub-central/ui/src/assets/one-to-many-white.svg, marklogic-data-hub-central/ui/src/assets/one-to-many.svg, marklogic-data-hub-central/ui/src/assets/one-to-one.svg, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx
- Edit relationship via clicking on edge in graph view; can edit relationship name, join property, and cardinality
- Out of scope: Swapping, Delete relationship, target entity dropdown
- RTL and Cypress tests added
- https://drive.google.com/file/d/1krFjAQkg0j0-ivmyT8cYGRGSYo3rQvo1/view
```diff
```
=> DHFPROD-7530: Showing and editing relationships between entity types

Jenkinsfile
=> DEVO-376: Setting PR pipeline

CODEOWNERS
=> DHFPROD-7715: Removed asonvane from codeowners

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
=> DHFPROD-7359: Add tooltips for mapping dropdown icons

marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/FlowStatusListener.java, marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/mapping/MappingValidator.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/StepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/ml-modules/services/mlMappingValidator.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/ValidateMappingTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/WriteStepRunnerTest.java
=> DHFPROD-7701: Restoring deleted code that DHHCE needs

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/uberModel/twoModelsWithSharedEntityTypeName.sjs
Added a test to capture what may seem like a bug is actually expected behavior
```diff
```
=> DHFPROD-7713: Documenting how uber-model work

marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
=> DHFPROD-7702: Fix E2E Monitor monitorTableValidations.spec.tsx test

Jenkinsfile
=> DHFPROD-7720: Use Nexus Nexus

Jenkinsfile
=> DHFPROD-7720: Using new Nexus and Fixes to build Stage

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/buildAndRunPropertyMappings.sjs
Include a space in the message text
```diff
```
=> DHFPROD-7428:Include a space in the message text

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graph.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/util/modeling-context.tsx
Screencast here: https://drive.google.com/file/d/1e4wdlhIGGY4Hm4-RhigH8efHlsdcLtA4/view
E2E test added in new graph.spec.tsx file. 
```diff
```
=> DHFPROD-7532: Add new entity type from graph UI

ml-data-hub-plugin/build.gradle
=> DHFPROD-7743: Fix testFullCycle task

Jenkinsfile
=> DHFPROD-7720: Download artifacts from new nexus

examples/dh-5-example/build.gradle
=> DHFPROD-7742: Replacing deprecated compile with implementation

marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubModulesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/models/SaveModelTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadHubModulesWithSingleAppServerTest.java
Just want to run the tests, no reviewers yet. 
```diff
```
=> DHFPROD-7716: Can load hub modules when staging and final are the same

marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java
Fix EndToEndFlowTests in Windows
```diff
```
=> DHFPROD-7630:Fix EndToEndFlowTests in Windows

Jenkinsfile
=> DHFPROD-7720: Download from New nexus

Jenkinsfile
=> DHFPROD-7720: copy gradle props from home

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
=> DHFPROD-7764: Fix E2E tests failing on feature/ant-lib-replacement

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/merge-rule-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-table.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.scss, marklogic-data-hub-central/ui/src/components/entities/matching/multi-slider/multi-slider.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
=> DHFPROD-7768: Threshold and ruleset handle names are not displayed

Jenkinsfile
=> DHFPROD-7720: Fixing props

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/customdata/ExploreCustomEntityInstancesTest.java, marklogic-data-hub/src/test/resources/test-projects/custom-data/README.md, marklogic-data-hub/src/test/resources/test-projects/custom-data/entities/Person.entity.json, marklogic-data-hub/src/test/resources/test-projects/custom-data/modules/root/custom-data-modules/my-entity-type-constraint.xqy, marklogic-data-hub/src/test/resources/test-projects/custom-data/modules/root/custom-data-modules/my-options-post-processor.xqy
=> DHFPROD-7717: Can now modify DHF-generated search options

Jenkinsfile
=> DHFPROD-7720: Make directory and copy props-- TEST PR

README.md
=> DUMMY PR for testing the merge.

Jenkinsfile
=> DHFPROD-7720: Make direcctory and copy props

Jenkinsfile
=> DHFPROD-7720:Make directory and copy props

performance-tests/build.gradle, performance-tests/gradle.properties, performance-tests/src/main/jmeter/disable-job-output.jmx
Note: the story itself will not be completed until I have written a performance report regarding the results.
```diff
```
=> DHFPROD-6147: Test performance of disableJobOutput

marklogic-data-hub-central/ui/src/components/header/header.module.scss, marklogic-data-hub-central/ui/src/components/header/header.tsx
=> DHFPROD-7680: Component Replacement: Avatar

marklogic-data-hub-central/ui/src/components/entities/matching/expandable-table-view/expandable-table-view.tsx
=> DHFPROD-7683: Component Replacement: Progress

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-vis.tsx, marklogic-data-hub-central/ui/src/components/async-loader/async-loader.module.scss, marklogic-data-hub-central/ui/src/components/async-loader/async-loader.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/components/login-form/login-form.tsx, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-7684: Component Replacement: Spin

marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/WriteJobsDataTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/rejectFromFlow.sjs
=> DHFPROD-7473: (5.5.3) Ensure data-hub-job-internal role can update jobs

marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/WriteJobsDataTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/jobs.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/rejectFromFlow.sjs
=> DHFPROD-7473: (ant-lib) Ensure data-hub-job-internal role can update jobs

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/HCTheme.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/index.tsx
=> DHFPROD-7744: Component Replacement: Create a theme on bootstrap 

marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx
=> DHFPROD-7687:  Component Replacement: Col, Row

CODEOWNERS
=> DHFPROD-7810: Updating CODEOWNERS

marklogic-data-hub-central/ui/e2e/cypress.json, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/multi-slider.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx
Will be working on slider moving validations as part of DHFPROD-7815
```diff
```
=> DHFPROD-7619: new vis-js-timeline slider validations on match page

marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java
=> DHFPROD-7630:Fix 4.x mlcp flow in Windows

marklogic-data-hub-central/ui/src/components/column-selector/column-selector.tsx, marklogic-data-hub-central/ui/src/components/common/hc-divider/hc-divider.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-divider/hc-divider.test.tsx, marklogic-data-hub-central/ui/src/components/common/hc-divider/hc-divider.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.module.scss, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.module.scss, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/search-bar/search-bar.tsx, marklogic-data-hub-central/ui/src/components/sidebar-footer/sidebar-footer.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx
=> DHFPROD-7735: Component Replacement: Divider

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/relationship-modal.tsx, marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling.js, marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
- Can now create relationships via dragging edges between nodes or clicking on a node with edit mode
- Demo here: https://drive.google.com/file/d/1-q9HPD2c7YoJ1I8GYNbMm20IEn-PtbGR/view
- UX approved by Jamie
```diff
```
=> DHFPROD-7574: Create relationship via Add relationship button

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MappingStepControllerTest.java, marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/AbstractHubClientTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/getDocument.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getUrisAndDoc.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/setup.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/test-data/beforeMain.sjs
Run 'beforeMain' interceptor on source record in mapping step. This PR currently contains backend work only, will include front end work in another PR.
```diff
```
=> DHFPROD-7600:Run 'beforeMain' interceptor on source record in mapping step

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/hooksAndInterceptors/test-data/addHeaders.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/hooksAndInterceptors/testHooksAndInterceptors.sjs, marklogic-data-hub/src/test/resources/entity-reference-model/modules/root/custom-modules/step-interceptors/addHeaders.sjs
=> DHFPROD-7809: Interceptor now runs against the correct database

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MappingStepControllerTest.java, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/curation/mapping.data.ts, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/getDocument.sjs
Run 'beforeMain' interceptor on source record in mapping step-FE
```diff
```
=> DHFPROD-7600:Run 'beforeMain' interceptor on source record in mapping step-FE

marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-5271: UI text in merge step details page

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/DeleteModelTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/PublishModelsTest.java, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ModelsService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/deleteDraftModel.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/deleteDraftModel.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/getModelReferences.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/ApplyDownloadedZipToProjectTest.java
=> DHFPROD-7804: Work on delete draft modal and added flag for draft model.

marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-draft-entity-validate-create.json, marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-draft-entity-validate-modify.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/draft-entity-model-validate-trigger.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-validate-trigger-lib.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/models/model-with-null-ref.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/models/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/models/test-data/content/modelWithNullRef.json
=> DHFPROD-7771: Allow null  for draft models

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
=> DHFPROD-7819: Fix for undefined flashing when moving the slider

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.module.scss, marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx
=> DHFPROD-7820: Hide the run flow button and run flow settings from 5.6

marklogic-data-hub-central/ui/e2e/cypress.json, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx
=> DHFPROD-7837: Resolving conflicts for Ant-lib-replacement branch

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/entity-lib/suite-setup.xqy
=> DHFPROD-7699: Wait for indexing before entity-lib tests

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-7794: Add final modeling Graph UI text

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/api/modeling.ts, marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling.js, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx, marklogic-data-hub-central/ui/src/config/graph-vis.config.ts, marklogic-data-hub-central/ui/src/pages/Modeling.tsx
- Can select colors when adding a new entity type or editing a new entity type in the graph view
- Out of scope but included: Relayed this work in the tabular view as well so color is visible in the table and can also be added/modified too.
- Demo: https://drive.google.com/file/d/1_XD1jmedmtYvrcdSpRoX50wJwF6ndHBt/view
```diff
```
=> DHFPROD-7444: Edit color in the Graph View

marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/components/common/hc-slider/hc-slider.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-slider/hc-slider.test.tsx, marklogic-data-hub-central/ui/src/components/common/hc-slider/hc-slider.tsx, marklogic-data-hub-central/ui/src/components/numeric-facet/numeric-facet.tsx
=> DHFPROD-7739: Component Replacement: Slider

marklogic-data-hub-central/ui/src/components/job-response/job-response.module.scss, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
=> DHFPROD-7777: Component Replacement: Descriptions

build.gradle, examples/README.md, examples/SLED/build.gradle, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/reference-entity-model/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, examples/step-interceptors/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, performance-tests/projects/commoncrawl/build.gradle
=> DEVO-401: Updating the version to 5.6.0-rc1

marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.module.scss, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.scss, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-7639: Improve tooltips for source query

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/src/assets/icon_closeTag.svg, marklogic-data-hub-central/ui/src/components/common/hc-tag/hc-tag.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-tag/hc-tag.test.tsx, marklogic-data-hub-central/ui/src/components/common/hc-tag/hc-tag.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx
DHFPROD-7740: Component Replacement Tag
```diff
```
=> DHFPROD-7740: Component Replacement: Tag

examples/SLED/entities/ClaimFHIR.entity.json, examples/SLED/entities/ClaimItem.entity.json, examples/SLED/entities/Member.entity.json, examples/SLED/entities/Provider.entity.json, examples/SLED/steps/mapping/HarmonizeClaimItems.step.json
=> DHFPROD-7836: Add entities to SLED MLS demo as example project

marklogic-data-hub-central/gradle/wrapper/gradle-wrapper.properties, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/e2e/hc-qa-project/gradle/wrapper/gradle-wrapper.properties, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-7507: Updated error message when type and property share a name.

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/src/components/common/hc-card/hc-card.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-card/hc-card.test.tsx, marklogic-data-hub-central/ui/src/components/common/hc-card/hc-card.tsx, marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.module.scss, marklogic-data-hub-central/ui/src/components/header/system-info.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.module.scss, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.module.scss, marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.module.scss, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx
Replaces the `antd` `<Card />` component with a new `<HCCard />` wrapping React-Bootstrap.
```diff
```
=> DHFPROD-7686: Component Replacement: Card

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/collections.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/merging.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mastering/default/checkOptions.sjs
=> DHFPROD-7849: Ensure targetCollections is preserved for merging

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx, marklogic-data-hub-central/ui/src/types/modeling-types.ts
=> DHFPROD-7878: Saving coordinates of all entity nodes in just one api call

build.gradle, examples/README.md, examples/SLED/build.gradle, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/reference-entity-model/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, examples/step-interceptors/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, performance-tests/projects/commoncrawl/build.gradle
=> DEVO-401: Updating the version to 5.6.0-rc2

Jenkinsfile
=> DHFPROD-7883: Update regressions to run on 10.0-7

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
- Minor text updates to match step details page
```diff
```
=> DHFPROD-7558: UI Text in Match Step Details Page

marklogic-data-hub/src/main/resources/ml-modules/services/mlSmMerge.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMerge/post.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMerge/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMerge/test-data/content/customer1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMerge/test-data/entities/Customer.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMerge/test-data/flows/CurateCustomerJSON.flow.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMerge/test-data/steps/matching/matchCustomers.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMerge/test-data/steps/merging/mergeCustomers.step.json
=> DHFPROD-7710: Enhanced error handling for mlSmMerge

marklogic-data-hub/src/main/resources/ml-modules/services/mlSmMatch.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMatch/post.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMatch/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMatch/test-data/content/customer1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMatch/test-data/content/customer2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMatch/test-data/entities/Customer.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMatch/test-data/flows/CurateCustomerJSON.flow.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMatch/test-data/steps/matching/matchCustomers.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMatch/test-data/steps/merging/mergeCustomers.step.json
=> DHFPROD-7708: Make mlSmMatch compatible with matching steps

marklogic-data-hub-central/ui/src/config/steps.config.ts, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
Tooltip and warning content.
Existing tests of field not affected.
```diff
```
=> DHFPROD-7738: Update Source Record Scope content in Mapping step

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.module.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx, marklogic-data-hub-central/ui/src/components/tiles/tiles.scss, marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
Note: Also fixed the line break issue for Add merge rules description. 
```diff
```
=> DHFPROD-7640: Improve tooltips for interceptors

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
=> DHFPROD-7838: Panned graph view coordinates are not persisted

marklogic-data-hub-central/ui/src/pages/Detail.module.scss, marklogic-data-hub-central/ui/src/pages/Detail.tsx
=> DHFPROD-7658: Cannot scroll vertically in entity instance view

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx
fix UI tests
adding aria label
```diff
```
=> DHFPROD-7856: Plus circle icon

examples/smart-mastering-complete/entities/Person.entity.json, examples/smart-mastering-complete/src/main/entity-config/databases/final-database.json, examples/smart-mastering-complete/src/main/entity-config/databases/staging-database.json, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/matching.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mastering/default/filterMatchingContent.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mastering/default/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mastering/default/test-data/content/matchSummary.json
=> DHFPROD-7867: Fix false positive merges detected in matchSummary files

marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.module.scss, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/components/search-results/search-results.module.scss, marklogic-data-hub-central/ui/src/components/search-results/search-results.tsx
=> DHFPROD-7783: Component Replacement: List

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss
=> DHFPROD-7914: Containment problem in Match Step Detail

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.module.scss, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/pages/Run.module.scss, marklogic-data-hub-central/ui/src/pages/Run.tsx
=> DHFPROD-7855: Punctuation icons replacement

NOTICE.txt
=> RC-2497: Updating the Notices

marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelMvcTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/ExploreCustomEntityInstancesTest.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs
=> DHFPROD-7892: Add endpoint to save Hub Central Config

marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-draft-entity-validate-create.json, marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-draft-entity-validate-modify.json, marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-entity-validate-create.json, marklogic-data-hub/src/main/resources/hub-internal-config/triggers/ml-dh-entity-validate-modify.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/draft-entity-model-validate-trigger.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-trigger.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-validate-trigger-lib.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-validate-trigger.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/models/model-with-null-ref.xqy
=> DHFPROD-7895: Allow empty relationship for published entities

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMatch/post.sjs
=> DHFPROD-7926: Fix syntax incompatible with ML 9

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/DeleteModelTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/PublishModelsTest.java, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/validate-entity/setup.xqy, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
=> DHFPROD-7935: Address intermittent nightly regressions

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/constants.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/notification-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/services/mlSmNotifications.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/match-and-merge/teardown.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merge-double-notify/teardown.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/getNotifications.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/postNotifications.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/putNotifications.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/test-data/content/customer1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/test-data/content/customer2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/test-data/content/notification1.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/test-data/content/notification2.xml
=> DHFPROD-7703: Notifications now go over all notifications collections.

performance-tests/build.gradle, performance-tests/src/main/jmeter/monitoring.jmx
When running this test, please use Piterations=300 (or some large number of flows) or change iterations in gradle.properties
```diff
```
=> DHFPROD-7598: Performance metrics: Monitoring

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx
=> DHFPROD-7897: Remove Related Entity from icon legend

marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
=> DHFPROD-7937: Add button misplaced in Curate Merge view

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/detail-header/detail-header.module.scss, marklogic-data-hub-central/ui/src/components/detail-header/detail-header.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/source-navigation/source-navigation.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/source-navigation/source-navigation.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.test.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.tsx, marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.test.tsx, marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.test.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx
fix lint
fix unit tests
```diff
```
=> DHFPROD-7852: Arrows replacement with chevron

marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/HCTheme.scss, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.tsx, marklogic-data-hub-central/ui/src/components/entities/page-header/page-header.tsx, marklogic-data-hub-central/ui/src/components/entities/page-header/page.header.test.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx
=> DHFPROD-7828: Component Replacement: PageHeader

Jenkinsfile
=> DEVO-409: Running tests on chrome

marklogic-data-hub-central/ui/e2e/cypress/fixtures/config/hubCentral.json, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graph.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts, marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/BabyRegistry.entity.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/Client.entity.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/Customer.entity.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/Order.entity.json, marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/Person.entity.json, marklogic-data-hub-central/ui/src/api/modeling.ts, marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling.js, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx, marklogic-data-hub-central/ui/src/config/modeling.config.ts, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/types/modeling-types.ts, marklogic-data-hub-central/ui/src/util/modeling-context.tsx
=> DHFPROD-7905: Persisting graph config data using new endpoint

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/createDraftModel.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/models/drafts/createDraftEntity.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/models/drafts/setup.sjs
=> DHFPROD-7902: Re-create an entity in draft mode

Jenkinsfile
=> DEVO-409: cypress tests on chrome and mac

marklogic-data-hub-central/ui/src/components/common/hc-datetime-picker/hc-datetime-picker.test.tsx, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/login-form/login-form.module.scss, marklogic-data-hub-central/ui/src/components/login-form/login-form.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.module.scss, marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx, marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx
=> DHFPROD-7857: Windows icons replacement

Jenkinsfile
=> DEVO-400: Fixing post stage

marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/AbstractHubClientTest.java, marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
Our logic for checking for active indexing and rebalancing was inverted. This corrects that. 
```diff
```
=> DHFPROD-7935: Fix nightly long running tests

marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view.tsx, marklogic-data-hub-central/ui/src/HCTheme.scss, marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.scss, marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/header/header.module.scss, marklogic-data-hub-central/ui/src/components/header/header.test.tsx, marklogic-data-hub-central/ui/src/components/header/header.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.module.scss, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/tiles/toolbar.module.scss, marklogic-data-hub-central/ui/src/pages/Modeling.module.scss, marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx
=> DHFPROD-7778: Component Replacement: Dropdown

marklogic-data-hub-api/src/main/java/com/marklogic/hub/HubClient.java, marklogic-data-hub-api/src/main/java/com/marklogic/hub/impl/HubClientImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/IngestToJobsTest.java
=> DHFPROD-7979: (5.5) Allow ingest to write to DB other than STAGING or FINAL

marklogic-data-hub-api/src/main/java/com/marklogic/hub/HubClient.java, marklogic-data-hub-api/src/main/java/com/marklogic/hub/impl/HubClientImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/IngestToJobsTest.java
=> DHFPROD-7979: Allow ingest to write to DB other than STAGING or FINAL

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EntitySearchController.java, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx, marklogic-data-hub-central/ui/src/util/data-conversion.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs
=> DHFPROD-7791: Validate entity model for showing content in Explorer tabular view

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
=> DHFPROD-7913: Hovering over entity type shouldn't show placeholder text

marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.test.tsx, marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/facet/facet-element.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.tsx
run lint
create unit test
```diff
```
=> DHFPROD-7778: Component Replacement: Checkbox

marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
Minor text edits, no test updates needed.
```diff
```
=> DHFPROD-7881: Update help text in popups

marklogic-data-hub-central/ui/e2e/cypress/integration/login/customRole.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
Also includes fix for the bug DHFPROD-7899.
```diff
```
=> DHFPROD-7917: Cannot center on node

Jenkinsfile
=> DHFPROD-8088: Setup develop branch for 5.6

marklogic-data-hub-central/ui/e2e/setup.sh
=> DHFPROD-8094: Ensure e2e runs with latest SNAPSHOT

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyDataInDatabases.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/column-selector/column-selector.tsx, marklogic-data-hub-central/ui/src/components/common/hc-search/hc-search.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-search/hc-search.test.tsx, marklogic-data-hub-central/ui/src/components/common/hc-search/hc-search.tsx, marklogic-data-hub-central/ui/src/components/search-bar/search-bar.module.scss, marklogic-data-hub-central/ui/src/components/search-bar/search-bar.tsx, marklogic-data-hub-central/ui/src/theme/HCVariables.scss
=> DHFPROD-7941: InputSearch: Component Replacement Input Search

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/saveModels.sjs
=> DHFPROD-8030: Flush XML/JSON schema cache

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/detail.tsx, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json
=> DHFPROD-8105: Upgrade bootstrap version 

marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.tsx
=> DHFPROD-7861: Irrelevant Delete feature when adding thresholds, rulesets in mastering

marklogic-data-hub-central/ui/src/components/common/confirm-yes-no/confirm-yes-no.tsx, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.module.scss, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx, marklogic-data-hub-central/ui/src/theme/HCTheme.scss
=> DHFPROD-8010: Generic replacement

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.tsx, marklogic-data-hub-central/ui/src/pages/Load.test.tsx
=> DHFPROD-7944: Input-Group-3

marklogic-data-hub-central/ui/src/components/header/system-info.module.scss, marklogic-data-hub-central/ui/src/components/header/system-info.tsx, marklogic-data-hub-central/ui/src/theme/HCTheme.scss
=> DHFPROD-8002: Modal header replacement

marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx
=> DHFPROD-7946: Input-Group-5

marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.module.scss, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.tsx, marklogic-data-hub-central/ui/src/theme/HCTheme.scss
=> DHFPROD-8013: Flow replacement

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.module.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.module.scss, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.tsx, marklogic-data-hub-central/ui/src/theme/HCTheme.scss
=> DHFPROD-8012: Load replacement

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.module.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/common/hc-input/hc-input.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.module.scss, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.test.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx
=> DHFPROD-7943: Component Replacement: Input Group 2

marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/src/components/common/hc-input/hc-input.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/edit-query-dialog/edit-query-dialog.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/edit-query-details.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.tsx
=> DHFPROD-7945: input-group-4

marklogic-data-hub-junit5/src/test/java/com/marklogic/hub/ext/junit5/ConcreteDataHubTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ArtifactService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/StepDefinitionManagerImpl.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/stepDefinition.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/setArtifact.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/setArtifact.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommandTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/DisableJobOutputTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunFlowWithWriteErrorTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunStepAsUserWithDefaultCollectionsTest.java, marklogic-data-hub/src/test/java/com/marklogic/hub/mapping/MappingPerformanceTool.java, marklogic-data-hub/src/test/resources/test-projects/multiple-stepDef/step-definitions/custom/multipleStepDefs/multipleStepDefs.step.json, marklogic-data-hub/src/test/resources/test-projects/multiple-stepDef/step-definitions/custom/multipleStepDefs/testAnotherStep.step.json, marklogic-data-hub/src/test/resources/test-projects/multiple-stepDef/step-definitions/custom/multipleStepDefs/testStep.step.json, ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/CreateFlowTask.groovy
=> DHFPROD-7948: Unable to deploy step definitions

marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling.js, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
=> DHFPROD-7993: Color of nodes doesn't change in relationship modal

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubModulesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
=> DHFPROD-7885: Fix modules timestamp file for Windows

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx
=> DHFPROD-8096: Fix e2e failures from ant merge on develop

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mapping/entity-services/function-metadata.xsl, marklogic-data-hub/src/test/resources/mapping-test/modules/root/custom-modules/mapping-functions/custom-mapping-function.sjs
=> DHFPROD-8027: XSLTs for custom mapping functions returning arrays fix

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/src/components/modal-status/modal-status.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.tsx
=> DHFPROD-8009: Modeling replacement

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx
- Duplicate PR of e2e fixes for 5.6-develop
```diff
```
=> DHFPROD-8096: Fix e2e failures

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/tiles.tsx, marklogic-data-hub-central/ui/src/App.tsx, marklogic-data-hub-central/ui/src/pages/Curate.tsx, marklogic-data-hub-central/ui/src/pages/Load.module.scss, marklogic-data-hub-central/ui/src/pages/Load.tsx, marklogic-data-hub-central/ui/src/pages/Run.module.scss, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx, marklogic-data-hub-central/ui/src/util/error-message-context.tsx
=> DHFPROD-8011: Page replacement

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.module.scss
=> DHFPROD-7847: Add missing tests for Publish Entity types

performance-tests/build.gradle, performance-tests/src/main/jmeter/provenance.jmx, performance-tests/src/main/jmeter/provenanceOff.jmx
The tests are ran in performance-tests dir. Before running tests, run "../gradlew prepareJMeter".
The tests are meant to be run after running gradle bootstrap (but you can run without it- just set the jmeter variables as needed)
To test provenance off:
run "../gradlew testProvenanceOff"
To test provenance set to coarse-grain:
run "../gradlew testCoarseGrain_LatestProvenancetrue" to run with provenance set to coarse-grain and latestProvenance set to true 
or run "../gradlew testCoarseGrain_LatestProvenancefalse"  to run with provenance set to coarse-grain and latestProvenance set to false
Once reviewed and merged, these tests will be put into PEAR.
```diff
```
=> DHFPROD-7549: Create performance tests for coarse-grain provenance

marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
=> DHFPROD-8135: Fix e2e verify step in flow

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.module.scss
- Example: https://watch.screencastify.com/v/iPgGz555HciPGAL2pRfz
- Design approved by UX
```diff
```
=> DHFPROD-8092: Add None option to foreign key dropdowns

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.module.scss
- Duplicate PR for 5.6-develop
```diff
```
=> DHFPROD-8092: Add None to foreign key dropdown

marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
=> DHFPROD-8149:Fix for nested table header on develop

marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
=> DHFPROD-8029: Hub Central UI white out when showing matching results

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/detect-mapping-functions.xslt, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/xquery-lib.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/getXpathFunctionsThatDoNotWorkInMappingExpressions.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getMappingFunctionsTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/getMappingFunctions.sjs
=> DHFPROD-8116: Accurately determine available mapping functions

Jenkinsfile
=> DEVO-437: Kill hc running from prev builds

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/src/components/common/hc-sider/hc-sider.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-sider/hc-sider.test.tsx, marklogic-data-hub-central/ui/src/components/common/hc-sider/hc-sider.tsx, marklogic-data-hub-central/ui/src/components/common/index.ts, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.module.scss, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.test.tsx, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.tsx, marklogic-data-hub-central/ui/src/components/facet/facet.module.scss, marklogic-data-hub-central/ui/src/components/footer/footer.module.scss, marklogic-data-hub-central/ui/src/components/footer/footer.test.tsx, marklogic-data-hub-central/ui/src/components/footer/footer.tsx, marklogic-data-hub-central/ui/src/components/header/header.module.scss, marklogic-data-hub-central/ui/src/components/header/header.tsx, marklogic-data-hub-central/ui/src/components/monitor-sidebar/monitor-sidebar.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.module.scss, marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx, marklogic-data-hub-central/ui/src/components/search-bar/search-bar.module.scss, marklogic-data-hub-central/ui/src/components/sidebar-footer/sidebar-footer.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.test.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx, marklogic-data-hub-central/ui/src/pages/Monitor.module.scss, marklogic-data-hub-central/ui/src/pages/Monitor.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.scss, marklogic-data-hub-central/ui/src/theme/HCVariables.scss
=> DHFPROD-7689: Component Replacement Layout

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/helper-impl.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/entityDrivenMatches.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/PartyDocumentXPath1.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/PartyDocumentXPath2.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/entities/Party.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/matching/matchDocumentXPathOnly.step.json
=> DHFPROD-7504: Fix exact matches using documentXPath

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
=> DHFPROD-8090: Remove pinch zoom in Graph modeling

marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
=> DHFPROD-8007: Entities merging replacement

marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/delete-modal/delete-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.tsx, marklogic-data-hub-central/ui/src/theme/HCUtils.scss
=> DHFPROD-8006: Entities matching replacement

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
- Duplicate PR for 5.6
```diff
```
=> DHFPROD-8090: Remove pinch zoom from Graph modeling

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
- Will create a duplicate PR for 5.6 after this is merged
```diff
```
=> DHFPROD-8111: Modeling graph UI fixes

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyDataInDatabases.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss, marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.module.scss, marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.test.tsx, marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.tsx
=> DHFPROD-7829: Component Replacement: Pagination

marklogic-data-hub-central/ui/src/components/column-selector/column-selector.module.scss, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.module.scss, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.module.scss, marklogic-data-hub-central/ui/src/components/steps/steps.scss, marklogic-data-hub-central/ui/src/components/steps/steps.tsx, marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.module.scss
=> DHFPROD-8093: Visual/Alignment issues from Ant Replacement

marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts
This PR contains 2 functions to avoid repeated(unnecessary) logins within tests.
```diff
```
=> DHFPROD-8165: Cypress-PreserveSessionFunctions

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs, marklogic-data-hub/src/main/resources/ml-modules/services/mlSmMerge.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMerge/post.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMerge/test-data/content/customer1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMerge/test-data/content/customer2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMerge/test-data/mergeInterceptor.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMerge/test-data/steps/merging/mergeCustomers.step.json
=> DHFPROD-8136: Passing extra interceptors to flow if needed.

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/src/api/mapping.tsx, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.module.scss, marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
=> DHFPROD-8161: Replacing Remaining Modals

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
=> DHFPROD-8123: Foreign Key Tooltip is Missing

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/column-selector/column-selector.module.scss, marklogic-data-hub-central/ui/src/components/column-selector/column-selector.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.module.scss, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-settings/entity-settings.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-settings/entity-settings.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.module.scss, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx, marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.module.scss, marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.module.scss, marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx, marklogic-data-hub-central/ui/src/components/tiles/tiles.module.scss, marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx, marklogic-data-hub-central/ui/src/pages/Overview.module.scss, marklogic-data-hub-central/ui/src/pages/Overview.tsx
=> DHFPROD-7830: popover

marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.module.scss, marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.test.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-view-explore.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.module.scss, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-7966: Create side panel for viewing record properties in graph view

examples/README.md, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/reference-entity-model/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, examples/step-interceptors/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, performance-tests/projects/commoncrawl/build.gradle
=> DHFPROD-8153: Updating the version to 5.6.1

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.module.scss, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/components/expand-collapse/expand-collapse.tsx, marklogic-data-hub-central/ui/src/components/load/switch-view.test.tsx, marklogic-data-hub-central/ui/src/components/load/switch-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.module.scss, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx, marklogic-data-hub-central/ui/src/pages/Browse.test.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/theme/HCTheme.scss, marklogic-data-hub-central/ui/src/theme/HCVariables.scss
=> DHFPROD-7825: Component Replacement: Radio (or MLRadio)

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EntitySearchController.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/CustomStepService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/FlowService.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/GraphService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/babyRegistry1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/customer1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/product50.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/product60.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/entities/BabyRegistry.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/entities/Customer.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/entities/Product.entity.json
=> DHFPROD-8059: Graph search request.

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/getDocument.sjs
=> DHFPROD-8110: getDocument test failure on 9.0-Nightly

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/merge-rule-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/merge-strategy-modal.tsx, marklogic-data-hub-central/ui/src/components/common/confirm-yes-no/confirm-yes-no.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/timeline-vis-default/timeline-vis-default.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/timeline-vis/timeline-vis.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-8160: Discard change modal not work consistently in Merging Tile

marklogic-data-hub-central/ui/src/components/common/hc-sider/hc-sider.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/theme/HCTheme.scss
=> DHFPROD-7833: Component Replacement: Switch or MLSwitch

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java
=> DHFPROD-8177: BE - Modify Graph Settings

marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/column-selector/column-selector.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.module.scss, marklogic-data-hub-central/ui/src/components/load/load-card.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx, marklogic-data-hub-central/ui/src/components/monitor-selected-facets/monitor-selected-facets.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx, marklogic-data-hub-central/ui/src/components/zero-state-explorer/zero-state-explorer.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.module.scss, marklogic-data-hub-central/ui/src/pages/Modeling.tsx
=> DHFPROD-7803: Component Replacement: Tooltip - other places

marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/merge-rule-modal.tsx, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.module.scss, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx, marklogic-data-hub-central/ui/src/theme/HCTheme.scss
=> DHFPROD-7741: Component Replacement: Treeselect

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
=> DHFPROD-8166: Export Graph To PNG in Modeling

marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.test.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx
=> DHFPROD-7761: Query-export-modal

marklogic-data-hub-central/ui/e2e/cypress/support/components/common/multi-slider.tsx
=> DHFPROD-8220: Delete Match Ruleset Intermittent e2e Failure

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
=> DHFPROD-7751: Matching/matching-step-detail

marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/create-edit-step-dialog.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/create-edit-mapping-dialog.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.test.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.test.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx, marklogic-data-hub-central/ui/src/theme/HCTheme.scss, marklogic-data-hub-central/ui/src/theme/HCVariables.scss
=> DHFPROD-7772: Autocomplete

marklogic-data-hub-central/ui/src/api/queries.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.test.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx, marklogic-data-hub-central/ui/src/config/graph-vis.config.ts, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/types/common-types.ts, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs
Some of the e2e test cases will be added separately, as part of DHFPROD-8208.
This involves changes for the ticket DHFPROD-7875 as well.
```diff
```
=> DHFPROD-7874: Display records related via foreign key in graph view

marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.scss, marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
=> DHFPROD-7749: Matching/compare-values-modal

CODEOWNERS
=> DHFPROD-8232: Updating CODEOWNERS file

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/JobControllerTest.java
=> DHFPROD-8221: Core failures on 10.0-Nightly for 5.6 and develop

marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
=> DHFPROD-8222: writerScenarioGraph e2e Failure

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addCustomStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/helper.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
=> DHFPROD-8163: Cypress-redundantWaitUntils

marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx, marklogic-data-hub-central/ui/src/util/user-context.tsx
=> DHFPROD-7672: Avoid repeating search calls on errors

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/util.xqy
=> DHFPROD-7512: 5.5 Matching - Bad error when Cant match JSON when namespace defined in model

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/customer1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/office1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/entities/Office.entity.json
=> DHFPROD-8190: BE: Add a leaf node indicator in the graph search response

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, marklogic-data-hub-central/ui/src/theme/HCTheme.scss, marklogic-data-hub-central/ui/src/theme/HCVariables.scss
=> DHFPROD-7691: Cascader

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/expandable-table-view/expandable-table-view.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/config/mapping.config.js
=> DHFPROD-7748: mapping-step-detail

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx
Fix Cascader Edit Related Entity
```diff
```
=> DHFPROD-8256: CascaderFixEditRelatedEntity

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EntitySearchController.java, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/GraphService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/nodeExpand.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/nodeExpand.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/nodeExpand.sjs
=> DHFPROD-8120: Expand node endpoint logic.

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/components/column-selector/column-selector.tsx, marklogic-data-hub-central/ui/src/theme/HCTheme.scss, marklogic-data-hub-central/ui/src/theme/HCVariables.scss
=> DHFPROD-7835: Component Replacement: Tree

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/util.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/helper-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/notification-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/options-impl.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher.xqy, marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java
=> DHFPROD-8164: Better handle massive match events

marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.scss, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx, marklogic-data-hub-central/ui/src/pages/Monitor.module.scss
DHFPROD-7756: Job-results-table
```diff
```
=> DHFPROD-7756: Job-results-table-view

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
=> DHFPROD-8240: Allow queries to be searched on via Graph Search

marklogic-data-hub-central/ui/e2e/cypress/support/components/query/manage-queries-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.module.scss, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx
=> DHFPROD-7760: ManageQuery

marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity2/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-matching/structured-property/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/lib/masteringTestLib.sjs
=> DHFPROD-8258: Ensure indexes are ready for match tests

marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.scss, marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.module.scss, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/table-view/table-view.tsx
=> DHFPROD-8226: Results-tabular-view - Expandable

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss, marklogic-data-hub-central/ui/src/components/expandable-table-view/expandable-table-view.tsx
=> DHFPROD-7755: Expandable table view

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx
changes to explore with xml
waitUntils
changes to explore with xml
deleting unuseful logs
```diff
```
=> DHFPROD-8218: CypressRefactor

marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-matching/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-matching/structured-property/suite-setup.xqy
=> DHFPROD-8258: Add more test indexing waits

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
=> DHFPROD-7747: entity-map-table

examples/step-interceptors/data/10248.json, examples/step-interceptors/entities/Order.entity.json, examples/step-interceptors/src/main/ml-modules/root/custom-modules/step-interceptors/breakoutProducts.sjs, examples/step-interceptors/steps/mapping/map-orders.step.json
=> DHFPROD-8272: Provide new step interceptor example to add content

marklogic-data-hub-central/ui/e2e/cypress/support/components/common/multi-slider.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-multiple-modal.tsx, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx
=> DHFPROD-7752: Matching/ruleset-multiple-modal

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx
=> DHFPROD-8271:Reader Graph Intermittent e2e Failure

marklogic-data-hub-central/ui/src/components/header/header.tsx, marklogic-data-hub-central/ui/src/config/overview.config.ts, marklogic-data-hub-central/ui/src/pages/Overview.test.tsx, marklogic-data-hub-central/ui/src/pages/Overview.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx, marklogic-data-hub-central/ui/src/util/environment.tsx
- Duplicate PR for 5.6
```diff
```
=> DHFPROD-8228: Make Hub Central Documentation Links Dynamic

marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub-central/ui/src/util/priority-order-conversion.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/standard.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/entityDrivenMatches.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/entityDrivenMerges.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/CustMatchMerge3.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/NsCustMatchMerge3.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/customerMatchSummary.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/namespacedCustomerMatchSummary.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/merging/mergeCustomers.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/merging/mergeNamespacedCustomers.step.json
=> DHFPROD-8189: Allow timestamp weight to be adjusted

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/relationship-modal.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.test.tsx, marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-settings/entity-settings.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx
=> DHFPROD-8209: Select components - TABLES dependencies

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/reorderSteps.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
=> DHFPROD-7762: Results-tabular-view - Main

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.tsx
=> DHFPROD-7776: Component Replacement: Remove ConfigProvider

marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorColumnSelector.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.test.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx
=> DHFPROD-8266: Fix for column selector on Monitor tile

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx
=> DHFPROD-8288: Mapping Intermittent e2e Failure

marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.module.scss, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/pages/Browse.module.scss
=> DHFPROD-8261: Sub-column nesting on explorer main table

marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.tsx
=> DHFPROD-8268: Fix for pagination on explorer tile

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/util.xqy, marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.xqy
=> DHFPROD-8258: Reduce index sleep escalation and look for SVC-EXTIME

installer-for-dhs/build.gradle
=> DEVO-350: Publish DependsOn ShadowJar

marklogic-data-hub-central/ui/e2e/cypress/support/pages/detail-nonEntity.tsx, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.module.scss, marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.tsx
=> DHFPROD-8306: Replace table: detail page non entity

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
- Fixed the following visual/UX issues in the mapping tables:
-
1) Related entity map tables need to have rounded out upper edges 
2) URI and Context Rows in entity map tables need to have different background styling
3) Overflow text in Name column should have ellipses
4) Nested rows in source and entity tables should not indent the other columns as well.
5) Source table value column is off-center towards the right.
```diff
```
=> DHFPROD-8265: Mapping UX Improvements

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
Bug: TABLE-Structured property should expand when property is added and delete
```diff
```
=> DHFPROD-8193: TABLE-Structured property should expand

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeWarnings.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/advanced-settings.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-target-collections.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.test.tsx
Replaces Advanced Settings table in merging flow steps.
```diff
```
=> DHFPROD-8305: Replace table: advanced target collection

marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-8308: All Data Toggle does bring the user to card view

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSidePanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/graphExplore.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/types/explore-graph-nodes.ts, marklogic-data-hub-central/ui/src/api/record.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.module.scss, marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.test.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-view-explore.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx, marklogic-data-hub-central/ui/src/components/table-view/table-view.module.scss, marklogic-data-hub-central/ui/src/components/table-view/table-view.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
=> DHFPROD-7961: View Instance tab in graph view

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
=> DHFPROD-8290: Reset query intermittent failure

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
=> DHFPROD-8145: Update mapping namespaces on save

.github/PULL_REQUEST_TEMPLATE.md
=> DHFPROD-8317: Added release notes

.github/PULL_REQUEST_TEMPLATE.md, NOTICE.txt
Updating notice.txt
```diff
```
=> DHFPROD-8317: Added release notes and updating notices

marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/src/App.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.module.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/common/hc-input/hc-input.tsx, marklogic-data-hub-central/ui/src/components/common/hc-tooltip/hc-tooltip.tsx, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.module.scss, marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub-central/ui/src/types/curation-types.ts, marklogic-data-hub-central/ui/src/util/curation-context.tsx
Note: Testing strategy will be included in separate ticket.
```diff
```
=> DHFPROD-5653: Help icons on forms aren't accessible using keyboard

examples/README.md, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/reference-entity-model/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, examples/step-interceptors/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, performance-tests/projects/commoncrawl/build.gradle
=> DHFPROD-8355: Updating the version to 5.6.2

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/types/base-entity-types.tsx, marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/entity-icons-sidebar/entity-icons-sidebar.module.scss, marklogic-data-hub-central/ui/src/components/entity-icons-sidebar/entity-icons-sidebar.tsx, marklogic-data-hub-central/ui/src/components/entity-specific-sidebar/entity-specific-sidebar.module.scss, marklogic-data-hub-central/ui/src/components/entity-specific-sidebar/entity-specific-sidebar.test.tsx, marklogic-data-hub-central/ui/src/components/entity-specific-sidebar/entity-specific-sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.test.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
UX checked the implementation and some updated where done.
Found an issue with the DateRangePicker component, as it's displaying at the bottom of  the facets it's not been fully displayed and I cannot scroll more to the bottom.
```diff
```
=> DHFPROD-7871: Populate entity-specific side panel

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EntitySearchController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/models/DocSearchQueryInfo.java, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/ingestionForAllFiletypes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/reorderSteps.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/validationsForNonHCSavedQueryUser.spec.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/GraphService.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/nodeExpand.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/nodeExpand.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.api, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchFacets.sjs
=> DHFPROD-8230: BE: Handle faceting for multiple entities

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
=> DHFPROD-8270: writerScenarioGraph Intermittent e2e Failure

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSidePanel.spec.tsx
=> DHFPROD-8367: Test '/Explore' graph right panel Failure on Develop

marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.test.tsx
=> DHFPROD-8336: Sidebar Changes in Card View

marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
=> DHFPROD-8303: Graph Stretches/Shrinks When Changing Width

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/compare-values-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/index.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.scss, marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.scss, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
Fixes unwanted table heading for test URIs.
```diff
```
=> DHFPROD-8322: Test URIs lists have unwanted heading

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.module.scss, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
DHFPROD-8284: Graph context menu functionality
```diff
```
=> DHFPROD-8284: Graph context menu functionality

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/checkVisibilityOfDropdownWithSearch.spec.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
=> DHFPROD-8350: Table Dropdowns are hidden

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss
=> DHFPROD-8365: [Mapping] Browsing through documents is tricky due to button having a narrow click area

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/structured-type-modal.tsx, marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts, marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling.js, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.module.scss, marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/types/modeling-types.ts
=> DHFPROD-7258: Set namespaces for structured properties

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/types/explore-graph-nodes.ts, marklogic-data-hub-central/ui/src/components/common/hc-input/hc-input.tsx, marklogic-data-hub-central/ui/src/components/entity-icons-sidebar/entity-icons-sidebar.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/components/sidebar-footer/sidebar-footer.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
Screencast: https://drive.google.com/file/d/1Ze5dIxV0mRm5LB9XiWzIHzFmjoCUXn_J/view?usp=sharing.
```diff
```
=> DHFPROD-7949: Search box in the sidebar

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreViewSelector.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-8381: Card View not toggling from Graph View

marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx, marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx, marklogic-data-hub-central/ui/src/config/explore.config.tsx, marklogic-data-hub-central/ui/src/config/exploreSidebar.tsx, marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js, marklogic-data-hub-central/ui/src/pages/Browse.tsx
Just the UI changes for group nodes display. Nothing happens when you click on a group node yet. That portion, along with the test cases, will be handled in a separate PR for 8235 and 8236.
```diff
```
=> DHFPROD-7920: Introduce group nodes

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/controlPermissionsIngestionByUser.spec.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.tsx
=> DHFPROD-8356: tooltip flapping

marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
**It also includes  the fix for [DHFPROD-8340](https://project.marklogic.com/jira/browse/DHFPROD-8340)**
```diff
```
=> DHFPROD-8321: Indent properties table under an entity type

marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.module.scss, marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.tsx
=> DHFPROD-8151: The function menu on the Map screen is tiny, values are cut off

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/graphExplore.tsx, marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx, marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.test.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
- Base Entities selections in the main panel now filter the graph, works on top of search text query as well
- UX reviewed by Jamie
```diff
```
=> DHFPROD-7969: Apply Main Panel Facets

marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
=> DHFPROD-7953: Error handling with empty Custom datepicker is broken

marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.module.scss, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx
Tooltip Background and Popovers
```diff
```
=> DHFPROD-8348: Change tooltips with links to white background to make the links readable

marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx
=> DHFPROD-8271: Reader Graph Intermittent e2e Failure

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/theme/HCTheme.scss, marklogic-data-hub-central/ui/src/theme/HCVariables.scss
Radio Group Hover Interaction
```diff
```
=> DHFPROD-8338: RadioGroupHoverInteraction

marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.module.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/expandable-table-view/expandable-table-view.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
=> DHFPROD-8300: TABLE - Expanded / nested levels indentation and width issues

marklogic-data-hub-central/ui/e2e/cypress.json, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyDataInDatabases.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx, marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.test.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.test.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js, marklogic-data-hub-central/ui/src/pages/Browse.test.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx
=> DHFPROD-7872: Display results in table view

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java, marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesTest.java
=> DHFPROD-8238: Prevent error deploying granular privileges

marklogic-data-hub-central/ui/src/api/queries.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-view-explore.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.module.scss, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/nodeExpand.sjs
Involves changes for DHFPROD-8236 as well.
Test cases will be added as part of a separate ticket.
```diff
```
=> DHFPROD-8235: Expand / collapse group nodes

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
=> DHFPROD-8452: Limit graph search result using pageLimit parameter

marklogic-data-hub-central/ui/e2e/cypress.json, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx
=> DHFPROD-8454: Reset to All Entities Hotfix

marklogic-data-hub-central/ui/src/components/explore/entity-specific-sidebar/entity-specific-sidebar.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-8331: Update existing tooltips in Graph Instance UI

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSidePanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/graphExplore.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.module.scss, marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.module.scss, marklogic-data-hub-central/ui/src/components/record-view/record-view.test.tsx, marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx
=> DHFPROD-8425: Replace Icons for Navigating to Details View in Explore

marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-8017: Update Provenance Granularity tooltip text - Mapping step

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.module.scss, marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-8384: Modeling Visual Issues and Tooltips

build.gradle, examples/SLED/build.gradle
=> DHFPROD-8460: Update SLED Project to 5.7

examples/README.md, examples/SLED/build.gradle, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/reference-entity-model/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, examples/step-interceptors/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, performance-tests/projects/commoncrawl/build.gradle
=> DEVO-450: Updating version to 5.7.0-rc1

marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/pages/Browse.module.scss, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/util/entities-sorting.tsx
=> DHFPROD-8396: Base Entities not in Alphabetical order

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/controlPermissionsIngestionByUser.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx
=> DHFPROD-8458: controlPermissionsIngestionByUser e2e failure

examples/SLED/build.gradle, examples/dhf4/DHS-e2e/DHS/build.gradle, examples/dhf4/disconnected-project/build.gradle, examples/dhf4/performance-sample/build.gradle, examples/dhf4/spring-batch/build.gradle, examples/reference-entity-model/build.gradle, examples/smart-mastering-complete/build.gradle, installer-for-dhs/build.gradle, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub-client-jar/build.gradle, marklogic-data-hub-junit5/build.gradle, marklogic-data-hub-spark-connector/build.gradle, marklogic-data-hub/build.gradle, performance-tests/build.gradle, performance-tests/projects/commoncrawl/build.gradle
=> DHFPROD-8201: Upgrade shadow jar library to 7.1.1

marklogic-data-hub-central/src/main/resources/explore-data/ui-config/config.json, marklogic-data-hub-central/ui-custom/src/views/Detail.tsx
Need this fix for the initial release. Docs reference it.
=> DHFPROD-8470: Refactor Personal Data so contents are more configurable

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx, marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.test.tsx, marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-8330: Tooltip for Entity property facets

marklogic-data-hub-central/ui/src/components/tiles/tiles.module.scss, marklogic-data-hub-central/ui/src/components/tiles/tiles.test.tsx, marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-8219: Update Explore tile lightbulb text

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
Entity types description issue in graph view
```diff
```
=> DHFPROD-8368: EntityTypeDescriptionIssue

CODEOWNERS
=> DHFPROD-8479: Update CODEOWNERS file

marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
=> DHFPROD-8472: e2eMasteringflow Intermittent e2e Failure

.github/PULL_REQUEST_TEMPLATE.md
=> DHFPROD-8466: Update Release Checkbox in PR

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/reorderSteps.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx, marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/sidebar-footer/sidebar-footer.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.test.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/services/user-preferences.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-8397: Refactor to clean up properties use.

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelTest.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/PublishModelsTest.java, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioModeling.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/types/modeling-types.ts, marklogic-data-hub-central/ui/src/api/modeling.ts, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.module.scss, marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.module.scss, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/types/common-types.ts
=> DHFPROD-8431: Discard All Changes in Draft

marklogic-data-hub-central/ui/src/components/common/hc-select/hc-select.tsx, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss, marklogic-data-hub-central/ui/src/components/common/index.ts, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.module.scss, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx
Matching Table Issues
```diff
```
=> DHFPROD-8281: Matching Table Issues

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
=> DHFPROD-8400: mappingWithInterceptorsAndCustomHook

marklogic-data-hub-central/ui/src/theme/HCTheme.scss
Typeahead Keyboard Issue
```diff
```
=> DHFPROD-8339: TypeaheadKeyboardIssue

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
=> DHFPROD-8424: Update XPath tooltip

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphExportPNG.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/graphExplore.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-view-explore.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
=> DHFPROD-8183: Export graph results as PNG - Explore tile

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/entities/Person-Dash.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/test-data/mappings/PersonMapping/PersonDashMapping.mapping.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/builtins/steps/mapping/entity-services/validateAndRunMapping.sjs
=> DHFPROD-8417: Mapping validation fails for entity properties with dashes

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchFacets.sjs
=> DHFPROD-8291: Core Unit Failures on Nightly

marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
This also involves changes for the ticket DHFPROD-7919. The e2e tests cases will be handled separately as part of the ticket DHFPROD-8208.
```diff
```
- [N/A] Added Tests  
=> DHFPROD-8142: View, expand and collapse leaf nodes in graph view

marklogic-data-hub-central/ui/e2e/cypress.json, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx
=> DHFPROD-8398: IntermitentE2eFix

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
Error Message Curate
```diff
```
=> DHFPROD-8412: ErrorMessageCurate

marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
=> DHFPROD-8476: Explore in graph view issue

marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.test.tsx, marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-8462: Issues with saved queries

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EntitySearchController.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/Constants.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/impl/RawStructuredQueryDefinitionHandler.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/models/DocSearchQueryInfo.java, marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.module.scss, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/constraint/relatedTo.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy
=> DHFPROD-8236: Table View for Expand right-click menu option for group nodes

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx, marklogic-data-hub-central/ui/src/components/common/hc-datetime-picker/hc-datetime-picker.tsx, marklogic-data-hub-central/ui/src/components/monitor-sidebar/monitor-sidebar.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
```diff
```
- [n/a] Added Tests  
=> DHFPROD-8374: Custom Date picker selection should be fixed

examples/README.md, examples/SLED/build.gradle, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/reference-entity-model/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, examples/step-interceptors/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, performance-tests/projects/commoncrawl/build.gradle
=> DHFPROD-8517: Updating the version to 5.7.0-rc2

marklogic-data-hub-central/ui/e2e/cypress.json, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/validationsForNonHCSavedQueryUser.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyDataInDatabases.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
- There are just 2 specs left regarding queries that need to be touched up once the bug https://project.marklogic.com/jira/browse/DHFPROD-8462 is completed in the near future.
```diff
```
=> DHFPROD-8455: Faceting in Explore e2e Overhaul

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EnvironmentController.java, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/system/getVersions.sjs
=> DHFPROD-7676: Manage steps in HC while using overridden database names

marklogic-data-hub-central/ui/src/components/date-facet/date-facet.module.scss, marklogic-data-hub-central/ui/src/components/date-facet/date-facet.tsx, marklogic-data-hub-central/ui/src/components/date-time-facet/date-time-facet.module.scss, marklogic-data-hub-central/ui/src/components/date-time-facet/date-time-facet.tsx, marklogic-data-hub-central/ui/src/components/explore/entity-specific-sidebar/entity-specific-sidebar.module.scss
=> DHFPROD-8498: Date Picker can't be selected at bottom

marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
Side Panel´s Styles
```diff
```
=> DHFPROD-8345: SidePanelStyles

marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/merge-rule-modal.tsx, marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/Person.entity.json, marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.module.scss, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.test.tsx, marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx
```diff
```
Added to https://wiki.marklogic.com/display/ENGINEERING/Data+Hub+5.7.0
=> DHFPROD-7656: Allow selecting top-level property for merge rule

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreGraphFacetConsistentNavigation.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/graph-explore-side-panel.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx
=> DHFPROD-8508: View Full Details from graph view

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
```diff
```
- n/a Added Tests  
=> DHFPROD-8468: Total result is not correct in graphSearch endpoint

marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx
White Page Deleting Entity Sidebar
```diff
```
=> DHFPROD-8503: WhitePageDeletingEntitySidebar

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx, marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.tsx, marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.module.scss, marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.test.tsx, marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
- UX reviewed by @jbelonoj 
- https://watch.screencastify.com/v/H7zpDOehdVJcX0o8Ab95
```diff
```
=> DHFPROD-8405: Remove Double Entities From Sidebar

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
```diff
```
- [N/A Code passes ESLint tests
=> DHFPROD-8529: graphSearch Failure on Nightly

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/util.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/utils/suite-setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/utils/test-data/entities/TestTitle.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/utils/titleExtractionTest.sjs
=> DHFPROD-8495: Don't extract entity info as part of match/merge

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
=> DHFPROD-8423: firefoxIntermitentE2E

marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling-context-mock.ts, marklogic-data-hub-central/ui/src/components/column-selector/column-selector.module.scss, marklogic-data-hub-central/ui/src/components/common/switch-view/view-switch.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-view-explore.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx, marklogic-data-hub-central/ui/src/components/query-export/query-export.module.scss, marklogic-data-hub-central/ui/src/config/modeling.config.ts, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/types/modeling-types.ts, marklogic-data-hub-central/ui/src/util/modeling-context.tsx
=> DHFPROD-8514: Buttons are not consistent in Model/Explore Graph and Table Views

marklogic-data-hub-central/build.gradle, marklogic-data-hub-central/ui/package-lock.json, marklogic-data-hub-central/ui/package.json
```diff
```
- [N/A] Added Tests  
=> DHFPROD-8015: Palamida High Critical Vulnerabilities

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FixCreatedByStepTest.java
```diff
```
- [n/a] Code passes ESLint tests
=> DHFPROD-8437: FixCreatedByStepTest Core Failure

marklogic-data-hub-central/ui/src/App.scss
```diff
```
- [n/a] Added Tests  
=> DHFPROD-8342: Radio and Checkboxes don't have hover state

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/preview-matching-activity-lib.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/test-data/content/CustMatchMergeExcludedByFilter.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/test-data/steps/matching/matchCustomers.step.json
=> DHFPROD-8497: Incorporate filterQuery in match preview

marklogic-data-hub-central/ui/src/components/queries/queries.tsx
```diff
```
- [N/A] Added Tests  
=> DHFPROD-8555: Flicker on save query icon in explore main side panel

marklogic-data-hub-central/ui/src/api/queries.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/explore/entity-search.js, marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.test.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx, marklogic-data-hub-central/ui/src/components/explore/table-view-group-nodes/table-view-group-nodes.module.scss, marklogic-data-hub-central/ui/src/components/explore/table-view-group-nodes/table-view-group-nodes.test.tsx, marklogic-data-hub-central/ui/src/components/explore/table-view-group-nodes/table-view-group-nodes.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/config/explore.config.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/types/query-types.ts, marklogic-data-hub-central/ui/src/util/search-context.tsx
RTL tests added. e2e will be added as part of DHFPROD-8556, on top of @csilva-ml 's group nodes related test cases.
```diff
```
=> DHFPROD-8530: Table view modal for group nodes

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/models/drafts/clearModelFromHubCentralConfig.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/models/drafts/setup.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/models/drafts/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/models/drafts/test-data/entities/Test.entity.json
=> DHFPROD-7956: Clear model info from HC config when deletes are published

marklogic-data-hub-central/ui/src/components/explore/graph-view-explore.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx, marklogic-data-hub-central/ui/src/pages/Browse.test.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
Also contains the fix for the bug DHFPROD-8459, 8563
```diff
```
- [N/A] Added Tests  
=> DHFPROD-8506: In explore, right side panel must be closed on changes

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreExport.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
=> DHFPROD-8545: Export icon should be hidden in table view, for All Entities

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreExport.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphExportPNG.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSidePanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyDataInDatabases.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/src/api/queries.tsx, marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/services/user-preferences.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs
- Reopening Akshay's PR after a couple conflict resolution and test fixes.
```diff
```
=> DHFPROD-7876: Default views for first-time user experience

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphExportPNG.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/tiles.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-8191: e2e failures on Windows nightly

marklogic-data-hub-central/ui/src/config/formats.config.js
Update XML and JSON file type colors
```diff
```
=> DHFPROD-5998: UpdateXMLJSONFileTypeColors

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json, marklogic-data-hub-central/ui-custom/src/components/Membership/Membership.scss, marklogic-data-hub-central/ui-custom/src/components/Membership/Membership.test.tsx, marklogic-data-hub-central/ui-custom/src/components/Membership/Membership.tsx, marklogic-data-hub-central/ui-custom/src/views/Detail.tsx
=> DHFPROD-8504: Widget— Membership

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mappingWithRelationships/setup.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mappingWithRelationships/test-data/entities/Cat.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mappingWithRelationships/test-data/entities/Dog.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mappingWithRelationships/test-data/steps/mapping/MapCat.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mappingWithRelationships/test-data/steps/mapping/MapDog.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/mappingWithRelationships/test.sjs
=> DHFPROD-8379: Fix mapping related entities with same property name

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json, marklogic-data-hub-central/ui-custom/src/components/ImageGallery/ImageGallery.scss, marklogic-data-hub-central/ui-custom/src/components/ImageGallery/ImageGallery.tsx, marklogic-data-hub-central/ui-custom/src/components/Membership/Membership.tsx, marklogic-data-hub-central/ui-custom/src/views/Detail.tsx
=> DHFPROD-8502: Image Gallery 

examples/README.md, examples/SLED/build.gradle, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/reference-entity-model/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, examples/step-interceptors/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, performance-tests/projects/commoncrawl/build.gradle
=> DHFPROD-8577: Updating the version to 5.7.0

examples/README.md, examples/SLED/build.gradle, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/reference-entity-model/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, examples/step-interceptors/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, performance-tests/projects/commoncrawl/build.gradle
=> DHFPROD-8581:Updating the version to 5.8-snapshot

Jenkinsfile
=> DHFPROD-8581: Setting up automatic merge for 5.7-develop

marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-8593: Pagination not working in Table and Snippet views in explore

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/theme/HCVariables.scss
Re Add Run Flows From Run Tile
```diff
```
=> DHFPROD-8521: Re Add Run Flows From Run Tile

marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-8593: Pagination not working in table and snippet view in explore

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/entityMappingMoreLessFunctionality.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSidePanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/validationsForNonHCSavedQueryUser.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyDataInDatabases.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/tiles.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
=> DHFPROD-8191: e2e Failures on Windows nightly pt. 2

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/validationsForNonHCSavedQueryUser.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/explore/entity-type-display-settings-modal/entity-type-display-settings-modal.module.scss, marklogic-data-hub-central/ui/src/components/explore/entity-type-display-settings-modal/entity-type-display-settings-modal.test.tsx, marklogic-data-hub-central/ui/src/components/explore/entity-type-display-settings-modal/entity-type-display-settings-modal.tsx, marklogic-data-hub-central/ui/src/components/tiles/tiles.module.scss, marklogic-data-hub-central/ui/src/components/tiles/tiles.test.tsx, marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx, marklogic-data-hub-central/ui/src/config/explore.config.tsx, marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js, marklogic-data-hub-central/ui/src/config/themes.config.js
=> DHFPROD-7934: Navigate to Graph Settings

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EnvironmentController.java, marklogic-data-hub-central/ui/src/api/queries.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.module.scss, marklogic-data-hub-central/ui/src/components/header/system-info.test.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.tsx, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java, marklogic-data-hub/src/test/java/com/marklogic/hub/impl/ClearUserDataTest.java
=> DHFPROD-7560: Add options to clear user data

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphFocusDefocusCluster.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/graphExplore.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/types/explore-graph-nodes.ts, marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
=> DHFPROD-7960: Focus defocus clusters in explore graph view

examples/entity-viewer-v2/entity-viewer-client/input/10001.xml, examples/entity-viewer-v2/entity-viewer-client/input/10003.xml, examples/entity-viewer-v2/entity-viewer-client/input/10028.xml, examples/entity-viewer-v2/entity-viewer-client/input/10069.xml, examples/entity-viewer-v2/entity-viewer-client/input/10098.xml, examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json, marklogic-data-hub-central/ui-custom/src/components/SocialMedia/SocialMedia.scss, marklogic-data-hub-central/ui-custom/src/components/SocialMedia/SocialMedia.test.tsx, marklogic-data-hub-central/ui-custom/src/components/SocialMedia/SocialMedia.tsx, marklogic-data-hub-central/ui-custom/src/util/util.tsx
=> DHFPROD-8580: SocialMedia update: display handle

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphGroupNodes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui/e2e/cypress/support/components/common/tables.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/graphExplore.tsx
=> DHFPROD-8556: GraphE2E-ExpandRecordsOnTable

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/suite-setup.xqy
=> DHFPROD-8644: Wait for indexes before running flow tests

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/standard.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging-json/standard-merge-with-arrays.sjs
Didn't add tests as this removes a default limit, essentially removing an "undocumented feature."
```diff
```
=> DHFPROD-8599: Remove default max values/sources on merge

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addCustomStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/customIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/ingestionForAllFiletypes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorCustomDatePicker.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.module.scss, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx
=> DHFPROD-8541: Re-Add Run Flows Success and Error Messages

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs
=> DHFPROD-8588: Add Matchable class

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreViewSelector.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphGroupNodes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/validationsForNonHCSavedQueryUser.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyDataInDatabases.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
=> DHFPROD-8191: e2e Failures on Nightly pt. 3

marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx
=> DHFPROD-8595: Incorrect Active Tab in Record XML/JSON View

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/merge-rule-modal.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/merge-strategy-modal.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/curation/curation-context-mock.js, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.module.scss, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.test.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-8280: Default Strategy Tooltip

marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx, marklogic-data-hub-central/ui/src/config/explore.config.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-8596: Pagination not working as expected when changing entities in Explore

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addCustomStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/checkVisibilityOfDropdownWithSearch.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/custom.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/entityMappingMoreLessFunctionality.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matchStepAdvanceSettingsReader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matchStepAdvanceSettingsWriter.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matchWarnings.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeWarnings.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
=> DHFPROD-8535: replaceRepeatedLogins

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreColumnSelector.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/queryWithMoreThanOneEntity.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx, marklogic-data-hub-central/ui/src/components/column-selector/column-selector.tsx, marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx, marklogic-data-hub-central/ui/src/components/queries/queries.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.tsx, marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/saveSavedQuery.sjs
=> DHFPROD-8553: Save queries for multiple entities in explore

marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
=> DHFPROD-7255: Update flow status modal every few seconds

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
=> DHFPROD-8669: Crear user data is not working when used by gradle command

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs, marklogic-data-hub/src/main/resources/ml-modules/services/hubFlowRunner.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/IngestAndMapWithConnectedStepsTest.java
=> DHFPROD-8527: Parse XML options in hubFlowRunner

examples/reference-entity-model/build.gradle, examples/reference-entity-model/entities/Product.entity.json, examples/reference-entity-model/input/jsonCustomersWithRelatedEntities/customer1WithRelatedEntities.json, examples/reference-entity-model/input/productConcepts.ttl, examples/reference-entity-model/input/xmlCustomersWithRelatedEntities/customer1WithRelatedEntities.xml, examples/reference-entity-model/steps/mapping/mapCustomersWithRelatedEntitiesJSON.step.json, examples/reference-entity-model/steps/mapping/mapCustomersWithRelatedEntitiesXML.step.json, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/template-generated.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/generateTDEWithConceptType.sjs
=> DHFPROD-8645: BE - Defining related concepts in entity model

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/src/components/modal-status/modal-status.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-8565: Error upon navigation to explore from Run tile

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/verifyReaderRoleCantPublish.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioModeling.spec.tsx
=> DHFPROD-8534: ModelingReplaceRepeatedLogin

Jenkinsfile
=> DEVO-488: Temp Disable JIRA Comment

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub-central/ui/src/util/modeling-utils.tsx
=> DHFPROD-8668: Irregular vis-network stabilization in Model graph view

marklogic-data-hub-central/ui/e2e/cypress/fixtures/input/person.xml, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx
DHFPROD-7187: Change Flow Run Settings In Run Tile.
Same code of [this PR](https://github.com/marklogic/marklogic-data-hub/pull/6600) for 5.7 branch, cherry pick´s hash "1ebd436c9d480a98f5cf0ee867884db8d6a9726f".
```diff
```
=> DHFPROD-7187: Change Flow Run Settings In Run Tile

Jenkinsfile
This reverts commit 86a0015d69cbc1adb016e55907741444e3d4dd74.
```diff
```
=> DEVO-488: "Revert:Temp Disable JIRA Comment"

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/queryWithMoreThanOneEntity.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorCustomDatePicker.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
=> DHFPROD-8684: Failure on Develop PR's

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx, marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.module.scss, marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Browse.tsx
=> DHFPROD-8569: Related entity icons still visible in the new entity icons sidebar, for table/snippet view

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/Constants.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java, marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/impl/StepRangeFacetHandler.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/impl/StepRangeFacetHandlerTest.java, marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java, marklogic-data-hub/src/main/resources/hub-internal-config/database-fields/staging-database.xml, marklogic-data-hub/src/main/resources/ml-config/database-fields/final-database.xml, marklogic-data-hub/src/main/resources/ml-modules-final/options/default.xml, marklogic-data-hub/src/main/resources/ml-modules-staging/options/default.xml, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/UpdateIndexesTaskTest.groovy
=> DHFPROD-7126: Ability to navigate to the output records of a step run

marklogic-data-hub/src/main/resources/ml-modules/services/hubFlowRunner.sjs, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunCustomStepTest.java, marklogic-data-hub/src/test/resources/test-projects/simple-custom-step/flows/simpleCustomStepFlow.flow.json
=> DHFPROD-8528: Fix PROV-O code with JobID specified by hubFlowRunner XML

marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
=> DHFPROD-8622: Related Entities Panel Fix

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ExploreDataController.java, marklogic-data-hub-central/src/main/resources/explore-data/data-services/ml-exp-search/getUserMetaData.api, marklogic-data-hub-central/src/main/resources/explore-data/data-services/ml-exp-search/getUserMetaData.sjs, marklogic-data-hub-central/src/main/resources/explore-data/data-services/ml-exp-search/saveUserMetaData.api, marklogic-data-hub-central/src/main/resources/explore-data/data-services/ml-exp-search/saveUserMetaData.sjs, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ExploreDataService.java
The following Commits are in this PR;
DHFPROD-8646: Get Endpoint for search execution
DHFPROD-8513: BE endpoint to save searches
DHFPROD-8585: Get Record Endpoint
```diff
```
=> DHFPROD-8585: Get Record Endpoint

marklogic-data-hub-central/ui-custom/src/components/RecentSearches/RecentSearches.tsx
=> DHFPROD-8616: Update sharing icon for Recent Searches feature

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json, marklogic-data-hub-central/ui-custom/src/components/RecentSearches/RecentSearches.scss
=> DHFPROD-8616: Update share header label

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/monitor/monitor-sidebar.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
=> DHFPROD-8681: e2eFirefoxFailures-5.7

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelTest.java, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/api/modeling.ts, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.module.scss, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub-central/ui/src/pages/Modeling.tsx, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/createDraftModel.sjs, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateDraftModelInfo.sjs
=> DHFPROD-7564: Display and Modify Entity Version Number

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/queryWithMoreThanOneEntity.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
- Duplicate PR that already merged, but for develop this time.
```diff
```
=> DHFPROD-8684: Failures on develop

ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/ExportProjectTask.groovy, ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/ExportProjectTaskTest.groovy
=> DHFPROD-8187: Pull changes from HC when exporting project

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx, marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx, marklogic-data-hub-central/ui/src/components/steps/steps.test.tsx, marklogic-data-hub-central/ui/src/config/steps.config.ts
=> DHFPROD-8649: Default batch size for merge step 1

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/controlPermissionsIngestionByUser.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/customIngestion.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/ingestionForAllFiletypes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/reorderSteps.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
=> DHFPROD-8537: ReplaceRepeatedLogin

examples/README.md, examples/SLED/build.gradle, examples/dh-5-example/build.gradle, examples/dhf5-custom-hook/build.gradle, examples/insurance/build.gradle, examples/mapping-example/build.gradle, examples/patient-hub/build.gradle, examples/reference-entity-model/build.gradle, examples/smart-mastering-complete/build.gradle, examples/snapshot-testing/build.gradle, examples/step-interceptors/build.gradle, gradle.properties, marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json, marklogic-data-hub/src/main/resources/scaffolding/build_gradle, performance-tests/projects/commoncrawl/build.gradle
=> DHFPROD-8695: updating version to 5.7-snapshot for testing

marklogic-data-hub-central/ui-custom/e2e/cypress.json, marklogic-data-hub-central/ui-custom/e2e/cypress/integration/landingPage.spec.tsx, marklogic-data-hub-central/ui-custom/e2e/cypress/plugins/index.js, marklogic-data-hub-central/ui-custom/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui-custom/e2e/cypress/support/index.js, marklogic-data-hub-central/ui-custom/e2e/package-lock.json, marklogic-data-hub-central/ui-custom/e2e/package.json
=> DHFPROD-8631: E2E Initial setup for Twizzlers

marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.test.tsx, marklogic-data-hub-central/ui-custom/src/views/Detail.test.tsx, marklogic-data-hub-central/ui-custom/src/views/Search.tsx
=> DHFPROD-8691: Fix failing tests

examples/entity-viewer-v2/entity-viewer-client/input/10028.xml, examples/entity-viewer-v2/entity-viewer-client/input/10038.xml, examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json, marklogic-data-hub-central/ui-custom/src/App.tsx, marklogic-data-hub-central/ui-custom/src/api/api.ts, marklogic-data-hub-central/ui-custom/src/store/DetailContext.tsx, marklogic-data-hub-central/ui-custom/src/store/SearchContext.tsx, marklogic-data-hub-central/ui-custom/src/views/Detail.tsx
For example: http://localhost:3000/detail?recordId=/record/10028.xml
Update Detail endpoint to new getRecord endpoint.
Fix some sample data XML files.
```diff
```
=> DHFPROD-8584: Update Detail routing to use unencoded param in URL

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx
Flow Settings Menu Enhancements
```diff
```
=> DHFPROD-8614: FlowSettingsMenuEnhancements

marklogic-data-hub-api/build.gradle, marklogic-data-hub-central/gradle.properties, marklogic-data-hub-junit5/build.gradle, marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle
=> DHFPROD-8690: Update Spring dependencies

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java, marklogic-data-hub/src/test/java/com/marklogic/hub/flow/CancelJobsTest.java
```diff
```
- [n/a ] Added to Release Wiki
=> DHFPROD-8578: BE: Job Canceling

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/reorderSteps.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx
=> DHFPROD-8692: writerScenario2 failure

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json, marklogic-data-hub-central/ui-custom/src/components/RecentClear/RecentClear.scss, marklogic-data-hub-central/ui-custom/src/components/RecentClear/RecentClear.tsx, marklogic-data-hub-central/ui-custom/src/components/Section/Section.scss, marklogic-data-hub-central/ui-custom/src/components/Section/Section.tsx, marklogic-data-hub-central/ui-custom/src/components/confirmation-modal/confirmation-modal.scss, marklogic-data-hub-central/ui-custom/src/components/confirmation-modal/confirmation-modal.tsx, marklogic-data-hub-central/ui-custom/src/store/DetailContext.tsx, marklogic-data-hub-central/ui-custom/src/views/Dashboard.test.tsx
=> DHFPROD-8624: Widget— Recent Records, Management (Local Storage)

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/ingestionForAllFiletypes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/reorderSteps.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorCustomDatePicker.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/curation/flows.data.ts, marklogic-data-hub-central/ui/src/components/flows/flows.module.scss, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.module.scss, marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/config/tooltips.config.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/util/conversionFunctions.tsx
=> DHFPROD-7254: Flow Status Modal Enhancements

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/pagination.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
=> DHFPROD-8671: e2eFirefoxFailures

marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx, marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.module.scss, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.scss, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.test.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx, marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.test.tsx, marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.tsx, marklogic-data-hub-central/ui/src/config/tiles.config.ts
Changes Monitoring Screen: same [commit hash](https://github.com/marklogic/marklogic-data-hub/pull/6701/commits) from 5.7
```diff
```
=> DHFPROD-7723: ChangesMonitoringScreen

marklogic-data-hub-api/build.gradle, marklogic-data-hub/build.gradle, ml-data-hub-plugin/build.gradle
=> DHFPROD-8690: Bump ml-gradle/ml-app-deployer versions

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/content/docA.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/content/tripleToBlockMatch.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/matchableInterceptors.sjs
=> DHFPROD-8591: Add filterQuery to Matchable

marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx, marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.module.scss, marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx, marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx, marklogic-data-hub-central/ui/src/config/modeling.config.ts
=> DHFPROD-8619: Apply Entity Icons to Modeling Graph View

marklogic-data-hub-central/ui-custom/e2e/cypress.json, marklogic-data-hub-central/ui-custom/e2e/cypress/integration/landingPage.spec.tsx, marklogic-data-hub-central/ui-custom/e2e/cypress/support/commands.js, marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/comman.tsx, marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/landing.tsx, marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/search.tsx, marklogic-data-hub-central/ui-custom/e2e/package-lock.json, marklogic-data-hub-central/ui-custom/e2e/package.json
Command to run the test : npm run cy:run
```diff
```
=> DHFPROD-8634: E2E tests for validating landing page of Twizzlers

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/entityDrivenMerges.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/CustMatchMerge1.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/CustMatchMerge2.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/CustMatchMerge3.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/NsCustMatchMerge1.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/NsCustMatchMerge2.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/NsCustMatchMerge3.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/entities/Customer.entity.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/entities/NamespacedCustomer.entity.json
=> DHFPROD-8620: Don't drop false boolean from JSON merges

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/ingestionForAllFiletypes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/reorderSteps.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/src/assets/mock-data/curation/flows.data.ts, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.module.scss, marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-7477: Add explore data links from Run flow modal

examples/entity-viewer-v2/entity-viewer-client/input/organizations/10040.xml, examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/options/search-options.xml, marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search-impl.xqy, marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search.sjs
=> DHFPROD-8753: Support for searching multiple entities and All entities

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-config/security/roles/application-user-role.json, marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search-impl.xqy, marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search.sjs
=> DHFPROD-8753: Generate xpath dynamically for xml to json array conversion

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
=> DHFPROD-8748: e2eFixes-Chrome

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/pagination.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
=> DHFPROD-8748: e2eFixes-Pt2

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ExploreDataController.java, marklogic-data-hub-central/src/main/resources/explore-data/data-services/ml-exp-search/getEntityModels.api, marklogic-data-hub-central/src/main/resources/explore-data/data-services/ml-exp-search/getEntityModels.sjs, marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search.sjs, marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ExploreDataService.java
=> DHFPROD-8755: Support returning list of entities for application

marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.module.scss, marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.tsx
=> DHFPROD-8689: Pagination changes in search results in Explorer

marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
=> DHFPROD-8686: Set Flow Status Modal Timeout

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/options/search-options.xml, marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search.sjs
=>  DHFPROD-8729: Support for Sort facet

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx
=> DHFPROD-8756: Unit Test Failures on Develop

marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/util/search-context.tsx
=> DHFPROD-8557: Default views for first-time user experience when no data in FINAL

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/options.xqy, marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/standard.xqy, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/entityDrivenMerges.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/CustMatchMerge3.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/NsCustMatchMerge3.xml, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/customerMatchSummary.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/namespacedCustomerMatchSummary.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/merging/mergeCustomers.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/merging/mergeNamespacedCustomers.step.json, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/merging-function-arguments.xqy
=> DHFPROD-8650: Fix default merge strategy information being dropped

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs, marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchWithConfigProperties.sjs
=> DHFPROD-8663: BE: Add entity instance in graph endpoint response

marklogic-data-hub-central/ui/package.json, marklogic-data-hub-central/ui/src/assets/mock-data/curation/common.data.ts, marklogic-data-hub-central/ui/src/components/common/hc-datetime-picker/hc-datetime-picker.tsx, marklogic-data-hub-central/ui/src/components/date-facet/date-facet.tsx, marklogic-data-hub-central/ui/src/components/date-time-facet/date-time-facet.tsx, marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx, marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx, marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx, marklogic-data-hub-central/ui/src/components/explore/entity-specific-sidebar/entity-specific-sidebar.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx, marklogic-data-hub-central/ui/src/components/load/load-list.tsx, marklogic-data-hub-central/ui/src/components/monitor-sidebar/monitor-sidebar.tsx, marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx, marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx, marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx, marklogic-data-hub-central/ui/src/pages/Detail.tsx, marklogic-data-hub-central/ui/src/pages/Load.test.tsx, marklogic-data-hub-central/ui/src/util/date-conversion.tsx
This should fix the moment js related security vulnerabilities.
```diff
```
=> DHFPROD-8761: Replace moment js with dayjs in HC

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EnvironmentController.java, marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/environment/EnvironmentControllerTest.java, marklogic-data-hub-central/ui/src/components/header/system-info.module.scss, marklogic-data-hub-central/ui/src/components/header/system-info.test.tsx, marklogic-data-hub-central/ui/src/components/header/system-info.tsx, marklogic-data-hub-central/ui/src/config/messages.config.tsx, marklogic-data-hub-central/ui/src/config/steps.config.ts, marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java, marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/system/getVersions.sjs
=> DHFPROD-8576: Update message when clearing user data

marklogic-data-hub-central/ui/src/pages/Run.test.tsx
=> DHFPROD-8756: Unit Test Failures on Develop pt. 2

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/pagination.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx
=> DHFPROD-8746: e2eFixes-5.7

marklogic-data-hub-spark-connector/gradle.properties
=> DHFPROD-8723: Updating the version to 1.0.1

marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search.sjs, marklogic-data-hub-central/src/main/resources/explore-data/search-lib/configurable-search-lib.sjs
=> Include total number of searchable records in database in search results

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json, marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search.sjs, marklogic-data-hub-central/ui-custom/src/api/api.ts, marklogic-data-hub-central/ui-custom/src/store/SearchContext.tsx
=> DHFPROD-8770: Get total records from search results payload

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphCenterNode.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/graphExplore.tsx, marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
=> DHFPROD-8229: Create right-click menu for nodes on the graph

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/pagination.spec.tsx
=> DHFPROD-8762: e2eFixes

marklogic-data-hub-central/ui-custom/e2e/cypress/integration/landingPage.spec.tsx, marklogic-data-hub-central/ui-custom/e2e/cypress/integration/searchValidations.spec.tsx, marklogic-data-hub-central/ui-custom/e2e/cypress/support/index.js, marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/landing.tsx, marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/search.tsx
=> DHFPROD-8635: E2E tests to validate search in Twizzlers

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/pagination.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx
=> DHFPROD-8762: e2eFixesPt3

marklogic-data-hub-central/ui/src/components/common/hc-datetime-picker/hc-datetime-picker.tsx
=> DHFPROD-8768: Date range picker calendar breaks after clearing in explore tile

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphGroupNodes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx
=> DHFPROD-8680: e2eFix5.7

marklogic-data-hub-central/ui/src/assets/mock-data/curation/flows.data.ts, marklogic-data-hub-central/ui/src/components/flows/flows.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx, marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx, marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx, marklogic-data-hub-central/ui/src/pages/Run.test.tsx, marklogic-data-hub-central/ui/src/pages/Run.tsx, marklogic-data-hub-central/ui/src/types/run-types.ts
DHFPROD-8712: Expose All Steps in Status Modal
```diff
```
=> DHFPROD-8712: Expose All Steps in Status Modal

marklogic-data-hub-central/ui-custom/src/components/DataTableValue/DataTableValue.test.tsx, marklogic-data-hub-central/ui-custom/src/components/DataTableValue/DataTableValue.tsx, marklogic-data-hub-central/ui-custom/src/components/MetadataValue/MetadataValue.test.tsx, marklogic-data-hub-central/ui-custom/src/components/MetadataValue/MetadataValue.tsx, marklogic-data-hub-central/ui-custom/src/views/Detail.test.tsx
=> DHFPROD-8741: metadata unit tests

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphCenterNode.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSettings.spec.tsx, marklogic-data-hub-central/ui/e2e/cypress/integration/explore/pagination.spec.tsx
=> DHFPROD-8762: e2eFixesPt4
