marklogic/marklogic-data-hub

marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx

DHFPROD-8478: Fix table update for multi-match rules

---

marklogic-data-hub-central/ui/src/assets/mock-data/curation/flows.data.ts
marklogic-data-hub-central/ui/src/components/flows/flows.module.scss
marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
marklogic-data-hub-central/ui/src/pages/Run.test.tsx
marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx

DHFPROD-8708: Disable Run Settings When Flow is Empty

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/startStep.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/startStep/setup.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/startStep/verifyStepNameAndType.sjs

DHFPROD-8788: Expose Step Running Name and Type in Response

---

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx
marklogic-data-hub-central/ui/package-lock.json
marklogic-data-hub-central/ui/package.json
marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx
marklogic-data-hub-central/ui/src/components/common/hc-icon-picker/hc-icon-picker.module.scss
marklogic-data-hub-central/ui/src/components/common/hc-icon-picker/hc-icon-picker.test.tsx
marklogic-data-hub-central/ui/src/components/common/hc-icon-picker/hc-icon-picker.tsx
marklogic-data-hub-central/ui/src/components/common/index.ts
marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.tsx
marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx

DHFPROD-8694: Some icons don't show when are selected in the entity type properties

---

marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx
marklogic-data-hub-central/ui/src/components/explore/entity-specific-sidebar/entity-specific-sidebar.test.tsx
marklogic-data-hub-central/ui/src/components/explore/entity-specific-sidebar/entity-specific-sidebar.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
marklogic-data-hub-central/ui/src/util/data-conversion.tsx

DHFPROD-8554: Base Entity with Wrong Title Display but Unselectable

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx

DHFPROD-8680: e2eWinFailures-5.7

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ExploreDataController.java
marklogic-data-hub-central/src/main/resources/explore-data/data-services/ml-exp-search/getMetrics.api
marklogic-data-hub-central/src/main/resources/explore-data/data-services/ml-exp-search/getMetrics.sjs
marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search.sjs
marklogic-data-hub-central/src/main/resources/explore-data/search-lib/configurable-search-lib.sjs
marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ExploreDataService.java

DHFPROD-8630: and DHFPROD-8632: Metrics Widget Endpoint

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.tsx
marklogic-data-hub-central/ui/src/services/user-preferences.tsx

DHFPROD-8710: Save Step Settings Develop
```diff
```

DHFPROD-8710: Save Step Settings Develop

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.tsx
marklogic-data-hub-central/ui/src/services/user-preferences.tsx

Save Step Settings
```diff
```

DHFPROD-8710: Save Step Settings 5.7

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job-query-lib.sjs

DHFPROD-8799: stepResponses endpoint should return step status

---

marklogic-data-hub/src/main/resources/ml-modules/services/hubFlowRunner.sjs
marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunCustomStepTest.java

DHFPROD-8791: make value optional for hubFlowRunner

---

marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.module.scss
marklogic-data-hub-central/ui/src/components/flows/flows.scss
marklogic-data-hub-central/ui/src/components/flows/flows.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx

Step Settings Dropdown Issue 5.7
Same [hash commit Develop branch](https://github.com/marklogic/marklogic-data-hub/pull/6784/commits).
```diff
```

DHFPROD-8794: StepSettingsDropdownIssue_5.7

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java
marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts
marklogic-data-hub-central/ui/src/assets/mock-data/curation/flows.data.ts
marklogic-data-hub-central/ui/src/components/flows/flows.module.scss
marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.module.scss
marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
marklogic-data-hub-central/ui/src/pages/Run.tsx
marklogic-data-hub-central/ui/src/theme/HCVariables.scss
marklogic-data-hub-central/ui/src/util/run-utils.tsx

DHFPROD-7578: Stop a running step/flow from Hub Central
```diff
```

DHFPROD-7578: Stop a running step/flow from Hub Central

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx

DHFPROD-8680: e2eWinFailures-5.7-Pt2

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/pagination.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-8801: firefoxE2EFailures-5.7

---

marklogic-data-hub-central/ui-custom/e2e/cypress.json
marklogic-data-hub-central/ui-custom/e2e/cypress/integration/landingPage.spec.tsx
marklogic-data-hub-central/ui-custom/e2e/cypress/integration/searchValidations.spec.tsx
marklogic-data-hub-central/ui-custom/e2e/cypress/integration/widgetValidations.spec.tsx
marklogic-data-hub-central/ui-custom/e2e/cypress/plugins/index.js
marklogic-data-hub-central/ui-custom/e2e/cypress/support/commands.js
marklogic-data-hub-central/ui-custom/e2e/cypress/support/index.js
marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/landing.tsx
marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/recordDetails.tsx
marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/search.tsx
marklogic-data-hub-central/ui-custom/e2e/package-lock.json
marklogic-data-hub-central/ui-custom/e2e/package.json

DHFPROD-8636: E2E tests for validating all the widgets in Twizzlers

---

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json
marklogic-data-hub-central/ui-custom/src/App.tsx
marklogic-data-hub-central/ui-custom/src/api/api.ts
marklogic-data-hub-central/ui-custom/src/components/Metrics/Metric.tsx
marklogic-data-hub-central/ui-custom/src/components/Metrics/Metrics.test.tsx
marklogic-data-hub-central/ui-custom/src/components/Metrics/Metrics.tsx
marklogic-data-hub-central/ui-custom/src/components/WhatsNew/WhatsNew.scss
marklogic-data-hub-central/ui-custom/src/components/WhatsNew/WhatsNew.test.tsx
marklogic-data-hub-central/ui-custom/src/components/WhatsNew/WhatsNew.tsx
marklogic-data-hub-central/ui-custom/src/store/MetricsContext.tsx
marklogic-data-hub-central/ui-custom/src/views/Dashboard.tsx

Pull configurable data from metrics endpoint.
```diff
```

DHFPROD-8630: What's New and Metrics widgets integration

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/entity-type-display-settings-modal.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/graph-explore-side-panel.tsx
marklogic-data-hub-central/ui/src/components/explore/entity-type-display-settings-modal/entity-type-display-settings-modal.test.tsx
marklogic-data-hub-central/ui/src/components/explore/entity-type-display-settings-modal/entity-type-display-settings-modal.tsx
marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx
marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js

DHFPROD-7938: Modify Explore Settings to Change entity label

---

marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.module.scss
marklogic-data-hub-central/ui/src/components/flows/flows.scss
marklogic-data-hub-central/ui/src/components/flows/flows.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx

Step Settings Dropdown Issue Develop
```diff
```

DHFPROD-8794: StepSettingsDropdownIssue_Develop

---

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/startStep/verifyStepNameAndType.sjs

DHFPROD-8800: Test Failure: verifyStepNameAndType.sjs

---

marklogic-data-hub-central/ui-custom/e2e/cypress/integration/recentlyVisited.spec.tsx

DHFPROD-8638: E2E tests for validating Recently visited feature

---

marklogic-data-hub-central/ui-custom/e2e/cypress.json
marklogic-data-hub-central/ui-custom/e2e/cypress/integration/recentSearches.spec.tsx
marklogic-data-hub-central/ui-custom/e2e/cypress/integration/searchValidations.spec.tsx
marklogic-data-hub-central/ui-custom/e2e/cypress/integration/widgetValidations.spec.tsx

DHFPROD-8637: E2E tests for Recent searches feature - Twizzlers

---

marklogic-data-hub-central/ui/package-lock.json
marklogic-data-hub-central/ui/package.json

DHFPROD-8771: Fix minimist security vulnerability found on palamida scan

---

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.module.scss
marklogic-data-hub-central/ui/src/components/flows/flows.tsx
marklogic-data-hub-central/ui/src/components/header/system-info.test.tsx
marklogic-data-hub-central/ui/src/components/header/system-info.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.module.scss
marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.module.scss
marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx
marklogic-data-hub-central/ui/src/components/load/load-card.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.tsx
marklogic-data-hub-central/ui/src/config/messages.config.tsx
marklogic-data-hub-central/ui/src/config/monitoring.config.js
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
marklogic-data-hub-central/ui/src/theme/HCVariables.scss
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job-query-lib.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/testFindStepResponses.sjs

DHFPROD-8617: Update Status Icons

---

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json
marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/InstallEntityViewerModules.java
marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search-impl.xqy
marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search.sjs
marklogic-data-hub-central/src/main/resources/explore-data/third-party/fast-xml-parser/LICENSE
marklogic-data-hub-central/src/main/resources/explore-data/third-party/fast-xml-parser/json2xml.js
marklogic-data-hub-central/src/main/resources/explore-data/third-party/fast-xml-parser/nimndata.js
marklogic-data-hub-central/src/main/resources/explore-data/third-party/fast-xml-parser/node2json.js
marklogic-data-hub-central/src/main/resources/explore-data/third-party/fast-xml-parser/node2json_str.js
marklogic-data-hub-central/src/main/resources/explore-data/third-party/fast-xml-parser/parser.d.ts
marklogic-data-hub-central/src/main/resources/explore-data/third-party/fast-xml-parser/parser.js
marklogic-data-hub-central/src/main/resources/explore-data/third-party/fast-xml-parser/read.js
marklogic-data-hub-central/src/main/resources/explore-data/third-party/fast-xml-parser/util.js
marklogic-data-hub-central/src/main/resources/explore-data/third-party/fast-xml-parser/validator.js
marklogic-data-hub-central/src/main/resources/explore-data/third-party/fast-xml-parser/xmlNode.js
marklogic-data-hub-central/src/main/resources/explore-data/third-party/fast-xml-parser/xmlstr2xmlnode.js
marklogic-data-hub-central/ui-custom/src/components/Facets/Facets.tsx
marklogic-data-hub-central/ui-custom/src/store/SearchContext.tsx
marklogic-data-hub-central/ui-custom/src/views/Detail.tsx

DHFPROD-8615: Adding modules for faster xml to json parsing

---

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json
marklogic-data-hub-central/ui-custom/e2e/cypress/integration/searchValidations.spec.tsx
marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/search.tsx
marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.scss
marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.tsx

DHFPROD-8742: Widget: EntityIcon

---

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json
marklogic-data-hub-central/ui-custom/src/components/DataTableMultiValue/DataTableMultiValue.tsx
marklogic-data-hub-central/ui-custom/src/components/Membership/Membership.scss
marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.scss
marklogic-data-hub-central/ui-custom/src/views/Detail.tsx

Hide Important menu in Detail view.
Hide geo map icon in DataTableMulti.
Fix Membership style issue.
Make "All Entities" the default Searchbox menu selection.
```diff
```

DHFPROD-8742: Style fixes for entity icon, etc.

---

marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.module.scss
marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.tsx

DHFPROD-8834: Fix for the scroll within entity icon sidebar in explore

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphFocusDefocusCluster.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx

DHFPROD-8762: e2eFixes-pt2

---

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json
marklogic-data-hub-central/ui-custom/src/components/RecentRecords/RecentRecords.test.tsx
marklogic-data-hub-central/ui-custom/src/components/RecentSearches/RecentSearches.test.tsx
marklogic-data-hub-central/ui-custom/src/components/RecentSearches/RecentSearches.tsx
marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.test.tsx
marklogic-data-hub-central/ui-custom/src/components/Section/Section.scss
marklogic-data-hub-central/ui-custom/src/views/Search.test.tsx

- solved Record Info section title bug
- solved unit failing tests 
- visual improvement
```diff
```

DHFPROD-8820: Record Info section title is not displayed

---

marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx

DHFPROD-8812: Merge Details Timeline Error

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FinalDatabaseXmlFileUpgrader.java
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeFinalDatabaseXmlFileTest.java

DHFPROD-8815: ranByStep missing in FINAL DB

---

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json

DHFPROD-8821: Update page length dropdown menu

---

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx

DHFPROD-8813: Modeling Graph Entity Physics

---

marklogic-data-hub-central/ui-custom/src/store/DetailContext.tsx
marklogic-data-hub-central/ui-custom/src/store/SearchContext.tsx

Do not execute saves when features are not configured.
```diff
```

DHFPROD-8836: Fix RecentSearches and RecentRecords when not configured

---

marklogic-data-hub-central/ui-custom/src/components/DataTableValue/DataTableValue.tsx

DHFPROD-8837: Fix DataTableValue when empty value passed in

---

marklogic-data-hub-central/ui-custom/src/components/DataTableValue/DataTableValue.tsx

DHFPROD-8837: Value fix

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ExploreDataController.java
marklogic-data-hub-central/src/main/resources/explore-data/data-services/ml-exp-search/getEntityModels.api
marklogic-data-hub-central/src/main/resources/explore-data/data-services/ml-exp-search/getEntityModels.sjs
marklogic-data-hub-central/src/main/resources/explore-data/data-services/ml-exp-search/getRecords.sjs
marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search.sjs
marklogic-data-hub-central/src/main/resources/explore-data/search-lib/configurable-search-lib.sjs
marklogic-data-hub-central/ui-custom/src/api/api.ts
marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ExploreDataService.java

DHFPROD-8835: Passing userid's from HTTP layer to Dataservice endpoints

---

marklogic-data-hub-central/ui-custom/src/store/DetailContext.tsx
marklogic-data-hub-central/ui-custom/src/store/SearchContext.tsx
marklogic-data-hub-central/ui-custom/src/views/Detail.tsx

DHFPROD-8817: Fix navigation history

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/ingestionForAllFiletypes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/entity-type-display-settings-modal.tsx

DHFPROD-8841: e2eFixes

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.tsx
marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx
marklogic-data-hub-central/ui/src/components/load/load-card.tsx
marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx
marklogic-data-hub-central/ui/src/components/load/load-list.tsx

DHFPROD-8804: Run Flow After Deleting Step Develop

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.tsx
marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx
marklogic-data-hub-central/ui/src/components/load/load-card.tsx
marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx
marklogic-data-hub-central/ui/src/components/load/load-list.tsx

DHFPROD-8804: Run Flow After Deleting Step 5.7
```diff
```

DHFPROD-8804: Run Flow After Deleting Step 5.7

---

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy

DHFPROD-8856: Handle empty sequences from merge

---

examples/SLED/build.gradle
examples/SLED/lib/log4j2.properties
examples/barebones/build.gradle
examples/dh-5-example/build.gradle
examples/dhf4/DHS-e2e/DHS/build.gradle
examples/dhf4/DHS-e2e/DHS/lib/log4j.properties
examples/dhf4/DHS-e2e/DHS/lib/log4j2.properties
examples/dhf4/disconnected-project/build.gradle
examples/dhf4/performance-sample/build.gradle
examples/disconnected-project/build.gradle
examples/insurance/build.gradle
examples/mapping-example/build.gradle
examples/patient-hub/build.gradle
examples/reference-entity-model/build.gradle
examples/reference-entity-model/lib/log4j.properties
examples/reference-entity-model/lib/log4j2.properties
examples/smart-mastering-complete/build.gradle
examples/smart-mastering-complete/lib/log4j.properties
examples/smart-mastering-complete/lib/log4j2.properties
examples/step-interceptors/build.gradle
marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
marklogic-data-hub-central/ui/e2e/hc-qa-project/lib/log4j.properties
marklogic-data-hub-central/ui/e2e/hc-qa-project/lib/log4j2.properties
marklogic-data-hub/build.gradle
marklogic-data-hub/src/test/resources/log4j2.properties
performance-tests/projects/commoncrawl/build.gradle

DHFPROD-8814: Clean up reference projects

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphGroupNodes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-8680: e2eWinFailures

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx

DHFPROD-8847: e2eFirefox

---

marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx

DHFPROD-8860: Job response modal not opening on Monitor

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx

DHFPROD-8853: firefoxE2eFailure-5.7

---

marklogic-data-hub-central/ui-custom/src/components/Chiclet/Chiclet.test.tsx
marklogic-data-hub-central/ui-custom/src/components/Chiclet/Chiclet.tsx
marklogic-data-hub-central/ui-custom/src/components/ConfirmationModal/ConfirmationModal.tsx
marklogic-data-hub-central/ui-custom/src/components/ConfirmationModal/confirmationModal.test.tsx
marklogic-data-hub-central/ui-custom/src/components/DateTime/DateTime.test.tsx
marklogic-data-hub-central/ui-custom/src/components/DateTime/DateTime.tsx
marklogic-data-hub-central/ui-custom/src/components/Image/Image.test.tsx
marklogic-data-hub-central/ui-custom/src/components/Image/Image.tsx
marklogic-data-hub-central/ui-custom/src/components/Loading/Loading.test.tsx
marklogic-data-hub-central/ui-custom/src/components/Loading/Loading.tsx
marklogic-data-hub-central/ui-custom/src/components/Menus/Menus.test.tsx
marklogic-data-hub-central/ui-custom/src/components/Menus/Menus.tsx
marklogic-data-hub-central/ui-custom/src/components/RecentClear/RecentClear.test.tsx
marklogic-data-hub-central/ui-custom/src/components/RecentClear/RecentClear.tsx
marklogic-data-hub-central/ui-custom/src/components/Section/Section.tsx
marklogic-data-hub-central/ui-custom/src/components/Section/section.test.tsx
marklogic-data-hub-central/ui-custom/src/components/SelectedFacets/SelectedFacets.test.tsx
marklogic-data-hub-central/ui-custom/src/components/SummaryMeter/SummaryMeter.test.tsx
marklogic-data-hub-central/ui-custom/src/components/SummaryMeter/SummaryMeter.tsx
marklogic-data-hub-central/ui-custom/src/components/Value/Value.test.tsx
marklogic-data-hub-central/ui-custom/src/components/Value/Value.tsx
marklogic-data-hub-central/ui-custom/src/store/DetailContext.tsx
marklogic-data-hub-central/ui-custom/src/store/SearchContext.tsx
marklogic-data-hub-central/ui-custom/src/views/Detail.tsx

DHFPROD-8832: Unit tests for components

---

marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx
marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx
marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx
marklogic-data-hub-central/ui/src/types/view-types.ts

DHFPROD-8808: Retain state: Modeling Table View
```diff
```

DHFPROD-8808: Retain state: Modeling Table View

---

examples/README.md
examples/SLED/build.gradle
examples/dh-5-example/build.gradle
examples/dhf5-custom-hook/build.gradle
examples/insurance/build.gradle
examples/mapping-example/build.gradle
examples/patient-hub/build.gradle
examples/reference-entity-model/build.gradle
examples/smart-mastering-complete/build.gradle
examples/snapshot-testing/build.gradle
examples/step-interceptors/build.gradle
gradle.properties
marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java
marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json
marklogic-data-hub/src/main/resources/scaffolding/build_gradle
performance-tests/projects/commoncrawl/build.gradle

DEVO-516: Update the version to 5.7.2

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/datahub.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/core/models/entities.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/core/models/entityModel.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/content/docA.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/content/first-names.xml
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/content/nicknames.xml
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/entities/Customer.entity.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/matchableInterceptors.sjs

DHFPROD-8590: Add MatchRulesetDefinitions

---

marklogic-data-hub-central/ui-custom/src/components/ConfirmationModal/ConfirmationModal.scss
marklogic-data-hub-central/ui-custom/src/components/RecentClear/RecentClear.scss

DHFPROD-8872: Fix Clear buttons in Firefox

---

marklogic-data-hub-central/ui-custom/e2e/cypress/integration/searchPagination.spec.tsx
marklogic-data-hub-central/ui-custom/e2e/cypress/integration/widgetValidations.spec.tsx
marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/search.tsx

DHFPROD-8750: E2E tests for validating Search Page pagination

---

marklogic-data-hub-central/ui-custom/src/components/DataTableValue/DataTableValue.tsx
marklogic-data-hub-central/ui-custom/src/components/RecentRecords/RecentRecords.tsx
marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.tsx
marklogic-data-hub-central/ui-custom/src/components/Value/Value.tsx
marklogic-data-hub-central/ui-custom/src/views/Detail.tsx

DHFPROD-8848: Display a record's URI value if the title as configured is missing

---

marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/monitor/monitor-sidebar.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx
marklogic-data-hub-central/ui/src/components/monitor-selected-facets/monitor-selected-facets.tsx
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job-query-lib.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/testFindStepResponses.sjs

DHFPROD-8805: Step Status Faceting on Monitoring Table

---

marklogic-data-hub-central/ui-custom/src/components/Timeline/Timeline.scss

DHFPROD-8884: Update Timeline marker colors

---

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/detail.config.sjs
marklogic-data-hub-central/ui-custom/src/components/Relationships/Relationships.scss
marklogic-data-hub-central/ui-custom/src/components/Relationships/Relationships.tsx
marklogic-data-hub-central/ui-custom/src/components/Timeline/Timeline.scss

Make Timeline and Relationships consistent.
```diff
```

DHFPROD-8884: Update Timeline and Relationships styles

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/entity-type-display-settings-modal.tsx
marklogic-data-hub-central/ui/src/components/explore/entity-type-display-settings-modal/entity-type-display-settings-modal.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
marklogic-data-hub-central/ui/src/pages/Browse.tsx

DHFPROD-7939: Modify Explore Settings to Change hover properties

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/core/models/entityModel.sjs

DHFPROD-8881: Fix matching to be ML 9 compatible

---

marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
marklogic-data-hub-central/ui/src/types/view-types.ts

DHFPROD-5754: Retain state: Modeling Graph View
```diff
```

DHFPROD-5754: Retain state: Modeling Graph View

---

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/detail.config.sjs
marklogic-data-hub-central/ui-custom/src/components/Timeline/Timeline.test.tsx

DHFPROD-8886: Update Timeline popover content

---

marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.test.tsx
marklogic-data-hub-central/ui-custom/src/store/SearchContext.tsx
marklogic-data-hub-central/ui-custom/src/views/Detail.test.tsx

Also fix unit test issues, ResultsList and Detail
```diff
```

DHFPROD-8893: Check for empty result on search retrieval

---

examples/entity-viewer-v2/entity-viewer-client/input/persons/10006.xml
examples/entity-viewer-v2/entity-viewer-client/input/persons/10024.xml
examples/entity-viewer-v2/entity-viewer-client/input/persons/10031.xml
examples/entity-viewer-v2/entity-viewer-client/input/persons/10041.xml
examples/entity-viewer-v2/entity-viewer-client/input/persons/10053.xml
examples/entity-viewer-v2/entity-viewer-client/input/persons/10073.xml

Known issue, breaks UI. When we update sample data this needs to be done. Optimally it would be automated and done during the data generation.
```diff
```

DHFPROD-8897: Remove duplicate relationships in sample data

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs

DHFPROD-8610: Matchable implement buildActionDetails

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/nodeExpand.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/nodeExpand.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/office1.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/entities/Office.entity.json

DHFPROD-8809: BE - Expand concept node to view everything related to it

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeWarnings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/common/multi-slider.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.tsx
marklogic-data-hub-central/ui/src/pages/Curate.tsx
marklogic-data-hub-central/ui/src/types/view-types.ts

DHFPROD-8806: Retain State: Matching Step Details

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx
marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx
marklogic-data-hub-central/ui/src/types/view-types.ts

Retain State Map Match Merge In Curate View
```diff
```

DHFPROD-7180: Retain State Map Match Merge In Curate

---

marklogic-data-hub-central/ui-custom/src/components/RecentRecords/RecentRecords.tsx

DHFPROD-8880 resent record multiples entities

---

examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/detail.config.sjs
marklogic-data-hub-central/ui-custom/src/components/Timeline/Timeline.tsx

Improve Timeline usability with different options, allow options override from config object.
```diff
```

DHFPROD-8908: Improve Timeline UX with options

---

marklogic-data-hub-central/ui-custom/src/components/Facets/Facets.tsx

DHFPROD-8906: Invalid facet name is throwing a blank page

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/core/models/entityModel.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/matchableInterceptors.sjs

DHFPROD-8609: Add scoreDocument function to Matchable

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/src/components/column-selector/column-selector.module.scss
marklogic-data-hub-central/ui/src/components/column-selector/column-selector.tsx
marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx
marklogic-data-hub-central/ui/src/components/queries/queries.module.scss
marklogic-data-hub-central/ui/src/components/queries/queries.tsx
marklogic-data-hub-central/ui/src/components/query-export/query-export.module.scss
marklogic-data-hub-central/ui/src/components/query-export/query-export.tsx
marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.module.scss
marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js
marklogic-data-hub-central/ui/src/theme/HCTheme.scss

…s that cannot be used
```diff
```

DHFPROD-8519: In the Explore screen, display and disable icons/buttons that cannot be used

---

marklogic-data-hub-central/ui-custom/src/components/WhatsNew/WhatsNew.tsx

DHFPROD-8920: Catch NaN in What's New and don't show

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/monitor/monitor-sidebar.tsx

DHFPROD-8918: Intermittent graph and monitor e2e Failure

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/models/DocSearchQueryInfo.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchFacets.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/product50.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/product70.json

DHFPROD-8419: BE - Add Concepts facets

---

examples/entity-viewer-baseball/README.md
examples/entity-viewer/README.md

PLEASE TEST EXAMPLE PROJECTS PRETENDING YOU ARE A CUSTOMER. 
Start with a clean MarkLogic server and an application WAR file (build it from the branch) and work through the steps in the READMEs. Note if anything is confusing or incorrect. 
These projects may not be relevant to the Twizzlers customer but they will be important for other users/customers trying to test/evaluate the application.
```diff
```

DHFPROD-8924: Update example project README files

---

.github/PULL_REQUEST_TEMPLATE.md

DHFPROD-8928: Update the checklist

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/InstallEntityViewerModules.java
marklogic-data-hub-central/src/main/resources/explore-data/examples/ml-search-lib/search.sjs
marklogic-data-hub-central/src/main/resources/explore-data/third-party/fast-xml-parser/json2xml.js
marklogic-data-hub-central/src/main/resources/explore-data/third-party/fast-xml-parser/util.js

DHFPROD-8930: Testing changes for remote build

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/validationsForNonHCSavedQueryUser.spec.tsx
marklogic-data-hub-central/ui/src/components/queries/managing/edit-query-dialog/edit-query-dialog.tsx
marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx
marklogic-data-hub-central/ui/src/components/queries/queries.test.tsx
marklogic-data-hub-central/ui/src/components/queries/queries.tsx
marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx

DHFPROD-7910: Clear query should be visible even with no saved queries

---

Jenkinsfile

DEVO-523: Do not fail on error from JIRA

---

marklogic-data-hub-central/ui/src/pages/noMatchRedirect.module.scss
marklogic-data-hub-central/ui/src/pages/noMatchRedirect.test.tsx
marklogic-data-hub-central/ui/src/pages/noMatchRedirect.tsx

```diff
```
- [ n/a] Added to Release Wiki

DHFPROD-8901: Error handling: Redirect screen

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/entity-type-display-settings-modal.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/home.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/types/base-entity-types.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx

DHFPROD-8607: Add Entity Type Display Settings to Model screen

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/matchableInterceptors.sjs

DHFPROD-8787: Allow Custom Match Functions to Return Atomic Values

---

marklogic-data-hub-central/ui-custom/e2e/cypress/integration/recentSearches.spec.tsx
marklogic-data-hub-central/ui-custom/e2e/cypress/integration/sortingValiations.tsx
marklogic-data-hub-central/ui-custom/e2e/cypress/integration/widgetValidations.spec.tsx
marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/search.tsx

`###` Description
```diff
```
- ##### Owner:

DHFPROD-8827: E2E tests for validate Sorting in Search Page in Twizzlers

---

marklogic-data-hub-central/ui-custom/e2e/cypress/integration/recordsDetailPage.spec.tsx
marklogic-data-hub-central/ui-custom/e2e/cypress/support/pages/recordDetails.tsx

DHFPROD-8751: E2E tests for validate Record Details Page in Twizzlers

---

examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/detail.config.sjs
marklogic-data-hub-central/ui-custom/src/components/Membership/Membership.tsx
marklogic-data-hub-central/ui-custom/src/views/Detail.tsx

DHFPROD-8952: Status and timestamp values configurable

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EntitySearchController.java
marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/GraphService.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/entitiesWithConceptsTypes.api
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/entitiesWithConceptsTypes.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/getEntitiesTypesWithRelatedConceptsTypes.sjs

DHFPROD-8945: BE -Display Concepts facets in explore Side panel

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/suite-setup.xqy

DHFPROD-8935: Create Mergeable Class

---

marklogic-data-hub-central/ui/e2e/cypress.json

DHFPROD-8958: changeRetries

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/sidebarIndicators.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.module.scss
marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.test.tsx
marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx
marklogic-data-hub-central/ui/src/components/common/hc-facet-indicator/hc-facet-indicator.module.scss
marklogic-data-hub-central/ui/src/components/common/hc-facet-indicator/hc-facet-indicator.test.tsx
marklogic-data-hub-central/ui/src/components/common/hc-facet-indicator/hc-facet-indicator.tsx
marklogic-data-hub-central/ui/src/components/common/index.ts
marklogic-data-hub-central/ui/src/components/explore/entity-specific-sidebar/entity-specific-sidebar.tsx
marklogic-data-hub-central/ui/src/components/facet/facet-element.tsx
marklogic-data-hub-central/ui/src/components/facet/facet.module.scss
marklogic-data-hub-central/ui/src/components/facet/facet.tsx
marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.module.scss
marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.test.tsx
marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.test.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
marklogic-data-hub-central/ui/src/config/themes.config.js
marklogic-data-hub-central/ui/src/pages/Browse.tsx

DHFPROD-8060: Add Counts and Green bars to Facets

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
marklogic-data-hub-central/ui/src/types/view-types.ts

Retain State Mapping Step Detail Source Table
```diff
```
- ##### Owner:

DHFPROD-8810: Retain State Mapping Step Detail Source Table

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSidePanel.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/graph-view.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore.module.scss
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js
marklogic-data-hub-central/ui/src/types/explore-types.ts

Also contains changes for the ticket DHFPROD-8811 and DHFPROD-8685.
```diff
```
- ##### Owner:

DHFPROD-7959: Turn concepts on/off

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/matching.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMatchOptionsLib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matcher.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/core/models/entityModel.sjs
marklogic-data-hub/src/main/resources/scaffolding/defaultFlow.flow.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/algorithms/reduce/testReduce.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/entityDrivenMatches.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/matching/matchCustomerBillingCityState.step.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/matching/matchCustomerShippingCityState.step.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/matching/matchCustomers.step.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/matching/matchDocumentXPathOnly.step.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/matching/matchNSCustomerBillingCityState.step.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/matching/matchNSCustomerShippingCityState.step.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/matching/matchNamespacedCustomers.step.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-matching/test-data/flows/customerV1Flow.flow.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/lib/masteringTestLib.sjs
marklogic-data-hub/src/test/resources/master-test/flows/myMatchMergeFlow.flow.json
ml-data-hub-plugin/src/test/resources/master-test/myNewFlow.flow.json

DHFPROD-8954: Use Matchable for matching step

---

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractHubCentralTest.java
marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelTest.java
marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/AbstractSparkConnectorTest.java
marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/AbstractHubClientTest.java
marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java
marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java
marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractSimpleHubTest.java

DHFPROD-8962: Wait for rebalance to test cluster

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/types/explore-graph-nodes.ts
marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/Office.entity.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/office/Office1.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/mapping/mapOfficeStep.step.json
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx

DHFPROD-8077: Expand concept node to view everything related to it.

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/ClearUserDataTest.java

DHFPROD-8916: Clear user data retains /config/hubCentral.json file

---

marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.test.tsx
marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx
marklogic-data-hub-central/ui/src/pages/Detail.tsx
marklogic-data-hub-central/ui/src/theme/HCCustomFont.scss
marklogic-data-hub-central/ui/src/theme/HCTheme.scss

DHFPROD-6341: Enhance "Record" tab in Explore details to note doc type

---

marklogic-data-hub-central/ui-custom/openapi/openapi-spec.json
marklogic-data-hub-central/ui-custom/openapi/openapi-spec.yaml

DHFPROD-8824: Document the Twizzlers API in Swagger

---

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractHubCentralTest.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/EntityManagerImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/collector/impl/LegacyCollectorImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/SourceQueryCollector.java
marklogic-data-hub/src/test/java/com/marklogic/bootstrap/TestAppInstaller.java
marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java
marklogic-data-hub/src/test/java/com/marklogic/hub_integration/EndToEndFlowTests.java
marklogic-data-hub/src/test/java/com/marklogic/hub_unit_test/RunMarkLogicUnitTestsTest.java
marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractSimpleHubTest.java

```diff
```
- ##### Owner:
- [x Squashed all commits into a single commit

DHFPROD-8962: Stabilize test performance

---

marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadAllDataTypesTest.java

DHFPROD-8949: ReadAllDataTypesTest

---

examples/real-estate/CSV/uszips.csv

Dataset details:
Nested Object - Lands, Commercial Properties, Shopping Centers
Array of Numbers - Gas Stations
Array of Integers - Gyms
Array of strings - Parks and Recreation, Dog Parks, Banks
Empty & null arrays and null values are included in above
Example project is also created
```diff
```
- ##### Owner:

DHFPROD-8909: Populate Example Project with XML Data Part2

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreColumnSelector.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreExport.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreGraphFacetConsistentNavigation.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreViewSelector.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphCenterNode.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphExportPNG.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphFocusDefocusCluster.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphGroupNodes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx

DHFPROD-8538: replaceRtLogin-pt1

---

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx

DHFPROD-8980: Make mapping column options consistent

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/common.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/mergeableInterceptors.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs

DHFPROD-8938: Allow interceptors to be used with applyDocumentContext

---

marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search.sjs

DHFPROD-9043: Default search works for selected facets

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/common.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/test-data/content/CustMatchMerge1.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/test-data/content/CustMatchMerge2.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/test-data/content/CustMatchMerge3.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/test-data/content/NsCustMatchMerge1.xml
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/test-data/content/NsCustMatchMerge2.xml
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/test-data/content/NsCustMatchMerge3.xml
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/test-data/entities/Customer.entity.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/test-data/entities/NamespacedCustomer.entity.json

DHFPROD-8936: Implement MergeRuleDefintions

---

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss
marklogic-data-hub-central/ui/src/pages/TilesView.scss

- Removed unnecessary horizontal scroll in matching step details screen and possible combinations box.
- 
```diff
```
- ##### Owner:

DHFPROD-8224: Remove unnecessary horizontal scrolls

---

marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search-impl.xqy
marklogic-data-hub-central/src/main/resources/explore-data/ml-search-lib/search.sjs

DHFPROD-9045: Transform Search response match snippets

---

marklogic-data-hub/src/test/java/com/marklogic/hub/impl/ClearUserDataTest.java

DHFPROD-9028: ClearUserDataTest

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/pagination.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyDataInDatabases.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/explore.tsx

DHFPROD-8641: cypressRefactor

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ConceptController.java
marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ConceptService.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/concept/createDraftConceptModel.api
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/concept/createDraftConceptModel.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/concept/deleteDraftConceptModel.api
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/concept/deleteDraftConceptModel.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/concept/updateDraftConceptModelInfo.api
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/concept/updateDraftConceptModelInfo.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/concept-lib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs
marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/models/ConceptTest.java

```diff
```
- ##### Owner:
- [n/a ] Ran cypress tests on firefox locally

DHFPROD-8802: BE - Create/Update/Delete concept classes in HC

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSidePanel.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/queryWithMoreThanOneEntity.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/sidebarIndicators.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyDataInDatabases.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/viewNavigation.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-8539: replaceRtLogin-pt2

---

marklogic-data-hub/src/test/ml-modules/root/test/data-hub-test-helper.xqy

DHFPROD-8598: Wait for post-commit triggers as part of index wait

---

marklogic-data-hub-central/ui-custom/src/components/RecentRecords/RecentRecords.tsx
marklogic-data-hub-central/ui-custom/src/components/ResultSnippet/ResultSnippet.tsx
marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.scss
marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.tsx
marklogic-data-hub-central/ui-custom/src/views/Detail.tsx

DHFPROD-9019: Display RecordRaw widget on Detail page OOTB

---

marklogic-data-hub-central/gradle.properties
marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/Application.java
marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/SwaggerConfig.java
marklogic-data-hub-central/src/main/resources/application.properties
marklogic-data-hub/build.gradle

DHFPROD-8927: Address palamida scan spring framework vulnerabilities

---

marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx

DHFPROD-9042: Unable to create self relationships with one entity

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
marklogic-data-hub-central/ui/src/api/facets.tsx
marklogic-data-hub-central/ui/src/components/common/dynamic-icons/dynamic-icons.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore.module.scss
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore.tsx
marklogic-data-hub-central/ui/src/components/facet/facet-element.tsx
marklogic-data-hub-central/ui/src/components/facet/facet.module.scss
marklogic-data-hub-central/ui/src/components/facet/facet.tsx
marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
marklogic-data-hub-central/ui/src/config/explore.config.tsx
marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
marklogic-data-hub-central/ui/src/pages/Browse.tsx
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/entitiesWithConceptsTypes.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/getEntitiesTypesWithRelatedConceptsTypes.sjs

DHFPROD-7888: Add concept facets

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java
marklogic-data-hub/src/main/resources/ml-modules/transforms/hubEntitySearchTransform.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/exportSearchAsCSVTest.sjs

DHFPROD-9035: Export to CSV for All Entities

---

Jenkinsfile

DHFPROD-9036: Run cypress tests on win firefox against hc on linux

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
marklogic-data-hub-central/ui/src/components/queries/queries.tsx
marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx

DHFPROD-8955: Clear query should be disabled when no query is selected

---

marklogic-data-hub-central/ui/package-lock.json
marklogic-data-hub-central/ui/package.json

DHFPROD-9058: Resolve Palamida Vulnerabilities - url-parse, lodash

---

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx

DHFPROD-9067: e2eFixes

---

Jenkinsfile

DHFPROD-9037: Adding timeouts

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/queryWithMoreThanOneEntity.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
marklogic-data-hub-central/ui/src/App.scss
marklogic-data-hub-central/ui/src/App.tsx
marklogic-data-hub-central/ui/src/pages/Login.module.scss
marklogic-data-hub-central/ui/src/pages/TilesView.module.scss

- Footer used to never be visible. Now scrolling on main pages reach footer.
```diff
```
- ##### Owner:

DHFPROD-9055: Scrolling on landing page

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreColumnSelector.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonSnippetViewValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/sidebarIndicators.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyDataInDatabases.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/common/tables.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/specific-sidebar.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/explore.tsx

DHFPROD-8641: e2eRefactorPt2

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/template-generated.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/generateTDEWithRelatedEntityType.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/updateMappingTransform/mappingXmlUpdateTest.sjs

DHFPROD-9069: Allow graph links on non-identifier properties

---

marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
marklogic-data-hub-central/ui/src/config/themes.config.js

DHFPROD-9056: Hover feature for concept nodes

---

marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx

DHFPROD-8985: e2eLoadWriterPerm 

---

Jenkinsfile

DHFPROD-9036: Adding windows chrome

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx

DHFPROD-9090: Fix intermittent E2E failures on develop branch

---

Jenkinsfile

DHFPROD-9036:fixing cast exception

---

marklogic-data-hub-central/build.gradle
marklogic-data-hub-central/gradle.properties
marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/HubCentral.java
marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/HubCentralTest.java
marklogic-data-hub-central/src/test/resources/custom-config/datahubConfig.json
marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/SystemService.java
marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/FinishHubDeploymentCommand.java
marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.hub/config.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/system/getDataHubConfig.api
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/system/getDataHubConfig.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/system/system-lib.sjs
marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/FinishHubDeploymentCommandTest.java
marklogic-data-hub/src/test/java/com/marklogic/hub/entity/EntityServicesAlignmentTest.java

DHFPROD-8842: Hubcentral on custom databases and ports

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/content/nicknames.xml

DHFPROD-8983: Convert Synonym function to JavaScript

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/concept/deleteDraftConceptModel.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/getPrimaryEntityTypes.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/publishDraftModels.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/concept-lib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs
marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/models/ConceptTest.java

DHFPROD-9065: BE: Publish concept classes

---

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx

- Example demo: https://watch.screencastify.com/v/aAQzLvm20sIpoCk5LyUW
```diff
```
- ##### Owner:

DHFPROD-8287: Invalid URI Messaging in Mapper GUI

---

marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx

Changes the Iincomplete sentence and deleted the sentence which is under 'Show Preview'
```diff
```
- ##### Owner:

DHFPROD-9063 Table View Export Warning has Incomplete Sentence

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorPagination.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/common/pagination.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-9006: e2eMonitorPaginationTests

---

Jenkinsfile

DHFPROD-9036: Updated the command to run tests on chrome

---

examples/reference-entity-model/src/main/ml-modules/root/custom-modules/custom/user-params.sjs
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingParameterModulePath.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/advanced-settings-dialog.tsx
marklogic-data-hub-central/ui/e2e/hc-qa-project/src/main/ml-modules/root/custom-modules/custom/user-params.sjs
marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.module.scss
marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx
marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx
marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.test.tsx
marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx
marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.tsx
marklogic-data-hub-central/ui/src/components/steps/steps.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
marklogic-data-hub-central/ui/src/types/common-types.ts

- To verify, go to advanced settings of any mapping step
- Edit the "Parameter Module Path Field"
- Add any string for an invalid path error
- Add "/custom-modules/custom/user-params.sjs" for valid path.
```diff
```
- ##### Owner:

DHFPROD-7360: Add new mapping field for Parameter Module Path

---

marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-8986: Verify the privileges assigned to hub-central-step-runner role

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/content/last-names.xml

DHFPROD-8982: Convert Double Metaphone function to JavaScript

---

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx
marklogic-data-hub-central/ui/src/api/modeling.ts
marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling.js
marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/concept-class-modal/concept-class-modal.module.scss
marklogic-data-hub-central/ui/src/components/modeling/concept-class-modal/concept-class-modal.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/concept-class-modal/concept-class-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
marklogic-data-hub-central/ui/src/config/graph-vis.config.ts
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx
marklogic-data-hub-central/ui/src/pages/Modeling.tsx
marklogic-data-hub-central/ui/src/util/hubCentralConfig-context.tsx
marklogic-data-hub-central/ui/src/util/modeling-utils.tsx

Functionality to add concepts in the Modeling screen.
Unit and Integration tests added in RTL. E2E will be added as part of future stories when delete/edit capabilities will be added.
```diff
```
- ##### Owner:

DHFPROD-8765: Add new concept class from Graph view in Modeling screen

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreXMLValidations.spec.tsx
marklogic-data-hub-central/ui/src/components/facet/facet-element.tsx
marklogic-data-hub-central/ui/src/components/facet/facet.tsx
marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
marklogic-data-hub-central/ui/src/util/search-context.tsx

RetainStateExploreTile: for this PR are retained in local storage the checkboxes and the date of the "hub properties".
```diff
```
- ##### Owner:

DHFPROD-7023: RetainStateExploreTile

---

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractHubCentralTest.java
marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/environment/EnvironmentControllerTest.java

DHFPROD-9121: Fix Java Compile Errors in Pipeline

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/customer1.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/entities/Customer.entity.json

DHFPROD-9044: BE - Show recursive relationship in explore view

---

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/common/confirmation-modal.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/types/modeling-types.ts
marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
marklogic-data-hub-central/ui/src/types/common-types.ts

DHFPROD-7921: Provide warning for property rowId

---

marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx
marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx

DHFPROD-9000: RTL: Verify 'Add' button for Entities and properties for hub-central-model-writer and hub-central-model-reader

---

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx

- Steps to reproduce in the ticket.
```diff
```
- ##### Owner:

DHFPROD-8957: Mapping test failing with namespace error

---

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractHubCentralTest.java
marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/HubCentralManager.java
marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/GetProjectAsZipTest.java

DHFPROD-9123: GetProjectAsZipTest Intermittent failure

---

Jenkinsfile

DEVO-558: Update the builds to run on 11.0-nightly

---

marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.test.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.test.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.test.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.tsx
marklogic-data-hub-central/ui/src/components/header/system-info.test.tsx
marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.test.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx

DHFPROD-8416: UI Tests Not Working with Tooltips

---

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-table.tsx

DHFPROD-9002: e2eStructuredProperty

---

Jenkinsfile

DHFPROD-9036: Do not exit on test failures

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/DataHubImplTest.java

DHFPROD-9089: Validating ML 11.x on preInstallCheck

---

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx

DHFPROD-8071: Graph not moving the focus on node on filtered entity type

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/common.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/core/models/entityModel.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs

DHFPROD-8939: Implement buildMergeDocument for Mergeable

---

marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/HubCentralManager.java
marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/GetProjectAsZipTest.java
marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java

DHFPROD-9123: Fix for GetProjectAsZip core test

---

marklogic-data-hub-central/ui-custom/e2e/cypress/integration/recordsDetailPage.spec.tsx

This update fixes failing Twizzlers e2e tests.
```diff
```
- ##### Owner:

DHFPROD-9138: Fix e2e tests

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/stepDefinition.sjs
marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/FlowRunnerTest.java
marklogic-data-hub/src/testFixtures/resources/flow-runner-test/flows/invalidModuleFlow.flow.json
marklogic-data-hub/src/testFixtures/resources/flow-runner-test/modules/root/custom-modules/custom.invalid/invalidModulePath.sjs
marklogic-data-hub/src/testFixtures/resources/flow-runner-test/step-definitions/custom/invalidModule/invalidModule.step.json

DHFPROD-8854: XDMP-MODNOTFOUND error message pointing the wrong module

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreGraphFacetConsistentNavigation.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/common/confirmation-modal.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs

DHFPROD-9112: Fix intermittent E2E failures on PRs - runFlow.spec.tsx

---

marklogic-data-hub/src/main/java/com/marklogic/hub/MasteringManager.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/MasteringManagerImpl.java
marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMerge/deleteMerge.sjs
ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/UnmergeRecordTask.groovy
ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/ManualMergeUnmergeTaskTest.groovy

DHFPROD-8961: Gradle task to remove an item from a mastered record

---

marklogic-data-hub-central/ui/src/components/common/entity-type-color-picker/entity-type-color-picker.tsx

Fix to handle the closed popover after clicking inside the input.
```diff
```
- ##### Owner:

DHFPROD-7929: ControlMaximumLengthOfColorName

---

.github/dependabot.yml

DEVO-555: Adding dependabot configuration for automatic security updates

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/common/create-edit-step-dialog.tsx
marklogic-data-hub-central/ui/src/components/steps/steps.tsx

DHFPROD-9124: EditMatchMergeSettingsShowsNoCollect

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingParameterModulePath.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx

DHFPROD-9142: Fix intermittent E2E failures on nightly

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MergingStepController.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/MasteringManagerImpl.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs
marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/searchResultFacetsTest.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/test-data/content/jane.json

DHFPROD-9138: Add unmerge property to entity search results

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs

DHFPROD-8984: Convert Zip function to JavaScript

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingRelatedRolesPrivileges.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx

DHFPROD-8997: Verify the privileges assigned to hub-central-mapping-writer role

---

marklogic-data-hub-central/ui/src/pages/Run.tsx

DHFPROD-8825: Run flow modal preserves last run status

---

.github/dependabot.yml
Jenkinsfile

DHFPROD-9037: Updating the new machien

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/custom.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/entityMappingMoreLessFunctionality.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/entity-tiles.test.tsx
marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx
marklogic-data-hub-central/ui/src/pages/Curate.test.tsx

Indicator Of Curate Tabs With Config Artifacts
```diff
```
- ##### Owner:

DHFPROD-8282: Indicator Of Curate Tabs With Config Artifacts

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx

DHFPROD-9007: Verify sorting in monitor tile

---

examples/reference-entity-model/entities/Product.entity.json
marklogic-data-hub-central/ui/src/pages/Detail.module.scss
marklogic-data-hub-central/ui/src/pages/Detail.tsx
marklogic-data-hub-central/ui/src/util/data-conversion.tsx

DHFPROD-8100: Show relationships to other concepts at record-level

---

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx

DHFPROD-8699: Filter concept classes in Modeling graph view

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/MappingController.java
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/verifyConceptClassesInModeling.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-vis.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/relationship-modal.tsx
marklogic-data-hub-central/ui/src/api/mapping.tsx
marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.module.scss
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.module.scss
marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.scss
marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
marklogic-data-hub-central/ui/src/util/common-utils.tsx
marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MappingService.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/getMappingFunctions.api
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/getMappingFunctions.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getMappingFunctionsTest.sjs

DHFPROD-8740: Create relationship between Entity type and Concept class node via Add relationship button

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingRelatedRolesPrivileges.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx

DHFPROD-8996: Verify the privileges assigned to hub-central-mapping-reader role

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/EntityManagerImpl.java

DHFPROD-8109: Ordering protected path files by name.

---

marklogic-data-hub-central/ui/src/App.scss
marklogic-data-hub-central/ui/src/components/footer/footer.module.scss
marklogic-data-hub-central/ui/src/pages/Monitor.tsx
marklogic-data-hub-central/ui/src/pages/Overview.module.scss
marklogic-data-hub-central/ui/src/pages/Overview.tsx
marklogic-data-hub-central/ui/src/pages/TilesView.module.scss
marklogic-data-hub-central/ui/src/theme/HCVariables.scss

Improve Page CSS Responsiveness
```diff
```
- ##### Owner:

DHFPROD-9100: Improve Page CSS Responsiveness

---

Jenkinsfile

DHFPROD-9036: Archiving test results

---

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getMappingFunctionsTest.sjs

DHFPROD-6169: Removed extra comma.

---

marklogic-data-hub-central/ui/src/components/facet/facet-element.tsx
marklogic-data-hub-central/ui/src/components/facet/facet.module.scss
marklogic-data-hub-central/ui/src/components/facet/facet.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.test.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx

DHFPROD-9166: Explore Entity Sidebar Containers are Cut Off

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/entityMappingFunctionalities.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx

DHFPROD-8992: e2ePersistFilter

---

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/PreinstallCheckTask.groovy

DHFPROD-8973: Ensure final db indexes are deployed

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingRelatedRolesPrivileges.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx

DHFPROD-8990: e2eMappingConfig

---

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelTest.java
marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/PublishModelsTest.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-trigger.xqy

DHFPROD-8687: Changing Entity Model versions can create multiple TDEs for an entity which may conflict

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx

DHFPROD-9034: e2eWinFailuresPt1

---

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx
marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx
marklogic-data-hub-central/ui/src/components/header/header.module.scss
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx

DHFPROD-9004: RTL: Validate modeling Graph UI text

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/MappingController.java
marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/MappingService.java

DHFPROD-9169: Making mapping service compatible with Community Edition.

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeNotification.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphEntitiesSettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/explore.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-9163: Fix failures on nightly - 10.0-9-Win10-On-Prem-Firefox

---

marklogic-data-hub-central/ui/src/config/tiles.config.ts
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx

…w to be generic
```diff
```
- ##### Owner:

DHFPROD-9118: Update entity model specific text in Modeling graph view to be generic

---

marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.test.tsx

DHFPROD-9012: RTL: Verify merge settings privileges for data-hub-match-merge-writer and data-hub-match-merge-reader

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/matching.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/merging.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMergeOptionsLib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/common.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matcher.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/merger.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/core/models/entities.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/ingestMapMaster/ingestMapMatchMerge.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs

DHFPROD-9131: Use mergeable class

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeNotification.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/unMerge.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/api/merging.ts
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs

- Modal setup for unmerge in table view and snippet view
- Out of scope but to follow with DHFPROD-9136 PR: Submit button functionality.
```diff
```
- ##### Owner:

DHFPROD-9126: Unmerge documents via details page

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MergingStepController.java
marklogic-data-hub/src/main/resources/ml-modules/services/mlSmMerge.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/searchResultFacetsTest.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/entitySearch/test-data/content/smNotifiedDoc.xml
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmMerge/post.sjs

DHFPROD-9178: End point to expose manual merge functionality

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
marklogic-data-hub-central/ui/src/types/modeling-types.ts

DHFPROD-8959: View Related Concept Classes tab in Modeling

---

marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx

DHFPROD-9183: fix prop name issue

---

marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx

DHFPROD-9034: e2eWinFailuresPt2

---

examples/README.md
examples/SLED/build.gradle
examples/dh-5-example/build.gradle
examples/dhf5-custom-hook/build.gradle
examples/insurance/build.gradle
examples/mapping-example/build.gradle
examples/patient-hub/build.gradle
examples/reference-entity-model/build.gradle
examples/smart-mastering-complete/build.gradle
examples/snapshot-testing/build.gradle
examples/step-interceptors/build.gradle
gradle.properties
marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java
marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json
marklogic-data-hub/src/main/resources/scaffolding/build_gradle
performance-tests/projects/commoncrawl/build.gradle

DHFPROD-9180: Updating the version to 5.8.0-rc1

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs

DHFPROD-9187: Restore validation of foreign between entities on delete

---

marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx

… to see the whole version.
DHFPROF-9158: In Model, an Entity's version property box is too small to see the whole version.
```diff
```
- ##### Owner:
- [n/A] Added Tests

DHFPROD-9158: In Model, an Entity's version property box is too small to see the whole version.

---

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx

DHFPROD-9005: RTL: Ready-only user should not be able to edit entity type description and namespace

---

marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx

DHFPROD-9216: e2eAuthFix

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs

DHFPROD-9202: Make merge comparison work in ML9

---

ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/InstalledTests.groovy

DHFPROD-9223: Reset properties file after testing DB setting

---

marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js

DHFPROD-9188: Update label/tooltip text for Physics animation toggle in Hub Central Explore Graph View

---

marklogic-data-hub-central/ui/src/components/column-selector/column-selector.test.tsx

DHFPROD-9009: RTL: Validate Typeahead search for properties of an entity

---

examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/dashboard.config.sjs
examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/detail.config.sjs
examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/search.config.sjs
marklogic-data-hub-central/ui-custom/src/components/RecentRecords/RecentRecords.test.tsx
marklogic-data-hub-central/ui-custom/src/components/RecentRecords/RecentRecords.tsx
marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.test.tsx
marklogic-data-hub-central/ui-custom/src/components/ResultsList/ResultsList.tsx
marklogic-data-hub-central/ui-custom/src/views/Detail.test.tsx
marklogic-data-hub-central/ui-custom/src/views/Detail.tsx

See: https://wiki.marklogic.com/display/ENGINEERING/Make+Entity+Type+path+configurable
```diff
```
- ##### Owner:

DHFPROD-9032: Make entity type configurable

---

examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/detail.config.sjs
marklogic-data-hub-central/ui-custom/src/components/Relationships/Relationships.tsx

Also enable color styling of different node types and ability to turn on/off links for node types.
```diff
```
- ##### Owner:

DHFPROD-9132: Support multiple node types in Relationships

---

examples/entity-viewer/src/main/ml-modules/root/explore-data/ui-config/detail.config.sjs
marklogic-data-hub-central/ui-custom/src/components/Relationships/Relationships.tsx
marklogic-data-hub-central/ui-custom/src/components/Timeline/Timeline.scss
marklogic-data-hub-central/ui-custom/src/components/Timeline/Timeline.test.tsx
marklogic-data-hub-central/ui-custom/src/components/Timeline/Timeline.tsx
marklogic-data-hub-central/ui-custom/src/views/Detail.tsx

Also support coloring marker types. 
```diff
```
- ##### Owner:

DHFPROD-9133: Support multiple marker types and ranges in Timeline

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.tsx

Remove Step From Flow Causes Run Flow Issues
```diff
```
- ##### Owner:

DHFPROD-9201: Remove Step From Flow Causes Run Flow Issues

---

marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx

DHFPROD-9192: 'Action' Info icon in Run step modal doesn't do anything

---

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/hubURI.sjs

DHFPROD-9225: Fix for Test failure hubURI.sjs

---

marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs

DHFPROD-9221: Merge options missing when attempting to unmerge

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/common/toolbar.tsx

DHFPROD-9034: e2eWinFix

---

marklogic-data-hub-central/ui/src/assets/mock-data/curation/merging.data.ts
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.module.scss

- To reproduce, must merge > 2 documents together
- Navigate to Explore for unmerge functionality
```diff
```
- ##### Owner:

DHFPROD-9189: Add Total Count to Compare Match Modal

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/verifyConceptClassesInModeling.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/explore.tsx

DHFPROD-9010: e2eValidateSort

---

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/verifyConceptClassesInModeling.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/commands.js

DHFPROD-9240: e2eWinFix

---

marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/verifyConceptClassesInModeling.spec.tsx

DHFPROD-9268: e2eAuthFix

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs

DHFPROD-7054: Error messages for invalid URIs.

---

marklogic-data-hub-api/build.gradle
marklogic-data-hub-central/gradle.properties
marklogic-data-hub-junit5/build.gradle
marklogic-data-hub/build.gradle
ml-data-hub-plugin/build.gradle

DHFPROD-8144: Updating ml-gradle/ml-app-deployer and spring dependencies

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.tsx

DHFPROD-9227: Running a load step runs whole flow

---

examples/SLED/entities/MedicalHistory.entity.json
examples/SLED/src/main/entity-config/exp-final-entity-options.xml
examples/SLED/src/main/entity-config/exp-staging-entity-options.xml
examples/SLED/src/main/entity-config/final-entity-options.xml
examples/SLED/src/main/entity-config/staging-entity-options.xml
examples/SLED/src/main/ml-config/database-fields/final-database.xml
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/mappable-entity-lib.sjs

DHFPROD-9238: Fix SLED entity relationship

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/matchableInterceptors.sjs

DHFPROD-9220: Pass match rule as node

---

marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/graph-view.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore.tsx
marklogic-data-hub-central/ui/src/types/view-types.ts

DHFPROD-9198: Retain State: Explore

---

marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/verifyConceptClassesInModeling.spec.tsx
marklogic-data-hub-central/ui/e2e/package-lock.json
marklogic-data-hub-central/ui/e2e/package.json
marklogic-data-hub-central/ui/package-lock.json
marklogic-data-hub-central/ui/package.json

DHFPROD-9185: Assess git hub vulnerabilities

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingParameterModulePath.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphEntitiesSettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx

DHFPROD-9193: Fix failures on nightly - 10.0-9-Win10-On-Prem-chrome

---

marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx
marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx

Retain State Monitoring Expand Collapse
```diff
```
- ##### Owner:

DHFPROD-9196: Retain State Monitoring Expand Collapse

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeNotification.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx
marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx

DHFPROD-9248: Merge properties not always highlighted

---

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx

DHFPROD-9224:  A newly loaded project, in the model view, has the entities moving indefinately.

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/nodeExpand.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchWithConfigProperties.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/nodeExpand.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/babyRegistry1.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/entities/BabyRegistry.entity.json

DHFPROD-9232: Error when expanding nodes in graph view

---

marklogic-data-hub-central/ui/src/pages/Overview.module.scss
marklogic-data-hub-central/ui/src/pages/Overview.tsx

DHFPROD-9334: Home Page info icon disappearing

---

marklogic-data-hub-central/ui/e2e/cypress/fixtures/config/hubCentral.json
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphEntitiesSettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/verifyConceptClassesInModeling.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorColumnSelector.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorCustomDatePicker.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx

DHFPROD-8540: e2ePreserveSession

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/concept-lib.sjs

**Test cases will be covered in PR DHFPROD-9333**
```diff
```
- ##### Owner:

DHFPROD-9329: Problem deleting a concept class and its relationship

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MergingStepController.java
marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/exceptions/CustomExceptionHandler.java
marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MergingStepControllerTest.java
marklogic-data-hub/src/main/java/com/marklogic/hub/MasteringManager.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/MasteringManagerImpl.java
marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/notification-impl.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs

DHFPROD-9317: Add notification endpoints

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx

DHFPROD-9008: verifyFacets

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx

DHFPROD-9335: e2eWinFixes

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/test-data/entities/Customer.entity.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/testSchemaGeneration.sjs

DHFPROD-9316: Correct schema generation for complex models

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx

Update Additional Relation Leaf Node Ellipsis.
Added a fix for unrelated e2e "mappingWithInterceptorsAndCustomHook.spec".
```diff
```
- ##### Owner:

DHFPROD-9141: UpdateAdditionalRelationShipLeafNode

---

marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx
marklogic-data-hub-central/ui/src/pages/Detail.tsx

DHFPROD-9273: Detail View Relationships Missing Links

---

marklogic-data-hub-central/ui/src/components/detail-header/detail-header.module.scss
marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.module.scss
marklogic-data-hub-central/ui/src/components/steps/steps.scss
marklogic-data-hub-central/ui/src/components/steps/steps.tsx
marklogic-data-hub-central/ui/src/pages/Detail.module.scss

DHFPROD-9274: Detail View Scroll Overflow
```diff
```
- ##### Owner:
- [n/a ] Added to Release Wiki

DHFPROD-9274: Detail View Scroll Overflow

---

marklogic-data-hub-central/ui/e2e/package-lock.json
marklogic-data-hub-central/ui/e2e/package.json

DHFPROD-9353: Fix git hub vulnerabilities - Minimist

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/suite-setup.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/product100.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/product50.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/product60.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/product70.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/product80.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/product90.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/entities/Product.entity.json

DHFPROD-9297: Eliminate ghost node

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx

DHFPROD-9253: Testing sample data in a matching step it deletes more URIs than the one I select

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingParameterModulePath.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeWarnings.spec.tsx

DHFPROD-9335: e2eWinFix

---

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/verifyConceptClassesInModeling.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/common/tables.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-modal.tsx

DHFPROD-9377: Fix the failing intermittent cypress e2e scripts on PRs

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flow/flowRunner/ingestMapMaster/ingestMapMatchMerge.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs

DHFPROD-9289: Don't show archived documents for entity search

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.tsx

DHFPROD-9234: In Run tile, Run flow selections are not correct.

---

marklogic-data-hub-central/ui/src/api/merging.ts
marklogic-data-hub-central/ui/src/assets/mock-data/explore/entity-search.js
marklogic-data-hub-central/ui/src/components/record-view/record-view.test.tsx
marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx

DHFPROD-9246: Remove notifications after merge

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeNotification.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/common/toolbar.tsx
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.module.scss
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx

Populate Notifications Table Menu
```diff
```
- ##### Owner:

DHFPROD-9320: Populate Notifications Table Menu

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx

DHFPROD-9286: Failed mastering step gives no indication about why it failed

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matcher.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/content/docB.json

DHFPROD-9379: Don't query on empty values

---

examples/reference-entity-model/concepts/ShoeType.concept.json
marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.test.tsx
marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.tsx
marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx
marklogic-data-hub-central/ui/src/pages/TilesView.tsx

DHFPROD-9174: Model page - unnecessary API calls

---

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/notification-impl.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/matching.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matcher.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/merger.sjs
marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java
marklogic-data-hub/src/test/resources/master-test/flows/myMatchMergeFlow.flow.json

DHFPROD-9386: Return Match Step Name in Notifications Endpoint

---

marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx
marklogic-data-hub-central/ui/src/pages/Run.tsx

…shows the latest general flow run
```diff
```
- ##### Owner:

DHFPROD-9304: In Run tile, the info of the status of the flow always shows the latest general flow run

---

marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.module.scss
marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/entity-display-settings/entity-display-settings.tsx

DHFPROD-9271: Fix Hover Effect in Table Data Model Display Settings

---

marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx

DHFPROD-9342: In Explore, Related Entities appears unchecked and entities are checked.

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/HubCentral.java
marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/HubCentralTest.java

DHFPROD-9390: Read properties passed into environment while running war file

---

marklogic-data-hub-central/ui/src/pages/TilesView.tsx

DHFPROD-9235: JS Error When Deleting Concepts

---

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/notification-impl.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matcher.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/merger.sjs

DHFPROD-9410: Adding flowName to notifications endpoint

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSidePanel.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx

DHFPROD-9398: e2eFixesForLinux

---

marklogic-data-hub-central/ui/src/components/explore/graph-view-explore.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx

DHFPROD-9256:Right model panel hidden after move it in Model and Explore

---

marklogic-data-hub-central/ui/src/api/matching.ts
marklogic-data-hub-central/ui/src/assets/mock-data/explore/Non-entity-document-payload.js
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/components/record-view/record-view.test.tsx
marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx
marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx

DHFPROD-9324: Enhance Third Preview Column

---

Jenkinsfile

DHFPROD-9037: Fixing mac cypress regression

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeNotification.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeUnmergePrivileges.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/common/toolbar.tsx
marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx
marklogic-data-hub-central/ui/src/types/common-types.ts

ApplyNotificationsDeleteAction
```diff
```
- ##### Owner:

DHFPROD-9322: Apply Notifications Delete Action

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeNotification.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/src/App.tsx
marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts
marklogic-data-hub-central/ui/src/assets/mock-data/curation/ingestion.data.ts
marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/header/header.tsx
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.module.scss
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx
marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx

DHFPROD-9321: Apply Notifications Merge Action

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/validationsWithoutHubCentralConfig.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts
marklogic-data-hub-central/ui/e2e/cypress/support/pages/explore.tsx

DHFPROD-9029: e2e validate entity display settings without hubCentralConfig

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/test-data/content/CustMatchMerge1.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/test-data/content/NsCustMatchMerge1.xml

DHFPROD-9389: Fix triple merge regression

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/template-generated.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateSearchOptions.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/generateTDE.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/verifyTdeContext.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/generateTDEWithNoPrimaryKey.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/generateTDEWithRelatedEntityType.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/test-data/content/order.json

DHFPROD-9403: Fix triples for entities without primary key

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/entitiesWithConceptsTypes.sjs

DHFPROD-9242: Fix concepts when it includes characters like #

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/MasteringManagerImpl.java

DHFPROD-9284: Unmerge fails for non-standard database names

---

marklogic-data-hub-central/ui/src/App.tsx
marklogic-data-hub-central/ui/src/api/merging.ts
marklogic-data-hub-central/ui/src/assets/mock-data/notification-context-mock.ts
marklogic-data-hub-central/ui/src/components/header/header.tsx
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.test.tsx
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
marklogic-data-hub-central/ui/src/components/search-pagination-simple/search-pagination-simple.module.scss
marklogic-data-hub-central/ui/src/components/search-pagination-simple/search-pagination-simple.test.tsx
marklogic-data-hub-central/ui/src/components/search-pagination-simple/search-pagination-simple.tsx
marklogic-data-hub-central/ui/src/util/notification-context.tsx

Notification Table Pagination With Endpoint.
**Video with instructions in the Jira ticket.**
```diff
```
- ##### Owner:

DHFPROD-9401: Notification Table Pagination With Endpt

---

marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.module.scss
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx
marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx
marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx

DHFPROD-9417: Notifications Consistency with Disabled Permissions

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingRelatedRolesPrivileges.spec.tsx
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/mergeableInterceptors.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs

DHFPROD-9285: Restore previous way of passing source to merge functions

---

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/notification-impl.xqy
marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java

DHFPROD-9385: Return labels in Notification endpoint

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeNotification.spec.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx

```diff
```
- ##### Owner:
- NA Added Tests

DHFPROD-9425: Missing renders in Compare Modal

---

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx
marklogic-data-hub-central/ui/src/util/modeling-utils.tsx

DHFPROD-9337: Creating a new model with a color does not show the color in the graph

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/template-generated.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/concepts/statusConcept.concept.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/namespacedCustomer1.xml
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/entities/NamespacedCustomer.entity.json

DHFPROD-9418: Creating a concept for namespaced entities

---

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/notification-impl.xqy
marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java
marklogic-data-hub/src/test/resources/master-test/entities/person.entity.json

```diff
```
- ##### Owner:
- NA Added to Release Wiki

DHFPROD-9436: GET notification to work when there is no primary key

---

marklogic-data-hub-central/ui/src/assets/mock-data/notification-context-mock.ts
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/header/header.tsx
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.module.scss
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
marklogic-data-hub-central/ui/src/util/notification-context.tsx

Error In Pagination Deleting Row In Last Page
```diff
```
- ##### Owner:
- n/a Ran cypress tests on firefox locally

DHFPROD-9422: Error In Pagination Deleting Row In Last Pag

---

marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx

Generic Error In Explore Sled Project
```diff
```
- ##### Owner:

DHFPROD-9431: Generic Error In Explore Sled Project

---

marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx

DHFPROD-9437: Format Structured Data in Compare Modal

---

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx

DHFPROD-9441: Generic Error In Matching Step Detail screen

---

examples/README.md
examples/SLED/build.gradle
examples/dh-5-example/build.gradle
examples/dhf5-custom-hook/build.gradle
examples/insurance/build.gradle
examples/mapping-example/build.gradle
examples/patient-hub/build.gradle
examples/reference-entity-model/build.gradle
examples/smart-mastering-complete/build.gradle
examples/snapshot-testing/build.gradle
examples/step-interceptors/build.gradle
gradle.properties
marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java
marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json
marklogic-data-hub/src/main/resources/scaffolding/build_gradle
performance-tests/projects/commoncrawl/build.gradle

DEVO-641: Updating the version 5.8.0-rc2

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreGraphFacetConsistentNavigation.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx

DHFPROD-9398: e2e fixes

---

ml-data-hub-plugin/build.gradle

DEVO-643: Updating the dependency of the publish plugin

---

marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.test.tsx
marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx

DHFPROD-9339: Collection and Query tooltips are swapped

---

marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/nodeExpand.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/nodeExpand.sjs

DHFPROD-9478: fix undefined .length error

---

marklogic-data-hub-api/build.gradle
marklogic-data-hub/build.gradle
ml-data-hub-plugin/build.gradle

DHFPROD-9443: Load schemas using mlLoadSchemas on 10.0-9 and above

---

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FixCreatedByStepTest.java

```diff
```
- ##### Owner:
-  N/A Code passes ESLint tests
-  N/A Added Tests
-  N/A Ran cypress tests on firefox locally

DHFPROD-9162: Added error log to get more information from pipeline.

---

CODEOWNERS

DHFPROD-9509: Update code owners file

---

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioGraph.spec.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx

DHFPROD-9433: Operation Failed on graph view

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/custom.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx

DHFPROD-9283: e2eFixes

---

marklogic-data-hub-api/src/main/java/com/marklogic/hub/HubClient.java
marklogic-data-hub-api/src/main/java/com/marklogic/hub/impl/HubClientImpl.java
marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/HttpSessionHubClientProvider.java
marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/HubClientProvider.java
marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/auth/AuthenticationFilter.java
marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/BaseController.java
marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MergingStepController.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/MasteringManagerImpl.java

DHFPROD-9475: Creating HubClientConfig object during authentication

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx

DHFPROD-9502: Fix Intermittent failures e2e failure on PR's

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMatchOptionsLib.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/updateMatchOptions.sjs

DHFPROD-9384: Update match step conversion account for more settings

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx

DHFPROD-9350: e2eLinuxFixes

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/nodeExpand.sjs

DHFPROD-9511: Fix node expand on ML 10.0-7

---

marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx

DHFPROD-9477: The product group node should not be displayed

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/template-generated.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/generateTDEWithConceptType.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/generateTDEWithRelatedEntityType.sjs

DHFPROD-9120: Triples generated for null values

---

marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-9489: Fixes Win10 Chrome

---

marklogic-data-hub-central/ui/e2e/cypress.json
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreColumnSelector.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphGroupNodes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorColumnSelector.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/explore.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-9283: Fix failures on nightly - cypress-win-firefox

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java
marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/AbstractMvcTest.java
marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java
marklogic-data-hub-central/src/test/resources/test-projects/run-flow-test/flows/CurateCustomerJSON.flow.json
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
marklogic-data-hub-central/ui/src/pages/Run.tsx

DHFPROD-9466: Run Flows API should use flow and step names

---

marklogic-data-hub/build.gradle

DHFPROD-9537:Fix for palamida spring core vulnerabilities

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMatchOptionsLib.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/test-data/steps/matching/matchCustomers.step.json

DHFPROD-9546: Match step to work when distance threshold is not defined

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.tsx

Run Flows State Retainment
```diff
```
- ##### Owner:

DHFPROD-9456: RunFlowsStateRetainment

---

examples/SLED/gradle.properties
marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/verifyReaderRoleCantPublish.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx

DHFPROD-9586: Fix failures on nightly - 10.0-9-Win10-On-Prem-chrome

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/template-generated.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchWithConfigProperties.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/nodeExpand.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/concepts/zipConcept.concept.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/entities/Customer.entity.json

DHFPROD-9496: Concept context for structured properties

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/nodeExpand.sjs

DHFPROD-9588: Return concept class name

---

marklogic-data-hub-api/src/main/java/com/marklogic/hub/MarkLogicVersion.java
marklogic-data-hub/src/test/java/com/marklogic/hub/MarkLogicVersionTest.java

DHFPROD-9590: Accomodate ML 11 Server Version number changes

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/graphExplore.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
marklogic-data-hub-central/ui/src/pages/Browse.tsx

```diff
```
- ##### Owner:
Test plan: 
https://wiki.marklogic.com/display/ENGINEERING/Test+plan+for+Explore+Graph+count

DHFPROD-9356: In Explore, when toggling "Concepts" off/on the results count doesn't update.

---

examples/SLED/README.md
examples/SLED/steps/mapping/HarmonizeClaimItems.step.json
examples/SLED/steps/mapping/HarmonizeClaims.step.json
examples/SLED/steps/mapping/mapCMSProvider.step.json
examples/SLED/steps/mapping/mapCuram.step.json
examples/SLED/steps/mapping/mapHospitalAffiliation1.step.json
examples/SLED/steps/mapping/mapHospitalAffiliation2.step.json
examples/SLED/steps/mapping/mapHospitalAffiliation3.step.json
examples/SLED/steps/mapping/mapHospitalAffiliation4.step.json
examples/SLED/steps/mapping/mapHospitalAffiliation5.step.json
examples/SLED/steps/mapping/mapMMIS.step.json
examples/SLED/steps/mapping/mapMMISNew.step.json
examples/SLED/steps/mapping/mapOrgAssociation.step.json
examples/SLED/steps/mapping/mapServiceLocation.step.json

DHFPROD-9154: Fix SLED prefixes to be consistent

---

examples/online-store/build.gradle
examples/online-store/plugins/entities/Order/Order.entity.json
examples/online-store/plugins/entities/Product/Product.entity.json
examples/online-store/src/main/entity-config/databases/final-database.json
examples/online-store/src/main/entity-config/databases/staging-database.json
examples/online-store/src/main/entity-config/final-entity-options.xml
examples/online-store/src/main/entity-config/staging-entity-options.xml

DHFPROD-9299: Online store example 4.3.2 changes

---

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MergingStepControllerTest.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/lib.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/getDefaultCollections.sjs

DHFPROD-9464: Set/remove Entity collection in manual merge/unmerge

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphGroupNodes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/graph-view.tsx

DHFPROD-9613: Fix intermittent failures on PRs

---

Jenkinsfile

DHFPROD-9354: Updating Timeout to 5hours

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/template-generated.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/nodeExpand.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/customer1.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/entities/Customer.entity.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/generateTDEWithConceptType.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/generateTDEWithRelatedEntityType.sjs

DHFPROD-9491: BE - Creating a relationship by a property other than id

---

marklogic-data-hub-central/ui/src/components/modeling/concept-class-modal/concept-class-modal.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/concept-class-modal/concept-class-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx
marklogic-data-hub-central/ui/src/config/modeling.config.ts
marklogic-data-hub-central/ui/src/pages/Modeling.tsx

DHFPROD-9535: Error creating a concept with existing

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx
marklogic-data-hub-central/ui/src/pages/Browse.tsx
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/entitiesWithConceptsTypes.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FixCreatedByStepTest.java
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/getEntitiesTypesWithRelatedConceptsTypes.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchFacets.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchWithConfigProperties.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/nodeExpand.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/setup.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/suite-setup.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/triples.xml

9563 is also inlcuded as a part of this ticket
```diff
```
- ##### Owner:

DHFPROD-9597: Condition Concepts search on compatible ML version

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphConceptsSettings.spec.tsx
marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/concepts-display-settings/concepts-display-settings.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx

DHFPROD-9258: Concepts Settings Modal

---

marklogic-data-hub-central/ui/src/components/common/hc-button/hc-button.tsx
marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx
marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx

fixed some warning that appears in the Monitor View
```diff
```
- ##### Owner:

DHFPROD-9264: Clean up Console Warnings - Monitor

---

marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx

DHFPROD-9598: FE - 5.8 Graph Issues

---

marklogic-data-hub-central/ui/src/components/common/confirm-yes-no/confirm-yes-no.tsx
marklogic-data-hub-central/ui/src/components/common/hc-modal/hc-modal.test.tsx
marklogic-data-hub-central/ui/src/components/common/hc-modal/hc-modal.tsx
marklogic-data-hub-central/ui/src/components/common/index.ts
marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.tsx
marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/delete-modal/delete-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merge-delete-modal/merge-delete-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.tsx
marklogic-data-hub-central/ui/src/components/flows/confirmation-modals.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx
marklogic-data-hub-central/ui/src/util/test-utils.tsx

DHFPROD-9396: Close Modals in Hub Central with ESC Key

---

Jenkinsfile

DHFPROD-9515: Adding 10.0.Nightly to Jenkins file

---

Jenkinsfile

Removing Emails

---

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
marklogic-data-hub-central/ui/src/config/messages.config.tsx
marklogic-data-hub-central/ui/src/config/messages.module.scss

DHFPROD-7057: Validate that the URI is valid from the Mapping configuration

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreGraphFacetConsistentNavigation.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
marklogic-data-hub-central/ui/src/pages/Browse.module.scss
marklogic-data-hub-central/ui/src/pages/Browse.tsx

DHFPROD-9281: Add Loading Message while Graph Loads

---

marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/expandable-table-view/expandable-table-view.tsx

DHFPROD-9610: Clean up Console Warnings - Matching Step Details

---

marklogic-data-hub-central/ui/src/components/explore/table-view-group-nodes/table-view-group-nodes.tsx
marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.test.tsx
marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx
marklogic-data-hub-central/ui/src/components/header/system-info/system-info.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
marklogic-data-hub-central/ui/src/components/load/load-card.tsx
marklogic-data-hub-central/ui/src/components/load/load-list.tsx
marklogic-data-hub-central/ui/src/components/modal-status/modal-status.tsx
marklogic-data-hub-central/ui/src/components/modeling/concept-class-modal/concept-class-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.tsx
marklogic-data-hub-central/ui/src/components/queries/managing/edit-query-dialog/edit-query-dialog.tsx
marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx
marklogic-data-hub-central/ui/src/components/queries/queries.tsx
marklogic-data-hub-central/ui/src/components/queries/saving/discard-changes/discard-changes-modal.tsx
marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/edit-query-details.tsx
marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.tsx
marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx
marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.tsx
marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx
marklogic-data-hub-central/ui/src/components/steps/steps.tsx
marklogic-data-hub-central/ui/src/pages/TilesView.tsx

DHFPROD-9632: Close Modals in Hub Central with ESC Key

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreGraphFacetConsistentNavigation.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphCenterNode.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphConceptsSettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphEntitiesSettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphFocusDefocusCluster.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphGroupNodes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx

DHFPROD-9646: Fixing clicking on explore graph logic for e2e.

---

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchFacets.sjs

DHFPROD-9660: Improving tests for graphSearchFacets.

---

marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/concepts/TestConcept.concept.json

DHFPROD-9581: In Modeling tile, properties that are structured are not shown correctly

---

marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx

DHFPROD-9654: refresh details information

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreGraphFacetConsistentNavigation.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/graphExplore.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.module.scss
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js

DHFPROD-9658: Matching two URI's after a wrong match is unresponsive

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-9593: Add Flow Menu Select/Deselect e2e
```diff
```
- ##### Owner:

DHFPROD-9593: Add Flow Menu Select/Deselect e2e

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs

DHFPROD-9657: Limit number of nodes returned on graph search

---

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubAmpsCommand.java
marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java
marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/util/json/JSONObject.java
marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/thesaurus.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/sm-es-impl.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/notification-impl.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/options-impl.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/lib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/matching.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/merging.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collectorLib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/template-generated.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matcher.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/preview-matching-activity-lib.xqy
marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/endpoints/collectorLib/prepareSourceQuery.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableXQueryTest.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/matchableInterceptors.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/compile-options/mergeOptions.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/entityDrivenMatches.sjs

DHFPROD-9050: Additional matching performance updates

---

marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx

…raph
```diff
```
- ##### Owner:

DHFPROD-9662: Disable Structured properties as a foreign key on the graph 

---

marklogic-data-hub-central/ui/src/components/common/hc-input/hc-input.tsx

DHFPROD-9611: Clean up Console Warnings - Merging Step Details

---

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchFacets.sjs

DHFPROD-9660: Fix e2e test pipeline graphSearchFacets

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs

DHFPROD-9664: BE - Missing DocURi in related elements after a search

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx
marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx

DHFPROD-9382: Does not correctly work the initial view in curate.

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs

DHFPROD-9667: Address missing concepts in graph endpoint

---

marklogic-data-hub-central/ui/package-lock.json

DHFPROD-9668: Fix for Arbitrary Code execution security vulnerability

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/custom.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphFocusDefocusCluster.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSidePanel.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/graph-explore-side-panel.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/index.js
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx

DHFPROD-9663: Fix E2E tests on 11.0-Nightly-linux-On-Prem

---

marklogic-data-hub-central/ui/src/components/common/hc-input/hc-input.tsx
marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.module.scss
marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx

DHFPROD-9611: hc-input fixes

---

examples/README.md
examples/SLED/build.gradle
examples/dh-5-example/build.gradle
examples/dhf5-custom-hook/build.gradle
examples/insurance/build.gradle
examples/mapping-example/build.gradle
examples/patient-hub/build.gradle
examples/reference-entity-model/build.gradle
examples/smart-mastering-complete/build.gradle
examples/snapshot-testing/build.gradle
examples/step-interceptors/build.gradle
gradle.properties
marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java
marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json
marklogic-data-hub/src/main/resources/scaffolding/build_gradle
performance-tests/projects/commoncrawl/build.gradle

DEVO-678: Updating the versions to 5.8.0

---

marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx

DHFPROD-9609: Clean up Console Warnings - Mapping Step Details

---

marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
marklogic-data-hub-central/ui/src/components/table-view/table-view.tsx
marklogic-data-hub-central/ui/src/pages/Detail.tsx

DHFPROD-9263: Clean up Console Warnings - Explore

---

marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorCustomDatePicker.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx

Add Monitor Run Status E2E
```diff
```
- ##### Owner:

DHFPROD-9595: AddMonitorRunStatusE2e

---

marklogic-data-hub-central/ui/src/pages/Modeling.tsx

Clean Up Console Warnings Model
```diff
```
- ##### Owner:

DHFPROD-9265: CleanUpConsoleWarningsModel

---

Jenkinsfile

DHFPROD-9672: Enabling auto-merge to feature/5.8-develop branch

---

marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.test.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx

DHFPROD-9275: Enhancement on input search in explore page

---

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/notification-impl.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/getNotifications.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/setup.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/test-data/content/customer1.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/test-data/content/customer2.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/test-data/content/notification1.xml
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/test-data/content/notification2.xml

DHFPROD-9559: Notifications Table to use Record Labels when available

---

examples/README.md
examples/SLED/build.gradle
examples/dh-5-example/build.gradle
examples/dhf5-custom-hook/build.gradle
examples/insurance/build.gradle
examples/mapping-example/build.gradle
examples/patient-hub/build.gradle
examples/reference-entity-model/build.gradle
examples/smart-mastering-complete/build.gradle
examples/snapshot-testing/build.gradle
examples/step-interceptors/build.gradle
gradle.properties
marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java
marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json
marklogic-data-hub/src/main/resources/scaffolding/build_gradle
performance-tests/projects/commoncrawl/build.gradle

DHFPROD-9672: Updating version to 6.0-snapshot

---

marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx

DHFPROD-9259: Clean up Console Warnings - Notifications

---

marklogic-data-hub-central/ui/e2e/cypress/support/index.js

DHFPROD-9705: Fix cypress tests to fail the test on failure

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/graph-explore-side-panel.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
marklogic-data-hub-central/ui/src/components/facet/facet-name.tsx
marklogic-data-hub-central/ui/src/components/facet/facet.tsx
marklogic-data-hub-central/ui/src/pages/Modeling.tsx

DHFPROD-9706: Cannot check facets

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSidePanel.spec.tsx

DHFPROD-9719: Fix intermittent failures on PRs

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java
marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java

DHFPROD-9608: Run flow in the order of the steps

---

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss

DHFPROD-9533: UI Scrollbar Improvements

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getRecord.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/customer1.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/steps/matching/matchingStep.step.json

DHFPROD-9556: Unmerge via Explore Graph View

---

marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
marklogic-data-hub-central/ui/src/components/header/header.tsx

…atar
```diff
```
- ##### Owner:

DHFPROD-7915: User menu should disappear when you click away - user avatar

---

examples/smart-mastering-complete/steps/merging/merge-persons.step.json
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs

DHFPROD-9675: Protect against empty string collections

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java
marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/FlowService.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/flow/flow-lib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/flow/getFlowsWithLatestJobInfo.api
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/flow/getFlowsWithLatestJobInfo.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/flows/flowWithStepDetails2.flow.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job3.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/testGetFlowWithLatestJobInfo.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/testGetFlowsWithStepDetails.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/lib/flowService.sjs

DHFPROD-9552: Consolidate latestJobStatus calls

---

NOTICE.txt

DEVO-688: Updating Product notice for ml11

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MatchingStepController.java
marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MatchingStepControllerTest.java
marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ArtifactService.java
marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubModulesCommand.java
marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/exclusionList.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/getArtifact.api
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/getArtifact.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/getList.sjs

DHFPROD-9278: add endpoints for match exclusion lists

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/template-generated.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/TDEWithRelatedInsideStructured.sjs

DHFPROD-9638: BE - Relationships are missing on the graph

---

marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx

DHFPROD-9520: Adding a relationship without foreign key defined by string as default 

---

marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx

DHFPROD-9520: Adding a relationship without foreign key defined by string as default

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/unMerge.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx

- This PR also includes https://project.marklogic.com/jira/browse/DHFPROD-9557 (unmerged preview in compare modal)
- Tests added and 5.8.1 release wiki updated
```diff
```
- ##### Owner:

DHFPROD-9558: Include/Exclude unmerged documents from future match

---

marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.scss
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
marklogic-data-hub-central/ui/src/types/curation-types.ts

Double Metaphone Fuzzy Matching
```diff
```
- ##### Owner:

DHFPROD-9209: Double Metaphone Fuzzy Matching

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs

this is how we are showing the message in the UI
```diff
```
- ##### Owner:

DHFPROD-9490: Error messages not shown

---

marklogic-data-hub-central/ui/src/components/common/hc-modal/hc-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.scss
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx
marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.tsx

DHFPROD-9602: Sticky header in explorer settings modal

---

marklogic-data-hub-api/src/main/java/com/marklogic/hub/HubClientConfig.java
marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CheckSecurityConfiguration.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/CheckSecurityConfigurationTest.java

DHFPROD-9679: Add error messaging for role conflict

---

marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.scss
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx

Display Values To Ignore Menu, first part.
```diff
```
- ##### Owner:

DHFPROD-9707: Display Values To Ignore Menu

---

marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/entitySearch/GetRecordTest.java

DHFPROD-9512: Fix provenance core test failure - Intermittent

---

marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeWarnings.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/advanced-settings.tsx
marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.module.scss
marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx
marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-target-collections.tsx
marklogic-data-hub-central/ui/src/components/steps/steps.tsx

DHFPROD-9524: Option to remove collections from a document in a merge step through UI

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreUnmerge.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts
marklogic-data-hub-central/ui/e2e/cypress/support/pages/graphExplore.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/types/explore-graph-nodes.ts
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
marklogic-data-hub-central/ui/src/components/table-view/table-view.module.scss
marklogic-data-hub-central/ui/src/components/table-view/table-view.test.tsx
marklogic-data-hub-central/ui/src/components/table-view/table-view.tsx
marklogic-data-hub-central/ui/src/pages/Browse.tsx

DHFPROD-9555: Unmerge via Explore Graph View

---

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx

DHFPROD-9617: Migrate to RTL - mapping

---

marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.test.tsx
marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx

DHFPROD-9616: Add call to action when a flow doesn't have any steps

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.scss
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
marklogic-data-hub-central/ui/src/theme/HCVariables.scss

Create Edit New List In Values To Ignore
```diff
```
- ##### Owner:

DHFPROD-9677: Create Edit New List In Values To Ignore

---

marklogic-data-hub-central/ui/e2e/package-lock.json
marklogic-data-hub-central/ui/package-lock.json

DHFPROD-9704: Fixing GitBot Vulnarabilities

---

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
marklogic-data-hub-central/ui/src/util/data-conversion.tsx

DHFPROD-9728: Cut long relationship names in Related Concept Classes

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/queryHasher.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs

DHFPROD-9340: Add query hashes to match summaries

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/addMergeStepToFlow.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/run/runFlow.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/graphValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyConceptClassesInModeling.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/persistence/persistence.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-9746: Fix add merge step to flow cypress test

---

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FixCreatedByStepTest.java

DHFPROD-9162: Patch for intermittent test failure queryStep

---

Jenkinsfile

DHFPROD-9694: Setting CYPRESS_RUN_BINARY environment var

---

marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle

DEVO-699: Using nexus to download artifacts

---

examples/SLED/entities/Appointment.entity.json
examples/SLED/entities/MedicalEquipment.entity.json
examples/SLED/entities/OverTimeAssignment.entity.json
examples/SLED/src/main/ml-config/entities.layout.json

DHFPROD-9747: SLED Member's mapping step keeps loading

---

marklogic-data-hub/src/main/resources/ml-modules/services/hubFlowRunner.mjs
marklogic-data-hub/src/main/resources/ml-modules/services/hubJobs.mjs
marklogic-data-hub/src/main/resources/ml-modules/services/mlCollections.mjs
marklogic-data-hub/src/main/resources/ml-modules/services/mlJobs.mjs
marklogic-data-hub/src/main/resources/ml-modules/services/mlMappingValidator.mjs
marklogic-data-hub/src/main/resources/ml-modules/services/mlRunFlow.mjs
marklogic-data-hub/src/main/resources/ml-modules/services/mlSjsFlow.mjs
marklogic-data-hub/src/main/resources/ml-modules/services/mlSmMatch.mjs
marklogic-data-hub/src/main/resources/ml-modules/services/mlSmMerge.mjs
marklogic-data-hub/src/main/resources/ml-modules/services/mlStepValidate.mjs
marklogic-data-hub/src/main/resources/ml-modules/transforms/hubAllDataSearchTransform.mjs
marklogic-data-hub/src/main/resources/ml-modules/transforms/hubDownloadDocument.mjs
marklogic-data-hub/src/main/resources/ml-modules/transforms/hubEntitySearchTransform.mjs
marklogic-data-hub/src/main/resources/ml-modules/transforms/mlGenerateFunctionMetadata.mjs
marklogic-data-hub/src/main/resources/ml-modules/transforms/mlJobSearchResults.mjs
marklogic-data-hub/src/main/resources/ml-modules/transforms/mlRunIngest.mjs
marklogic-data-hub/src/main/resources/ml-modules/transforms/mlSjsInputFlow.mjs
marklogic-data-hub/src/main/resources/ml-modules/transforms/mlTraceSearchResults.mjs

DHFPROD-9751: Convert services and transform to JavaScript Module (mjs)

---

marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.module.scss

DHFPROD-9739: Buttons with wrong position

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/graphValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyConceptClassesInModeling.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenario2.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenarioModeling.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/fixtures/config/hubCentral.json
marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
marklogic-data-hub-central/ui/src/pages/Modeling.tsx

DHFPROD-9661: Relationships with structured props missing from the model

---

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.hub/config.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/datahub-singleton.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/datahub.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/common.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matcher.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/merger.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/provenance/prov-lib.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/provenance/provenanceWriteQueue.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/security/describe-lib.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/system/system-lib.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/temporal/hub-temporal.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/transforms/mlcp-flow-transform.mjs

DHFPROD-9752: Convert datahub 5 directory to JavaScript Module (mjs)

---

marklogic-data-hub-central/ui/src/components/search-pagination-simple/search-pagination-simple.test.tsx
marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.test.tsx
marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.tsx
marklogic-data-hub-central/ui/src/components/search-summary/search-summary.test.tsx
marklogic-data-hub-central/ui/src/components/search-summary/search-summary.tsx

DHFPROD-9618: Migrate to RTL - search

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs

DHFPROD-9655: Do not show archived items in graph

---

marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphGroupNodes.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/graph-explore-side-panel.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx

DHFPROD-9776: Wrong behavior on selecting all Concepts after search

---

Jenkinsfile
marklogic-data-hub-central/ui/e2e/cypress.config.js
marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/addCustomStepToFlow.cy.tsx

DHFPROD-9694: Investigating nightly upgrade issue

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/relatedEntityMapping.cy.tsx

DHFPROD-9760: Fix failures on nightly - cypress-win-chrome

---

marklogic-data-hub-central/ui/package-lock.json
marklogic-data-hub-central/ui/package.json
marklogic-data-hub-central/ui/src/components/detail-header/detail-header.test.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/footer/footer.test.tsx
marklogic-data-hub-central/ui/src/components/json-view/json-view.test.tsx
marklogic-data-hub-central/ui/src/components/table-view/table-view.test.tsx
marklogic-data-hub-central/ui/src/pages/Login.test.tsx
marklogic-data-hub-central/ui/src/setupTests.ts

DHFPROD-9619: Migrate to RTL - misc

---

Jenkinsfile
marklogic-data-hub-central/ui/e2e/cypress.config.js

DHFPROD-9782: Fix the nightly build failure

---

marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.module.scss
marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.module.scss

DHFPROD-9738: Buttons in modal out of the screen

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/relatedEntityMapping.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/entitiesSidepanel.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/viewNavigation.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx

DHFPROD-9783: Forcing click when switching view in Explore.

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/EntityManagerImpl.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-validate-trigger-lib.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy
marklogic-data-hub/src/test/java/com/marklogic/hub/entity/EntityManagerTest.java
marklogic-data-hub/src/test/resources/invalid/entities/testModel.entity.json

DHFPROD-9697: Surface invalid model messages in mlLoadModules

---

marklogic-data-hub-central/ui/src/pages/Overview.test.tsx
marklogic-data-hub-central/ui/src/pages/Overview.tsx

DHFPROD-7296: Home Page: Links not Keyboard Accessible

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyConceptClassesInModeling.cy.tsx

DHFPROD-9329 Creating/Deleting relationship
```diff
```
- ##### Owner:

DHFPROD-9333: Problem deleting concept class and relationship

---

marklogic-data-hub-central/ui/e2e/package-lock.json
marklogic-data-hub-central/ui/e2e/package.json

DHFPROD-9737: Fix Git Security Vulnerabilities in E2E

---

marklogic-data-hub/src/test/java/com/marklogic/hub/mlcp/MlcpRunner.java
marklogic-data-hub/src/test/java/com/marklogic/hub/mlcp/ProcessRunner.java

DHFPROD-8779: Fix MLCP argument length issue

---

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx
marklogic-data-hub-central/ui/src/components/common/hc-tooltip/hc-tooltip.test.tsx
marklogic-data-hub-central/ui/src/components/common/hc-tooltip/hc-tooltip.tsx
marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.test.tsx
marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.test.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx
marklogic-data-hub-central/ui/src/components/header/system-info/system-info.test.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.test.tsx
marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx
marklogic-data-hub-central/ui/src/util/common-utils.tsx

DHFPROD-8360: Add Lag to All Tooltips

---

marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.tsx

DHFPROD-9708: Error Validation For Create New List

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mappingWithCustomHeader.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphFocusDefocusCluster.cy.tsx

DHFPROD-9786: Fix intermittent failures on nightly

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs

DHFPROD-9592: Fix default label in expore graph

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.scss
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx
marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
marklogic-data-hub-central/ui/src/theme/HCUtils.scss

DHFPROD-9536: Multi Match in the Notification Merge View

---

marklogic-data-hub-central/ui/src/assets/mock-data/curation/curation-context-mock.js
marklogic-data-hub-central/ui/src/assets/mock-data/explore/model-mock.js
marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling-context-mock.ts
marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx
marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.test.tsx
marklogic-data-hub-central/ui/src/components/common/hc-card/hc-card.test.tsx
marklogic-data-hub-central/ui/src/components/common/hc-card/hc-card.tsx
marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.test.tsx
marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.test.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/load/create-edit-load/create-edit-load.test.tsx
marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx
marklogic-data-hub-central/ui/src/components/table-view/table-view.test.tsx
marklogic-data-hub-central/ui/src/pages/Browse.test.tsx
marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx

Fix Git Security Vulnerabilities Group 4
```diff
```
- ##### Owner:

DHFPROD-9774: Fix Git Security Vulnerabilities Group 4

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx

DHFPROD-9709: Tooltip in Values to Ignore Menu

---

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/source-navigation/source-navigation.module.scss

DHFPROD-8647: Source documents navigation buttons are misplaced

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyConceptClassesInModeling.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/concept-class-modal.tsx

DHFPROD-9665: Add tests to validate entities and concepts with different special characters

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/verifyConceptsInExplore.cy.tsx

DHFPROD-9645: Graph validate, turns on/off concept

---

marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx
marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx
marklogic-data-hub-central/ui/src/components/common/hc-button/hc-button.scss
marklogic-data-hub-central/ui/src/components/common/hc-button/hc-button.tsx
marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.tsx
marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.test.tsx
marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.tsx
marklogic-data-hub-central/ui/src/components/monitor-selected-facets/monitor-selected-facets.test.tsx
marklogic-data-hub-central/ui/src/components/monitor-selected-facets/monitor-selected-facets.tsx
marklogic-data-hub-central/ui/src/components/monitor-sidebar/monitor-sidebar.tsx
marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.tsx
marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.tsx

DHFPROD-7311: Monitor Facets: Keyboard Nav

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/addMatchStepToFlow.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/addMergeStepToFlow.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-9013: Validate adding Match and Merge configuration to multiple flows

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MatchingStepController.java
marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MatchingStepControllerTest.java
marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ArtifactService.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/deleteArtifact.api
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/artifacts/deleteArtifact.sjs

DHFPROD-9799: back-end delete exclusion list

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/entitySettings.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/graphValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreUnmerge.spec.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/common/multi-slider.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx
marklogic-data-hub-central/ui/e2e/package.json

DHFPROD-9812: Enhancements to Cypress tests

---

marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.module.scss
marklogic-data-hub-central/ui/src/components/expand-collapse/expand-collapse.module.scss
marklogic-data-hub-central/ui/src/components/expand-collapse/expand-collapse.tsx
marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.module.scss
marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx
marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.module.scss
marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.module.scss
marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.tsx
marklogic-data-hub-central/ui/src/pages/Monitor.module.scss
marklogic-data-hub-central/ui/src/pages/Monitor.tsx

DHFPROD-9117: Monitor Table: Keyboard Nav

---

marklogic-data-hub-central/ui/src/components/header/system-info/system-info.module.scss
marklogic-data-hub-central/ui/src/components/header/system-info/system-info.tsx
marklogic-data-hub-central/ui/src/config/react-select-theme.config.ts

DHFPROD-5800: Info Popup: Missing keyboard nav to copy functionality

---

marklogic-data-hub-central/ui/package-lock.json
marklogic-data-hub-central/ui/package.json

DHFPROD-9809: Fix Critical non-dependent Git Security Vulnerabilities

---

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MatchingStepControllerTest.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.sjs

DHFPROD-9797: Allow artifacts to be renamed

---

marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.tsx

DHFPROD-9823: Issue opening the compare value modal in the graph view.

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenario2.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-table.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx

DHFPROD-9789: Modeling - Missing nested structured property name

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/exploreUnmerge.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/graphExplore.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/types/explore-graph-nodes.ts

DHFPROD-9815: Move file that is in the wrong place

---

marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx

DHFPROD-8440: Update occurrences of 'property' to 'entity property' in Hub Central

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/doc-permissions.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/mapping.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/protected-collections.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/provenance.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/schema-validation.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/temporal.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/doc-permissions.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/mapping.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/protected-collections.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/provenance.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/schema-validation.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/temporal.mjs

DHFPROD-9553: Skeleton code for new features for artifacts and intances.

---

marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx
marklogic-data-hub-central/ui/src/components/flows/flow-panel/step-card.tsx
marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
marklogic-data-hub-central/ui/src/theme/HCTheme.scss

DHFPROD-5658: Run: Make Step Cards Keyboard Accessible

---

marklogic-data-hub-central/ui/e2e/cypress.config.js
marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mappingWithCustomHeader.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mergeNotification.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/mastering/e2eMasteringflow.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenario2.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx

DHFPROD-9852: Fix latest E2E failures on nightly

---

marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx

DHFPROD-9788: Misalignment in Operator Role Merging Card

---

marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MatchingStepController.java
marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MatchingStepControllerTest.java
marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/StepService.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/getReferences.api
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/getReferences.sjs

DHFPROD-9534: Endpoint to finding exclusion list references

---

marklogic-data-hub-central/ui/src/components/entities/entity-tiles.module.scss
marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx
marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.module.scss

DHFPROD-6741: Curate + Run: Add focus state to expand/collapse component

---

marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.test.tsx
marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx

DHFPROD-9778: Create a map/match/merge step with any collection name

---

marklogic-data-hub-central/ui/src/components/common/switch-view/view-switch.tsx
marklogic-data-hub-central/ui/src/components/load/load-list.scss
marklogic-data-hub-central/ui/src/components/load/load-list.tsx
marklogic-data-hub-central/ui/src/components/steps/steps.tsx

Load Table Not Accessible Using Keyboard
```diff
```
- ##### Owner:

DHFPROD-5654: Load Table Not Accessible Using Keyboard

---

marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.tsx
marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/entity-display-settings/entity-display-settings.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx

DHFPROD-9832: Entity Explore Settings e2e Error

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx
marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts
marklogic-data-hub-central/ui/src/api/matching.ts
marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx

DHFPROD-9750: Use real data for Create, Edit and copy lists

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/data-model-display-settings-modal.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx
marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.tsx
marklogic-data-hub-central/ui/src/components/common/hc-popover-search/hc-popover-search.test.tsx
marklogic-data-hub-central/ui/src/components/common/hc-popover-search/hc-popover-search.tsx
marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss
marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.test.tsx
marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/entity-settings/entity-settings.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.scss
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx
marklogic-data-hub-central/ui/src/components/expand-collapse/expand-collapse.tsx
marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.tsx
marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/entity-display-settings/entity-display-settings.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx

- Test plan for this story here: https://project.marklogic.com/jira/browse/DHFPROD-5710
- Includes minor e2e fix for https://project.marklogic.com/jira/browse/DHFPROD-9832
```diff
```
- ##### Owner:

DHFPROD-5710: Mapping: Keyboard Navigation

---

marklogic-data-hub-central/ui/src/pages/Modeling.tsx

DHFPROD-9732: State is retained even after deleting entity

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/crudQueriesFromManageQueries.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphLeafNodes.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/jsonOtherValidations.cy.tsx
marklogic-data-hub-central/ui/src/App.scss
marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.module.scss
marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx
marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.scss
marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.tsx
marklogic-data-hub-central/ui/src/components/common/hc-sider/hc-sider.tsx
marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.tsx
marklogic-data-hub-central/ui/src/components/facet/facet-name.tsx
marklogic-data-hub-central/ui/src/components/facet/facet.test.tsx
marklogic-data-hub-central/ui/src/components/facet/facet.tsx
marklogic-data-hub-central/ui/src/components/queries/queries.tsx
marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx
marklogic-data-hub-central/ui/src/components/related-concepts-facet/related-concepts-facet.tsx
marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.test.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
marklogic-data-hub-central/ui/src/config/react-select-theme.config.ts

DHFPROD-8074: Keyboard accessibility for Sidebar of Explorer

---

marklogic-data-hub-central/ui/src/components/common/switch-view/view-switch.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.tsx
marklogic-data-hub-central/ui/src/components/query-export/query-export.tsx
marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx
marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx
marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx
marklogic-data-hub-central/ui/src/pages/Browse.tsx
marklogic-data-hub-central/ui/src/pages/Detail.tsx

DHFPROD-5711: Explore: Make Explore Results Area Keyboard Accessible

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/exploreViewSelector.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx
marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
marklogic-data-hub-central/ui/src/components/search-result/search-result.test.tsx
marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx
marklogic-data-hub-central/ui/src/components/search-results/search-results.tsx
marklogic-data-hub-central/ui/src/types/entity-types.ts
marklogic-data-hub-central/ui/src/types/view-types.ts

DHFPROD-9255: Retain State on Explore expanded table and snippet view

---

marklogic-data-hub-central/ui/src/components/common/hc-card/hc-card.module.scss

DHFPROD-9860: Align the size of the components displayed on curate

---

marklogic-data-hub-central/ui/e2e/package.json

DHFPROD-9115: Installing Sorry Cypress for Parallel testing

---

marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx

NOTE: tests are going to be manual
```diff
```
- ##### Owner:

DHFPROD-5660: Keyboard accessibility for Side panel of Explorer Graph

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.tsx
marklogic-data-hub-central/ui/src/util/test-utils.tsx

DHFPROD-9811: Additional Error Validation For Create New List

---

Jenkinsfile

DHFPROD-9891: removing community edition stage

---

Jenkinsfile
marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mergeUnmergePrivileges.cy.tsx

DHFPROD-9895: Fix 5.8/develop nightly build after Cypress upgrade

---

marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.tsx

DHFPROD-9793: Weird behavior when tooltip is opened

---

marklogic-data-hub-central/ui/src/components/column-selector/column-selector.tsx
marklogic-data-hub-central/ui/src/components/detail-page-non-entity/detail-page-non-entity.tsx
marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx
marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx

…keyboard
```diff
```
- ##### Owner:

DHFPROD-8101: List of relationships at record view is accessible via keyboard

---

marklogic-data-hub-central/ui/src/components/common/entity-type-color-picker/entity-type-color-picker.tsx
marklogic-data-hub-central/ui/src/components/common/hc-icon-picker/hc-icon-picker.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.module.scss
marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx

Accesing Forms Using Keyboard In Model Tile
```diff
```
- ##### Owner:

DHFPROD-8388: Accesing Forms Using Keyboard In Model Tile

---

marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.test.tsx
marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx
marklogic-data-hub-central/ui/src/components/sidebar-footer/sidebar-footer.tsx

DHFPROD-9853: Facet Selection is not retaining selection

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mappingWithInterceptorsAndCustomHook.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/load/ingestionForAllFiletypes.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/login/authorization.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/persistence/persistence.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx

DHFPROD-9896: Fix intermittent failures on nightly

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/addCustomStepToFlow.cy.tsx
marklogic-data-hub-central/ui/src/components/entities/entity-tiles.module.scss
marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx
marklogic-data-hub-central/ui/src/pages/Curate.test.tsx
marklogic-data-hub-central/ui/src/pages/Curate.tsx

DHFPROD-9839: Add Spinner to Curate Tile

---

Jenkinsfile

DHFPROD-9898: Increase timeout on 10.0.9

---

marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/entitySearch/GetRecordTest.java
marklogic-data-hub/src/test/resources/test-projects/provenance-test/flows/inline.flow.json

DHFPROD-9813: Core test failure Provenance - Get more info

---

marklogic-data-hub-central/ui/src/components/header/header.tsx
marklogic-data-hub-central/ui/src/pages/Run.tsx

Header Keyboard Navigation Is Wrong
```diff
```
- ##### Owner:

DHFPROD-9843: Header Keyboard Navigation Is Wrong

---

Jenkinsfile

DHFPROD-9919: Add ML 11.0.0 to nightly build

---

marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.module.scss
marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.test.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.test.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.module.scss
marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx

DHFPROD-7310: Merge: Keyboard Accessibility

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/viewNavigation.cy.tsx
marklogic-data-hub-central/ui/src/components/common/hc-alert/hc-alert.module.scss
marklogic-data-hub-central/ui/src/components/common/hc-alert/hc-alert.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.tsx
marklogic-data-hub-central/ui/src/services/user-preferences.tsx

DHFPROD-9842: Make Explore Stabilization Message Dismissable

---

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss

DHFPROD-9899: Possible Combinations of Matched Rulesets container wont expand

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs

```diff
```
- ##### Owner:
- N/A Added to Release Wiki (In 5.8.1 release notes)

DHFPROD-9767: Add limit to SPARQL query to reduce memory consumption

---

marklogic-data-hub-central/ui/src/components/common/hc-select/hc-select.tsx
marklogic-data-hub-central/ui/src/components/common/hc-tag/hc-tag.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.scss
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.test.tsx
marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.module.scss
marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx

DHFPROD-7309: Match Keyboard Accessibility

---

marklogic-data-hub-central/ui/src/components/common/hc-card/hc-card.module.scss
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.module.scss

DHFPROD-9938: Clear Data Boxes are shrinked

---

marklogic-data-hub-central/ui/package-lock.json

DHFPROD-9920: Github HIGH vulnerabilities

---

marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx

DHFPROD-9928: Editing a Rs using struct props creates a new rs

---

marklogic-data-hub-central/ui/package.json
marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.module.scss

DHFPROD-9930: Unable to select property

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/jsonTableViewValidations.cy.tsx
marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
marklogic-data-hub-central/ui/src/util/data-conversion.tsx

DHFPROD-9922: Limit Table Width in Explore

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mergeNotification.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/run/runFlow.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/compare-values-modal.tsx
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/MasteringManagerImpl.java
marklogic-data-hub/src/main/resources/ml-modules/services/mlSmMerge.sjs

DHFPROD-9849: Use preview param to not write merge preview

---

marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/DeployUserAmpsTest.java

DHFPROD-9937: Fix amp test version check

---

marklogic-data-hub-central/ui/package-lock.json

DHFPROD-9945: Palamida readable stream

---

marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/ConceptService.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/mapping.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/mapping.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/protected-collections.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/mapping/setup.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/mapping/test-data/entities/Customer.entity.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/mapping/test-data/steps/mapping/MappingFeatureStep.step.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/mapping/testMapping.sjs

DHFPROD-9450: Add Mapping to Artifact Events

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchWithConfigProperties.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/customer%20without%20id.json

DHFPROD-9933: Decode URIs for graph

---

marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.scss
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx

Unmerge Modal Column Order
```diff
```
- ##### Owner:

DHFPROD-9900: Unmerge Modal Column Order

---

marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx

Export Table Modal In Explore View Overflowed
```diff
```
- ##### Owner:

DHFPROD-9926: Export Table Modal In Explore View Overflowed

---

marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx

Export Table Modal In Explore ViewOverflowed
```diff
```
- ##### Owner:

DHFPROD-9926: Export Table Modal In Explore ViewOverflowed

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/finishStep.mjs

DHFPROD-9869: Update Java core tests to work with mjs files

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphSidePanel.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
marklogic-data-hub-central/ui/src/pages/Browse.tsx

DHFPROD-9936: Facet Selection is not retaining collection facet selection

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/mappable-entity-lib.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getEntitiesForMapping/test-data/entities/Order.entity.json

DHFPROD-9957: Allow entity with missing structured prop definition

---

marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelTest.java
marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/PublishModelsTest.java
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenario1.cy.tsx
marklogic-data-hub-central/ui/src/api/modeling.ts
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.scss
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx
marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
marklogic-data-hub-central/ui/src/pages/Modeling.tsx
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/createDraftModel.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateDraftModelInfo.sjs

DHFPROD-9943: Hide entity versioning

---

marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.scss
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/record-view/record-view.test.tsx
marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx

DHFPROD-9946: Multi Match Error in All Data Card View

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matchWarnings.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mergeNotification.cy.tsx
marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx
marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx
marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-target-collections.tsx
marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.test.tsx
marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx

DHFPROD-8389: Create/Edit Step Keyboard Navigation

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.mjs

DHFPROD-9754: fix particular test

---

Jenkinsfile

DHFPROD-9969: Stop hub central systemd service before running tests

---

marklogic-data-hub/src/test/resources/test-projects/temporal-test/modules/root/custom-modules/custom/temporal-step/main.sjs

DHFPROD-9754: change import

---

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunCustomStepTest.java
marklogic-data-hub/src/test/resources/test-projects/temporal-test/modules/root/custom-modules/custom/temporal-step/main.sjs

DHFPROD-9754: adjust some tests

---

marklogic-data-hub-central/ui/e2e/cypress.config.js
marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/run/runFlow.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphLeafNodes.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphSidePanel.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/types/explore-graph-nodes.ts
marklogic-data-hub-central/ui/src/components/flows/flows.tsx
marklogic-data-hub-central/ui/src/components/load/load-card.tsx

DHFPROD-9585: State retention in accordion does not work in flows

---

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.module.scss
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.module.scss
marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.module.scss
marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx
marklogic-data-hub-central/ui/src/components/load/load-card.module.scss
marklogic-data-hub-central/ui/src/components/load/load-card.tsx
marklogic-data-hub-central/ui/src/components/load/load-list.module.scss
marklogic-data-hub-central/ui/src/util/AddTooltipWhenTextOverflow.tsx

DHFPROD-9962: Long name is overflowed in curate merging modal view

---

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FixCreatedByStepTest.java

DHFPROD-9869: Update fixCreatedByStepTest

---

marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/CreateStepTest.java

DHFPROD-9869: adjust test

---

marklogic-data-hub-central/ui/src/assets/mock-data/notification-context-mock.ts
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.module.scss
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.test.tsx
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx
marklogic-data-hub-central/ui/src/util/AddTooltipWhenTextOverflow.tsx

DHFPROD-9941: Merge Notifications Table Alignment

---

marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx

DHFPROD-9931: Values to Ignore Selector: Keyboard Navigation

---

Jenkinsfile

DHFPROD-9969: Stop hub central rpm service

---

examples/reference-entity-model/src/test/ml-modules/root/test/suites/xqueryExample/xquery-test.xqy
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java
marklogic-data-hub/src/main/resources/scaffolding/custom-module/sjs/main-ingestion.sjs
marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/CreateStepDefinitionTest.java
marklogic-data-hub/src/test/resources/step-runner-transactions-test/src/main/ml-modules/root/custom-modules/custom/testTransactionsStep/main.sjs

DHFPROD-9869: Scaffolding adjust

---

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/schemaValidation/setup.xqy

DHFPROD-9449: Adding a reset hub to schema feaure tests

---

marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx

DHFPROD-9940: Clean Strategy Name after discard changes

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx
marklogic-data-hub-central/ui/src/api/matching.ts
marklogic-data-hub-central/ui/src/components/common/hc-facet-indicator/hc-facet-indicator.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
marklogic-data-hub-central/ui/src/components/flows/confirmation-modals.tsx
marklogic-data-hub-central/ui/src/types/curation-types.ts

DHFPROD-9690: Select lists in Values to Ignore Menu, save and delete

---

marklogic-data-hub-client-jar/src/main/java/com/marklogic/hub/clientjar/RunFlowCommand.java
performance-tests/projects/commoncrawl/src/main/hub-internal-config/security/amps/evalInDatabase.json
performance-tests/projects/commoncrawl/src/main/hub-internal-config/security/amps/findProvenance.json
performance-tests/projects/commoncrawl/src/main/hub-internal-config/security/amps/getTemporalCollection.json
performance-tests/projects/commoncrawl/src/main/hub-internal-config/security/amps/updateJob.json

DHFPROD-9869: RunFlowCommand and Performance test

---

marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx
marklogic-data-hub-central/ui/src/pages/Run.tsx
marklogic-data-hub-central/ui/src/types/run-types.ts

Running Flows After Rearrange Doesn´t Work 5.8
```diff
```
- ##### Owner:

DHFPROD-9934: Running Flows After Rearrange Doesnt Work Well 5.8

---

marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx
marklogic-data-hub-central/ui/src/pages/Run.tsx
marklogic-data-hub-central/ui/src/types/run-types.ts

Running Flows After Rearranging Doesn't Work Well.
```diff
```
- ##### Owner:

DHFPROD-9934: Running Flows After Rearrange Doesnt Work Well

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/core.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/protectedCollections/test-data/entities/Customer.entity.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/protectedCollections/test-data/steps/mapping/ProtectedCollectionsMapping.step.json

DHFPROD-9583: Invoke onInstancePassToStep.

---

Jenkinsfile

DHFPROD-10012: Stopping hubcentral service before running tests

---

marklogic-data-hub/src/main/java/com/marklogic/hub/FlowManager.java
marklogic-data-hub/src/main/java/com/marklogic/hub/HubProject.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java

DHFPROD-9395: Create latest datahub user artifacts for 4.3.2 flows on hubUpdate

---

marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx

DHFPROD-9961: Add Match Ruleset for Single Property

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphSidePanel.cy.tsx
marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.module.scss
marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx
marklogic-data-hub-central/ui/src/components/related-concepts-facet/related-concepts-facet.module.scss
marklogic-data-hub-central/ui/src/components/related-concepts-facet/related-concepts-facet.tsx
marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.module.scss
marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx
marklogic-data-hub-central/ui/src/util/AddTooltipWhenTextOverflow.tsx

DHFPROD-9958: Wrong icons on explore view side bar

---

marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx

Graph Side Panel Tabs Alignment
```diff
```
- ##### Owner:

DHFPROD-9994: GraphSidePanelTabsAlignment

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/mastering/stepsAndRunFlowValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/editEntityValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-modal.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx
marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx

DHFPROD-10005: Entity modal closes even if there is an error

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/entitiesSidepanel.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/entitySettings.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.test.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx

Adds assertions for the magnifying glass functionality from de Explore page.
```diff
```
- ##### Owner:

DHFPROD-9999: Validate Enhancement on input search in explore page

---

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FixCreatedByStepTest.java

DHFPROD-9869: adjust a particular test

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/load.tsx
marklogic-data-hub-central/ui/src/api/matching.ts
marklogic-data-hub-central/ui/src/components/confirmation-modal/confirmation-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
marklogic-data-hub-central/ui/src/types/common-types.ts

Show References To Default Values List
```diff
```
- ##### Owner:

DHFPROD-9890: Show References To Default Values List

---

marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx

Unmerge With Less Three Count Needs Preview Text
```diff
```
- ##### Owner:

DHFPROD-9995: Unmerge With Less Three Count Needs Preview Text

---

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/schemaValidation/schema-validation.mjs

DHFPROD-9869: adjust one invoke function

---

marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-target-collections.module.scss
marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-target-collections.tsx

DHFPROD-9996: Validate Option to remove colls from a doc in a merge step

---

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/schemaValidation/schema-validation.mjs

DHFPROD-9869: add time for test purposes

---

build.gradle
marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EnvironmentController.java
marklogic-data-hub-central/src/main/resources/application.properties
marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/environment/EnvironmentControllerTest.java
marklogic-data-hub-central/src/test/resources/application-test.properties
marklogic-data-hub-central/ui/src/assets/mock-data/system-info.data.ts
marklogic-data-hub-central/ui/src/components/header/header.tsx
marklogic-data-hub-central/ui/src/components/header/system-info/system-info.test.tsx
marklogic-data-hub-central/ui/src/components/header/system-info/system-info.tsx
marklogic-data-hub-central/ui/src/util/environment.tsx

DHFPROD-9976: Display HubCentral Version

---

marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/schemaValidation/schema-validation.mjs

DHFPROD-9869: schema validation

---

marklogic-data-hub-central/ui/package.json
marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx
marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx
marklogic-data-hub-central/ui/src/components/related-concepts-facet/related-concepts-facet.tsx
marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx
marklogic-data-hub-central/ui/src/util/AddTooltipWhenTextOverflow.tsx

Adds `"linter-format": "npm run prettier-format && npm run lint . -- --fix"` to react scripts
```diff
```
- ##### Owner:

DHFPROD-10032: Unify prettier and ESlint script

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java

DHFPROD-9986: Update Step Options for Ingestion and Custom steps

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/crudQueriesFromManageQueries.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/jsonTableViewValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/pagination.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/queryWithMoreThanOneEntity.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
marklogic-data-hub-central/ui/e2e/hc-qa-project/entities/Person.entity.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/persons/first-name-double-metaphone1.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/persons/first-name-double-metaphone2.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/persons/first-name-synonym1.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/persons/first-name-synonym2.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/persons/last-name-address-reduce1.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/persons/last-name-address-reduce2.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/persons/last-name-dob-custom1.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/persons/last-name-dob-custom2.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/persons/last-name-plus-zip-boost1.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/persons/last-name-plus-zip-boost2.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/persons/last-name-slight-match1.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/persons/last-name-slight-match2.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/persons/ssn-match1.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/json/persons/ssn-match2.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/xml/persons/first-name-double-metaphone1.xml
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/xml/persons/first-name-double-metaphone2.xml
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/xml/persons/first-name-synonym1.xml
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/xml/persons/first-name-synonym2.xml
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/xml/persons/ssn-match1.xml
marklogic-data-hub-central/ui/e2e/hc-qa-project/input/xml/persons/ssn-match2.xml
marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/mapping/mapPersonJSON.step.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/mapping/mapPersonXML.step.json

DHFPROD-9918: Add boolean data to Person and test table boolean values
```diff
```
- ##### Owner:

DHFPROD-9918: Add boolean data to Person and test table boolean values

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphEntitiesSettings.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphLeafNodes.cy.tsx
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/entitiesWithConceptsTypes.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/getEntitiesTypesWithRelatedConceptsTypes.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchFacets.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchWithConfigProperties.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/nodeExpand.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/test-data/entities/Purchase.entity.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/testSchemaGeneration.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/verifyTdeContext.xqy

DHFPROD-9767: Replace all value generated key refs with expression

---

marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.module.scss
marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx

DHFPROD-9236: Add Icon To Column Header On Nested Properties

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/mastering/stepsAndRunFlowValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-10021: Fix e2e scenario where steps are added in different flows

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphSidePanel.cy.tsx
marklogic-data-hub-central/ui/e2e/package-lock.json
marklogic-data-hub-central/ui/package-lock.json
marklogic-data-hub-central/ui/package.json

DHFPROD-10023: Latest security vulnerability fixes

---

examples/README.md
examples/SLED/build.gradle
examples/dh-5-example/build.gradle
examples/dhf5-custom-hook/build.gradle
examples/insurance/build.gradle
examples/mapping-example/build.gradle
examples/patient-hub/build.gradle
examples/reference-entity-model/build.gradle
examples/smart-mastering-complete/build.gradle
examples/snapshot-testing/build.gradle
examples/step-interceptors/build.gradle
gradle.properties
marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java
marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json
marklogic-data-hub/src/main/resources/scaffolding/build_gradle
performance-tests/projects/commoncrawl/build.gradle

DEVO-774: Updating the version to 5.8.1

---

Jenkinsfile

DEVO-766: Copying the logs from container

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/relationsBetweenEntities.cy.tsx

DHFPROD-10020: SPIKE: Be able to test drag and drop with cypress

---

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx

Added "Custom Function" link to XPath tooltip
```diff
```
- ##### Owner:

DHFPROD-8426: Reword XPath tooltip in Curate screen

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/relationsBetweenEntities.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-vis.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx

DHFPROD-10003: Validate truncation for long names in the relationship between entities and concepts

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/run/runFlow.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx

Adds the scenarios from the ticket.
It also fixes a bug where some of the accordions from the run page opened after running any flow.
```diff
```
- ##### Owner:

DHFPROD-10001: Validate Run flow follow the order of the steps

---

marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
marklogic-data-hub-central/ui/src/util/date-conversion.tsx

DHFPROD-10066: Run Flow Modal Timer Should Be Live

---

marklogic-data-hub-central/ui/package-lock.json

DHFPROD-10023: Latest security vulnerability fixes pt. 2

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowProvenance.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/provenance/provenance.mjs

DHFPROD-9451: adjust Provenance

---

marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/test-data/content/CustMatchMerge1.json

DHFPROD-10085: unmerge when single document left in merged document

---

Jenkinsfile
installer-for-dhs/build.gradle
marklogic-data-hub-api/build.gradle
marklogic-data-hub-central/build.gradle
marklogic-data-hub-client-jar/build.gradle
marklogic-data-hub-junit5/build.gradle
marklogic-data-hub-test/build.gradle
marklogic-data-hub/build.gradle
marklogic-data-hub/src/test/java/com/marklogic/hub/mlcp/MlcpRunner.java

DHFPROD-10074: Stabilize MJS tests in nightly regressions

---

ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/SslTest.groovy
ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/TlsTest.groovy

DHFPROD-10092: Remove Legacy Task Calls from SSL/TLS Tests

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collectorLib.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/core.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/protected-collections.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/temporal.mjs

DHFPROD-10017: Integrate onBuildInstanceQuery

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/crudQueriesfromExplore.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/detailRelationshipsTab.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphSidePanel.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/verifyDataInDatabases.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/persistence/persistence.cy.tsx
marklogic-data-hub-central/ui/src/util/search-context.tsx

DHFPROD-10058: Search in Explore disappears when switching between database tabs

---

marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.test.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx
marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js

DHFPROD-10026: Extra nodes in Graph View when using latest SLED Project

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchFacets.mjs

DHFPROD-10050: Show all relevant for a search query

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mergeWarnings.cy.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss
marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx

DHFPROD-10067: Mapping Table Tooltips Need to Disappear on Blur

---

Jenkinsfile
marklogic-data-hub/src/main/resources/hub-internal-config/security/amps/requireFunction.json
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.mjs
marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java
marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/customStep/CreateAndUpdateCustomStepTest.java
marklogic-data-hub/src/test/java/com/marklogic/hub/flow/impl/RunFlowWithStemmingEnabledTest.java
marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubCommonTest.java
marklogic-data-hub/src/test/java/com/marklogic/hub/test/HubConfigInterceptor.java
marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java

DHFPROD-10074: Additional checks for borrowing hub configs

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/stepExecutionContext.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/core/models/entityModel.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/features-util.mjs

DHFPROD-9702: Getting features from step or model.

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FlowManagerImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/StepDefinitionManagerImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/Versions.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/dhf.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/dhf.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/flow-lib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/trace-lib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/trace-lib.xqy
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java
marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/CreateStepTest.java

Saving flow only locally
```diff
```
- ##### Owner:

DHFPROD-9988: Deprecate 4.x Trace library for upgraded flows

---

Jenkinsfile

DHFPROD-10134: Use ML 10.0-10 in CI/CD pipeline

---

Jenkinsfile

DEVO-780: Updating the stage to get 11 nightlies

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java

DHFPROD-9650: Sort steps in upgraded flow by step type

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mergeNotification.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mergeWarnings.cy.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.module.scss
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx

```diff
```
- ##### Owner:
- [ n/a] Added to Release Wiki

DHFPROD-10116: Flickering of Larger Tooltips

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java
marklogic-data-hub/src/main/resources/scaffolding/custom-module/mjs/main-custom-legacy-upgrade.mjs
marklogic-data-hub/src/main/resources/scaffolding/custom-module/mjs/main-custom.mjs
marklogic-data-hub/src/main/resources/scaffolding/custom-module/mjs/main-ingestion-legacy-upgrade.mjs
marklogic-data-hub/src/main/resources/scaffolding/custom-module/mjs/main-ingestion.mjs
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java
marklogic-data-hub/src/test/java/com/marklogic/hub/scaffolding/CreateStepDefinitionTest.java
marklogic-data-hub/src/test/resources/log4j2.properties

DHFPROD-9407: Custom Module for Upgraded Ingestion and Custom Step

---

Jenkinsfile

DHFPROD-10134 : Updating Jenkins File with 11.0.2 and 10.0-Nightly

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx

DHFPROD-10119: Matching Step Details Incorrect Column Ordering

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/match/entityDrivenMatches.mjs

DHFPROD-9959: Tests for fuzzy match with reduce

---

NOTICE.txt
marklogic-data-hub-central/NOTICE.txt
marklogic-data-hub-spark-connector/NOTICE.txt

OLD:
https://jenkins.marklogic.com/view/Security_Palamida/job/palamida-branch-dhf/18/artifact/ML-DHF-REPORT_on_DHFPROD-10122.json/*view*/
vs
NEW:
https://jenkins.marklogic.com/view/Security_Palamida/job/palamida-branch-dhf/19/artifact/ML-DHF-REPORT_on_DHFPROD-10122.json/*view*/
The vulnerabilities are at the bottom of the json file under "vulnerabilities". If you check the link you would notice there's none.
```diff
```
- ##### Owner:

DHFPROD-10122: Latest Palamida Vulnerabilities Fix

---

Jenkinsfile

DHFPROD-10189: Fixing the 10.0-nightly version

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mergeWarnings.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphEntitiesSettings.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphLeafNodes.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-target-collections.tsx
marklogic-data-hub-central/ui/src/components/common/hc-alert/hc-alert.tsx
marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.test.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx
marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
marklogic-data-hub-central/ui/src/components/steps/steps.tsx

DHFPROD-10144: Stabilize e2e Failures on Pipeline pt.1

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenario2.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-table.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx

DHFPROD-10151: Validate Editing a Structured Property to Another One

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphVerifyTooltipString.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx

DHFPROD-10150: Validate Graph Explore Node Display Labels And On Hover

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/persistence/persistence.cy.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx

DHFPROD-10156: Matching Step Details Selection Retainment~

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/crudQueriesFromManageQueries.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/jsonTableViewValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx

DHFPROD-10118: Make jsonTableViewValidation independent

---

marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.test.tsx
marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.module.scss
marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx

DHFPROD-10155: Size Adjustment on Match Ruleset Modal

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/common/multi-slider.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.tsx
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matcher.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/preview-matching-activity-lib.xqy

DHFPROD-10110: Values to ignore

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/flow-lib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/data-services/stepRunner/processBatch.mjs
marklogic-data-hub/src/main/resources/scaffolding/custom-module/mjs/main-custom-legacy-upgrade.mjs
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java

DHFPROD-9408: Run Legacy Harmonize Flow with collector returning uris

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/DataHubPlugin.groovy
ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/UpdateLegacyFlowsTask.groovy

DHFPROD-9409: gradle task to upgrade legacy flow from 4.3.x

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphEntitiesSettings.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphLeafNodes.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/mastering/e2eMasteringflow.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx

DHFPROD-10259: Fix intermittent Test failures on PRs

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/common.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matcher.mjs

DHFPROD-10257: matching performance changes

---

marklogic-data-hub/src/test/java/com/marklogic/hub/CustomStepE2E.java

DHFPROD-10243: Investigate & fix null pointer exceptions on nightly

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/load/loadPageValidations.cy.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx

DHFPROD-10174: TEST: Editing a load step does not affect other steps

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/crudQueriesfromExplore.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx

DHFPROD-10178: Review skipped test for crudQueriesfromExplore.cy.tsx

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mergeWarnings.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/run/runFlow.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphConceptsSettings.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphEntitiesSettings.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/graphValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/reader.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyConceptClassesInModeling.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx

DHFPROD-10240: check e2e win-chrome failures in the latest chrome version

---

marklogic-data-hub-client-jar/build.gradle

DEVO-800: Publishing client jar to nexus

---

examples/SLED/build.gradle
examples/SLED/flows/Claims.flow.json
examples/SLED/flows/Mastering.flow.json
examples/SLED/steps/matching/matchMemberWithIgnore.step.json
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/valuesToIgnore.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/verifyConceptsInExplore.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/fixtures/input/valuesToIgnore/values-to-ignore1.json
marklogic-data-hub-central/ui/e2e/cypress/fixtures/input/valuesToIgnore/values-to-ignore2.json
marklogic-data-hub-central/ui/e2e/cypress/fixtures/input/valuesToIgnore/values-to-ignore3.json
marklogic-data-hub-central/ui/e2e/cypress/fixtures/input/valuesToIgnore/values-to-ignore4.json
marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/helper.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/graphExplore.tsx
marklogic-data-hub-central/ui/e2e/hc-qa-project/flows/testValuesToIgnore.flow.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/ingestion/loadValuesToIgnore.step.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/mapping/mapForValuesToIgnore.step.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/matching/matchForValuesToIgnore.step.json
marklogic-data-hub-central/ui/e2e/hc-qa-project/steps/merging/mergeForValuesToIgnore.step.json
marklogic-data-hub-central/ui/src/components/load/load-list.tsx
marklogic-data-hub-central/ui/src/components/steps/steps.tsx
marklogic-data-hub-central/ui/src/pages/Detail.tsx
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matcher.mjs

DHFPROD-10089: Adding tests to values to ignore feature. Plus a bug fix.

---

marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx

Adds undefined check to avoid the app to crash. Also fixes some react dev tool warnings (div cannot be child of p and a function being call incorrectly)
```diff
```
- ##### Owner:

DHFPROD-10170: Matching Step Details Compare Error

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/common/multi-slider.tsx
marklogic-data-hub-central/ui/package-lock.json
marklogic-data-hub-central/ui/package.json
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/timeline-vis/timeline-vis.scss

DHFPROD-10203: Address Node Js package vulnerability

---

marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunCustomStepTest.java

DHFPROD-10245: Adding log to track the error

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/crudQueriesfromExplore.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/valuesToIgnore.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/fixtures/input/valuesToIgnore/values-to-ignore3.json
marklogic-data-hub-central/ui/e2e/cypress/fixtures/input/valuesToIgnore/values-to-ignore4.json
marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.tsx

Some e2e was deleted, those are already covered by the unit test
```diff
```
- ##### Owner:

DHFPROD-10239: In values to ignore we want to add spaces to the values

---

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx

DHFPROD-10158: Adjust long names in Thresholds matching

---

marklogic-data-hub-central/ui/src/assets/mock-data/mapping/entityMapTable.ts
marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.test.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
marklogic-data-hub-central/ui/src/util/environment.tsx

DHFPROD-10175: Mapping Link Needs to Use Version

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/entitiesSidepanel.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx

DHFPROD-10173:  Persistence of Related Entities checkboxes in Explore

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/exploreXMLValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphCenterNode.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphLeafNodes.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx

DHFPROD-10180: Review skipped test for exploreXMLValidations.cy.tsx

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/jsonTableViewValidations.cy.tsx

DHFPROD-10183: Fixing skipped test for jsonTableViewValidtion

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/persistence/persistence.cy.tsx

DHFPROD-10186: Fixing skipped persistence test

---

marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/compare-values-modal.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.tsx

DHFPROD-10129: memo on Explore page

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/common.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/merger.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping-functions/general/hubURI.mjs

DHFPROD-10306: Ensure merge isn't attempted on non-existing document

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/queryWithMoreThanOneEntity.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/valuesToIgnore.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/login/authorization.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/relationsBetweenEntities.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenario1.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/fixtures/config/hubCentral.json
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-10292: Fix e2e failures on chrome-nightly

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/relatedEntityMapping.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/login/authorization.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/mastering/e2eMasteringflow.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/mastering/stepsAndRunFlowValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/editEntityValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/entitySettings.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/graphValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/reader.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyConceptClassesInModeling.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyReaderRoleCantPublish.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenario1.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenario2.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenarioGraph.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenarioModeling.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/persistence/persistence.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx

DHFPROD-10310: Fix grapdhValidation intermitent tests

---

marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java

DHFPROD-10243: fix null pointer exceptions customstep2e2

---

marklogic-data-hub/src/main/java/com/marklogic/hub/HubProject.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java
ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/UpdateLegacyFlowsTask.groovy

DHFPROD-10254: Fix NPE when plugins directory doesnt exist on hubUpgradeLegacyFlows

---

marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.tsx

DHFPROD-9982: Entity specific sidebar shows the entities twice

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/flow-lib.sjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils/invoke-queue-write.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/data-services/stepRunner/processBatch.mjs
marklogic-data-hub/src/main/resources/scaffolding/custom-module/mjs/main-custom-legacy-upgrade.mjs
marklogic-data-hub/src/main/resources/scaffolding/custom-module/mjs/main-ingestion-legacy-upgrade.mjs

DHFPROD-9652: Run Legacy Harmonize Flow with collector returning non uris

---

marklogic-data-hub-api/src/main/java/com/marklogic/hub/HubClientConfig.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubConfigImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/FileCollector.java
marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/SourceQueryCollector.java
marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java
marklogic-data-hub/src/main/java/com/marklogic/hub/util/DiskQueue.java
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/HubConfigImplTest.java

DHFPROD-3205: Configure tmpDir and maxInMemorySize in DHF Collector/DiskQueue

---

marklogic-data-hub-central/ui/src/components/record-view/record-view.module.scss
marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx

DHFPROD-10289: Incorrect position of the information modal

---

Jenkinsfile
ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/fullcycle/TlsTest.groovy

DHFPROD-10315: TLS nightly test fix

---

Jenkinsfile

DHFPROD-10322: Fix nightly build to save Chrome and Firefox artifacts

---

Jenkinsfile

DHFPROD-10322: Fix nightly build to save artifacts

---

marklogic-data-hub-central/ui/src/components/search-pagination-simple/search-pagination-simple.test.tsx
marklogic-data-hub-central/ui/src/components/search-pagination-simple/search-pagination-simple.tsx

DHFPROD-10331: Notifications Page Error on Nightly

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/exploreGraphFacetConsistentNavigation.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphEntitiesSettings.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphVerifyTooltipString.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/explore.tsx

DHFPROD-10317: Fix e2e failures on firefox-nightly

---

marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.module.scss
marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.test.tsx
marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx

DHFPROD-10276: FE: Problem exporting rows in explore screen

---

Jenkinsfile

DHFPROD-10322: Fix artifacts in nightly build

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/crudQueriesFromManageQueries.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphLeafNodes.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/persistence/persistence.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-10273: Rewrite logic of monitorTableValidations

---

marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java

DHFPROD-10328: Fix for upgrade core test failure on nightly

---

Jenkinsfile

DHFPROD-10322: Fix artifacts in nightly build-pt2

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/stepDefinition.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/common.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matcher.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matching.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/merger.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/data-services/flow/flow-lib.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/data-services/mapping/generateMappingFunctions.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/public/flow/flow-api.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/transforms/mlcp-flow-transform-lib.mjs
marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunFlowWithWriteErrorTest.java
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.mjs

DHFPROD-10327: Optimize match caching

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx
marklogic-data-hub-central/ui/src/pages/Monitor.tsx

DHFPROD-9157: Unable to sort Entity Type in Monitor Table

---

marklogic-data-hub-central/ui/src/components/modal-status/modal-status.tsx
marklogic-data-hub-central/ui/src/util/user-context.tsx

DHFPROD-10059: Session Timeout popup does not allow to continue session

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collector.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collectorLib.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/temporal/hub-temporal.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/temporal.mjs
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/WriteDocumentsTest.java
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/temporal-operations/suiteSetup.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/temporal-operations/suiteTeardown.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/temporal-operations/temporalMatchTest.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/temporal-operations/test-data/entities/Customer.entity.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/temporal-operations/test-data/flows/CustomerJSON.flow.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/security/temporal-operations/test-data/steps/matching/match-customers.step.json

DHFPROD-8780: Match temporal documents

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/crudQueriesfromExplore.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/relationsBetweenEntities.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/graph-view.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view.tsx

nightly 4529 chrome-firefox
nightly 4523 chrome
```diff
```
- ##### Owner:

DHFPROD-10292: Fix e2e failures on chrome-firefox-nightly

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx

DHFPROD-10337: Fix monitorTableValidations intermitent tests

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/login/authorization.cy.tsx
marklogic-data-hub-central/ui/src/App.tsx
marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.test.tsx
marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
marklogic-data-hub-central/ui/src/components/flows/flows.tsx
marklogic-data-hub-central/ui/src/components/related-concepts-facet/related-concepts-facet.tsx
marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx
marklogic-data-hub-central/ui/src/pages/Browse.tsx
marklogic-data-hub-central/ui/src/pages/Detail.tsx
marklogic-data-hub-central/ui/src/pages/Modeling.tsx
marklogic-data-hub-central/ui/src/pages/TilesView.tsx
marklogic-data-hub-central/ui/src/util/hubCentralConfig-context.tsx

DHFPROD-10120: Implement Reducers for HCConfigContext 

---

marklogic-data-hub-central/ui/e2e/hc-qa-project/src/main/ml-modules/root/custom-modules/custom/generate-dictionary/main.sjs
marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/ScriptStepRunner.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/flowRunner.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/data-services/stepRunner/customWriteInSameDatabase.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/data-services/stepRunner/test-data/custom-with-update.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/data-services/stepRunner/test-data/flows/SimpleFlow.flow.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/data-services/stepRunner/test-data/step-definitions/custom/custom-with-update/custom-with-update.step.json
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/data-services/stepRunner/test-data/steps/custom/customWithUpdate.step.json

DHFPROD-10358: Allow stepUpdate in staging db

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/load/defaultIngestionListView.cy.tsx

DHFPROD-10419: Fix Intermittent test on develop run

---

marklogic-data-hub/src/main/resources/scaffolding/custom-module/mjs/main-ingestion-legacy-upgrade.mjs

DHFPROD-10359: Removing content object created when converting from csv to json/xml

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matching.xqy
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchingFunctionArguments.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/javascriptMatchingFunctions.sjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/xqueryMatchingFunctions.xqy

DHFPROD-10346: Preserve match function signature for QS format

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-validate-trigger-lib.xqy

I manually check all the mentioned scenarios, relationships at the root level and inside structured properties
```diff
```
- ##### Owner:

DHFPROD-10389: BE:Problem creating a relationship

---

examples/SLED/src/main/ml-modules/root/custom-modules/mapping-functions/getHash64.sjs
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.tsx
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/template-generated.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/data-services/graph/nodeExpand.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/data-services/graph/searchNodes.mjs

DHFPROD-10369: Ghost nodes on unmerge

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java
ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/UpdateLegacyFlowsTask.groovy

DHFPROD-10416: Upgarde Subset of  legacy flows

---

examples/README.md
examples/SLED/build.gradle
examples/dh-5-example/build.gradle
examples/dhf5-custom-hook/build.gradle
examples/insurance/build.gradle
examples/mapping-example/build.gradle
examples/patient-hub/build.gradle
examples/reference-entity-model/build.gradle
examples/smart-mastering-complete/build.gradle
examples/snapshot-testing/build.gradle
examples/step-interceptors/build.gradle
gradle.properties
marklogic-data-hub-central/src/main/resources/application.properties
marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java
marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json
marklogic-data-hub/src/main/resources/scaffolding/build_gradle
performance-tests/projects/commoncrawl/build.gradle

DEVO-822: Updating the versions to 6.0.0-rc1

---

examples/SLED/src/main/ml-modules/root/custom-modules/mapping-functions/sledMappingFunctions.sjs

DHFPROD-10048:Update sledMappingFunctions.sjs

---

marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx

DHFPROD-10275:Error on monitor page when flow is running

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/merger.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/core/entiity-services/entity-services-impl.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/schema-validation.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/schemaValidation/schema-validation.mjs

DHFPROD-10439: Fix ES model generated schema

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/core.mjs

```diff
```
- ##### Owner:
- n/a Ran newly added/edited cypress tests on Firefox locally

DHFPROD-10453: Adding features to step context.

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matchWarnings.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/viewNavigation.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/login/authorization.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/mastering/e2eMasteringflow.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/mastering/stepsAndRunFlowValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/relationsBetweenEntities.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx

DHFPROD-10395: Fix e2e failures on 11-Nightly-linux-On-Prem

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/crudQueriesFromManageQueries.cy.tsx

DHFPROD-10496: Fix e2e failure on nightly

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/persistence/persistence.cy.tsx
marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
marklogic-data-hub-central/ui/src/pages/Browse.tsx
marklogic-data-hub-central/ui/src/util/search-context.tsx

DHFPROD-10423: Explore view doesn't retain the search after loading data

---

marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx

DHFPROD-10396: Undefined error on Run screen

---

examples/reference-entity-model/gradle-cloud.properties
marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/ConfigureAppServerBasePaths.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java

DHFPROD-10454: Appservice Basepath Configurations

---

marklogic-data-hub-central/ui/src/assets/mock-data/monitor/facet-props.js
marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.test.tsx
marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.tsx

DHFPROD-10431: Missing text on monitor when step is running

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.mjs

```diff
```
- ##### Owner:
- n/a Ran newly added/edited cypress tests on Firefox locally

DHFPROD-10445: Cleaning up ghost nodes

---

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss
marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/page-header/page-header.tsx

DHFPROD-10420: Items misplaced in mapping step details on Firefox

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/mastering/stepsAndRunFlowValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
marklogic-data-hub-central/ui/e2e/cypress/support/components/common/confirmation-modal.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx

DHFPROD-10514: Fix failures in develop - Run 4067

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/mastering/e2eMasteringflow.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx

DHFPROD-10438: Validate auditing and notification collections

---

marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx

DHFPROD-10511: UI issues with graph nodes in latest sled project

---

marklogic-data-hub/src/test/java/com/marklogic/hub/integrationTest/IntegrationStep.java
marklogic-data-hub/src/test/resources/integration-test/entities/Customer.entity.json
marklogic-data-hub/src/test/resources/integration-test/flows/CurateCustomerJSON.flow.json
marklogic-data-hub/src/test/resources/integration-test/flows/CurateCustomerSmallBatchJSON.flow.json
marklogic-data-hub/src/test/resources/integration-test/flows/CurateCustomerXML.flow.json
marklogic-data-hub/src/test/resources/integration-test/input/json/CustIntegration1.json
marklogic-data-hub/src/test/resources/integration-test/input/json/CustIntegration2.json
marklogic-data-hub/src/test/resources/integration-test/input/json/CustIntegration3.json
marklogic-data-hub/src/test/resources/integration-test/input/json/CustIntegration4.json
marklogic-data-hub/src/test/resources/integration-test/input/json/CustIntegration5-merge.json
marklogic-data-hub/src/test/resources/integration-test/input/json/CustIntegration5.json
marklogic-data-hub/src/test/resources/integration-test/input/xml/CustIntegrationXMLDoc1.xml
marklogic-data-hub/src/test/resources/integration-test/input/xml/CustIntegrationXMLDoc2.xml
marklogic-data-hub/src/test/resources/integration-test/input/xml/CustIntegrationXMLDoc3.xml
marklogic-data-hub/src/test/resources/integration-test/input/xml/CustIntegrationXMLDoc4.xml
marklogic-data-hub/src/test/resources/integration-test/input/xml/CustIntegrationXMLDoc5.xml
marklogic-data-hub/src/test/resources/integration-test/modules/root/custom-modules/custom/integration-step/collectionAdder.sjs
marklogic-data-hub/src/test/resources/integration-test/step-definitions/custom/collectionAdder/collectionAdder.step.json
marklogic-data-hub/src/test/resources/integration-test/steps/custom/collectionAdder.step.json
marklogic-data-hub/src/test/resources/integration-test/steps/ingestion/loadCustomersJSON.step.json
marklogic-data-hub/src/test/resources/integration-test/steps/ingestion/loadCustomersJSONSmallBatchSize.step.json
marklogic-data-hub/src/test/resources/integration-test/steps/ingestion/loadCustomersXML.step.json
marklogic-data-hub/src/test/resources/integration-test/steps/mapping/mapCustomersJSON.step.json
marklogic-data-hub/src/test/resources/integration-test/steps/mapping/mapCustomersJSONSmallBatchSize.step.json
marklogic-data-hub/src/test/resources/integration-test/steps/mapping/mapCustomersXML.step.json
marklogic-data-hub/src/test/resources/integration-test/steps/matching/match-customers.step.json
marklogic-data-hub/src/test/resources/integration-test/steps/merging/merge-customers.step.json

DHFPROD-10202: Integration tests to cover different scenarios

---

marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss
marklogic-data-hub-central/ui/src/components/related-concepts-facet/related-concepts-facet.tsx
marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx

DHFPROD-10417: Related concepts in the explore side panel is not working

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx

DHFPROD-10528: Fix Monitor Failures

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/mastering/e2eMasteringflow.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/persistence/persistence.cy.tsx

DHFPROD-10544: Fix intermittent Test failures on nightly

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/flow-lib.xqy
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils/invoke-queue-write.mjs
marklogic-data-hub/src/main/resources/scaffolding/custom-module/mjs/main-ingestion-legacy-upgrade.mjs
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java
marklogic-data-hub/src/test/resources/upgrade-projects/hr-hub/input/Claims/Claim1.xml
marklogic-data-hub/src/test/resources/upgrade-projects/hr-hub/plugins/entities/Employee/harmonize/harmonize-claims/collector.xqy
marklogic-data-hub/src/test/resources/upgrade-projects/hr-hub/plugins/entities/Employee/harmonize/harmonize-claims/content.xqy
marklogic-data-hub/src/test/resources/upgrade-projects/hr-hub/plugins/entities/Employee/harmonize/harmonize-claims/harmonize-claims.properties
marklogic-data-hub/src/test/resources/upgrade-projects/hr-hub/plugins/entities/Employee/harmonize/harmonize-claims/headers.xqy
marklogic-data-hub/src/test/resources/upgrade-projects/hr-hub/plugins/entities/Employee/harmonize/harmonize-claims/main.xqy
marklogic-data-hub/src/test/resources/upgrade-projects/hr-hub/plugins/entities/Employee/harmonize/harmonize-claims/triples.xqy
marklogic-data-hub/src/test/resources/upgrade-projects/hr-hub/plugins/entities/Employee/harmonize/harmonize-claims/writer.xqy
marklogic-data-hub/src/test/resources/upgrade-projects/hr-hub/plugins/entities/Employee/input/input-claims/content.xqy
marklogic-data-hub/src/test/resources/upgrade-projects/hr-hub/plugins/entities/Employee/input/input-claims/headers.xqy
marklogic-data-hub/src/test/resources/upgrade-projects/hr-hub/plugins/entities/Employee/input/input-claims/input-claims.properties
marklogic-data-hub/src/test/resources/upgrade-projects/hr-hub/plugins/entities/Employee/input/input-claims/main.xqy
marklogic-data-hub/src/test/resources/upgrade-projects/hr-hub/plugins/entities/Employee/input/input-claims/triples.xqy

DHFPROD-10506: Allow Xml Strings in upgraded flows source collector

---

marklogic-data-hub/package-lock.json
marklogic-data-hub/package.json

DHFPROD-10382: Address Github security vulnerabilities alerts

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/exploreUnmerge.cy.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx

DHFPROD-10326: Unmerge Confirmation Message Should Vary

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
marklogic-data-hub-central/ui/src/api/matching.ts
marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx
marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.tsx
marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx
marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx
marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.mjs

DHFPROD-10425: Warning when dictionay does not exist.

---

marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling.js
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.test.tsx
marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx
marklogic-data-hub-central/ui/src/pages/Modeling.tsx

Added the fix for the model alert: if the user doesnt have write rights, the alert for modified model wont appear.
```diff
```
- ##### Owner:

DHFPROD-10370: Disable buttons for users without write rights.

---

examples/SLED/src/main/ml-modules/root/custom-modules/custom/generate-dictionary/main.sjs
examples/real-estate/src/main/ml-modules/root/custom-modules/custom/generate-dictionary/main.sjs
examples/smart-mastering-complete/src/main/ml-modules/root/custom-modules/custom/generate-dictionary/main.sjs

```diff
```
- ##### Owner:
- n/a Ran newly added/edited cypress tests on Firefox locally

DHFPROD-10383: Fixing custom sjs files.

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorCustomDatePicker.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx
marklogic-data-hub-central/ui/src/components/monitor-sidebar/monitor-sidebar.tsx

…he selection
```diff
```
- ##### Owner:

DHFPROD-10318: Start Time facet value does not reset after clearing he selection

---

marklogic-data-hub/src/main/resources/scaffolding/custom-module/mjs/main-ingestion-legacy-upgrade.mjs
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java
marklogic-data-hub/src/test/resources/upgrade-projects/hr-hub/plugins/entities/Employee/harmonize/harmonize-claims/writer.xqy

DHFPROD-10506: Upgraded ingest steps retain permissions in steps

---

.github/PULL_REQUEST_TEMPLATE.md

DHFPROD-10569:Update PULL_REQUEST_TEMPLATE.md

---

marklogic-data-hub/src/main/resources/hub-internal-config/security/amps/protectCollections.json
marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-collection-protector.json
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/protected-collections.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/protectedCollections/protected-collections.mjs

DHFPROD-10475: Protected collections feature is creating the collection

---

marklogic-data-hub-central/ui/src/components/flows/flow-panel/step-card.test.tsx
marklogic-data-hub-central/ui/src/components/flows/flow-panel/step-card.tsx
marklogic-data-hub-central/ui/src/pages/Run.tsx

DHFPROD-10274: Step Card in Flow Needs In-Progress Indicator

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java
marklogic-data-hub/src/test/resources/upgrade-projects/dhf43x/plugins/entities/Employee/Employee.entity.json
marklogic-data-hub/src/test/resources/upgrade-projects/dhf43x/plugins/entities/Employee/harmonize/NoProperties/content.sjs
marklogic-data-hub/src/test/resources/upgrade-projects/dhf43x/plugins/entities/Employee/harmonize/NoProperties/headers.sjs
marklogic-data-hub/src/test/resources/upgrade-projects/dhf43x/plugins/entities/Employee/harmonize/NoProperties/main.sjs
marklogic-data-hub/src/test/resources/upgrade-projects/dhf43x/plugins/entities/Employee/harmonize/NoProperties/triples.sjs
marklogic-data-hub/src/test/resources/upgrade-projects/dhf43x/plugins/entities/Employee/harmonize/NoProperties/writer.sjs
ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/UpdateLegacyFlowsTask.groovy

Upgrade changes
```diff
```
- ##### Owner:

DHFPROD-10566: Ignore flow when properties file is missing in legacy flow directory

---

marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss
marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx
marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/main.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mapping/map-multiple-entities/runMappingWithUriExpressionThatEvaluatesToNull.mjs

DHFPROD-10486: BE:Handle Case When Mapping Context is Inapplicable

---

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java

DHFPROD-10566: Make step-defs read database name from hubconfig and renaming variables

---

marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx

```diff
```
- ##### Owner:
- N/A Remove any PII info and customer data
- N/A Review any PII info and customer data

DHFPROD-10577: Update test match preview text

---

marklogic-data-hub-api/src/main/java/com/marklogic/hub/HubClientConfig.java
marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/ConfigureAppServerBasePaths.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java

DHFPROD-10578: Changing waiting strategy for ml cloud gateway restart

---

marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts
marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx

DHFPROD-10528: Fix intermittent failures on Monitor

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils/invoke-queue-write.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/features/temporal/temporal.mjs

```diff
```
- ##### Owner:
- N/A Review any PII info and customer data

DHFPROD-10568: Only include 'latest' when matching temporal docs

---

marklogic-data-hub-central/ui/e2e/cypress/support/commands.js

DHFPROD-10558: Fix Intermittent failures in develop - 4651 run

---

marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/ConfigureAppServerBasePaths.java
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java

DHFPROD-10578: Lazy hubclient object creation

---

marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matcher.mjs
marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/data-services/mastering/previewMatchingActivity.mjs
marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/data-services/mastering/previewMatchingActivity/previewMatchingActivity.mjs

```diff
```
- ##### Owner:
- N/A Remove any PII info and customer data
- N/A Review any PII info and customer data

DHFPROD-10507: in-memory fuzzy match

---

marklogic-data-hub-junit5/build.gradle
marklogic-data-hub/build.gradle

```diff
```
- ##### Owner:
- [N/A] Remove any PII info and customer data
- [N/A] Review any PII info and customer data

DHFPROD-10595: Address Palamida security vulnerabilities - Spring

---

examples/README.md
examples/SLED/build.gradle
examples/dh-5-example/build.gradle
examples/dhf5-custom-hook/build.gradle
examples/insurance/build.gradle
examples/mapping-example/build.gradle
examples/patient-hub/build.gradle
examples/reference-entity-model/build.gradle
examples/smart-mastering-complete/build.gradle
examples/snapshot-testing/build.gradle
examples/step-interceptors/build.gradle
gradle.properties
marklogic-data-hub-central/src/main/resources/application.properties
marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java
marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json
marklogic-data-hub/src/main/resources/scaffolding/build_gradle
performance-tests/projects/commoncrawl/build.gradle

DEVO-747: Updating the version to 6.0.0
